### ISSUE TITLE
Plugin: TETRIS Stats

### ISSUE THREAD

**Issue by shoucandanghehe** [nonebot/nonebot2#1008]
**插件名称：**

TETRIS Stats

**插件功能：**

一个基于nonebot2的用于查询TETRIS相关游戏玩家数据的插件

**PyPI 项目名：**

nonebot-plugin-tetris-stats

**插件 import 包名：**

nonebot_plugin_tetris_stats

**插件项目仓库/主页链接：**

https://github.com/shoucandanghehe/nonebot-plugin-tetris-stats

**标签：**

[{"label":"a:onebot","color":"#da2b2b"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: TETRIS Stats

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:OneBot-#da2b2b</li><li>✅ 项目 <a href="https://github.com/shoucandanghehe/nonebot-plugin-tetris-stats">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tetris-stats/">nonebot-plugin-tetris-stats</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖项中将添加nonebot2，nb-cli作为dev依赖

**Comment by shoucandanghehe** [comment]
> 请在插件依赖项中将添加nonebot2，nb-cli作为dev依赖

已将nb-cli替换为nonebot2
