### ISSUE TITLE
Plugin: B站视频伪分享卡片

### ISSUE THREAD

**Issue by ASTWY** [nonebot/nonebot2#1013]
**插件名称：**

B站视频伪分享卡片

**插件功能：**

将用户发送的B站视频ID转为(伪)分享卡片的形式

**PyPI 项目名：**

nonebot_plugin_bilibili_viode

**插件 import 包名：**

nonebot_plugin_bilibili_viode

**插件项目仓库/主页链接：**

https://github.com/ASTWY/nonebot_plugin_bilibili_viode

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: B站视频伪分享卡片

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ASTWY/nonebot_plugin_bilibili_viode">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_bilibili_viode/">nonebot_plugin_bilibili_viode</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
