### ISSUE TITLE
Plugin: 青年大学习提交（有后台记录）

### ISSUE THREAD

**Issue by ZMXC01** [nonebot/nonebot2#1016]
**插件名称：**

青年大学习提交（有后台记录）

**插件功能：**

利用requests库往相应平台提交个人大学习信息（暂时只适配了部分地区）

**PyPI 项目名：**

nonebot_plugin_botteenstudy

**插件 import 包名：**

nonebot_plugin_botteenstudy

**插件项目仓库/主页链接：**

https://github.com/ZMXC01/nonebot_plugin_botteenstudy

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 青年大学习提交（有后台记录）

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ZMXC01/nonebot_plugin_botteenstudy">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_botteenstudy/">nonebot_plugin_botteenstudy</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
注意不要把.git文件夹包含到插件里上传到pypi。。。
