### ISSUE TITLE
Plugin: 明日方舟工具箱

### ISSUE THREAD

**Issue by NumberSir** [nonebot/nonebot2#1018]
**插件名称：**

明日方舟工具箱

**插件功能：**

简单实现一些有需求的资源查询功能和计算功能

**PyPI 项目名：**

nonebot-plugin-arktools

**插件 import 包名：**

nonebot_plugin_arktools

**插件项目仓库/主页链接：**

https://github.com/NumberSir/nonebot_plugin_arktools

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 明日方舟工具箱

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/NumberSir/nonebot_plugin_arktools">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-arktools/">nonebot-plugin-arktools</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
