### ISSUE TITLE
Plugin: Warframe时间查询

### ISSUE THREAD

**Issue by axStar** [nonebot/nonebot2#1022]
**插件名称：**

Warframe时间查询

**插件功能：**

查询Warframe的平原与地球时间状态

**PyPI 项目名：**

nonebot-plugin-warframe-clock

**插件 import 包名：**

nonebot_plugin_warframe_clock

**插件项目仓库/主页链接：**

https://github.com/axStar/nonebot_plugin_warframe_clock

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"Warframe","color":"#149090"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Warframe时间查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, Warframe-#149090</li><li>✅ 项目 <a href="https://github.com/axStar/nonebot_plugin_warframe_clock">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-warframe-clock/">nonebot-plugin-warframe-clock</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请注意修改一下插件依赖，nb-cli应为dev依赖，deps里应该写`nonebot2`

**Comment by axStar** [comment]
> 请注意修改一下插件依赖，nb-cli应为dev依赖，deps里应该写`nonebot2`
修改了
