### ISSUE TITLE
Plugin: Hikari-战舰世界水表查询

### ISSUE THREAD

**Issue by benx1n** [nonebot/nonebot2#1024]
**插件名称：**

Hikari-战舰世界水表查询

**插件功能：**

顾名思义

**PyPI 项目名：**

hikari-bot

**插件 import 包名：**

hikari_bot

**插件项目仓库/主页链接：**

https://github.com/benx1n/HikariBot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Hikari-战舰世界水表查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/benx1n/HikariBot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/hikari-bot/">hikari-bot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请不要把plugin-gocq作为插件的deps依赖，应该放在dev里
