### ISSUE TITLE
Plugin: 疫情小助手

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#1032]
**插件名称：**

疫情小助手

**插件功能：**

疫情小助手 支持查地区 风险地区 境外输入等

**PyPI 项目名：**

nonebot-plugin-covid-19-by

**插件 import 包名：**

nonebot_plugin_covid_19_by

**插件项目仓库/主页链接：**

https://github.com/bingqiu456/nonebot-plugin-covid-19-by

**标签：**

[{"label":"a:onebot","color":"#52ea8a"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 疫情小助手

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#52ea8a</li><li>✅ 项目 <a href="https://github.com/bingqiu456/nonebot-plugin-covid-19-by">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-covid-19-by/">nonebot-plugin-covid-19-by</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
