### ISSUE TITLE
Plugin: 命令重启机器人

### ISSUE THREAD

**Issue by 18870** [nonebot/nonebot2#1037]
**插件名称：**

命令重启机器人

**插件功能：**

用命令重启你的机器人 /reboot

**PyPI 项目名：**

nonebot-plugin-reboot

**插件 import 包名：**

nonebot_plugin_reboot

**插件项目仓库/主页链接：**

https://github.com/18870/nonebot-plugin-reboot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 命令重启机器人

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/18870/nonebot-plugin-reboot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-reboot/">nonebot-plugin-reboot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
