### ISSUE TITLE
Question: 关于安装错误的反映

### ISSUE THREAD

**Issue by legiorange** [nonebot/nonebot2#1039]
notebot2是我心目中一个非常适合的轮子，我也认为nonebot2是一个非常强的聊天机器人框架。
但是在安装过程中我浪费了3个多小时，始终停留在：
1：
pip install nb-cli
ERROR: Could not find a version that satisfies the requirement nonebot2
ERROR: No matching distribution found for nonebot2
2：
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'
nb plugin install cqhttp
An error occurred while requesting https://v2.nonebot.dev/plugins.json.
An error occurred while requesting https://fastly.jsdelivr.net/gh/nonebot/non
ebot2/website/static/plugins.json.

我十分期望它能正常使用，因为这些问题以致于我不得不放弃nonebot2。

在能不提Issue就不提的原则下，我只能说，我尽力了。

希望未来nonebot2能带来一个好的使用体验。

**Comment by StarHeartHunt** [comment]
1. 试试换个镜像或直接走 pypi 安装
2. 一般是全局代理污染了 cli 内部 httpx proxy 的配置，取消全局代理可以解决

**Comment by yanyongyu** [comment]
首先，这个问题不是nb2导致的，他的可能原因是
- 你所安装的python版本不符合文档所示条件
- 你使用了一个残缺的pip镜像
- 你的网络存在问题

**Comment by legiorange** [comment]
1.关于镜像问题：
 pip install nb-cli -i https://pypi.org/simple
https://pypi.tuna.tsinghua.edu.cn/simple
https://mirrors.aliyun.com/pypi/simple
等均出现
'
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /pypi/simple/nb-cli/
'
在其他安装包没有该现象，这和yanyongyu所说的存在网络问题完全没有关系，连pypi.org都出现问题，明显不可能是残缺的pip镜像导致的，尝试关闭全局代理以后，和StarHeartHunt反映的一样，出在全局代理上。
关于cqhttp
教程开始里写的是
···
from nonebot.adapters.cqhttp import Bot as CQHTTPBot
···

我尝试一下使用nonebot-adapter-onebot。

**Comment by yanyongyu** [comment]
> 1.关于镜像问题：
>  pip install nb-cli -i https://pypi.org/simple
> https://pypi.tuna.tsinghua.edu.cn/simple
> https://mirrors.aliyun.com/pypi/simple
> 等均出现
> '
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /pypi/simple/nb-cli/
> '

我列出的是所有常见的问题原因可能性，在你这报错明确写着`ProxyError`，即你的网络有问题

**Comment by legiorange** [comment]
感谢两位！
在教程中写的是 nonebot.adapters.cqhttp 以至于我安装该adapter失败，成功安装nb-cli后使用nb create有nonebot.adapters.onebot.v11和nonebot.adapters.onebot.v12的adapter插件是成功的
目前关闭全局代理已经成功安装。
问题解决。

**Comment by yanyongyu** [comment]
> 在教程中写的是 nonebot.adapters.cqhttp

可能你需要查看更新的教程，alpha教程有些落后了，当前beta版本在B站有well404的视频教程等
