### ISSUE TITLE
Plugin: 历史上的今天

### ISSUE THREAD

**Issue by AquamarineCyan** [nonebot/nonebot2#1047]
**插件名称：**

历史上的今天

**插件功能：**

nonebot2历史上的今天

**PyPI 项目名：**

nonebot-plugin-today-in-histroy

**插件 import 包名：**

nonebot_plugin_today_in_histroy

**插件项目仓库/主页链接：**

https://github.com/AquamarineCyan/nonebot-plugin-today-in-histroy

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 历史上的今天

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot-plugin-today-in-histroy/">nonebot-plugin-today-in-histroy</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/AquamarineCyan/nonebot-plugin-today-in-histroy">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
