### ISSUE TITLE
Plugin: 历史上的今天

### ISSUE THREAD

**Issue by AquamarineCyan** [nonebot/nonebot2#1048]
**插件名称：**

历史上的今天

**插件功能：**

nonebot2历史上的今天

**PyPI 项目名：**

nonebot-plugin-today-in-history

**插件 import 包名：**

nonebot_plugin_today_in_history

**插件项目仓库/主页链接：**

https://github.com/AquamarineCyan/nonebot-plugin-today-in-history

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 历史上的今天

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/AquamarineCyan/nonebot-plugin-today-in-history">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-today-in-history/">nonebot-plugin-today-in-history</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请注意插件中不应使用`requests`进行虚假的异步IO（

建议使用httpx代替requests

**Comment by AquamarineCyan** [comment]
> 请注意插件中不应使用`requests`进行虚假的异步IO（
> 
> 建议使用httpx代替requests

已更换发版
