### ISSUE TITLE
Plugin: nonebot_plugin_setu4

### ISSUE THREAD

**Issue by Special-Week** [nonebot/nonebot2#1050]
**插件名称：**

nonebot_plugin_setu4

**插件功能：**

内置数据库的色图插件, 尝试减小发不出图片的概率

**PyPI 项目名：**

nonebot-plugin-setu4

**插件 import 包名：**

nonebot_plugin_setu4

**插件项目仓库/主页链接：**

https://github.com/Special-Week/nonebot_plugin_setu4

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_setu4

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Special-Week/nonebot_plugin_setu4">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_setu4/">nonebot_plugin_setu4</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件打包配置中正确填写依赖项`nonebot2`以及`nonebot-adapter-onebot`

**Comment by Special-Week** [comment]
> 请在插件打包配置中正确填写依赖项`nonebot2`以及`nonebot-adapter-onebot`

已修改
