### ISSUE TITLE
Plugin: smart_reply

### ISSUE THREAD

**Issue by Special-Week** [nonebot/nonebot2#1053]
**插件名称：**

智能回复

**插件功能：**

nonebot2的智能(障)回复插件

**PyPI 项目名：**

nonebot-plugin-smart-reply

**插件 import 包名：**

nonebot_plugin_smart_reply

**插件项目仓库/主页链接：**

https://github.com/Special-Week/nonebot_plugin_smart_reply

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: smart_reply

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Special-Week/nonebot_plugin_smart_reply">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_smart_reply/">nonebot_plugin_smart_reply</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
