### ISSUE TITLE
Plugin: BitTorrent

### ISSUE THREAD

**Issue by Special-Week** [nonebot/nonebot2#1058]
**插件名称：**

BitTorrent

**插件功能：**

nonebot2磁力搜索插件

**PyPI 项目名：**

nonebot_plugin_BitTorrent

**插件 import 包名：**

nonebot_plugin_BitTorrent

**插件项目仓库/主页链接：**

https://github.com/Special-Week/nonebot_plugin_BitTorrent

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: BitTorrent

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包名 "lxml","httpx","bs4","nonebot2","nonebot-adapter-onebot" 不符合规范。<dt>请确保包名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Special-Week/nonebot_plugin_BitTorrent">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_BitTorrent/">nonebot_plugin_BitTorrent</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
