### ISSUE TITLE
Plugin: 黑白名单

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1060]
**插件名称：**

黑白名单

**插件功能：**

简易黑白用户名单管理

**PyPI 项目名：**

nonebot-plugin-namelist

**插件 import 包名：**

nonebot_plugin_namelist

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-namelist

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 黑白名单

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-namelist">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-namelist/">nonebot-plugin-namelist</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
