### ISSUE TITLE
Plugin: 生存时间

### ISSUE THREAD

**Issue by 1623658271** [nonebot/nonebot2#1062]
**插件名称：**

生存时间

**插件功能：**

你想查看自己在世上的存活时间吗

**PyPI 项目名：**

**插件 import 包名：**

nonebot_plugin_lifetime

**插件项目仓库/主页链接：**

https://github.com/1623658271/nonebot_plugin_lifetime.git

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 生存时间

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/1623658271/nonebot_plugin_lifetime.git">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
