### ISSUE TITLE
Plugin: nonebot-plugin-bread

### ISSUE THREAD

**Issue by Mai-icy** [nonebot/nonebot2#1063]
**插件名称：**

面包店小游戏

**插件功能：**

面包店休闲小游戏

**PyPI 项目名：**

nonebot-plugin-bread-shop

**插件 import 包名：**

nonebot_plugin_bread_shop

**插件项目仓库/主页链接：**

https://github.com/Mai-icy/nonebot-plugin-bread-shop

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-bread

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Mai-icy/nonebot-plugin-bread-shop">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bread-shop/">nonebot-plugin-bread-shop</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
能否修改一下插件功能描述，光面包店并不能知晓插件功能
