### ISSUE TITLE
Plugin: 赛马

### ISSUE THREAD

**Issue by shinianj** [nonebot/nonebot2#1067]
**插件名称：**

赛马

**插件功能：**

群内青春版赛马小游戏

**PyPI 项目名：**

nonebot_plugin_horserace

**插件 import 包名：**

**插件项目仓库/主页链接：**

https://github.com/shinianj/nonebot_plugin_horserace

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 赛马

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/shinianj/nonebot_plugin_horserace">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_horserace/">nonebot_plugin_horserace</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by shinianj** [comment]
> **插件名称：**
> 
> 赛马
> 
> **插件功能：**
> 
> 群内青春版赛马小游戏
> 
> **PyPI 项目名：**
> 
> nonebot_plugin_horserace
> 
> **插件 import 包名：**
> nonebot_plugin_horserace

> **插件项目仓库/主页链接：**
> 
> https://github.com/shinianj/nonebot_plugin_horserace
> 
> **标签：**
> 
> []
