### ISSUE TITLE
Plugin: PicMenu

### ISSUE THREAD

**Issue by hamo-reid** [nonebot/nonebot2#1070]
**插件名称：**

PicMenu

**插件功能：**

根据插件元数据生成图片化功能菜单

**PyPI 项目名：**

nonebot_plugin_PicMenu

**插件 import 包名：**

nonebot_plugin_PicMenu

**插件项目仓库/主页链接：**

https://github.com/hamo-reid/nonenot_plugin_PicMenu

**标签：**

[{"label":"a:onebot","color":"#030303"},{"label":"t:menu","color":"#753dc6"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: PicMenu

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#030303, t:menu-#753dc6</li><li>✅ 项目 <a href="https://github.com/hamo-reid/nonenot_plugin_PicMenu">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_PicMenu/">nonebot_plugin_PicMenu</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
