### ISSUE TITLE
Plugin: 米游币商品自动兑换

### ISSUE THREAD

**Issue by CMHopeSunshine** [nonebot/nonebot2#1075]
**插件名称：**

米游币商品自动兑换

**插件功能：**

让Bot帮你抢米游币商品

**PyPI 项目名：**

nonebot-plugin-myb-exchange

**插件 import 包名：**

nonebot_plugin_myb_exchange

**插件项目仓库/主页链接：**

https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:Genshin","color":"#ffca0a"},{"label":"小派蒙","color":"#7c0dc3"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 米游币商品自动兑换

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, t:Genshin-#ffca0a, 小派蒙-#7c0dc3</li><li>✅ 项目 <a href="https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-myb-exchange/">nonebot-plugin-myb-exchange</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
nb-cli应作为dev deps依赖，请勿放在运行依赖里
