### ISSUE TITLE
Bug: logger设置冲突

### ISSUE THREAD

**Issue by Polyisoprene** [nonebot/nonebot2#1078]
**描述问题：**

不管是通过.env.prod配置LOG_LEVEL还是通过.env.dev配置LOG_LEVEL,配置都不起作用，即使设置LOG_LEVEL=INFO，仍然会显示DEBUG信息

**如何复现？**

配置完LOG_LEVEL后nb run

**期望的结果**

只显示设置的LOG_LEVEL及以上的日志

**环境信息：**

 - OS: windows10
 - Python Version: 3.8.10
 - Nonebot Version:  2.0.0b4

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: v1.0.0-rc3

**截图或日志**

![图1](http://i0.hdslb.com/bfs/new_dyn/65ccd48a0970e36b4b8fece5f760a2eb37815472.png)
![图2](http://i0.hdslb.com/bfs/new_dyn/d4ff79c575512521ca97794cf69a0d4c37815472.png)
![图3](http://i0.hdslb.com/bfs/new_dyn/275405bce8840c68c4edc70df8ff5aff37815472.png)

**Comment by Polyisoprene** [comment]
经过检查，是有其他程序里也用了logguru
```python
logger.remove()
logger.add(sys.stdout,
           format="<red>[</red><green>{time:YYYY/MM/DD HH:mm:ss}</green><red>]</red> <red>[</red> <green>{level}</green> <red>]</red> {message}")
```
这一段使得nb的设置不起作用了

**Comment by yanyongyu** [comment]
如果需要自定义logger，可以在add的时候加上nb的default_filter（nonebot.log模块里），就可以使用配置项了
