### ISSUE TITLE
Plugin: OSU查分插件

### ISSUE THREAD

**Issue by yaowan233** [nonebot/nonebot2#1081]
**插件名称：**

OSU查分插件

**插件功能：**

OSU查分插件

**PyPI 项目名：**

nonebot-plugin-osubot

**插件 import 包名：**

nonebot_plugin_osubot

**插件项目仓库/主页链接：**

https://github.com/yaowan233/nonebot-plugin-osubot

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"OSU","color":"#eb5d9b"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: OSU查分插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, OSU-#eb5d9b</li><li>✅ 项目 <a href="https://github.com/yaowan233/nonebot-plugin-osubot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-osubot/">nonebot-plugin-osubot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
虽然但是，为什么你的`__init__.py`在插件外面

**Comment by yaowan233** [comment]
啊 已改正
