### ISSUE TITLE
Plugin: 一起燚xN吧

### ISSUE THREAD

**Issue by GC-ZF** [nonebot/nonebot2#1084]
**插件名称：**

一起燚xN吧

**插件功能：**

QQ续火花，可以自定义多个联系人、消息内容、发送时间

**PyPI 项目名：**

nonebot-plugin-firexN

**插件 import 包名：**

nonebot_plugin_firexN

**插件项目仓库/主页链接：**

https://github.com/GC-ZF/nonebot_plugin_firexN

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 一起燚xN吧

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/GC-ZF/nonebot_plugin_firexN">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-firexN/">nonebot-plugin-firexN</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
