### ISSUE TITLE
Plugin: 战地1、5战绩查询工具

### ISSUE THREAD

**Issue by GC-ZF** [nonebot/nonebot2#1086]
**插件名称：**

战地1、5战绩查询工具

**插件功能：**

QQ私聊或群聊发送战地游戏ID，返回基础信息以及最佳兵种、最佳枪械、最佳载具、最佳模式信息

**PyPI 项目名：**

nonebot-plugin-bfinfo

**插件 import 包名：**

nonebot_plugin_bfinfo

**插件项目仓库/主页链接：**

https://github.com/GC-ZF/nonebot_plugin_bfinfo

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 战地1、5战绩查询工具

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/GC-ZF/nonebot_plugin_bfinfo">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bfinfo/">nonebot-plugin-bfinfo</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
