### ISSUE TITLE
Plugin: 自动回复（文i）插件

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1089]
**插件名称：**

自动回复（文i）插件

**插件功能：**

使用 Kyomotoi/AnimeThesaurus 的nonebot2的回复（文i）插件

**PyPI 项目名：**

nonebot_plugin_kawaii_robot

**插件 import 包名：**

nonebot_plugin_kawaii_robot

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_kawaii_robot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 自动回复（文i）插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_kawaii_robot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_kawaii_robot/">nonebot_plugin_kawaii_robot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖中正确填写 nonebot2 以及 nonebot-adapter-onebot

**Comment by KarisAya** [comment]
> 请在插件中正确填写 nonebot2 以及 nonebot-adapter-onebot
是这样吗
    install_requires=["nonebot2","nonebot-adapter-onebot"],

**Comment by yanyongyu** [comment]
是
