### ISSUE TITLE
Feature: 希望能够和v1共存，方便旧版本的维护

### ISSUE THREAD

**Issue by zangxx66** [nonebot/nonebot2#109]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

想尝试v2的开发，但是需要维护v1的仓库，按照文档指示需要先卸载v1，想做到两个版本共存

**描述你所需要的特性：**

希望v1和v2采用不同的包名用以区分，方便同时维护不同版本的机器人

**Comment by Lancercmd** [comment]
你可以用虚拟环境

**Comment by mnixry** [comment]
同上,我们推荐采用`poetry`来管理程序编写时的虚拟环境,用来防止不同项目依赖版本不同所造成的冲突

或者你是想说在同一个程序中同时使用nonebot1和nonebot2?

**Comment by yanyongyu** [comment]
维护多个项目应该使用不同的环境来进行管理而不是使用同一个环境，这容易导致版本冲突、依赖混乱，虚拟环境是一个很好的解决方案
