### ISSUE TITLE
Docs: `选择驱动器` 一节增加驱动器顺序警告

### ISSUE THREAD

**Issue by MingxuanGame** [nonebot/nonebot2#1091]
**描述问题或主题：**

在加载多个驱动器时，会对第一个驱动器之后的所有驱动器进行 Mixin

https://github.com/nonebot/nonebot2/blob/fa3ed2b58c3e0b82f39214d502cdea80494870ea/nonebot/__init__.py#L202-L205

如果该驱动器不支持 Mixin 就会报错，例如下面的驱动器组合

```
DRIVER=~httpx+~websockets+~fastapi
```

由于会对 `websockets` 和 `fastapi` 进行 Mixin，但是 `fastapi` 不支持 Mixin，这样就会报错

```
AttributeError: module 'nonebot.drivers.fastapi' has no attribute 'Mixin'
```

**需做出的修改：**

* [ ]  添加一个警告，提醒用户配置的驱动器顺序为 `一个不支持Mixin的驱动器+若干支持Mixin的驱动器` 或 `若干支持Mixin的驱动器`

**Comment by yanyongyu** [comment]
其实在Driver配置里写了Driver+Mixin

![image](https://user-images.githubusercontent.com/42488585/178128487-b4d9c3e2-b7dd-491f-bc3e-f16f202ae6c2.png)

**Comment by MingxuanGame** [comment]
噢噢并没看到上一节已经有了，道歉
