### ISSUE TITLE
Plugin: ACC计算工具

### ISSUE THREAD

**Issue by 10-24** [nonebot/nonebot2#1092]
**插件名称：**

ACC计算工具

**插件功能：**

能够计算段位的单曲acc，支持malodyv3段位regular、ex

**PyPI 项目名：**

nonebot-plugin-acc-calculate

**插件 import 包名：**

nonebot_plugin_acc_calculate

**插件项目仓库/主页链接：**

https://github.com/10-24/nonebot-plugin-acc-calculate

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ACC计算工具

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/10-24/nonebot-plugin-acc-calculate">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_acc_calculate/">nonebot_plugin_acc_calculate</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
