### ISSUE TITLE
Plugin: 明日方舟寻访记录分析

### ISSUE THREAD

**Issue by zheuziihau** [nonebot/nonebot2#1096]
**插件名称：**

明日方舟寻访记录分析

**插件功能：**

从官网获取明日方舟寻访记录并出图的插件

**PyPI 项目名：**

nonebot_plugin_arkrecord

**插件 import 包名：**

nonebot_plugin_arkrecord

**插件项目仓库/主页链接：**

https://github.com/zheuziihau/nonebot_plugin_arkrecord

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 明日方舟寻访记录分析

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/zheuziihau/nonebot_plugin_arkrecord">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_arkrecord/">nonebot_plugin_arkrecord</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖中缺少nonebot2以及nonebot-adapter-onebot

**Comment by zheuziihau** [comment]
> 插件依赖中缺少nonebot2以及nonebot-adapter-onebot

已经完成修改
