### ISSUE TITLE
Plugin: 处理好友添加和群邀请

### ISSUE THREAD

**Issue by ziru-w** [nonebot/nonebot2#1098]
**插件名称：**

处理好友添加和群邀请

**插件功能：**

一个基于NoneBot2的插件，用于处理被请求加QQ好友和QQ群的请求

**PyPI 项目名：**

nonebot_plugin_addFriend

**插件 import 包名：**

nonebot_plugin_addFriend

**插件项目仓库/主页链接：**

https://github.com/ziru-w/nonebot_plugin_addFriend

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 处理好友添加和群邀请

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ziru-w/nonebot_plugin_addFriend">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_addFriend/">nonebot_plugin_addFriend</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
