### ISSUE TITLE
question:"WebSocket /cqhttp/ws" 403

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#110]
运行环境：CentOS8
整个文件夹就一个bot.py文件
![image](https://user-images.githubusercontent.com/36919867/102026749-a24c3400-3dda-11eb-955f-8dea21154b50.png)
bot.py文件内容如下
![image](https://user-images.githubusercontent.com/36919867/102026752-a5dfbb00-3dda-11eb-8999-a4364e62ab86.png)
http端报错403
![image](https://user-images.githubusercontent.com/36919867/102027000-4e424f00-3ddc-11eb-8cdc-a9acf0f2f62f.png)

http配置那边只改过账号密码和反向ws地址
![image](https://user-images.githubusercontent.com/36919867/102026817-0e2e9c80-3ddb-11eb-9e56-3c60d911a48a.png)

问题描述：

是个很蠢的问题，但是我昨天折腾了一天，都快怀疑人生了，救救孩子。  本来用的好好的，重装个系统就变成这样了。  换过QQ号，换过端口，重装过系统(Ubuntu也是403)，都不行。 按照我的记忆，把go cq配置的端口和bot端口改一致就好了。还是说我遗漏了什么东西？

ps:重装系统的原因是CentOS8的screen有问题，假设主窗口什么都没有（即光标停留在第一行）, screen -r 切换到工作窗口，作业完成之后使用CTRL+A+D切回主窗口时，会保留工作窗口的打印内容，而光标却依然留在第一行，虽然可以正常输入，也可以用clear清屏，然而依旧很麻烦。 已经多次更换过镜像（包括CentOS 7.6），也更换过SSH工具，确定是CentOS8的问题。 （然后我才知道有tmux可以代替，不过此时问题已经换成了ws 403，跟什么系统没关系了）
![image](https://user-images.githubusercontent.com/36919867/102026945-f1469900-3ddb-11eb-9c18-6b03f621aa68.png)

**Comment by railannad** [comment]
又看了看文档，发现是忘了[register_adapter ](https://v2.nonebot.dev/guide/getting-started.html#%E5%8E%86%E5%8F%B2%E6%80%A7%E7%9A%84%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%AF%B9%E8%AF%9D)

实在是丢人，close了

**Comment by putianyi889** [comment]
我出了同样的问题，搜半天没搜到，到这里挨个翻issue才找到。我把文本放这方便搜索

连接到反向Websocket Universal服务器 ws://127.0.0.1:8080/ws 时出现错误: websocket: bad handshake

**Comment by mnixry** [comment]
NoneBot2目前仍然处于Alpha阶段，在每次版本更新之间会存在不兼容的API更改
如果想要在升级后正常使用，请随时跟进我们的文档

**Comment by railannad** [comment]
> 我出了同样的问题，搜半天没搜到，到这里挨个翻issue才找到。我把文本放这方便搜索
> 
> 连接到反向Websocket Universal服务器 ws://127.0.0.1:8080/ws 时出现错误: websocket: bad handshake

bad handshake是协议端的报错，不属于nonebot(
另外我是直接压缩了py文件后才重装系统的，没想到bot.py会出问题

**Comment by lengthmin** [comment]
https://github.com/nonebot/nonebot2/commit/a539fd00622870b7ed7df557138e9aa010dc74c5

**Comment by GoogleNB** [comment]
> 

兄弟，文档没了，我也卡在这里了，怎么操作啊

**Comment by yanyongyu** [comment]
> 兄弟，文档没了，我也卡在这里了，怎么操作啊

onebot适配器文档：https://onebot.adapters.nonebot.dev/

**Comment by GoogleNB** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nonebot/nonebot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nonebot/nonebot2] question:"WebSocket /cqhttp/ws" 403 (#110)





  
兄弟，文档没了，我也卡在这里了，怎么操作啊
  
onebot适配器文档：https://onebot.adapters.nonebot.dev/

**Comment by SanJerry007** [comment]
确实是驱动器的问题，这个报错403有点误导性。。。

我是直接通过 python 方式启动的 bot，结果里面忘记导入 OneBot Adapter 了，然后一直报这个错，加上之后就好了：

`
from nonebot.adapters.onebot.v11 import Adapter as OneBotAdapter

nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter(OneBotAdapter)  # ADD THIS!!!!!!!!!
`
