### ISSUE TITLE
Plugin: 明日方舟寻访记录分析

### ISSUE THREAD

**Issue by zheuziihau** [nonebot/nonebot2#1100]
**插件名称：**

明日方舟寻访记录分析

**插件功能：**

从官网获取明日方舟寻访记录并进行分析

**PyPI 项目名：**

nonebot_plugin_arkrecord

**插件 import 包名：**

nonebot_plugin_arkrecord

**插件项目仓库/主页链接：**

https://github.com/zheuziihau/nonebot_plugin_arkrecord

**标签：**

[{"label":"t:明日方舟","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 明日方舟寻访记录分析

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ PyPI 项目名 nonebot_plugin_arkrecord 加包名 nonebot_plugin_arkrecord 的值与商店重复。<dt>请确保没有重复发布。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: t:明日方舟-#ea5252</li><li>✅ 项目 <a href="https://github.com/zheuziihau/nonebot_plugin_arkrecord">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_arkrecord/">nonebot_plugin_arkrecord</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
