### ISSUE TITLE
Plugin: 群昵称时间

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#1108]
**插件名称：**

群昵称时间

**插件功能：**

一个可以群昵称显示现在时间的插件

**PyPI 项目名：**

nonebot-plugin-date-name

**插件 import 包名：**

nonebot_plugin_date_name

**插件项目仓库/主页链接：**

https://github.com/bingqiu456/nonebot-plugin-date-name

**标签：**

[{"label":"a:onebot","color":"#a552ea"},{"label":"t:qun_card","color":"#e552ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 群昵称时间

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#a552ea, t:qun_card-#e552ea</li><li>✅ 项目 <a href="https://github.com/bingqiu456/nonebot-plugin-date-name">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-date-name/">nonebot-plugin-date-name</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
