### ISSUE TITLE
Plugin: 易命令

### ISSUE THREAD

**Issue by ziru-w** [nonebot/nonebot2#1110]
**插件名称：**

易命令

**插件功能：**

一个基于NoneBot2的简单的用于动态地添加命令或添加定时任务的插件

**PyPI 项目名：**

nonebot_plugin_easyCommand

**插件 import 包名：**

nonebot_plugin_easyCommand

**插件项目仓库/主页链接：**

https://github.com/ziru-w/nonebot_plugin_easyCommand

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 易命令

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ziru-w/nonebot_plugin_easyCommand">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_easyCommand/">nonebot_plugin_easyCommand</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
