### ISSUE TITLE
Bot: SkadiBot

### ISSUE THREAD

**Issue by yuyuziYYZ** [nonebot/nonebot2#1112]
**机器人名称：**

SkadiBot

**机器人功能：**

明日方舟主题机器人—斯卡蒂

**机器人项目仓库/主页链接：**

https://github.com/yuyuziYYZ/skadi_bot

**标签：**

[{"label":"明日方舟","color":"#a48888"},{"label":"斯卡蒂","color":"#a48888"},{"label":"arknights","color":"#a48888"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: SkadiBot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 明日方舟-#a48888, 斯卡蒂-#a48888, arknights-#a48888</li><li>✅ 项目 <a href="https://github.com/yuyuziYYZ/skadi_bot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
