### ISSUE TITLE
Plugin: 「能不能好好说话？」缩写翻译

### ISSUE THREAD

**Issue by ArgonarioD** [nonebot/nonebot2#1117]
**插件名称：**

「能不能好好说话？」缩写翻译

**插件功能：**

拼音首字母及阿拉伯数字缩写翻译

**PyPI 项目名：**

nonebot-plugin-hammer-nbnhhsh

**插件 import 包名：**

nonebot_plugin_hammer_nbnhhsh

**插件项目仓库/主页链接：**

https://github.com/ArgonarioD/nonebot-plugin-hammer-nbnhhsh

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"a:cqhttp","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 「能不能好好说话？」缩写翻译

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, a:cqhttp-#000000</li><li>✅ 项目 <a href="https://github.com/ArgonarioD/nonebot-plugin-hammer-nbnhhsh">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-hammer-nbnhhsh/">nonebot-plugin-hammer-nbnhhsh</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
