### ISSUE TITLE
更新beta5版本后启动提示UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 717: invalid continuation byte

### ISSUE THREAD

**Issue by WindraiteLesd** [nonebot/nonebot2#1123]
**描述问题：**

无法正常启动

**如何复现？**

python bot.py

**期望的结果**

正常启动

**环境信息：**

 - OS: [Windows Server 2019]
 - Python Version: [3.9.7]
 - Nonebot Version: [beta5]

**协议端信息：**

 - 协议端: [go-cqhttp]

**截图或日志**
![image](https://user-images.githubusercontent.com/104503043/182996269-f4603d60-8442-4257-9711-ebf7fd8880ec.png)

**Comment by yanyongyu** [comment]
请检查你的.env文件编码

**Comment by WindraiteLesd** [comment]
> 请检查你的.env文件编码

![image](https://user-images.githubusercontent.com/104503043/182996939-6c62f68e-7c41-4265-8777-753ac820ee13.png)

**Comment by yanyongyu** [comment]
是你的.env.dev或者.env.prod文件的编码

**Comment by WindraiteLesd** [comment]
> 是你的.env.dev或者.env.prod文件的编码，不是你的bot.py文件内容

解决了，更新前后.env.dev一直是没动过的不知道怎么就把编码换回ANSI了
