### ISSUE TITLE
Plugin: MC_QQ

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1126]
**插件名称：**

MC_QQ通信

**插件功能：**

基于NoneBot的与Minecraft Server互通消息的插件

**PyPI 项目名：**

nonebot-plugin-mcqq

**插件 import 包名：**

nonebot_plugin_mcqq

**插件项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-plugin-mcqq

**标签：**

[{"label":"Minecraft","color":"#52ea6f"},{"label":"消息互通","color":"#52eadf"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Msg_QQ

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#52ea6f, 消息互通-#52eadf</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-plugin-msgqq">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-msgqq/">nonebot-plugin-msgqq</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖中正确填写`nonebot2`和`nonebot-adapter-onebot`

**Comment by 17TheWord** [comment]
> 请在插件依赖中正确填写和`nonebot2``nonebot-adapter-onebot`

已在插件依赖中填写 `nonebot2 `和 `nonebot-adapter-onebot`
