### ISSUE TITLE
Plugin: BAWiki

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1128]
**插件名称：**

BAWiki

**插件功能：**

基于 NoneBot2 的碧蓝档案 Wiki 插件

**PyPI 项目名：**

nonebot-plugin-bawiki

**插件 import 包名：**

nonebot_plugin_bawiki

**插件项目仓库/主页链接：**

https://github.com/lgc2333/nonebot-plugin-bawiki/

**标签：**

[{"label":"t:碧蓝档案","color":"#00d7fb"},{"label":"t:蔚藍檔案","color":"#00d7fb"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: BAWiki

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:碧蓝档案-#00d7fb, t:蔚藍檔案-#00d7fb</li><li>✅ 项目 <a href="https://github.com/lgc2333/nonebot-plugin-bawiki/">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bawiki/">nonebot-plugin-bawiki</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
