### ISSUE TITLE
Plugin: 疫情小助手-频道版

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#1130]
**插件名称：**

疫情小助手-频道版

**插件功能：**

👉 疫情小助手 频道版👈

**PyPI 项目名：**

nonebot-plugin-covid-19-by-guild

**插件 import 包名：**

nonebot_plugin_covid_19_by_guild

**插件项目仓库/主页链接：**

https://github.com/bingqiu456/nonebot-plugin-covid-19-by-guild

**标签：**

[{"label":"a:QQ频道","color":"#ea5252"},{"label":"t:疫情小助手","color":"#526fea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 疫情小助手-频道版

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:QQ频道-#ea5252, t:疫情小助手-#526fea</li><li>✅ 项目 <a href="https://github.com/bingqiu456/nonebot-plugin-covid-19-by-guild">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-covid-19-by-guild/">nonebot-plugin-covid-19-by-guild</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
