### ISSUE TITLE
Plugin: wiki条目搜索、获取简介

### ISSUE THREAD

**Issue by ZombieFly** [nonebot/nonebot2#1132]
**插件名称：**

wiki条目搜索、获取简介

**插件功能：**

通过mediawiki api进行条目搜索、生成简介（biliwiki部分通过网页解析实现）

**PyPI 项目名：**

nonebot-plugin-wiki

**插件 import 包名：**

nonebot_plugin_wiki

**插件项目仓库/主页链接：**

https://github.com/ZombieFly/nb2-wiki

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: wiki条目搜索、获取简介

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ZombieFly/nb2-wiki">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-wiki/">nonebot-plugin-wiki</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖项中正确添加`nonebot`和`nonebot-adapter-onebot`

**Comment by ZombieFly** [comment]
> 请在插件依赖项中正确添加`nonebot`和`nonebot-adapter-onebot`

感谢指出，已添加，请查验
