### ISSUE TITLE
Plugin: 查看正方教务课表

### ISSUE THREAD

**Issue by letianpai-lpt** [nonebot/nonebot2#1135]
**插件名称：**

查看正方教务课表

**插件功能：**

查看今日,明日,本周,下周课表

**PyPI 项目名：**

无

**插件 import 包名：**

json,re,requests,ast,datetime

**插件项目仓库/主页链接：**

https://github.com/letianpai-lpt/nonebot_plugin_kebiao

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 查看正方教务课表

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包名 json,re,requests,ast,datetime 不符合规范。<dt>请确保包名正确。</dt></li><li>⚠️ PyPI 项目名 无 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/letianpai-lpt/nonebot_plugin_kebiao">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
