### ISSUE TITLE
Plugin: bangumi搜索

### ISSUE THREAD

**Issue by Ankhyty** [nonebot/nonebot2#1136]
**插件名称：**

bangumi搜索

**插件功能：**

搜索番剧，并且返回简介栏和收藏盒

**PyPI 项目名：**

nonebot-plugin-bangumi-search

**插件 import 包名：**

nonebot-plugin-bangumi-search

**插件项目仓库/主页链接：**

https://github.com/Ankhyty/nonebot-plugin-bangumi-search

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:漫研","color":"#2f48e0"},{"label":"bangumi","color":"#de2968"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: bangumi搜索

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, t:漫研-#2f48e0, bangumi-#de2968</li><li>✅ 项目 <a href="https://github.com/Ankhyty/nonebot-plugin-bangumi-search">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bangumi-search/">nonebot-plugin-bangumi-search</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖中正确填写`nonebot2`以及`nonebot-adapter-onebot`，而不是`nonebot`

**Comment by Ankhyty** [comment]
> 请在插件依赖中正确填写`nonebot2`以及`nonebot-adapter-onebot`，而不是`nonebot`

已在插件依赖中填写 `nonebot2` 和 `nonebot-adapter-onebot`
