### ISSUE TITLE
Plugin: oxword

### ISSUE THREAD

**Issue by eskha256** [nonebot/nonebot2#1139]
**插件名称：**

oxword

**插件功能：**

每天的牛津词典官网推荐的单词

**PyPI 项目名：**

nonebot_plugin_oxword

**插件 import 包名：**

oxword

**插件项目仓库/主页链接：**

https://github.com/eskha256/oxword

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: oxword

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot_plugin_oxword/">nonebot_plugin_oxword</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/eskha256/oxword">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
