### ISSUE TITLE
Bug: func.pause()当用户进一步发送消息之后对话直接结束了

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#114]
**描述问题：**

在插件中使用func.pause("xxx")，试图与用户进一步交互。当用户发送新的信息之后对话就结束了

**如何复现？**
相关代码如下:
功能：当用户输入指定格式的ID时从 [DLsite](https://www.dlsite.com/maniax/fsr/=/work_type/SOU/work_category/doujin/from/left_pain.work_type)抓取封面。如果封面存在则询问用户，如果用户输入0则只发送封面，如果输入1则发送完整作品信息  （本来是只能发封面的，我想加个选择分支）
```
@get_cover.got('RJ_code',prompt='请输入6位或8位RJ号\n示例: RJ266666/266666')
async def __(bot: Bot, event: Event, state: dict):
    # 去掉消息首尾的空白符
    RJ_code = str(state['RJ_code'])
    RJ_code=RJ_code.upper()
    if str(len(RJ_code)) != '8' and str(len(RJ_code)) != '6':
        await get_cover.finish('这不是RJ号,重来!')
    resault = re.search('RJ\d{6}',RJ_code)
    if resault:
        RJ_code = RJ_code
    else:
        if re.search('\d{6}',RJ_code) and len(RJ_code) == 6 : 
            RJ_code='RJ'+RJ_code
        else:
            await get_cover.finish('这不是RJ号,重来!')
    img = await get_cover_with_RJ_code(RJ_code)
    if img == 404 or not img:
        await get_cover.finish('RJ号不存在,请重新检查')
    await get_cover.pause("已抓取到封面,仅获取封面回复0,获取标题CV等完整信息输入1")
    await get_cover.finish(str(state))
    if str(only_cover) == "0":
        await get_cover.finish(img)
    elif str(only_cover) == "1":
        title,CV,price,R18=get_RJ_info.get_work_info(RJ_code)
        info="RJ号: "+RJ_code+"\n标题: "+title+"\nCV: "+CV+"\n价格: "+price+"\n是否R18: "+R18+"\n"+img
        await get_cover.finish(info)
    else:
        await get_cover.finish("参数不对哟")
```

**期望的结果**

根据代码，期望bot回复完整对话state，用于进一步调试，而实际上在pause之后对话直接结束了

PS：顺带一提reject也用过了，但是效果是直接重置。  看起来似乎只有pause能实现我想要的功能

**环境信息：**

 - OS: CentOS8
 - Python Version: 3.8.3
 - Nonebot Version: 2.0.0a7

**截图**

![image](https://user-images.githubusercontent.com/36919867/102304483-82626f00-3f98-11eb-8e33-b5bef520f1cb.png)
![image](https://user-images.githubusercontent.com/36919867/102303477-2c8cc780-3f96-11eb-81b2-4e2200dbfbc8.png)
![image](https://user-images.githubusercontent.com/36919867/102304627-e2591580-3f98-11eb-9836-c729e03e3828.png)

**Comment by yanyongyu** [comment]
你这里的 `pause` 用法有点不对，你可能是要这样

```python
@get_cover.got('RJ_code',prompt='请输入6位或8位RJ号\n示例: RJ266666/266666')
async def __(bot: Bot, event: Event, state: dict):
    # 去掉消息首尾的空白符
    RJ_code = str(state['RJ_code'])
    RJ_code=RJ_code.upper()
    if str(len(RJ_code)) != '8' and str(len(RJ_code)) != '6':
        await get_cover.finish('这不是RJ号,重来!')
    resault = re.search('RJ\d{6}',RJ_code)
    if resault:
        RJ_code = RJ_code
    else:
        if re.search('\d{6}',RJ_code) and len(RJ_code) == 6 : 
            RJ_code='RJ'+RJ_code
        else:
            await get_cover.finish('这不是RJ号,重来!')
    img = await get_cover_with_RJ_code(RJ_code)
    if img == 404 or not img:
        await get_cover.finish('RJ号不存在,请重新检查')

@get_cover.got('only_cover',prompt='已抓取到封面,仅获取封面回复0,获取标题CV等完整信息输入1')
async def _(bot: Bot, event: Event, state: dict):
    print(state['only_cover'])
    only_cover = state['only_cover']
    if only_cover == "0":
        await get_cover.finish(img)
    elif only_cover == "1":
        title,CV,price,R18=get_RJ_info.get_work_info(RJ_code)
        info="RJ号: "+RJ_code+"\n标题: "+title+"\nCV: "+CV+"\n价格: "+price+"\n是否R18: "+R18+"\n"+img
        await get_cover.finish(info)
    else:
        await get_cover.finish("参数不对哟")
```

**Comment by yanyongyu** [comment]
题外话 `await get_cover.finish('这不是RJ号,重来!')` 可以用 `get_cover.reject` 来允许用户重新输入RJ号

**Comment by yanyongyu** [comment]
`pause` 与 nonebot1 中的pause不同。`pause`的作用是跳出当前 `handler` 并等待用户发送消息后，执行下一个 `handler`。你没有下一个 `handler` 所以就直接结束了。

**Comment by railannad** [comment]
> `pause` 与 nonebot1 中的pause不同。`pause`的作用是跳出当前 `handler` 并等待用户发送消息后，执行**下一个** `handler`。你没有下一个 `handler` 所以就直接结束了。

懂了，感谢大佬解答 ，之前看文档一直看不懂"下一个处理函数"是什么意思，原来是指py文件的上下文

题外话: RJ266666图床还在，但是商品页已经404了(猜测是作者下架)，导致除了封面全部抓取失败，吓得我以为又要重构函数

**Comment by railannad** [comment]
> `pause` 与 nonebot1 中的pause不同。`pause`的作用是跳出当前 `handler` 并等待用户发送消息后，执行**下一个** `handler`。你没有下一个 `handler` 所以就直接结束了。


之前大佬提到 "pause的作用是跳出当前handler并等待用户发送消息后，执行下一个handler" 。 看了下文档似乎没有能够捕获用户输入的参数/key，那能否根据用户输入的不同来执行不同的分支？
上次大佬给的代码里没有用到 `pause` ，能否给个`pause`的简单示例？

**Comment by yanyongyu** [comment]
> 上次大佬给的代码里没有用到 `pause` ，能否给个`pause`的简单示例？

`pause` 目前的作用仅仅是在当前 `handler` 与后续 `handler`之间动态插入一个获取消息的过程。

如果你需要实现的某个功能，他既可能不需要用户发送消息直接进行下一步，也有可能需要用户进一步回复时会用到。~~预留了这么一个方法，万一用到了呢~~

**Comment by railannad** [comment]
> > 上次大佬给的代码里没有用到 `pause` ，能否给个`pause`的简单示例？
> 
> `pause` 目前的作用仅仅是在当前 `handler` 与后续 `handler`之间动态插入一个获取消息的过程。
> 
> 如果你需要实现的某个功能，他既可能不需要用户发送消息直接进行下一步，也有可能需要用户进一步回复时会用到。~预留了这么一个方法，万一用到了呢~
> 
> 更多的还是使用 `got` 与 `reject` 的组合

懂了  看来暂时是用不到`pause`了
