### ISSUE TITLE
Plugin: 简易群管（带入群欢迎）

### ISSUE THREAD

**Issue by HuYihe2008** [nonebot/nonebot2#1141]
**插件名称：**

简易群管（带入群欢迎）

**插件功能：**

与简易群管属于同个产品，就是多了一个入群欢迎，感谢@幼稚园园长 开发的原版插件的帮助 

**PyPI 项目名：**

nonebot-plugin-admin-hello

**插件 import 包名：**

nonebot_plugin_admin_hello

**插件项目仓库/主页链接：**

https://github.com/HuYihe2008/nonebot_plugin_admin_hello

**标签：**

[{"label":"简易群管","color":"#53e950"},{"label":"插件改良","color":"#2b7be2"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 简易群管（带入群欢迎）

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 简易群管-#53e950, 插件改良-#2b7be2, 感谢幼稚园园长-#e2622b</li><li>✅ 项目 <a href="https://github.com/HuYihe2008/nonebot_plugin_admin_hello">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-admin-hello/">nonebot-plugin-admin-hello</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
