### ISSUE TITLE
Feature: argparse 直接处理 Message

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#1143]
使用 `on_shell_command`  是先把消息变成字符串再匹配
因此，如果消息里面有CQ码就会有些问题

如:  
<img width="283" alt="CleanShot 2022-08-12 at 14 53 11" src="https://user-images.githubusercontent.com/71873002/184300489-258ca38d-7e2d-4096-8d93-367908ee9722.png">

希望:
-  `ShellCommandArgs` 和 `ShellCommandArgv` 得到的东西可以是 `str, Message`

~~我也不知道应该怎么描述~~

**Comment by yanyongyu** [comment]
🥵 🥵 🥵

**Comment by kexue-z** [comment]
![7F778E0DBFEE52C9E5F912482DEEEEF9](https://user-images.githubusercontent.com/71873002/184313662-c7a1872f-ea81-4d9e-a970-96b9318f26e3.gif)
