### ISSUE TITLE
Plugin: 简易群管（带入群欢迎）

### ISSUE THREAD

**Issue by jamyido** [nonebot/nonebot2#1144]
**插件名称：**

简易群管（带入群欢迎）

**插件功能：**

简易群管，原版：简易群管@yzyyz1387

**PyPI 项目名：**

nonebot-plugin-admin-hello

**插件 import 包名：**

nonebot_plugin_admin_hello

**插件项目仓库/主页链接：**

https://github.com/HuYihe2008/nonebot_plugin_admin_hello

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 简易群管（带入群欢迎）

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 项目 <a href="https://github.cin/HuYihe2008/nonebot-plugin-admin-hello">主页</a> 返回状态码 None。<dt>请确保您的项目主页可访问。</dt></li><li>⚠️ PyPI 项目名 nonebot-plugin-admin-hello 加包名 nonebot_plugin_admin_hello 的值与商店重复。<dt>请确保没有重复发布。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-admin-hello/">nonebot-plugin-admin-hello</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
