### ISSUE TITLE
Plugin: nonebot-plugin-drawer

### ISSUE THREAD

**Issue by CrazyBoyM** [nonebot/nonebot2#1145]
**插件名称：**

nonebot-plugin-drawer

**插件功能：**

适用于 Nonebot2 的AI画画插件

**PyPI 项目名：**

nonebot-plugin-drawer

**插件 import 包名：**

nonebot_plugin_drawer

**插件项目仓库/主页链接：**

https://github.com/CrazyBoyM/nonebot-plugin-drawer

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-drawe

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/CrazyBoyM/nonebot-plugin-drawer">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-drawer/">nonebot-plugin-drawer</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在插件依赖中正确填写`nonebot2`和`nonebot-adapter-onebot`，不要将setup.py和pyproject.toml混用

**Comment by yanyongyu** [comment]
你新发的版本还是没写对啊，你setup.py里的install_requires呢，或者你直接用pyproject poetry打包不就行了

**Comment by yanyongyu** [comment]
插件依赖里少了`nonebot-adapter-onebot`，多了`asyncio`，这个是标准库

**Comment by shikukuya** [comment]
114514
