### ISSUE TITLE
Plugin: 小游戏合集

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1149]
**插件名称：**

小游戏合集

**插件功能：**

改自 nonebot_plugin_russian 合并了nonebot_plugin_horserace还有一些自编玩法的小游戏合集。

**PyPI 项目名：**

nonebot_plugin_game_collection

**插件 import 包名：**

nonebot_plugin_game_collection

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_game_collection

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 小游戏合集

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_game_collection">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_game_collection/">nonebot_plugin_game_collection</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
