### ISSUE TITLE
Bug: Something went wrong

### ISSUE THREAD

**Issue by RickSchanze** [nonebot/nonebot2#1152]
**描述问题：**

在使用on_keyword时，不正确的消息触发了关键词处理函数。

**如何复现？**

定义
```
studentunion = on_keyword("学生会哪个部门比较好玩")
@studentunion.handle()
async def studentunion_handle(event:Event, bot:Bot):
    await bot.send(event, Message(f"哪个部门都很好玩啦！"))
```
当获得”好玩“，”不好玩“或者一些其他消息时，该handle函数也会触发

**期望的结果**
仅仅在收到”学生会哪个部门比较好玩“时触发

**环境信息：**

 - OS: [Windows]
 - Python Version: 3.9.7
 - Nonebot Version: Nonebot2 2.0.0b4

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [e.g. v1.0.0-rc3]

**截图或日志**

![7769B25E59680198564420EA86C1F731](https://user-images.githubusercontent.com/93311103/184538127-ecb6080a-60f7-420c-b5f2-136e7b10e09a.jpg)

**Comment by yanyongyu** [comment]
请正确使用 `on_keyword` https://v2.nonebot.dev/docs/api/plugin/on#on_keyword
