### ISSUE TITLE
Feature: 更改插件名称“简易群管（带入群欢迎）”为“多功能简易群管”

### ISSUE THREAD

**Issue by jamyido** [nonebot/nonebot2#1153]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

更改插件nonebot_plugin_admin_hello的名称为“多功能简易群管”

**描述你所需要的特性：**

更改插件名称“简易群管（带入群欢迎）”为“多功能简易群管”

**Comment by yanyongyu** [comment]
插件信息修改请直接提交pr
