### ISSUE TITLE
Plugin: 每日人品

### ISSUE THREAD

**Issue by SkyDynamic** [nonebot/nonebot2#1155]
**插件名称：**

每日人品

**插件功能：**

不基于random的每日人品插件

**PyPI 项目名：**

nonebot-plugin-jrrp-n

**插件 import 包名：**

nonebot_plugin_jrrp-n

**插件项目仓库/主页链接：**

https://github.com/SkyDynamic/nonebot_plugin_jrrp

**标签：**

[{"label":"每日人品","color":"#ea5252"},{"label":"jrrp","color":"#529fea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 每日人品

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包名 typing,time 不符合规范。<dt>请确保包名正确。</dt></li><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-plugin-jrrp-n/ 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 每日人品 -#ea5252, 人品-#ea5252, jrrp-#529fea</li><li>✅ 项目 <a href="https://github.com/SkyDynamic/nonebot_plugin_jrrp">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在你的插件依赖中正确添加`nonebot-adapter-onebot`

**Comment by SkyDynamic** [comment]
> 请在你的插件依赖中正确添加`nonebot-adapter-onebot`

在pypi项目里添加对吧，好了
