### ISSUE TITLE
Plugin: 日韩中 VITS 模型原神拟声

### ISSUE THREAD

**Issue by Yiyuiii** [nonebot/nonebot2#1161]
**插件名称：**

日韩中 VITS 模型原神拟声

**插件功能：**

现在是琪亚娜时间~

**PyPI 项目名：**

nonebot-plugin-moegoe

**插件 import 包名：**

nonebot_plugin_moegoe

**插件项目仓库/主页链接：**

https://github.com/Yiyuiii/nonebot-plugin-moegoe

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 日韩中 VITS 模型原神拟声

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Yiyuiii/nonebot-plugin-moegoe">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-moegoe/">nonebot-plugin-moegoe</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
