### ISSUE TITLE
Plugin: 语言翻译

### ISSUE THREAD

**Issue by Tamakostory** [nonebot/nonebot2#1163]
**插件名称：语言翻译插件**

**插件功能：自动识别源语言的多语言翻译插件**

**PyPI 项目名：无**

**插件项目仓库/主页链接：https://github.com/Tamakostory/baidu_translate**

**标签：python plug**
v0.0.1

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 语言翻译

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ tags: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Tamakostory/baidu_translate">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
