### ISSUE TITLE
Plugin: PixivBot

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#1164]
**插件名称：**

PixivBot

**插件功能：**

NoneBot插件，发送随机Pixiv插画、画师更新推送、定时订阅推送……

**PyPI 项目名：**

nonebot-plugin-pixivbot

**插件 import 包名：**

nonebot_plugin_pixivbot

**插件项目仓库/主页链接：**

https://github.com/ssttkkl/nonebot-plugin-pixivbot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: PixivBot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ssttkkl/nonebot-plugin-pixivbot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-pixivbot/">nonebot-plugin-pixivbot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
