### ISSUE TITLE
Plugin: 课表查询

### ISSUE THREAD

**Issue by InariInDream** [nonebot/nonebot2#1167]
**插件名称：**

课表查询

**插件功能：**

本周课表，完整课表，下节课在哪上，今天还有什么课🤔

**PyPI 项目名：**

nonebot-plugin-course

**插件 import 包名：**

nonebot_plugin_course

**插件项目仓库/主页链接：**

https://github.com/InariInDream/nonebot_plugin_course

**标签：**

[{"label":"课表","color":"#6e9af2"}]

**Comment by yanyongyu** [comment]
请在插件依赖中添加`nonebot2`以及`nonebot-adapter-onebot`

**Comment by InariInDream** [comment]
> 请在插件依赖中添加`nonebot2`以及`nonebot-adapter-onebot`

修改后已上传至pypi
