### ISSUE TITLE
Plugin: 娶群友

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1169]
**插件名称：**

娶群友

**插件功能：**

娶群友（纯爱版，ntr版）

**PyPI 项目名：**

 nonebot_plugin_groupmate_waifu

**插件 import 包名：**

 nonebot_plugin_groupmate_waifu

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_groupmate_waifu

**标签：**

[{"label":"娶群友","color":"#529bea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 娶群友

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 娶群友-#529bea</li><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_groupmate_waifu">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_groupmate_waifu/">nonebot_plugin_groupmate_waifu</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
