### ISSUE TITLE
内置插件/say无法将纯文本转换为富文本

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#117]
环境: windows10 64位
nonebot 版本:2.0.0a7
python 版本 3.8.0

根据[loading-a-plugin.md](https://github.com/nonebot/nonebot2/blob/b6bbc7d2284e5cee9de8cc012fefa40da6d2b544/archive/2.0.0a7/guide/loading-a-plugin.md#%E5%8A%A0%E8%BD%BD%E5%86%85%E7%BD%AE%E6%8F%92%E4%BB%B6)，期望出现的结果是bot回复一个表情（我记得用nb1的时候[文档](https://docs.nonebot.dev/guide/getting-started.html#%E5%8E%86%E5%8F%B2%E6%80%A7%E7%9A%84%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%AF%B9%E8%AF%9D)还有写，现在不知道怎么没了

![image](https://user-images.githubusercontent.com/36919867/102869367-7b46cf80-4476-11eb-8ba6-4a7eb821d687.png)
![image](https://user-images.githubusercontent.com/36919867/102869391-813cb080-4476-11eb-9adc-14c97bdc13d2.png)

第二条消息是非SUPERUSER用户发的，无响应，在期望之内
我还特地发了个表情，确认CQ码没有错  (本来是打算发送图片的（懒，不想改代码））
搜索/echo稍微看了下源码，nb1里面有个unescape模块， 即不解析CQ码，nb2里面似乎没有这种东西...
再也不敢用bug template了，怕打脸(小声bb

![image](https://user-images.githubusercontent.com/36919867/102869779-19d33080-4477-11eb-9ecc-c814446f41f7.png)

**Comment by yanyongyu** [comment]
日志中显示蓝字代表已经是CQ码了。如果你用的是`go-cqhttp`这个无法显示的原因是因为并不支持`face`

**Comment by railannad** [comment]
> 日志中显示蓝字代表已经是CQ码了。如果你用的是`go-cqhttp`这个无法显示的原因是因为并不支持`face`

大佬可能误会了我的意思。   第二张图是我发送了一个表情（bot收到了一个表情），所以才是蓝色的。 而此行为的目的是确保我的CQ码(/say之后的内容)没有错

**Comment by yanyongyu** [comment]
我这边复现了，我看一下

**Comment by yanyongyu** [comment]
已修改
