### ISSUE TITLE
Plugin: 业余无线电助手

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#1172]
**插件名称：**

业余无线电助手

**插件功能：**

一个业余无线电相关的插件

**PyPI 项目名：**

nonebot-plugin-cqsat

**插件 import 包名：**

cqsat

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/cqsat

**标签：**

[{"label":"业余无线电","color":"#ea5252"},{"label":"HAM","color":"#3898fc"},{"label":"卫星追踪","color":"#fca638"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 业余无线电助手

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 业余无线电-#ea5252, HAM-#3898fc, 卫星追踪-#fca638</li><li>✅ 项目 <a href="https://github.com/yzyyz1387/cqsat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-cqsat/">nonebot-plugin-cqsat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖项中多了个`nonebot`，这是nonebot1

**Comment by yzyyz1387** [comment]
> 插件依赖项中多了个`nonebot`，这是nonebot1

哦哦，抱歉，没有注意到，稍后对其进行更改

**Comment by yzyyz1387** [comment]
已做出更改：[6650df8](https://github.com/yzyyz1387/cqsat/commit/6650df812ad3f11c66384be8d7dff5e24061610e)

**Comment by yzyyz1387** [comment]
pypi已上传带正确依赖的版本
