### ISSUE TITLE
Plugin: NoneBot 树形帮助插件

### ISSUE THREAD

**Issue by he0119** [nonebot/nonebot2#1176]
**插件名称：**

NoneBot 树形帮助插件

**插件功能：**

利用插件元数据生成插件帮助，并支持插件嵌套。

**PyPI 项目名：**

nonebot-plugin-treehelp

**插件 import 包名：**

nonebot_plugin_treehelp

**插件项目仓库/主页链接：**

https://github.com/he0119/nonebot-plugin-treehelp

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: NoneBot 树形帮助插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/he0119/nonebot-plugin-treehelp">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-treehelp/">nonebot-plugin-treehelp</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
