### ISSUE TITLE
Plugin: 保存群聊闪照

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1178]
**插件名称：**

保存群聊闪照

**插件功能：**

静默保存群聊中的闪照

**PyPI 项目名：**

nonebot_plugin_flash_silentsave

**插件 import 包名：**

nonebot_plugin_flash_silentsave

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_flash_silentsave

**标签：**

[{"label":"反闪照","color":"#52a5ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 保存群聊闪照

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 反闪照-#52a5ea</li><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_flash_silentsave">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_flash_silentsave/">nonebot_plugin_flash_silentsave</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
