### ISSUE TITLE
Plugin: 话痨排行榜

### ISSUE THREAD

**Issue by X-Skirt-X** [nonebot/nonebot2#1181]
**插件名称：**

话痨排行榜

**插件功能：**

给话多的群友一个排行

**PyPI 项目名：**

nonebot-plugin-dialectlist

**插件 import 包名：**

nonebot_plugin_dialectlist

**插件项目仓库/主页链接：**

https://github.com/X-Skirt-X/nonebot_plugin_dialectlist

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 话痨排行榜

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/X-Skirt-X/nonebot_plugin_dialectlist">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-dialectlist/">nonebot-plugin-dialectlist</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
