### ISSUE TITLE
Plugin: MagiaDice骰娘及TRPGLOG

### ISSUE THREAD

**Issue by sena-nana** [nonebot/nonebot2#1184]
**插件名称：**

MagiaDice骰娘及TRPGLOG

**插件功能：**

能够实时在网页围观的TRPG记录插件，同时具有骰娘的功能

**PyPI 项目名：**

nonebot-plugin-magiadice

**插件 import 包名：**

nonebot-plugin-magiadice

**插件项目仓库/主页链接：**

https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-magiadice

**标签：**

[{"label":"TRPG","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: MagiaDice骰娘及TRPGLOG

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: TRPG-#ea5252</li><li>✅ 项目 <a href="https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-magiadice">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_magiadice/">nonebot_plugin_magiadice</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`

**Comment by sena-nana** [comment]
> 请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`

重新打包了下，麻烦您看看还有没有问题

**Comment by yanyongyu** [comment]
你打包的文件里没有`setup.py`。。。

**Comment by sena-nana** [comment]
> 你打包的文件里没有`setup.py`。。。

可能是因为之前setup.py没有按标准命名，您再看一下。因为第一次传pypi，这套流程跑不太清楚，非常感谢指点

**Comment by sena-nana** [comment]
其他两个插件也都进行了同样的修改
