### ISSUE TITLE
Plugin: 反馈及通知

### ISSUE THREAD

**Issue by sena-nana** [nonebot/nonebot2#1186]
**插件名称：**

反馈及通知

**插件功能：**

用户通过bot向superuser发送反馈，以及bot向全群发送通知

**PyPI 项目名：**

nonebot-plugin-send

**插件 import 包名：**

nonebot-plugin-send

**插件项目仓库/主页链接：**

https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-send

**标签：**

[{"label":"send","color":"#ea5252"},{"label":"notice","color":"#ea5252"},{"label":"公告","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 反馈及通知

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: send-#ea5252, notice-#ea5252, 公告-#ea5252</li><li>✅ 项目 <a href="https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-send">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_send/">nonebot_plugin_send</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`

**Comment by sena-nana** [comment]
> 请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`

重新打包了下，麻烦您看看还有没有问题
