### ISSUE TITLE
Plugin: 雨课堂自动签到

### ISSUE THREAD

**Issue by sena-nana** [nonebot/nonebot2#1188]
**插件名称：**

雨课堂自动签到

**插件功能：**

使用playwright模拟浏览器签到雨课堂，并将腾讯会议号发送给superuser

**PyPI 项目名：**

nonebot-plugin-ykt

**插件 import 包名：**

nonebot-plugin-ykt

**插件项目仓库/主页链接：**

https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-ykt

**标签：**

[{"label":"playwright","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 雨课堂自动签到

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: playwright-#ea5252</li><li>✅ 项目 <a href="https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-ykt">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_ykt/">nonebot_plugin_ykt</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`，另外你这个插件打包都打错了。

**Comment by sena-nana** [comment]
重新打包了下，麻烦您看看还有没有问题

> 请在你的插件依赖`install_requires`中正确添加依赖，包括`nonebot2`和`nonebot-adapter-onebot`，另外你这个插件打包都打错了。
