### ISSUE TITLE
Plugin: 面麻小助手

### ISSUE THREAD

**Issue by Nranphy** [nonebot/nonebot2#1190]
**插件名称：**

面麻小助手

**插件功能：**

可约桌、算点、精算、雀魂查询的面麻助手。

**PyPI 项目名：**

nonebot-plugin-offline-mahjong-helper

**插件 import 包名：**

nonebot_plugin_offline_mahjong_helper

**插件项目仓库/主页链接：**

https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper

**标签：**

[{"label":"Mahjong","color":"#ea5252"},{"label":"雀魂","color":"#eaa452"},{"label":"线下约桌","color":"#52a6ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 面麻小助手

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Mahjong-#ea5252, 雀魂-#eaa452, 线下约桌-#52a6ea</li><li>✅ 项目 <a href="https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-offline-mahjong-helper/">nonebot-plugin-offline-mahjong-helper</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖项中缺少`nonebot-adapter-onebot`

**Comment by Nranphy** [comment]
> 插件依赖项中缺少`nonebot-adapter-onebot`

已修改并发版
