### ISSUE TITLE
Plugin: 自识别todo

### ISSUE THREAD

**Issue by CofinCup** [nonebot/nonebot2#1192]
**插件名称：**

自识别todo

**插件功能：**

一款自动识别提醒内容，可生成todo图片并定时推送的nonebot2插件，v11适配器可用

**PyPI 项目名：**

nonebot-plugin-todo-nlp

**插件 import 包名：**

nonebot_plugin_todo_nlp

**插件项目仓库/主页链接：**

https://github.com/CofinCup/nonebot-plugin-todo-nlp

**标签：**

[{"label":"t:todo","color":"#499bdd"},{"label":"t:nlp","color":"#83b279"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 自识别todo

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:todo-#499bdd, t:nlp-#83b279</li><li>✅ 项目 <a href="https://github.com/CofinCup/nonebot-plugin-todo-nlp">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-todo-nlp/">nonebot-plugin-todo-nlp</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖中缺少了`nonebot-adapter-onebot`，另外setup.py不要和poetry同时使用

**Comment by CofinCup** [comment]
> 插件依赖中缺少了`nonebot-adapter-onebot`，另外setup.py不要和poetry同时使用
> 插件依赖中缺少了`nonebot-adapter-onebot`，另外setup.py不要和poetry同时使用

已修正并重新发布到pypi
