### ISSUE TITLE
Plugin: 修仙模拟器

### ISSUE THREAD

**Issue by s52047qwas** [nonebot/nonebot2#1195]
**插件名称：**

修仙模拟器

**插件功能：**

加入群内修仙吧！

**PyPI 项目名：**

nonebot-plugin-xiuxian

**插件 import 包名：**

nonebot_plugin_xiuxian

**插件项目仓库/主页链接：**

https://github.com/s52047qwas/nonebot_plugin_xiuxian

**标签：**

[]

**Comment by s52047qwas** [comment]
已发布至pypi

**Comment by s52047qwas** [comment]
> 

已发布至PyPI

**Comment by yanyongyu** [comment]
插件依赖写错了，应该是`nonebot2`，还少了`nonebot-adapter-onebot`

**Comment by s52047qwas** [comment]
> 插件写错了，应该是`nonebot2`，依赖还少了`nonebot-adapter-onebot`

已更新

**Comment by yanyongyu** [comment]
pypi上的还是不对啊

**Comment by s52047qwas** [comment]
> pypi上的还是不对啊

sorry，这次可以了
