### ISSUE TITLE
Plugin: nonebot2_manage

### ISSUE THREAD

**Issue by SDIJF1521** [nonebot/nonebot2#1200]
**插件名称：**

nonebot2_manage

**插件功能：**

用于辅助管理群的插件，支持群禁言，单人禁言，不良语言撤回(可在群内自定义不良词汇)

**PyPI 项目名：**

nonebot2_manage

**插件 import 包名：**

nonebot2_manage

**插件项目仓库/主页链接：**

https://github.com/SDIJF1521/nonebot2_manage

**标签：**

[{"label":"群管理","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot2_manage

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 群管理-#ea5252</li><li>✅ 项目 <a href="https://github.com/SDIJF1521/nonebot2_manage">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot2_manage/">nonebot2_manage</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖缺少`nonebot2`和`nonebot-adapter-onebot`，并且你的打包package名字不对
