### ISSUE TITLE
Plugin: 赛博浅草寺

### ISSUE THREAD

**Issue by Raidenneox** [nonebot/nonebot2#1205]
**插件名称：**

赛博浅草寺

**插件功能：**

随机抽取浅草寺的一签运势

**PyPI 项目名：**

nonebot-plugin-CyberSensoji

**插件 import 包名：**

nonebot_plugin_CyberSensoji

**插件项目仓库/主页链接：**

https://github.com/Raidenneox/nonebot_plugin_CyberSensoji

**标签：**

[{"label":"t:抽签","color":"#52eadf"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 赛博浅草寺

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: t:抽签-#52eadf</li><li>✅ 项目 <a href="https://github.com/Raidenneox/nonebot_plugin_CyberSensoji/tree/master">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖写错了，应该是`nonebot2`，还缺少了`nonebot-adapter-onebot`

**Comment by Raidenneox** [comment]
> 插件依赖写错了，应该是`nonebot2`，还缺少了`nonebot-adapter-onebot`

抱歉，已经更正并重新发布
