### ISSUE TITLE
Plugin: 原神角色展柜查询

### ISSUE THREAD

**Issue by monsterxcn** [nonebot/nonebot2#1207]
**插件名称：**

原神角色展柜查询

**插件功能：**

移植自 @yoimiya-kokomi/miao-plugin 的原神游戏内角色展柜数据查询

**PyPI 项目名：**

nonebot-plugin-gspanel

**插件 import 包名：**

nonebot_plugin_gspanel

**插件项目仓库/主页链接：**

https://github.com/monsterxcn/nonebot-plugin-gspanel

**标签：**

[{"label": "t:Genshin", "color": "#ffd49f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 原神角色展柜查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:Genshin-#ffd49f</li><li>✅ 项目 <a href="https://github.com/monsterxcn/nonebot-plugin-gspanel">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-gspanel/">nonebot-plugin-gspanel</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
