### ISSUE TITLE
Feature: 希望添加旧版的 IntentCommand 功能

### ISSUE THREAD

**Issue by v587ygq** [nonebot/nonebot2#121]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

旧版 nonebot 能通过 IntentCommand 手动触发一条指令，新版好像无该功能？

**描述你所需要的特性：**

希望添加手动触发指令或响应器的功能

**Comment by yanyongyu** [comment]
新版里的 `nlp` 由 `Rule` 替代实现

手动触发响应器可以自行调用 `matcher.run(bot, event)`

**Comment by v587ygq** [comment]
> 新版里的 `nlp` 由 `Rule` 替代实现，通过 `Rule` 来判断是否执行当前的响应器
> 
> `IntendCommand` 并不是手动触发指令 `call_command` 才是
> 
> 手动触发响应器可以自行调用 `matcher.run(bot, event)`

感谢回答，原来还有 run 方法。。。
