### ISSUE TITLE
Plugin: MC_QQ_MCRcon

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1210]
**插件名称：**

MC_QQ_MCRcon

**插件功能：**

基于NoneBot的QQ群聊与Minecraft Server消息互通插件

**PyPI 项目名：**

nonebot-plugin-mcqq-mcrcon

**插件 import 包名：**

nonebot_plugin_mcqq_mcrcon

**插件项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-plugin-mcqq/tree/mcqq_mcrcon

**标签：**

[{"label":"Minecraft","color":"#4aea7a"},{"label":"消息互通","color":"#32ddea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: MC_QQ_MCRcon

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#4aea7a, 消息互通-#32ddea</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-plugin-mcqq/tree/mcqq_mcrcon">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-mcqq-mcrcon/">nonebot-plugin-mcqq-mcrcon</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
