### ISSUE TITLE
Adapter: Console

### ISSUE THREAD

**Issue by Melodyknit** [nonebot/nonebot2#1212]
**协议名称：**

Console

**协议功能：**

基于终端的交互式适配器

**PyPI 项目名：**

nonebot-adapter-console

**协议 import 包名：**

nonebot.adapters.console

**协议项目仓库/主页链接：**

https://github.com/nonebot/adapter-console

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: Console

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-adapter-console/ 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/nonebot/adapter-console">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
