### ISSUE TITLE
Feature: 添加发送消息前钩子

### ISSUE THREAD

**Issue by MingxuanGame** [nonebot/nonebot2#1214]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

添加 `Bot.on_sending_msg` hook，在 `bot.send` 实际发送消息前运行此 hook，执行一些操作（例如日志记录，消息存入数据库等）

**描述你所需要的特性：**

调用应该是类似于下方的样子

```python
from nonebot.adapters import Bot, Event, Message, MessageSegment


@Bot.on_sending_msg
async def handle_bot_send(bot: Bot, event: Event, message: Union[str, Message, MessageSegment], **kwargs):
    pass
```

（可选）添加异常 `MockMessageException` ，抛出此异常来对消息进行修改

参数：
message: Union[str, Message, MessageSegment]

**为什么不用 `Bot.on_calling_api`？**

`on_calling_api` 提供的数据为 `Dict[str, Any]`，一是缺少了类型提示（虽然可以手动标注，问题不大），二是一些平台（例如 QQ 频道）的发消息接口较为特殊，`Dict[str, Any]` 可能无法准确还原成调用 `bot.send` 时传入的消息，也比较麻烦

**局限性**

需要各适配器主动运行此 hook，无法在本体内直接实现

**Comment by yanyongyu** [comment]
这个问题可以由custom send解决，如果适配器提供了自定义send方法的话。这个hook不太好加，加了所有适配器都得改，一波breaking。
