### ISSUE TITLE
Plugin: 原神每日材料查询

### ISSUE THREAD

**Issue by monsterxcn** [nonebot/nonebot2#1215]
**插件名称：**

原神每日材料查询

**插件功能：**

原神每日天赋培养、武器突破材料查询，通过 Project Amber 数据库（支持部分尚未实装角色）自动更新每日数据～

**PyPI 项目名：**

nonebot-plugin-gsmaterial

**插件 import 包名：**

nonebot_plugin_gsmaterial

**插件项目仓库/主页链接：**

https://github.com/monsterxcn/nonebot-plugin-gsmaterial

**标签：**

[{"label": "t:Genshin", "color": "#ffd49f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 原神每日材料查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:Genshin-#ffd49f</li><li>✅ 项目 <a href="https://github.com/monsterxcn/nonebot-plugin-gsmaterial">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-gsmaterial/">nonebot-plugin-gsmaterial</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
