### ISSUE TITLE
Plugin: 星际战甲事件查询

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1219]
**插件名称：**

星际战甲事件查询

**插件功能：**

基于NoneBot的星际战甲事件查询插件

**PyPI 项目名：**

nonebot-plugin-warframe

**插件 import 包名：**

nonebot_plugin_warframe

**插件项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-plugin-warframe

**标签：**

[{"label":"星际战甲","color":"#ed3f3f"},{"label":"WarFrame","color":"#edea3f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 星际战甲事件查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 星际战甲-#ed3f3f, WarFrame-#edea3f</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-plugin-warframe">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-warframe/">nonebot-plugin-warframe</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
