### ISSUE TITLE
Nonebot doesn't work!

### ISSUE THREAD

**Issue by lcy1317** [nonebot/nonebot2#122]
I have configured go-CQHTTP and installed Nonebot2 as required by the documentation but Nonebot2 had no reaction.
![{7W1S@T`MJ7))0XMTFECAU7](https://user-images.githubusercontent.com/60378321/103135280-29aa7900-46f2-11eb-8f82-8f2b45aa1a68.png)

![TLCCJ6PA 8GVO5%8@9`G~X](https://user-images.githubusercontent.com/60378321/103135269-17c8d600-46f2-11eb-9bd9-a3f4a7ce5e23.png)

**Comment by mnixry** [comment]
请参照[最新文档](https://v2.nonebot.dev/guide/getting-started.html#%E6%9C%80%E5%B0%8F%E5%AE%9E%E4%BE%8B)
我们现在需要手动注册adapter

Duplicate of #110

**Comment by lcy1317** [comment]
谢谢，想再请问一下
使用nonebot2
用如下方式发送图片：await hhh.finish("[CQ:image,file=.ml.png]")
出现了下面的报错，请问如何解决
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed retcode=100>

**Comment by yanyongyu** [comment]
> 出现了下面的报错，请问如何解决
> nonebot.adapters.cqhttp.exception.ActionFailed: ActionFailed retcode=100

这个问题请看 go-cqhttp 日志

**Comment by lcy1317** [comment]
> > 出现了下面的报错，请问如何解决
> > nonebot.adapters.cqhttp.exception.ActionFailed: ActionFailed retcode=100
> 
> 这个问题请看 go-cqhttp 日志
> 
> 你这多半是file参数写错了，没有你这种写法，具体写法参考 cqhttp 协议

谢谢

**Comment by GoogleNB** [comment]
> 

大佬，文档没了，咋注册啊

**Comment by mnixry** [comment]
> 大佬，文档没了，咋注册啊

在每个相关问题下方都回复一遍并不能加快里问题解决的速度

我们文档的地址是v2.nonebot.dev

请在打开文档之后Ctrl+F5刷新以获得最新文档

**Comment by GoogleNB** [comment]
汝邮件吾已收到，汝勿虑也。

**Comment by synodriver** [comment]
吓死我了，还以为死issue复活了

**Comment by Adversarr** [comment]
Wow, logo of matlab!

**Comment by synodriver** [comment]
> Wow, logo of matlab!

Wow, logo for Wolfram Mathematica!

**Comment by GoogleNB** [comment]
> > 大佬，文档没了，咋注册啊
> 
> 在每个相关问题下方都回复一遍并不能加快里问题解决的速度
> 
> 我们文档的地址是v2.nonebot.dev
> 
> 请在打开文档之后Ctrl+F5刷新以获得最新文档

抱歉，搞了一下午没搞懂，加群也没反应，又找到这了，线索又断了有点激动
