### ISSUE TITLE
Plugin: 

### ISSUE THREAD

**Issue by IPearZ** [nonebot/nonebot2#1222]
**插件名称：**

**插件功能：**

提供剑网3各种服务

**PyPI 项目名：**

nonebot-plugin-jx3pear

**插件 import 包名：**

nonebot_plugin_jx3pear

**插件项目仓库/主页链接：**

https://github.com/IPearZ/jx3/tree/master

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包名 imgkit, matplotlib 不符合规范。<dt>请确保包名正确。</dt></li><li>⚠️ 包 <a href="https://pypi.org/project/jx3/">jx3</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li><li>⚠️ name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/IPearZ/jx3/tree/master">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
