### ISSUE TITLE
Bot: 小白机器人

### ISSUE THREAD

**Issue by SDIJF1521** [nonebot/nonebot2#1223]
**机器人名称：**

小白机器人

**机器人功能：**

一个高度依赖数据库的群管理机器人

**机器人项目仓库/主页链接：**

https://github.com/SDIJF1521/qqai

**标签：**

[{"label":"群管理","color":"#ea5252"},{"label":"新人作品","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: 小白机器人

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 群管理-#ea5252, 新人作品-#ea5252</li><li>✅ 项目 <a href="https://github.com/SDIJF1521/qqai">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
