### ISSUE TITLE
Bot: GenshinUID

### ISSUE THREAD

**Issue by 84227871** [nonebot/nonebot2#1225]
**机器人名称：**

GenshinUID

**机器人功能：**

原神机器人

**机器人项目仓库/主页链接：**

https://github.com/KimigaiiWuyi/GenshinUID

**标签：**

[{"label":"原神","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: GenshinUID

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 原神-#ea5252</li><li>✅ 项目 <a href="https://github.com/KimigaiiWuyi/GenshinUID">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by 84227871** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by A-kirami** [comment]
GenshinUID 是一个插件而非一个 Bot，[README.md](https://github.com/KimigaiiWuyi/GenshinUID#readme) 的标语是：
**基于[HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)/[NoneBot2](https://github.com/nonebot/nonebot2)/[QQ官方频道Bot](https://bot.q.qq.com/wiki/#)的原神多功能插件**
它依托于其他 Bot 框架，无法独立运行，应该作为插件发布而不是 Bot 发布
