### ISSUE TITLE
增加获取某插件下matcher及其触发条件的API

### ISSUE THREAD

**Issue by htharoldht** [nonebot/nonebot2#1228]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

为了更方便地对权限进行管理，我想获取到某插件下的所有matcher，以及其触发条件

**描述你所需要的特性：**

该接口能更方便地进行权限管理、命令帮助，甚至对生成机器人的帮助文档都会有很大的帮助

**Comment by yanyongyu** [comment]
`plugin = nonebot.get_plugin('name')`获取插件对象，`plugin.matchers`就是你要的所有matcher。

获取到matcher怎么解析`matcher.rule`触发条件就看你自己想怎么写了

**Comment by htharoldht** [comment]
我能拿到matcher的触发条件，但是拿不到matcher的名字

```py
for i in plugin.matcher:
    for j in i.rule.checkers:
        tmp = list(map(str, re.findall(r"[\"']([^',]+?)['\"]", str(j.call))))
```

**Comment by yanyongyu** [comment]
matcher是不会存储名字这种东西的

**Comment by htharoldht** [comment]
增加`matcher.__doc__`的话，得手动更改好多东西[捂脸]，且现有的插件基本都没有这个支持

如果框架内部有这个东西，就方便多了

这样就可以针对各个插件的matcher级别进行权限控制，以及之前提到的帮助文档生成

**Comment by yanyongyu** [comment]
参考 #1015 目前不会对matcher进行改变，只有插件元数据

**Comment by yanyongyu** [comment]
如果有问题或者建议，请前往 #1015 参与讨论。
