### ISSUE TITLE
Plugin: 查询ETH合并日期

### ISSUE THREAD

**Issue by Sclock** [nonebot/nonebot2#1230]
**插件名称：**

查询ETH合并日期

**插件功能：**

矿难！！！！

**PyPI 项目名：**

nonebot2_plugin_eth_terminal

**插件 import 包名：**

ETH_Terminal

**插件项目仓库/主页链接：**

https://github.com/Sclock/nonebot2_plugin_eth_terminal

**标签：**

[{"label":"爬虫","color":"#ea5252"},{"label":"ETH","color":"#5285ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 查询ETH合并日期

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 项目 <a href="https://github.com/Sclock/nonebot2_plugin_eth_terminal">主页</a> 返回状态码 404。<dt>请确保您的项目主页可访问。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 爬虫-#ea5252, ETH-#5285ea</li><li>✅ 包 <a href="https://pypi.org/project/nonebot2_plugin_eth_terminal/">nonebot2_plugin_eth_terminal</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by Sclock** [comment]
已修改
