### ISSUE TITLE
Feature: 函数命名符合 PEP 8 规范

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1235]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

在 Nonebot2 中，有部分函数名称不符合 PEP 8 的命名规则，显得有些突兀

**描述你所需要的特性：**

重命名函数以贴合 PEP8

**Comment by yanyongyu** [comment]
？比如？

**Comment by A-kirami** [comment]
> ？比如？

比如 `internal.params` 的 `Depends`、`Arg`、`ArgStr`、`ArgStr`
以及 `params` 中一系列的依赖函数

**Comment by yanyongyu** [comment]
一系列依赖函数是与pydantic，fastapi命名风格一致，如`Field()`，`Query()`，`Body()`，另外我觉得大写首字母更能突出依赖注入的作用~~可能是我用惯了~~

**Comment by A-kirami** [comment]
个人感觉大部分开发者编写的依赖注入可能更多的是蛇形命名，容易造成大驼峰与蛇形命名混杂的问题，不过这个看法比较主观

**Comment by yanyongyu** [comment]
大驼峰就是python class的命名格式，你把它当成class就行了
