### ISSUE TITLE
Plugin: Minecraft Server 聊天同步

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1244]
**插件名称：**

Minecraft Server 聊天同步

**插件功能：**

采用本地读取log信息的方法的Minecraft Server互通消息的插件，mcqq服主版。

**PyPI 项目名：**

nonebot-plugin-mcqq-server

**插件 import 包名：**

nonebot_plugin_mcqq_server

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_mcqq_server

**标签：**

[{"label":"Minecraft","color":"#52ea64"},{"label":"消息互通","color":"#52e5ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Minecraft Server 聊天同步

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#52ea64, 消息互通-#52e5ea</li><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_mcqq_server">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_mcqq_server/">nonebot_plugin_mcqq_server</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
