### ISSUE TITLE
Plugin: QQ表情回复

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#1246]
**插件名称：**

QQ表情回复

**插件功能：**

发送指定表情触发回复，目前已经编好了一些回复……

**PyPI 项目名：**

Candy-reply

**插件 import 包名：**

Candy_reply

**插件项目仓库/主页链接：**

https://github.com/zhulinyv/Candy_reply

**标签：**

[{"label":"闲聊","color":"#FB04B7"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: QQ表情回复

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/zhulinyv/Candy_reply">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/Candy-reply/">Candy-reply</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖中缺少`nonebot2`和`nonebot-adapter-onebot`
