### ISSUE TITLE
Plugin: 图像超分辨率重建

### ISSUE THREAD

**Issue by ppxxxg22** [nonebot/nonebot2#1249]
**插件名称：**

图像超分辨率重建

**插件功能：**

对图像进行超分辨率重建，可以理解成将图像变大变清晰，不过线上重建的效果没有本地的好，具体可以查阅仓库

**PyPI 项目名：**

nonebot_plugin_RealESRGAN

**插件 import 包名：**

nonebot_plugin_RealESRGAN

**插件项目仓库/主页链接：**

https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN

**标签：**

[{"label":"图像超分辨率重建","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 图像超分辨率重建

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 图像超分辨率重建-#ea5252</li><li>✅ 项目 <a href="https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_RealESRGAN/">nonebot_plugin_RealESRGAN</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖中缺少`nonebot-adapter-onebot`，以及 https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN/blob/1a481f01ece41e452ed5e1876d314df604513d8f/src/__init__.py#L1 第一行import就写错了

**Comment by ppxxxg22** [comment]
> 插件依赖中缺少`nonebot-adapter-onebot`

已添加

> https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN/blob/1a481f01ece41e452ed5e1876d314df604513d8f/src/__init__.py#L1 第一行import就写错了

这个是仓库忘记更新了，pypi中的版本是正常的，我之前试过安装到本地并测试了。现仓库已更新。
