### ISSUE TITLE
Plugin: 狼人杀插件

### ISSUE THREAD

**Issue by AbCooly** [nonebot/nonebot2#1251]
**插件名称：**

狼人杀插件

**插件功能：**

在群里玩狼人杀

**PyPI 项目名：**

nonebot-plugin-wolf-kill

**插件 import 包名：**

nonebot-plugin-wolf-kill

**插件项目仓库/主页链接：**

https://github.com/AbCooly/nonebot_plugin_wolf_kill

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot狼人杀插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/AbCooly/nonebot_plugin_wolf_kill">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_wolf_kill/">nonebot_plugin_wolf_kill</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖填写错误，不是`nonebot`，是`nonebot2`以及`nonebot-adapter-onebot`

**Comment by AbCooly** [comment]
那我重新发一下
