### ISSUE TITLE
Feature: 希望实现permission中的and功能

### ISSUE THREAD

**Issue by CallMeChinese** [nonebot/nonebot2#126]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

例如在某些情况下，需要超管且私聊的环境下才能出发某些命令，虽然可以通过判断event的各种参数来实现，但是在permission中实现<code>permission=SUPERUSER & PRIVATE</code>看上去更加简洁

**描述你所需要的特性：**

https://github.com/nonebot/nonebot2/blob/a068040cbfc1284943eb8a65f6256e850df258a3/nonebot/permission.py#L60-L61

希望这里能实现一下（可能permission的结构要大改了）

**Comment by yanyongyu** [comment]
permission中一直是使用 `|` 符号进行连接，代表 `或` 的意思

**Comment by yanyongyu** [comment]
因为目前permission实现原理限制，暂不能实现 & 功能

**Comment by yanyongyu** [comment]
这个需求的话，目前还是通过自定义 `permission` 来实现较好，这部分在dev中实现有所改变，`nonebot` 这边更多的只是提供这么一个接口，和一些常见的权限

**Comment by yanyongyu** [comment]
如果有更好的 `permission` 实现方式，欢迎提出建议。😄
