### ISSUE TITLE
Plugin: nonebot物联网插件

### ISSUE THREAD

**Issue by littlebutt** [nonebot/nonebot2#1264]
**插件名称：**

nonebot物联网插件

**插件功能：**

为nonebot接入物联网提供方案，目前支持天猫精灵终端，后续会增加

**PyPI 项目名：**

nonebot-plugin-iot

**插件 import 包名：**

iot

**插件项目仓库/主页链接：**

https://github.com/littlebutt/nonebot-plugin-iot

**标签：**

[{"label":"t:物联网","color":"#4b86d7"},{"label":"t:天猫精灵","color":"#4b86d7"},{"label":"t:IOT","color":"#4b86d7"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot物联网插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:物联网-#4b86d7, t:天猫精灵-#4b86d7, t:IOT-#4b86d7</li><li>✅ 项目 <a href="https://github.com/littlebutt/nonebot-plugin-iot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-iot/">nonebot-plugin-iot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件打包的有问题，包里的路径是`plugins/iot/`，建议换种路径打包。另外，setup.py插件依赖缺少`nonebot2`以及`nonebot-adapter-onebot`

**Comment by littlebutt** [comment]
> 插件打包的有问题，包里的路径是`plugins/iot/`，建议换种路径打包。另外，setup.py插件依赖缺少`nonebot2`以及`nonebot-adapter-onebot`

你好，路径把plugins去掉了，然后依赖也加上了，谢谢。
