### ISSUE TITLE
Bot: IdhagnBot

### ISSUE THREAD

**Issue by su226** [nonebot/nonebot2#1266]
**机器人名称：**

IdhagnBot

**机器人功能：**

🐱🤖 一个以娱乐功能为主的缝合怪（划掉）QQ机器人，包含一定Furry要素但是不会卖萌（就是逊啦！）

**机器人项目仓库/主页链接：**

https://github.com/su226/IdhagnBot

**标签：**

[{"label":"a:OneBot","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: IdhagnBot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:OneBot-#ea5252</li><li>✅ 项目 <a href="https://github.com/su226/IdhagnBot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
