### ISSUE TITLE
Plugin: 聊天记录插件频道适配

### ISSUE THREAD

**Issue by X-Skirt-X** [nonebot/nonebot2#1268]
**插件名称：**

聊天记录插件频道适配

**插件功能：**

适用于nonebot-plugin-chatrecorder的频道适配器

**PyPI 项目名：**

nonebot-plugin-chatrecorder-guild-patch

**插件 import 包名：**

nonebot_plugin_chatrecorder_guild_patch

**插件项目仓库/主页链接：**

https://github.com/X-Skirt-X/nonebot-plugin-chatrecorder-guild-patch

**标签：**

[{"label":"t:消息记录","color":"#9dea52"},{"label":"t:频道","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 聊天记录插件频道适配

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:消息记录-#9dea52, t:频道-#ea5252</li><li>✅ 项目 <a href="https://github.com/X-Skirt-X/nonebot-plugin-chatrecorder-guild-patch">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatrecorder-guild-patch/">nonebot-plugin-chatrecorder-guild-patch</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
这种插件的extra就不用发到商店了吧，你可以在你的插件中说明
