### ISSUE TITLE
Plugin: BWIKI助手移植版

### ISSUE THREAD

**Issue by XZhouQD** [nonebot/nonebot2#1273]
**插件名称：**

BWIKI助手移植版

**插件功能：**

BWIKI助手机器人Nonebot2插件移植版

**PyPI 项目名：**

nonebot-plugin-bwiki-navigator

**插件 import 包名：**

nonebot_plugin_bwiki_navigator

**插件项目仓库/主页链接：**

https://github.com/XZhouQD/nonebot-plugin-bwiki-navigator

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:wiki","color":"#29a5e3"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: BWIKI助手移植版

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 项目 <a href="https://github.com/XZhouQD/nonebot-plugin-bwiki-navigator">主页</a> 返回状态码 404。<dt>请确保您的项目主页可访问。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, t:wiki-#29a5e3</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bwiki-navigator/">nonebot-plugin-bwiki-navigator</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
