### ISSUE TITLE
Plugin: 漂流瓶

### ISSUE THREAD

**Issue by Todysheep** [nonebot/nonebot2#1278]
**插件名称：**

漂流瓶

**插件功能：**

群与群互通的漂流瓶插件

**PyPI 项目名：**

nonebot-plugin-bottle

**插件 import 包名：**

nonebot_plugin_bottle

**插件项目仓库/主页链接：**

https://github.com/Todysheep/nonebot_plugin_bottle

**标签：**

[{"label":"漂流瓶","color":"#0893f2"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 漂流瓶

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 漂流瓶-#0893f2</li><li>✅ 项目 <a href="https://github.com/Todysheep/nonebot_plugin_bottle">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bottle/">nonebot-plugin-bottle</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
