### ISSUE TITLE
Plugin: gal角色语音生成

### ISSUE THREAD

**Issue by dpm12345** [nonebot/nonebot2#1280]
**插件名称：**

gal角色语音生成

**插件功能：**

能够根据发送角色名和文本生成对应角色语音

**PyPI 项目名：**

nonebot-plugin-tts-gal

**插件 import 包名：**

nonebot_plugin_tts_gal

**插件项目仓库/主页链接：**

https://github.com/dpm12345/nonebot_plugin_tts_gal

**标签：**

[{"label":"VITS","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: gal角色语音生成

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: VITS-#ea5252</li><li>✅ 项目 <a href="https://github.com/dpm12345/nonebot_plugin_tts_gal">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tts-gal/">nonebot-plugin-tts-gal</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
