### ISSUE TITLE
Plugin: PicStatus

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1286]
**插件名称：**

PicStatus

**插件功能：**

服务器运行状态图片版

**PyPI 项目名：**

nonebot-plugin-picstatus

**插件 import 包名：**

nonebot_plugin_picstatus

**插件项目仓库/主页链接：**

https://github.com/lgc2333/nonebot-plugin-picstatus

**标签：**

[{"label":"t:server","color":"#8bff00"},{"label":"a:OB V11","color":"#ff43c3"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: PicStatus

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:server-#8bff00, a:OB V11-#ff43c3</li><li>✅ 项目 <a href="https://github.com/lgc2333/nonebot-plugin-picstatus">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-picstatus/">nonebot-plugin-picstatus</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
