### ISSUE TITLE
Plugin: 图灵机器人

### ISSUE THREAD

**Issue by koking0** [nonebot/nonebot2#1288]
**插件名称：**

图灵机器人

**插件功能：**

接入图灵机器人做聊天

**PyPI 项目名：**

nonebot-plugin-tuling

**插件 import 包名：**

nonebot_plugin_tuling

**插件项目仓库/主页链接：**

https://github.com/Matrix-King-Studio/nonebot_plugin_tuling

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 图灵机器人

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Matrix-King-Studio/nonebot_plugin_tuling">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tuling/">nonebot-plugin-tuling</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖中缺少`nonebot2`和`nonebot-adapter-onebot`，另外请不要在异步中使用requests

**Comment by koking0** [comment]
> 插件依赖中缺少`nonebot2`和`nonebot-adapter-onebot`，另外请不要在异步中使用requests

已修改
