### ISSUE TITLE
Plugin: 监听者

### ISSUE THREAD

**Issue by AbCooly** [nonebot/nonebot2#1298]
**插件名称：**

监听者

**插件功能：**

监听指定消息并转发到指定群

**PyPI 项目名：**

nonebot-plugin-listener

**插件 import 包名：**

nonebot_plugin_listener

**插件项目仓库/主页链接：**

https://github.com/AbCooly/nonebot_plugin_listener

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 监听者

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/AbCooly/nonebot_plugin_listener">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-listener/">nonebot-plugin-listener</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
