### ISSUE TITLE
Plugin: BiliRequestAll

### ISSUE THREAD

**Issue by Shadow403** [nonebot/nonebot2#1301]
**插件名称：**

BiliRequestAll

**插件功能：**

通过B站UID审核入群

**PyPI 项目名：**

nonebot-plugin-BiliRequestAll

**插件 import 包名：**

nonebot_plugin_BiliRequestAll

**插件项目仓库/主页链接：**

https://github.com/Shadow403/nonebot_plugin_BiliRequestAll

**标签：**

[{"label":"bilibili","color":"#ea52e9"},{"label":"request","color":"#5eea52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: BiliRequestAll

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: bilibili-#ea52e9, request-#5eea52</li><li>✅ 项目 <a href="https://github.com/Shadow403/nonebot_plugin_BiliRequestAll.git">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_BiliRequestAll/">nonebot_plugin_BiliRequestAll</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请不要在插件依赖中写死版本

**Comment by Shadow403** [comment]
已更新

**Comment by Shadow403** [comment]
已更新
