### ISSUE TITLE
Bug: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by iven13465** [nonebot/nonebot2#1304]
**描述问题：**

服务器卡死重启后使用任何插件都会报错TypeError: argument of type 'NoneType' is not iterable，已尝试过重装nb2

**环境信息：**

 - OS: ubuntu20.04
 - Python Version: 3.8.10
 - Nonebot Version: 2.0.0b5

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: 1.0.0rc3

**截图或日志**

![Screenshot_20221005_113807.jpg](https://user-images.githubusercontent.com/95957360/193976765-b0465789-e47d-45f9-b9fe-2d0591333974.jpg)

**Comment by iven13465** [comment]
> 这你应该去问这个插件，这报错和nb没有关系

不单单是这个插件，所有插件都报这个错

**Comment by yanyongyu** [comment]
这个错的traceback里就是nonebot_plugin_manager出错

**Comment by iven13465** [comment]
> 
可以了，谢谢大佬
