### ISSUE TITLE
Plugin: Github卡片

### ISSUE THREAD

**Issue by mute23-code** [nonebot/nonebot2#1309]
**插件名称：**

Github卡片

**插件功能：**

将github链接转换为卡片

**PyPI 项目名：**

nonebot-plugin-githubcard

**插件 import 包名：**

nonebot_plugin_githubcard

**插件项目仓库/主页链接：**

https://github.com/mute23-code/nonebot_plugin_githubcard

**标签：**

[{"label":"Github","color":"#11152c"},{"label":"Card","color":"#131522"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Github卡片

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: Github-#11152c, Card-#131522</li><li>✅ 项目 <a href="https://github.com/mute23-code/nonebot_plugin_githubcard">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
