### ISSUE TITLE
Plugin: 轮盘禁言小游戏

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#1310]
**插件名称：**

轮盘禁言小游戏

**插件功能：**

轮盘禁言小游戏，附送快捷禁言/解禁

**PyPI 项目名：**

nonebot-plugin-russian-ban

**插件 import 包名：**

nonebot_plugin_russian_ban

**插件项目仓库/主页链接：**

https://github.com/KarisAya/nonebot_plugin_russian_ban

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 轮盘禁言小游戏

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/KarisAya/nonebot_plugin_russian_ban">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_russian_ban/">nonebot_plugin_russian_ban</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
