### ISSUE TITLE
Adapter: Ntchat

### ISSUE THREAD

**Issue by JustUndertaker** [nonebot/nonebot2#1313]
**协议名称：**

Ntchat

**协议功能：**

pc hook的微信客户端适配

**PyPI 项目名：**

nonebot-adapter-ntchat

**协议 import 包名：**

nonebot.adapters.ntchat

**协议项目仓库/主页链接：**

https://github.com/JustUndertaker/adapter-ntchat

**标签：**

[{"label":"微信","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: Ntchat

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 微信-#ea5252</li><li>✅ 项目 <a href="https://github.com/JustUndertaker/adapter-ntchat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-adapter-ntchat/">nonebot-adapter-ntchat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
