### ISSUE TITLE
Plugin: 游戏王小程序查价

### ISSUE THREAD

**Issue by Kaguyaya** [nonebot/nonebot2#1316]
**插件名称：**

游戏王小程序查价

**插件功能：**

集换社游戏王的卡价查询

**PyPI 项目名：**

nonebot-plugin-ygo-trade

**插件 import 包名：**

nonebot_plugin_ygo_trade

**插件项目仓库/主页链接：**

https://github.com/Kaguyaya/nonebot_plugin_ygo_trade

**标签：**

[{"label":"游戏王","color":"#ea5252"},{"label":"YGO","color":"#ea5252"},{"label":"集换社","color":"#eada52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 游戏王小程序查价

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 游戏王-#ea5252, YGO-#ea5252, 集换社-#eada52</li><li>✅ 项目 <a href="https://github.com/Kaguyaya/nonebot_plugin_ygo_trade">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ygo-trade/">nonebot-plugin-ygo-trade</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
