### ISSUE TITLE
Plugin: novelai

### ISSUE THREAD

**Issue by sena-nana** [nonebot/nonebot2#1318]
**插件名称：**

novelai

**插件功能：**

调用novelai

**PyPI 项目名：**

nonebot-plugin-novelai

**插件 import 包名：**

nonebot-plugin-novelai

**插件项目仓库/主页链接：**

https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-novelai

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: novelai

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/sena-nana/MutsukiBot/tree/main/nonebot-plugin-novelai">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-novelai/">nonebot-plugin-novelai</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
你这插件打包的问题有点大啊，你自己看看你打包的压缩包里面是点啥（

**Comment by sena-nana** [comment]
我新发了一个包，应该修复了
