### ISSUE TITLE
Plugin: AI绘图

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1322]
**插件名称：**

AI绘图

**插件功能：**

使用第三方 API 的 NovelAI 绘图插件

**PyPI 项目名：**

nonebot-plugin-aidraw

**插件 import 包名：**

nonebot_plugin_aidraw

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-aidraw

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: AI绘图

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-aidraw">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-aidraw/">nonebot-plugin-aidraw</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
