### ISSUE TITLE
Plugin: bnhhsh -「不能好好说话！」

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1325]
**插件名称：**

bnhhsh -「不能好好说话！」

**插件功能：**

不对劲的拼音首字母缩写翻译工具 | 基于 RimoChan/bnhhsh

**PyPI 项目名：**

nonebot-plugin-bnhhsh

**插件 import 包名：**

nonebot_plugin_bnhhsh

**插件项目仓库/主页链接：**

https://github.com/lgc2333/nonebot-plugin-bnhhsh

**标签：**

[{"label":"a:OB V11","color":"#000000"},{"label":"t:涩涩！","color":"#ffc646"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: bnhhsh -「不能好好说话！」

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:OB V11-#000000, t:涩涩！-#ffc646</li><li>✅ 项目 <a href="https://github.com/lgc2333/nonebot-plugin-bnhhsh">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bnhhsh/">nonebot-plugin-bnhhsh</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
