### ISSUE TITLE
Plugin: ayaka衍生插件 - 小游戏合集

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1327]
**插件名称：**

ayaka衍生插件 - 小游戏合集

**插件功能：**

多功能聚合，基于ayaka插件实现：背包、 签到 、印加宝藏、生成糊文字截图、bingo、b站视频链接分析、原神接龙、成语接龙、缩写翻译

**PyPI 项目名：**

nonebot-plugin-ayaka-games

**插件 import 包名：**

ayaka_games

**插件项目仓库/主页链接：**

https://github.com/bridgeL/nonebot-plugin-ayaka-games

**标签：**

[{"label":"a:cqhttp","color":"#0c0c0c"},{"label":"a:onebot","color":"#0c0c0c"},{"label":"t:文字游戏","color":"#e36306"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ayaka衍生插件 - 小游戏合集

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#0c0c0c, a:onebot-#0c0c0c, t:文字游戏-#e36306</li><li>✅ 项目 <a href="https://github.com/bridgeL/nonebot-plugin-ayaka-games">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ayaka-games/">nonebot-plugin-ayaka-games</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
