### ISSUE TITLE
Plugin: ayaka衍生插件 - 谁是卧底

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1329]
**插件名称：**

ayaka衍生插件 - 谁是卧底

**插件功能：**

至少4人游玩，游玩前需要加bot好友，否则无法通过私聊告知关键词

**PyPI 项目名：**

nonebot-plugin-ayaka-who-is-suspect

**插件 import 包名：**

ayaka_who_is_suspect

**插件项目仓库/主页链接：**

https://github.com/bridgeL/nonebot-plugin-ayaka-who-is-suspect

**标签：**

[{"label":"a:cqhttp","color":"#000000"},{"label":"a:onebot","color":"#000000"},{"label":"t:文字游戏","color":"#e36306"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ayaka衍生插件 - 谁是卧底

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#000000, a:onebot-#000000, t:文字游戏-#e36306</li><li>✅ 项目 <a href="https://github.com/bridgeL/nonebot-plugin-ayaka-who-is-suspect">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ayaka-who-is-suspect/">nonebot-plugin-ayaka-who-is-suspect</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
