### ISSUE TITLE
Plugin: ayaka衍生插件 - 坏词撤回

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1334]
**插件名称：**

ayaka衍生插件 - 坏词撤回

**插件功能：**

撤回有问题的发言

**PyPI 项目名：**

nonebot-plugin-ayaka-prevent-bad-words

**插件 import 包名：**

ayaka_prevent_bad_words

**插件项目仓库/主页链接：**

https://github.com/bridgeL/nonebot-plugin-ayaka-prevent-bad-words

**标签：**

[{"label":"a:cqhttp","color":"#000000"},{"label":"a:onebot","color":"#000000"},{"label":"t:撤回","color":"#e36306"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ayaka衍生插件 - 坏词撤回

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#000000, a:onebot-#000000, t:撤回-#e36306</li><li>✅ 项目 <a href="https://github.com/bridgeL/nonebot-plugin-ayaka-prevent-bad-words">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ayaka-prevent-bad-words/">nonebot-plugin-ayaka-prevent-bad-words</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
