### ISSUE TITLE
Plugin: 通用抽图/语音

### ISSUE THREAD

**Issue by jcjrobert** [nonebot/nonebot2#1340]
**插件名称：**

通用抽图/语音

**插件功能：**

Nonebot2 通用抽图/语音插件

**PyPI 项目名：**

nonebot-plugin-random

**插件 import 包名：**

nonebot-plugin-random

**插件项目仓库/主页链接：**

https://github.com/jcjrobert/nonebot-plugin-random

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 通用抽图/语音

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/jcjrobert/nonebot-plugin-random">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-random/">nonebot-plugin-random</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
