### ISSUE TITLE
Plugin: NoneBot SQLAlchemy封装

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#1344]
**插件名称：**

NoneBot SQLAlchemy封装

**插件功能：**

提供简单的sqlalchemy封装

**PyPI 项目名：**

nonebot-plugin-sqlalchemy

**插件 import 包名：**

nonebot_plugin_sqlalchemy

**插件项目仓库/主页链接：**

https://github.com/ssttkkl/nonebot-plugin-sqlalchemy

**标签：**

[{"label":"t:sql","color":"#ad1717"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: NoneBot SQLAlchemy封装

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:sql-#ad1717</li><li>✅ 项目 <a href="https://github.com/ssttkkl/nonebot-plugin-sqlalchemy">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-sqlalchemy/">nonebot-plugin-sqlalchemy</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
