### ISSUE TITLE
Plugin: 用户&群聊黑名单

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#1347]
**插件名称：**

用户&群聊黑名单

**插件功能：**

另一个黑名单插件, 可批量屏蔽用户和群聊

**PyPI 项目名：**

nonebot-plugin-blacklist

**插件 import 包名：**

nonebot_plugin_blacklist

**插件项目仓库/主页链接：**

https://github.com/tkgs0/nonebot-plugin-blacklist

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 用户&群聊黑名单

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/tkgs0/nonebot-plugin-blacklist">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-blacklist/">nonebot-plugin-blacklist</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
