### ISSUE TITLE
Plugin: 反嘴臭插件

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#1349]
**插件名称：**

反嘴臭插件

**插件功能：**

检测到有用户 @机器人 并嘴臭时将其临时屏蔽(bot重启后失效), 当bot为群管理时会请对方喝昏睡红茶(禁言), 可批量增删敏感词

**PyPI 项目名：**

nonebot-plugin-antiinsult

**插件 import 包名：**

nonebot_plugin_antiinsult

**插件项目仓库/主页链接：**

https://github.com/tkgs0/nonebot-plugin-antiinsult

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:被动","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 反嘴臭插件

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, t:被动-#ea5252</li><li>✅ 项目 <a href="https://github.com/tkgs0/nonebot-plugin-antiinsult">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-antiinsult/">nonebot-plugin-antiinsult</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
