### ISSUE TITLE
Plugin: 文本生成器

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#1354]
**插件名称：**

文本生成器

**插件功能：**

抽象话、火星文等多种文本生成

**PyPI 项目名：**

nonebot-plugin-oddtext

**插件 import 包名：**

nonebot_plugin_oddtext

**插件项目仓库/主页链接：**

https://github.com/noneplugin/nonebot-plugin-oddtext

**标签：**

[{"label":"t:RCNB!","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 文本生成器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:RCNB!-#ea5252</li><li>✅ 项目 <a href="https://github.com/noneplugin/nonebot-plugin-oddtext">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-oddtext/">nonebot-plugin-oddtext</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
