### ISSUE TITLE
Plugin: 日麻寄分器

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#1356]
**插件名称：**

日麻寄分器

**插件功能：**

为群友提供日麻对局分数记录。根据马点进行PT精算，统计PT增减，支持对局与榜单查询与导出。

**PyPI 项目名：**

nonebot-plugin-mahjong-scoreboard

**插件 import 包名：**

nonebot_plugin_mahjong_scoreboard

**插件项目仓库/主页链接：**

https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard

**标签：**

[{"label":"a:onebot","color":"#4684d3"},{"label":"t:日麻","color":"#4684d3"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 日麻寄分器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#4684d3, t:日麻-#4684d3</li><li>✅ 项目 <a href="https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-mahjong-scoreboard/">nonebot-plugin-mahjong-scoreboard</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
