### ISSUE TITLE
Plugin: 二次元化图像

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1359]
**插件名称：**

二次元化图像

**插件功能：**

对三次元图像动漫化, 打开二次元的大门

**PyPI 项目名：**

nonebot-plugin-cartoon

**插件 import 包名：**

nonebot_plugin_cartoon

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-cartoon

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 二次元化图像

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-cartoon">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-cartoon/">nonebot-plugin-cartoon</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
