### ISSUE TITLE
Bug: run_preprocessor时无法使用matcher与用户交互

### ISSUE THREAD

**Issue by JustUndertaker** [nonebot/nonebot2#1363]
**描述问题：**

在run_preprocessor钩子中，无法使用matcher与用户进行交互（如matcher.send），报错为找不到current_bot

**如何复现？**

```python
weather = on_command("weather", aliases={"天气", "天气预报"}, priority=5)


@weather.handle()
async def handle_first_receive(matcher: Matcher, args: Message = CommandArg()):
    await weather.finish("520520520")


@run_preprocessor
async def _( matcher: Matcher, event: GroupMessageEvent):
    await matcher.send("77777777")
```

**期望的结果**

bot发送"77777777”给当前用户

**环境信息：**

 - OS:windows
 - Python Version: 3.10
 - Nonebot Version: 2.0.0rc1

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: 1.0rc3

**截图或日志**
![image](https://user-images.githubusercontent.com/37363867/199425679-9d328f36-a3d1-4575-b90f-23a25df2aeac.png)

**Comment by yanyongyu** [comment]
context并未在run preprocessor运行时设置
