### ISSUE TITLE
Bot: hsbot

### ISSUE THREAD

**Issue by gzy02** [nonebot/nonebot2#1367]
**机器人名称：**

hsbot

**机器人功能：**

服务于《炉石传说》玩家的机器人，上线至今已有加入13个炉石相关群聊，上千名用户使用，响应请求数万次。
数据使用：[HSreplay](https://hsreplay.net/), [Fbigame](https://hs.fbigame.com/), [Hearthstone API](https://hearthstoneapi.com/)

**机器人项目仓库/主页链接：**

https://github.com/gzy02/hsbot

**标签：**

炉石传说

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: hsbot

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 标签解码失败。<dt>请确保标签格式正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/gzy02/hsbot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
