### ISSUE TITLE
Bot: hsbot

### ISSUE THREAD

**Issue by gzy02** [nonebot/nonebot2#1368]
**机器人名称：**

hsbot

**机器人功能：**

 服务于《炉石传说》玩家的机器人，上线至今已有加入十余个个炉石相关群聊，上千名用户使用，响应请求数万次。 数据使用：HSreplay, Fbigame, Hearthstone API

**机器人项目仓库/主页链接：**

https://github.com/gzy02/hsbot

**标签：**

[{"label":"炉石传说","color":"#526fea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: hsbot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 炉石传说-#526fea</li><li>✅ 项目 <a href="https://github.com/gzy02/hsbot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
