### ISSUE TITLE
Plugin: 动漫资源获取

### ISSUE THREAD

**Issue by Melodyknit** [nonebot/nonebot2#1370]
**插件名称：**

动漫资源获取

**插件功能：**

动漫资源获取

**PyPI 项目名：**

nonebot-plugin-animeres

**插件 import 包名：**

nonebot_plugin_animeres

**插件项目仓库/主页链接：**

https://github.com/Melodyknit/nonebot_plugin_animeres

**标签：**

[{"label":"a:onebot","color":"#ec5252"},{"label":"anime","color":"#ec5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 动漫资源获取

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-plugin-animeres/ 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: onebot-#ec5252, anime-#ec5252</li><li>✅ 项目 <a href="https://github.com/Melodyknit/nonebot_plugin_animeres">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖缺少nb2和onebot适配器

**Comment by Melodyknit** [comment]
>_<好了，已经加上了
https://github.com/Melodyknit/nonebot_plugin_animeres/commit/a67d4099777415e61ce62208b50f1b6e481fcc51#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711
