### ISSUE TITLE
Plugin: Apex API Query

### ISSUE THREAD

**Issue by H-xiaoH** [nonebot/nonebot2#1374]
**插件名称：**

Apex API Query

**插件功能：**

Apex Legends API 查询插件

**PyPI 项目名：**

nonebot-plugin-apex-api-query

**插件 import 包名：**

nonebot_plugin_apex_api_query

**插件项目仓库/主页链接：**

https://github.com/H-xiaoH/nonebot-plugin-apex-api-query

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Apex API Query

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/H-xiaoH/nonebot-plugin-apex-api-query">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-apex-api-query/">nonebot-plugin-apex-api-query</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
尽量不要在插件内部使用requests阻塞机器人，另外你的plugin metadata写错了，缺少`__plugin_meta__ = `

**Comment by H-xiaoH** [comment]
requests 更换成 httpx 了。
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/72a5c2665c8a9edd59124da639d5e9e7d88bf395#diff-5127cc56447c8318bf819f6cd19c3aa9f3271bbe480aebbca59bd7b4fe071c59

**Comment by yanyongyu** [comment]
`__plugin_meta__ = PluginMetadata(xxxxx)`改错了啊（

**Comment by H-xiaoH** [comment]
改好了。（
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/commit/347763bd778326c879e369bd59a32910ff16a195#diff-5127cc56447c8318bf819f6cd19c3aa9f3271bbe480aebbca59bd7b4fe071c59
