### ISSUE TITLE
和风天气插件问题

### ISSUE THREAD

**Issue by Lujiawenn** [nonebot/nonebot2#1376]
**描述问题：**
安装完和风插件之后，nonebot启动失败

**如何复现？**

1.安装插件：nb plugin install nonebot-plugin-heweather
2. 在配置文件中配置QWEATHER_APIKEY和QWEATHER_APITYPE参数
3. 启动

**环境信息：**

 - OS:win 11
 - Python Version: 3.10
 - Nonebot Version: 2.0.0

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本:1.0.0

**截图或日志**

![image](https://user-images.githubusercontent.com/94944974/200556023-07d4bbc3-2da6-47bc-8be8-a70f0e0e4b86.png)

**Comment by Lujiawenn** [comment]
> See: [nonebot/discussions#13 (comment)](https://github.com/nonebot/discussions/discussions/13#discussioncomment-1159147)

我将汇总里提到的那段代码放到了bot.py中nonebot.run()方法之前还是不行。请问汇总里面所提到的在nonebot.run()之前导入是怎么做？

**Comment by yanyongyu** [comment]
可能是uvicorn新版更改了一些方法，你或者可以尝试关闭reload模式，在env文件里关闭fastapi reload
