### ISSUE TITLE
Bot: Bread Dog Bot

### ISSUE THREAD

**Issue by Qianyiovo** [nonebot/nonebot2#1379]
**机器人名称：**

Bread Dog Bot

**机器人功能：**

Terraria TShock QQ 机器人

**机器人项目仓库/主页链接：**

https://github.com/Qianyiovo/bread_dog_bot

**标签：**

[{"label":"TShock","color":"#ea5252"},{"label":"泰拉瑞亚","color":"#5dea52"},{"label":"Terraria","color":"#5dea52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: Bread Dog Bot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: TShock-#ea5252, 泰拉瑞亚-#5dea52, Terraria-#5dea52</li><li>✅ 项目 <a href="https://github.com/Qianyiovo/bread_dog_bot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
