### ISSUE TITLE
Plugin: b站用户直播号、粉丝、舰团数查询

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1383]
**插件名称：**

b站用户直播号、粉丝、舰团数查询

**插件功能：**

调用b站官方API获取用户直播号、粉丝、舰团数（文本形式返回）

**PyPI 项目名：**

nonebot-plugin-searchBiliInfo

**插件 import 包名：**

nonebot-plugin-searchBiliInfo

**插件项目仓库/主页链接：**

[https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo)

**标签：**

[{"label":"t:bilibili","color":"#e55d80"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ homepage: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ tags: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by Ikaros-521** [comment]
项目 主页可以访问，请问为什么会返回none

**Comment by Ikaros-521** [comment]
重新发起
