### ISSUE TITLE
Plugin: b站用户直播号、粉丝、舰团数查询

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1384]
**插件名称：**

b站用户直播号、粉丝、舰团数查询

**插件功能：**

调用b站官方API获取用户直播号、粉丝、舰团数（文本形式返回）

**PyPI 项目名：**

nonebot-plugin-searchBiliInfo

**插件 import 包名：**

nonebot_plugin_searchBiliInfo

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo

**标签：**

[{"label":"bilibili","color":"#e55d80"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: b站用户直播号、粉丝、舰团数查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: bilibili-#e55d80</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-searchBiliInfo/">nonebot-plugin-searchBiliInfo</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
