### ISSUE TITLE
Bot: 早苗&澪&浅羽

### ISSUE THREAD

**Issue by Hoshinonyaruko** [nonebot/nonebot2#1386]
**机器人名称：**

早苗&澪&浅羽

**机器人功能：**

老牌古董机器人,从酷Q插件重构来的

**机器人项目仓库/主页链接：**

https://github.com/Hoshinonyaruko/SanaeBot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: 早苗&澪&浅羽

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Hoshinonyaruko/SanaeBot/blob/main/README.md">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
你这bot不算是nb2写的啊
