### ISSUE TITLE
Plugin: Colab-NovelAI

### ISSUE THREAD

**Issue by EtherLeaF** [nonebot/nonebot2#1389]
**插件名称：**

Colab-NovelAI

**插件功能：**

解放你的双手，让Colab持续给你提供算力生产色图！

**PyPI 项目名：**

nonebot-plugin-colab-novelai

**插件 import 包名：**

nonebot_plugin_colab_novelai

**插件项目仓库/主页链接：**

https://github.com/EtherLeaF/nonebot-plugin-colab-novelai

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:NovelAI","color":"#eacd52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Colab-NovelAI

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:NovelAI-#eacd52</li><li>✅ 项目 <a href="https://github.com/EtherLeaF/nonebot-plugin-colab-novelai">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-colab-novelai/">nonebot-plugin-colab-novelai</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
