### ISSUE TITLE
Bug: 发送窗口抖动消息，在msg中是无消息内容的，如果通过[0]索引或报错

### ISSUE THREAD

**Issue by anshingy** [nonebot/nonebot2#139]
cqhttp包下bot.py模块中    first_msg_seg = event.message[0] 超出索引

问题如上，另外建议连续二次索引时增加第一次索引的默认值防止第二次索引超出，state["_prefix"]["command"] in commands

**Comment by yanyongyu** [comment]
窗口抖动消息应该有[CQ:poke]才对

**Comment by yanyongyu** [comment]
能否提供一下cqhttp实现以及复现方法信息

二次索引这边都做了长度判断以及message长度补充确保长度>0

**Comment by yanyongyu** [comment]
`go-cqhttp` 上报类型错误已经反馈并修复，发布后及时更新最新版本，`nonebot` 这边也做了处理确保上报array为`[]`时进行正确处理
