### ISSUE TITLE
Feature: 希望提供插件管理功能

### ISSUE THREAD

**Issue by p0ise** [nonebot/nonebot2#1403]
使用插件时，感觉插件管理比较混乱，使用时会出现一些问题：

1. 插件配置和全局配置混在一起。
2. 插件之间的实现不能良好隔离，比如可能都使用了同一个命令。

希望能够增加**插件管理系统**，实现以下功能：

1. 每个插件应该有自己独立的配置文件，或者在全局对不同插件的配置进行某种隔离。
2. 插件实现的命令可以考虑在全局注册，避免隐式冲突。或者插件只提供功能接口，由框架层面管理不同接口对应的命令。
3. 提供细粒度的插件开关接口，比如控制某个插件的某些功能对部分用户或群开启。开关接口可以由框架管理，也可以由特定插件管理。

**Comment by yanyongyu** [comment]
1. 并不会考虑提供独立配置文件，增加配置管理难度。目前的配置方式是考虑到了虚拟化容器部署方案的最便捷配置方式。在同一个dotenv文件内并不会出现混淆问题，你可以通过分段或者加注释的方式提高可读性。
2. 框架本身就允许多个插件注册同一个命令，这是by-design行为，插件可以根据不同rule或者permission来执行同一个命令的不同handle方式。
3. 插件开关目前做不到，目前框架并不能很好的收集到插件注册的所有信息，也无法对插件进行关闭的操作，框架本体也不会干预插件的行为。商店有继承插件开关管理的[社区插件](https://github.com/nonepkg/nonebot-plugin-manager)，至于可用性请自行验证。
