### ISSUE TITLE
Plugin: b站用户信息查询

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1409]
**插件名称：**

b站用户信息查询

**插件功能：**

查询b站用户粉丝、舰团信息；直播收益数据；直播观看信息；通过关键词搜昵称、UID等

**PyPI 项目名：**

nonebot-plugin-searchBiliInfo

**插件 import 包名：**

nonebot_plugin_searchBiliInfo

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo

**标签：**

[{"label":"bilibili","color":"#e55d80"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: b站用户信息查询

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ PyPI 项目名 nonebot-plugin-searchBiliInfo 加包名 nonebot_plugin_searchBiliInfo 的值与商店重复。<dt>请确保没有重复发布。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: bilibili-#e55d80</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-searchBiliInfo/">nonebot-plugin-searchBiliInfo</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by Ikaros-521** [comment]
针对 https://github.com/nonebot/nonebot2/issues/1384 
b站用户直播号、粉丝、舰团数查询
进行的更新

**Comment by yanyongyu** [comment]
更新请提交pr
