### ISSUE TITLE
Bug: 开启鉴权后，在env里设置了正确的access token，可以接受消息，无法发送消息

### ISSUE THREAD

**Issue by LollipopKit** [nonebot/nonebot2#141]
**描述问题：**

开启鉴权后，在env里设置了正确的access token，可以接受消息（说明access token无误），却无法发送消息
确认token无误，因为“没有”显示token错误的log（[WARNING] nonebot | CQHTTP | Authorization Header is invalid）

**如何复现？**

1. 使用go cqhttp
2. config.hjson配置access_token为abc123
3. nonebot项目文件夹下env.dev新增access_token=abc123
4. 运行nonebot，初始化时可以看见正确读取了token
5. 触发nonebot设置的trigger，nonebot和cqhttp内都无法看见发送消息的log，消息也的确没有发送出去

**期望的结果**

触发on_command等触发器后成功发送消息，cqhttp和nonebot都应该可见发送的log

**环境信息：**

 - OS: debian10
 - Python Version: 3.7.3
 - Nonebot Version: 2.0.0a7

**截图**

**Comment by lengthmin** [comment]
没有复现

- gocqhttp Version: go-cqhttp-v0.9.36-fix3-windows-amd64
- Nonebot Version: 2.0.0a7

配置：
![image](https://user-images.githubusercontent.com/13938334/103621733-9e8e7600-4f70-11eb-8fd6-318f012da6f6.png)

![image](https://user-images.githubusercontent.com/13938334/103621670-86b6f200-4f70-11eb-8509-8f9d8ec15947.png)

版本：
![image](https://user-images.githubusercontent.com/13938334/103621805-b9f98100-4f70-11eb-9794-24004b9488a8.png)
![image](https://user-images.githubusercontent.com/13938334/103621816-bfef6200-4f70-11eb-9dff-26e71716400c.png)


运行结果：

![image](https://user-images.githubusercontent.com/13938334/103621524-4f484580-4f70-11eb-9b85-909a5cd1aaf6.png)

![image](https://user-images.githubusercontent.com/13938334/103621594-67b86000-4f70-11eb-83cb-ee4d467fdd31.png)

**Comment by LollipopKit** [comment]
我懵了
![image](https://user-images.githubusercontent.com/10864310/103623831-9dab1380-4f73-11eb-9f8c-7123ff09c1aa.png)
![image](https://user-images.githubusercontent.com/10864310/103623958-d21ecf80-4f73-11eb-9f41-8e42ddfdf7c9.png)
![image](https://user-images.githubusercontent.com/10864310/103624062-f8dd0600-4f73-11eb-940f-0d6bdd693ec7.png)
是开启了built in plugin
![image](https://user-images.githubusercontent.com/10864310/103624135-0befd600-4f74-11eb-99d7-12d9bbcf8b31.png)

**Comment by lengthmin** [comment]
关掉 `access_token` 后就能使用了？

**Comment by lengthmin** [comment]
贴一下 nonebot 这边接收消息的日志呢？

**Comment by LollipopKit** [comment]
感觉可能是python或者系统的问题
刚才依次操作
rm-rf venv，
deactivate， 
virtualenv venv，
pip3 install nb-cli，
nb create，
把旧项目plugins文件夹复制到新建的项目里来尝试解决问题，结果出现如下问题：
![image](https://user-images.githubusercontent.com/10864310/103627963-4314b600-4f79-11eb-83fe-f95c58d12688.png)

尝试了`pip3 install nonebot2==2.0.0a7 或 pip3 install nb-cli==0.3.0`，错误同上

重启一次，就自己好了，能正常发送信息：
![image](https://user-images.githubusercontent.com/10864310/103627594-d26d9980-4f78-11eb-8d18-f85ae0d3ef7c.png)
