### ISSUE TITLE
Bot: 云崽Bot

### ISSUE THREAD

**Issue by Duoream** [nonebot/nonebot2#1411]
**机器人名称：**

云崽Bot

**机器人功能：**

原神机器人，提供原神查询服务和一堆有用没用的插件功能

**机器人项目仓库/主页链接：**

https://github.com/Le-niao/Yunzai-Bot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: 云崽Bot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Le-niao/Yunzai-Bot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
我寻思，这也没看见有半毛钱和nb有关啊

**Comment by synodriver** [comment]
甚至不含py
