### ISSUE TITLE
Feature: 32yytag支持

### ISSUE THREAD

**Issue by KanoYL** [nonebot/nonebot2#1418]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

没有32yytag

**描述你所需要的特性：**

更新32yytag

私通开后门是吧

**Comment by mnixry** [comment]
?

**Comment by yanyongyu** [comment]
？什么东西

**Comment by watermellye** [comment]
群友不懂事发着玩的，抱歉打扰了

**Comment by mnixry** [comment]
> 群友不懂事发着玩的，抱歉打扰了

~~ellye 🥵~~ 草 为什么会把issue发到这

**Comment by watermellye** [comment]
![C01C45DAA784CD89554454210C697B5A](https://user-images.githubusercontent.com/22909197/203730022-f5edcd8f-d044-43c6-81da-3b81f7ec0ed3.jpg)

**Comment by mnixry** [comment]
草 ~~好活 下次别整了~~

/cc @maxesisn
