### ISSUE TITLE
Plugin: 记事本

### ISSUE THREAD

**Issue by Passerby-D** [nonebot/nonebot2#1419]
**插件名称：**

记事本

**插件功能：**

一个有提醒功能的记事本

**PyPI 项目名：**

nonebot-plugin-note

**插件 import 包名：**

nonebot_plugin_note

**插件项目仓库/主页链接：**

https://github.com/Passerby-D/nonebot_plugin_note

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 记事本

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Passerby-D/nonebot_plugin_note">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-note/">nonebot-plugin-note</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件依赖写的有问题 `PIL` -> `pillow`, `nonebot` -> `nonebot2`

**Comment by Passerby-D** [comment]
哦哦哦哦哦
刚刚在pypi上改过了
我需要重新issue一次吗

**Comment by yanyongyu** [comment]
不需要

**Comment by Passerby-D** [comment]
那我还需要做什么才能成功发布
