### ISSUE TITLE
Plugin: 原神前瞻直播兑换码查询

### ISSUE THREAD

**Issue by monsterxcn** [nonebot/nonebot2#1421]
**插件名称：**

原神前瞻直播兑换码查询

**插件功能：**

原神前瞻直播兑换码查询，数据来自米哈游官方接口

**PyPI 项目名：**

nonebot-plugin-gscode

**插件 import 包名：**

nonebot_plugin_gscode

**插件项目仓库/主页链接：**

https://github.com/monsterxcn/nonebot-plugin-gscode

**标签：**

[{"label": "t:Genshin", "color": "#ffd49f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 原神前瞻直播兑换码查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:Genshin-#ffd49f</li><li>✅ 项目 <a href="https://github.com/monsterxcn/nonebot-plugin-gscode">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-gscode/">nonebot-plugin-gscode</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
readme里面有个小问题`python3 -m nb_cli plugin install`或者`nb plugin install`

**Comment by monsterxcn** [comment]
OK，有空改一下
