### ISSUE TITLE
Bug: 无法正常导入 def Keyword()

### ISSUE THREAD

**Issue by EnderKC** [nonebot/nonebot2#1428]
**描述问题：**

无法正常导入 def Keyword()

**如何复现？**

from nonebot.params import Keyword

**期望的结果**

可以正常导入不会报错

**环境信息：**

 - OS: [Windows 10]
 - Python Version: [3.10.4]
 - Nonebot Version: [2.1.5]

**协议端信息：**

 - 协议端: [go-cqhttp]

**截图或日志**
![image](https://user-images.githubusercontent.com/117884530/204497720-83f27f25-3534-478b-86b0-f79cf9039c28.png)

**Comment by yanyongyu** [comment]
运行也报错？

**Comment by EnderKC** [comment]
会报错
![image](https://user-images.githubusercontent.com/117884530/204533842-3d6c46e7-a5ce-4131-aded-b72782246edb.png)

**Comment by EnderKC** [comment]
可以了，换一个虚拟环境重新安装就可以了
