### ISSUE TITLE
Plugin: b站图片下载

### ISSUE THREAD

**Issue by jcjrobert** [nonebot/nonebot2#1429]
**插件名称：**

b站图片下载

**插件功能：**

b站封面提取，动态图片/专栏图片下载

**PyPI 项目名：**

nonebot-plugin-bilibili-image

**插件 import 包名：**

nonebot-plugin-bilibili-image

**插件项目仓库/主页链接：**

https://github.com/jcjrobert/nonebot-plugin-bilibili-image

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: b站图片下载

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/jcjrobert/nonebot-plugin-bilibili-image">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bilibili-image/">nonebot-plugin-bilibili-image</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
