### ISSUE TITLE
Plugin: 动画截图追溯来源

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1433]
**插件名称：**

动画截图追溯来源

**插件功能：**

调用trace.moe的API查询动画截图源自的作品名和时间段 

**PyPI 项目名：**

nonebot-plugin-trace-moe

**插件 import 包名：**

nonebot_plugin_trace_moe

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_trace_moe

**标签：**

[{"label":"a:onebot","color":"#191919"},{"label":"t:trace","color":"#191919"},{"label":"t:image","color":"#00a0ff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 动画截图追溯来源

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#191919, t:trace-#191919, t:image-#00a0ff</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_trace_moe">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-trace-moe/">nonebot-plugin-trace-moe</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
