### ISSUE TITLE
Plugin: 免费快捷点歌插件

### ISSUE THREAD

**Issue by ZYKsslm** [nonebot/nonebot2#1435]
**插件名称：**

免费快捷点歌插件

**插件功能：**

一个用于nonebot2的点歌插件。操作简单粗暴，交互简洁易懂.

**PyPI 项目名：**

nonebot-plugin-zyk-music

**插件 import 包名：**

nonebot_plugin_zyk_music

**插件项目仓库/主页链接：**

https://github.com/ZYKsslm/nonebot_plugin_zyk_music

**标签：**

[{"label":"Free","color":"#26d019"},{"label":"Simple","color":"#b8c10d"},{"label":"Music","color":"#0d92c1"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 免费快捷点歌插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Free-#26d019, Simple-#b8c10d, Music-#0d92c1</li><li>✅ 项目 <a href="https://github.com/ZYKsslm/nonebot_plugin_zyk_music">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-zyk-music/">nonebot-plugin-zyk-music</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
