### ISSUE TITLE
Plugin: ChatGPT

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1438]
**插件名称：**

ChatGPT

**插件功能：**

AI 聊天对话

**PyPI 项目名：**

nonebot-plugin-chatgpt

**插件 import 包名：**

nonebot_plugin_chatgpt

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-chatgpt

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ChatGPT

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://pypi.org/project/nonebot-plugin-chatgpt/">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatgpt/">nonebot-plugin-chatgpt</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
