### ISSUE TITLE
Plugin: 基于OpenAI的AI聊天

### ISSUE THREAD

**Issue by InariInDream** [nonebot/nonebot2#1440]
**插件名称：**

基于OpenAI的AI聊天

**插件功能：**

另一个AI聊天对话

**PyPI 项目名：**

nonebot-plugin-openai 

**插件 import 包名：**

nonebot_plugin_openai 

**插件项目仓库/主页链接：**

https://github.com/InariInDream/nonebot_plugin_openai

**标签：**

[{"label":"AI聊天","color":"#3b5fdd"},{"label":"chat","color":"#62e8d0"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 基于OpenAI的AI聊天

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: AI聊天-#3b5fdd, chat-#62e8d0</li><li>✅ 项目 <a href="https://github.com/InariInDream/nonebot_plugin_openai">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-openai/">nonebot-plugin-openai</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
