### ISSUE TITLE
Plugin: 雀魂信息查询

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#1442]
**插件名称：**

雀魂信息查询

**插件功能：**

根据牌谱屋的数据查询雀魂账号信息

**PyPI 项目名：**

nonebot-plugin-majsoul

**插件 import 包名：**

nonebot_plugin_majsoul

**插件项目仓库/主页链接：**

https://github.com/ssttkkl/nonebot-plugin-majsoul

**标签：**

[{"label":"t:majsoul","color":"#e54141"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 雀魂信息查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:majsoul-#e54141</li><li>✅ 项目 <a href="https://github.com/ssttkkl/nonebot-plugin-majsoul">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-majsoul/">nonebot-plugin-majsoul</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
