### ISSUE TITLE
Plugin: 图片背景消除

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1445]
**插件名称：**

图片背景消除

**插件功能：**

适用于onebot v11的基于remove.bg的图片背景消除插件

**PyPI 项目名：**

nonebot-plugin-remove-bg

**插件 import 包名：**

nonebot_plugin_remove_bg

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_remove_bg

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:img","color":"#111111"},{"label":"t:removeBG","color":"#7a7a7a"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 图片背景消除

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:img-#111111, t:removeBG-#7a7a7a</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_remove_bg">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-remove-bg/">nonebot-plugin-remove-bg</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
