### ISSUE TITLE
Plugin: 全群广播

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1449]
**插件名称：**

全群广播

**插件功能：**

将你的消息广播到全部群聊中

**PyPI 项目名：**

nonebot-plugin-broadcast

**插件 import 包名：**

nonebot_plugin_broadcast

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-broadcast

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 全群广播

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-broadcast">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-broadcast/">nonebot-plugin-broadcast</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
