### ISSUE TITLE
Plugin: 汇率换算

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1451]
**插件名称：**

汇率换算

**插件功能：**

支持汇率换算与汇率查询

**PyPI 项目名：**

nonebot-plugin-exchangerate

**插件 import 包名：**

nonebot_plugin_exchangerate

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-exchangerate

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 汇率换算

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-exchangerate">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-exchangerate/">nonebot-plugin-exchangerate</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
