### ISSUE TITLE
Feature: 更易于扩展的事件响应器

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1455]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

在编写 Bot 的时候，我们可能会需要定制事件响应器，为它添加上新属性和新方法。然而在目前的模式下，如果要扩展事件响应器的功能，会是一件比较麻烦的事情，而且很有可能出现奇奇怪怪的问题。

**描述你所需要的特性：**

希望能够使事件响应器更易于扩展。

**Comment by yanyongyu** [comment]
目前并不推荐修改事件响应器，包括添加属性等操作（为什么总有人想要改内部类型）。应该使用依赖注入或者直接调用函数，全局的信息可以储存在事件响应器的state/state factory中，或者存储于全局config中。

**Comment by A-kirami** [comment]
> 目前并不推荐修改事件响应器，包括添加属性等操作（~为什么总有人想要改内部类型~）。应该使用依赖注入或者直接调用函数，全局的信息可以储存在事件响应器的state/state factory中，或者存储于全局config中。

因为如果基于 nb2 编写 bot 的话，随着自定义程度的加深，有些特性已经无法（或者较难）在外部实现，最后总会不可避免的~走向魔改~深入 nb2 内部（~或者打上难看的🐒补丁~）。

**Comment by yanyongyu** [comment]
如果你非要自行扩展的话，建议你继承Matcher类然后覆盖new和run方法，另外插件自行使用你的类型创建响应器
