### ISSUE TITLE
Plugin: 熊老板

### ISSUE THREAD

**Issue by ReiiNoki** [nonebot/nonebot2#1459]
**插件名称：**

熊老板

**插件功能：**

一个获取斯普拉遁3场地信息用的nonebot插件

**PyPI 项目名：**

nonebot-plugin-kuma-san

**插件 import 包名：**

nonebot_plugin_kuma_san

**插件项目仓库/主页链接：**

https://github.com/ReiiNoki/nonebot-plugin-kuma-san

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 熊老板

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ReiiNoki/nonebot-plugin-kuma-san">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-kuma-san/">nonebot-plugin-kuma-san</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件打包存在问题，请检查你的package，另外缺少依赖声明`install_requires`需要`nonebot2`和`nonebot-adapter-onebot`

**Comment by ReiiNoki** [comment]
谢谢，我第一次做插件，查查看怎么做
