### ISSUE TITLE
Plugin: multi-ChatGPT

### ISSUE THREAD

**Issue by chrisyy2003** [nonebot/nonebot2#1461]
**插件名称：**

multi-ChatGPT

**插件功能：**

多账户的ChatGPT插件

**PyPI 项目名：**

nonebot-plugin-multi-chatgpt

**插件 import 包名：**

nonebot_plugin_multi_chatgpt

**插件项目仓库/主页链接：**

https://github.com/chrisyy2003/lingyin-bot/tree/main/plugins/chatGPT

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: multi-chatGPT

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/chrisyy2003/lingyin-bot/tree/main/src/plugins/openai">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-multi-chatgpt/">nonebot-plugin-multi-chatgpt</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在你的插件依赖中正确填写`nonebot2`和`nonebot-adapter-onebot`

**Comment by chrisyy2003** [comment]
辛苦啦，这么晚
