### ISSUE TITLE
Plugin: nonebot_plugin_idiom

### ISSUE THREAD

**Issue by wsdtl** [nonebot/nonebot2#1468]
**插件名称：**

nonebot_plugin_idiom

**插件功能：**

成语接龙

**PyPI 项目名：**

nonebot-plugin-idiom

**插件 import 包名：**

nonebot_plugin_idiom

**插件项目仓库/主页链接：**

https://github.com/wsdtl/nonebot_plugin_Idiom

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_idiom

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/wsdtl/nonebot_plugin_Idiom/tree/master">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-idiom/">nonebot-plugin-idiom</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
