### ISSUE TITLE
Bug: 文档底部“在GitHub上编辑”链接

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/nonebot2#147]
**描述问题：**

`https://github.com/nonebot/nonebot2/edit/dev/archive//2.0.0a8.post2/guide/installation.html`

出现冗余`/`且结尾变为`.html`，导致无法正常着陆至对应的文档源文件页。

**如何复现？**

1. 前往 `https://v2.nonebot.dev/guide/installation.html`
2. 点击 `在 GitHub 上编辑此页`

**期望的结果**

`https://github.com/nonebot/nonebot2/edit/dev/archive/2.0.0a8.post2/guide/installation.md`

已确认为上游依赖[vuepress-theme-nonebot](https://github.com/nonebot/vuepress-theme-nonebot) 拼接URL时产生的问题，修复于[#1](https://github.com/nonebot/vuepress-theme-nonebot/pull/1) ，请求重新deploy文档页。

**Comment by yanyongyu** [comment]
已deploy
