### ISSUE TITLE
Plugin: GPT3

### ISSUE THREAD

**Issue by chrisyy2003** [nonebot/nonebot2#1479]
**插件名称：**

GPT3

**插件功能：**

openai官方api的会话插件

**PyPI 项目名：**

nonebot-plugin-gpt3

**插件 import 包名：**

nonebot-plugin-gpt3

**插件项目仓库/主页链接：**

https://github.com/chrisyy2003/lingyin-bot/tree/main/plugins/gpt3

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: GPT3

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 标签解码失败。<dt>请确保标签格式正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/chrisyy2003/lingyin-bot/tree/main/plugins/GPT3">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-gpt3/">nonebot-plugin-gpt3</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by chrisyy2003** [comment]
已修改
