### ISSUE TITLE
自动生成 api 文档

### ISSUE THREAD

**Issue by v587ygq** [nonebot/nonebot2#148]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

```python
self._server_app = FastAPI(
            debug=config.debug,
            openapi_url=None,
            docs_url=None,
            redoc_url=None,
        )
```

源码好像禁止了API文档自动生成的功能，能否改为根据配置决定？例如添加一个配置项。

因为开发时要进行 API 请求调试，所以感觉这个功能还是挺有必要的

**Comment by mnixry** [comment]
[根据FastAPI文档](https://fastapi.tiangolo.com/advanced/sub-applications/#check-the-automatic-api-docs), 你似乎可以自己挂载一个Sub Application

**Comment by yanyongyu** [comment]
这个后续可以进行支持

**Comment by yanyongyu** [comment]
已支持，下版本发布
