### ISSUE TITLE
Plugin: 只因进化录

### ISSUE THREAD

**Issue by RShock** [nonebot/nonebot2#1483]
**插件名称：**

只因进化录

**插件功能：**

q群挂机小游戏。开局一只因，进化全靠吞

**PyPI 项目名：**

nonebot-plugin-ikun-evolution

**插件 import 包名：**

nonebot_plugin_ikun_evolution

**插件项目仓库/主页链接：**

https://github.com/RShock/nonebot_plugin_ikun_evolution

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 只因进化录

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-plugin-ikun-evolution/ 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/RShock/nonebot_plugin_ikun_evolution">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
