### ISSUE TITLE
Plugin: 随机禁言

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1485]
**插件名称：**

随机禁言

**插件功能：**

适用于onebot v11的随机禁言一名群员n分钟（n通过传入数字然后随机实现）

**PyPI 项目名：**

nonebot-plugin-random-ban

**插件 import 包名：**

nonebot_plugin_random_ban

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_random_ban

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:禁言","color":"#020202"},{"label":"t:ban","color":"#ffffff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 随机禁言

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:禁言-#020202, t:ban-#ffffff</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_random_ban">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-random-ban/">nonebot-plugin-random-ban</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
