### ISSUE TITLE
Plugin: 防撤回

### ISSUE THREAD

**Issue by Jerry080801** [nonebot/nonebot2#1488]
**插件名称：**

防撤回

**插件功能：**

防撤回

**PyPI 项目名：**

nonebot-plugin-antirecall

**插件 import 包名：**

nonebot_plugin_antirecall

**插件项目仓库/主页链接：**

https://github.com/Jerry080801/nonebot-plugin-antirecall/

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 防撤回

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 群管-#ea5252, 娱乐-#ea5252</li><li>✅ 项目 <a href="https://github.com/Jerry080801/nonebot-plugin-antirecall/">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-antirecall/">nonebot-plugin-antirecall</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
