### ISSUE TITLE
Plugin: TSETTSETBOTBOT

### ISSUE THREAD

**Issue by R1ckzzzzz** [nonebot/nonebot2#1490]
**插件名称：**

TSETTSETBOTBOT

**插件功能：**

**PyPI 项目名：**

**插件 import 包名：**

**插件项目仓库/主页链接：**

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: TSETTSETBOTBOT

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ homepage: 无法匹配到数据。<dt>请确保填写该项目。</dt></li></code></pre>

---

💪 Powered by NoneBot2 Publish Bot
