### ISSUE TITLE
Docs: 移除商店中的过期插件 2023

### ISSUE THREAD

**Issue by j1g5awi** [nonebot/nonebot2#1498]
# 移除商店中的过期插件 2023

上一次：#795

计划将插件商店中仍未适配 rc 更新的插件移除，具体移除日期待定。

### Git 已适配但未在 PyPI 发版（Warning）

[ELF-RSS](https://github.com/Quan666/ELF_RSS) @Quan666
[nonebot-plugin-picsbank](https://github.com/Diaosi1111/nonebot_plugin_picsbank) @Diaosi1111

#### 使用了过时的 Export 功能（#1125）

- [ ] [nonebot-plugin-broker](https://github.com/mwbimh/nonebot_plugin_broker) @mwbimh
- [x] [nonebot-plugin-dida](https://github.com/TDK1969/nonebot_plugin_dida) @TDK1969

##### 未更新 [nonebot-plugin-apscheduler](https://github.com/nonebot/plugin-apscheduler) 依赖

- [x] [nonebot-plugin-flexperm](https://github.com/rmuchan/nonebot-plugin-flexperm) @rmuchan
- [x] [nonebot-plugin-youthstudy](https://github.com/ayanamiblhx/nonebot_plugin_youthstudy) @ayanamiblhx
- [x] [nonebot-plugin-fortune](https://github.com/KafCoppelia/nonebot_plugin_fortune) @KafCoppelia
- [x] [nonebot-plugin-what2eat](https://github.com/KafCoppelia/nonebot_plugin_what2eat) @KafCoppelia
- [x] [nonebot-plugin-morning](https://github.com/KafCoppelia/nonebot_plugin_morning) @KafCoppelia
- [x] [nonebot-plugin-today-in-history](https://github.com/AquamarineCyan/nonebot-plugin-today-in-history) @AquamarineCyan
- [ ] [nonebot-plugin-gamedraw](https://github.com/HibiKier/nonebot_plugin_gamedraw) @HibiKier
- [ ] [nonebot-plugin-todo-nlp](https://github.com/CofinCup/nonebot-plugin-todo-nlp) @CofinCup

#### 使用了过时的 State 注入参数（#1160） 

- [x] [nonebot-plugin-songpicker2](https://github.com/maxesisn/nonebot_plugin_songpicker2) @maxesisn
- [x] [nonebot-plugin-biliav](https://github.com/knva/nonebot_plugin_biliav) @knva
- [ ] [nonebot-plugin-setu2](https://github.com/NoneBot2-Ae/nonebot-plugin-setu2) @alphaAE
- [x] [nonebot-plugin-qrcode](https://github.com/kexue-z/nonebot-plugin-qrcode) @kexue-z
- [ ] [nonebot-plugin-bangumi-search](https://github.com/Ankhyty/nonebot-plugin-bangumi-search) @Ankhyty
- [x] [nonebot-plugin-offline-mahjong-helper](https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper) @Nranphy

#### 缺少依赖

- [x] [nonebot-plugin-ncm](https://github.com/kitUIN/nonebot-plugin-ncm) @kitUIN httpx
- [x] [nonebot-plugin-analysis-bilibili](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili) @mengshouer nonebot-adapter-onebot
- [ ] [nanobot-plugin-splatoon2tools](https://github.com/DrinkOolongTea/splatoon2-bot) @DrinkOolongTea httpx
- [ ] [nonebot-plugin-yulu](https://github.com/bingqiu456/nonebot-plugin-yulu) @bingqiu456 httpx
- [ ] [nonebot-plugin-eventdone](https://github.com/PadorFelice/Nonebot_plugin_eventdone) @PadorFelice nonebot2
- [x] [nonebot-plugin-maze](https://github.com/EtherLeaF/nonebot_plugin_maze) @EtherLeaF numpy
- [ ] [nonebot-plugin-arktools](https://github.com/NumberSir/nonebot_plugin_arktools) @NumberSir nonebot-plugin-apscheduler
- [x] [nonebot-plugin-firexN](https://github.com/GC-ZF/nonebot_plugin_firexN) @GC-ZF requests
- [x] [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) @GC-ZF pillow
- [x] [nonebot-plugin-moegoe](https://github.com/Yiyuiii/nonebot-plugin-moegoe) @Yiyuiii nonebot-adapter-onebot
- [x] [nonebot-plugin-workscore](https://github.com/yzyyz1387/nonebot_plugin_workscore) @yzyyz1387 httpx
- [x] [nonebot-plugin-cqsat](https://github.com/yzyyz1387/cqsat) @yzyyz1387 nonebot-plugin-apscheduler
- [x] [nonebot-plugin-warframe](https://github.com/17TheWord/nonebot-plugin-warframe) @17TheWord httpx
- [x] [nonebot-plugin-bottle](https://github.com/Todysheep/nonebot_plugin_bottle) @Todysheep requests
- [x] [nonebot-plugin-tts-gal](https://github.com/dpm12345/nonebot_plugin_tts_gal) @dpm12345 httpx
- [ ] [nonebot-plugin-masiro](https://github.com/Ankhyty/nonebot-plugin-masiro) @Ankhyty nonebot-plugin-apscheduler
- [x] [nonebot-plugin-bnhhsh](https://github.com/lgc2333/nonebot-plugin-bnhhsh) @lgc2333 pypinyin
- [x] [nonebot-plugin-repeep](https://github.com/p0ise/nonebot-plugin-repeep) @p0ise httpx
- [x] [nonebot-plugin-note](https://github.com/Passerby-D/nonebot_plugin_note) @Passerby-D nonebot-adapter-onebot
- [x] [nonebot-plugin-bilibili-image](https://github.com/jcjrobert/nonebot-plugin-bilibili-image) @jcjrobert bs4
- [ ] [nonebot-plugin-idiom](https://github.com/wsdtl/nonebot_plugin_Idiom) @wsdtl pandas
- [x] [nonebot-plugin-backup](https://github.com/Yuelioi/nonebot-plugin-backup) @Yuelioi requests
- [x] [nonebot-plugin-hitokoto](https://github.com/A-kirami/nonebot-plugin-hitokoto) @A-kirami httpx
- [x] [nonebot-plugin-bilicover](https://github.com/A-kirami/nonebot-plugin-bilicover) @A-kirami httpx
- [ ] [nonebot-plugin-mcqq-server](https://github.com/KarisAya/nonebot_plugin_mcqq_server) @KarisAya mcrcon
- [x] [nonebot_plugin_kawaii_robot](https://github.com/KarisAya/nonebot_plugin_kawaii_robot) @KarisAya httpx
- [x] [nonebot-plugin-BiliRequestAll](https://github.com/Shadow403/nonebot_plugin_BiliRequestAll) @Shadow403 requests
- [ ] [nonebot-plugin-read-60s](https://github.com/bingganhe123/60s-) @bingganhe123 nonebot-adapter-onebot
- [x] [hikari-bot](https://github.com/benx1n/HikariBot) @benx1n urllib3
- [x] [nonebot-plugin-apex-api-query](https://github.com/H-xiaoH/nonebot-plugin-apex-api-query) @H-xiaoH nonebot-adapter-onebot
- [x] [nonebot-plugin-ikun-evolution](https://github.com/RShock/nonebot_plugin_ikun_evolution) @RShock dateutil

#### 商店 module_name 与实际模块名不一致

- [ ] [nonebot-plugin-russian](https://github.com/HibiKier/nonebot_plugin_russian) @HibiKier
- [ ] [nonebot-plugin-bVideo](https://github.com/ziru-w/nonebot_plugin_bVideo) @ziru-w
- [x] [nonebot-plugin-gpt3](https://github.com/chrisyy2003/nonebot-plugin-gpt3) @chrisyy2003 

#### 其他

- [x] [nonebot-plugin-bilibilibot](https://github.com/TDK1969/nonebot_plugin_bilibilibot) @TDK1969 No module named 'nonebot_plugin_bilibilibot.bili_src
- [ ] [nonebot_plugin_arkrecord](https://github.com/zheuziihau/nonebot_plugin_arkrecord) @zheuziihau Permission denied: '/root/.arkrecord'
- [x] [nonebot-plugin-course](https://github.com/InariInDream/nonebot_plugin_course) @InariInDream setup.py
- [x] [nonebot-plugin-zyk-novelai](https://github.com/ZYKsslm/nonebot_plugin_zyk_novelai) @ZYKsslm setup.py
- [x] [nonebot-plugin-zyk-music](https://github.com/ZYKsslm/nonebot_plugin_zyk_music) @ZYKsslm setup.py
- [x] [nonebot-plugin-mystool](https://github.com/Ljzd-PRO/nonebot-plugin-mystool) @Ljzd-PRO No such file or directory
- [ ] [nonebot-plugin-multi-chatgpt](https://github.com/chrisyy2003/nonebot-plugin-multi-chatgpt) @chrisyy2003 No such file or directory
- [x] [nonebot-plugin-abstain-diary](https://github.com/Ikaros-521/nonebot_plugin_abstain_diary) @Ikaros-521 No such file or directory
- [ ] [nonebot_plugin_groupmate_waifu](https://github.com/KarisAya/nonebot_plugin_groupmate_waifu) @KarisAya No such file or directory
- [ ] [nonebot-plugin-admin](https://github.com/yzyyz1387/nonebot_plugin_admin) @yzyyz1387 No such file or directory
- [ ] [nonebot-plugin-monitor](https://github.com/cjladmin/nonebot_plugin_monitor) @cjladmin No module named 'monitor_groups'
- [x] [nonebot-plugin-lolmatch](https://github.com/Diaosi1111/nonebot_plugin_lolmatch) @Diaosi1111 nonebot_plugin_tortoise_orm = "^0"

### 待删除

- [nonebot_plugin_flash_silentsave](https://github.com/KarisAya/nonebot_plugin_flash_silentsave) @KarisAya requests
- [nonebot-plugin-magiadice](https://github.com/sena-nana/nonebot-plugin-magiadice) @sena-nana wcwidth
- [nonebot-plugin-myb-exchange](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange) @CMHopeSunshine
- [nonebot2-plugin-eth-terminal](https://github.com/Sclock/nonebot2_plugin_eth_terminal) @Sclock httpx
- [nonebot-plugin-vf](https://github.com/snowyfirefly/VirtualFriends) @snowyfirefly 上次忘删
- [nonebot-plugin-auto-teenstudy](https://github.com/ZMXC01/nonebot_plugin_auto_teenstudy) @ZMXC01 requests
- [nonebot-plugin-ykt](https://github.com/sena-nana/nonebot-plugin-ykt) @sena-nana nonebot-plugin-apscheduler
- [nonebot-plugin-xiuxian](https://github.com/s52047qwas/nonebot_plugin_xiuxian) @s52047qwas No such file or directory

### 已删除

- [nonebot-plugin-filehost](https://github.com/mnixry/nonebot-plugin-filehost) @mnixry 

## 数据来源

[Lancercmd/nonebot2-store-test](https://github.com/Lancercmd/nonebot2-store-test)

**Comment by PadorFelice** [comment]
我收到了呦~晚点会看的，秋咪。

**Comment by yzyyz1387** [comment]
- nonebot-plugin-workscore
 - nonebot-plugin-cqsat
 依赖问题已修复，并在pypi发布
（修复了需要在这里回复吗）

**Comment by lgc2333** [comment]
[nonebot-plugin-bnhhsh](https://github.com/lgc2333/nonebot-plugin-bnhhsh) 已发版

**Comment by dpm12345** [comment]
[nonebot-plugin-tts-gal](https://github.com/dpm12345/nonebot_plugin_tts_gal) 已添加依赖并发布

**Comment by rmuchan** [comment]
[nonebot-plugin-flexperm](https://github.com/rmuchan/nonebot-plugin-flexperm)已更新

**Comment by Yiyuiii** [comment]
[nonebot-plugin-moegoe](https://github.com/Yiyuiii/nonebot-plugin-moegoe)已更新依赖

**Comment by kitUIN** [comment]
[nonebot-plugin-ncm](https://github.com/kituin/nonebot-plugin-ncm)已更新依赖

**Comment by AquamarineCyan** [comment]
[nonebot-plugin-today-in-history](https://github.com/AquamarineCyan/nonebot-plugin-today-in-history)已更新依赖

**Comment by EtherLeaF** [comment]
[nonebot-plugin-maze](https://github.com/EtherLeaF/nonebot_plugin_maze)已更新依赖

**Comment by p0ise** [comment]
[nonebot-plugin-repeep](https://github.com/p0ise/nonebot-plugin-repeep)已更新依赖

**Comment by kexue-z** [comment]
[nonebot-plugin-qrcode](https://github.com/kexue-z/nonebot-plugin-qrcode) 删了吧

**Comment by j1g5awi** [comment]
@Yiyuiii 加载时就导入的包（nonebot-adapter-onebot）请别设置为可选依赖
@p0ise 请在 PyPI 更新

**Comment by kitUIN** [comment]
> @Yiyuiii 加载时就导入的包（nonebot-adapter-onebot）请别设置为可选依赖 @kitUIN 加载时就导入的包（httpx）请别设置为可选依赖 @p0ise 请在 PyPI 更新

已修改

**Comment by Yiyuiii** [comment]
已修改

**Comment by TDK1969** [comment]
[nonebot-plugin-dida](https://github.com/TDK1969/nonebot_plugin_dida)已更新，移除export机制

**Comment by GC-ZF** [comment]
[nonebot-plugin-firexN](https://github.com/GC-ZF/nonebot_plugin_firexN) 已添加 requests
 [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) 已添加F pillow
并更新Github仓库，上传pypi

**Comment by Nranphy** [comment]
[nonebot-plugin-offline-mahjong-helper](https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper) 已删除State注入并发版

**Comment by j1g5awi** [comment]
@Yiyuiii 仍为可选依赖
@TDK1969 没有删除 import https://github.com/TDK1969/nonebot_plugin_dida/blob/81aaaf1cb3105012a8e1e49e9ce3e44c88a3a9a0/__init__.py#LL4C51-L4C51
@GC-ZF [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) 还缺 requests
@Nranphy import 不止一处没删 https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper/blob/f9465d757cf0c35743087d7ea7b8e7fc00fab275/appoint/__init__.py#L3

**Comment by GC-ZF** [comment]
> @GC-ZF [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) 还缺 requests

已更改

**Comment by KarisAya** [comment]
[nonebot_plugin_flash_silentsave](https://github.com/KarisAya/nonebot_plugin_flash_silentsave)这个插件没用了可以删掉

**Comment by TDK1969** [comment]
> @TDK1969 没有删除 import https://github.com/TDK1969/nonebot_plugin_dida/blob/81aaaf1cb3105012a8e1e49e9ce3e44c88a3a9a0/__init__.py#LL4C51-L4C51

已修改

**Comment by sena-nana** [comment]
magiadice插件需要重写，可以先删掉

**Comment by CMHopeSunshine** [comment]
[nonebot_plugin_myb_exchange](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange)也要重写，先删掉吧

**Comment by Nranphy** [comment]
> @Yiyuiii 仍为可选依赖 @TDK1969 没有删除 import https://github.com/TDK1969/nonebot_plugin_dida/blob/81aaaf1cb3105012a8e1e49e9ce3e44c88a3a9a0/__init__.py#LL4C51-L4C51 @GC-ZF [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) 还缺 requests @Nranphy import 不止一处没删 https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper/blob/f9465d757cf0c35743087d7ea7b8e7fc00fab275/appoint/__init__.py#L3

[nonebot-plugin-offline-mahjong-helper](https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper) 已重新修改，删除了对应import内容，已发版

**Comment by Yiyuiii** [comment]
> @Yiyuiii 仍为可选依赖 @TDK1969 没有删除 import https://github.com/TDK1969/nonebot_plugin_dida/blob/81aaaf1cb3105012a8e1e49e9ce3e44c88a3a9a0/__init__.py#LL4C51-L4C51 @GC-ZF [nonebot-plugin-bfinfo](https://github.com/GC-ZF/nonebot_plugin_bfinfo) 还缺 requests @Nranphy import 不止一处没删 https://github.com/Nranphy/nonebot_plugin_offline_mahjong_helper/blob/f9465d757cf0c35743087d7ea7b8e7fc00fab275/appoint/__init__.py#L3

应该是修改过了吧，还报错的话我也不知道了

**Comment by Shadow403** [comment]
[nonebot-plugin-BiliRequestAll](https://github.com/Shadow403/nonebot_plugin_BiliRequestAll)      依赖已更新

**Comment by j1g5awi** [comment]
@Yiyuiii https://github.com/Yiyuiii/nonebot-plugin-moegoe/blob/adfaf0c4df549528b43303e02d9689fda8f9a1b1/pyproject.toml#L23
@Nranphy 缺少 httpx 依赖

**Comment by Yiyuiii** [comment]
> @Yiyuiii https://github.com/Yiyuiii/nonebot-plugin-moegoe/blob/adfaf0c4df549528b43303e02d9689fda8f9a1b1/pyproject.toml#L23 @Nranphy 缺少 httpx 依赖

已修改

**Comment by shoucandanghehe** [comment]
[nonebot-plugin-tetris-stats](https://github.com/shoucandanghehe/nonebot-plugin-tetris-stats) PyPI已发版

**Comment by j1g5awi** [comment]
cc @ZM25XC @Ljzd-PRO @Ikaros-521 @s52047qwas @cjladmin @snowyfirefly

**Comment by Nranphy** [comment]
> @Yiyuiii https://github.com/Yiyuiii/nonebot-plugin-moegoe/blob/adfaf0c4df549528b43303e02d9689fda8f9a1b1/pyproject.toml#L23 @Nranphy 缺少 httpx 依赖

已修改发版

**Comment by ZYKsslm** [comment]
setup有什么问题

**Comment by j1g5awi** [comment]
@ZYKsslm https://github.com/ZYKsslm/nonebot_plugin_zyk_novelai/blob/f9932d362a15d9ca6cb3198634ba96c9ab87e502/setup.py#L13 install_requires 填写错误，见 https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#declaring-required-dependency

**Comment by Nranphy** [comment]
[nonebot-plugin-leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2) 已在PyPI发版

**Comment by j1g5awi** [comment]
@Nranphy 你 [nonebot-plugin-leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2)  发的版还是有 State

**Comment by ZYKsslm** [comment]
已重写setup

**Comment by Ikaros-521** [comment]
> cc @ZM25XC @Ljzd-PRO @Ikaros-521 @s52047qwas @cjladmin @snowyfirefly
 
已修复问题并重新发布  [nonebot_plugin_abstain_diary](https://github.com/Ikaros-521/nonebot_plugin_abstain_diary)

**Comment by CherryCherries** [comment]
[nonebot-plugin-abstract](https://github.com/CherryCherries/nonebot-plugin-abstract) 已在pypi发版

**Comment by Ljzd-PRO** [comment]
[nonebot-plugin-mystool](https://github.com/Ljzd-PRO/nonebot-plugin-mystool) 已修复

**Comment by InariInDream** [comment]
setup.py是什么问题，需要将setup.py一并上传到repository吗

**Comment by j1g5awi** [comment]
@InariInDream 你的 setup.py 第 18 行少了个逗号。

**Comment by InariInDream** [comment]
> @InariInDream 你的 setup.py 第 18 行少了个逗号。

已修改并在pypi发版

**Comment by p0ise** [comment]
> @Yiyuiii 加载时就导入的包（nonebot-adapter-onebot）请别设置为可选依赖 @kitUIN 加载时就导入的包（httpx）请别设置为可选依赖 @p0ise 请在 PyPI 更新

已在PyPI更新

**Comment by Todysheep** [comment]
[github.com/todysheep/nonebot_plugin_bottle](nonebot_plugin_bottle)已修复

**Comment by Nranphy** [comment]
> @Nranphy 你 [nonebot-plugin-leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2) 发的版还是有 State

[nonebot-plugin-leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2) 已经再次改好发版了喵

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query

**Comment by TDK1969** [comment]
[nonebot-plugin-bilibilibot](https://github.com/TDK1969/nonebot_plugin_bilibilibot)的import错误已经修复

**Comment by j1g5awi** [comment]
@Nranphy 很遗憾，你依赖的 nonebot-plugin-htmlrender 版本使用了过时的 Export 功能
@H-xiaoH 请在 PyPI 更新
@TDK1969 ModuleNotFoundError: No module named 'lxml'

**Comment by TDK1969** [comment]
> @TDK1969 ModuleNotFoundError: No module named 'lxml'
已修复

**Comment by Nranphy** [comment]
> 
已经修改好了
大佬辛苦了qwq

**Comment by sena-nana** [comment]
nonebot-plugin-ykt插件也删掉吧，这个插件已经不再维护了

**Comment by benx1n** [comment]
已移除[hikari-bot](https://github.com/benx1n/HikariBot)中的无效依赖urllib3

**Comment by s52047qwas** [comment]
暂时没打算更新自动下载配置文件的功能，可删除

**Comment by KafCoppelia** [comment]
- [ ] [nonebot-plugin-fortune](https://github.com/KafCoppelia/nonebot_plugin_fortune) 已进入测试阶段
- [ ] [nonebot-plugin-what2eat](https://github.com/KafCoppelia/nonebot_plugin_what2eat) 已进入测试阶段
- [ ] [nonebot-plugin-morning](https://github.com/KafCoppelia/nonebot_plugin_morning) 已进入测试阶段

**Comment by A-kirami** [comment]
已解决：
[nonebot-plugin-hitokoto](https://github.com/A-kirami/nonebot-plugin-hitokoto) 
[nonebot-plugin-bilicover](https://github.com/A-kirami/nonebot-plugin-bilicover)

**Comment by H-xiaoH** [comment]
https://pypi.org/project/nonebot-plugin-apex-api-query/22.12.26/

**Comment by Yuelioi** [comment]
缺少依赖
nonebot-plugin-backup @Yuelioi requests
 

已更改
https://github.com/Yuelioi/nonebot-plugin-backup/blob/master/setup.py

**Comment by knva** [comment]
DONE.
https://github.com/knva/nonebot_plugin_biliav

**Comment by ayanamiblhx** [comment]
[nonebot-plugin-youthstudy](https://github.com/ayanamiblhx/nonebot_plugin_youthstudy)
已更新依赖

**Comment by KarisAya** [comment]
[nonebot_plugin_groupmate_waifu](https://github.com/KarisAya/nonebot_plugin_groupmate_waifu) @KarisAya No such file or directory
这个需要怎么做

**Comment by jcjrobert** [comment]
已添加bs4并在pypi发布新版
https://github.com/jcjrobert/nonebot-plugin-bilibili-image/blob/master/setup.py

**Comment by j1g5awi** [comment]
@KarisAya https://github.com/KarisAya/nonebot_plugin_groupmate_waifu/blob/eaabe899921dcc9e38ee64574a5e9d5c36b3a257/__init__.py#L46

**Comment by kexue-z** [comment]
> [nonebot-plugin-qrcode](https://github.com/kexue-z/nonebot-plugin-qrcode) 删了吧

不删了把，更新了~

**Comment by Passerby-D** [comment]
[https://github.com/Passerby-D/nonebot_plugin_note](url) 已更新依赖

**Comment by HibiKier** [comment]
[nonebot-plugin-gamedraw](https://github.com/HibiKier/nonebot_plugin_gamedraw) 已更新

**Comment by j1g5awi** [comment]
@HibiKier bs4

**Comment by CofinCup** [comment]
[nonebot-plugin-todo-nlp](https://github.com/CofinCup/nonebot-plugin-todo-nlp/)已更新

**Comment by bingqiu456** [comment]
[nonebot-plugin-yulu](https://github.com/bingqiu456/nonebot-plugin-yulu) 已更新

**Comment by HibiKier** [comment]
> @HibiKier bs4

已更新

**Comment by HibiKier** [comment]
商店 module_name 与实际模块名不一致

 [nonebot-plugin-russian](https://github.com/HibiKier/nonebot_plugin_russian) @HibiKier

这是是指？
![图片](https://user-images.githubusercontent.com/45528451/213845320-30f7615f-5093-4f3e-ab19-750c96d245da.png)
![图片](https://user-images.githubusercontent.com/45528451/213845322-1f557a68-5bb3-4669-8329-3317525465e1.png)
![图片](https://user-images.githubusercontent.com/45528451/213845328-c939b7d6-361e-4158-aca9-1ab9a3f379ef.png)

**Comment by j1g5awi** [comment]
@HibiKier russian 是使用了过时的 State 注入参数，可能与其他插件弄混了

**Comment by HibiKier** [comment]
> @HibiKier russian 是使用了过时的 State 注入参数，可能与其他插件弄混了

已更新

**Comment by zheuziihau** [comment]
nonebot_plugin_arkrecord已更新，

**Comment by zheuziihau** [comment]
nonebot_plugin_arkrecord 已经修复问题，是在这里申请重新上架吗？

**Comment by PadorFelice** [comment]
我收到了呦~晚点会看的，秋咪。

**Comment by yanyongyu** [comment]
> nonebot_plugin_arkrecord 已经修复问题，是在这里申请重新上架吗？

直接重新发布
