### ISSUE TITLE
Plugin: 不要复读

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1499]
**插件名称：**

不要复读

**插件功能：**

防止代码炸了在群里复读刷屏，让你写插件的时候更安全

**PyPI 项目名：**

nonebot-plugin-no-repeat

**插件 import 包名：**

nonebot_plugin_no_repeat

**插件项目仓库/主页链接：**

https://github.com/bridgeL/nonebot-plugin-no-repeat

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 不要复读

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/bridgeL/nonebot-plugin-no-repeat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_no_repeat/">nonebot_plugin_no_repeat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
