### ISSUE TITLE
Plugin: 群友召唤术

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#1502]
**插件名称：**

群友召唤术

**插件功能：**

群友召唤术

**PyPI 项目名：**

nonebot-plugin-summon

**插件 import 包名：**

nonebot_plugin_summon

**插件项目仓库/主页链接：**

https://github.com/zhulinyv/nonebot_plugin_summon

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_summo

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/zhulinyv/nonebot_plugin_summon">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-summon/">nonebot-plugin-summon</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
未依赖 nonebot2、 nonebot-adapter-onebot

**Comment by zhulinyv** [comment]
> 未依赖 nonebot2、nonebot-adapter-onebot

已更新

**Comment by j1g5awi** [comment]
插件 import 包名填写与实际不符，#1507 同。

**Comment by zhulinyv** [comment]
> 插件 import 包名填写与实际不符，#1507 同。

已修改
