### ISSUE TITLE
Plugin: 战地群聊天插件

### ISSUE THREAD

**Issue by 050644zf** [nonebot/nonebot2#1505]
**插件名称：**

战地群聊天插件

**插件功能：**

群内绑定战地一/五账号，快速查询战地战绩，查看服务器信息

**PyPI 项目名：**

nonebot-plugin-bfchat

**插件 import 包名：**

nonebot_plugin_bfchat

**插件项目仓库/主页链接：**

https://github.com/050644zf/nonebot-plugin-bfchat

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 战地群聊天插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/050644zf/nonebot-plugin-bfchat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bfchat/">nonebot-plugin-bfchat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
未依赖 requests

**Comment by 050644zf** [comment]
> 未依赖 requests

已更新依赖
