### ISSUE TITLE
Plugin: Ping

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#1507]
**插件名称：**

Ping

**插件功能：**

调用api，获取网站信息

**PyPI 项目名：**

nonebot-plugin-ping

**插件 import 包名：**

nonebot_plugin_ping

**插件项目仓库/主页链接：**

https://github.com/zhulinyv/nonebot_plugin_ping

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Ping

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/zhulinyv/nonebot_plugin_ping">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ping/">nonebot-plugin-ping</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
未依赖 nonebot2, nonebot-adapter-onebot, httpx

**Comment by zhulinyv** [comment]
> 未依赖 nonebot2, nonebot-adapter-onebot, httpx

已更新
