### ISSUE TITLE
Bot: RanBot

### ISSUE THREAD

**Issue by IAXRetailer** [nonebot/nonebot2#1510]
**机器人名称：**

RanBot

**机器人功能：**

不@会很安静的Bot

**机器人项目仓库/主页链接：**

https://github.com/Hecatia-Hell-Workshop/RanBot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: RanBot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Hecatia-Hell-Workshop/RanBot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
