### ISSUE TITLE
Plugin: 服务状态查询

### ISSUE THREAD

**Issue by OREOCODEDEV** [nonebot/nonebot2#1512]
**插件名称：**

服务状态查询

**插件功能：**

查询服务可用状态

**PyPI 项目名：**

nonebot-plugin-servicestate

**插件 import 包名：**

nonebot_plugin_servicestate

**插件项目仓库/主页链接：**

https://github.com/OREOCODEDEV/nonebot-plugin-servicestate

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:api","color":"#52ea7f"},{"label":"t:state","color":"#52cfea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 服务状态查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:api-#52ea7f, t:state-#52cfea</li><li>✅ 项目 <a href="https://github.com/OREOCODEDEV/nonebot-plugin-servicestate">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-servicestate/">nonebot-plugin-servicestate</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
https://github.com/OREOCODEDEV/nonebot-plugin-servicestate/blob/e6803b627f5385ce5d70b30382a355f95190a46c/nonebot_plugin_servicestate/manager.py#L17
你想让 `pip install` 的用户上哪填 config.txt 去

**Comment by OREOCODEDEV** [comment]
> https://github.com/OREOCODEDEV/nonebot-plugin-servicestate/blob/e6803b627f5385ce5d70b30382a355f95190a46c/nonebot_plugin_servicestate/manager.py#L17 你想让 `pip install` 的用户上哪填 config.txt 去

项目自己带了个空的config.txt的https://github.com/OREOCODEDEV/nonebot-plugin-servicestate/blob/main/nonebot_plugin_servicestate/config.txt
