### ISSUE TITLE
Plugin: 腾讯云图像变换

### ISSUE THREAD

**Issue by ANGJustinl** [nonebot/nonebot2#1514]
**插件名称：**

腾讯云图像变换

**插件功能：**

✨基于腾讯云合成图的以图绘图的Nonebot插件✨

**PyPI 项目名：**

nonebot_plugin_face2cartoonpic

**插件 import 包名：**

nonebot_plugin_face2cartoonpic

**插件项目仓库/主页链接：**

https://github.com/ANGJustinl/nonebot_plugin_face2cartoonpic_main

**标签：**

[{"label":"以图绘图","color":"#72f15e"},{"label":"腾讯云","color":"#3785f1"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 腾讯云图像变换

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 以图绘图-#72f15e, 腾讯云-#3785f1</li><li>✅ 项目 <a href="https://github.com/ANGJustinl/nonebot_plugin_face2cartoonpic_main">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_face2cartoonpic/">nonebot_plugin_face2cartoonpic</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
缺少 nonebot2、nonebot-adapter-onebot 依赖，需移除 nb-cli 依赖

**Comment by ANGJustinl** [comment]
pip v0.2.8已修改为
install_requires=[
        'nonebot2>=2.0.0rc2'
        'nonebot-adapter-onebot>=2.1.5'
        'pydantic>=1.9.2'        
    ],

**Comment by j1g5awi** [comment]
逗号。

**Comment by ANGJustinl** [comment]
已订正

**Comment by j1g5awi** [comment]
缺 requests 依赖

**Comment by ANGJustinl** [comment]
已经添加
