### ISSUE TITLE
Plugin: AnimalVoice_Convert

### ISSUE THREAD

**Issue by ANGJustinl** [nonebot/nonebot2#1517]
**插件名称：**

AnimalVoice_Convert

**插件功能：**

✨支持切噜语和兽语的Nonebot译者插件✨

**PyPI 项目名：**

nonebot-plugin-animalVoice

**插件 import 包名：**

nonebot_plugin_animalVoice

**插件项目仓库/主页链接：**

https://github.com/ANGJustinl/nonebot_plugin_animalVoice/

**标签：**

[{"label":"切噜语~","color":"#e75f9d"},{"label":"兽语","color":"#5fe5e7"},{"label":"加密语言","color":"#79e556"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: AnimalVoice_Convert

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 切噜语~-#e75f9d, 兽语-#5fe5e7, 加密语言-#79e556</li><li>✅ 项目 <a href="https://github.com/ANGJustinl/nonebot_plugin_animalVoice/">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_animalVoice/">nonebot_plugin_animalVoice</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by he0119** [comment]
试试能不能触发插件测试。

**Comment by ANGJustinl** [comment]
![image](https://user-images.githubusercontent.com/96008766/210032187-805f7f89-71c3-4517-a73a-2addbf1490ef.png)

**Comment by ANGJustinl** [comment]
???为什么不断报错然后重来

**Comment by yanyongyu** [comment]
你写了markdown语法，我重新提交了
