### ISSUE TITLE
Plain typing.NoReturn is not valid as type argument

### ISSUE THREAD

**Issue by wandefou** [nonebot/nonebot2#152]
用脚手架安装后 nb create 提示 :  Plain typing.NoReturn is not valid as type argument

**Comment by lengthmin** [comment]
请检查一下自己的 python 版本，建议更新到 3.7 以上

**Comment by wandefou** [comment]
Python 3.7.1 这个版本可以吗?

**Comment by lengthmin** [comment]
应该是可以的，更新到 3.7.1 后如果还有问题我们继续探讨

**Comment by wandefou** [comment]
python 3.7.1  不能行
python 3.9.1  可以的

**Comment by lengthmin** [comment]
升级到 3.7.3+ 即可
