### ISSUE TITLE
Plugin: 命令探查

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1523]
**插件名称：**

命令探查

**插件功能：**

命令探查，缓解下载了新插件却不会使用的焦虑

**PyPI 项目名：**

nonebot-plugin-ayaka-scan-cmd

**插件 import 包名：**

nonebot_plugin_ayaka_scan_cmd

**插件项目仓库/主页链接：**

https://github.com/bridgeL/nonebot-plugin-ayaka-scan-cmd

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:命令探查","color":"#e36306"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 命令探查

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#000000, a:onebot-#000000, t:命令探查-#e36306。</li><li>✅ 项目 <a href="https://github.com/bridgeL/nonebot-plugin-ayaka-scan-cmd">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_ayaka_scan_cmd/">nonebot_plugin_ayaka_scan_cmd</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
