### ISSUE TITLE
Docs: 主页的商店页面搜索功能希望排除大小写限制

### ISSUE THREAD

**Issue by ericzhang-debug** [nonebot/nonebot2#1527]
**描述问题或主题：**

主页的商店页面搜索功能希望排除大小写限制

**需做出的修改：**

* [ ]  一些修改
主页的商店页面搜索功能希望排除大小写限制

**Comment by yanyongyu** [comment]
可以考虑采用模糊搜索

**Comment by yanyongyu** [comment]
fixed in #1609
