### ISSUE TITLE
Plugin: HttpCat🐱猫猫http状态码

### ISSUE THREAD

**Issue by ANGJustinl** [nonebot/nonebot2#1528]
**插件名称：**

HttpCat🐱猫猫http状态码

**插件功能：**

✨Nonebot猫猫http状态码插件✨

**PyPI 项目名：**

nonebot-plugin-HttpCat

**插件 import 包名：**

nonebot_plugin_HttpCat

**插件项目仓库/主页链接：**

https://github.com/ANGJustinl/nonebot_plugin_HttpCat

**标签：**

[{"label":"HttpCat","color":"#1f4ddc"},{"label":"http状态码","color":"#dc1f1f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: HttpCat🐱猫猫http状态码

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>Error while running project nonebot_plugin_HttpCat from PyPI:
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: HttpCat-#1f4ddc, 猫猫http状态码-#dc1f1f, 前置插件-#d91fdc。</li><li>✅ 项目 <a href="https://github.com/ANGJustinl/nonebot_plugin_HttpCat">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_HttpCat/">nonebot_plugin_HttpCat</a> 已发布至 PyPI。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by ANGJustinl** [comment]
reupload

**Comment by he0119** [comment]
似乎 PyPI 的缓存还没有更新，也许我还需要把插件加载测试的插件哪个版本也显示出来。

**Comment by ANGJustinl** [comment]
好像是
我太急了:(
