### ISSUE TITLE
[question]: If I import the file from the plug-in's directory, it will get two runs of the program

### ISSUE THREAD

**Issue by huang12zheng** [nonebot/nonebot2#153]
**描述问题：**

If I import the file from the plug-in's directory, it will get two runs of the program
It show " Duplicated prefix rule "

**如何复现？**
```py
from src.plugins.arena_sub.queryapi import getprofile
```
![截屏2021-01-15 上午2 57 51 (2)](https://user-images.githubusercontent.com/28038074/104636127-d7032200-56dd-11eb-8cce-5e57c5e60bb5.png)

**我期望的**
我需要注意什么? 是应该将共有的内容移出 插件目录外吗?

**Comment by mnixry** [comment]
由于NoneBot的插件加载机制,我们并不推荐通过Python原有的import机制来进行插件中的互相调用

你可以有以下两种选择

1. 抽离所有代码的公共部分, 然后放置在另一文件夹下调用
2. 使用NoneBot2提供的`export`/`require`机制来进行插件间互相调用

**Comment by huang12zheng** [comment]
我选择了1,抽离所有代码的公共部分, 然后放置在另一文件夹下调用
谢谢解答
