### ISSUE TITLE
Plugin: 求生之路2——服务器操作

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [nonebot/nonebot2#1531]
**插件名称：**

求生之路2——服务器操作

**插件功能：**

在Q群里做求生之路服务器相关操作，方便操作

**PyPI 项目名：**

nonebot-plugin-l4d2-server

**插件 import 包名：**

nonebot_plugin_l4d2_server

**插件项目仓库/主页链接：**

https://github.com/Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server

**标签：**

[{"label":"l4d2","color":"#05ff00"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 求生之路2服务器操作

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>Error while running project nonebot_plugin_l4d2_server from PyPI:
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: l4d2-#05ff00。</li><li>✅ 项目 <a href="https://github.com/Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_l4d2_server/">nonebot_plugin_l4d2_server</a> 已发布至 PyPI。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by Umamusume-Agnes-Digital** [comment]
**插件名称：**

求生之路2服务器操作

**插件功能：**

在Q群里做求生之路2服务器相关的操作

**PyPI 项目名：**

nonebot-plugin-l4d2-server

**插件 import 包名：**

nonebot_plugin_l4d2_server

**插件项目仓库/主页链接：**

https://github.com/Umamusume-Agnes-Digital/nonebot_plugin_l4d2_server

**标签：**

[{"label":"l4d2","color":"#05ff00"}]

**Comment by he0119** [comment]
你并没有加上依赖…

**Comment by Umamusume-Agnes-Digital** [comment]
> 你并没有加上依赖…

是在setup.py里面加吗，这次我加了惹

**Comment by he0119** [comment]
zipfile 和 pathlib 都是 Python 标准库啊，你为什么要加进依赖🤣

**Comment by Umamusume-Agnes-Digital** [comment]
原来是这样，已经改了

**Comment by he0119** [comment]
奇怪，为什么还是依赖有问题。不懂了。

**Comment by j1g5awi** [comment]
```py
    install_requires=[
        "nonebot2>=2.0.0b1,<3.0.0"
        "nonebot-adapter-onebot>=2.1.0",
        ],
```
少了个逗号

**Comment by Umamusume-Agnes-Digital** [comment]
> ```python
>     install_requires=[
>         "nonebot2>=2.0.0b1,<3.0.0"
>         "nonebot-adapter-onebot>=2.1.0",
>         ],
> ```
> 
> 少了个逗号

感谢大佬~
