### ISSUE TITLE
Plugin: 主动消息撤回

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#1535]
**插件名称：**

主动消息撤回

**插件功能：**

让机器人撤回自己发出的消息

**PyPI 项目名：**

nonebot-plugin-revoke

**插件 import 包名：**

nonebot_plugin_revoke

**插件项目仓库/主页链接：**

https://github.com/ssttkkl/nonebot-plugin-revoke

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 主动消息撤回

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:gocqhttp-#52ea95。</li><li>✅ 项目 <a href="https://github.com/ssttkkl/nonebot-plugin-revoke">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-revoke/">nonebot-plugin-revoke</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
