### ISSUE TITLE
Plugin: 群聊学习

### ISSUE THREAD

**Issue by CMHopeSunshine** [nonebot/nonebot2#1539]
**插件名称：**

群聊学习

**插件功能：**

让Bot学习群友说话和发表情包！

**PyPI 项目名：**

nonebot-plugin-learning-chat

**插件 import 包名：**

nonebot_plugin_learning_chat

**插件项目仓库/主页链接：**

https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat

**标签：**

[{"label":"a:onebot","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 群聊学习

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252。</li><li>✅ 项目 <a href="https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-learning-chat/">nonebot-plugin-learning-chat</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
