### ISSUE TITLE
Plugin: 对对联

### ISSUE THREAD

**Issue by CMHopeSunshine** [nonebot/nonebot2#1541]
**插件名称：**

对对联

**插件功能：**

人工智能给你对对联

**PyPI 项目名：**

nonebot-plugin-couplets

**插件 import 包名：**

nonebot_plugin_couplets

**插件项目仓库/主页链接：**

https://github.com/CMHopeSunshine/nonebot-plugin-couplets

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 对对联

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/CMHopeSunshine/nonebot-plugin-couplets">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-couplets/">nonebot-plugin-couplets</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
