### ISSUE TITLE
Plugin: 图像标注

### ISSUE THREAD

**Issue by istrashguy** [nonebot/nonebot2#1546]
**插件名称：**

图像标注

**插件功能：**

基于yolov5的图像标注插件

**PyPI 项目名：**

nonebot-plugin-Imagelabels

**插件 import 包名：**

nonebot_plugin_Imagelabels

**插件项目仓库/主页链接：**

https://github.com/istrashguy/nonebot_plugin_Imagelabels

**标签：**

[{"label":"Yolov5","color":"#9a2828"},{"label":"图像标注","color":"#e981dc"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 图像标注

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-Imagelabels 的信息如下：
    name         : nonebot-plugin-imagelabels 
     version      : 0.1.2                      
     description  : 基于yolov5实现的图像标注
插件 nonebot_plugin_Imagelabels 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: Yolov5-#9a2828, 图像标注-#e981dc。</li><li>✅ 项目 <a href="https://github.com/istrashguy/nonebot_plugin_Imagelabels">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-Imagelabels/">nonebot-plugin-Imagelabels</a> 已发布至 PyPI。</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by he0119** [comment]
你还需要在 `setup.py` 的 `install_requires` 中添加你需要的依赖，例如：
```python
install_requires=[
    "nonebot2>=2.0.0rc1,<3.0.0",
    "nonebot-adapter-onebot",
    "httpx",
]
```

**Comment by istrashguy** [comment]
Dependency requirements have been added to the setup.py




匿名者
***@***.***







                       
原始邮件
                       
                     

发件人："he0119"< ***@***.*** &gt;;

发件时间：2023/1/4 16:56

收件人："nonebot/nonebot2"< ***@***.*** &gt;;

抄送人："HeartBeat"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [nonebot/nonebot2] Plugin: 图像标注 (Issue #1546)




 
你还需要在 setup.py 的 install_requires 中添加你需要的依赖，例如：
 install_requires=[     "nonebot2&gt;=2.0.0rc1,<3.0.0",     "nonebot-adapter-onebot",     "httpx", ]

**Comment by istrashguy** [comment]
HTTPX has been added to the repository's setup.py dependencies




匿名者
***@***.***







                       
原始邮件
                       
                     

发件人："he0119"< ***@***.*** &gt;;

发件时间：2023/1/4 18:48

收件人："nonebot/nonebot2"< ***@***.*** &gt;;

抄送人："HeartBeat"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [nonebot/nonebot2] Plugin: 图像标注 (Issue #1546)




 
你的依赖还差 httpx

**Comment by yanyongyu** [comment]
你添加了httpx依赖后并未更新到pypi

**Comment by istrashguy** [comment]
Updated httpx dependencies to pypi




匿名者
***@***.***







                       
原始邮件
                       
                     

发件人："Ju4tCode"< ***@***.*** &gt;;

发件时间：2023/1/4 23:53

收件人："nonebot/nonebot2"< ***@***.*** &gt;;

抄送人："HeartBeat"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [nonebot/nonebot2] Plugin: 图像标注 (Issue #1546)




 
你添加了httpx依赖后并未更新到pypi
