### ISSUE TITLE
Feature: 建议使用简化的函数commandHandle来简化on_command的使用

### ISSUE THREAD

**Issue by huang12zheng** [nonebot/nonebot2#155]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

on_command 使用有点烦锁

**描述你所需要的特性：**
```py
from typing import Any, Dict, Union, TypeVar, Optional, Callable, NoReturn, Awaitable, TYPE_CHECKING
from typing import Set, List, Type, Tuple
from nonebot.typing import T_State, T_StateFactory, T_Handler, T_RuleChecker
from nonebot.rule import Rule, startswith, endswith, keyword, command, regex
if TYPE_CHECKING:
    from nonebot.adapters import Bot, Event

def commandHandle(cmd: Union[str, Tuple[str, ...]],
               rule: Optional[Union[Rule, T_RuleChecker]] = None,
               aliases: Optional[Set[Union[str, Tuple[str, ...]]]] = None):
    _ = on_command(cmd,rule=rule,aliases=aliases)
    return _.handle()
```

建一些简化函数来让on_command 简化  ( 不用记变量名,  且与V1有一定层度的一致性)

**Comment by huang12zheng** [comment]
* 调用

```py
@command('call')
async def show_issue(bot: Bot, event: Event, state: dict):
    await bot.send(event,f"欧尼酱,爱你")
```

**Comment by yanyongyu** [comment]
这样子的简化并不符合nb2目前的事件响应逻辑。nb2更推荐使用多个函数按次序响应，每个函数都有自己的作用。如果像你简化的那样功能，只是对命令进行一次简单的处理，`on_command`并`handle`也只是多了一行而已

**Comment by huang12zheng** [comment]
```py
jjchelp = on_command('jjc帮助')
arena_bind=on_command('竞技场绑定',aliases={'jjcbind','bind','b '})
query_arena=on_command('竞技场查询',aliases={'js','jjcsearch'})
disable_arena_sub=on_command('停止竞技场订阅')
disable_grand_arena_sub=on_command('停止公主竞技场订阅')
enable_arena_sub=on_command('启用竞技场订阅')
enable_grand_arena_sub=on_command('启用公主竞技场订阅')
delete_arena_sub=on_command('删除竞技场订阅',aliases={'unbind'})
send_arena_sub_status=on_command('竞技场订阅状态')
switch_bind=on_command('switch')
switch_log=on_command('sl_arena')
bind_config_reload=on_command('绑定配置重载',aliases={"bind_reload","br "})

@jjchelp.handle()
.....
```
> 你使用的时候并不需要输入所有变量名，比如rule和aliases并不需要写出，另一个是你的IDE没有提示么😂
1. 我的变量名 是指  jjchelp这些.  报歉,没有说清楚.   
    而这个jjchelp 变量,实际上好像没有什么用, 但它出现了两次 或 多次
    而这个变量占用了我的脑容量->  日常中,我只会记得“'jjc帮助”  ,  我是不知道 jjchelp的.

> 只是多了一行而已
2.  我认为是每个处理过程 都要 多一行  声明  
    ` jjchelp = on_command('jjc帮助') ` 和
     对应的若干装饰器前缀
----
我是不知道如何去更好的优化这个问题, 所以 用了 commandHandle来简来我认为多余的代码.
PS: 当然,可能我的想法不对.

**Comment by yanyongyu** [comment]
1. 如果你是指命令过多导致混乱的话，有以下解决方式:
  - 每定义一个命令即对命令的响应函数(handle)做出定义
  - 将多个命令分在不同的插件、文件中，模块分割可以更好的帮助开发
2. 对于变量名（装饰器前缀）
  - 这个变量即是你响应操作的凭据，可以进行`reject`, `pause`, `finish`等操作
  - 如果你想要省下这个变量，你可以这么做: 事先定义好一系列的handle函数并通过`on_command("xxx", handlers=[一系列的handle函数])`直接注册一个事件响应

如果你觉得依然非常的麻烦，你可以自行封装一个command，像你上面提到的那样。
