### ISSUE TITLE
Feature: 支持手动注册父子插件

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#1558]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

某些情况下需要手动加载某个插件的子插件，而不是在 `__init__.py` 中使用 `load_plugin` 或 `load_plugins`

但手动加载之后，这些插件不会像通过 `load_plugin` 或 `load_plugins` 一样自动成为父子插件

**描述你所需要的特性：**

希望能提供一个注册父子插件的函数

**Comment by yanyongyu** [comment]
插件需要事先加载，手动加载是什么意思

**Comment by A-kirami** [comment]
> 插件需要事先加载，手动加载是什么意思

比如，使用 `PluginMetadata` 来标明需要加载的子插件，像这样

```py
from nonebot.plugin import PluginMetadata

__plugin_meta__ = PluginMetadata(
    "插件名", "插件描述", "插件使用说明", extra={"subplugin_dirs": ["plugins"]}
)
```

然后在这个插件加载完之后，手动对它的子插件 `subplugin_dirs` 进行加载

**Comment by yanyongyu** [comment]
那你直接在模块最底下`load_plugins`不是一样的吗，嵌套插件就是这么写的

**Comment by A-kirami** [comment]
> 那你直接在模块最底下`load_plugins`不是一样的吗，嵌套插件就是这么写的

这部分是由 bot 来进行加载管理的，就是不想插件开发者直接使用 `load_plugins`

**Comment by yanyongyu** [comment]
嵌套插件就是通过在插件中进行load plugin完成的，无法通过配置来完成

**Comment by A-kirami** [comment]
> 嵌套插件就是通过在插件中进行load plugin完成的，无法通过配置来完成

不是，指的是基于 nb2 开发的 bot 来加载子插件，就像 nb2 不推荐在 `bot.py` 中手动加载一样，我觉得子插件也不应该让插件开发者来手动加载，于是在我的 bot 设计中，我采用了这种方法来加载子插件

因此希望 nb2 能提供一个供 bot 开发者使用的子插件注册函数
