### ISSUE TITLE
question:  AttributeError: 'NoneType' object has no attribute 'scheduler'

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#156]
nonebot 版本 2.0.0a7
python版本 3.8.0

参考 [文档](https://github.com/nonebot/nonebot2/blob/dev/archive/2.0.0a8.post2/advanced/scheduler.md)

看起来未能成功创建对象，问：
1.安装  `nonebot_plugin_apscheduler` 时， "通过 nb-cli" 和 "通过 poetry" 是二选一即可还是两个命令都要执行？
2. [配置插件选项](https://github.com/nonebot/nonebot2/blob/dev/archive/2.0.0a8.post2/advanced/scheduler.md#%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6%E9%80%89%E9%A1%B9)是必须的吗？

(代码用的是文档里的，虽然有红线，但是报错的地方是第3行所以大概是没问题的吧)

![image](https://user-images.githubusercontent.com/36919867/105046326-edc1c400-5aa3-11eb-9407-a4cc836426dc.png)

![image](https://user-images.githubusercontent.com/36919867/105045606-109fa880-5aa3-11eb-8b4c-71c3b50237f2.png)

**Comment by abrahum** [comment]
看log你的test插件在nonebot_plugin_apscheduler加载前加载了，test当然会报错了，可以尝试在bot.py里调换一下插件加载顺序
``` python
nonebot.load_plugin("nonebot_plugin_apscheduler")
nonebot.load_plugins("QQbot/plugins")
```

**Comment by railannad** [comment]
> 看log你的test插件在nonebot_plugin_apscheduler加载前加载了，test当然会报错了，可以尝试在bot.py里调换一下插件加载顺序
> 
> ```python
> nonebot.load_plugin("nonebot_plugin_apscheduler")
> nonebot.load_plugins("QQbot/plugins")
> ```

我记得我没写过 nonebot.load_plugin("nonebot_plugin_apscheduler") 是安装插件的时候它给我写入了吗....

话说更新到2.0.0a8就莫名其妙好了(
