### ISSUE TITLE
rc2不兼容依赖项fastapi 0.89.0

### ISSUE THREAD

**Issue by jxLYH6134** [nonebot/nonebot2#1565]
**描述问题：**

matadata中的
```
Requires-Dist: fastapi (>=0.87.0,<1.0.0)
```
会下载fastapi依赖的最新版本0.89.0，而rc2无法调用它

**如何复现？**

1. 使用 pip install nb-cli 命令安装rc2
2. pip list 中可见fastapi版本号为0.89.0
3. 使用 nb run ，fastapi抛出错误
4. 使用 pip install fastapi==0.88.0 命令安装上一个版本
5. 再次运行，错误消失

**期望的结果**

fastapi将会抛出
```
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'starlette.responses.Response'> is a valid pydantic field type
```

**环境信息：**

 - OS: Windows 19044.2364
 - Python Version: 3.9.13
 - Nonebot Version: 2.0.0rc2

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: v1.0.0-rc4

**截图或日志**

![image](https://user-images.githubusercontent.com/48689047/211167422-cb692c71-e4ba-4e4c-bf8c-e49e715d53f7.png)
>运行失败

![image](https://user-images.githubusercontent.com/48689047/211167383-62f13c26-3aa2-44fd-ad6f-b2e836fcb826.png)
>降级为0.88.0后，错误消失

**Comment by yanyongyu** [comment]
`fastapi 0.89.0` 更新了return type hint的识别功能，导致routing函数报错

**Comment by yanyongyu** [comment]
will be fixed in https://github.com/tiangolo/fastapi/pull/5855

**Comment by fatinghenji** [comment]
遇到相同问题。准备先按上面的方法尝试下。

**Comment by spicyrnilk** [comment]
执行 pip install fastapi==0.88.0 降级后问题解决，感谢。

**Comment by yanyongyu** [comment]
fastapi已修复
