### ISSUE TITLE
Plugin: 回声洞

### ISSUE THREAD

**Issue by hmzz804** [nonebot/nonebot2#1570]
**插件名称：**

回声洞

**插件功能：**

PCL2内群的回声洞，添加了审核功能。

**PyPI 项目名：**

nonebot-plugin-cave

**插件 import 包名：**
nonebot_plugin_cave

**插件项目仓库/主页链接：**

https://github.com/hmzz804/nonebot_plugin_cave

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 回声洞

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary></details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/hmzz804/nonebot_plugin_cave">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-cave/">nonebot-plugin-cave</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
