### ISSUE TITLE
Plugin: 星座运势

### ISSUE THREAD

**Issue by mengxinyuan638** [nonebot/nonebot2#1571]
**插件名称：**

星座运势

**插件功能：**

返回星座的运势

**PyPI 项目名：**

nonebot-plugin-xingzuo

**插件 import 包名：**

nonebot_plugin_xingzuo

**插件项目仓库/主页链接：**

https://github.com/mengxinyuan638/xingzuo_luck

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 星座运势

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-xingzuo 的信息如下：
    name         : nonebot-plugin-xingzuo 
     version      : 1.0.0                  
     description  :
插件 nonebot_plugin_xingzuo 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/mengxinyuan638/xingzuo_luck">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-xingzuo/">nonebot-plugin-xingzuo</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by mengxinyuan638** [comment]
已修改

**Comment by mengxinyuan638** [comment]
可以了吗

**Comment by mengxinyuan638** [comment]
好了
