### ISSUE TITLE
Bug: 无法从环境变量中读取列表型变量

### ISSUE THREAD

**Issue by zeithrold** [nonebot/nonebot2#1575]
**描述问题：**

nonebot2的变量类型读取能力表格如下：
|类型|dotenv|环境变量|
|---|---|---|
|其他简单类型变量|✅|✅|
|dict|✅|✅|
|list|✅|❌|

**如何复现？**

在`tests/test_init.py`作如下修改，运行测试出现错误：
```diff
diff --git a/tests/test_init.py b/tests/test_init.py
index 3d49d5ce..3fbb4965 100644
--- a/tests/test_init.py
+++ b/tests/test_init.py
@@ -3,6 +3,7 @@ import os
 import pytest
 
 os.environ["CONFIG_FROM_ENV"] = '{"test": "test"}'
+os.environ["CONFIG_FROM_ENV_LIST"] = '["test1", "test2"]'
 os.environ["CONFIG_OVERRIDE"] = "new"
 
 
@@ -26,6 +27,7 @@ async def test_init(nonebug_init):
 
     config = get_driver().config
     assert config.config_from_env == {"test": "test"}
+    assert config.config_from_env_list == ["test1", "test2"]
     assert config.config_override == "new"
     assert config.config_from_init == "init"
     assert config.common_config == "common"
```

```bash
# 测试命令参照.github/workflows/codecov.yml
$ poetry run pytest -n auto --cov-report xml
```
**期望的结果**

```
=============================================== short test summary info ================================================
FAILED test_init.py::test_init[nonebug_init0] - AttributeError: 'Config' object has no attribute 'config_from_env_list'
FAILED test_init.py::test_init[nonebug_init1] - AttributeError: 'Config' object has no attribute 'config_from_env_list'
============================================ 2 failed, 109 passed in 14.06s ============================================
```

**环境信息：**

该问题在以下环境中可以复现。

|OS|Python|Nonebot|
|---|---|---|
|`Darwin notebook.zeithrold.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64`|3.9.12|git`master`分支HEAD, `afd13ed65d6b925bf4f1587a8dfd7fa3c09da152`|
|`Linux codespaces-d7be66 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`|3.10.4|git`master`分支HEAD, `afd13ed65d6b925bf4f1587a8dfd7fa3c09da152`|

**协议端信息：**

*无*

**截图或日志**

*无*

**备注**

这似乎是`Pydantic`的问题，该库[文档](https://docs.pydantic.dev/usage/settings/#parsing-environment-variable-values)提供了一种通过自定义解析的方式获取列表型环境变量：

```python
import os
from typing import Any, List

from pydantic import BaseSettings


class Settings(BaseSettings):
    numbers: List[int]

    class Config:
        @classmethod
        def parse_env_var(cls, field_name: str, raw_val: str) -> Any:
            if field_name == 'numbers':
                return [int(x) for x in raw_val.split(',')]
            return cls.json_loads(raw_val)


os.environ['numbers'] = '1,2,3'
print(Settings().dict())
#> {'numbers': [1, 2, 3]}
```

从环境变量读取配置的原因在于，使用nonebot必然导致输入**机密数据**，这些数据**不适宜存储在文件当中**。部分Adapter要求使用列表型配置，但并不支持通过环境变量读取。

如果只能通过Pydantic读取变量，那么至少要在官方文档中醒目标注：**目前无法支持通过环境变量传入列表型变量*。*

**Comment by yanyongyu** [comment]
你需要在.env文件里添加这个参数值，否则nb会认为这是无关环境变量

**Comment by zeithrold** [comment]
部分环境变量不适宜通过.env传递数据，例如[onebot适配器的正向WS链接](https://onebot.adapters.nonebot.dev/docs/guide/setup#%E6%AD%A3%E5%90%91-websocket-%E8%BF%9E%E6%8E%A5)、[Nonebot2的SUPERUSERS](https://v2.nonebot.dev/docs/tutorial/configuration#superusers)。
这些配置均定义为列表类型。

**Comment by yanyongyu** [comment]
.env里留空就行了，让nb知道这个环境变量是要读取的，这样才会去环境变量里获取

**Comment by he0119** [comment]
https://github.com/he0119/CoolQBot/blob/840eee9239428bc54ee47928974da08332ba97a0/.env#L18

比如这样。

**Comment by yanyongyu** [comment]
目前dotenv没有合适的list配置项解决方案，目前只有dict可以使用delimiter来进行配置，参考[pydantic文档](https://docs.pydantic.dev/usage/settings/#parsing-environment-variable-values)

**Comment by zeithrold** [comment]
> .env里留空就行了，让nb知道这个环境变量是要读取的，这样才会去环境变量里获取

明白了，目前官方文档有类似表述吗？

**Comment by he0119** [comment]
确实该在 [环境变量](https://v2.nonebot.dev/docs/tutorial/configuration#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F) 那个地方加个提示。

**Comment by yanyongyu** [comment]
![image](https://user-images.githubusercontent.com/42488585/211253582-52b372aa-af56-4abf-80fa-dd471acbdd84.png)

**Comment by yanyongyu** [comment]
虽然实际上任何存在的配置项都会优先从环境变量中获取

**Comment by zeithrold** [comment]
> ![image](https://user-images.githubusercontent.com/42488585/211253582-52b372aa-af56-4abf-80fa-dd471acbdd84.png)

至少对我来讲似乎存在一些歧义，不知道添加一行

> https://github.com/he0119/CoolQBot/blob/840eee9239428bc54ee47928974da08332ba97a0/.env#L18
> 
> 比如这样。

类似于这种的代码示例会不会好一些？

**Comment by yanyongyu** [comment]
可以考虑在文档中明确一下

**Comment by zeithrold** [comment]
好的，明白，谢谢了，那就关闭issue了。
