### ISSUE TITLE
Plugin: Bing每日图片获取

### ISSUE THREAD

**Issue by ericzhang-debug** [nonebot/nonebot2#1576]
**插件名称：**

Bing每日图片获取

**插件功能：**

获取Bing每日一图

**PyPI 项目名：**

nonebot-plugin-BingImage

**插件 import 包名：**

nonebot_plugin_BingImage

**插件项目仓库/主页链接：**

https://github.com/ericzhang-debug/nonebot_plugin_BingImage

**标签：**

[{"label":"风景图","color":"#0ce354"},{"label":"Bing","color":"#0c43e3"},{"label":"必应","color":"#eddf13"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Bing每日图片获取

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 风景图-#0ce354, Bing-#0c43e3, 必应-#eddf13。</li><li>✅ 项目 <a href="https://github.com/ericzhang-debug/nonebot_plugin_BingImage">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-BingImage/">nonebot-plugin-BingImage</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
