### ISSUE TITLE
Plugin: 原神实时公告

### ISSUE THREAD

**Issue by mengxinyuan638** [nonebot/nonebot2#1584]
**插件名称：**

原神实时公告

**插件功能：**

实时展示官网最新前20条公告

**PyPI 项目名：**

nonebot-plugin-yuanshen-notice

**插件 import 包名：**

nonebot_plugin_yuanshen_notice

**插件项目仓库/主页链接：**

https://github.com/mengxinyuan638/nonebot_plugin_yuanshen_notice

**标签：**

[{"label":"原神","color":"#ef3700"},{"label":"公告","color":"#00ef04"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 原神实时公告

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 原神-#ef3700, 萌新源-#ef3700, 公告-#00ef04。</li><li>✅ 项目 <a href="https://github.com/mengxinyuan638/nonebot_plugin_yuanshen_notice">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-yuanshen-notice/">nonebot-plugin-yuanshen-notice</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by yanyongyu** [comment]
请注意更新插件依赖

**Comment by mengxinyuan638** [comment]
把request依赖删除么换httpx是吧

**Comment by yanyongyu** [comment]
看上面插件测试输出

**Comment by mengxinyuan638** [comment]
可以了
