### ISSUE TITLE
Docs: "目录结构"中"bot.py"在新版nb_cli中是可选的，但是没有打上#可选

### ISSUE THREAD

**Issue by shikukuya** [nonebot/nonebot2#1587]
**描述问题或主题：**

文档需更新

**需做出的修改：**

https://v2.nonebot.dev/docs/tutorial/create-project#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84

"目录结构"中"bot.py"在新版nb_cli中是可选的，但是没有打上`#可选`

**Comment by MingxuanGame** [comment]
文档在改，稍安勿躁

**Comment by yanyongyu** [comment]
文档更新全部集中到 #793
