### ISSUE TITLE
Plugin: 哔哩哔哩q群登录

### ISSUE THREAD

**Issue by mengxinyuan638** [nonebot/nonebot2#1590]
**插件名称：**

哔哩哔哩q群登录

**插件功能：**

实现哔哩哔哩q群登录的插件

**PyPI 项目名：**

nonebot-plugin-bilibili-yuan 

**插件 import 包名：**

nonebot_plugin_bilibili_yuan

**插件项目仓库/主页链接：**

https://github.com/mengxinyuan638/nonebot-plugin-bilibili-yuan

**标签：**

[{"label":"bilibili","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 哔哩哔哩q群登录

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: bilibili-#ea5252, 萌新源-#ea5252。</li><li>✅ 项目 <a href="https://github.com/mengxinyuan638/nonebot-plugin-bilibili-yuan">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bilibili-yuan/">nonebot-plugin-bilibili-yuan</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
