### ISSUE TITLE
Plugin: 简易谷歌翻译插件

### ISSUE THREAD

**Issue by nikissXI** [nonebot/nonebot2#1592]
**插件名称：**

简易谷歌翻译插件

**插件功能：**

免api key简单谷歌翻译插件

**PyPI 项目名：**

nonebot-plugin-easy-translate

**插件 import 包名：**

nonebot_plugin_easy_translate

**插件项目仓库/主页链接：**

https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_easy_translate

**标签：**

[{"label":"翻译","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 免key，简易谷歌翻译插件

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 翻译-#ea5252。</li><li>✅ 项目 <a href="https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_easy_translate">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_easy_translate/">nonebot_plugin_easy_translate</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
