### ISSUE TITLE
Plugin: OrangeDice!

### ISSUE THREAD

**Issue by BigOrangeQWQ** [nonebot/nonebot2#1594]
**插件名称：**

OrangeDice!

**插件功能：**

一个COC跑团用插件

**PyPI 项目名：**

nonebot-plugin-orangedice

**插件 import 包名：**

nonebot_plugin_orangedice

**插件项目仓库/主页链接：**

https://github.com/BigOrangeQWQ/nonebot_plugin_orangedice

**标签：**

[{"label":"dice","color":"#08c0bb"},{"label":"COC","color":"#a2bc0c"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: OrangeDice!

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 项目 <a href="https://github.com/BigOrangeQWQ/nonebot_plugin_orangedice">主页</a> 返回状态码 404。<dt>请确保您的项目主页可访问。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: dice-#08c0bb, COC-#a2bc0c。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-orangedice/">nonebot-plugin-orangedice</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by BigOrangeQWQ** [comment]
已修复:p
