### ISSUE TITLE
Plugin: 成语接龙

### ISSUE THREAD

**Issue by Jerry080801** [nonebot/nonebot2#1602]
**插件名称：**

成语接龙

**插件功能：**

成语接龙

**PyPI 项目名：**

nonebot-plugin-idiom-sequence

**插件 import 包名：**

nonebot_plugin_idiom_sequence

**插件项目仓库/主页链接：**

https://github.com/Jerry080801/nonebot_plugin_idiom_sequence

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 成语接龙

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ desc: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot_plugin_idiom_sequence 的信息如下：
    name         : nonebot-plugin-idiom-sequence 
     version      : 0.1.0                         
     description  :
插件 nonebot_plugin_idiom_sequence 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Jerry080801/nonebot_plugin_idiom_sequence">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_idiom_sequence/">nonebot_plugin_idiom_sequence</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by yanyongyu** [comment]
依赖项缺少nonebot2

**Comment by yanyongyu** [comment]
@Jerry080801
