### ISSUE TITLE
Plugin: 犯人在跳舞

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1607]
**插件名称：**

犯人在跳舞

**插件功能：**

文字版桌游，犯人在跳舞

**PyPI 项目名：**

criminal-dance

**插件 import 包名：**

criminal_dance

**插件项目仓库/主页链接：**

https://github.com/bridgeL/criminal_dance

**标签：**

[{"label":"t:文字版桌游","color":"#e36306"},{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 犯人在跳舞

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 criminal_dance 的信息如下：
    name         : criminal-dance 
     version      : 0.0.1          
     description  : 犯人在跳舞          
    
    dependencies
     - ayaka &gt;=0.0.1.3,&lt;0.0.2.0
插件 criminal_dance 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: t:文字版桌游-#e36306, a:onebot-#000000。</li><li>✅ 项目 <a href="https://github.com/bridgeL/criminal_dance">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/criminal_dance/">criminal_dance</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by bridgeL** [comment]
我这个插件是做的跨机器人适配的（支持nonebot1和nonebot2），没法写依赖，咋办

**Comment by yanyongyu** [comment]
你确定加载没有问题是吧

**Comment by bridgeL** [comment]
没问题，已经在自己bot上玩了半天了
