### ISSUE TITLE
Adapter: Spigot

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1611]
**协议名称：**

Spigot

**协议功能：**

MineCraft通信适配

**PyPI 项目名：**

nonebot-adapter-spigot

**协议 import 包名：**

nonebot.adapters.spigot

**协议项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-adapter-spigot

**标签：**

[{"label":"Minecraft","color":"#4ef0ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: Spigot

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#4ef0ea。</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-adapter-spigot">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-adapter-spigot/">nonebot-adapter-spigot</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
