### ISSUE TITLE
Plugin: PicMCStat

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1613]
**插件名称：**

PicMCStat

**插件功能：**

将 Minecraft 服务器的 MOTD 信息绘制为一张图片

**PyPI 项目名：**

nonebot-plugin-picmcstat

**插件 import 包名：**

nonebot_plugin_picmcstat

**插件项目仓库/主页链接：**

https://github.com/lgc2333/nonebot-plugin-picmcstat

**标签：**

[{"label":"Minecraft","color":"#7fbf55"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: PicMCStat

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#7fbf55。</li><li>✅ 项目 <a href="https://github.com/lgc2333/nonebot-plugin-picmcstat">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-picmcstat/">nonebot-plugin-picmcstat</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by lgc2333** [comment]
bump ver
