### ISSUE TITLE
Adapter: BilibiliLive

### ISSUE THREAD

**Issue by wwweww** [nonebot/nonebot2#1616]
**协议名称：**

BilibiliLive

**协议功能：**

b站直播间ws协议

**PyPI 项目名：**

nonebot-adapter-bilibili

**协议 import 包名：**

nonebot.adapter.bilibili

**协议项目仓库/主页链接：**

https://github.com/wwweww/adapter-bilibili

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: BilibiliLive

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/wwweww/adapter-bilibili">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-adapter-bilibili/">nonebot-adapter-bilibili</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
