### ISSUE TITLE
Plugin: 植物大战僵尸小游戏

### ISSUE THREAD

**Issue by longchengguxiao** [nonebot/nonebot2#1621]
**插件名称：**

植物大战僵尸小游戏

**插件功能：**

通过签到获取金币购买植物或者僵尸，放置植物在草坪上抵御入侵，或者进行僵尸入侵来吃掉别人的脑子

**PyPI 项目名：**

nonebot-plugin-pvz

**插件 import 包名：**

nonebot_plugin_pvz

**插件项目仓库/主页链接：**

https://github.com/longchengguxiao/nonebot_plugin_pvz

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 植物大战僵尸小游戏

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-plugin-pvz/ 不符合规范。<dt>请确保项目名正确。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 https://pypi.org/project/nonebot-plugin-pvz/ 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    [Errno 21] Is a directory: &#x27;/tmp/tmp1d3o0b7w&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/longchengguxiao/nonebot_plugin_pvz">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by longchengguxiao** [comment]
1

**Comment by longchengguxiao** [comment]
这个错误是为什么，No module named 'nonebot.adapters.onebot'，我已经在setup.py中写了依赖nonebot2==2.0.0rc3

**Comment by yanyongyu** [comment]
缺少 nonebot-adapter-onebot

**Comment by longchengguxiao** [comment]
> 缺少 nonebot-adapter-onebot

明白了，我刚刚看别人的项目需求了，发现了这个问题，多谢，我修改一下再试一次
