### ISSUE TITLE
Bot: 青岚

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1629]
**机器人名称：**

青岚

**机器人功能：**

基于NoneBot的与Minecraft Server互通消息的机器人

**机器人项目仓库/主页链接：**

https://github.com/17TheWord/qinglan_bot

**标签：**

[{"label":"MineCraft","color":"#4ef0ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: 青岚

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: MineCraft-#4ef0ea, 消息互通-#f0b74e。</li><li>✅ 项目 <a href="https://github.com/17TheWord/qinglan_bot">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
