### ISSUE TITLE
Plugin: nonebot-plugin-mcport

### ISSUE THREAD

**Issue by Proviasw** [nonebot/nonebot2#1633]
**插件名称：**

nonebot-plugin-mcport

**插件功能：**

我的世界JAVA服务器通过RCON连接远程执行命令

**PyPI 项目名：**

nonebot-plugin-mcport

**插件 import 包名：**

nonebot-plugin-mcport

**插件项目仓库/主页链接：**

https://github.com/Proviasw/nonebot-plugin-mcport

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-mcpor

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot-plugin-mcport/">nonebot-plugin-mcport</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 nonebot-plugin-mcport 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    Could not find a matching version of package nonebot-plugin-mcport</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Proviasw/nonebot-plugin-mcport">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Proviasw** [comment]
已更新

**Comment by Proviasw** [comment]
已更新

**Comment by Proviasw** [comment]
已更新

**Comment by Proviasw** [comment]
已更新

**Comment by he0119** [comment]
你 PyPI 上的版本并没有更新。

**Comment by Proviasw** [comment]
> 你 PyPI 上的版本并没有更新。

OK，感谢提醒

**Comment by Proviasw** [comment]
已更新

**Comment by yanyongyu** [comment]
请更新版本号并发布到pypi

**Comment by Proviasw** [comment]
已更新

**Comment by Proviasw** [comment]
已更新

**Comment by Proviasw** [comment]
已更新
