### ISSUE TITLE
Plugin: 简易群管女生自用99新

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#1634]
**插件名称：**

简易群管女生自用99新

**插件功能：**

简单的群管插件，BOT不是群主也可以设置管理员啦……

**PyPI 项目名：**

nonebot-plugin-easy-group-manager

**插件 import 包名：**

nonebot_plugin_easy_group_manager

**插件项目仓库/主页链接：**

https://github.com/zhulinyv/nonebot_plugin_easy_group_manager

**标签：**

[{"label":"群管","color":"#1eb262"},{"label":"女生自用","color":"#b21e82"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 简易群管女生自用99新

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot-plugin-easy-group-manager/ 不符合规范。<dt>请确保项目名正确。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 https://pypi.org/project/nonebot-plugin-easy-group-manager/ 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    [Errno 21] Is a directory: &#x27;/tmp/tmpcv1jyw4_&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 群管-#1eb262, 女生自用-#b21e82。</li><li>✅ 项目 <a href="https://github.com/zhulinyv/nonebot_plugin_easy_group_manager">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
