### ISSUE TITLE
Plugin: Group_Link_Guild

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1636]
**插件名称：**

Group_Link_Guild

**插件功能：**

互通QQ群聊与QQ频道消息的插件

**PyPI 项目名：**

nonebot-plugin-group-link-guild

**插件 import 包名：**

nonebot_plugin_group_link_guild

**插件项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-plugin-group-link-guild

**标签：**

[{"label":"QQ群","color":"#ea5252"},{"label":"QQ频道","color":"#52ead5"},{"label":"消息互通","color":"#50c545"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Group_Link_Guild

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: QQ群-#ea5252, QQ频道-#52ead5, 消息互通-#50c545。</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-plugin-group-link-guild">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-group-link-guild/">nonebot-plugin-group-link-guild</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
