### ISSUE TITLE
Plugin: 舔狗日记

### ISSUE THREAD

**Issue by Reversedeer** [nonebot/nonebot2#1645]
**插件名称：**

舔狗日记

**插件功能：**

随机发送一句舔狗日记文案

**PyPI 项目名：**

nonebot-plugin-dog

**插件 import 包名：**

nonebot_plugin_dog

**插件项目仓库/主页链接：**

https://github.com/Reversedeer/nonebot_plugin_dog

**标签：**

[{"label":"a:nonebot","color":"#c61b1b"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 舔狗日记

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:nonebot-#c61b1b。</li><li>✅ 项目 <a href="https://github.com/Reversedeer/nonebot_plugin_dog">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-dog/">nonebot-plugin-dog</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Reversedeer** [comment]
没发布？
