### ISSUE TITLE
Question: 调用httpx驱动器上传文件失败

### ISSUE THREAD

**Issue by eya46** [nonebot/nonebot2#1647]
**描述问题：**

调用~httpx驱动器上传文件有bug
nonebot.internal.driver.Request对files的处理可能有问题

**如何复现？**

[adapter-upload-test](https://github.com/eya46/adapter-upload-test)

``` python3
args = {
    "headers": {
        "Authorization": f"Bearer {token}",
        "Accept": f"application/json"
    }, "files": {"file": _get_file()}
}

req = Request(
    "POST", "https://pic.eya46.com/api/v1/upload", **args
)
logger.debug(req.files)
result = json.loads((await self.adapter.request(req)).content)
logger.debug("调用驱动器~httpx")
logger.debug(result)

result = httpx.post("https://pic.eya46.com/api/v1/upload",**args).json()
logger.debug("直接调用httpx")
logger.debug(result)
```

**期望的结果**

上传成功

**环境信息：**

 - OS: [Windows10]
 - Python Version: [3.10]
 - Nonebot Version: [2.0.0rc3~最新]

**截图或日志**

![1](https://user-images.githubusercontent.com/61458340/215310483-7eb317d1-347c-4d9a-8868-3e2e5a4b6e81.png)
![2](https://user-images.githubusercontent.com/61458340/215310486-27c14974-9152-4334-88b7-7a0d0be7f0c1.png)
[代码的位置](https://github.com/nonebot/nonebot2/blob/master/nonebot/internal/driver/model.py#L119-L129)
![3](https://user-images.githubusercontent.com/61458340/215310492-31460737-d3cd-4a97-9c24-b6400d07c671.png)

删除后

![4](https://user-images.githubusercontent.com/61458340/215310494-3702de4f-e8de-42de-9503-a681db402d3d.png)
![6](https://user-images.githubusercontent.com/61458340/215310729-13a7c79d-968f-482d-b598-32b690c4da09.png)

**Comment by yanyongyu** [comment]
上传文件需要提供文件名，否则是form

```python
files = {"field_name": (file_name, file_content)}
files = {"field_name": (file_name, file_content, content_type)}
```

**Comment by eya46** [comment]
> 上传文件需要提供文件名，否则是form，试试这样行不行
> 
> ```python
> files = {"field_name": (file_name, file_content)}
> files = {"field_name": (file_name, file_content, content_type)}
> ```

后面改成第一种就能成功上传了，(file_name, file_content)
