### ISSUE TITLE
Plugin: uuid生成器

### ISSUE THREAD

**Issue by ZombieFly** [nonebot/nonebot2#1648]
**插件名称：**

uuid生成器

**插件功能：**

通过 uuid4 与 uuid5 生成 uuid ，并且支持快速去除短横线

**PyPI 项目名：**

nonebot-plugin-uuid

**插件 import 包名：**

nonebot_plugin_uuid

**插件项目仓库/主页链接：**

https://github.com/ZombieFly/nonebot-plugin-uuid

**标签：**

[{"label":"工具","color":"#39c5bb"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: uuid生成器

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 工具-#39c5bb。</li><li>✅ 项目 <a href="https://github.com/ZombieFly/nonebot-plugin-uuid">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-uuid/">nonebot-plugin-uuid</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
