### ISSUE TITLE
Plugin: 更人性化的GPT-Ai聊天插件

### ISSUE THREAD

**Issue by KroMiose** [nonebot/nonebot2#1650]
**插件名称：**

更人性化的GPT-Ai聊天插件

**插件功能：**

一个基于NoneBot框架的Ai聊天插件，对接OpenAi文本生成接口，优化了群聊场景的上下文支持。

**PyPI 项目名：**

nonebot-plugin-naturel-gpt

**插件 import 包名：**

nonebot_plugin_naturel_gpt

**插件项目仓库/主页链接：**

https://github.com/KroMiose/nonebot_plugin_naturel_gpt

**标签：**

[{"label":"GPT3","color":"#66ccff"},{"label":"OpenAi","color":"#cc66ff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 更人性化的GPT-Ai聊天插件

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-naturel-gpt 的信息如下：
    name         : nonebot-plugin-naturel-gpt          
     version      : 1.0.0                               
     description  : 一个基于NoneBot框架的Ai聊天插件，对接OpenAi文本生成接口
插件 nonebot-plugin-naturel-gpt 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: GPT3-#66ccff, OpenAi-#c766ff。</li><li>✅ 项目 <a href="https://github.com/KroMiose/nonebot_plugin_naturel_gpt">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-naturel-gpt/">nonebot-plugin-naturel-gpt</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by KroMiose** [comment]
test

**Comment by KroMiose** [comment]
更新依赖测试

**Comment by KroMiose** [comment]
更新测试

**Comment by KroMiose** [comment]
更新测试

**Comment by KroMiose** [comment]
更新测试
