### ISSUE TITLE
Plugin: MC Ping

### ISSUE THREAD

**Issue by 17TheWord** [nonebot/nonebot2#1655]
**插件名称：**

MC Ping

**插件功能：**

查询MineCraft服务器状态并返回图片的插件，支持JE/BE服务端

**PyPI 项目名：**

nonebot-plugin-mcping

**插件 import 包名：**

nonebot_plugin_mcping

**插件项目仓库/主页链接：**

https://github.com/17TheWord/nonebot-plugin-mcping

**标签：**

[{"label":"Minecraft","color":"#47d754"},{"label":"服务器状态","color":"#d7cd47"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: MC Ping

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#47d754, 服务器状态-#d7cd47。</li><li>✅ 项目 <a href="https://github.com/17TheWord/nonebot-plugin-mcping">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-mcping/">nonebot-plugin-mcping</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by MSDNicrosoft** [comment]
插件缺少 `pyproject.toml` 或者 setup

**Comment by 17TheWord** [comment]
不好意思少上传了一个文件，已推送。

**Comment by 17TheWord** [comment]
不好意思少上传了一个文件，已推送。

**Comment by MSDNicrosoft** [comment]
> 不好意思少上传了一个文件，已推送。

PyPI记得发版

**Comment by 17TheWord** [comment]
PyPI已有[pypi](https://pypi.org/project/nonebot-plugin-mcping/)
