### ISSUE TITLE
Plugin: AutoReply

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1659]
**插件名称：**

AutoReply

**插件功能：**

一个简单的只有配置文件的无数据库自动回复插件，支持多种匹配模式

**PyPI 项目名：**

nonebot-plugin-autoreply

**插件 import 包名：**

nonebot_plugin_autoreply

**插件项目仓库/主页链接：**

https://github.com/lgc2333/nonebot-plugin-autoreply/

**标签：**

[{"label":"t:自动回复","color":"#ea881e"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: AutoReply

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/lgc2333/nonebot-plugin-autoreply/">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-autoreply/">nonebot-plugin-autoreply</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
