### ISSUE TITLE
Plugin: 每日人品2

### ISSUE THREAD

**Issue by Rene8028** [nonebot/nonebot2#1667]
**插件名称：**

每日人品2

**插件功能：**

带数据库可查询历史平均人品的jrrp插件

**PyPI 项目名：**

nonebot-plugin-jrrp2

**插件 import 包名：**

nonebot_plugin_jrrp2

**插件项目仓库/主页链接：**

https://github.com/Rene8028/nonebot_plugin_jrrp2

**标签：**

[{"label":"每日人品","color":"#ea5252"},{"label":"jrrp","color":"#5290ea"},{"label":"jrrp2","color":"#52bbea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 每日人品2

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 nonebot-plugin-jrrp2 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    Because no versions of nonebot-plugin-jrrp2 match &gt;1.1,&lt;2.0
     and nonebot-plugin-jrrp2 (1.1) depends on random (*), nonebot-plugin-jrrp2 (&gt;=1.1,&lt;2.0) requires random (*).
    So, because no versions of random match *
     and plugin-test depends on nonebot-plugin-jrrp2 (^1.1), version solving failed.</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 每日人品-#ea5252, jrrp-#5290ea, jrrp2-#52bbea。</li><li>✅ 项目 <a href="https://github.com/Rene8028/nonebot_plugin_jrrp2">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-jrrp2/">nonebot-plugin-jrrp2</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Rene8028** [comment]
no versions of random match * ？
为什么呢？是找不到random吗

**Comment by Rene8028** [comment]
更新结果

**Comment by Rene8028** [comment]
1

**Comment by Rene8028** [comment]
更新

**Comment by Rene8028** [comment]
1

**Comment by Rene8028** [comment]
1

**Comment by Rene8028** [comment]
1

**Comment by Rene8028** [comment]
1
