### ISSUE TITLE
Plugin: nonebot-plugin-stupidjdsd

### ISSUE THREAD

**Issue by liu1272** [nonebot/nonebot2#1673]
**插件名称：**

nonebot-plugin-stupidjdsd

**插件功能：**

一个笨笨的用于解决广州大学经典诵读任务的插件

**PyPI 项目名：**

nonebot-plugin-stupidjdsd

**插件 import 包名：**

nonebot-plugin-stupidjdsd

**插件项目仓库/主页链接：**

https://github.com/liu1272/nonebot-plugin-stupidjdsd

**标签：**

[{"label":"广州大学","color":"#ea5959"},{"label":"经典诵读","color":"#88ea59"},{"label":"刷分脚本","color":"#0c1c09"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-stupidjdsd

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ PyPI 项目名 广州大学经典诵读 不符合规范。<dt>请确保项目名正确。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 广州大学经典诵读 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    Could not find a matching version of package 广州大学经典诵读</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 广州大学-#ea5959, 经典诵读-#88ea59, 刷分脚本-#0c1c09。</li><li>✅ 项目 <a href="https://github.com/liu1272/nonebot-plugin-stupidjdsd">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by liu1272** [comment]
测试

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
这咋办？

**Comment by j1g5awi** [comment]
首先，建议你 setup.py，了解下现代的 python 打包方式。
其次，你应该依赖 nonebot2 而非 nonebot。

**Comment by liu1272** [comment]
> 首先，建议你 setup.py，了解下现代的 python 打包方式。 其次，你应该依赖 nonebot2 而非 nonebot。
确实是不会打包，唉这个早上起来学学
这个requests的话是因为我用了subprocess哈哈哈
nonebot2这个已经改过来啦！
非常感谢！

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by liu1272** [comment]
1

**Comment by yanyongyu** [comment]
还能用么

**Comment by liu1272** [comment]
感觉不是很行，算了吧
