### ISSUE TITLE
Plugin: 今天吃喝什么（图片版）

### ISSUE THREAD

**Issue by Cvandia** [nonebot/nonebot2#1677]
**插件名称：**

今天吃喝什么（图片版）

**插件功能：**

今天吃什么呢

**PyPI 项目名：**

nonebot-plugin-whateat-pic

**插件 import 包名：**

nonebot_plugin_whateat_pic

**插件项目仓库/主页链接：**

https://github.com/Cvandia/nonebot-plugin-whateat-pic

**标签：**

[{"label":"t:吃什么","color":"#e4ea52"},{"label":"t:喝什么","color":"#52ea8b"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 今天吃喝什么（图片版）

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:吃什么-#e4ea52, t:喝什么-#52ea8b。</li><li>✅ 项目 <a href="https://github.com/Cvandia/nonebot-plugin-whateat-pic">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-whateat-pic/">nonebot-plugin-whateat-pic</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
