### ISSUE TITLE
Bot: koishi

### ISSUE THREAD

**Issue by CupidsBow** [nonebot/nonebot2#1680]
**机器人名称：**

koishi

**机器人功能：**

支持爬取 codeforces, atcoder, 牛客上程序设计赛事的 bot。

**机器人项目仓库/主页链接：**

https://github.com/CupidsBow/koishi

**标签：**

[{"label":"acm","color":"#f71d1d"},{"label":"codeforces","color":"#1df721"},{"label":"atcoder","color":"#aa1df7"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: koishi

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: acm-#f71d1d, codeforces-#1df721, atcoder-#aa1df7。</li><li>✅ 项目 <a href="https://github.com/CupidsBow/koishi">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
