### ISSUE TITLE
Plugin: ACMReminder

### ISSUE THREAD

**Issue by BigOrangeQWQ** [nonebot/nonebot2#1685]
**插件名称：**

ACMReminder

**插件功能：**

获取CF/牛客等平台的竞赛信息的插件

**PyPI 项目名：**

nonebot-plugin-acm-reminder

**插件 import 包名：**

nonebot_plugin_acm_reminder

**插件项目仓库/主页链接：**

https://github.com/BigOrangeQWQ/nonebot_plugin_acm_reminder

**标签：**

[{"label":"ACM","color":"#3b8b74"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ACMReminder

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: ACM-#3b8b74。</li><li>✅ 项目 <a href="https://github.com/BigOrangeQWQ/nonebot_plugin_acm_reminder">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-acm-reminder/">nonebot-plugin-acm-reminder</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
