### ISSUE TITLE
Plugin: 工具拓展

### ISSUE THREAD

**Issue by NCBM** [nonebot/nonebot2#1693]
**插件名称：**

工具拓展

**插件功能：**

便于开发 nonebot2 插件的工具拓展

**PyPI 项目名：**

nonebot-plugin-extrautils

**插件 import 包名：**

nonebot_plugin_extrautils

**插件项目仓库/主页链接：**

https://github.com/NCBM/nonebot-plugin-extrautils

**标签：**

[{"label":"t:dev","color":"#c99309"},{"label":"t:utils","color":"#3a46f6"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 工具拓展

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: t: dev-#c99309, t: utils-#3a46f6。</li><li>✅ 项目 <a href="https://github.com/NCBM/nonebot-plugin-extrautils">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-extrautils/">nonebot-plugin-extrautils</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
