### ISSUE TITLE
[Bug] 为 on_command 设置 aliases 后，通过 aliases 触发的消息有关问题

### ISSUE THREAD

**Issue by Lancercmd** [nonebot/nonebot2#17]
## 当前提交 nonebot2-dev-1aac3d5

该版本可以在 on_command 设置 aliases ，如：
```
from nonebot import on_command
from nonebot.adapters.cqhttp import Bot, Event


test = on_command('test', aliases=('ts'))


@test.handle()
async def _(bot: Bot, event: Event, state: dict):
    print(f'{event.message}')


@test.got('input', prompt='xxxx')
async def _(bot: Bot, event: Event, state: dict):
    ....
```
加入以上代码，并通过 nonebot-test 向 Bot 发送：
```
test nonebot2
```
此时 nonebot2 控制台上 print() 的内容：
```
nonebot2
```
以上为符合预期的情况。
但通过 aliases 调用时，通过 nonebot-test 向 Bot 发送：
```
ts nonebot2
```
此时 nonebot2 控制台上 print() 的内容：
```
s nonebot2
```
除此以外，当发送的消息仅包含 aliases 时，通过 nonebot-test 向 Bot 发送：
```
ts
```
此时 nonebot2 控制台上 print() 的内容：
```
s
```
而上述情况的发送消息都成功被传入了 @test.got() 的函数中，即使发送的消息并不包含参数。
PS: 经测试，上述问题和首个字符是什么无关，和是否有命令分隔符无关。

**Comment by yanyongyu** [comment]
由于共享了handler出现了handler错误

**Comment by yanyongyu** [comment]
看了下你的代码，问题出在这里：

> `test = on_command('test', aliases=('ts'))`

应该是 `aliases={"ts"}`，类型应该为Set（怕不是没开类型检查XD
