### ISSUE TITLE
sorry 

### ISSUE THREAD

**Issue by rating12** [nonebot/nonebot2#1700]
抱歉不好意思，不小心点错了打扰您了

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: SSXQww

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/thereisnodice/nodice2">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_nodice/">nonebot_plugin_nodice</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
