### ISSUE TITLE
Plugin: OAchatbot

### ISSUE THREAD

**Issue by Jmy999** [nonebot/nonebot2#1703]
**插件名称：**

OAchatbot

**插件功能：**

没有上下文语境的简易chatbot，调用openai API

**PyPI 项目名：**

**插件 import 包名：**

**插件项目仓库/主页链接：**

https://github.com/Jmy999/nonebot2_wulun_oachatbot

**标签：**

[{"label":"OpenAi","color":"#ea5252"},{"label":"GPT3","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: OAchatbot

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary></details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: OpenAi-#ea5252, GPT3-#ea5252。</li><li>✅ 项目 <a href="https://github.com/Jmy999/nonebot2_wulun_oachatbot">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
