### ISSUE TITLE
Plugin: 你画我猜组队

### ISSUE THREAD

**Issue by bridgeL** [nonebot/nonebot2#1704]
**插件名称：**

你画我猜组队

**插件功能：**

自动创建gartic房间，主题为综合，将房间链接发送到群聊

**PyPI 项目名：**

nonebot-plugin-gartic-room

**插件 import 包名：**

gartic_room

**插件项目仓库/主页链接：**

https://github.com/bridgeL/gartic_room

**标签：**

[{"label":"ayaka","color":"#e36306"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 你画我猜组队

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ PyPI 项目名 gartic_room[htmlrender] 不符合规范。<dt>请确保项目名正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: ayaka-#e36306。</li><li>✅ 项目 <a href="https://github.com/bridgeL/gartic_room">主页</a> 返回状态码 200。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
