### ISSUE TITLE
Plugin: Bing Chat

### ISSUE THREAD

**Issue by Harry-Jing** [nonebot/nonebot2#1713]
**插件名称：**

Bing Chat

**插件功能：**

使用新版必应的聊天功能

**PyPI 项目名：**

nonebot-plugin-bing-chat

**插件 import 包名：**

nonebot_plugin_bing_chat

**插件项目仓库/主页链接：**

https://github.com/Harry-Jing/nonebot-plugin-bing-chat

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Bing Chat

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Harry-Jing/nonebot-plugin-bing-chat">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bing-chat/">nonebot-plugin-bing-chat</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
