### ISSUE TITLE
Plugin: 发病语录

### ISSUE THREAD

**Issue by Ikaros-521** [nonebot/nonebot2#1727]
**插件名称：**

发病语录

**插件功能：**

对输入的人，随机返回一条本地的发病语录

**PyPI 项目名：**

nonebot-plugin-random-stereotypes

**插件 import 包名：**

nonebot_plugin_random_stereotypes

**插件项目仓库/主页链接：**

https://github.com/Ikaros-521/nonebot_plugin_random_stereotypes

**标签：**

[{"label":"语录","color":"#6a6060"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 发病语录

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 发病-#ea5252, 语录-#6a6060。</li><li>✅ 项目 <a href="https://github.com/Ikaros-521/nonebot_plugin_random_stereotypes">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_random_stereotypes/">nonebot_plugin_random_stereotypes</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
