### ISSUE TITLE
Plugin: H2E（如何锻炼）

### ISSUE THREAD

**Issue by Gin2O** [nonebot/nonebot2#1734]
**插件名称：**

H2E（如何锻炼）

**插件功能：**

类似`今天吃什么`的一个插件，通过命令返回健身、游泳、瑜伽的锻炼方式啦

**PyPI 项目名：**

nonebot-plugin-h2e

**插件 import 包名：**

nonebot-plugin-h2e

**插件项目仓库/主页链接：**

https://github.com/Gin2O/nonebot_plugin_h2e

**标签：**

[{"label":"锻炼","color":"#da4a4a"},{"label":"t:what2eat","color":"#99da4a"},{"label":"t: how2exe","color":"#99da4a"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: H2E（如何锻炼）

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-h2e 的信息如下：
    name         : nonebot-plugin-h2e                            
     version      : 0.1.1                                         
     description  : A nonebot2 plugin package for how to exercise
插件 nonebot-plugin-h2e 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 锻炼-#da4a4a, t:what2eat-#99da4a, t: how2exe-#99da4a。</li><li>✅ 项目 <a href="https://github.com/Gin2O/nonebot_plugin_h2e">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-h2e/">nonebot-plugin-h2e</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
