### ISSUE TITLE
Plugin: 呆呆兽都会起来锻炼 H2E

### ISSUE THREAD

**Issue by Gin2O** [nonebot/nonebot2#1735]
**插件名称：**

呆呆兽都会起来锻炼 H2E

**插件功能：**

类似`今天吃什么`的一个插件，通过命令返回健身、游泳、瑜伽的锻炼方式啦

**PyPI 项目名：**

nonebot-plugin-h2e

**插件 import 包名：**

nonebot-plugin-h2e

**插件项目仓库/主页链接：**

https://github.com/Gin2O/nonebot_plugin_h2e

**标签：**

[{"label":"锻炼","color":"#da4a4a"},{"label":"t:what2eat","color":"#99da4a"},{"label":"t: how2exe","color":"#99da4a"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 呆呆兽都会起来锻炼 H2E

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 nonebot-plugin-h2e 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    Because no versions of nonebot-plugin-h2e match &gt;0.1.2,&lt;0.2.0
     and nonebot-plugin-h2e (0.1.2) depends on asyncio (&gt;=3.6.2,&lt;4.0.0), nonebot-plugin-h2e (&gt;=0.1.2,&lt;0.2.0) requires asyncio (&gt;=3.6.2,&lt;4.0.0).
    So, because no versions of asyncio match &gt;=3.6.2,&lt;4.0.0
     and plugin-test depends on nonebot-plugin-h2e (^0.1.2), version solving failed.</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 锻炼-#da4a4a, t:what2eat-#99da4a, t: how2exe-#99da4a。</li><li>✅ 项目 <a href="https://github.com/Gin2O/nonebot_plugin_h2e">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-h2e/">nonebot-plugin-h2e</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
