### ISSUE TITLE
Plugin: 呆呆兽都会用的chatbot接api

### ISSUE THREAD

**Issue by Gin2O** [nonebot/nonebot2#1737]
**插件名称：**

呆呆兽都会用的chatbot接api

**插件功能：**

没有上下文语境的简易chatbot，调用openai API

**PyPI 项目名：**

nonebot-plugin-oachat

**插件 import 包名：**

nonebot_plugin_oachat

**插件项目仓库/主页链接：**

https://github.com/Gin2O/nonebot_plugin_oachat

**标签：**

[{"label":"OpenAI","color":"#ea5252"},{"label":"GPT3","color":"#ea5252"},{"label":"ChatBot","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 呆呆兽都会用的chatbot接api

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 nonebot-plugin-oachat 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    Because no versions of nonebot-plugin-oachat match &gt;0.1.1,&lt;0.2.0
     and nonebot-plugin-oachat (0.1.1) depends on asyncio (&gt;=3.6.2), nonebot-plugin-oachat (&gt;=0.1.1,&lt;0.2.0) requires asyncio (&gt;=3.6.2).
    So, because no versions of asyncio match &gt;=3.6.2
     and plugin-test depends on nonebot-plugin-oachat (^0.1.1), version solving failed.</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: OpenAI-#ea5252, ChatGPT-#ea5252, ChatBot-#ea5252。</li><li>✅ 项目 <a href="https://github.com/Gin2O/nonebot_plugin_oachat">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-oachat/">nonebot-plugin-oachat</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Gin2O** [comment]
test

**Comment by Gin2O** [comment]
test

**Comment by Gin2O** [comment]
test

**Comment by Gin2O** [comment]
test

**Comment by Gin2O** [comment]
test
