### ISSUE TITLE
Plugin: wf的wm市场

### ISSUE THREAD

**Issue by mmxd12** [nonebot/nonebot2#1741]
**插件名称：**

wf的wm市场

**插件功能：**

warframe游戏的WM市场查询

**PyPI 项目名：**

nonebot-plugin-warframe-mode

**插件 import 包名：**

nonebot_plugin_warframe_mode

**插件项目仓库/主页链接：**

https://github.com/mmxd12/nonebot_plugin_warframe_mode

**标签：**

[{"label":"星际战甲","color":"#ea5252"},{"label":"warframe","color":"#ea5252"}]

**Comment by StarHeartHunt** [comment]
请正确填写插件依赖

**Comment by mmxd12** [comment]
TT
