### ISSUE TITLE
希望可以添加让command后面必须接空白符的选项。

### ISSUE THREAD

**Issue by BiologyHazard** [nonebot/nonebot2#1743]
**是否在使用中遇到某些问题而需要新的特性？请描述：**
目前on_command辅助函数似乎只要求消息开头含有command即可，若命令后面不跟空格，仍可以触发命令。
如果我希望command后面必须跟空格，我只能使用on_command('something ')，在something后面添加一个空格。
有些命令的参数是可选的，如果用上面的办法，当命令后面不接参数时又会失效。

**描述你所需要的特性：**
我不知道目前有没有完美的解决方案
如果目前的解决方案都比较复杂的话，希望可以添加让command后面必须接空白符的选项。

**Comment by BiologyHazard** [comment]
看起来自己重写command rule是个可能的解决方案，但并不通用

**Comment by Lancercmd** [comment]
拆分成两个 Matcher 。
```python
from nonebot.plugin import MatcherGroup

worker = MatcherGroup(type="message")  # 通用的 Rule 等定义直接在组上
worker1 = worker.on_regex(r"^cmd$")
worker2 = worker.on_regex(r"^cmd ")

@worker1.handle()
async def _():
    pass

@worker2.handle()
async def _():
    pass
```

**Comment by BiologyHazard** [comment]
彳亍，能用（（

**Comment by yanyongyu** [comment]
目前nb依靠前缀树解析命令，解析与触发部分是完全分开的，如果需要强制空格，那就需要在解析命令参数的部分增加一个判断

**Comment by BiologyHazard** [comment]
谢谢大佬～

**Comment by lgc2333** [comment]
支持，这个功能写tg bot是需要的

**Comment by yanyongyu** [comment]
看了下应该是写错了org（，开个新issue吧
