### ISSUE TITLE
Plugin: 战地一入群审批

### ISSUE THREAD

**Issue by qienoob** [nonebot/nonebot2#1744]
**插件名称：**

战地一入群审批

**插件功能：**

战地一通过游戏id的入群审核并其修改群名片为id

**PyPI 项目名：**

nonebot-plugin-bf1-groptools

**插件 import 包名：**

nonebot_plugin_bf1_groptools

**插件项目仓库/主页链接：**

https://github.com/zzcqie666/nonebot_plugin_bf1_groptools

**标签：**

[{"label":"战地一","color":"#52eae4"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 战地一入群审批

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-bf1-groptools 的信息如下：
    name         : nonebot-plugin-bf1-groptools                                                                                         
     version      : 0.0.1                                                                                                                
     description  : Nonebot plug-in that verifies BF1 accounts and automatically approves group applications and changes business cards.
插件 nonebot_plugin_bf1_groptools 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 战地一-#52eae4。</li><li>✅ 项目 <a href="https://github.com/zzcqie666/nonebot_plugin_bf1_groptools">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bf1-groptools/">nonebot-plugin-bf1-groptools</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
评论任意内容

**Comment by zzcqie666** [comment]
刷新，请重新检测

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新检测

**Comment by zzcqie666** [comment]
> **插件名称：**
> 
> 战地一入群审批
> 
> **插件功能：**
> 
> 战地一通过游戏id的入群审核并其修改群名片为id
> 
> **PyPI 项目名：**
> 
> nonebot-plugin-bf1-groptools
> 
> **插件 import 包名：**
> 
> nonebot_plugin_bf1_groptools
> 
> **插件项目仓库/主页链接：**
> 
> https://github.com/zzcqie666/nonebot_plugin_bf1_groptools
> 
> **标签：**
> 
> [{"label":"战地一","color":"#52eae4"}]

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
来刷新检测

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新

**Comment by zzcqie666** [comment]
刷新
