### ISSUE TITLE
Plugin: 60s日历

### ISSUE THREAD

**Issue by techotaku39** [nonebot/nonebot2#1751]
**插件名称：**

60s日历

**插件功能：**

每天60秒读懂世界

**PyPI 项目名：**

nonebot-plugin-60s

**插件 import 包名：**

nonebot_plugin_60s

**插件项目仓库/主页链接：**

https://github.com/techotaku39/nonebot-plugin-60s

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 60s日历

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-60s 的信息如下：
    name         : nonebot-plugin-60s 
     version      : 0.1.1              
     description  : 每天60秒读懂世界
插件 nonebot_plugin_60s 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/techotaku39/nonebot-plugin-60s">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-60s/">nonebot-plugin-60s</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by techotaku39** [comment]
v0.1.2

**Comment by he0119** [comment]
pypi有时候会有延迟

**Comment by techotaku39** [comment]
大佬现在可以了吗，抱歉我第一次上传插件

**Comment by he0119** [comment]
还是不行，你需要在 https://github.com/techotaku39/nonebot-plugin-60s/blob/d4607a41567f06a5e8196191fdc858883f67ad22/pyproject.toml#L10

这里加上 nonebot2 的依赖。比如使用 `poetry add nonebot2` 命令。

**Comment by techotaku39** [comment]
加上了，谢谢大佬

**Comment by yanyongyu** [comment]
`nonebot-plugin-apscheduler`的版本不正确

**Comment by techotaku39** [comment]
重新打包了 > <
