### ISSUE TITLE
Plugin: 网抑云

### ISSUE THREAD

**Issue by techotaku39** [nonebot/nonebot2#1759]
**插件名称：**

网抑云

**插件功能：**

一开口就老网抑云了

**PyPI 项目名：**

nonebot-plugin-ncm-saying

**插件 import 包名：**

nonebot_plugin_ncm_saying

**插件项目仓库/主页链接：**

https://github.com/techotaku39/nonebot-plugin-ncm-saying

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 网抑云

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/techotaku39/nonebot-plugin-ncm-saying">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ncm-saying/">nonebot-plugin-ncm-saying</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
