### ISSUE TITLE
请问，怎么处理 别人 邀请入群，或者 加好友请求 ？？谢谢 

### ISSUE THREAD

**Issue by djtu** [nonebot/nonebot2#176]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

请问，怎么处理 别人 邀请入群，或者 加好友请求 ？？谢谢 

**描述你所需要的特性：**

请问，怎么处理 别人 邀请入群，或者 加好友请求 ？？谢谢 

做好给个简单的代码，非常感谢

**Comment by yanyongyu** [comment]
事件的响应可以使用`on_notice`,  `on_request`, `on_metaevent` 注册响应器，可以参考如下代码

https://github.com/cscs181/QQ-GitHub-Bot/blob/7698e42d6f595d886cd98ddc2b972d268df034b6/src/plugins/nonebot_plugin_status/__init__.py#L51

事件类型可以从 `nonebot.adapters.cqhttp` 导入，具体可以查看api文档以及onebot文档

https://v2.nonebot.dev/api/adapters/cqhttp.html#nonebot-adapters-cqhttp-event-%E6%A8%A1%E5%9D%97

https://github.com/howmanybots/onebot/blob/master/v11/specs/README.md

**Comment by djtu** [comment]
谢谢yanyongyu   事件捕获到了，如果要 同意邀请，或者拒绝邀请，需要怎么处理呢？

**Comment by yanyongyu** [comment]
当前版本需要自行调用api `set_friend_add_request` `set_group_add_request`，下一个版本可以使用`event.approve` `event.reject`

**Comment by djtu** [comment]
收到，谢谢！~可以关闭了

**Comment by SD7935** [comment]
能给个处理事件的例子嘛，不太会用api🥺
