### ISSUE TITLE
Plugin: ChatGPT官方接口版

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#1766]
**插件名称：**

ChatGPT官方接口版

**插件功能：**

适配新版OpenAI API的nonebot插件，可以调用官方稳定版ChatGPT进行回复

**PyPI 项目名：**

nonebot-plugin-chatgpt-turbo

**插件 import 包名：**

nonebot_plugin_chatgpt_turbo

**插件项目仓库/主页链接：**

https://github.com/Alpaca4610/nonebot_plugin_chatgpt_turbo

**标签：**

[{"label":"ChatGPT","color":"#ea5252"},{"label":"OpenAI","color":"#52ea92"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ChatGPT官方接口版

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-chatgpt-turbo 的信息如下：
    name         : nonebot-plugin-chatgpt-turbo             
     version      : 0.1.0                                    
     description  : A nonebot plugin for openai gpt3.5-turbo 
    
    dependencies
     - httpx &gt;=0.23.3,&lt;0.24.0
     - nonebot-adapter-onebot &gt;=2.2.1,&lt;3.0.0
     - nonebot2 &gt;=2.0.0rc3,&lt;3.0.0
     - openai &gt;=0.27.0,&lt;0.28.0
插件 nonebot_plugin_chatgpt_turbo 加载出错：
03-02 17:20:32 [SUCCESS] nonebot | NoneBot is initializing...
03-02 17:20:32 [INFO] nonebot | Current Env: prod
03-02 17:20:32 [ERROR] nonebot | Failed to import &quot;nonebot_plugin_chatgpt_turbo&quot;
Traceback (most recent call last):
  File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 4, in &lt;module&gt;
    valid = load_plugin(&quot;nonebot_plugin_chatgpt_turbo&quot;)
  File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py&quot;, line 34, in load_plugin
    return manager.load_plugin(module_path)
&gt; File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 141, in load_plugin
    module = importlib.import_module(name)
  File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1006, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 688, in _load_unlocked
  File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 233, in exec_module
    super().exec_module(module)
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 883, in exec_module
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed
  File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_chatgpt_turbo/__init__.py&quot;, line 10, in &lt;module&gt;
    api_key = nonebot.get_driver().config.openai_api_key
AttributeError: &#x27;Config&#x27; object has no attribute &#x27;openai_api_key&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: ChatGPT-#ea5252, OpenAI-#52ea92。</li><li>✅ 项目 <a href="https://github.com/Alpaca4610/nonebot_plugin_chatgpt_turbo">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatgpt-turbo/">nonebot-plugin-chatgpt-turbo</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Alpaca4610** [comment]
test

**Comment by Alpaca4610** [comment]
> # 📃 商店发布检查结果
> > Plugin: ChatGPT官方接口版
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-chatgpt-turbo 的信息如下：
>       name         : nonebot-plugin-chatgpt-turbo             
>        version      : 0.1.0                                    
>        description  : A nonebot plugin for openai gpt3.5-turbo 
>       
>       dependencies
>        - httpx >=0.23.3,<0.24.0
>        - nonebot-adapter-onebot >=2.2.1,<3.0.0
>        - nonebot2 >=2.0.0rc3,<3.0.0
>        - openai >=0.27.0,<0.28.0
>   插件 nonebot_plugin_chatgpt_turbo 加载出错：
>   03-02 17:33:35 [SUCCESS] nonebot | NoneBot is initializing...
>   03-02 17:33:35 [INFO] nonebot | Current Env: prod
>   03-02 17:33:36 [ERROR] nonebot | Failed to import "nonebot_plugin_chatgpt_turbo"
>   Traceback (most recent call last):
>     File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>       valid = load_plugin("nonebot_plugin_chatgpt_turbo")
>     File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
>       return manager.load_plugin(module_path)
>   > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>       module = importlib.import_module(name)
>     File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>       return _bootstrap._gcd_import(name[level:], package, level)
>     File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>     File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>     File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>     File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>     File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
>       super().exec_module(module)
>     File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>     File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_chatgpt_turbo/__init__.py", line 10, in <module>
>       api_key = nonebot.get_driver().config.openai_api_key
>   AttributeError: 'Config' object has no attribute 'openai_api_key'
> ```
> 
> 详情
> ```
> * ✅ 标签: ChatGPT-#ea5252, OpenAI-#52ea92。* ✅ 项目 [主页](https://github.com/Alpaca4610/nonebot_plugin_chatgpt_turbo) 返回状态码 200。* ✅ 包 [nonebot-plugin-chatgpt-turbo](https://pypi.org/project/nonebot-plugin-chatgpt-turbo/) 已发布至 PyPI。
> ```
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

test

**Comment by mnixry** [comment]
你是不是忘记在PyPI上发布新版了

**Comment by Alpaca4610** [comment]
> 你是不是忘记在PyPI上发布新版了

orz，第一次上传插件没太注意这些细节，现在已经在pypi上更新了QAQ

**Comment by yanyongyu** [comment]
请用openai的[异步接口](https://github.com/openai/openai-python#async-api)，你这异步太假了

**Comment by Alpaca4610** [comment]
> 请用openai的[异步接口](https://github.com/openai/openai-python#async-api)，你这异步太假了。openai默认是requests

orz，我之前直接把OpenAI官网API文档的调用example搬下来了。已改为第二种（第一种使用的时候有点问题，不知道是不是新版API文档还没更新）

**Comment by yanyongyu** [comment]
你这也没改对啊

```diff
 async def get_response(user_id, content):
     openai.api_key = api_key

-    res_ = openai.ChatCompletion.create(
+    res_ = await openai.ChatCompletion.acreate(
         model=model_id,
         messages=[
             {"role": "user", "content": content}
         ]
     )
```

**Comment by Alpaca4610** [comment]
> 你这也没改对啊，不是让你改session啊
> 
> ```diff
>  async def get_response(user_id, content):
>      openai.api_key = api_key
> 
> -    res_ = openai.ChatCompletion.create(
> +    res_ = await openai.ChatCompletion.acreate(
>          model=model_id,
>          messages=[
>              {"role": "user", "content": content}
>          ]
>      )
> ```

> 使用acreate()函数进行请求会返回Error communicating with OpenAI的错误信息。

**Comment by Alpaca4610** [comment]
已在代码中添加asyncio

**Comment by yanyongyu** [comment]
不是，我不是给你了修改样例了吗，你在瞎改啥（

**Comment by Alpaca4610** [comment]
> 不是，我不是给你了修改样例了吗，你在瞎改啥（

目前官方的异步API调用会出错，返回不了信息（

**Comment by Alpaca4610** [comment]
> > 不是，我不是给你了修改样例了吗，你在瞎改啥（
> 
> 目前官方的异步API调用会出错，返回不了信息（

model设置为最新的gpt-3.5-turbo时，调用会长时间无响应，返回Error communicating with OpenAI。所以我就自己整了个asyncio（

**Comment by yanyongyu** [comment]
![image](https://user-images.githubusercontent.com/42488585/222638540-9eea1d23-236e-48a4-b660-3b1ae814b87b.png)

**Comment by yanyongyu** [comment]
`await openai.ChatCompletion.acreate`

**Comment by Alpaca4610** [comment]
> https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
> 
> ![image](https://user-images.githubusercontent.com/42488585/222638540-9eea1d23-236e-48a4-b660-3b1ae814b87b.png)

我的代码中使用的就是`openai.ChatCompletion.create`函数（ 问题是在于使用`await openai.ChatCompletion.acreate`发送请求时会出现错误，而改用`openai.ChatCompletion.create`才可以正常返回结果。

在下面的测试中，我用不同的命令触发异步和非异步的访问请求，结果是使用`await openai.ChatCompletion.acreate`时无法返回结果。

<img width="443" alt="iShot_2023-03-03_14 20 35" src="https://user-images.githubusercontent.com/16055526/222647066-f6aa1cc4-8d05-4a9a-a09c-adf55ff51d39.png">
<img width="501" alt="iShot_2023-03-03_14 18 02" src="https://user-images.githubusercontent.com/16055526/222647050-1aaafab2-d5c7-47cf-ba5d-d7d0443e9b26.png">
<img width="465" alt="iShot_2023-03-03_14 26 43" src="https://user-images.githubusercontent.com/16055526/222647391-b995459e-e118-4019-8133-39f9fe3a3078.png">

**Comment by Alpaca4610** [comment]
> `await openai.ChatCompletion.acreate`
> 
> 另外你的插件也不依赖httpx，不需要这个依赖

https://github.com/openai/openai-python/issues/250#issuecomment-1451599906
在openai-python的项目里也存在着出现这个问题的issue

**Comment by Alpaca4610** [comment]
> https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
> 
> ![image](https://user-images.githubusercontent.com/42488585/222638540-9eea1d23-236e-48a4-b660-3b1ae814b87b.png)

https://github.com/openai/openai-python/issues/250#issuecomment-1451599906
https://github.com/openai/openai-python/issues/250#issuecomment-1451613399
看了openai-python项目下的两条issue，感觉是openai那边还没有更新异步请求函数（ ，`openai.ChatCompletion.**a**create`目前还无法使用

**Comment by Alpaca4610** [comment]
删除pyproject.poml中的httpx依赖

**Comment by yanyongyu** [comment]
等他异步接口修好了再合吧

**Comment by yanyongyu** [comment]
看openai的issue说是没有问题了，你再试试？

**Comment by Alpaca4610** [comment]
> 看openai的issue说是没有问题了，你再试试？

刚刚试了下还是不行，acreate没有修好。
https://github.com/openai/openai-python/issues/278#issue-1611338785

**Comment by Alpaca4610** [comment]
0.2.0更新：使用asyncio库的loop.run_in_executor实现异步调用，增加每个用户的上下文关联回复功能，增加代理设置功能

**Comment by Alpaca4610** [comment]
0.2.1更新:使用OpenAI的异步接口和代理

**Comment by yanyongyu** [comment]
你依赖里多写了一个asyncio

**Comment by Alpaca4610** [comment]
更新依赖

**Comment by yanyongyu** [comment]
你在pypi发版了吗

**Comment by Alpaca4610** [comment]
> 你在pypi发版了吗

发了

**Comment by Alpaca4610** [comment]
update

**Comment by zdyy001** [comment]
@Alpaca4610 @yanyongyu 本地挂了vpn，proxy = ‘http:\\127.0.0.1:8001'，升级了aiohttp版本3.8.4，在调用`res_ = await openai.ChatCompletion.acreate(
                model=self.model_id,
                messages=self.content
            )`
时，还是会出现Error communicating with OpenAI，是什么原因？

**Comment by Alpaca4610** [comment]
> @Alpaca4610 @yanyongyu 本地挂了vpn，proxy = ‘http:\127.0.0.1:8001'，升级了aiohttp版本3.8.4，在调用`res_ = await openai.ChatCompletion.acreate( model=self.model_id, messages=self.content )`
> 时，还是会出现Error communicating with OpenAI，是什么原因？

注意proxy的端口和你VPN设置的端口一致，另外提issue请到https://github.com/Alpaca4610/nonebot_plugin_chatgpt_turbo/issues
