### ISSUE TITLE
Plugin: Sanae

### ISSUE THREAD

**Issue by Hoshinonyaruko** [nonebot/nonebot2#1774]
**插件名称：**

Sanae

**插件功能：**

早苗连接器,也可转发其他onebotv11到nb2~

**PyPI 项目名：**

nonebot-plugin-sanae

**插件 import 包名：**

nonebot_plugin_sanae

**插件项目仓库/主页链接：**

https://github.com/Hoshinonyaruko/nonebot-plugin-sanae

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Sanae

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-sanae 的信息如下：
    name         : nonebot-plugin-sanae 
     version      : 0.0.1                
     description  : sanae connecter      
    
    dependencies
     - aiohttp &gt;=2.2.5
     - asyncio &gt;=3.4.3
插件 nonebot-plugin-sanae 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Hoshinonyaruko/nonebot-plugin-sanae">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-sanae/">nonebot-plugin-sanae</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Hoshinonyaruko** [comment]
阿巴阿巴

**Comment by Hoshinonyaruko** [comment]
阿巴阿巴

**Comment by yanyongyu** [comment]
asyncio不需要写在依赖里，python<3.5才需要
