### ISSUE TITLE
Bot: LOVE酱

### ISSUE THREAD

**Issue by allureluoli** [nonebot/nonebot2#1778]
**机器人名称：**

LOVE酱

**机器人功能：**

为铁锈战争游戏群服务的虚拟少女,内置了爬取铁锈房间列表功能,以及游戏内单位查询功能,并制作了教学系统以及铁锈相关游戏群的收集功能。

**机器人项目仓库/主页链接：**

https://github.com/allureluoli/LOVE-

**标签：**

[{"label":"铁锈战争","color":"#19e229"},{"label":"RW","color":"#19e229"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: LOVE酱

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 铁锈战争-#19e229, RW-#19e229。</li><li>✅ 项目 <a href="https://github.com/allureluoli/LOVE-">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
