### ISSUE TITLE
Bot: fubot

### ISSUE THREAD

**Issue by HCskia** [nonebot/nonebot2#1782]
**机器人名称：**

fubot

**机器人功能：**

基于nonebot与go-cqhttp的QQ娱乐bot，提供群日常娱乐功能与舞萌DX游戏相关的信息查询功能。

**机器人项目仓库/主页链接：**

https://github.com/HCskia/fu-Bot

**标签：**

[{"label":"maimai","color":"#52eaa5"},{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: fubot

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: maimai-#52eaa5, go-cqhttp-#6aea52, nonebotv11-#6aea52。</li><li>✅ 项目 <a href="https://github.com/HCskia/fu-Bot">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
