### ISSUE TITLE
Plugin: 和团子聊天！

### ISSUE THREAD

**Issue by TheLZY** [nonebot/nonebot2#1784]
**插件名称：**

和团子聊天！

**插件功能：**

来和团子聊天吧~  Powered by chatgpt

**PyPI 项目名：**

nonebot-plugin-tuan-chatgpt

**插件 import 包名：**

nonebot_plugin_tuan_chatgpt

**插件项目仓库/主页链接：**

https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt

**标签：**

[{"label":"t:chat","color":"#ff9d97"},{"label":"t:chatgpt","color":"#ff9d97"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 和团子聊天！

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:chat-#ff9d97, t:chatgpt-#ff9d97。</li><li>✅ 项目 <a href="https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tuan-chatgpt/">nonebot-plugin-tuan-chatgpt</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by yanyongyu** [comment]
你这里真的没有写错吗？是不是少了个`a`

https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/blob/df434c710e610206e3f6920ef4f25dcfa4c3ffe5/nonebot_plugin_tuan_chatgpt/chatgpt.py#L54-L69

**Comment by TheLZY** [comment]
> 

可以使用！（我发现我只加到了测试环境）
我怀疑是梯子的问题？

**Comment by yanyongyu** [comment]
@Suxmx @Alpaca4610

**Comment by Alpaca4610** [comment]
> 可以使用！ 我怀疑是梯子的问题？
> 
> ![image](https://user-images.githubusercontent.com/32624562/224017730-21092ef2-1694-48ef-b25a-b51364b34d62.png) ![image](https://user-images.githubusercontent.com/32624562/224017821-8d4156bb-4894-4505-bba5-057fcff5fb57.png)

请问你的网络环境是？截止2023.3.9 22:01，我在全局梯子、python设置代理、USA的VPS三种环境下都无法正常使用异步接口，想看一下你是在什么环境下成功的。

**Comment by yanyongyu** [comment]
或者你们可以试试梯子能不能上chatgpt网页版，有些ip可能被ban了？

**Comment by Suxmx** [comment]
可以进的...create方法也是正常的,唯独用acreate会出错

**Comment by Alpaca4610** [comment]
> 或者你们可以试试梯子能不能上chatgpt网页版，有些ip可能被ban了？

我的是可以访问网页版的的，除了acreate接口，其他接口也正常。

**Comment by yanyongyu** [comment]
看看openai的版本？

**Comment by Alpaca4610** [comment]
> 看看openai的版本？这总不能是帐号的问题吧（（

0.27.1

**Comment by TheLZY** [comment]
openai == 0.27.0
最近openai没咋更新，按理来说能调用gpt-3.5-turbo 的都是这个版本（
可能我是肉身翻墙，acreate确实有梯子的问题

有空我拿国内的服务器试一下（

**Comment by Alpaca4610** [comment]
> openai == 0.27.0 最近openai没咋更新，按理来说能调用gpt-3.5-turbo 的都是这个版本（ 可能我是肉身翻墙，acreate确实有梯子的问题
> 
> 有空我拿国内的服务器试一下（

我刚刚更新到的0.27.1（ ，上一个版本0.27.0也不行，还以为是0.27.0的问题（

**Comment by TheLZY** [comment]
怪了，我在服务器上跑，加了代理之后用async会报错，但是在家里的电脑上跑就都没有问题

![image](https://user-images.githubusercontent.com/32624562/224154226-fa48cc61-2b40-4cea-a525-e5dc6289be77.png)
梯子：
![image](https://user-images.githubusercontent.com/32624562/224154434-e7a62701-a3e4-4996-9818-66c8a34ea975.png)

我怀疑是aiohttp版本（特别是涉及ssl处理有关）的问题，因为搜到好几个与这个有关的错误

服务器报错的其中一段：
```
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [参数错误。]
```

还有一个解决了我服务器端的问题的
```
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())   # 加上这一行,解决使用代理请求 https会报错问题
```
ref: https://www.phper163.com/article/39.html

我再研究研究到底是哪个环节出了问题。。。。。。

**Comment by TheLZY** [comment]
服务器 `pip install --upgrade aiohttp` 之后没有问题了

测试结果：
![image](https://user-images.githubusercontent.com/32624562/224162050-d23b41a7-8fa2-4094-8199-95c6d56af89c.png)


测试脚本：
（换成.py）
[test_acreate.txt](https://github.com/nonebot/nonebot2/files/10936134/test_acreate.txt)

所以得回去加上 aiohttp>=3.8.4 了 （之前不行的是 aiohttp==3.7.4.post0 ）

**Comment by TheLZY** [comment]
@Suxmx @Alpaca4610

**Comment by Alpaca4610** [comment]
> @Suxmx @Alpaca4610

感谢！

**Comment by Alpaca4610** [comment]
> 服务器 `pip install --upgrade aiohttp` 之后没有问题了
> 
> 测试结果： ![image](https://user-images.githubusercontent.com/32624562/224162050-d23b41a7-8fa2-4094-8199-95c6d56af89c.png)
> 
> 测试脚本： （换成.py） [test_acreate.txt](https://github.com/nonebot/nonebot2/files/10936134/test_acreate.txt)
> 
> 所以得回去加上 aiohttp>=3.8.4 了 （之前不行的是 aiohttp==3.7.4.post0 ）

你的测试脚本这有个问题，好像你的main函数和main_a里面调用的都是非异步接口进行的消息获取？使用异步接口获取的信息存储的asr变量从来没有被访问。也就是说你的两个测试结果都是在非异步的接口下获取的。
<img width="495" alt="iShot_2023-03-10_11 41 47" src="https://user-images.githubusercontent.com/16055526/224218096-255fcb34-e3c1-418a-89dc-fb6d1d667de7.png">

**Comment by TheLZY** [comment]
啊，确实，我就说咋截图的时候两个都是一样的（
这就去改（

![image](https://user-images.githubusercontent.com/32624562/224219179-2f20a8b5-812c-463b-b58d-7f94406120cd.png)

[test_acreate.txt](https://github.com/nonebot/nonebot2/files/10938286/test_acreate.txt)

**Comment by Suxmx** [comment]
我早上早八之前急急忙忙试了一下，发现还是报错了，不过我直接挂的梯子没有设置openai.proxy我以为是这个的问题😣

**Comment by Alpaca4610** [comment]
> 我早上早八之前急急忙忙试了一下，发现还是报错了，不过我直接挂的梯子没有设置openai.proxy我以为是这个的问题😣

我设置了openai.proxy之后在楼上的测试脚本里跑通了

**Comment by Suxmx** [comment]
我设置了之后也可以了！非常感谢！

**Comment by yanyongyu** [comment]
所以升级aiohttp之后就好使了么:joy:

**Comment by Suxmx** [comment]
我不确定是aiohttp版本的问题还是openai.proxy的设置问题 不过 @Alpaca4610 说他之前也试过了不行，估计是要设置openai.proxy+升级aiohttp😂

**Comment by TheLZY** [comment]
我是这样的，测试了三台设备，现在也已经在国内的服务器上挂着了😂
大部分问题都是版本问题，这很合理（
