### ISSUE TITLE
Plugin: ChatPDF文章分析

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#1787]
**插件名称：**

ChatPDF文章分析

**插件功能：**

在nonebot中使用ChatPDF的最小实现来中分析文章内容

**PyPI 项目名：**

nonebot-plugin-chatpdf

**插件 import 包名：**

nonebot_plugin_chatpdf

**插件项目仓库/主页链接：**

https://github.com/Alpaca4610/nonebot_plugin_chatpdf

**标签：**

[{"label":"ChatGPT","color":"#ea5252"},{"label":"ChatPDF","color":"#6c7abd"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ChatPDF文章分析

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: ChatGPT-#ea5252, ChatPDF-#6c7abd。</li><li>✅ 项目 <a href="https://github.com/Alpaca4610/nonebot_plugin_chatpdf">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatpdf/">nonebot-plugin-chatpdf</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Alpaca4610** [comment]
使用OpenAI的异步接口和代理

**Comment by Alpaca4610** [comment]
更新依赖

**Comment by Alpaca4610** [comment]
update

**Comment by yanyongyu** [comment]
已经发布的不需要update
