### ISSUE TITLE
Plugin: 群聊自定义表情包

### ISSUE THREAD

**Issue by DMCSWCG** [nonebot/nonebot2#1794]
**插件名称：**

群聊自定义表情包

**插件功能：**

发送 表情名称 加 (.jpg或.png或.gif)后缀，就会发送设置好的表情。快速方便，聊天必备。

**PyPI 项目名：**

nonebot-plugin-customemote

**插件 import 包名：**

nonebot_plugin_customemote

**插件项目仓库/主页链接：**

https://github.com/DMCSWCG/nonebot-plugin-customemote/

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 群聊自定义表情包

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/DMCSWCG/nonebot-plugin-customemote/">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-customemote/">nonebot-plugin-customemote</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
