### ISSUE TITLE
Plugin: chatgpt插件api版

### ISSUE THREAD

**Issue by TheKOG** [nonebot/nonebot2#1796]
**插件名称：**

chatgpt插件api版

**插件功能：**

基于openai的api实现的chatgpt插件, 可以分辨不同说话者的身份

**PyPI 项目名：**

**插件 import 包名：**

nonebot_plugin_chatgpt_api

**插件项目仓库/主页链接：**

https://github.com/TheKOG/nonebot_plugin_chatgpt_api

**标签：**

[{"label":"t:chat","color":"#ea5252"},{"label":"a:cqhttp","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: chatgpt插件api版

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ project_link: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary></details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: t:chat-#ea5252, a:cqhttp-#ea5252。</li><li>✅ 项目 <a href="https://github.com/TheKOG/nonebot_plugin_chatgpt_api">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by mnixry** [comment]
仓库文件不全，Issue内容没填全，然后要用异步API，ref #1766
