### ISSUE TITLE
Plugin: 修仙模拟器

### ISSUE THREAD

**Issue by luoyefufeng** [nonebot/nonebot2#1799]
**插件名称：**

修仙模拟器

**插件功能：**

基于原版修仙的修改

**PyPI 项目名：**

nonebot-plugin-simulator-xiuxian

**插件 import 包名：**

nonebot_plugin_simulator_xiuxian

**插件项目仓库/主页链接：**

https://github.com/luoyefufeng/nonebot_plugin_simulator_xiuxian

**标签：**

[{"label":"文游","color":"#4256da"},{"label":"修仙1.0","color":"#1d1b1c"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 修仙1.0

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ PyPI 项目名 https://pypi.org/project/nonebot_plugin_xiuxian_1 不符合规范。<dt>请确保项目名正确。</dt></li><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>项目 https://pypi.org/project/nonebot_plugin_xiuxian_1 创建失败：
    Creating virtualenv plugin-test-rYmcgvOP-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
    
    file could not be opened successfully:
    - method gz: ReadError(&#x27;not a gzip file&#x27;)
    - method bz2: ReadError(&#x27;not a bzip2 file&#x27;)
    - method xz: ReadError(&#x27;not an lzma file&#x27;)
    - method tar: ReadError(&#x27;invalid header&#x27;)</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: 文游-#4256da, 修仙1.0-#1d1b1c。</li><li>✅ 项目 <a href="https://github.com/luoyefufeng/nonebot_plugin_xiuxian_1">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
