### ISSUE TITLE
Bot: 桃桃酱

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#1800]
**机器人名称：**

桃桃酱

**机器人功能：**

一个会拆家的高性能缝合萝卜子

**机器人项目仓库/主页链接：**

https://github.com/tkgs0/Momoko

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: 桃桃酱

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:OneBot11-#000000。</li><li>✅ 项目 <a href="https://github.com/tkgs0/Momoko">主页</a> 返回状态码 200。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
