### ISSUE TITLE
Plugin: apex信息查询

### ISSUE THREAD

**Issue by Windylh** [nonebot/nonebot2#1810]
**插件名称：**

apex信息查询

**插件功能：**

查询apex玩家信息、地图等信息

**PyPI 项目名：**

nonebot-plugin-apexranklookup

**插件 import 包名：**

nonebot_plugin_apexranklookup

**插件项目仓库/主页链接：**

https://github.com/Windylh/nonebot_plugin_apexranklookup

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: apex信息查询

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-apexranklookup 的信息如下：
    name         : nonebot-plugin-apexranklookup 
     version      : 0.1.0                         
     description  :                               
    
    dependencies
     - Pillow &gt;=9.4.0,&lt;10.0.0
     - pydantic &gt;=1.10.6,&lt;2.0.0
插件 nonebot-plugin-apexranklookup 依赖的插件如下：
    
插件 nonebot_plugin_apexranklookup 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin, require
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Windylh/nonebot_plugin_apexranklookup">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-apexranklookup/">nonebot-plugin-apexranklookup</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Windylh** [comment]
已更新

**Comment by Windylh** [comment]
test

**Comment by Windylh** [comment]
0.1.1:修改依赖包

**Comment by Windylh** [comment]
Update to 0.1.2

**Comment by Windylh** [comment]
Update to 0.1.3

**Comment by Windylh** [comment]
Update to 0.1.4.
 - add nonebot-adapter-onebot
