### ISSUE TITLE
Plugin: 随机点名

### ISSUE THREAD

**Issue by QingMuCat** [nonebot/nonebot2#1818]
**插件名称：**

随机点名

**插件功能：**

就是群聊点名，让学生感受刺激

**PyPI 项目名：**

nonebot-plugin-rrc

**插件 import 包名：**

nonebot_plugin_rrc

**插件项目仓库/主页链接：**

https://github.com/QingMuCat/nonebot-plugin-rrc

**标签：**

[{"label":"课堂","color":"#ea5252"},{"label":"抽人","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 随机点名

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 课堂-#ea5252, 抽人-#ea5252。</li><li>✅ 项目 <a href="https://github.com/QingMuCat/nonebot-plugin-rrc">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-rrc/">nonebot-plugin-rrc</a> 已发布至 PyPI。</li><li>✅ 插件加载测试通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by yanyongyu** [comment]
请不要在插件依赖里使用`==`写死版本

**Comment by QingMuCat** [comment]
好的，新版本已经更新去除
