### ISSUE TITLE
Plugin: ChatGLM

### ISSUE THREAD

**Issue by DaoMingze** [nonebot/nonebot2#1827]
**插件名称：**

ChatGLM

**插件功能：**

基于ChatGLM-6B模型，提供本地中文（汉语）聊天机器人功能

**PyPI 项目名：**

nonebot-plugin-chatglm

**插件 import 包名：**

nonebot_plugin_chatglm

**插件项目仓库/主页链接：**

https://github.com/DaoMingze/zhukebot/tree/main/zhukebot/plugins/chatglm

**标签：**

[{"label": "t:Chatbot","color": "#4366eb"},{"label": "ChatGLM","color": "#af286f"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: ChatGLM

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-chatglm 的信息如下：
    name         : nonebot-plugin-chatglm  
     version      : 0.1.0                   
     description  : 基于ChatGLM-6B的NoneBot2插件
插件 nonebot-plugin-chatglm 依赖的插件如下：
    
插件 nonebot_plugin_chatglm 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin, require
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/DaoMingze/zhukebot/tree/main/zhukebot/plugins/chatglm">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatglm/">nonebot-plugin-chatglm</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by DaoMingze** [comment]
增加对话记录导出功能

**Comment by he0119** [comment]
你的包里没有东西啊……

**Comment by DaoMingze** [comment]
我是sb，:worried:，忘记命名包名了，所以掉到site-package的根目录里了。抱歉，已修复

**Comment by DaoMingze** [comment]
> 你的包里没有东西啊……

我是sb，😟，忘记命名包名了，所以掉到site-package的根目录里了。抱歉，已修复。现在把默认调整为CPU推理。

**Comment by DaoMingze** [comment]
更新至0.1.4。①加入简陋的ChatRWKV支持用来续写中文小说文本；②加入冷却时间（默认30），防止高频请求堵塞（内嵌模型，线性处理请求）。
