### ISSUE TITLE
Plugin: 喵喵点歌

### ISSUE THREAD

**Issue by nikissXI** [nonebot/nonebot2#1837]
**插件名称：**

喵喵点歌

**插件功能：**

可听歌可下载，音乐源酷我音乐

**PyPI 项目名：**

nonebot-plugin-nya-music

**插件 import 包名：**

nonebot_plugin_nya_music

**插件项目仓库/主页链接：**

https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_nya_music

**标签：**

[{"label":"点歌","color":"#f05cea"},{"label":"酷我","color":"#dea833"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 喵喵点歌

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 点歌-#f05cea, 酷我-#dea833。</li><li>✅ 项目 <a href="https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_nya_music">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_nya_music/">nonebot_plugin_nya_music</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4508902816">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
