### ISSUE TITLE
Bug: nb-cli 1.0.5 requirement conflict with nonebot-adapter-feishu 2.0.0b7

### ISSUE THREAD

**Issue by wiketool** [nonebot/nonebot2#1839]
**描述问题：**

pip依赖冲突

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nonebot-adapter-feishu 2.0.0b7 requires cashews<5.0.0,>=4.0.0, but you have cashews 5.3.1 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nb-cli 1.0.5 requires cashews~=5.0, but you have cashews 4.7.1 which is incompatible.

**环境信息：**

 - OS: windows 10
 - Python Version: 3.9
 - Nonebot Version: 2.0.0rc3

**协议端信息：**

 - 协议端: nonebot-adapter-feishu
 - 协议端版本: 2.0.0b7

**截图或日志**
![image](https://user-images.githubusercontent.com/64351271/227468301-9bb2d55d-5c61-4881-bf2f-c12cd6134f9d.png)

**Comment by he0119** [comment]
你可以通过 pipx 安装 nb-cli 来避免这个问题，现在的 cli 是独立的了。

**Comment by yanyongyu** [comment]
nb-cli推荐使用pipx安装
```bash
pip install --user pipx
pipx install nb-cli
```
