### ISSUE TITLE
Plugin: 通括膨胀

### ISSUE THREAD

**Issue by NCBM** [nonebot/nonebot2#1846]
**插件名称：**

通括膨胀

**插件功能：**

让你的机器人随机发括号

**PyPI 项目名：**

nonebot-plugin-overbracket

**插件 import 包名：**

nonebot_plugin_overbracket

**插件项目仓库/主页链接：**

https://github.com/NCBM/nonebot-plugin-overbracket

**标签：**

[{"label":"t:useless","color":"#0a930e"},{"label":"a:all","color":"#e15149"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 通括膨胀

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:useless-#0a930e, a:all-#e15149。</li><li>✅ 项目 <a href="https://github.com/NCBM/nonebot-plugin-overbracket">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-overbracket/">nonebot-plugin-overbracket</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4524538603">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
