### ISSUE TITLE
Plugin: 颠倒问号

### ISSUE THREAD

**Issue by NumberSir** [nonebot/nonebot2#1848]
**插件名称：**

颠倒问号

**插件功能：**

发送单个问号 `?` 或 `？`, bot会自动回复颠倒的问号 `¿`

**PyPI 项目名：**

nonebot-plugin-questionmark

**插件 import 包名：**

nonebot_plugin_questionmark

**插件项目仓库/主页链接：**

https://github.com/NumberSir/nonebot-plugin-questionmark

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 颠倒问号

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252。</li><li>✅ 项目 <a href="https://github.com/NumberSir/nonebot-plugin-questionmark">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-questionmark/">nonebot-plugin-questionmark</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4524678228">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by yanyongyu** [comment]
你这插件为啥需要onebot啊，可以适配全平台的 `event.get_plaintext()`
