### ISSUE TITLE
Plugin: nonebot-plugin-miao

### ISSUE THREAD

**Issue by CMHopeSunshine** [nonebot/nonebot2#1850]
**插件名称：**

nonebot-plugin-miao

**插件功能：**

给Bot的发言添加一些奇怪的口癖

**PyPI 项目名：**

nonebot-plugin-miao

**插件 import 包名：**

nonebot_plugin_miao

**插件项目仓库/主页链接：**

https://github.com/CMHopeSunshine/nonebot-plugin-miao

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-miao

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/CMHopeSunshine/nonebot-plugin-miao">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-miao/">nonebot-plugin-miao</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4524998251">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
