### ISSUE TITLE
为啥看不到文档，简单安装完怎么使用呢

### ISSUE THREAD

**Issue by umena337** [nonebot/nonebot2#1852]
**描述问题：**

**如何复现？**

**期望的结果**

**环境信息：**

 - OS: [e.g. Linux]
 - Python Version: [e.g. 3.8]
 - Nonebot Version: [e.g. 2.0.0]

**协议端信息：**

 - 协议端: [e.g. go-cqhttp]
 - 协议端版本: [e.g. 1.0.0]

**截图或日志**

**Comment by yanyongyu** [comment]
。。。？

**Comment by CMHopeSunshine** [comment]
6

**Comment by Acpear** [comment]
。。。？？？？

**Comment by lgc2333** [comment]
6 批准入典

**Comment by SK-415** [comment]
![V5MX0JHNW~OG$720CPDH8CD](https://user-images.githubusercontent.com/36433929/227843884-f7fc540e-31d4-4780-a066-09b53b149875.jpg)

**Comment by Well2333** [comment]
![c9e0a43567da07d80e70081035b75506](https://user-images.githubusercontent.com/40534114/227844408-007b795b-902f-42df-9a96-0cd4e58844bf.jpeg)

**Comment by ayanamiblhx** [comment]
`https://nb2.baka.icu/docs/quick-start`

**Comment by BigOrangeQWQ** [comment]
？6

**Comment by djkcyl** [comment]
？

**Comment by yanyongyu** [comment]
https://v2.nonebot.dev/docs/quick-start

现在看到了吗
