### ISSUE TITLE
Plugin: nonebot clock 群闹钟 ⏰

### ISSUE THREAD

**Issue by Zeta-qixi** [nonebot/nonebot2#1861]
**插件名称：**

nonebot clock 群闹钟 ⏰

**插件功能：**

支持群聊 私聊的⏰插件

**PyPI 项目名：**

nonebot-plugin-clock

**插件 import 包名：**

nonebot_plugin_clock

**插件项目仓库/主页链接：**

https://github.com/Zeta-qixi/nonebot-plugin-clock

**标签：**

[{"label":"闹钟","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot clock 群闹钟 ⏰

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-clock 的信息如下：
    name         : nonebot-plugin-clock       
     version      : 0.5.6                      
     description  : nonebot_plugin about clock 
    
    dependencies
     - nonebot2 &gt;=2.0.0rc3
插件 nonebot-plugin-clock 依赖的插件如下：
    
插件 nonebot_plugin_clock 加载出错：
    03-29 09:28:09 [SUCCESS] nonebot | NoneBot is initializing...
    03-29 09:28:09 [INFO] nonebot | Current Env: prod
    03-29 09:28:09 [ERROR] nonebot | Failed to import &quot;nonebot_plugin_clock&quot;
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 4, in &lt;module&gt;
        valid = load_plugin(&quot;nonebot_plugin_clock&quot;)
      File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py&quot;, line 34, in load_plugin
        return manager.load_plugin(module_path)
    &gt; File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 141, in load_plugin
        module = importlib.import_module(name)
      File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import
      File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load
      File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1006, in _find_and_load_unlocked
      File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 688, in _load_unlocked
      File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 233, in exec_module
        super().exec_module(module)
      File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 883, in exec_module
      File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed
      File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_clock/__init__.py&quot;, line 6, in &lt;module&gt;
        from nonebot.adapters.onebot.v11.bot import Bot
    ModuleNotFoundError: No module named &#x27;nonebot.adapters.onebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Zeta-qixi/nonebot-plugin-clock">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-clock/">nonebot-plugin-clock</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by Zeta-qixi** [comment]
1

**Comment by yanyongyu** [comment]
插件依赖中缺少`nonebot-adapter-onebot`

**Comment by Zeta-qixi** [comment]
更新

**Comment by yanyongyu** [comment]
依赖缺少`nonebot-plugin-apscheduler`以及不是`nonebot-adapter-cqhttp`应该是`nonebot-adapter-onenot`

**Comment by Zeta-qixi** [comment]
已修改
