### ISSUE TITLE
Plugin: 今日老婆

### ISSUE THREAD

**Issue by glamorgan9826** [nonebot/nonebot2#1873]
**插件名称：**

今日老婆

**插件功能：**

随机抓取群友做老婆

**PyPI 项目名：**

nonebot-plugin-today-waifu

**插件 import 包名：**

nonebot_plugin_today_waifu

**插件项目仓库/主页链接：**

https://github.com/glamorgan9826/nonebot-plugin-today-waifu

**标签：**

[{"label":"娱乐","color":"#eac752"},{"label":"每日老婆","color":"#9beff6"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 今日老婆

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: 娱乐-#eac752, 今日老婆-#e67676, 每日老婆-#9beff6。</li><li>✅ 项目 <a href="https://github.com/glamorgan9826/nonebot-plugin-today-waifu">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-today-waifu/">nonebot-plugin-today-waifu</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4583522343">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
