### ISSUE TITLE
Plugin: nonebot_api_paddle

### ISSUE THREAD

**Issue by canxin121** [nonebot/nonebot2#1879]
**插件名称：**

nonebot_api_paddle

**插件功能：**

nonebot_api_paddleocr

**PyPI 项目名：**

nonebot-api-paddle

**插件 import 包名：**

nonebot_api_paddle

**插件项目仓库/主页链接：**

https://github.com/canxin121/nonebot_api_paddleocr

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_api_paddleoc

**⚠️ 在发布检查过程中，我们发现以下问题：**
<pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-api-paddleocr 的信息如下：
    name         : nonebot-api-paddleocr 
     version      : 1.0.0                 
     description  : nonebot_api_paddleocr
插件 nonebot-api-paddleocr 依赖的插件如下：
    
插件 requests 加载出错：
    Traceback (most recent call last):
      File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 1, in &lt;module&gt;
        from nonebot import init, load_plugin, require
    ModuleNotFoundError: No module named &#x27;nonebot&#x27;</details></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/canxin121/nonebot_api_paddleocr">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-api-paddleocr/">nonebot-api-paddleocr</a> 已发布至 PyPI。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by canxin121** [comment]
> 

1

**Comment by canxin121** [comment]
1

**Comment by canxin121** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot_api_paddleoc
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-api-paddleocr 的信息如下：
>       name         : nonebot-api-paddleocr 
>        version      : 1.0.3                 
>        description  : nonebot_api_paddleocr
>   插件 nonebot-api-paddleocr 依赖的插件如下：
>       
>   插件 nonebot_api_paddle 加载出错：
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 1, in <module>
>           from nonebot import init, load_plugin, require
>       ModuleNotFoundError: No module named 'nonebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

1
