### ISSUE TITLE
Plugin: AI生成PPT

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#1883]
**插件名称：**

AI生成PPT

**插件功能：**

在nonebot框架下实现一个AI生成指定主题PPT的文件并上传到群文件中

**PyPI 项目名：**

nonebot-plugin-chatppt

**插件 import 包名：**

nonebot_plugin_chatppt

**插件项目仓库/主页链接：**

https://github.com/Alpaca4610/nonebot-plugin-chatppt

**标签：**

[{"label":"ChatGPT","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: AI生成PPT

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: ChatGPT-#ea5252。</li><li>✅ 项目 <a href="https://github.com/Alpaca4610/nonebot-plugin-chatppt">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatppt/">nonebot-plugin-chatppt</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4593510112">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)

**Comment by lxlz1989** [comment]
大哥抽空再把教程详细一点？我搭建完nonebot的QQ机器刃，然后研究半天看不懂

**Comment by Alpaca4610** [comment]
> 大哥抽空再把教程详细一点？我搭建完nonebot的QQ机器刃，然后研究半天看不懂

使用教程吗？你到 https://github.com/Alpaca4610/nonebot-plugin-chatppt/issues 提issue吧，这里不是我的代码仓库。
