### ISSUE TITLE
Plugin: Steam游戏状态播报

### ISSUE THREAD

**Issue by nek0us** [nonebot/nonebot2#1886]
**插件名称：**

Steam游戏状态播报

**插件功能：**

在群内监控播报群友的Steam游戏状态

**PyPI 项目名：**

nonebot-plugin-steam-game-status

**插件 import 包名：**

nonebot_plugin_steam_game_status

**插件项目仓库/主页链接：**

https://github.com/nek0us/nonebot_plugin_steam_game_status

**标签：**

[{"label":"t:Steam","color":"#6690a5"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Steam游戏状态播报

**✅ 所有测试通过，一切准备就绪！**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:Steam-#6690a5。</li><li>✅ 项目 <a href="https://github.com/nek0us/nonebot_plugin_steam_game_status">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-steam-game-status/">nonebot-plugin-steam-game-status</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/4596130288">加载测试</a> 通过。</li></code></pre></details>

---

💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

💪 Powered by [NoneBot2 Publish Bot](https://github.com/nonebot/nonebot2-publish-bot)
