### ISSUE TITLE
Plugin: 宝可梦融合

### ISSUE THREAD

**Issue by IllusiveBull** [nonebot/nonebot2#1911]
**插件名称：**

宝可梦融合

**插件功能：**

Pokemon Infinite Fusion的中文版融合计算器，支持融合420^2=176400种宝可梦

**PyPI 项目名：**

nonebot-plugin-pokemonfusion

**插件 import 包名：**

nonebot_plugin_pokemonfusion

**插件项目仓库/主页链接：**

https://github.com/IllusiveBull/nonebot_plugin_pokemonfusion

**标签：**

[]

**Comment by IllusiveBull** [comment]
已更新

**Comment by he0119** [comment]
看了一下 difflib 是标准库，不需要声明依赖的。还有能不能不用 requests，而是用支持异步的库呢？😥

**Comment by IllusiveBull** [comment]
> 看了一下 difflib 是标准库，不需要声明依赖的。还有能不能不用 requests，而是用支持异步的库呢？😥

感谢指点，我以为不堵主线程就没问题了，用支持异步的库替代会有什么其它区别吗

**Comment by he0119** [comment]
> > 看了一下 difflib 是标准库，不需要声明依赖的。还有能不能不用 requests，而是用支持异步的库呢？😥
> 
> 感谢指点，我以为不堵主线程就没问题了，用支持异步的库替代会有什么其它区别吗

确实是可以，不过用异步的话，就不需要运行在线程池里，不需要新开线程之类的。而且异步写起来也不麻烦吧（

**Comment by forchannot** [comment]
raw.githubusercontent.com在国内大概率无法直连，可以考虑使用ghproxy对其进行代理，使用方法为https://ghproxy.com/https://raw.githubusercontent.com/xxxx

**Comment by IllusiveBull** [comment]
改过了，谢谢两位🙏

**Comment by he0119** [comment]
对了 PIL 的包其实是 [Pillow](https://pypi.org/project/Pillow/)。所以依赖要写 Pillow 而不是 PIL。

**Comment by forchannot** [comment]
还有个建议，不算bug，enable_transparent是可以作为配置项的，发布pypi包后不方便别人改源代码，将其独立为配置项可以方便别人在不修改源码的基础上改变配置，具体可参考商店其他有配置项的插件是如何写的

**Comment by he0119** [comment]
> ModuleNotFoundError: No module named 'nonebot.adapters.onebot'

你还忘记添加 nonebot-adapter-onebot 到依赖了（

**Comment by IllusiveBull** [comment]
> 还有个建议，不算bug，enable_transparent是可以作为配置项的，发布pypi包后不方便别人改源代码，将其独立为配置项可以方便别人在不修改源码的基础上改变配置，具体可参考商店其他有配置项的插件是如何写的

加了，这个本来想加来着想到大部分人用QQ因为透明通道bug不会动这个就懒了💧

**Comment by IllusiveBull** [comment]
测试
