### ISSUE TITLE
Bug: argpraser遇到MessageSegment对象报错

### ISSUE THREAD

**Issue by Feiyuyu0503** [nonebot/nonebot2#1922]
**描述问题：**
https://github.com/nonebot/nonebot2/blob/master/nonebot/rule.py#L532
![image](https://user-images.githubusercontent.com/32660959/231935508-a9e3e15a-f4a7-4c1e-a58b-31ba1c90e140.png)
如果seg是图片例如 [image:file=d81284dd30e2b12f044a15a4c2830224.image, subType=0, url=https://gchat.qpic.cn/gchatpic_new/1543979464/594697041-2827320626-...]，那么state[SHELL_ARGV]这个list中除了str元素还有一个类型为MessageSegment的元素，在第542行就会报错了
![image](https://user-images.githubusercontent.com/32660959/231936180-2fe9497a-4ea2-4c6e-830a-ecb48bc710c3.png)

**如何复现？**
1.在on_shell_command的指令中带图片

**期望的结果**
不报错（state[SHELL_ARGV]这个list中过滤掉图片？）

**环境信息：**

 - OS: Ubuntu 18.04 x86_64
 - Python Version: 3.10.6
 - Nonebot Version: v2.0.0rc4

**协议端信息：**

 - 协议端: gocqhttp (nonebot-plugin-gocqhttp)
 - 协议端版本: gocqhttp v1.0.1

**补充信息**
是在使用nonebot-plugin-novelai这个插件时，在qq端发送 以图生图命令 'draw prompts [图片]'时触发报错

**Comment by yanyongyu** [comment]
error format的时候遇到问题，得覆盖一下这块逻辑
