### ISSUE TITLE
Plugin: 运行代码

### ISSUE THREAD

**Issue by Yincmewy** [nonebot/nonebot2#1941]
**插件名称：**

运行代码

**插件功能：**

基于runoob.com的在线代码运行插件

**PyPI 项目名：**

nonebot-plugin-coderun

**插件 import 包名：**

nonebot-plugin-coderun

**插件项目仓库/主页链接：**

https://github.com/Yincmewy/nonebot_plugin_coderun

**标签：**

[]

**Comment by Yincmewy** [comment]
> 

1

**Comment by he0119** [comment]
推荐利用 poetry 或者 pdm 来管理依赖甚至发布至 pypi。

**Comment by NCBM** [comment]
不推荐无实物表演（

**Comment by Yincmewy** [comment]
> Contributor

1

**Comment by Yincmewy** [comment]
草

**Comment by he0119** [comment]
<https://github.com/Yincmewy/nonebot_plugin_runcode/blob/57775944fa62784b2eb538085a8a97d227b31f4b/pyproject.toml#L12>

为什么依赖的 nb1？

**Comment by Yincmewy** [comment]
> https://github.com/Yincmewy/nonebot_plugin_runcode/blob/57775944fa62784b2eb538085a8a97d227b31f4b/pyproject.toml#L12
> 
> 为什么依赖的 nb1？

写错了草

**Comment by yanyongyu** [comment]
你pypi的包怎么和你仓库的文件夹名字不一样啊

**Comment by Yincmewy** [comment]
> 你pypi的包怎么和你仓库的文件夹名字不一样啊

没注意，改了

**Comment by yanyongyu** [comment]
改了个寂默？？你的文件夹是下划线，pypi上的导入是短横杠？

**Comment by Yincmewy** [comment]
> 改了个寂默？？你的文件夹是下划线，pypi上的导入是短横杠？

这次真改了꒦ິ^꒦ິ
