### ISSUE TITLE
Plugin: 为美好群聊献上爆炎

### ISSUE THREAD

**Issue by youlanan** [nonebot/nonebot2#1952]
**插件名称：**

为美好群聊献上爆炎

**插件功能：**

现在，你的群友可以触发失传已久的爆裂魔法了

**PyPI 项目名：**

nonebot-plugin-megumin

**插件 import 包名：**

nonebot_plugin_megumin

**插件项目仓库/主页链接：**

https://github.com/youlanan/nonebot_plugin_megumin

**标签：**

[{"label":"小游戏","color":"#f9971c"},{"label":"Explosion","color":"#f94b1c"}]

**Comment by youlanan** [comment]
qaq




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月28日(星期五) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/nonebot2] Plugin: 为美好的群聊献上爆炎 (Issue #1952)





 
📃 商店发布检查结果
  
Plugin: 为美好群聊献上爆炎
  
⚠️ 在发布检查过程中，我们发现以下问题：
 
⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-megumin 的信息如下：     name         : nonebot-plugin-megumin       version      : 0.0.2                        description  : 让你的群友释放爆裂魔法吧！ 插件 nonebot-plugin-megumin 依赖的插件如下：      插件 nonebot_plugin_megumin 加载出错：     Traceback (most recent call last):       File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 1, in <module&gt;         from nonebot import init, load_plugin, require     ModuleNotFoundError: No module named 'nonebot'
 详情
✅ 标签: 小游戏-#f9971c, Explosion-#f94b1c。

✅ 项目 主页 返回状态码 200。

✅ 包 nonebot-plugin-megumin 已发布至 PyPI。
 
 
💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
 
💪 Powered by NoneFlow

**Comment by Well2333** [comment]
1. 插件项目仓库/主页链接 请填写你的项目仓库，而不是你的github主页
2. 在 [pypi](https://pypi.org/project/nonebot-plugin-megumin) 上目前最新版为 0.0.3，install_requires 中未填写任何依赖，请考虑使用poetry或pdm进行项目管理与发布。
