### ISSUE TITLE
Plugin: 链接解析

### ISSUE THREAD

**Issue by mute23-code** [nonebot/nonebot2#1959]
### 插件名称

链接解析

### 插件描述

检测链接并发送网站简介及预览图

### PyPI 项目名

nonebot-plugin-og

### 插件 import 包名

nonebot_plugin_og

### 插件项目仓库/主页链接

https://github.com/mute23-code/nonebot_plugin_og

### 标签

[]

**Comment by mute23-code** [comment]
1

**Comment by mute23-code** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot_plugin_og
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot_plugin_og 的信息如下：
>       name         : nonebot-plugin-og 
>        version      : 0.2.0             
>        description  : 检测链接并发送网站简介及预览图   
>       
>       dependencies
>        - httpx >=0.24.0,<0.25.0
>        - pyquery >=2.0.0,<3.0.0
>   插件 nonebot_plugin_og 依赖的插件如下：
>       
>   插件 nonebot_plugin_og 加载出错：
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 1, in <module>
>           from nonebot import init, load_plugin, require
>       ModuleNotFoundError: No module named 'nonebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

well

**Comment by yanyongyu** [comment]
还能过测试吗（

**Comment by Well2333** [comment]
温馨提示，这个插件**还没有**通过自动审核，如果需要继续发布到插件商店仍需要进一步的修改，如果放弃发布可以关闭此issue

**Comment by mute23-code** [comment]
刚回家，马上改

**Comment by mute23-code** [comment]
应该没问题了（？
