### ISSUE TITLE
Feature: `MessageTemplate` 应像 `str.format` 那样支持 `{{` 与 `}}` 转义

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#1960]
### 希望能解决的问题

目前在使用 MessageTemplate.format_map() 时，如果像用 `str.format()` 那样使用 `{{` 或 `}}` 来转义大括号时会报错或无法正确转义

### 描述所需要的功能

希望 `MessageTemplate` 能够支持 `{{` 与 `}}` 的转义

**Comment by yanyongyu** [comment]
你的报错是什么，我这尝试没有问题啊。。

**Comment by lgc2333** [comment]
invalid
