### ISSUE TITLE
Plugin: 水印大师

### ISSUE THREAD

**Issue by X-Skirt-X** [nonebot/nonebot2#1962]
**插件名称：**

水印大师

**插件功能：**

给bot发的图片增加水印,支持随机水印添加

**PyPI 项目名：**

nonebot-plugin-watermarker

**插件 import 包名：**

nonebot_plugin_watermarker

**插件项目仓库/主页链接：**

https://github.com/X-Skirt-X/nonebot-plugin-watermarker

**标签：**

[{"label":"t:水印","color":"#52eae7"},{"label":"t:图片水印","color":"#ef258f"}]

**Comment by X-Skirt-X** [comment]
updata requirement

**Comment by X-Skirt-X** [comment]
> # 📃 商店发布检查结果
> > Plugin: 水印大师
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-watermarker 的信息如下：
>       name         : nonebot-plugin-watermarker 
>        version      : 0.1.0                      
>        description  : 为nonebot机器人发送的图片加上水印       
>       
>       dependencies
>        - nb-cli *
>   插件 nonebot-plugin-watermarker 依赖的插件如下：
>       
>   插件 nonebot_plugin_watermarker 加载出错：
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 1, in <module>
>           from nonebot import init, load_plugin, require
>       ModuleNotFoundError: No module named 'nonebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

# ?
任意内容.jpg(

**Comment by X-Skirt-X** [comment]
> # 📃 商店发布检查结果
> > Plugin: 水印大师
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-watermarker 的信息如下：
>       name         : nonebot-plugin-watermarker 
>        version      : 0.1.1                      
>        description  : 为nonebot机器人发送的图片加上水印       
>       
>       dependencies
>        - nb-cli *
>        - nonebot2 *
>   插件 nonebot-plugin-watermarker 依赖的插件如下：
>       
>   插件 nonebot_plugin_watermarker 加载出错：
>       05-01 14:05:05 [SUCCESS] nonebot | NoneBot is initializing...
>       05-01 14:05:05 [INFO] nonebot | Current Env: prod
>       05-01 14:05:05 [ERROR] nonebot | Failed to import "nonebot_plugin_watermarker"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_watermarker")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
>       ModuleNotFoundError: No module named 'nonebot_plugin_watermarker'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)


# !
我准备好了!我准备好了!

**Comment by MingxuanGame** [comment]
你import包名写错了()

**Comment by X-Skirt-X** [comment]
> 你import包名写错了()

是不能下滑线吗?我检查不出来()

**Comment by Well2333** [comment]
> 项目缺少nonebot2 依赖，请在依赖文件中添加

并不是这个问题，依赖中已包含nonebot2，可参考 [此文件](https://files.pythonhosted.org/packages/e4/16/433cd51c194324a7dbf3a59b26dd81b761310e2ebce2082cb094f503d792/nonebot-plugin-watermarker-0.1.2.tar.gz)

**Comment by X-Skirt-X** [comment]
> > 是不能下滑线吗?我检查不出来()
> 
> 根据在 GitHub 中的文件夹名称和 pypi 发布的版本，import 包名为 `nonebot-plugin-watermarker`

明白了，谢谢，我会把文件夹名改为nonebot_plugin_watermarker，因为Python里面包名好像不能-。
我打算写的不一样还是根据以前发布插件的记忆写的()

**Comment by X-Skirt-X** [comment]
> 项目缺少nonebot2 依赖，请在依赖文件中添加

非常感谢指出问题

**Comment by Well2333** [comment]
> > 项目缺少nonebot2 依赖，请在依赖文件中添加
> 
> 非常感谢指出问题

不是这个问题啊，问题是你的包名写错了，import 的包名应该是 nonebot-plugin-watermarker

**Comment by X-Skirt-X** [comment]
> > > > 是不能下滑线吗?我检查不出来()
> > > 
> > > 
> > > 根据在 GitHub 中的文件夹名称和 pypi 发布的版本，import 包名为 `nonebot-plugin-watermarker`
> > 
> > 
> > 明白了，谢谢，我会把文件夹名改为nonebot_plugin_watermarker，因为Python里面包名好像不能-。 我打算写的不一样还是根据以前发布插件的记忆写的()
> 
> 程序中的分字符一般都用的是 `_` 而不是 `-`，因为 `-` 一般是作为减号，但在 json 或 html 等非图灵完备的语言中就可以做分字使用了。
> 
> python 在导入包的时候可以使用 import 语句，也可以使用 importlib 来导入，这种包名带 `-` 的只能通过 importlib 来导入，因此这样写其实没有问题但十分不推荐就是了。

这样啊,谢谢大佬
