### ISSUE TITLE
Plugin: 星铁活动日历

### ISSUE THREAD

**Issue by nicklly** [nonebot/nonebot2#1963]
**插件名称：**

星铁活动日历

**插件功能：**

查看《崩坏：星穹铁道》活动日历

**PyPI 项目名：**

nonebot-plugin-star-rail-calendar

**插件 import 包名：**

nonebot_plugin_star_rail_calendar

**插件项目仓库/主页链接：**

https://github.com/nicklly/nonebot_plugin_star_rail_calendar

**标签：**

[]

**Comment by nicklly** [comment]
> # 📃 商店发布检查结果
> > Plugin: 星铁活动日历
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-star-rail-calendar 的信息如下：
>       name         : nonebot-plugin-star-rail-calendar 
>        version      : 0.0.1                             
>        description  : 查看《崩坏：星穹铁道》官方活动                   
>       
>       dependencies
>        - nonebot-adapter-onebot >=2.0.0b1
>        - nonebot2 >=2.0.0b1
>   插件 nonebot-plugin-star-rail-calendar 依赖的插件如下：
>       
>   插件 nonebot_plugin_star_rail_calendar 加载出错：
>       05-01 14:51:36 [SUCCESS] nonebot | NoneBot is initializing...
>       05-01 14:51:36 [INFO] nonebot | Current Env: prod
>       05-01 14:51:36 [ERROR] nonebot | Failed to import "nonebot_plugin_star_rail_calendar"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_star_rail_calendar")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
>       ModuleNotFoundError: No module named 'nonebot_plugin_star_rail_calendar'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

fix

**Comment by BigOrangeQWQ** [comment]
检查一下依赖，还有pypi发布的包名能否import

**Comment by nicklly** [comment]
> 检查一下依赖，还有pypi发布的包名能否import

依赖并没有问题

**Comment by MingxuanGame** [comment]
import 包名错了，应该是 `nonebot-plugin-star-rail-calendar`

**Comment by nicklly** [comment]
> import 包名错了，应该是 `nonebot-plugin-star-rail-calendar`

确实(不过以前包名不是下划线吗？难道改了？) 总有人不看就说是依赖的问题 简直了)

**Comment by Well2333** [comment]
> > import 包名错了，应该是 `nonebot-plugin-star-rail-calendar`
> 
> 确实(不过以前包名不是下划线吗？难道改了？) 总有人不看就说是依赖的问题 简直了)

你管 `nonebot-plugin-star-rail-calendar` 叫下划线？

你发到pypi上的叫什么，你就该import什么

**Comment by BigOrangeQWQ** [comment]
> > import 包名错了，应该是 `nonebot-plugin-star-rail-calendar`
> 
> 确实(不过以前包名不是下划线吗？难道改了？) 总有人不看就说是依赖的问题 简直了)

你的依赖只有
- nonebot2
- nonebot-adapter-onebot
该包有以下import及require
- apscheduler
- httpx
- htmlrender

为什么你觉得我不看你的源码就comment呢？

**Comment by Well2333** [comment]
然后，关于依赖问题

https://github.com/nicklly/nonebot_plugin_star_rail_calendar/blob/main/nonebot-plugin-star-rail-calendar/__init__.py#L4
https://github.com/nicklly/nonebot_plugin_star_rail_calendar/blob/main/nonebot-plugin-star-rail-calendar/browser.py#L15
https://github.com/nicklly/nonebot_plugin_star_rail_calendar/blob/main/nonebot-plugin-star-rail-calendar/browser.py#L15

但是，你的setup.py里面只有

```
install_requires=[
        "nonebot2 >= 2.0.0b1",
        "nonebot-adapter-onebot >= 2.0.0b1",
    ]
```

https://github.com/nicklly/nonebot_plugin_star_rail_calendar/blob/main/setup.py#L19

你觉得这个对吗？不去检查一下就张口说 `总有人不看就说是依赖的问题` ?
