### ISSUE TITLE
Feature: on_calling_api的钩子函数能否支持获取调用该平台api的事件响应器?

### ISSUE THREAD

**Issue by X-Skirt-X** [nonebot/nonebot2#1966]
### 希望能解决的问题

想要使用`on_calling_api`钩子阻断调用api的同时知道是什么插件在调用api,从而决定放行还是阻断

#### 需要的功能
为`bot.on_calling_api`钩子添加获取获取matcher的支持
或者类似的支持(改这个钩子可能会让很多适配器不适配改动后的Bot基类?)
#### 可能的解决方案
为钩子函数添加matcher的注入
但是我看了相关代码,发现bot和mathcer似乎是俩个独立的存在,在Bot内不能直接获得matcher
https://github.com/nonebot/nonebot2/blob/e98d28f3b4fdda2504ecc07318563ce202464b96/nonebot/internal/adapter/bot.py#L62-L94

**Comment by yanyongyu** [comment]
不能，调用api行为与事件响应器无关，仅与平台bot有关

**Comment by A-kirami** [comment]
调用平台api并不需要事件响应器，两者没有关联

**Comment by X-Skirt-X** [comment]
> 不能，调用api行为与事件响应器无关，仅与平台bot有关

如果想在`on_calling_api`获取调用平台bot的api的插件的相关信息要怎么做?

**Comment by yanyongyu** [comment]
如果是在事件处理流程中调用的api，可以通过current_matcher contextvar获取到上下文中的响应器

**Comment by X-Skirt-X** [comment]
> 如果是在事件处理流程中调用的api，可以通过current_matcher contextvar获取到上下文中的响应器

能否指个路到文档或者源码,我不太理解current_matcher contextvar这些的用法(文档里也没搜索到(

**Comment by synodriver** [comment]
这个属于nonebot的内部实现细节=(

**Comment by yanyongyu** [comment]
如果还有问题的话欢迎到discussion讨论
