### ISSUE TITLE
Bug: run_sync忽略了上下文变量

### ISSUE THREAD

**Issue by synodriver** [nonebot/nonebot2#1967]
### 操作系统

Windows

### Python 版本

3.11.0

### NoneBot 版本

2.0.0rc4

### 适配器

-

### 协议端

-

### 描述问题

[run_sync](https://github.com/nonebot/nonebot2/blob/e98d28f3b4fdda2504ecc07318563ce202464b96/nonebot/utils.py#L114)忽略了上下文变量，可能会导致异常，比如https://github.com/nonebot/nonebot2/issues/1966

### 复现步骤

-

### 期望的结果

使用```copy_context```然后```ctx.run```进executor

### 截图或日志

-

**Comment by yanyongyu** [comment]
索性直接换anyio解决所有问题 一步到位（
