### ISSUE TITLE
Plugin: 星穹铁道活动日历

### ISSUE THREAD

**Issue by nicklly** [nonebot/nonebot2#1969]
**插件名称：**

星穹铁道活动日历

**插件功能：**

查看《崩坏：星穹铁道》官方活动

**PyPI 项目名：**

nonebot-plugin-starrail-calendar

**插件 import 包名：**

nonebot_plugin_starrail_calendar

**插件项目仓库/主页链接：**

https://github.com/nicklly/nonebot_plugin_StarRail_calendar

**标签：**

[]

**Comment by he0119** [comment]
你没有把代码打包进去啊，包里面啥都没有。

**Comment by nicklly** [comment]
> 你没有把代码打包进去啊，包里面啥都没有。

确实（感觉脑子一片空白）

**Comment by he0119** [comment]
要不试试去看看 poetry 和 pdm 的用法？用那些工具来管理依赖和发布，别用 setup.py 了。

**Comment by Well2333** [comment]
来看 poetry 教程谢谢喵
http://blog.well404.top/2022/08/17/%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83/
