### ISSUE TITLE
Plugin: CSGO开箱模拟器

### ISSUE THREAD

**Issue by roiiiu** [nonebot/nonebot2#1985]
**插件名称：**

CSGO开箱模拟器

**插件功能：**

内置所有最新武器箱，可多箱连开

**PyPI 项目名：**

nonebot-plugin-csgo-case-simulator

**插件 import 包名：**

nonebot-plugin-csgo-case-simulator

**插件项目仓库/主页链接：**

https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator

**标签：**

[{"label":"CSGO","color":"#47aeff"},{"label":"开箱模拟器","color":"#ff4781"}]

**Comment by roiiiu** [comment]
retry

**Comment by CMHopeSunshine** [comment]
推荐使用`httpx`或`aiohttp`等异步网络请求库，而非同步的`requests`，同步请求会出现网络io阻塞
