### ISSUE TITLE
没有找到加好友和删好友的api文档

### ISSUE THREAD

**Issue by waner1998** [nonebot/nonebot2#1991]
### 描述问题或主题

加好友和删好友的api文档

### 需做出的修改

增加加好友和删好友的api文档

**Comment by forchannot** [comment]
这和nb有什么关系

**Comment by CMHopeSunshine** [comment]
协议端的具体功能请去看协议端文档，如果你用的是gocq那就去看gocq的文档

**Comment by NumberSir** [comment]
猜你想找：gocq文档

**Comment by shikukuya** [comment]
6

**Comment by FYWinds** [comment]
请查阅你所使用的适配器的文档 如[onebor](https://github.com/nonebot/adapter-onebot/)
