### ISSUE TITLE
Plugin: 签到

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#2013]
### 插件名称

签到

### 插件描述

从 hoshino 搬过来的 pcr 签到, 略作修改。

### PyPI 项目名

nonebot-plugin-hoshino-sign

### 插件 import 包名

nonebot_plugin_hoshino_sign

### 插件项目仓库/主页链接

https://github.com/zhulinyv/nonebot_plugin_hoshino_sign

### 标签

[{"label":"PCR","color":"#ff0000"},{"label":"签到","color":"#008000"}]

**Comment by zhulinyv** [comment]
2.0.1

**Comment by zhulinyv** [comment]
2.0.2 💦

**Comment by zhulinyv** [comment]
频道补丁也需要先 require() 嘛
![6VSY3SF)S4JB6ZBZV_I}SLK](https://github.com/nonebot/nonebot2/assets/66541860/eebe294a-0a48-4a00-9afc-68c4355204cd)

**Comment by he0119** [comment]
是的，所有 nb 插件都需要 require。

**Comment by zhulinyv** [comment]
![P92E$8EL7I9BM3O%QAB8M12](https://github.com/nonebot/nonebot2/assets/66541860/1ee99861-a0cb-480d-864b-0a4c372436de)

**Comment by zhulinyv** [comment]
> # 📃 商店发布检查结果
> > Plugin: 签到
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-hoshino-sign 的信息如下：
>       name         : nonebot-plugin-hoshino-sign  
>        version      : 2.0.4                        
>        description  : 一个从 hoshino 搬过来的 nonebot2 插件 
>       
>       dependencies
>        - httpx *
>        - nonebot-adapter-onebot *
>        - nonebot_plugin_guild_patch *
>        - nonebot2 *
>        - pillow *
>        - pytz *
>   插件 nonebot-plugin-hoshino-sign 依赖的插件如下：
>       nonebot_plugin_guild_patch
>   插件 nonebot_plugin_hoshino_sign 加载出错：
>       05-13 15:13:05 [SUCCESS] nonebot | NoneBot is initializing...
>       05-13 15:13:05 [INFO] nonebot | Current Env: prod
>       05-13 15:13:05 [ERROR] nonebot | Failed to import "nonebot_plugin_hoshino_sign"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_hoshino_sign")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
>       ModuleNotFoundError: No module named 'nonebot_plugin_hoshino_sign'
>       05-13 15:13:05 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
> ```
> 
> 详情
> ```
> * ✅ 标签: PCR-#ff0000, 签到-#008000。* ✅ 项目 [主页](https://github.com/zhulinyv/NJS/tree/Bot/src/plugins/nonebot_plugin_hoshino_sign) 返回状态码 200。* ✅ 包 [nonebot-plugin-hoshino-sign](https://pypi.org/project/nonebot-plugin-hoshino-sign/) 已发布至 PyPI。
> ```
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

rename

**Comment by zhulinyv** [comment]
![X90S4O%){GY3KD}ISP}{)RQ](https://github.com/nonebot/nonebot2/assets/66541860/3bc6eab5-38af-4b7c-a8a4-08bbcb8e1b94)

**Comment by zhulinyv** [comment]
.

**Comment by zhulinyv** [comment]
![TY~{T MDC(L3UT_)TRTDWKE](https://github.com/nonebot/nonebot2/assets/66541860/66850483-9a9e-44bc-8ae4-552b99c6e550)
不会了（
依赖都加了，仓库里文件夹的名字也和 import 包名一样...
看了个[类似的 issue](https://github.com/nonebot/nonebot2/issues/1962#issuecomment-1529833406)，是要把 _ 改成 - 嘛？

**Comment by zhulinyv** [comment]
早上好吖
