### ISSUE TITLE
.got秒回可能导致的封号

### ISSUE THREAD

**Issue by waner1998** [nonebot/nonebot2#2015]
### 描述问题或主题

@matcher.got("key", prompt="请输入...")这个命令下机器人对用户的消息是秒回的，自己做的限速管理也不奏效，想请问下如何对这种消息的回复速度做限制？即不要描绘

### 需做出的修改

.got的回复速度做限制

**Comment by eya46** [comment]
.handle()里面等待一会

**Comment by waner1998** [comment]
> .handle()里面等待一会

试了不管用

**Comment by yanyongyu** [comment]
你可以使用api hook实现

**Comment by waner1998** [comment]
> .got

能麻烦详细说一下怎么用吗，开发文档没看见详细内容，麻烦了

**Comment by StarHeartHunt** [comment]
> > .got
> 
> 能麻烦详细说一下怎么用吗，开发文档没看见详细内容，麻烦了

https://v2.nonebot.dev/docs/advanced/runtime-hook

**Comment by waner1998** [comment]
> > > .got
> > 
> > 
> > 能麻烦详细说一下怎么用吗，开发文档没看见详细内容，麻烦了
> 
> https://v2.nonebot.dev/docs/advanced/runtime-hook

没看懂这个，方便丢个demo给我嘛

**Comment by yanyongyu** [comment]
建议自己认真看文档或者参考其他人的写法，有问题请去论坛
