### ISSUE TITLE
Plugin: 《女神异闻录5》预告信生成器

### ISSUE THREAD

**Issue by xi-yue-233** [nonebot/nonebot2#2016]
### 插件名称

《女神异闻录5》预告信生成器

### 插件描述

可以生成仿《女神异闻录5》中心之怪盗团向罪人宣战的预告信

### PyPI 项目名

nonebot-plugin-p5generator

### 插件 import 包名

nonebot_plugin_p5generator

### 插件项目仓库/主页链接

https://github.com/xi-yue-233/nonebot-plugin-p5generator

### 标签

[]

**Comment by yanyongyu** [comment]
插件加载报错，请修改相关代码后更新发布

**Comment by xi-yue-233** [comment]
需要下载库中资源才能正常运行的，资源放在data/p5generator文件夹下
为了能正常加载我修改了一下mkdir以便通过加载
https://github.com/xi-yue-233/nonebot-plugin-p5generator

**Comment by yanyongyu** [comment]
目前商店发布要求插件需要在未配置情况下正常加载，你可以通过logger来提醒用户进行相应配置
