### ISSUE TITLE
Question: 安装apscheduler失败

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#203]
环境CentOS 8.0 
nonebot版本 2.0.0a7
由于a7版本没有文档，参考的是 [a8文档](https://github.com/nonebot/nonebot2/blob/3460d445b83d1f8c7653f4316a374fb5935a3f25/archive/2.0.0a8.post2/advanced/scheduler.md#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6)

**尝试使用 `nb plugin install nonebot_plugin_apscheduler` 安装时报错如下：**
![image](https://user-images.githubusercontent.com/36919867/107143515-79769400-6970-11eb-8849-37ba810d85e9.png)
**尝试使用 `poetry add nonebot-plugin-apscheduler`安装时 报错如下：**
![image](https://user-images.githubusercontent.com/36919867/107143532-957a3580-6970-11eb-8114-10a6cb26f557.png)

系统环境信息：`pip` 和 `python3` 命令均指向3.6版本(CentOS8貌似没有python2.x，输入`python`会提示`command not found`)，不符合nonebot的要求(>=3.7)，因此,需要用到 "pip" 或 "python" 的安装命令，均为 `python3.8 xxx` 或 `python3.8 -m pip install xxx`  ， 或许是`python`和`pip`的软链接问题，但是在查教程(重装系统)之前，还是先保留一下环境 请教一下大佬，因为之前每次遇到这种问题都是重装系统换系统()

**Comment by yanyongyu** [comment]
这种情况建议使用虚拟环境进行安装，例如poetry自带的env，使用poetry shell进入虚拟环境

**Comment by railannad** [comment]
直接输入poetry shell：
![image](https://user-images.githubusercontent.com/36919867/107144888-176e5c80-6979-11eb-9605-d1199fd35c4c.png)
参考[官方？教程](https://docs.python.org/zh-cn/3.8/tutorial/venv.html)使用venv进入虚拟环境： `pip`和`python` 已指向3.8版本

`poetry add nonebot-plugin-apscheduler`
![image](https://user-images.githubusercontent.com/36919867/107144813-98792400-6978-11eb-90fe-b13d6bcf353e.png)
`nb plugin install nonebot_plugin_apscheduler`
![image](https://user-images.githubusercontent.com/36919867/107144939-5e5c5200-6979-11eb-876a-b821c629caf1.png)

**Comment by mnixry** [comment]
你用虚拟环境的前提是得有一个用poetry的项目(即当前工作目录下有pyproject.toml)
很疑惑你使用这个插件的目的是什么

**Comment by railannad** [comment]
> 你用虚拟环境的前提是得有一个用poetry的项目(即当前工作目录下有pyproject.toml)
> 很疑惑你使用这个插件的目的是什么

安装apscheduler当然是为了写定时任务，在Windows写好了准备拉到Linux用，发现插件装不了。。。
更新了一下pip发现能用nb安装了，打扰了
