### ISSUE TITLE
Plugin: 股票看盘助手

### ISSUE THREAD

**Issue by Calanosay** [nonebot/nonebot2#2031]
### 插件名称

股票看盘助手

### 插件描述

股票波动超过设定值提醒，省去一直盯盘的烦恼

### PyPI 项目名

nonebot-plugin-stockhelper

### 插件 import 包名

nonebot_plugin_stockhelper

### 插件项目仓库/主页链接

https://github.com/Calanosay/nonebot_plugin_stockhelper

### 标签

[{"label":"股票","color":"#ea5252"}]

**Comment by Well2333** [comment]
regex 警察龟速出警，请停止滥用正则表达，这将严重影响bot整体的运行速度

**Comment by Calanosay** [comment]
> regex 警察龟速出警，请停止滥用正则表达，这将严重影响bot整体的运行速度

已修改

**Comment by lgc2333** [comment]
https://github.com/Calanosay/nonebot_plugin_stockhelper/blob/origin/nonebot_plugin_stockhelper/__init__.py#L44-45

```
gpjk = on_command('监控', alias={'关注', 'jk'}, priority=10, rule=to_me())
show = on_regex('看股票', alias={'kgp'}, priority=10, rule=to_me())
```
