### ISSUE TITLE
Plugin: AI聊天(腾讯云)

### ISSUE THREAD

**Issue by Calanosay** [nonebot/nonebot2#2035]
### 插件名称

AI聊天(腾讯云)

### 插件描述

基于腾讯云接口的的ai聊天功能

### PyPI 项目名

nonebot-plugin-aitx

### 插件 import 包名

nonebot-plugin-aitx

### 插件项目仓库/主页链接

https://github.com/Calanosay/nonebot-plugin-aitx

### 标签

[{"label":"AI","color":"#ea5252"}]

**Comment by Calanosay** [comment]
> 

....

**Comment by Calanosay** [comment]
...

**Comment by Calanosay** [comment]
> # 📃 商店发布检查结果
> > Plugin: AI聊天(腾讯云)
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-aitx 的信息如下：
>       name         : nonebot-plugin-aitx 
>        version      : 0.1.0               
>        description  : 基于腾讯云接口的ai聊天
>   插件 nonebot-plugin-aitx 依赖的插件如下：
>       
>   插件 nonebot-plugin-aitx 加载出错：
>       05-20 01:50:20 [SUCCESS] nonebot | NoneBot is initializing...
>       05-20 01:50:20 [INFO] nonebot | Current Env: prod
>       05-20 01:50:20 [ERROR] nonebot | Failed to import "nonebot-plugin-aitx"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot-plugin-aitx")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot-plugin-aitx/__init__.py", line 2, in <module>
>           from tencentcloud.common import credential
>       ModuleNotFoundError: No module named 'tencentcloud'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

233

**Comment by Calanosay** [comment]
233

**Comment by yanyongyu** [comment]
请参考插件配置编写方法 https://v2.nonebot.dev/docs/next/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE 修改你的插件，否则别人安装你的插件也无法使用

**Comment by Calanosay** [comment]
> 请参考插件配置编写方法 https://v2.nonebot.dev/docs/next/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE 修改你的插件，否则别人安装你的插件也无法使用

好了

**Comment by Calanosay** [comment]
233

**Comment by NumberSir** [comment]
要不你先加一下开发者群

**Comment by eya46** [comment]
测试评论

**Comment by Calanosay** [comment]
> 要不你先加一下开发者群

什么群

**Comment by MingxuanGame** [comment]
> 什么群
481878114

**Comment by yanyongyu** [comment]
@Calanosay 你的插件配置仍然是错误的

**Comment by Calanosay** [comment]
close
