### ISSUE TITLE
Plugin: Github仓库卡片

### ISSUE THREAD

**Issue by ElainaFanBoy** [nonebot/nonebot2#2041]
### 插件名称

 Github仓库卡片

### 插件描述

检测GitHub仓库链接并自动发送卡片信息

### PyPI 项目名

nonebot-plugin-githubcard

### 插件 import 包名

nonebot_plugin_githubcard

### 插件项目仓库/主页链接

https://github.com/ElainaFanBoy/nonebot_plugin_githubcard

### 标签

[{"label":"t: Github","color":"#171a21"},{"label":"a:onebot","color":"#000000"}]

**Comment by ElainaFanBoy** [comment]
0.0?

**Comment by ElainaFanBoy** [comment]
> # 📃 商店发布检查结果
> 
> > Plugin: Github仓库卡片
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> <pre><code><li>⚠️ 插件加载测试未通过。<details><summary>测试输出</summary>插件 nonebot-plugin-githubcard 的信息如下：
>     name         : nonebot-plugin-githubcard              
>      version      : 0.1.0                                  
>      description  : 检测GitHub仓库链接并自动发送卡片信息（适用于Nonebot2 V11） 
>     
>     dependencies
>      - nonebot-adapter-onebot &gt;=2.1.1,&lt;3.0.0
>      - nonebot2 &gt;=2.0.0rc1,&lt;3.0.0
> 插件 nonebot-plugin-githubcard 依赖的插件如下：
>     
> 插件 nonebot-plugin-githubcard 加载出错：
>     05-22 00:29:27 [SUCCESS] nonebot | NoneBot is initializing...
>     05-22 00:29:27 [INFO] nonebot | Current Env: prod
>     05-22 00:29:27 [ERROR] nonebot | Failed to import &quot;nonebot-plugin-githubcard&quot;
>     Traceback (most recent call last):
>       File &quot;/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py&quot;, line 4, in &lt;module&gt;
>         valid = load_plugin(&quot;nonebot-plugin-githubcard&quot;)
>       File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py&quot;, line 37, in load_plugin
>         return manager.load_plugin(module_path)
>     &gt; File &quot;/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 141, in load_plugin
>         module = importlib.import_module(name)
>       File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import
>       File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load
>       File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1004, in _find_and_load_unlocked
>     ModuleNotFoundError: No module named &#x27;nonebot-plugin-githubcard&#x27;</details></li></code></pre>
> <details><summary>详情</summary><pre><code><li>✅ 标签: t: Github-#171a21。</li><li>✅ 项目 <a href="https://github.com/ElainaFanBoy/nonebot_plugin_githubcard">主页</a> 返回状态码 200。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-githubcard/">nonebot-plugin-githubcard</a> 已发布至 PyPI。</li></code></pre></details>
> 
> ---
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
> 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> 
> 

0.0?

**Comment by eya46** [comment]
插件 import 包名
nonebot_plugin_githubcard

**Comment by ElainaFanBoy** [comment]
> 插件 import 包名
> nonebot_plugin_githubcard

谢谢

**Comment by ElainaFanBoy** [comment]
> # 📃 商店发布检查结果
> > Plugin: Github仓库卡片
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-githubcard 的信息如下：
>       name         : nonebot-plugin-githubcard            
>        version      : 0.1.1                                
>        description  : 检测GitHub仓库链接并自动发送卡片信息（适用于Onebot V11） 
>       
>       dependencies
>        - nonebot-adapter-onebot >=2.1.1,<3.0.0
>        - nonebot2 >=2.0.0rc1,<3.0.0
>   插件 nonebot-plugin-githubcard 依赖的插件如下：
>       
>   插件 nonebot_plugin_githubcard 加载出错：
>       05-22 00:57:36 [SUCCESS] nonebot | NoneBot is initializing...
>       05-22 00:57:36 [INFO] nonebot | Current Env: prod
>       05-22 00:57:37 [ERROR] nonebot | Failed to import "nonebot_plugin_githubcard"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_githubcard")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_githubcard/__init__.py", line 6, in <module>
>           from .data_source import get_github_reposity_information
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_githubcard/data_source.py", line 1, in <module>
>           import aiohttp
>       ModuleNotFoundError: No module named 'aiohttp'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

*^____^*

**Comment by yanyongyu** [comment]
github api有调用次数限制，建议加个token配置项，另外不要使用cq码，请使用MessageSegment

**Comment by ElainaFanBoy** [comment]
> github api有调用次数限制，建议加个token配置项，另外不要使用cq码，请使用MessageSegment

已修改

**Comment by ElainaFanBoy** [comment]
> #  商店发布检查结果
> > Plugin: Github仓库卡片
> 
> **white_check_mark 所有测试通过，一切准备就绪！**
> 
> 详情
> bulb 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 bulb 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> recycle 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://github.com/nonebot/noneflow)

0v0?

**Comment by yanyongyu** [comment]
选项需要做成optional的，如果是required应该明确告知用户并阻止功能添加

**Comment by ElainaFanBoy** [comment]
> # 📃 商店发布检查结果
> > Plugin: Github仓库卡片
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-githubcard 的信息如下：
>       name         : nonebot-plugin-githubcard            
>        version      : 0.1.3                                
>        description  : 检测GitHub仓库链接并自动发送卡片信息（适用于Onebot V11） 
>       
>       dependencies
>        - aiohttp >=3.7.4,<4.0.0
>        - nonebot-adapter-onebot >=2.1.1,<3.0.0
>        - nonebot2 >=2.0.0rc1,<3.0.0
>   插件 nonebot-plugin-githubcard 依赖的插件如下：
>       
>   插件 nonebot_plugin_githubcard 加载出错：
>       05-22 10:21:18 [SUCCESS] nonebot | NoneBot is initializing...
>       05-22 10:21:18 [INFO] nonebot | Current Env: prod
>       05-22 10:21:18 [ERROR] nonebot | Failed to import "nonebot_plugin_githubcard"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_githubcard")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_githubcard/__init__.py", line 4, in <module>
>           from .config import Config
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_githubcard/config.py", line 9, in <module>
>           githubcard_config = Config(**global_config.dict())
>         File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
>           raise validation_error
>       pydantic.error_wrappers.ValidationError: 1 validation error for Config
>       github_token
>         field required (type=value_error.missing)
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

0o0!
