### ISSUE TITLE
Plugin: cuber

### ISSUE THREAD

**Issue by initialencounter** [nonebot/nonebot2#2045]
### 插件名称

cuber

### 插件描述

魔方插件

### PyPI 项目名

nonebot-plugin-cube

### 插件 import 包名

nonebot_plugin_cube

### 插件项目仓库/主页链接

https://github.com/initialencounter/nonebot-plugin-cube

### 标签

[{"label":"魔方","color":"#ea5252"},{"label":"sqlite3","color":"#c2ea52"}]

**Comment by A-kirami** [comment]
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
> 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

不要重复开相同的插件发布issue

**Comment by initialencounter** [comment]
好的我会注意

**Comment by initialencounter** [comment]
测试

**Comment by initialencounter** [comment]
测试
