### ISSUE TITLE
Plugin: 游戏王小世界现象小助手

### ISSUE THREAD

**Issue by Passerby-D** [nonebot/nonebot2#2050]
### 插件名称

游戏王小世界现象小助手

### 插件描述

游戏王小世界现象小助手

### PyPI 项目名

nonebot-plugin-small-world

### 插件 import 包名

nonebot

### 插件项目仓库/主页链接

https://github.com/Passerby-D/nonebot_plugin_small_world

### 标签

[游戏王]

**Comment by CMHopeSunshine** [comment]
你插件包名叫nonebot?

**Comment by Passerby-D** [comment]
草 不小心打错了
