### ISSUE TITLE
Plugin: NAGA公交车

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#2061]
### 插件名称

NAGA公交车

### 插件描述

通过指令在NAGA进行雀魂/天凤牌谱解析

### PyPI 项目名

nonebot-plugin-nagabus

### 插件 import 包名

nonebot_plugin_nagabus

### 插件项目仓库/主页链接

https://github.com/ssttkkl/nonebot-plugin-nagabus

### 标签

[{"label":"日麻","color":"#b52ee1"}]

**Comment by ssttkkl** [comment]
插件测试未通过是因为插件只支持Reverse Driver（或者说只支持FastAPI）

**Comment by ssttkkl** [comment]
已更新

**Comment by yanyongyu** [comment]
请在用户未正确填写配置时提示用户并终止功能加载

**Comment by ssttkkl** [comment]
已更新

**Comment by yanyongyu** [comment]
我是指把事件响应单独写到一个文件里，如果配置错误就log异常，正确就import，这样不会出现插件加载出错

**Comment by ssttkkl** [comment]
> 我是指把事件响应单独写到一个文件里，如果配置错误就log异常，正确就import，这样不会出现插件加载出错

额，也行吧。我是觉得没有配置的话插件的所有功能都无法工作，直接让插件加载失败提示用户配置更合理些。
