### ISSUE TITLE
Plugin: stablediffusion绘画插件

### ISSUE THREAD

**Issue by DiaoDaiaChan** [nonebot/nonebot2#2065]
### 插件名称

stablediffusion绘画插件

### 插件描述

另一个绘画插件，支持多SD后端，负载均衡，lora，emb，chatgpt prompt生成，更换模型等等更多功能

### PyPI 项目名

nonebot-plugin-stable-diffusion-diao

### 插件 import 包名

nonebot_plugin_stable_diffusion_diao

### 插件项目仓库/主页链接

https://github.com/DiaoDaiaChan/nonebot-plugin-stable-diffusion-diao

### 标签

[{"label":"AI绘图","color":"#eaaf52"},{"label":"SD","color":"#eaaf52"}]

**Comment by DiaoDaiaChan** [comment]
乐

**Comment by he0119** [comment]
插件测试看起来没法通过，如果你确认没问题的话，我直接跳过测试。

**Comment by DiaoDaiaChan** [comment]
过！
