### ISSUE TITLE
Plugin: 链接防夹

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#2073]
### 插件名称

链接防夹

### 插件描述

自动转换发送消息中的URL，逃避URL检测

### PyPI 项目名

nonebot-plugin-escape-url

### 插件 import 包名

nonebot_plugin_escape_url

### 插件项目仓库/主页链接

https://github.com/bot-ssttkkl/nonebot-plugin-escape-url

### 标签

[{"label":"a:OneBot","color":"#5293ea"},{"label":"a:QQGuild","color":"#5293ea"}]

**Comment by yanyongyu** [comment]
请填写插件元信息中的 `config=Config` `type="application"` `homepage` `supported_adapters={"~onebot.v11", "~qqguild"}`

**Comment by ssttkkl** [comment]
已更新

**Comment by yanyongyu** [comment]
你仓库里的代码没更新啊

**Comment by ssttkkl** [comment]
> 你仓库里的代码没更新啊

1
