### ISSUE TITLE
Plugin: 碧蓝航线攻略

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/nonebot2#2075]
### 插件名称

碧蓝航线攻略

### 插件描述

从b站wiki搬运碧蓝井号榜等等攻略一图流

### PyPI 项目名

nonebot-plugin-al

### 插件 import 包名

nonebot_plugin_al

### 插件项目仓库/主页链接

https://github.com/Agnes4m/nonebot_plugin_AL

### 标签

[{"label":"bilibili","color":"#ea52e5"}]

**Comment by yanyongyu** [comment]
请填写插件元信息中的 `type="application"` `homepage` `supported_adapters={"~onebot.v11"}`

**Comment by Agnes4m** [comment]
已修改
