### ISSUE TITLE
Question: nonebot 无响应

### ISSUE THREAD

**Issue by gunh4mmer** [nonebot/nonebot2#2077]
### 操作系统

Windows

### Python 版本

3.11.3

### NoneBot 版本

2.0.0

### 适配器

onebot v11 2.2.2

### 协议端

go-cqhttp 1.0

### 描述问题

疑似消息阻塞，即go-cqhttp上显示已经接受信息，但是nonnebot上没有显示，但是如果此时按下ctrl+c，即可一瞬间显示，从阻塞开始到当前时间的所有信息，并且大概率仍然会按顺序执行相关命令。

### 复现步骤

如上

### 期望的结果

解决阻塞问题

### 截图或日志

![QQ截图20230602103244](https://github.com/nonebot/nonebot2/assets/73456895/c2ee31cc-24e3-4e2e-850b-3536397ef269)
shang
上图可以看出go-cqhhtp里面已经接受到了32分的信息，但是nonebot上仍然停留在28分，再过了几分钟后，我按下了ctrl+c，此时状况如下图
![QQ截图20230602104028](https://github.com/nonebot/nonebot2/assets/73456895/05e96470-7b75-4efb-98a9-1ad8803a6711)
可以看到信息批量接收，然后批量进行命令回复

**Comment by lgc2333** [comment]
提供下插件列表

**Comment by Well2333** [comment]
盲猜一手选中窗口了，Windows上请用Windows Terminal，原生的cmd或者powershell自己看看是不是选中东西了，窗口左上角的图标后面是不是有一个“选择：”的提示

**Comment by shikukuya** [comment]
不建议使用conhost，推荐windows terminal和gitbash（msys）

**Comment by gunh4mmer** [comment]
> 盲猜一手选中窗口了，Windows上请用Windows Terminal，原生的cmd或者powershell自己看看是不是选中东西了，窗口左上角的图标后面是不是有一个“选择：”的提示

还有这种说法。。。没注意

**Comment by gunh4mmer** [comment]
> 提供下插件列表
plugins = ["nonebot_plugin_bilichat", "nonebot_plugin_picsearcher", "haruka_bot", "nonebot_plugin_naturel_gpt"]
还有一些自己弄得

**Comment by gunh4mmer** [comment]
> 

感谢，等win更新了我去试试

**Comment by yanyongyu** [comment]
有问题欢迎到 https://discussions.nonebot.dev 讨论
