### ISSUE TITLE
Plugin: pcrjjc

### ISSUE THREAD

**Issue by reine-ishyanami** [nonebot/nonebot2#2090]
### 插件名称

pcrjjc

### 插件描述

pcrjjc排名监测插件

### PyPI 项目名

nonebot-plugin-pcrjjc

### 插件 import 包名

nonebot_plugin_pcrjjc

### 插件项目仓库/主页链接

https://github.com/reine-ishyanami/nonebot-plugin-pcrjjc

### 标签

[{"label":"t:公主连结","color":"#778a1e"},{"label":"t:pcrjjc","color":"#778a1e"}]

**Comment by reine-ishyanami** [comment]
测试

**Comment by he0119** [comment]
打包出问题了，为什么是从 src 文件夹开始的？

**Comment by reine-ishyanami** [comment]
> 打包出问题了，为什么是从 src 文件夹开始的？

```
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src/plugins"]
include = ["nonebot_plugin_pcrjjc"]

[tool.setuptools.package-data]
nonebot_plugin_pcrjjc = ["fonts/*.otf"]
```
打包配置是这段，请问该如何修改呢

**Comment by NCBM** [comment]
可以考虑使用 `{project_root}/{package}` 或 `{project_root}/src/{package}` 结构组织项目

**Comment by reine-ishyanami** [comment]
项目结构更新

**Comment by NCBM** [comment]
插件import包名改成下划线间隔

**Comment by yanyongyu** [comment]
插件需要添加[metadata](https://nonebot.dev/docs/advanced/plugin-info)并填写`type="application"` `homepage` `supported_adapters={"~onebot.v11"}`

**Comment by reine-ishyanami** [comment]
添加metadata

**Comment by yanyongyu** [comment]
数据存储建议使用[localstore](https://nonebot.dev/docs/best-practice/data-storing)官方存储支持

**Comment by yanyongyu** [comment]
@reine-ishyanami 另外metadata少了`config=Config`
