### ISSUE TITLE
Plugin: AI作曲

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#2092]
### 插件名称

AI作曲

### 插件描述

Nonebot框架下的AI作曲插件

### PyPI 项目名

nonebot-plugin-audiocraft

### 插件 import 包名

nonebot_plugin_audiocraft

### 插件项目仓库/主页链接

https://github.com/Alpaca4610/nonebot-plugin-audiocraft

### 标签

[{"label":"AI","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
插件需要添加[metadata](https://nonebot.dev/docs/advanced/plugin-info)并填写`type="application"` `homepage` `supported_adapters={"~onebot.v11"}`

**Comment by Alpaca4610** [comment]
add metadata

**Comment by yanyongyu** [comment]
metadata的config没有就是`None`，不是str

**Comment by Alpaca4610** [comment]
update metadata
