### ISSUE TITLE
Plugin: ba-strategy

### ISSUE THREAD

**Issue by zi-feng-0109** [nonebot/nonebot2#2099]
### PyPI 项目名

ba-strategy

### 插件 import 包名

ba-strategy

### 标签

[]

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/blob/master/nonebot_plugin_bawiki/__main__.py#L760

**Comment by yanyongyu** [comment]
如果还需要发布插件请重新提交issue
