### ISSUE TITLE
Plugin: bili_push

### ISSUE THREAD

**Issue by SuperGuGuGu** [nonebot/nonebot2#2100]
### PyPI 项目名

nonebot-plugin-bili-push

### 插件 import 包名

nonebot_plugin_bili_push

### 标签

[{"label":"bilibili","color":"#de5d92"}]

### 插件配置项

```dotenv
bilipush_basepath="./"
```

**Comment by he0119** [comment]
请将 nonebot2 也添加进依赖中。

**Comment by SuperGuGuGu** [comment]
更新版本-0.1.1

**Comment by he0119** [comment]
你的依赖还缺少了 onebot 适配器

**Comment by SuperGuGuGu** [comment]
更新版本-0.1.2（在改了在改了

**Comment by he0119** [comment]
请参考 [文档](https://nonebot.dev/docs/next/developer/plugin-publishing) 添加插件元数据。

**Comment by forchannot** [comment]
请不要使用同步的网络请求requests，改用异步httpx或者aiohttp，打印日志最好使用nonebot提供的logger，而非print

**Comment by SuperGuGuGu** [comment]
> 

下个版本就按这个来改
