### ISSUE TITLE
Feature: 增加filter

### ISSUE THREAD

**Issue by Fgaoxing** [nonebot/nonebot2#2105]
### 希望能解决的问题

过滤非法内容，和有害内容，全局替换字符

### 描述所需要的功能

增加过滤器，过滤接收到的消息，和发出的消息，如下
新消息——>nonebot（前置filter——>插件——>后置filter）——>发出消息

**Comment by Fgaoxing** [comment]
@he0119

**Comment by yanyongyu** [comment]
这个功能应该由插件通过 `event_preprocessor` 和 call api hook实现，与nb框架无关，参考 https://nonebot.dev/docs/advanced/runtime-hook

**Comment by Fgaoxing** [comment]
但是有没有办法把他优化的简单一些，方便一些，比如传入数据在传出数据

**Comment by yanyongyu** [comment]
这个功能也不会由nb本体来实现，你可以造一个插件来进行管理
