### ISSUE TITLE
Bug: @event_preprocessor 比 @Bot.on_called_api 先执行了

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [nonebot/nonebot2#2108]
### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

2.0.0

### 适配器

OneBot V11

### 协议端

go-cq 1.0.1

### 描述问题

   在 `NoneBot 2.0.0rc4` 及以前，`bot.send/matcher.send` 时，装饰器 `@Bot.on_called_api` 先于 装饰器 `@event_preprocessor` 执行，这样在 `@event_preprocessor` 时便可以获取到 `message_id`，
   但自动 `2.0.0rc5` 开始，这两个的执行顺序反了过来，这样 `on_called_api` 就毫无意义了。
   查看代码看起来应该是 `on_called_api` 先执行，不知为何 `@event_preprocessor` 插队了，希望能修正这个问题
![1c7678e9a7e6d2f350a34496429953e7](https://github.com/nonebot/nonebot2/assets/1246379/9146d71a-ae42-4581-81d6-13f992f594f2)

### 复现步骤

定义两个装饰器
```python
@Bot.on_called_api
async def handle_group_message_sent(bot: Bot, exception: Optional[Exception], api: str, data: Dict[str, Any], result: Any):
"""消息发送钩子，用于记录自己发送的消息"""
    global msg_sent_set
    if result and (api in ['send_msg', 'send_group_msg', 'send_private_msg']):
        logger.warning(f"收到发送事件：{api}, result:{result}")
        msg_id = result.get('message_id', None)
        if msg_id:
            msg_sent_set.add(f"{bot.self_id}_{msg_id}")
```
和
```python
@event_preprocessor
async def on_pre_message(event: BaseEvent, bot: BaseBot):
    """拦截消息发送"""
global msg_sent_set
    need_skip = False
    if isinstance(event, GroupMessageEvent) or isinstance(event, PrivateMessageEvent):
        if event.post_type == 'message_sent': # 通过bot.send发送的消息不处理
            msg_key = f"{bot.self_id}_{event.message_id}"
            if msg_key in msg_sent_set:
                msg_sent_set.remove(msg_key)
                need_skip = True

        if need_skip:
            raise IgnoredException("由bot_send发送的消息,取消派发")
```

在 `NoneBot 2.0.0rc4` 及以前, 两个函数是先执行 on_called_api ，再执行 event_preprocessor 的，但现在顺序反了过来

**Comment by yanyongyu** [comment]
你是在哪里调用的bot api，请给出你的代码

**Comment by yanyongyu** [comment]
event preprocessor和bot api hook是完全独立的两个部分，event preprocessor会在收到事件时就进行处理，而bot api hook是在你调用api时进行处理，这两hook完全不应该存在顺序反的问题。

能否给出复现最小实例

**Comment by Misaka-Mikoto-Tech** [comment]
> 

等我稍后写一个，我也很奇怪，我怀疑是否是因为这两个函数是在不同线程中执行的，所以并发执行了。我现在临时解决了，我在event preprocessor收到消息后加了一句 `await asyncio.sleep(0.2)`, 等 bot api hook 执行之后再判断 message_id

**Comment by Misaka-Mikoto-Tech** [comment]
> event preprocessor和bot api hook是完全独立的两个部分，event preprocessor会在收到事件时就进行处理，而bot api hook是在你调用api时进行处理，这两hook完全不应该存在顺序反的问题。
> 
> 能否给出复现最小实例

等我稍后写一个，我也很奇怪，我怀疑是否是因为这两个函数是在不同线程中执行的，所以并发执行了。我现在临时解决了，我在event preprocessor收到消息后加了一句 await asyncio.sleep(0.2), 等 bot api hook 执行之后再判断 message_id

**Comment by yanyongyu** [comment]
详细看了下你的代码，on_called_api和收到自己的消息事件这个时间完全是随机的。由于async的上下文切换和called api和事件接收完全独立，这个不算是bug他就是这样（

如果你一定要做的话，可以在on calling的时候加锁，called时候解锁，防止调用api的时候收到事件。

**Comment by yanyongyu** [comment]
而且这个问题和gocq有很强的关联性，如果gocq还没返回call api结果就上报了事件，你这里一样会乱序，建议自行加锁解决

**Comment by Misaka-Mikoto-Tech** [comment]
> 而且这个问题和gocq有很强的关联性，如果gocq还没返回call api结果就上报了事件，你这里一样会乱序，建议自行加锁解决

好的，我研究一下
