### ISSUE TITLE
Feature: 为插件设置增加命名空间

### ISSUE THREAD

**Issue by renmu123** [nonebot/nonebot2#2109]
### 希望能解决的问题

随着插件使用的增多，插件的配置项也会越来越多，如果采用目前的配置方式，那难免会有插件的配置项产生冲突。
虽然插件作者可以为自己的插件配置增加命名空间，但这显然不是很好的方法，希望可以在框架层面为插件配置增加命名空间。

### 描述所需要的功能

`dotenv`可以支持嵌套字典，那么可以不可以把比如插件名作为插件的命名空间。
比如我有一个插件叫做`nonebot_plugin`，有个配置项叫`to_me`，
那么用户可以通过这样配置dotenv文件来设置插件：
```
nonebot_plugin__to_me=true
```
或者直接在全局设置，但是命名空间中的配置优先级会优于全局设置
```
to_me=true
```

**Comment by yanyongyu** [comment]
插件读取配置的行为不受nb框架本体控制，这个功能应该由插件自行实现，例如：

```python
plugin_config = Config.parse_object(getattr(global_config, "plugin_name", {}))
```

这个用法可以在文档里进行注明
