### ISSUE TITLE
Plugin: Diablo4地狱狂潮boss提醒小助手

### ISSUE THREAD

**Issue by QBkira** [nonebot/nonebot2#2121]
### 插件名称

Diablo4地狱狂潮boss提醒小助手

### 插件描述

支持订阅，在D4继续上班

### PyPI 项目名

nonebot-plugin-helltide

### 插件 import 包名

nonebot_plugin_helltide

### 插件项目仓库/主页链接

https://github.com/QBkira/nonebot-plugin-helltide

### 标签

[{"label":"helltide","color":"#ff0000"},{"label":"diablo4","color":"#ff3300"}]

### 插件配置项

```dotenv
# event_check_interval=1
```

**Comment by QBkira** [comment]
已经更新

**Comment by QBkira** [comment]
已加上链接

**Comment by QBkira** [comment]
这漏了哪里没填，每次都是提示这个

**Comment by forchannot** [comment]
你的插件元数据没有包含homepage

**Comment by yanyongyu** [comment]
请正确填写插件支持的适配器 如：`supported_adapters={"~onebot.v11"}`

**Comment by QBkira** [comment]
> 请正确填写插件支持的适配器 如：`supported_adapters={"~onebot.v11"}`

元数据已补上

**Comment by yanyongyu** [comment]
你插件的type是application吧，不是library

**Comment by QBkira** [comment]
> 你插件的type是application吧，不是library

啊，确实，已修改
