### ISSUE TITLE
Docs: 内置配置项中API Timeout的类型有误

### ISSUE THREAD

**Issue by Decrabbityyy** [nonebot/nonebot2#2142]
### 描述问题或主题

API Timeout该项文档中标注类型为float | None
实际上该项只能配置为float

### 需做出的修改

修正文档中API Timeout的类型；或使API_TIMEOUT可以为None

**Comment by yanyongyu** [comment]
timeout是可以为None的，你是遇到了什么错误

**Comment by eya46** [comment]
如果想配置成None，在.env里面应该填啥，填的None、none都会报错

**Comment by MingxuanGame** [comment]
直接写 key，不加等号

```env
FOO
``` 

https://saurabh-kumar.com/python-dotenv/#variable-without-a-value

**Comment by yanyongyu** [comment]
文档里就有示例 https://nonebot.dev/docs/appendices/config#:~:text=%5D%0A%27%0AEMPTY_CONFIG%3D-,NULL_CONFIG,-Copy

**Comment by yanyongyu** [comment]
fixed in #2143
