### ISSUE TITLE
Feature: 希望添加贴吧聊天频道适配

### ISSUE THREAD

**Issue by RShock** [nonebot/nonebot2#2150]
### 希望能解决的问题

贴吧近期推出了聊天频道功能，类似q群，一个吧可以建立多个。
近来qq对机器人严重打压，其他平台用户使用少， 迁移困难。而贴吧安装量较大，希望大佬添加适配。

### 描述所需要的功能

希望添加对应适配

**Comment by yanyongyu** [comment]
暂时没有人手能够维护新的适配器，欢迎社区贡献
