### ISSUE TITLE
Bug: send_group_msg 无法正常工作

### ISSUE THREAD

**Issue by ZacharyChenpk** [nonebot/nonebot2#216]
我在代码中使用定时任务来对一个群发送消息，但是无法正常工作

**环境信息：**

 - OS: CentOS
 - Python Version: 3.7.9
 - Nonebot Version: 2.0.0a9.post1

代码：
scheduler = require("plugin-apscheduler-master.nonebot_plugin_apscheduler").scheduler
@scheduler.scheduled_job('cron', hour='*', minute='*')
async def _():
    bot = list(nonebot.get_bots().values())[0]
    now = datetime.now(pytz.timezone('Asia/Shanghai'))
    if (now.hour == 16 or now.hour == 17) and (now.minute == 50 or now.minute == 15):
        report = print_all_pot()
        await bot.send_group_msg(group=***,
                                    message_chain=[
            {
                "type": "text",
                "data": {
                    "text": 'info: \n'
                }
            },
            {
                "type": "text",
                "data": {
                    "text": report
                }
            }
        ])
其中print_all_pot是一个返回str的普通函数。

控制台报错信息：
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/python3/lib/python3.7/site-packages/nonebot/__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/python3/lib/python3.7/site-packages/nonebot/drivers/fastapi.py", line 166, in run
    **kwargs)
  File "/usr/python3/lib/python3.7/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/python3/lib/python3.7/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/python3/lib/python3.7/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/my-bot/pot/plugins/pot.py", line 511, in _
    "text": report
  File "/usr/python3/lib/python3.7/site-packages/nonebot/adapters/cqhttp/bot.py", line 369, in call_api
    seq, self.config.api_timeout))
  File "/usr/python3/lib/python3.7/site-packages/nonebot/adapters/cqhttp/bot.py", line 183, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=EMPTY_MSG_ERROR, retcode=100, status=failed, wording=消息为空>

**Comment by yanyongyu** [comment]
> await bot.send_group_msg(group=***, message_chain=[])

`cqhttp` 中参数名并不叫 `message_chain` 请勿和 `mirai-api-http` 搞混（

正确用法：

```python
from nonebot.adapters.cqhttp import MessageSegment

await bot.send_group_msg(group=xxx, message=MessageSegment.text("info: \n") + MessageSegment.text(report))
```

**Comment by ZacharyChenpk** [comment]
修改后报如下错误
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考输出>

**Comment by yanyongyu** [comment]
> nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考输出>

请参考go-cqhttp日志，多为风控，与nonebot无关
