### ISSUE TITLE
Plugin: nonebot-plugin-nobahpicture

### ISSUE THREAD

**Issue by Lptr-byte** [nonebot/nonebot2#2175]
### PyPI 项目名

nonebot-plugin-nobahpicture

### 插件 import 包名

nonebot_plugin_nobahpicture

### 标签

[{"label":"碧蓝档案","color":"#00defe"},{"label":"蔚蓝档案","color":"#00defe"},{"label":"涩图","color":"#00defe"}]

### 插件配置项
 
_No response_

**Comment by Lptr-byte** [comment]
PyPI 项目名
nonebot-plugin-nobahpictrue

插件 import 包名
nonebot_plugin_nobahpictrue

标签
[{"label":"t:碧蓝档案","color":"#00defe"},{"label":"t:蔚蓝档案","color":"#00defe"},{"label":"t:涩图","color":"#00defe"}]

**Comment by he0119** [comment]
你还需要将 nonebot2 依赖添加上去。

**Comment by CMHopeSunshine** [comment]
缺少`nonebot2`和`nonebot-adapter-onebot`依赖，建议使用`poetry`、`pdm`等现代包管理工具。
另外，请不要在异步框架中使用`requests`，建议改为`httpx`、`aiohttp`等异步网络请求库。

**Comment by Lptr-byte** [comment]
好的，那我再修改一下

**Comment by Lptr-byte** [comment]
update

**Comment by Lptr-byte** [comment]
> #  商店发布检查结果
> > Plugin: nonebot-plugin-nobahpictrue
> 
> **warning 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-nobahpictrue 的信息如下：
>        name         : nonebot-plugin-nobahpictrue 
>        version      : 1.0.6                       
>        description  : 获取碧蓝档案涩图                    
>       
>       dependencies
>        - httpx 0.24.1
>        - nonebot2 2.0.0
>   插件 nonebot-plugin-nobahpictrue 依赖的插件如下：
>       
>   插件 nonebot_plugin_nobahpictrue 加载出错：
>       07-10 06:16:01 [SUCCESS] nonebot | NoneBot is initializing...
>       07-10 06:16:01 [INFO] nonebot | Current Env: prod
>       07-10 06:16:01 [ERROR] nonebot | Failed to import "nonebot_plugin_nobahpictrue"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nobahpictrue-nonebot_plugin_nobahpictrue-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_nobahpictrue")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nobahpictrue-nonebot_plugin_nobahpictrue-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nobahpictrue-nonebot_plugin_nobahpictrue-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
>       ModuleNotFoundError: No module named 'nonebot_plugin_nobahpictrue'
> ```
> 
> 详情
> bulb 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 bulb 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> recycle 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://github.com/nonebot/noneflow)

update

**Comment by Lptr-byte** [comment]
update

**Comment by he0119** [comment]
应该是 picture 吧。

**Comment by Lptr-byte** [comment]
> 应该是 picture 吧。

感谢指正
