### ISSUE TITLE
Plugin: nonebot-plugin-picture-api

### ISSUE THREAD

**Issue by Q1351998764** [nonebot/nonebot2#2179]
### PyPI 项目名

nonebot-plugin-picture-api

### 插件 import 包名

nonebot_plugin_picture_api

### 标签

[{"label":"图片api","color":"#ea5252"}]

**Comment by he0119** [comment]
你应该依赖 `nonebot-adapter-onebot` 而不是 `nonebot-adapters-onebot`（

**Comment by Q1351998764** [comment]
好的好的，谢谢大佬。



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 11, 2023 16:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nonebot/nonebot2] Plugin: nonebot-plugin-picture-api (Issue#2179)




 
你应该依赖 nonebot-adapter-onebot 而不是 nonebot-adapters-onebot（
