### ISSUE TITLE
Question: Cannot find bot.py in current folder!

### ISSUE THREAD

**Issue by danuonuo** [nonebot/nonebot2#219]
**描述问题：**
使用nb-cli安装插件无论任何插件都提示**Cannot find bot.py in current folder!**

**如何复现？**

使用nb-cli安装任何插件

**期望的结果**

Cannot find bot.py in current folder!

**环境信息：**

 - OS: [Ubuntu20.04 LTS]
 - Python Version: [3.8.5]
 - Nonebot Version: [0.3.2]

**截图**
![image](https://user-images.githubusercontent.com/40296672/108442333-d4be5580-7291-11eb-8717-3deac66b5c4a.png)

**Comment by yanyongyu** [comment]
请在项目目录下运行nb相关命令，如果你的启动文件不叫`bot.py`的话请用-f参数指定

**Comment by SK-415** [comment]
请先使用 `nb init` 创建一个 NoneBot2 项目。

然后在项目根目录下，即 `bot.py` 所在目录下执行所有的  `nb` 指令相关操作。具体请**仔细**查阅 [文档](https://v2.nonebot.dev/guide/creating-a-project.html)。

**Comment by danuonuo** [comment]
> 请在项目目录下运行nb相关命令，如果你的启动文件不叫`bot.py`的话请用-f参数指定



> 请先使用 `nb init` 创建一个 NoneBot2 项目。
> 
> 然后在项目根目录下，即 `bot.py` 所在目录下执行所有的 `nb` 指令相关操作。具体请**仔细**查阅 [文档](https://v2.nonebot.dev/guide/creating-a-project.html)。

抱歉，可能没明白我的意思，我使用的是**nb plugin install xxx指令直接安装官方应用列表里的插件**

**Comment by yanyongyu** [comment]
> 抱歉，可能没明白我的意思，我使用的是**nb plugin install xxx指令直接安装官方应用列表里的插件**

插件也只能在项目目录下安装，因为需要在`bot.py`中加载插件

**Comment by danuonuo** [comment]
好的，谢谢。（虽然还是有点不明白2333）
