### ISSUE TITLE
能不能在nonebot2添加禁言踢人的功能、且添加获取发送者用户群信息

### ISSUE THREAD

**Issue by raindown200709** [nonebot/nonebot2#22]
**功能描述**
禁言踢人、获取发送者用户和群信息

**理由**
nb1的可以禁言踢人，如果nb2加上这个就比较厉害了
获取发送者用户群消息，nb1的session.event可以实现，但nb2没有实现，能不能从nb1迁移到nb2

**实现方案**
从nb1迁移到nb2

**Comment by mnixry** [comment]
https://github.com/nonebot/nonebot2/blob/master/nonebot/adapters/cqhttp.py#L315-380
这个是禁言等API调用的方法
https://v2.nonebot.dev/guide/writing-a-plugin.html#%E7%BC%96%E5%86%99%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0-handler
然后事件处理函数也有event参数
nonebot2已经没有了session概念

**Comment by yanyongyu** [comment]
nb2并没有nb1中的session这一套逻辑，你可以自行调用API完成

https://github.com/nonebot/nonebot2/blob/a308f4d4ee91fb929b6c5eb4916b578e11ae84ea/nonebot/adapters/cqhttp.pyi#L233-L251
