### ISSUE TITLE
Plugin: nonebot-plugin-SSBU-vip-score

### ISSUE THREAD

**Issue by yeye233cq** [nonebot/nonebot2#2203]
### PyPI 项目名

nonebot-plugin-SSBU-vip-score

### 插件 import 包名

nonebot_plugin_SSBU_vip_score

### 标签

[{"label":"GAME","color":"#ff0004"},{"label":"SSBU","color":"#ff0004"},{"label":"任天堂明星大乱斗","color":"#ff0004"}]

**Comment by yanyongyu** [comment]
还更新吗？

**Comment by yeye233cq** [comment]
> 还能更新啥，没有能更新的了
