### ISSUE TITLE
Question:如何使用nb-cli安装插件

### ISSUE THREAD

**Issue by danuonuo** [nonebot/nonebot2#221]
文档中的nb plugin install xxx安装完成后总是提示找不到bot.py，也无法使用，之前提过一个issue，但是并没有解决 #219

**Comment by abrahum** [comment]
当你使用nb plugin安装的时候，脚本需要修改你当前目录下的bot.py文件，增加加载该插件的语句，所以运行安装插件脚本是请确保pwd为bot.py所在的目录。

**Comment by mnixry** [comment]
"插件" 是基于一个nonebot"项目"的, 没有`bot.py`(当然也可以是别的入口文件), 也就是连"项目"都不存在,
你似乎用的是harukabot? [这里已经提供了文档](https://www.haruka-bot.live/install/)

**Comment by danuonuo** [comment]
> "插件" 是基于一个nonebot"项目"的, 没有`bot.py`(当然也可以是别的入口文件), 也就是连"项目"都不存在,
> 你似乎用的是harukabot? [这里已经提供了文档](https://www.haruka-bot.live/install/)

抱歉，不是。我用的是官方插件列表里的一个监控服务器状态的插件
