### ISSUE TITLE
Plugin: bot断连通知

### ISSUE THREAD

**Issue by Cypas** [nonebot/nonebot2#2211]
### PyPI 项目名

nonebot-plugin-disconnect-notice

### 插件 import 包名

nonebot_plugin_disconnect_notice

### 标签

[{"label":"掉线通知","color":"#ea5252"},{"label":"邮件","color":"#52eaa4"},{"label":"通知","color":"#cbea52"}]

### 插件配置项

```dotenv
# disconnect_notice示例配置
disconnect_notice_smtp_user = "114514@yeah.net" #邮箱账号
disconnect_notice_smtp_password = "114514" #邮箱密码
disconnect_notice_smtp_server = "smtp.yeah.net" #邮箱服务器地址
disconnect_notice_smtp_port = 465 #邮箱端口号
disconnect_notice_notice_email = "114514@qq.com" #收件人邮箱
```

**Comment by yanyongyu** [comment]
为什么只支持onebot？

**Comment by Cypas** [comment]
只有onebot11相关的qqbot用户量最大也最容易寄啊，其他的平台封号和断连的情况哪有那么多，这个之后看用户issus建议需要增加哪些平台和新的推送方式了，我也是预留了其他协议的接入位置

**Comment by Cypas** [comment]
已发布新版本
改为全平台协议兼容;
改为aiosmtplib异步发送邮件
