### ISSUE TITLE
Plugin: Bot上下线邮件通知

### ISSUE THREAD

**Issue by ZM25XC** [nonebot/nonebot2#2213]
### PyPI 项目名

nonebot-plugin-BotMailNotice

### 插件 import 包名

nonebot_plugin_BotMailNotice

### 标签

[{"label":"Mail","color":"#52e5ea"}]

### 插件配置项

```dotenv
MAIL_NOTICE='{
"username": "xxx@qq.com",
"password": "qflgxxxxxx",
"hostname": "smtp.qq.com",
"port": 587
}'
```

**Comment by yanyongyu** [comment]
主页访问不了啊
