### ISSUE TITLE
Plugin: Among US中的TOH模组职业介绍

### ISSUE THREAD

**Issue by qwqZYLqwq** [nonebot/nonebot2#2220]
### PyPI 项目名

nonebot-plugin-aujob

### 插件 import 包名

nonebot_plugin_aujob

### 标签

[{"label":"among us","color":"#48d5bf"},{"label":"TOH","color":"#05c4f2"}]

**Comment by qwqZYLqwq** [comment]
yee

**Comment by qwqZYLqwq** [comment]
> /update

已更改完

**Comment by yanyongyu** [comment]
记得更新github仓库

**Comment by qwqZYLqwq** [comment]
> 记得更新github仓库

已更新

**Comment by yanyongyu** [comment]
你handler标注的ob11事件还是没改啊，不改这个是没法用的啊。要改成事件基类。

```python
from nonebot.adapters import Event
```

**Comment by qwqZYLqwq** [comment]
emmmm

**Comment by yanyongyu** [comment]
依赖中的onebot适配器也可以删除了
