### ISSUE TITLE
Plugin: nonebot-plugin-buff

### ISSUE THREAD

**Issue by Sydrr0** [nonebot/nonebot2#2223]
### PyPI 项目名

nonebot-plugin-buff 

### 插件 import 包名

nonebot-plugin-buff 

### 标签

[{"label":"Buff_CS:GO","color":"#0f09ee"}]

**Comment by Sydrr0** [comment]
1

**Comment by StarHeartHunt** [comment]
```
    dependencies
     - requests >=2.31.0,<3.0.0
```

requests 会导致事件循环卡顿，不推荐在 nonebot 中使用 requests，可以考虑异步 httpx 或者 aiohttp 作为替代。

**Comment by Sydrr0** [comment]
> ```
>     dependencies
>      - requests >=2.31.0,<3.0.0
> ```
> 
> requests 会导致事件循环卡顿，不推荐在 nonebot 中使用 requests，可以考虑异步 httpx 或者 aiohttp 作为替代。

我的脚本比较简单，requests用的范围很小，请问是否可以用urllib.request替换或者接着使用requests

**Comment by NCBM** [comment]
搁这倒退是吧

**Comment by Sydrr0** [comment]
> 搁这倒退是吧

除了这个问题还有别的吗
