### ISSUE TITLE
Plugin: CSGO饰品查询机器人

### ISSUE THREAD

**Issue by Sydrr0** [nonebot/nonebot2#2224]
### PyPI 项目名

nonebot-plugin-csornament
### 插件 import 包名

nonebot_plugin_csornament

### 标签

[{"label":"CS:GO","color":"#047b97"}]

**Comment by yanyongyu** [comment]
插件的依赖是不是忘记更新了

**Comment by Sydrr0** [comment]
> 插件的依赖是不是忘记更新了
您说的对

**Comment by yanyongyu** [comment]
看见你插件里有些奇怪的代码，都不像是nb2的代码，请问是否能正确执行

```python
search.is_private_chat()
await bot.wait(timedelta(minutes=1))
```

**Comment by Sydrr0** [comment]
> 看见你插件里有些奇怪的代码，都不像是nb2的代码，请问是否能正确执行
> 
> ```python
> search.is_private_chat()
> await bot.wait(timedelta(minutes=1))
> ```

是完全没问题的，已经实测过

https://github.com/nonebot/nonebot2/assets/129657153/dd8ac1ed-ab39-4357-91c2-a4a16bdb40f0

**Comment by CMHopeSunshine** [comment]
你说是不是chatgpt写的）各种神奇的写法以及nonebot都没有的函数

**Comment by Sydrr0** [comment]
> 你说是不是chatgpt写的）各种神奇的写法以及nonebot都没有的函数

不是，但是我把之前写的插件拿了点过来，都是gocq，没问题

**Comment by CMHopeSunshine** [comment]
```    
async def main():
    miniprice = await get_miniprice(num=obindex, obtype=obname_type)
    await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))

loop = asyncio.get_event_loop()
loop.create_task(main())
```
这一部分为什么不直接：
```
miniprice = await get_miniprice(num=obindex, obtype=obname_type)
await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))
```
而要套一层task。

而且nonebot根本就没有`bot.wait`这种东西

**Comment by Sydrr0** [comment]
> ```python
> async def main():
>     miniprice = await get_miniprice(num=obindex, obtype=obname_type)
>     await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))
> 
> loop = asyncio.get_event_loop()
> loop.create_task(main())
> ```
> 
> 这一部分为什么不直接：
> 
> ```python
> miniprice = await get_miniprice(num=obindex, obtype=obname_type)
> await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))
> ```
> 
> 而要套一层task。
> 
> 而且nonebot根本就没有`bot.wait`这种东西

必须得加
loop = asyncio.get_event_loop()
loop.create_task(main())
否则给出的价格是这种没有解析的
![image](https://github.com/nonebot/nonebot2/assets/129657153/0f5bfa3c-7377-4876-b657-ddd77fc2e9ec)

**Comment by Sydrr0** [comment]
> > ```python
> > async def main():
> >     miniprice = await get_miniprice(num=obindex, obtype=obname_type)
> >     await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))
> > 
> > loop = asyncio.get_event_loop()
> > loop.create_task(main())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这一部分为什么不直接：
> > ```python
> > miniprice = await get_miniprice(num=obindex, obtype=obname_type)
> > await search.finish('%s\n现价: ￥ %s\nBuff代码: %s' % (obname_full, miniprice, obindex))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而要套一层task。
> > 而且nonebot根本就没有`bot.wait`这种东西
> 
> 必须得加 loop = asyncio.get_event_loop() loop.create_task(main()) 否则给出的价格是这种没有解析的 ![image](https://user-images.githubusercontent.com/129657153/257452930-0f5bfa3c-7377-4876-b657-ddd77fc2e9ec.png)

至于bot.wait是我之前为pycqbot写的插件，我忘记改了

**Comment by Sydrr0** [comment]
> 这边建议先学python异步呢谢谢。
> 
> 没有报错是因为finish了，后面的bot.wait没运行到而已，~蚌埠住了~

您好，我已经修改了代码，非常抱歉占用您的时间，我的基本功不是很扎实，还麻烦您赐教赐教，非常感谢，如果还有需要改进的地方，请您指正

**Comment by yanyongyu** [comment]
你的插件应该不仅仅支持onebot适配器吧，支持全平台的话supported adapters可以写none

**Comment by Sydrr0** [comment]
> 你的插件应该不仅仅支持onebot适配器吧，支持全平台的话supported adapters可以写none

您好，感谢您的体现，我已改正

**Comment by Sydrr0** [comment]
> 

try again

**Comment by Sydrr0** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-csornament
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-csornament 的信息如下：
>        name         : nonebot-plugin-csornament 
>        version      : 0.1.1                     
>        description  : nonebot社区插件，查询CSGO饰品      
>       
>       dependencies
>        - bs4 >=0.0.1
>        - lxml >=4.9.3
>        - nonebot2 >=2.0.1
>   插件 nonebot-plugin-csornament 依赖的插件如下：
>       
>   插件 nonebot_plugin_csornament 加载出错：
>       08-03 15:53:47 [SUCCESS] nonebot | NoneBot is initializing...
>       08-03 15:53:47 [INFO] nonebot | Current Env: prod
>       08-03 15:53:47 [ERROR] nonebot | Failed to import "nonebot_plugin_csornament"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_csornament")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot_plugin_csornament/__init__.py", line 32, in <module>
>           import httpx
>       ModuleNotFoundError: No module named 'httpx'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://githubfast.com/nonebot/noneflow)

try

**Comment by yanyongyu** [comment]
你的插件元数据里缺少了config

**Comment by Sydrr0** [comment]
> 你的插件元数据里缺少了config

**您好！那个不是说不需要可以不填么？祝您生活愉快！**

**Comment by yanyongyu** [comment]
但是你的插件里不是有config吗

**Comment by Sydrr0** [comment]
> 但是你的插件里不是有config吗

**是的，我用nb指令创建的plugin，那我直接把那个config加上去可以吗？**

**Comment by yanyongyu** [comment]
如果你的插件不需要config，把config全部删除；如果需要的话，请在元数据里填写config

**Comment by Sydrr0** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-csornament
> 
> **✅ 所有测试通过，一切准备就绪！**
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

更新

**Comment by Sydrr0** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-csornament
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-csornament 的信息如下：
>        name         : nonebot-plugin-csornament 
>        version      : 0.1.3                     
>        description  : nonebot社区插件，查询CSGO饰品      
>       
>       dependencies
>        - bs4 >=0.0.1
>        - httpx >=0.23.3
>        - lxml >=4.9.3
>        - nonebot2 >=2.0.1
>   插件 nonebot-plugin-csornament 依赖的插件如下：
>       
>   插件 nonebot_plugin_csornament 加载出错：
>       08-04 03:21:15 [SUCCESS] nonebot | NoneBot is initializing...
>       08-04 03:21:15 [INFO] nonebot | Current Env: prod
>       08-04 03:21:15 [ERROR] nonebot | Failed to import "nonebot_plugin_csornament"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_csornament")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-csornament-nonebot_plugin_csornament-test/.venv/lib/python3.10/site-packages/nonebot_plugin_csornament/__init__.py", line 1, in <module>
>           __plugin_meta__ = PluginMetadata(
>       NameError: name 'PluginMetadata' is not defined
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

更新

**Comment by Sydrr0** [comment]
> 如果你的插件不需要config，把config全部删除；如果需要的话，请在元数据里填写config

**您好，非常抱歉占用您的时间，我已更新完毕！**
