### ISSUE TITLE
Plugin: talk with poe ai

### ISSUE THREAD

**Issue by nikissXI** [nonebot/nonebot2#2229]
### PyPI 项目名

nonebot-plugin-talk-with-poe-ai

### 插件 import 包名

nonebot_plugin_talk_with_poe_ai

### 标签

[{"label":"poe","color":"#cd52ea"},{"label":"ai","color":"#cd52ea"}]

**Comment by nikissXI** [comment]
1

**Comment by nikissXI** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by yanyongyu** [comment]
你确定你的插件可以在全平台使用？

**Comment by KomoriDev** [comment]
`PluginMetadata` 里少了 `supported_adapters` 参数吧
加一行：`supported_adapters={"~onebot.v11"}`

**Comment by nikissXI** [comment]
> `PluginMetadata` 里少了 `supported_adapters` 参数吧，因为你的插件只能适配 Onebot V11，所以应该加一行：`supported_adapters={"~onebot.v11"}`

好的谢谢，正愁格式

**Comment by nikissXI** [comment]
> 你确定你的插件可以在全平台使用？

改好了
