### ISSUE TITLE
Plugin: KanonBot

### ISSUE THREAD

**Issue by SuperGuGuGu** [nonebot/nonebot2#2243]
### PyPI 项目名

nonebot-plugin-kanonbot

### 插件 import 包名

nonebot_plugin_kanonbot

### 标签

[{"label":"KanonBot","color":"#44ddff"}]

**Comment by SuperGuGuGu** [comment]
更新主页

**Comment by yanyongyu** [comment]
主页对吗¿

**Comment by SuperGuGuGu** [comment]
0.0.1b3版本修改了主页链接：https://github.com/SuperGuGuGu/nonebot_plugin_kanonbot
