### ISSUE TITLE
Plugin: MC版本更新检测

### ISSUE THREAD

**Issue by CN171-1** [nonebot/nonebot2#2246]
### PyPI 项目名

nonebot-plugin-mcversion

### 插件 import 包名

nonebot_plugin_mcversion

### 标签

[{"label":"版本","color":"#ea5252"},{"label":"MC","color":"#52e7ea"}]

### 插件配置项

```dotenv
MCVER_GROUP_ID=[123456789, 987654321]
```

**Comment by CN171-1** [comment]
蚌埠住了，脑子抽了.jpg

**Comment by CN171-1** [comment]
1

**Comment by yanyongyu** [comment]
加载还是有问题？

**Comment by CN171-1** [comment]
emmm，好嘛...

**Comment by CN171-1** [comment]
再试一次.jpg

**Comment by CN171-1** [comment]
彳亍了.jpg

**Comment by yanyongyu** [comment]
你代码编写的仅支持onebot适配器，请在元数据添加适配器支持信息

**Comment by CN171-1** [comment]
ok，加了
