### ISSUE TITLE
Plugin: Muteme(我禁我自己)

### ISSUE THREAD

**Issue by XTxiaoting14332** [nonebot/nonebot2#2251]
### PyPI 项目名

nonebot-plugin-muteme

### 插件 import 包名

nonebot_plugin_muteme

### 标签

[{"label":"禁言","color":"#e45b8d"},{"label":"muteme","color":"#5bc2e4"}]

**Comment by CMHopeSunshine** [comment]
你的仓库名是-，但是元数据里写的是_

**Comment by XTxiaoting14332** [comment]
> #  商店发布检查结果
> > Plugin: nonebot_plugin_muteme
> 
> **warning 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 项目 [主页](https://hub.xb6868.com/XTxiaoting14332/nonebot_plugin_muteme) 返回状态码 301。请确保您的项目主页可访问。
> ```
> 
> 详情
> bulb 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> recycle 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://hub.xb6868.com/nonebot/noneflow)

已更正 谢谢提醒

**Comment by XTxiaoting14332** [comment]
> #  商店发布检查结果
> > Plugin: nonebot_plugin_muteme
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 项目 [主页](https://hub.xb6868.com/XTxiaoting14332/nonebot_plugin_muteme) 返回状态码 301。请确保您的项目主页可访问。
> ```
> 
> 详情
> bulb 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 bulb 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://hub.xb6868.com/nonebot/noneflow)

已更正元数据

**Comment by XTxiaoting14332** [comment]
> 你的仓库名是-，但是元数据里写的是_。另外，请不要开新的issue，只需评论就会重新跑测试。

请问为什么改过来后还是不行呢

**Comment by XTxiaoting14332** [comment]
> 

已更新

**Comment by XTxiaoting14332** [comment]
> #  商店发布检查结果
> > Plugin: nonebot_plugin_muteme
> 
> **warning 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 项目 [主页](https://hub.xb6868.com/XTxiaoting14332/nonebot_plugin_muteme) 返回状态码 301。请确保您的项目主页可访问。
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> recycle 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://hub.xb6868.com/nonebot/noneflow)

已发布新的pypi包

**Comment by XTxiaoting14332** [comment]
> #  商店发布检查结果
> > Plugin: nonebot-plugin-muteme
> 
> **white_check_mark 所有测试通过，一切准备就绪！**
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 bulb 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://hub.xb6868.com/nonebot/noneflow)

已修改元数据

**Comment by XTxiaoting14332** [comment]
> > > 你的仓库名是-，但是元数据里写的是_。另外，请不要开新的issue，只需评论就会重新跑测试。
> > 
> > 
> > 请问为什么改过来后还是不行呢
> 
> 因为你还需要发布新版本。

请问我该如何更改插件在商店中显示的名称

**Comment by he0119** [comment]
> 请问我该如何更改插件在商店中显示的名称

修改插件元数据，并发布新版。

**Comment by yanyongyu** [comment]
支持的适配器漏写了吧，在插件元数据里加上

**Comment by XTxiaoting14332** [comment]
更新了元数据
加上了支持的适配器
