### ISSUE TITLE
Plugin: 剑网三查询和推送

### ISSUE THREAD

**Issue by fuyang0811** [nonebot/nonebot2#2253]
### PyPI 项目名

nonebot-plugin-jx3

### 插件 import 包名

nonebot_plugin_jx3

### 标签

[{"label":"剑网三","color":"#ea5252"},{"label":"jx3","color":"#ea5252"}]

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
> 

已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
不行了，先睡了，醒了再改

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
> 

已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
> 

已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by BigOrangeQWQ** [comment]
关注一下-和_的区别

**Comment by BigOrangeQWQ** [comment]
配置项应该添加默认值来着（issue配置项里面似乎没有填value）
应该也许大概可能是这个原因？

另外插件元数据未填写。

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
> 关注一下-和_的区别
说实话这两个符号的区别，我没搞太懂，我按照模板填的，（；´д｀）ゞ

**Comment by BigOrangeQWQ** [comment]
现在的问题是你好像没把nonebot-plugin-apscheduler
插件添加到依赖里面

只是写了个require

**Comment by fuyang0811** [comment]
> 现在的问题是你好像没把nonebot-plugin-apscheduler 插件添加到依赖里面
> 
> 只是写了个require

嗯嗯，大部分我能看懂，我慢慢改就行了，元数据不是很懂。 ᓚᘏᗢ，第一次上传，不是很标准，麻烦了。

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
> 现在的问题是你好像没把nonebot-plugin-apscheduler 插件添加到依赖里面
> 
> 只是写了个require

元数据是什么啊？？(′д｀ )…彡…彡poetry.lock么

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
已更新

**Comment by fuyang0811** [comment]
哦哦，好了，后面要更新的话只要更新pypi和github就行了吧？

**Comment by yanyongyu** [comment]
读写本地数据文件请使用localstore插件，参考https://nonebot.dev/docs/best-practice/data-storing

**Comment by fuyang0811** [comment]
> 读写本地数据文件请使用localstore插件，参考https://nonebot.dev/docs/best-practice/data-storing

好的，我看过了，也尝试了一下，发现数据文件是在用户文件夹下而不是机器人的文件夹里，我感觉这样不太好，不适合数据迁移和浏览。我想保持原来的data文件夹下可以么？

**Comment by fuyang0811** [comment]
> 

好的，谢谢
