### ISSUE TITLE
Bot: OCNbot

### ISSUE THREAD

**Issue by ACnoway** [nonebot/nonebot2#2260]
### 机器人名称

OCNbot

### 机器人描述

OI Contest Notifier bot，一个可以推送洛谷、cf、atcoder、牛客比赛通知的bot

### 机器人项目仓库/主页链接

https://github.com/ACnoway/OCNbot

### 标签

[{"label":"OI","color":"#2fccff"},{"label":"ACM","color":"#ff0004"}]

**Comment by yanyongyu** [comment]
要不换个名字¿别用`新`

**Comment by ACnoway** [comment]
改了qwq
