### ISSUE TITLE
Plugin: 双向聊天插件

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#2264]
### PyPI 项目名

nonebot-plugin-send-message

### 插件 import 包名

nonebot_plugin_send_message

### 标签

[{"label":"传话","color":"#52ea75"}]

### 插件配置项

```dotenv
SEND_MESSAGE=["123123"]
WELCOME="欢迎你添加我为好友\n我是一个传话机器人\n直接把你需要传递的信息发给我"
```

**Comment by fu050409** [comment]
插件 import 包名应该改成
nonebot_plugin_send_message

**Comment by yanyongyu** [comment]
请检查你的插件包名

**Comment by yanyongyu** [comment]
请根据[文档](https://nonebot.dev/docs/developer/plugin-publishing)补充插件元数据

**Comment by bingqiu456** [comment]
已添加

**Comment by yanyongyu** [comment]
插件支持的适配器填写错误

**Comment by bingqiu456** [comment]
已改

**Comment by yanyongyu** [comment]
你配置项的写法是错误的，请参考[nb文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)和[pydantic文档](https://docs.pydantic.dev/1.10/)
