### ISSUE TITLE
Plugin: 欧若可骰娘

### ISSUE THREAD

**Issue by fu050409** [nonebot/nonebot2#2265]
### PyPI 项目名

dicergirl

### 插件 import 包名

dicergirl

### 标签

[{"label":"跑团","color":"#ea5252"}]

**Comment by fu050409** [comment]
已修复问题

**Comment by fu050409** [comment]
已更新

**Comment by fu050409** [comment]
Pypi有延迟吗？已经是3.1.18了

**Comment by he0119** [comment]
是的

**Comment by fu050409** [comment]
项目 [主页](https://gitee.com/unvisitor/dicer) 返回状态码 None？？？？

**Comment by fu050409** [comment]
为什么是None呢我不理解

**Comment by he0119** [comment]
> 为什么是None呢我不理解

可能是 gitee 需要 ua，具体我也不清楚，待会儿测试一下。

**Comment by fu050409** [comment]
@he0119 多谢
不过离谱的是我重发了消息之后好了，没太理解是什么情况，感觉是Github自动化那边网络的问题

**Comment by yanyongyu** [comment]
看到插件依赖里有qqbotpy，提一下nb是支持QQ频道官方api的，可以直接使用适配器

**Comment by fu050409** [comment]
唔，close的issue会响应吗

**Comment by he0119** [comment]
不会

**Comment by fu050409** [comment]
> 不会

那如果要修改插件信息，是自己去fork一下仓库发PR吗？

**Comment by he0119** [comment]
是的，不过如不是项目名、包名或标签需要修改的话，直接更新插件元数据并发版就行。nonebot 商店信息会定期更新的，详见 https://registry.nonebot.dev/。

**Comment by fu050409** [comment]
> 是的，不过如不是项目名、包名或标签需要修改的话，直接更新插件元数据并发版就行。nonebot 商店信息会定期更新的，详见 [https://registry.nonebot.dev/。](https://registry.nonebot.dev/%E3%80%82)

[https://registry.nonebot.dev/](https://registry.nonebot.dev/)的确显示元数据被更新了。

不过我在[Nonebot2 商店](https://nonebot.dev/store)中搜索之后发现没有元数据没有被更新，是因为有延时？

**Comment by fu050409** [comment]
> 突然想到，新版插件商店还没发布，如果你想修改商店内容的话，还是直接 PR 吧。

好的，那我去发PR了

**Comment by he0119** [comment]
目前只有 nb-cli 用了 registry 数据，未来商店也会用上。

**Comment by fu050409** [comment]
> 目前只有 nb-cli 用了 registry 数据，未来商店也会用上。

也就是说`nb-cli`和`registry`是同步的对吧？

以及，商店的数据修改是`nonebot2/website/static/plugins.json`这个文件吗？

**Comment by he0119** [comment]
> 也就是说`nb-cli`和`registry`是同步的对吧？
> 
> 以及，商店的数据修改是`nonebot2/website/static/plugins.json`这个文件吗？

是的。

**Comment by fu050409** [comment]
`registry`这边已经更新了最新的元数据如下:
```json
{
  "name": "DicerGirl",
  "description": "新一代跨平台开源 TRPG 骰娘框架",
  "usage": "开箱即用",
  "type": "application",
  "homepage": "https://gitee.com/unvisitor/dicer",
  "supported_adapters": [
    "~onebot.v11"
  ]
}
```
详见[https://registry.nonebot.dev/plugin/dicergirl:dicergirl](https://registry.nonebot.dev/plugin/dicergirl:dicergirl)
然而在`nb-cli`里面似乎没有更新`name`，它是：
```plaintext
欧若可骰娘 (dicergirl)                                                     - 新一代跨平台开源 TRPG 骰娘框架
```
`欧若可骰娘`是我旧的插件名称，它看起来仍然没有更新。
我的元数据是同时修改的，`新一代跨平台开源 TRPG 骰娘框架`这个就是新的元数据。

这看起来是个小BUG，望检查。

**Comment by he0119** [comment]
有意思，我看看怎么回事。

**Comment by he0119** [comment]
> `欧若可骰娘`是我旧的插件名称，它看起来仍然没有更新。 我的元数据是同时修改的，`新一代跨平台开源 TRPG 骰娘框架`这个就是新的元数据。
> 
> 这看起来是个小BUG，望检查。

plugins.json 中的数据没问题，应该是 nb-cli 的缓存。

```json
{
    "module_name": "dicergirl",
    "project_link": "dicergirl",
    "name": "DicerGirl",
    "desc": "新一代跨平台开源 TRPG 骰娘框架",
    "author": "fu050409",
    "homepage": "https://gitee.com/unvisitor/dicer",
    "tags": [
        {
            "label": "跑团",
            "color": "#ea5252"
        }
    ],
    "is_official": false,
    "type": "application",
    "supported_adapters": [
        "nonebot.adapters.onebot.v11"
    ],
    "valid": true,
    "version": "3.3.1",
    "time": "2023-09-05T16:03:58.600442+08:00",
    "skip_test": false
}
```
