### ISSUE TITLE
Plugin: 周易蓍草占卜

### ISSUE THREAD

**Issue by fu050409** [nonebot/nonebot2#2267]
### PyPI 项目名

nonebot-plugin-uvdiviner

### 插件 import 包名

nonebot_plugin_uvdiviner

### 标签

[{"label":"占卜","color":"#440e0e"}]

**Comment by lgc2333** [comment]
6

**Comment by RF-Tar-Railt** [comment]
你在干什么

**Comment by Agnes4m** [comment]
是故意的还是不小心的

**Comment by fu050409** [comment]
手抖手抖

**Comment by fu050409** [comment]
复制粘贴搞错了不好意思诸位

**Comment by fu050409** [comment]
> 是故意的还是不小心的

纯属意外纯属意外（尴尬.jpg）

**Comment by fu050409** [comment]
pypi延迟……

**Comment by fu050409** [comment]
修复未列入的依赖包

**Comment by fu050409** [comment]
修复主页

**Comment by mobyw** [comment]
- Gitee 仓库似乎未设置为公开
- 如需检测 `DEBUG`，可以读取对应的 dotenv 配置项，无需在代码中使用全局变量
- 可以直接从 `nonebot.log` 导入 `logger`，其日志等级由 `LOG_LEVEL` 配置项管理，无需在启动时手动修改
- 延时请使用 `asyncio.sleep` 代替 `time.sleep`
- 插件似乎只有文本回复，可以不依赖特定适配器，可以参考内置的 `echo` 插件（如果设计目的是只在群聊触发可忽略）
- `limit` 设置为 `2` 且只有递减操作，每次非 `DEBUG` 模式该插件只能够正常运行两次

**Comment by fu050409** [comment]
> * Gitee 仓库似乎未设置为公开
> * 如需检测 `DEBUG`，可以读取对应的 dotenv 配置项，无需在代码中使用全局变量
> * 可以直接从 `nonebot.log` 导入 `logger`，其日志等级由 `LOG_LEVEL` 配置项管理，无需在启动时手动修改
> * 延时请使用 `asyncio.sleep` 代替 `time.sleep`
> * 插件似乎只有文本回复，可以不依赖特定适配器，可以参考内置的 `echo` 插件（如果设计目的是只在群聊触发可忽略）
> * `limit` 设置为 `2` 且只有递减操作，每次非 `DEBUG` 模式该插件只能够正常运行两次

多谢老哥

**Comment by fu050409** [comment]
@mobyw 顺便问下老哥隔壁我发的报错：
```
⚠️ 项目 [主页](https://gitee.com/unvisitor/dicer) 返回状态码 None。
```
怎么回事，我点开正常的，还是必须Github？

**Comment by yanyongyu** [comment]
如果是纯文本交流请修改移除适配器相关代码

**Comment by fu050409** [comment]
> 如果是纯文本交流请修改移除适配器相关代码

的确是纯文本，但是它基于Onebot的代码，将我之前写的本地代码移植到Nonebot2上，同时设定仅在QQ群聊中使用，需要移除适配器相关代码吗？

**Comment by fu050409** [comment]
更新：使用 asyncio.sleep 代替 time.sleep

**Comment by fu050409** [comment]
更新：设置定时重置limit

**Comment by yanyongyu** [comment]
> 同时设定仅在QQ群聊中使用

其实你可以移除这个限制让更多平台或者其他方式能够使用这个插件

**Comment by mobyw** [comment]
使用定时插件需要添加 `nonebot-plugin-apscheduler` 依赖

**Comment by fu050409** [comment]
> 其实你可以移除这个限制让更多平台或者其他方式能够使用这个插件

更新：插件移除Onebot限制



> 使用定时插件需要添加 `nonebot-plugin-apscheduler` 依赖

更新：修复 `nonebot-plugin-apscheduler` 的依赖问题

**Comment by fu050409** [comment]
更新：修复`scheduled_job`时间不能为`"24"`的问题.

**Comment by fu050409** [comment]
更新：修复bot无法加载的问题
似乎还是没奏效我给他移到函数里去了，先发上去，我再研究研究Nonebot2中bot的机制

**Comment by mobyw** [comment]
- 插件数据似乎是直接在插件目录下存储的，推荐使用 [`nonebot-plugin-localstore`](https://github.com/nonebot/plugin-localstore) 获取插件数据存储文件夹，或考虑使用 [`nonebot-plugin-datastore`](https://github.com/he0119/nonebot-plugin-datastore) 进行插件数据管理
- `Event` 类型均有 `get_user_id` 方法，但不一定有 `group_id` 字段，进行频率限制时可以考虑只使用 `user_id`
- `nonebot-adapter-onebot` 依赖可移除

**Comment by fu050409** [comment]
> * 插件数据似乎是直接在插件目录下存储的

我使用的是用户目录`Path(__file__).resolve().parent`， 即Windows中的`C:\Users\用户名\.uvdiviner`，Linux中的`~/.uvdiviner`作为存储目录，我并未使用被推荐的`nonebot-plugin-localstore`和`nonebot-plugin-datastore`一是由于我的项目还有非`Nonebot2`的版本，便于跨平台使用，二是我记得`datastore`似乎借助了数据库，那么当`Nonebot2`项目被部署到部分`serverless`中的时候会出现问题。

> * `Event` 类型均有 `get_user_id` 方法，但不一定有 `group_id` 字段，进行频率限制时可以考虑只使用 `user_id`

多谢提醒，正在改……

> * `nonebot-adapter-onebot` 依赖可移除

已删除该依赖。

**Comment by fu050409** [comment]
……刚才点错了

**Comment by fu050409** [comment]
> * `Event` 类型均有 `get_user_id` 方法，但不一定有 `group_id` 字段，进行频率限制时可以考虑只使用 `user_id`

我检查了代码，我在`group_id`字段中设置了`try: ... except: ...`的异常捕获，它似乎仍然正常运行，而针对群聊的配置是有利于管理的，虽说表面上说限制用户每日2次执行`占卜`这一个指令是玄学原因（bushi），但是实际上是防止有群员疯狂发指令导致机器人卡死，达成一个离谱的伪`DDOS`攻击。

同时为了多平台的泛用性，我这个我决定不去修改。但是我的确因此找到了一个由于`"0"`的BUG，因为`bot.send...`的时候可能会将`group_id`设置为`"0"`。

当然不管怎么说还是感谢老哥的帮助。

顺便问下老哥`nb-cli`这边是有延迟吗？我这边本地`nb plugin list`还没有找到我最近发布的插件，但是在[官网](https://nonebot.dev/store)上已经可以找到了。

**Comment by mobyw** [comment]
相关 PR 被合并后才能在 `nb-cli` 中查询，使用 `nb-cli` 查看插件列表时可能会因为使用了备选 url 而存在更新延迟。

**Comment by yanyongyu** [comment]
你可以使用`get_session_id`这是包括群信息的会话id

**Comment by fu050409** [comment]
> 你可以使用`get_session_id`这是包括群信息的会话id

多谢

**Comment by fu050409** [comment]
emm……又不小心点了close……最近手抖症状非常严重

这边的close是应该等机器人帮忙close还是可以手点？

我之前发的一个plugin好像就是机器人close的，目前官网还没能搜到。

**Comment by he0119** [comment]
等人工审核合并 PR 之后，issue 会自动关闭的。

**Comment by fu050409** [comment]
> 等人工审核合并 PR 之后，issue 会自动关闭的。

多谢

**Comment by yanyongyu** [comment]
在插件发布完成后会自动close

**Comment by fu050409** [comment]
> 在插件发布完成后会自动close

多谢
