### ISSUE TITLE
nb2.baka.icu这个文档地址的一个js脚本会时不时404

### ISSUE THREAD

**Issue by Redmomn** [nonebot/nonebot2#2269]
### 描述问题或主题

<img width="425" alt="image" src="https://github.com/nonebot/nonebot2/assets/109732988/6fd9ae67-ee75-49c4-a4dd-cd7c9ecc616e">
如图所示`https://nb2.baka.icu/assets/js/runtime~main.ea62d995.js`这个js会发生时不时请求不到的情况，请求不到的情况居多
这个问题从前天开始出现，具体表现就是导航栏的下拉菜单出不来，商店界面排版错误（好像就是所有的非超链接按钮都用不了）
<img width="1280" alt="image" src="https://github.com/nonebot/nonebot2/assets/109732988/fe06a607-abbc-4a7d-aaaf-00db8419c81c">

另外，实测在河北，北京，深圳等地访问nonebot文档均会出现这个问题，不知道是不是cdn的原因

### 需做出的修改

修复js时好时坏的问题

**Comment by Agnes4m** [comment]
臣附议

**Comment by StarHeartHunt** [comment]
已刷新镜像缓存

**Comment by yanyongyu** [comment]
https://nb2.baka.icu 为非官方镜像，有问题可以联系 @StarHeartHunt
