### ISSUE TITLE
Plugin: arxiv订阅

### ISSUE THREAD

**Issue by LuckySJTU** [nonebot/nonebot2#2281]
### PyPI 项目名

nonebot-plugin-arxivRSS

### 插件 import 包名

nonebot_plugin_arxivRSS

### 标签

[{"label":"arxiv","color":"#f30f0f"},{"label":"RSS","color":"#70a7d8"},{"label":"论文","color":"#f541dc"}]

**Comment by LuckySJTU** [comment]
已更新

**Comment by LuckySJTU** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-arxivRSS
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-arxivRSS 的信息如下：
>        name         : nonebot-plugin-arxivrss                                 
>        version      : 0.1.0                                                   
>        description  : Plugin of Nonebot2. Subscribe and push Arxiv RSS daliy. 
>       
>       dependencies
>        - feedparser *
>        - httpx >=0.23.3
>        - nonebot2 >=2.0.0
>   插件 nonebot-plugin-arxivRSS 依赖的插件如下：
>       
>   插件 nonebot_plugin_arxivRSS 加载出错：
>       08-18 03:30:32 [SUCCESS] nonebot | NoneBot is initializing...
>       08-18 03:30:32 [INFO] nonebot | Current Env: prod
>       08-18 03:30:32 [ERROR] nonebot | Failed to import "nonebot_plugin_arxivRSS"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-arxivRSS-nonebot_plugin_arxivRSS-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_arxivRSS")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-arxivRSS-nonebot_plugin_arxivRSS-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-arxivRSS-nonebot_plugin_arxivRSS-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-arxivRSS-nonebot_plugin_arxivRSS-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-arxivRSS-nonebot_plugin_arxivRSS-test/.venv/lib/python3.10/site-packages/nonebot_plugin_arxivRSS/__init__.py", line 11, in <module>
>           from nonebot.adapters.onebot.v11 import PrivateMessageEvent, GroupMessageEvent, MessageSegment, MessageEvent
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

已更新

**Comment by LuckySJTU** [comment]
yigengxin

**Comment by LuckySJTU** [comment]
111

**Comment by LuckySJTU** [comment]
222

**Comment by yanyongyu** [comment]
插件数据请勿存储在插件目录下污染python环境，请参考使用[数据存储](https://nonebot.dev/docs/best-practice/data-storing)

**Comment by LuckySJTU** [comment]
已更新localstore
