### ISSUE TITLE
Plugin: 识别动漫gal角色

### ISSUE THREAD

**Issue by tomorinao-www** [nonebot/nonebot2#2287]
### PyPI 项目名

nonebot-plugin-anime-trace 

### 插件 import 包名

nonebot_plugin_anime_trace

### 标签

[{"label":"AI","color":"#f541dc"}]

**Comment by tomorinao-www** [comment]
已更新

**Comment by yanyongyu** [comment]
你的插件usage有多余空格

**Comment by tomorinao-www** [comment]
> 你的插件usage有多余空格

已删除多余空格
