### ISSUE TITLE
更新到go-cqhttp-v0.9.40-fix2后发送消息出现报错

### ISSUE THREAD

**Issue by Skyar0423** [nonebot/nonebot2#229]
![QQ截图20210222173426](https://user-images.githubusercontent.com/12427962/108689598-3d2c6180-7534-11eb-8520-d235c7869c0b.png)
go-cqhttp-v0.9.40-fix2更新日志中提到将`post_type`改为了`message_sent`，然后跑nonebot2时就出现了以下报错（最后一行）
看起来是`message_sent`还未在支持列表中
![QQ截图20210222173327](https://user-images.githubusercontent.com/12427962/108689821-87adde00-7534-11eb-8dda-20f62c5bdde5.png)

**Comment by mnixry** [comment]
Duplicate of #222

**Comment by mnixry** [comment]
该问题已在 https://github.com/nonebot/nonebot2/commit/f9d4bcba3d03d3ec89944273fadac6ec6fd1c066 中被修复
请耐心等待发版(
