### ISSUE TITLE
Plugin: nonebot-plugin-starzai-memu

### ISSUE THREAD

**Issue by StarJian-Team** [nonebot/nonebot2#2290]
### PyPI 项目名

nonebot-plugin-starzai-memu

### 插件 import 包名

nonebot_plugin_starzai_memu

### 标签

[]

**Comment by lgc2333** [comment]
？

**Comment by fu050409** [comment]
请检查`setup.py`依赖包设置。

**Comment by KomoriDev** [comment]
这有一个发布到 pypi 的 [工作流](https://github.com/A-kirami/nonebot-plugin-template/blob/master/.github/workflows/pypi-publish.yml)，不需要 setup.py。

**Comment by fu050409** [comment]
> 这有一个发布到 pypi 的 [工作流](https://github.com/A-kirami/nonebot-plugin-template/blob/master/.github/workflows/pypi-publish.yml)，不需要 setup.py。

> > 请检查依赖包设置。`setup.py`
> 
> 您好，我发现我的开发目录下并没有setup.py，根据新手教程，我使用的是nb脚手架创建的项目，并没有setup.py。请问如何处理。

抱歉，我在之前没有详细阅读你的代码，你的项目中确实不包含`setup.py`，你使用了`Pypi工作流`API推送至`Pypi`。

你可以尝试以下方案：
1. 在你的项目目录表层新建`setup.py`，在`setup()`函数中，使用`install_requires`参数来列出项目所需的依赖包及其版本。例如：
```python
setup(
    name='nonebot-plugin-starzai-memu',
    version='0.1.3',
    install_requires=[
        'nonebot2',
        # 其它依赖项...
    ],
    # 其它内容...
)
```
~~就算~~`Github Actions`~~再牛逼我也能用原始方法解决问题~~

2. 在你的GitHub Actions工作流程中，确保你已经通过`pip install`命令安装了项目的依赖，例如：
```python
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install wheel twine
    pip install -r requirements.txt  # 如果使用了requirements.txt文件，否则请使用pip install nonebot2 [其它依赖...]
```
依赖的声明通常是在你的项目根目录下的`pyproject.toml`文件或者`requirements.txt`文件中定义的。这些文件用来告诉`Python`包管理器需要安装哪些依赖包。

**Comment by StarJian-Team** [comment]
> > 这有一个发布到 pypi 的 [工作流](https://github.com/A-kirami/nonebot-plugin-template/blob/master/.github/workflows/pypi-publish.yml)，不需要 setup.py。
> 
> > > 请检查依赖包设置。`setup.py`
> > 
> > 
> > 您好，我发现我的开发目录下并没有setup.py，根据新手教程，我使用的是nb脚手架创建的项目，并没有setup.py。请问如何处理。
> 
> 抱歉，我在之前没有详细阅读你的代码，你的项目中确实不包含`setup.py`，你使用了`Pypi工作流`API推送至`Pypi`。
> 
> 你可以尝试以下方案：
> 
> 1. 在你的项目目录表层新建`setup.py`，在`setup()`函数中，使用`install_requires`参数来列出项目所需的依赖包及其版本。例如：
> 
> ```python
> setup(
>     name='nonebot-plugin-starzai-memu',
>     version='0.1.3',
>     install_requires=[
>         'nonebot2',
>         # 其它依赖项...
>     ],
>     # 其它内容...
> )
> ```
> 
> ~就算~`Github Actions`~再牛逼我也能用原始方法解决问题~ **这是旧的打包方式，但至少能用**
> 
> 2. 在你的`GitHub Actions`工作流程中，你可以尝试使用`pip install`命令安装项目的依赖，例如：
> 
> ```python
> - name: Install dependencies
>   run: |
>     python -m pip install --upgrade pip
>     pip install wheel twine
>     pip install -r requirements.txt  # 如果使用了requirements.txt文件，否则请使用pip install nonebot2 [其它依赖...]
> ```
> 
> 防止是某些必须导入的依赖导致的打包错误。
> 
> 依赖的声明通常是在你的项目根目录下的`pyproject.toml`文件或者`requirements.txt`文件中定义的。这些文件用来告诉`Python`包管理器需要安装哪些依赖包。
> 
> 3. 在`pyproject.toml`中声明依赖 **（使用 PEP 517/518 标准的项目）**
> 
> ```toml
> [build-system]
> requires = ["setuptools>=42", "wheel", "pep517", "nonebot2"] # 只是个示例
> build-backend = "setuptools.build_meta"
> ```
> 
> 4. 放弃`Github Actions`工作流
>    如果你对`Github Actions`的需求并不强烈，你可以采用`setup.py`的方式来打包上传你的项目。
> 
> ```shell
> pip install twine
> python setup.py sdist bdist_wheel
> twine upload dist/*
> ```
> 
> 在`setup.py`中设置依赖项的方法参考方案1。

你好，我尝试了setup.py，在执行时，报错如下
Traceback (most recent call last):
  File "F:\StarJian\NoneBot-Dev\setup.py", line 1, in <module>
    setup(
    ^^^^^
NameError: name 'setup' is not defined

**Comment by StarJian-Team** [comment]
提交检查

**Comment by fu050409** [comment]
> 使用setup.py后1，仍旧报错

请检查`setup.py`是否符合规范，同时注意，`python setup.py sdist bdist_wheel`是使用`setup.py`打包的指令，请注意在`Github Actions`的`yml`文件中修改。

如果依然出现错误，希望你能给出详细的报错内容。

**Comment by fu050409** [comment]
如果你的项目的确无法使用`setup.py`打包，建议使用`pyproject.toml`作为打包声明文件。下面是一个示例：
```
[tool.poetry]
name = "包名"
description = "简介"
authors = ["作者"]
readme = "README.md"
homepage = "主页"
repository = "仓库"
documentation = "文档"
keywords = ["关键词",]
license = "开源证书"
classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License", #这个是开源证书请自行替换
        "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.6"
nonebot2 = "*"
nonebot-adapter-onebot = "*"
# ...其它依赖

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

使用`pip`安装`poetry`：
```
pip install poetry
```
安装完成后进入目录，使用`poetry`打包：
```
poetry build
```

**Comment by lgc2333** [comment]
为什么不用一个包管理器呢？例如 [pdm](https://pdm.fming.dev/latest/)

**Comment by StarJian-Team** [comment]
> 如果你的项目的确无法使用`setup.py`打包，建议使用`pyproject.toml`作为打包声明文件。下面是一个示例：
> 
> ```
> [tool.poetry]
> name = "包名"
> description = "简介"
> authors = ["作者"]
> readme = "README.md"
> homepage = "主页"
> repository = "仓库"
> documentation = "文档"
> keywords = ["关键词",]
> license = "开源证书"
> classifiers = [
>         "Programming Language :: Python :: 3",
>         "License :: OSI Approved :: Apache Software License", #这个是开源证书请自行替换
>         "Operating System :: OS Independent",
> ]
> 
> [tool.poetry.dependencies]
> python = "^3.6"
> nonebot2 = "*"
> nonebot-adapter-onebot = "*"
> # ...其它依赖
> 
> [build-system]
> requires = ["poetry-core>=1.0.0"]
> build-backend = "poetry.core.masonry.api"
> ```
> 
> **讲该文件命名为`pyproject.toml`，放置在项目表层目录中，同时，注意以下内容的修改**
> 
> 使用`pip`安装`poetry`：
> 
> ```
> pip install poetry
> ```
> 
> 安装完成后进入目录，使用`poetry`打包：
> 
> ```
> poetry build
> ```
> 
> **根据以上流程，修改`Github Actions`的配置文件，保证工作流的正常运作。**
你好，根据此教程，在编译时出现报错
Building nonebot-plugin-starzai-memu (0.0.4)

No file/folder found for package nonebot-plugin-starzai-memu

**Comment by fu050409** [comment]
> No file/folder found for package nonebot-plugin-starzai-memu

看起来你对`Python`打包**几乎没有涉猎**。你提供的信息过少，我无法判断你的问题。但是以下是出现以上情况的可能性以及解决方案：

1. **项目结构问题：** 
确保你的项目结构符合 Python 包的标准结构。你的项目目录中应该包含一个与你的库名相匹配的文件夹，该文件夹内包含一个 `__init__.py` 文件。例如：

   ```
   nonebot_plugin_starzai_memu/
   ├── __init__.py
   └── ...
   ```

3. **版本号问题：**
确保在 `pyproject.toml` 文件中正确指定了你的库的版本号，如：

   ```toml
   [tool.poetry]
   name = "nonebot-plugin-starzai-memu"
   version = "0.0.4"
   # 其他配置...
   ```

5. **依赖项问题：**
如果你的库依赖其他包，确保在 `pyproject.toml` 中正确声明它们。
值的注意的是，`nonebot-plugin-starzai-memu`看起来应该是你将要打包的项目，它不应该被声明在依赖项中。

7. **打包配置问题：** 如果你想使用 Poetry 打包你的库，确保在 `pyproject.toml` 中有以下配置：

   ```toml
   [build-system]
   requires = ["poetry-core>=1.0.0"]
   build-backend = "poetry.core.masonry.api"
   ```

   并且你的项目根目录下有 `pyproject.toml` 文件。

1. **以下是一个示例项目的结构：**

    ```
    your_package_name/
    ├── your_module.py
    └── __init__.py
    pyproject.toml
    ```

如果你仍然遇到问题，请提供更多关于报错或项目结构的详细信息。

**Comment by yanyongyu** [comment]
插件是否更新？

**Comment by StarJian-Team** [comment]
> 插件是否更新？

目前BOT反馈仍然报错无法加载，Bot正常

**Comment by yanyongyu** [comment]
你插件打包仍然有问题，请检查
