### ISSUE TITLE
Bot: huanxin_bot

### ISSUE THREAD

**Issue by huanxin996** [nonebot/nonebot2#2297]
### 机器人名称

huanxin_bot

### 机器人描述

开发中

### 机器人项目仓库/主页链接

https://github.com/huanxin996/nonebot_huanxin_bot

### 标签

[{"label":"幻歆","color":"#27d2d2"},{"label":"bot","color":"#dc1c15"}]

**Comment by KomoriDev** [comment]
？

**Comment by fu050409** [comment]
这是个空仓库吧？

**Comment by huanxin996** [comment]
> 这是个空仓库吧？

过几天会上传
