### ISSUE TITLE
Plugin: 二维码

### ISSUE THREAD

**Issue by tomorinao-www** [nonebot/nonebot2#2301]
### 插件名称

二维码

### 插件描述

通过pyzbar解析二维码

### 插件项目仓库/主页链接

https://github.com/tomorinao-www/nonebot-plugin-qrcode2

### 插件类型

application

### 插件支持的适配器

["~onebot.v11"]

### PyPI 项目名

nonebot-plugin-qrcode2

### 插件 import 包名

nonebot_plugin_qrcode2

### 标签

[{"label":"qrcode","color":"#f541dc"}]

**Comment by tomorinao-www** [comment]
根据pyzbar官方文档，zbar DLLs 已经包含在 Windows Python 轮子中。在其他操作系统上，需要安装 zbar 共享库。
Mac OS X:
    brew install zbar
Linux:
    sudo apt-get install libzbar0

nonebot的测试环境可能没有安装zbar，请问如何解决

**Comment by he0119** [comment]
现在没办法解决这个问题，只能跳过插件加载测试。

**Comment by yanyongyu** [comment]
noneflow这边需要调整一部分逻辑后才能合并此插件
