### ISSUE TITLE
Plugin: nonebot_plugin_groupAccountant

### ISSUE THREAD

**Issue by shilapi** [nonebot/nonebot2#2307]
### PyPI 项目名

nonebot_plugin_groupAccountant

### 插件 import 包名

nonebot_plugin_groupAccountant

### 标签

[]

**Comment by he0119** [comment]
<https://github.com/shilapi/nonebot-plugin-groupAccountant/blob/444c8153a85822f8a264ea769a2bbe3cdbdabe04/pyproject.toml#L12>

可以降低一下 python 版本限制吗？比如 ^3.10。依赖 ^3.10.6 是有什么特别的需求吗？
