### ISSUE TITLE
Plugin: nonebot-plugin-bastrategy

### ISSUE THREAD

**Issue by zi-feng-0109** [nonebot/nonebot2#2318]
### PyPI 项目名

nonebot-plugin-bastrategy

### 插件 import 包名

nonebot-plugin-bastrategy

### 标签

[{"label":"碧蓝档案","color":"#52b3ea"}]

**Comment by lgc2333** [comment]
这代码别说是我教的

**Comment by lgc2333** [comment]
这代码，别说是看了我的插件写出来的😨

**Comment by zi-feng-0109** [comment]
别骂了别骂了，给您丢脸了，我马上去改README，等以后更新优化了再加上去

**Comment by zi-feng-0109** [comment]
第一次写py的nonebot插件

**Comment by yanyongyu** [comment]
any update?
