### ISSUE TITLE
Plugin: nonebot_plugin_group_whitelist

### ISSUE THREAD

**Issue by Rikka-desu** [nonebot/nonebot2#2319]
### PyPI 项目名

nonebot-plugin-group-whitelist

### 插件 import 包名

nonebot_plugin_group_whitelist

### 标签

[]

**Comment by he0119** [comment]
如果没有通过你不需要重新开 issue 的。

>💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
>💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。

**Comment by Rikka-desu** [comment]
1

**Comment by he0119** [comment]
noneflow 是以插件中 metadata 的 name 为准的。如需修改名字请修改 metadata，并发布新版。

**Comment by Rikka-desu** [comment]
cao,忘记改那了

**Comment by yanyongyu** [comment]
你的插件仅适用于onebot协议吧

**Comment by Rikka-desu** [comment]
明白，加完了

**Comment by yanyongyu** [comment]
请在pypi发布版本

**Comment by Rikka-desu** [comment]
ok

**Comment by yanyongyu** [comment]
插件依赖缺少onebot适配器

**Comment by Rikka-desu** [comment]
已添加
