### ISSUE TITLE
Plugin: helper_plus

### ISSUE THREAD

**Issue by fR0Z863xF** [nonebot/nonebot2#2322]
### PyPI 项目名

nonebot-plugin-helper-plus

### 插件 import 包名

nonebot_plugin_helper_plus

### 标签

[{"label":"帮助","color":"#eae152"},{"label":"命令控制","color":"#52ea5c"}]

### 插件配置项

```dotenv
RULE_GROUP=["1"]
```

**Comment by fR0Z863xF** [comment]
1

**Comment by fR0Z863xF** [comment]
2

**Comment by XieXiLin2** [comment]
插件改完要在 PyPI 上发布新版，否则插件还是老版本的。

**Comment by fR0Z863xF** [comment]
哦我更新的时候版本号加了a，知道了谢谢！🙏

**Comment by fR0Z863xF** [comment]
啊？

**Comment by fR0Z863xF** [comment]
5

**Comment by he0119** [comment]
> 有没有佬帮我一下，这个到底是什么意思，我代码没问题啊，homepage也配置了啊

https://github.com/fR0Z863xF/nonebot-plugin-helper-plus/blob/f473317d073dd483f8450ae7affe192d676e8837/nonebot_plugin_helper_plus/__init__.py#L18

这个 homepage 是指插件元数据里的，你并没有配置。

**Comment by yanyongyu** [comment]
插件只支持onebot v11适配器吧，请在插件元数据内补充信息

**Comment by fR0Z863xF** [comment]
已更新
