### ISSUE TITLE
Plugin: 星崽Bot-菜单

### ISSUE THREAD

**Issue by StarJian-Team** [nonebot/nonebot2#2323]
### PyPI 项目名

nonebot-plugin-starzai-plugin-memu

### 插件 import 包名

nonebot_plugin_starzai_plugin_memu

### 标签

[]

**Comment by Kyomotoi** [comment]
请先认证阅读文档：
https://nonebot.dev/docs/developer/plugin-publishing

**Comment by bywhite0** [comment]
没必要重新开 Issue，在原 Issue 下触发测试就行了

**Comment by XieXiLin2** [comment]
就算换了你重新触发也会自动改的吧……

**Comment by he0119** [comment]
没区别的，你直接修改 issue 内容，会自动获取最新的名称

**Comment by bywhite0** [comment]
换项目名改元数据就行了

**Comment by XieXiLin2** [comment]
问: 为什么你用 Bot 项目的 pyproject.toml 来当插件的 pyproject.toml

**Comment by XieXiLin2** [comment]
没有就自己创造一个啊……
认 真 看 文 档 是 很 重 要 的

**Comment by StarJian-Team** [comment]
> 没有就自己创建一个啊…… 认 真 看 文 档 是 很 重 要 的

文档没写吧

**Comment by StarJian-Team** [comment]
> 没有就自己创建一个啊…… 认 真 看 文 档 是 很 重 要 的

咋写，文档没说

**Comment by StarJian-Team** [comment]
触发检查

**Comment by StarJian-Team** [comment]
> https://peps.python.org/pep-0621/ 参考其他插件的也可以……

其它插件的并无此文件
https://github.com/synodriver/nonebot_plugin_picsearcher/tree/beta1/nonebot_plugin_picsearcher

**Comment by StarJian-Team** [comment]
> https://github.com/SK-415/HarukaBot/blob/master/pyproject.toml

请问有没有Setuptools版的

**Comment by Kyomotoi** [comment]
你猜为什么 bot 将你的插件测试列为不通过 嗯？

**Comment by StarJian-Team** [comment]
> 你猜为什么 bot 将你的插件测试列为不通过 嗯？

为什么

**Comment by SakuraiCora** [comment]
cy

**Comment by Kyomotoi** [comment]
> > 你猜为什么 bot 将你的插件测试列为不通过 嗯？
> 
> 为什么

https://nonebot.dev/docs/developer/plugin-publishing#%E5%8F%91%E5%B8%83%E8%87%B3-pypi
这是我**第五次**给你发文档链接

**Comment by StarJian-Team** [comment]
> > > 你猜为什么 bot 将你的插件测试列为不通过 嗯？
> > 
> > 
> > 为什么
> 
> https://nonebot.dev/docs/developer/plugin-publishing#%E5%8F%91%E5%B8%83%E8%87%B3-pypi 这是我**第五次**给你发文档链接

这个链接我看过了，里面只有让我填入pyproject.toml

**Comment by Shanshui2022** [comment]
> > > > 你猜为什么 bot 将你的插件测试列为不通过 嗯？
> > > 
> > > 
> > > 为什么
> > 
> > 
> > https://nonebot.dev/docs/developer/plugin-publishing#%E5%8F%91%E5%B8%83%E8%87%B3-pypi 这是我**第五次**给你发文档链接
> 
> 这个链接我看过了，里面只有让我填入pyproject.toml

细看一下，里边有Setuptools的配置方法
https://setuptools.pypa.io/en/latest/

**Comment by StarJian-Team** [comment]
> > 这个链接我看过了，里面只有让我填入pyproject.toml
> 
> 细看一下，里边有Setuptools的配置方法 https://setuptools.pypa.io/en/latest/

谢谢，我看看

**Comment by eya46** [comment]
项目添加nonebot2的依赖

**Comment by StarJian-Team** [comment]
重新触发

**Comment by Shanshui2022** [comment]
> 重新触发

触发检查（

**Comment by StarJian-Team** [comment]
> > 重新触发
> 
> 触发检查（

等（）

**Comment by StarJian-Team** [comment]
触发检查

**Comment by eya46** [comment]
再加依赖，nonebot-adapter-onebot

**Comment by Shanshui2022** [comment]
> 再加依赖，nonebot-adapter-onebot

确实，字面意思（
~~这操作给我看傻了~~

**Comment by XieXiLin2** [comment]
你好 请遵守命名规范

**Comment by StarJian-Team** [comment]
> 你好 请遵守命名规范

请问如何解决目前的问题

**Comment by bywhite0** [comment]
> 请问如何解决目前的问题

随便找个 JSON 在线验证网站把你的元数据丢过去就能看出问题了

或者直接用 IDE 检查

**Comment by StarJian-Team** [comment]
触发检查

**Comment by StarJian-Team** [comment]
触发检查
