### ISSUE TITLE
Plugin: nonebot-plugin-souti

### ISSUE THREAD

**Issue by xiaoWangSec** [nonebot/nonebot2#2333]
### PyPI 项目名

nonebot-plugin-souti

### 插件 import 包名

nonebot_plugin_souti

### 标签

[{"label":"搜题","color":"#49e3d5"}]

**Comment by yanyongyu** [comment]
你的插件支持全部适配器的话，请修改元数据里的`supported_adapters=None`，另外请移除库依赖中的onebot适配器

**Comment by xiaoWangSec** [comment]
> 你的插件支持全部适配器的话，请修改元数据里的`supported_adapters=None`，另外请移除库依赖中的onebot适配器

已修改
