### ISSUE TITLE
Plugin: 女装 !

### ISSUE THREAD

**Issue by Lfhsheng** [nonebot/nonebot2#2335]
### PyPI 项目名

nonebot-plugin-wearskirt

### 插件 import 包名

nonebot_plugin_wearskirt

### 标签

[{"label":"女装","color":"#ffc0cb"}]

**Comment by Lfhsheng** [comment]
啊元数据忘记写了

**Comment by he0119** [comment]
话说你插件必须要 Python 3.11 以上吗？

**Comment by Lfhsheng** [comment]
其实不一定，不过最好吧

**Comment by he0119** [comment]
你还需要发布新版本至 pypi 才能进行验证。

**Comment by Lfhsheng** [comment]
> 你还需要发布新版本至 pypi 才能进行验证。

https://pypi.org/project/nonebot-plugin-wearskirt/0.1.1/
发布完成

**Comment by Lfhsheng** [comment]
> 

test

**Comment by Lfhsheng** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-wearskirt
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出项目 nonebot-plugin-wearskirt 创建失败：
>       Creating virtualenv nonebot-plugin-wearskirt-nonebot-plugin-wearskirt-test in /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv
>       
>       The current project's Python requirement (>=3.10,<3.11) is not compatible with some of the required packages Python requirement:
>         - nonebot-plugin-wearskirt requires Python >=3.11,<4.0, so it will not be satisfied for Python >=3.10,<3.11
>       
>       Because no versions of nonebot-plugin-wearskirt match >0.1.0,<0.2.0
>        and nonebot-plugin-wearskirt (0.1.0) requires Python >=3.11,<4.0, nonebot-plugin-wearskirt is forbidden.
>       So, because nonebot-plugin-wearskirt-nonebot-plugin-wearskirt-test depends on nonebot-plugin-wearskirt (^0.1.0), version solving failed.
>       
>         • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
>           
>           For nonebot-plugin-wearskirt, a possible solution would be to set the `python` property to "<empty>"
>       
>           https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
>           https://python-poetry.org/docs/dependency-specification/#using-environment-markers
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

重新测试

**Comment by he0119** [comment]
> > 你还需要发布新版本至 pypi 才能进行验证。
> 
> https://pypi.org/project/nonebot-plugin-wearskirt/0.1.2a0/ 发布完成

版本请发布正式版。

**Comment by Lfhsheng** [comment]
> > > 你还需要发布新版本至 pypi 才能进行验证。
> > 
> > 
> > https://pypi.org/project/nonebot-plugin-wearskirt/0.1.2a0/ 发布完成
> 
> 版本请发布正式版。

https://pypi.org/project/nonebot-plugin-wearskirt/0.1.2/ OK

**Comment by Lfhsheng** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-wearskirt
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-wearskirt 的信息如下：
>        name         : nonebot-plugin-wearskirt 
>        version      : 0.1.1                    
>        description  : Nonebot 赛博女装插件           
>   插件 nonebot-plugin-wearskirt 依赖的插件如下：
>       
>   插件 nonebot_plugin_wearskirt 加载出错：
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/runner.py", line 5, in <module>
>           from nonebot import init, load_plugin, require
>       ModuleNotFoundError: No module named 'nonebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

这样评论能重新测试吗

**Comment by he0119** [comment]
任何评论均可触发，修改 issue 内容或者标题也能触发。

**Comment by Lfhsheng** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-wearskirt
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-wearskirt 的信息如下：
>        name         : nonebot-plugin-wearskirt 
>        version      : 0.1.2                    
>        description  : Nonebot 赛博女装插件           
>       
>       dependencies
>        - nonebot-plugin-localstore >=0.5.0,<0.6.0
>        - nonebot2 >=2.0.1,<3.0.0
>   插件 nonebot-plugin-wearskirt 依赖的插件如下：
>       nonebot_plugin_localstore
>   插件 nonebot_plugin_wearskirt 加载出错：
>       09-02 12:58:53 [SUCCESS] nonebot | NoneBot is initializing...
>       09-02 12:58:53 [INFO] nonebot | Current Env: prod
>       09-02 12:58:53 [ERROR] nonebot | Failed to import "nonebot_plugin_wearskirt"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_wearskirt")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot_plugin_wearskirt/__init__.py", line 8, in <module>
>           from .wear_skirt import *
>       ModuleNotFoundError: No module named 'nonebot_plugin_wearskirt.wear_skirt'
> ```
> 
> 详情
> ```
> * ✅ 项目 [nonebot-plugin-wearskirt](https://pypi.org/project/nonebot-plugin-wearskirt/) 已发布至 PyPI。* ✅ 标签: 女装-#ffc0cb。
> ```
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

https://pypi.org/project/nonebot-plugin-wearskirt/0.1.3/ 蚌埠住了，一天发三个版本，唉

**Comment by XieXiLin2** [comment]
别急，有些时候在其他地方有人会比你发的还多（

**Comment by AzideCupric** [comment]
不得不品（

**Comment by Lfhsheng** [comment]
唉，又忘记加库了

**Comment by Lfhsheng** [comment]
这库我已经加了，怪

**Comment by he0119** [comment]
> 这库我已经加了，怪

你在使用 nonebot_plugin_localstore 前没有 require。

**Comment by Lfhsheng** [comment]
问个外行的问题，我在测试时并没有任何报错，为什么这里能够检查出来

**Comment by he0119** [comment]
> 问个外行的问题，我在测试时并没有任何报错，为什么这里能够检查出来

通过直接加载 nonebot_plugin_localstore 测试，如果 import 前没有 require 就会报错。

**Comment by Lfhsheng** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-wearskirt
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-wearskirt 的信息如下：
>        name         : nonebot-plugin-wearskirt 
>        version      : 0.1.3                    
>        description  : Nonebot 赛博女装插件           
>       
>       dependencies
>        - nonebot-plugin-localstore >=0.5.0,<0.6.0
>        - nonebot2 >=2.0.1,<3.0.0
>   插件 nonebot-plugin-wearskirt 依赖的插件如下：
>       nonebot_plugin_localstore
>   插件 nonebot_plugin_wearskirt 加载出错：
>       09-02 13:27:19 [SUCCESS] nonebot | NoneBot is initializing...
>       09-02 13:27:19 [INFO] nonebot | Current Env: prod
>       09-02 13:27:19 [ERROR] nonebot | Failed to import "nonebot_plugin_localstore"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_wearskirt")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot_plugin_wearskirt/__init__.py", line 12, in <module>
>           require('nonebot_plugin_localstore')
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 179, in require
>           plugin = load_plugin(name)
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 155, in load_plugin
>           raise RuntimeError(
>       RuntimeError: Module nonebot_plugin_localstore is not loaded as a plugin! Make sure not to import it before loading.
>       09-02 13:27:19 [ERROR] nonebot | Failed to import "nonebot_plugin_wearskirt"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_wearskirt")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot_plugin_wearskirt/__init__.py", line 12, in <module>
>           require('nonebot_plugin_localstore')
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-wearskirt-nonebot_plugin_wearskirt-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 183, in require
>           raise RuntimeError(f'Cannot load plugin "{name}"!')
>       RuntimeError: Cannot load plugin "nonebot_plugin_localstore"!
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

希望没有bug了😨

**Comment by Lfhsheng** [comment]
唉，bug好多，麻烦各位大佬了，不好意思

**Comment by lgc2333** [comment]
用数据库的话，可以试一试 nonebot-plugin-datastore

**Comment by Lfhsheng** [comment]
> 用数据库的话，可以试一试 [nonebot-plugin-datastore](https://github.com/he0119/nonebot-plugin-datastore) 喵

坏了坑越来越大了（
主要是可能得做数据迁移
但是这想法不错
