### ISSUE TITLE
Plugin: 森空岛明日方舟签到器

### ISSUE THREAD

**Issue by GuGuMur** [nonebot/nonebot2#2339]
### PyPI 项目名

nonebot-plugin-skland-arksign

### 插件 import 包名

nonebot_plugin_skland_arksign

### 标签

[{"label":"森空岛","color":"#c8eb21"},{"label":"明日方舟","color":"#111111"},{"label":"签到","color":"#ea5252"}]

**Comment by XieXiLin2** [comment]
没加 Adapter 为依赖。

**Comment by GuGuMur** [comment]
已更新

**Comment by AzideCupric** [comment]
一定非得onebot适配器吗

**Comment by StarHeartHunt** [comment]
`nonebot-plugin-apscheduler` 也依赖了但是没声明，以及如果是纯文本的插件不需要依赖 onebot 适配器。

**Comment by GuGuMur** [comment]
已更新
