### ISSUE TITLE
Plugin: 文心一言

### ISSUE THREAD

**Issue by Noctulus** [nonebot/nonebot2#2341]
### PyPI 项目名

nonebot-plugin-ernie

### 插件 import 包名

nonebot_plugin_ernie

### 标签

[{"label":"文心一言","color":"#2e317c"}]

### 插件配置项

```dotenv
WENXIN_AK="千帆大模型access key"
WENXIN_SK="千帆大模型secret key"
```

**Comment by Noctulus** [comment]
已更新

**Comment by yanyongyu** [comment]
你的插件不应该只支持onebot，稍微改下调用方式可以支持全平台

**Comment by Noctulus** [comment]
> 你的插件不应该只支持onebot，稍微改下调用方式可以支持全平台

已更新。

**Comment by Noctulus** [comment]
已更新修正
