### ISSUE TITLE
Plugin: nicoinfo

### ISSUE THREAD

**Issue by ECUsam** [nonebot/nonebot2#2346]
### PyPI 项目名

nicoinfo

### 插件 import 包名

nicoinfo

### 标签

[{"label":"cookie","color":"#ea7952"},{"label":"niconico","color":"#ea7952"}]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
你的插件依赖管理存在问题，请勿使用`==`限制版本号
