### ISSUE TITLE
Plugin: nonebot_plugin_yiyan

### ISSUE THREAD

**Issue by barryblueice** [nonebot/nonebot2#2348]
### PyPI 项目名

nonebot_plugin_yiyan

### 插件 import 包名

nonebot_plugin_yiyan

### 标签

[]

### 插件配置项

```dotenv
client_id = appid
client_secret = secret key
history_num = int
history_clear_time = int
name = VALUE
```

**Comment by barryblueice** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot_plugin_yiyan
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 标签: the JSON object must be str, bytes or bytearray, not NoneType* ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot_plugin_yiyan 的信息如下：
>        name         : nonebot-plugin-yiyan 
>        version      : 1.1.5                
>        description  : Nonebot文心一言对话平台      
>       
>       dependencies
>        - nonebot-adapter-onebot *
>        - nonebot-plugin-apscheduler *
>        - nonebot2 *
>        - requests *
>   插件 nonebot_plugin_yiyan 依赖的插件如下：
>       nonebot_plugin_apscheduler
>   插件 nonebot_plugin_yiyan 加载出错：
>       09-06 18:06:37 [SUCCESS] nonebot | NoneBot is initializing...
>       09-06 18:06:37 [INFO] nonebot | Current Env: prod
>       09-06 18:06:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_yiyan"
>       09-06 18:06:38 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/runner.py", line 30, in <module>
>           require('nonebot_plugin_apscheduler')
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 179, in require
>           plugin = load_plugin(name)
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 155, in load_plugin
>           raise RuntimeError(
>       RuntimeError: Module nonebot_plugin_apscheduler is not loaded as a plugin! Make sure not to import it before loading.
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/runner.py", line 30, in <module>
>           require('nonebot_plugin_apscheduler')
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot_plugin_yiyan-nonebot_plugin_yiyan-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 183, in require
>           raise RuntimeError(f'Cannot load plugin "{name}"!')
>       RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!
> ```
> 
> 详情
> ```
> * ✅ 项目 [nonebot_plugin_yiyan](https://pypi.org/project/nonebot_plugin_yiyan/) 已发布至 PyPI。
> ```
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

已修改

**Comment by he0119** [comment]
请在导入 nonebot_plugin_apscheduler 之前 require 该插件。

```python
from nonebot import require

require("nonebot_plugin_apscheduler")

from nonebot_plugin_apscheduler import scheduler
```

**Comment by yanyongyu** [comment]
any update？
