### ISSUE TITLE
Plugin: pamo-nonebot-ff14Tools

### ISSUE THREAD

**Issue by opaup** [nonebot/nonebot2#2365]
### PyPI 项目名

pamo-nonebot-ff14Tools

### 插件 import 包名

pamo-nonebot-ff14Tools

### 标签

[{"label":"ff14","color":"#ea5252"},{"label":"真寻bot","color":"#eaaa52"}]

**Comment by yanyongyu** [comment]
如需重新触发插件检测，请在pypi发布插件新版本后在此页面评论触发测试
