### ISSUE TITLE
Plugin: nonebot-plugin-video-api

### ISSUE THREAD

**Issue by Q1351998764** [nonebot/nonebot2#2366]
### PyPI 项目名

nonebot-plugin-video-api

### 插件 import 包名

nonebot_plugin_video_api

### 标签

[{"label":"视频api","color":"#14d8de"}]

**Comment by yanyongyu** [comment]
请勿在使用配置项的同时创建文件夹或配置文件，可以通过配置项指定文件路径再去读取

**Comment by yanyongyu** [comment]
插件依赖中缺少localstore，请记得添加（

**Comment by Q1351998764** [comment]
添加上了，发现localstore的readme里有个小bug，get_config_dir只需要一个参数。
![~Q2IYCB1PG9CN UE9(_`B`5](https://github.com/nonebot/nonebot2/assets/57926506/46ea0c0a-860a-4cd8-8906-5d86d68e4200)
