### ISSUE TITLE
Plugin: nonebot-plugin-mar7th_ai

### ISSUE THREAD

**Issue by GrayTempest-400** [nonebot/nonebot2#2378]
### PyPI 项目名

nonebot-plugin-mar7th_ai

### 插件 import 包名

nonebot-plugin-mar7th_ai

### 标签

插件模型过大无法上传pypi请github下载

### 插件配置项

```dotenv
看readme
```

**Comment by GrayTempest-400** [comment]
https://github.com/GrayTempest-400/marth7th_qqbot

**Comment by RF-Tar-Railt** [comment]
模型太大了那你不能整个插件初始化的时候从gh上下模型的操作吗。。

**Comment by GrayTempest-400** [comment]
也行
