### ISSUE TITLE
Question: 如何使用 permission 模块中的 USER()

### ISSUE THREAD

**Issue by fhyuncai** [nonebot/nonebot2#239]
perm 需要传入什么参数？单独传入 *user 无效

**Comment by yanyongyu** [comment]
`permission=USER(123, 456)`

**Comment by fhyuncai** [comment]
但是我这边无效，看了源代码获取的是 session_id ？
https://github.com/nonebot/nonebot2/blob/93ffc93a80cf9e3103eb4a164e7b32ab3cdd0882/nonebot/permission.py#L129-L130

**Comment by yanyongyu** [comment]
使用字符串形式可以

**Comment by fhyuncai** [comment]
> 使用字符串形式可以

那就需要用 `user = ["friend_123"]` 作为白名单

感觉不太方便啊
