### ISSUE TITLE
Feature: 在 meta 中强制添加更具体的插件用法描述

### ISSUE THREAD

**Issue by Dobiichi-Origami** [nonebot/nonebot2#2391]
### 希望能解决的问题

是否可以强制一种统一描述 NB Plugin 输入参数的描述形式，以帮助用户更快上手插件的使用？

### 描述所需要的功能

可以在 `__plugin_meta__` 中添加一个额外的字典，姑且名为 `args`，其为一个 list ，元素是以字典格式存储的插件形参描述，包括但不限于类型，用途等？
除此之外还可以添加一个 类似于`cmd` 的字段来描述触发关键词或其它的触发规则，如 shell command 等？

**Comment by yanyongyu** [comment]
Duplicate of #1015
