### ISSUE TITLE
Plugin: 算法比赛查询和今日比赛自动提醒

### ISSUE THREAD

**Issue by zhuhiki** [nonebot/nonebot2#2394]
### PyPI 项目名

nonebot-plugin-matchreminder

### 插件 import 包名

nonebot_plugin_matchreminder

### 标签

[]

### 插件配置项

```dotenv
superusers=["1145141"]
```

**Comment by zhuhiki** [comment]
为什么

**Comment by he0119** [comment]
请检查一下你打包的文件夹名，我看了一下文件夹名是 `nonenbot_plugin_matchreminder`，而非 `nonebot_plugin_matchreminder`。

**Comment by zhuhiki** [comment]
我超，还真是，我是💩
