### ISSUE TITLE
Feature: 封装对正向Websocket/轮询的支持

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#240]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

有很多bot的API均只提供轮询或者Websocket通信
而提供webhook等的仍是少数
在mah的adapter中实现了一个对正向Websocket的支持，但可复用性差

**描述你所需要的特性：**

添加对主动建立连接（即作为客户端）的封装

**Comment by yanyongyu** [comment]
在最新的dev分支中初步完成了实验性正向driver `nonebot.drivers.aiohttp`，可以先行尝试再反馈

**Comment by yanyongyu** [comment]
released in `2.0.0a14`
