### ISSUE TITLE
Plugin: op-finder

### ISSUE THREAD

**Issue by ninthseason** [nonebot/nonebot2#2402]
### PyPI 项目名

nonebot-plugin-op-finder

### 插件 import 包名

nonebot_plugin_op_finder

### 标签

[{"label":"原神","color":"#00a0ea"}]

### 插件配置项

```dotenv
KOOK_AUTH_KEY=kook_auth_key
```

**Comment by ninthseason** [comment]
update

**Comment by yanyongyu** [comment]
你要不把你的标签颜色改一下¿全是黑色太奇怪了

**Comment by ninthseason** [comment]
现在是否可行
