### ISSUE TITLE
Plugin: 肯定机

### ISSUE THREAD

**Issue by EuDs63** [nonebot/nonebot2#2408]
### PyPI 项目名

nonebot-plugin-yesman

### 插件 import 包名

nonebot-plugin-yesman

### 标签

[  ]

### 插件配置项

```
YESMAN_THRESHOLD=0.5
YESMAN_ALLOWED_USER_IDS=[]
```

**Comment by EuDs63** [comment]
第一次修改

**Comment by EuDs63** [comment]
已填写插件元数据

**Comment by EuDs63** [comment]
修复：无法读取插件元数据

**Comment by EuDs63** [comment]
修复：无法读取插件元数据2

**Comment by yanyongyu** [comment]
你的插件支持tg适配器？看上去只支持onebot v11

**Comment by EuDs63** [comment]
> 你的插件支持tg适配器？看上去只支持onebot v11

已修改，感谢指正
