### ISSUE TITLE
Plugin: VRChat查询

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/nonebot2#2410]
### PyPI 项目名

nonebot-plugin-vrchat

### 插件 import 包名

nonebot_plugin_vrchat

### 标签

[{"label":"VRChat","color":"#7aea53"}]

**Comment by Agnes4m** [comment]
1

**Comment by yanyongyu** [comment]
使用 saa 的话可以通过 `inherit_supported_adapters` 来继承 saa 支持的平台

**Comment by Agnes4m** [comment]
意思是用`inherit_supported_adapters `来替代require吗，不太懂这个，有咩有示例
![image](https://github.com/nonebot/nonebot2/assets/70925546/52d4c043-21f7-4c9d-a9a8-c681ae10de88)

**Comment by yanyongyu** [comment]
直接在元数据里填写 `supported_adapters=inherit_supported_adapters("nonebot_plugin_saa")`

**Comment by Agnes4m** [comment]
修改好了喵

**Comment by Agnes4m** [comment]
上当了，使用`supported_adapters=inherit_supported_adapters("nonebot_plugin_saa")`后，还是有qqguild，然后又通过不了了

**Comment by yanyongyu** [comment]
saa还没发版

**Comment by AzideCupric** [comment]
saa发版了，已经处理adapter-qqguild的问题

**Comment by yanyongyu** [comment]
可以考虑改回去了

**Comment by yanyongyu** [comment]
更新下支持的适配器？

**Comment by Agnes4m** [comment]
已修改
