### ISSUE TITLE
Plugin: BlueArchive Title Generator

### ISSUE THREAD

**Issue by MerCuJerry** [nonebot/nonebot2#2417]
### PyPI 项目名

nonebot-plugin-batitle

### 插件 import 包名

nonebot_plugin_batitle

### 标签

[{"label" : "碧蓝档案", "color" : "#00D7FB"}]

**Comment by RF-Tar-Railt** [comment]
我觉得你这个可以收录进memes插件里面

**Comment by MerCuJerry** [comment]
Update

**Comment by MerCuJerry** [comment]
Update
