### ISSUE TITLE
Plugin: 选择困难症

### ISSUE THREAD

**Issue by SherkeyXD** [nonebot/nonebot2#2427]
### PyPI 项目名

nonebot-plugin-make-choice

### 插件 import 包名

nonebot_plugin_make_choice

### 标签

[{"label": "choice", "color": "#77c5ff"}]

### 插件配置项

```dotenv
CHOOSE_BOTH_CHANCE=0.1
```

**Comment by SherkeyXD** [comment]
已更新

**Comment by he0119** [comment]
试试新版 noneflow。

**Comment by SherkeyXD** [comment]
已更新

**Comment by he0119** [comment]
你应该是把 Config 后面的括号去掉，而不是改一个名字…

**Comment by SherkeyXD** [comment]
草 我是铸币
