### ISSUE TITLE
Bot: Sakiko

### ISSUE THREAD

**Issue by zhaomaoniu** [nonebot/nonebot2#2438]
### 机器人名称

Sakiko

### 机器人描述

基于 LiteLoaderBDS 的 Minecraft 基岩版 Bot

### 机器人项目仓库/主页链接

https://github.com/zhaomaoniu/Sakiko

### 标签

[{"label":"Minecraft","color":"#6cc349"},{"label":"BanGDream","color":"#e70050"}]

**Comment by RF-Tar-Railt** [comment]
客服小祥太拼命了

**Comment by togawa-sakiko** [comment]
你好，立马给我关掉项目，否则我将委托长崎事务所对你提起侵权诉讼😀
