### ISSUE TITLE
Feature: 兼容 pydantic v2

### ISSUE THREAD

**Issue by uf-fipper** [nonebot/nonebot2#2454]
### 希望能解决的问题

pydantic已经升级到v2版本，包括了一些更实用的功能，希望能在nonebot中用到

### 描述所需要的功能

兼容pydantic v2

**Comment by yanyongyu** [comment]
目前由于pydantic-settings的问题无法同时兼容pyd v1和v2

**Comment by RF-Tar-Railt** [comment]
首先一点，nonebot2的内部大量依赖pydantic v1的功能，切换到v2将会造成巨大的破坏性改动
其次，nb周边，包括几乎所有适配器，与巨量的跟随nb使用pydantic v1的插件将同样收到波及。这会是一个巨量的任务
所以来说，迁移到v2，近期推动不了，也无法实现。
你可以等待nonebot的下一个大版本

**Comment by yanyongyu** [comment]
v1和v2同时兼容都好说，主要问题在pydantic settings没法依赖

**Comment by uf-fipper** [comment]
好吧，感谢大佬

**Comment by yanyongyu** [comment]
已于 https://github.com/nonebot/nonebot2/pull/2521 移除 `pydantic-settings` ，可以开始考虑兼容 pyd v2
