### ISSUE TITLE
Bug: Something went wrong

### ISSUE THREAD

**Issue by raindown200709** [nonebot/nonebot2#247]
**描述问题：**

打开bot.py后，出现UnicodeDecodeError:'utf-8' codec can't decode byte 0xc5 in position 80: invalid continuation byte

**如何复现？**

1. 在目录下使用cmd命令：python bot.py

**期望的结果**

希望能迅速修改bug，避免出现错误

**环境信息：**

 - OS: Windows Server 2016
 - Python Version: 3.9.2（3.9.0也有错误）
 - Nonebot Version: 2.0.0a10

**截图**

<img src="https://s3.ax1x.com/2021/02/27/6pMVKg.png" alt="6pMVKg.png" border="0" />

<img src="https://s3.ax1x.com/2021/02/27/6pMK5q.md.jpg" alt="6pMK5q.jpg" border="0" />

**Comment by yanyongyu** [comment]
请使用 `utf-8` 编码保存 `.env` 文件
