### ISSUE TITLE
Feature: 查看已安装插件及版本

### ISSUE THREAD

**Issue by WindStill** [nonebot/nonebot2#2478]
### 希望能解决的问题

列出所有已安装的插件，以及查看已安装插件的版本

### 描述所需要的功能

列出所有已安装的插件，以及查看已安装插件的版本

**Comment by RF-Tar-Railt** [comment]
有没有可能，你的包管理器就能做到

**Comment by he0119** [comment]
欢迎体验 <https://github.com/nonebot/cli-plugin-webui>。

**Comment by WindStill** [comment]
> 欢迎体验 https://github.com/nonebot/cli-plugin-webui。

好的，多谢。
