### ISSUE TITLE
Feature: 支持Graceful Shutdown（等待正在执行的matcher执行完毕后再退出）

### ISSUE THREAD

**Issue by ssttkkl** [nonebot/nonebot2#2479]
### 希望能解决的问题

我有一个提供naga牌谱解析服务的插件 [nonebot-plugin-nagabus](https://github.com/bot-ssttkkl/nonebot-plugin-nagabus) 。解析需要消耗点数，换句话说就是要给naga送钱。所以希望退出时等待用户请求处理完毕再退出，否则用户消耗了点数又没拿到结果。

### 描述所需要的功能

当用户退出时，不希望打断当前正在执行的matcher，希望能够等待执行完毕后再退出

目前是通过hook丑陋地实现的（ https://github.com/bot-ssttkkl/ssttkkl-nonebot-utils/blob/master/ssttkkl_nonebot_utils/interceptor/with_graceful_shutdown.py ），希望nb官方能够提供支持

**Comment by yanyongyu** [comment]
这个问题其实在之前改到结构化并发的时候就实现了，但是由于anyio的问题，这个分支最后被废弃了

**Comment by shoucandanghehe** [comment]
我的插件目前通过`hook signal handler`实现了 欢迎测试（
https://github.com/shoucandanghehe/nonebot-plugin-wait-a-minute

用法：
```python
require('nonebot_plugin_wait_a_minute')

from nonebot_plugin_wait_a_minute import graceful

@foo.handle()
@graceful()  # ← Add the decorator below the handle decorator
async def _():
    await foo.send('foo')
```

**Comment by ssttkkl** [comment]
> 我的插件目前通过`hook signal handler`实现了 欢迎测试（ https://github.com/shoucandanghehe/nonebot-plugin-wait-a-minute

我现在是注册了个on_shutdown的回调在里面await没执行完成的任务实现的（

https://github.com/bot-ssttkkl/ssttkkl-nonebot-utils/blob/master/ssttkkl_nonebot_utils/interceptor/with_graceful_shutdown.py

**Comment by yanyongyu** [comment]
在 #3053 中，迁移 nb 至结构化并发框架，经过对比各类驱动器实现（如 uvicorn），在 graceful shutdown 时均采用直接断开连接的方式。因此，此时再等待 matcher 执行完毕已经没有意义。同时，cancel 正在执行中的 task 并等待结束也是符合逻辑的 graceful shutdown。暂时不考虑支持在不断开连接的情况下等待 matcher 执行完毕。

**Comment by shoucandanghehe** [comment]
所以可以来用我的插件，阻止驱动器进行shutdown，达成等待matcher运行完成后再shutdown（
https://github.com/shoucandanghehe/nonebot-plugin-wait-a-minute
