### ISSUE TITLE
Plugin: ba塔罗牌，运势与魔法占卜！

### ISSUE THREAD

**Issue by Perseus037** [nonebot/nonebot2#2480]
### PyPI 项目名

nonebot-plugin-batarot

### 插件 import 包名

nonebot_plugin_batarot

### 标签

[{"label":"碧蓝档案","color":"#15a0df"}]

**Comment by Perseus037** [comment]
test 4

**Comment by Perseus037** [comment]
t

**Comment by yanyongyu** [comment]
你这依赖是什么鬼啊
<img width="190" alt="image" src="https://github.com/nonebot/nonebot2/assets/42488585/72680fb1-3660-466d-ab4e-999eda335e27">

**Comment by XieXiLin2** [comment]
估计手打的（
why not pdm

**Comment by Perseus037** [comment]
别骂了别骂了
