### ISSUE TITLE
Plugin: AntiMonkey

### ISSUE THREAD

**Issue by phquathi** [nonebot/nonebot2#2500]
### PyPI 项目名

nonebot-plugin-antimonkey

### 插件 import 包名

nonebot_plugin_antimonkey

### 标签

[{"label":"猴子","color":"#ea5252"},{"label":"群管","color":"#ea5252"}]

### 插件配置项

_No Response_

**Comment by phquathi** [comment]
已更新

**Comment by phquathi** [comment]
更新了😭重测一下吧😭测测我的

**Comment by phquathi** [comment]
已更新

**Comment by yanyongyu** [comment]
你插件不是已经发布了吗，你要看测试结果的话请到 https://registry.nonebot.dev

**Comment by phquathi** [comment]
我还以为是发一次它才测一次咧
