### ISSUE TITLE
Plugin: 最终台词

### ISSUE THREAD

**Issue by Perseus037** [nonebot/nonebot2#2522]
### PyPI 项目名

nonebot-plugin-finallines

### 插件 import 包名

nonebot_plugin_finallines

### 标签

[{"label":"最终台词","color":"#052199"}]

**Comment by yanyongyu** [comment]
看上去插件是可以支持全平台的吧，能否做个适配

**Comment by Perseus037** [comment]
好，我待会改一下

**Comment by lgc2333** [comment]
https://github.com/noneplugin/nonebot-plugin-userinfo

**Comment by Perseus037** [comment]
新发的包已经改好了，用了nonebot-plugin-userinfo获取全平台用户昵称，nonebot-plugin-saa发消息w

**Comment by yanyongyu** [comment]
你可以用nb的inherit supported adapters来继承userinfo和saa插件支持适配器的交集，而不是手写

**Comment by Perseus037** [comment]
saa的少supported adapters，直接用saa的了，新发的包已改好

**Comment by RF-Tar-Railt** [comment]
你只发文字没必要用到saa吧

**Comment by AzideCupric** [comment]
如果只需要发纯文字的话，并不需要这些跨平台发送的插件的

**Comment by Perseus037** [comment]
以后有空加个用saa渲染发图的功能吧，懒得改了，去打瓦了

**Comment by yanyongyu** [comment]
首先你导入saa插件没有用require，另外你好像并没有发布到pypi

**Comment by Perseus037** [comment]
已经使用了 inherit_supported_adapters来取交集，已发pypi，测试喵

**Comment by Perseus037** [comment]
test

**Comment by yanyongyu** [comment]
是不是没发布到pypi
