### ISSUE TITLE
Plugin: 谷歌Bard聊天

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#2528]
### PyPI 项目名

nonebot-plugin-bard

### 插件 import 包名

nonebot_plugin_bard

### 标签

[]

### 插件配置项

```dotenv
BARD_TOKEN=xxxxxxxxxx
```

**Comment by Alpaca4610** [comment]
update

**Comment by yanyongyu** [comment]
请使用异步代码防止卡住机器人哦，可以使用 `bardapi` 的 `BardAsync`

**Comment by Alpaca4610** [comment]
> 请使用异步代码防止卡住机器人哦，可以使用 `bardapi` 的 `BardAsync`

插件已经做了异步处理，测试过不会卡住机器人😀
