### ISSUE TITLE
Plugin: nonebot-plugin-mypower

### ISSUE THREAD

**Issue by tianyisama** [nonebot/nonebot2#2530]
### PyPI 项目名

nonebot-plugin-mypower

### 插件 import 包名

nonebot_plugin_mypower

### 标签

[]

### 插件配置项

_No Response_

**Comment by tianyisama** [comment]
try again please

**Comment by tianyisama** [comment]
try again please，write this for the first time

**Comment by tianyisama** [comment]
again

**Comment by AzideCupric** [comment]
有写插件元数据吗
https://nonebot.dev/docs/next/developer/plugin-publishing#填写插件元数据

**Comment by tianyisama** [comment]
again

**Comment by tianyisama** [comment]
> 有写插件元数据吗 [https://nonebot.dev/docs/next/developer/plugin-publishing#填写插件元数据](https://nonebot.dev/docs/next/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE)

thanks for your reply，now I have added
