### ISSUE TITLE
Plugin: 随机发送图片

### ISSUE THREAD

**Issue by HuParry** [nonebot/nonebot2#2547]
### PyPI 项目名

nonebot-plugin-randpic

### 插件 import 包名

nonebot_plugin_randpic

### 标签

[]

### 插件配置项

```dotenv
RANDPIC_COMMAND_LIST=["capoo"]
```

**Comment by HuParry** [comment]
重新测试

**Comment by HuParry** [comment]
已更新至最新检查结果

**Comment by yanyongyu** [comment]
插件依赖里不需要asyncio，另外插件数据请考虑使用[localstore](https://nonebot.dev/docs/best-practice/data-storing)插件获取存储路径，而不是直接存在当前目录下

**Comment by yanyongyu** [comment]
你的插件插件依赖里是不是缺了onebot适配器

**Comment by HuParry** [comment]
已更新至最新检查结果
