### ISSUE TITLE
Plugin: BA模拟抽卡

### ISSUE THREAD

**Issue by lengmianzz** [nonebot/nonebot2#2549]
### PyPI 项目名

nonebot-plugin-badrawcard

### 插件 import 包名

nonebot_plugin_BAdrawcard

### 标签

[]

### 插件配置项

_No Response_

**Comment by lengmianzz** [comment]
update

**Comment by lengmianzz** [comment]
update

**Comment by yanyongyu** [comment]
插件依赖里的httpx的extras写错了

**Comment by yanyongyu** [comment]
修改完记得发布到pypi

**Comment by lengmianzz** [comment]
> 修改完记得发布到pypi

已同步
