### ISSUE TITLE
Plugin: 黑名单插件

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#2553]
### PyPI 项目名

nonebot-plugin-easy-blacklist

### 插件 import 包名

nonebot_plugin_easy_blacklist

### 标签

[]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
请勿在机器人目录下随意存储数据文件，请使用 [localstore](https://nonebot.dev/docs/best-practice/data-storing) 文件存储插件或给用户提供配置存储路径的方式。另外，在导入apscheduler插件之前需要使用[require](https://nonebot.dev/docs/advanced/requiring#%E6%8F%92%E4%BB%B6%E4%BE%9D%E8%B5%96%E5%A3%B0%E6%98%8E)

**Comment by bingqiu456** [comment]
已经修改

**Comment by yanyongyu** [comment]
看上去你的scheduler部分还没有修改？

**Comment by bingqiu456** [comment]
GitHub忘记改代码了，抱歉

**Comment by yanyongyu** [comment]
从你的`__init__.py`来看，你的插件其他模块全都没有被导入加载啊，命令都没有生效

**Comment by bingqiu456** [comment]
已修改

**Comment by bingqiu456** [comment]
改完了？
