### ISSUE TITLE
Plugin: 定时提醒

### ISSUE THREAD

**Issue by velor2012** [nonebot/nonebot2#2557]
### PyPI 项目名

nonebot-plugin-reminder

### 插件 import 包名

nonebot_plugin_reminder

### 标签

[{"label":"scheduler","color":"#ea5252"}]

### 插件配置项

```dotenv
REMINDER_DEFAULT_HOUR=17
REMINDER_DEFAULT_MINUTE=0
REMINDER_ID_LEN=5
REMINDER_ID_PREFIX=reminder
```

**Comment by velor2012** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-reminder
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 标签: 解码失败。请确保其为 JSON 格式。* ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-reminder 的信息如下：
>        name         : nonebot-plugin-reminder 
>        version      : 0.1.0                   
>        description  :                         
>       
>       dependencies
>        - chinese-calendar >=1.9.0,<2.0.0
>        - nonebot >=1.9.1,<2.0.0
>        - nonebot-adapter-onebot >=2.3.1,<3.0.0
>        - nonebot2 >=2.1.3,<3.0.0
>   插件 nonebot-plugin-reminder 依赖的插件如下：
>       
>   插件 nonebot-plugin-reminder 加载出错：
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/runner.py", line 4, in <module>
>           from nonebot import init, load_plugin, require, logger
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 140, in <module>
>           from .command import CommandSession, CommandGroup
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/command/__init__.py", line 930, in <module>
>           from nonebot.command.group import CommandGroup
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/command/group.py", line 3, in <module>
>           from nonebot.plugin import on_command
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/plugin/__init__.py", line 111, in <module>
>           from .on import on as on
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/plugin/on.py", line 15, in <module>
>           from nonebot.adapters import Event
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/adapters/__init__.py", line 10, in <module>
>           from nonebot.internal.adapter import Bot as Bot
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/__init__.py", line 1, in <module>
>           from .bot import Bot as Bot
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 9, in <module>
>           from nonebot.typing import T_CalledAPIHook, T_CallingAPIHook
>       ImportError: cannot import name 'T_CalledAPIHook' from 'nonebot.typing' (/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-reminder-nonebot-plugin-reminder-test/.venv/lib/python3.10/site-packages/nonebot/typing.py)
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

1

**Comment by velor2012** [comment]
已更新3

**Comment by velor2012** [comment]
已更新4

**Comment by velor2012** [comment]
已更新5

**Comment by yanyongyu** [comment]
请勿在机器人目录下随意存储数据文件，请使用 [localstore](https://nonebot.dev/docs/best-practice/data-storing) 文件存储插件或给用户提供配置存储路径的方式。

**Comment by velor2012** [comment]
> 请勿在机器人目录下随意存储数据文件，请使用 [localstore](https://nonebot.dev/docs/best-practice/data-storing) 文件存储插件或给用户提供配置存储路径的方式。

已进行调整

**Comment by yanyongyu** [comment]
另外提醒一下你的config写法使用了pydantic的BaseSetting，这个在下一个版本里已经不会支持，你可以直接使用BaseModel或者限制pydantic版本为`^1.10`

**Comment by velor2012** [comment]
> BaseModel

ok, 已调整，感谢大佬
