### ISSUE TITLE
Bug: _build_secrets_files函数不存在？

### ISSUE THREAD

**Issue by woodcoding** [nonebot/nonebot2#256]
**描述问题：**

你好，我在使用nb-cli创建项目后启动，提示TypeError: 'NoneType' object is not callable，发现nonebot源码中config.py文件的53行中调用了self._build_secrets_files函数，但是这个函数似乎并未在项目中存在？把这个函数删除后程序运行正常，但是不知是否有其他影响？

**如何复现？**

使用最新版本的nb-cli创建项目并运行

**期望的结果**

正常运行

**环境信息：**

 - OS: Win10
 - Python Version: 3.7
 - Nonebot Version: 2.0.0a10

**截图**

**Comment by yanyongyu** [comment]
该问题由pydantic新版本的breaking change导致，已修复。

work around：降级pydantic至`1.7.3`
