### ISSUE TITLE
Plugin: Chikari_yinpa

### ISSUE THREAD

**Issue by mrqx0195** [nonebot/nonebot2#2571]
### PyPI 项目名

nonebot-plugin-chikari-yinpa

### 插件 import 包名

nonebot_plugin_chikari_yinpa

### 标签

[{"label":"yinpa","color":"#ffff00"}]

**Comment by mrqx0195** [comment]
已更新

**Comment by mrqx0195** [comment]
已更新

**Comment by mrqx0195** [comment]
已更新

**Comment by lgc2333** [comment]
只有py 3.12支持f-string嵌套引号

**Comment by mrqx0195** [comment]
已更新

**Comment by lgc2333** [comment]
如果你使用vscode开发，建议将pyright的targetVersion配置为你想要支持的Python版本

`pyproject.toml`:

```toml
[tool.pyright]
pythonVersion = "3.9"
```

**Comment by mrqx0195** [comment]
已更新

**Comment by mrqx0195** [comment]
已更新

**Comment by mrqx0195** [comment]
已更新

**Comment by mrqx0195** [comment]
已更新

**Comment by yanyongyu** [comment]
你的插件为什么要限制nonebot的版本小于2.2.0¿
