### ISSUE TITLE
Plugin: 运行状态

### ISSUE THREAD

**Issue by KomoriDev** [nonebot/nonebot2#2586]
### PyPI 项目名

nonebot-plugin-kawaii-status

### 插件 import 包名

nonebot_plugin_kawaii_status

### 标签

[{"label":"简约","color":"#54adff"},{"label":"可爱","color":"#ffb3cc"}]

**Comment by KomoriDev** [comment]
fix

**Comment by KomoriDev** [comment]
👉🏻👈🏻

**Comment by yanyongyu** [comment]
supported adapters应该用inherit而不是直接import然后使用哦，至少要用import as不然污染变量域。

**Comment by KomoriDev** [comment]
谢谢提醒，已更新
