### ISSUE TITLE
Bug: 在使用Minecraft适配器时出现错误

### ISSUE THREAD

**Issue by MingriLingran** [nonebot/nonebot2#2588]
### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

1.3.1

### 适配器

Minecraft 1.0.8

### 协议端

无需

### 描述问题

在加载Minecraft适配器时pydantic出现问题

### 复现步骤

1. 正常安装nonebot
2. 创建项目时适配器选择Minecraft
3. 其余参数默认
4. 正常启动即可复现

### 期望的结果

正常加载Minecraft适配器

### 截图或日志

![image](https://github.com/nonebot/nonebot2/assets/99112592/dfbd9116-3cd0-4ffa-a38b-cfd694083127)

**Comment by RF-Tar-Railt** [comment]
你可以去适配器仓库那里提这个issue

**Comment by yanyongyu** [comment]
适配器尚未支持pydantic v2，你可以激活虚拟环境后使用 `pip install --force-reinstall 'pydantic~=1.10'` 降级 pydantic
