### ISSUE TITLE
Plugin: 人性化的ChatGLM

### ISSUE THREAD

**Issue by XTxiaoting14332** [nonebot/nonebot2#2591]
### PyPI 项目名

nonebot-plugin-chatglm-plus

### 插件 import 包名

nonebot_plugin_chatglm_plus

### 标签

[{"label":"ChatGLM","color":"#73cccc"}]

### 插件配置项

_No Response_

**Comment by XTxiaoting14332** [comment]
已添加依赖

**Comment by XTxiaoting14332** [comment]
已使用require导入session

**Comment by yanyongyu** [comment]
插件内使用了nb 2.2.0+ 的配置读取方式，请注意在依赖中提升版本限制。数据存储目录请不要随意存放在机器人目录下，请使用[localhost插件](https://nonebot.dev/docs/best-practice/data-storing)，或为用户提供配置项进行选择。请求接口请勿使用同步方法，请使用`httpx.AsyncClient`。

**Comment by XTxiaoting14332** [comment]
已使用localstore插件储存聊天记录
已指定依赖为Nonoebot2.2.0

**Comment by yanyongyu** [comment]
记得修改同步请求为异步方法，否则会卡住机器人。另外看到你的supported adapters是手写的，如果你是继承session插件的支持列表，你可以使用：[`inherit_supported_adapters("nonebot_plugin_session")`](https://nonebot.dev/docs/api/plugin/load#inherit-supported-adapters)

**Comment by XTxiaoting14332** [comment]
已使用httpx.AsyncClient进行异步请求
已将适配器支持列表改为inherit_supported_adapters("nonebot_plugin_session")
