### ISSUE TITLE
Plugin: 赛博钓鱼

### ISSUE THREAD

**Issue by C14H22O** [nonebot/nonebot2#2593]
### PyPI 项目名

nonebot-plugin-fishing

### 插件 import 包名

nonebot_plugin_fishing

### 标签

[{"label":"钓鱼","color":"#87cefa"}]

**Comment by C14H22O** [comment]
再试试

**Comment by C14H22O** [comment]
再试试

**Comment by C14H22O** [comment]
fixed

**Comment by C14H22O** [comment]
再试试

**Comment by C14H22O** [comment]
更新了吗

**Comment by C14H22O** [comment]
啊

**Comment by yanyongyu** [comment]
asyncio 不需要写在插件依赖里。另外看你没有用到pydantic版本相关的方法，可以考虑降低版本限制到`1.10+`，防止用户无法在低版本使用插件。数据库相关内容也可以考虑使用 `nonebot-plugin-orm` 插件来管理。

**Comment by C14H22O** [comment]
好，我修改一下

**Comment by C14H22O** [comment]
> asyncio 不需要写在插件依赖里。另外看你没有用到pydantic版本相关的方法，可以考虑降低版本限制到`1.10+`，防止用户无法在低版本使用插件。数据库相关内容也可以考虑使用 `nonebot-plugin-orm` 插件来管理。

asyncio 依赖已经移除了。但是我目前使用的是 pdm，请问如何降低 pydantic 版本。
数据库相关内容会在下一个大版本中重写。

**Comment by yanyongyu** [comment]
在你的pyproject.toml里修改版本

**Comment by C14H22O** [comment]
@yanyongyu 你好，请问这个插件还有什么问题吗
