### ISSUE TITLE
Plugin: nonebot-plugin-vits-tts

### ISSUE THREAD

**Issue by Redmomn** [nonebot/nonebot2#2594]
### PyPI 项目名

nonebot-plugin-vits-tts

### 插件 import 包名

nonebot_plugin_vits_tts

### 标签

[{"label":"VITS","color":"#ea5252"},{"label":"TTS","color":"#52dbea"}]

### 插件配置项

```dotenv
VITS__DEVIC=0
VITS__VMODEL_PATH=models
VITS__AT_BOT=false
VITS__COOLDOWN=0
VITS__VMODEL_FILE_NAME=model.pth
VITS__CONFIG_FILE_NAME=config
VITS__TENCENT_SECRET_ID=
VITS__TENCENT_SECRET_KEY=
VITS__DEFAULT_LENGTH_SCALE=1
VITS__DEFAULT_NOISE_SCALE=0.667
VITS__DEFAULT_NOISE_SCALE_W=0.6
```

**Comment by Redmomn** [comment]
已更新依赖

**Comment by yanyongyu** [comment]
你的插件需要这么多依赖吗？这些都是你的插件的直接依赖？

```python
install_requires=[
    'Cython',
    'torch',
    'torchvision',
    'torchaudio',
    'numpy>=1.22.0',
    'scipy',
    'regex',
    'cn2an',
    'opencc',
    'inflect',
    'unidecode',
    'eng_to_ipa',
    'pyopenjtalk-prebuilt',
    'jamo',
    'ko_pron',
    'pypinyin',
    'jieba',
    'indic_transliteration',
    'num_thai',
    'pydub',
    'numba',
    'tencentcloud-sdk-python-tmt',
    'langdetect',
    'nonebot-adapter-onebot>=2.0.0',
    'nonebot2>=2.0.0'
]
```

**Comment by Redmomn** [comment]
> 你的插件需要这么多依赖吗？这些都是你的插件的直接依赖？
> 
> ```python
> install_requires=[
>     'Cython',
>     'torch',
>     'torchvision',
>     'torchaudio',
>     'numpy>=1.22.0',
>     'scipy',
>     'regex',
>     'cn2an',
>     'opencc',
>     'inflect',
>     'unidecode',
>     'eng_to_ipa',
>     'pyopenjtalk-prebuilt',
>     'jamo',
>     'ko_pron',
>     'pypinyin',
>     'jieba',
>     'indic_transliteration',
>     'num_thai',
>     'pydub',
>     'numba',
>     'tencentcloud-sdk-python-tmt',
>     'langdetect',
>     'nonebot-adapter-onebot>=2.0.0',
>     'nonebot2>=2.0.0'
> ]
> ```

是的，这个插件是基于[Plachtaa/VITS-fast-fine-tuning](https://github.com/Plachtaa/VITS-fast-fine-tuning)这个项目，只保留了推理相关的功能，多余的依赖已经全部删掉了

**Comment by yanyongyu** [comment]
cython什么的都不是推理相关的吧，你确定都是你的插件直接依赖吗

**Comment by Redmomn** [comment]
cython现在好像不需要了，之前是用来编译一个库的，现在用numba解决了
```
cn2an',
'opencc',
'inflect',
'unidecode',
'eng_to_ipa',
'pyopenjtalk-prebuilt',
'jamo',
'ko_pron',
'pypinyin',
'jieba',
'indic_transliteration',
'num_thai',
```
这几个是处理语言的库，毕竟是合成语音，得先把文本符号化，支持的语言有好几种，依赖也就多了
其他的就一些深度学习的库和一些小工具库，
