### ISSUE TITLE
Bug: 某些情况下require包有概率出现报错

### ISSUE THREAD

**Issue by eya46** [nonebot/nonebot2#2597]
### 操作系统

Windows

### Python 版本

3.11

### NoneBot 版本

2.2.1

### 适配器

None

### 协议端

None

### 描述问题

在`load_plugins`加载的插件中, 用(例如此处是yyy插件) `require`以绝对地址(?): `src.plugins.xxx` 导包 有概率会触发异常`RuntimeError: Plugin already exists: xxx! Check your plugin name`
(触发是概率性的, 在nb优先导入了xxx包后,yyy插件能顺利 `require`)

bug原因应该是
https://github.com/nonebot/nonebot2/blob/master/nonebot/plugin/load.py#L172
```python
def require(name: str) -> ModuleType:
    ...
    if not plugin:
        # plugin already declared
        if manager := _find_manager_by_name(name):
```
这里name是`src.plugins.xxx`, 然而 `_find_manager_by_name` 函数中 `if name in manager.plugins or name in manager.searched_plugins:` 都是经过 `_module_name_to_plugin_name` 处理后的, 例如 `xxx`
这导致再次 `load_plugin` 从而跑到 `prepare_plugins` 报 `RuntimeError`

尝试改了下`_find_manager_by_name`和`manager.load_plugin` 加 `_module_name_to_plugin_name` 
我的插件能正常导入, 但改完后 `test_require_not_loaded` 测试跑不过
接着想去改manager.plugins, 加个`_module_name_to_plugin_name`, 但可能会出 #2538 的问题. 搞不懂了

### 复现步骤

bot.py
```python
nonebot.load_plugins("src/plugins")
```

src/plugins.yyy.py
...

src/plugins.xxx.py
```python
from nonebot import require
require("src.plugins.yyy")
```

### 截图或日志

![image](https://github.com/nonebot/nonebot2/assets/61458340/4a559d50-6d9a-4a89-92e9-d5280c83e2d1)

![image](https://github.com/nonebot/nonebot2/assets/61458340/cdf427c5-77fa-45f2-bea6-e3cd5ecc4194)

![image](https://github.com/nonebot/nonebot2/assets/61458340/b8542a87-dbd2-4398-b9f1-b621c504e1fe)

![image](https://github.com/nonebot/nonebot2/assets/61458340/47d84025-6a77-4796-8e60-7061e10e39af)

**Comment by yanyongyu** [comment]
本地插件其实不推荐使用require，因为本身就会一起加载，如果是手动控制的加载更不需要担心顺序问题。这里判断可能还需要优化一下。
