### ISSUE TITLE
Plugin: 100orangejuice

### ISSUE THREAD

**Issue by GLDYM** [nonebot/nonebot2#2600]
### PyPI 项目名

nonebot-plugin-orangejuice

### 插件 import 包名

nonebot_plugin_orangejuice

### 标签

[{"label":"百橙","color":"#ed6f00"},{"label":"100OJ","color":"#ed6f00"}]

### 插件配置项

```.env
OJ_DATA_PATH="data/100oj"
```

**Comment by GLDYM** [comment]
1

**Comment by GLDYM** [comment]
1

**Comment by yanyongyu** [comment]
虽然但是，你为什么把数据库ip port user password都写在插件里了，在插件里你可以使用 [plugin-orm](https://github.com/nonebot/plugin-orm) 之类的插件将数据存储在用户本地数据库内。

**Comment by GLDYM** [comment]
> 虽然但是，你为什么把数据库ip port user password都写在插件里了这是很危险的事情建议立即删库跑路（，在插件里你可以使用 [plugin-orm](https://github.com/nonebot/plugin-orm) 之类的插件将数据存储在用户本地数据库内。

请仔细查看Sorabot的原文档，这是一个完全公开的数据库，guest只有SELECT权限。并且这个数据库大小非常大不适合放在本地。

**Comment by yanyongyu** [comment]
那建议你使用支持异步的库进行数据库操作，比如aiomysql、asyncmy、sqlalchemy之类的，远程数据库使用同步会很容易卡住机器人

**Comment by GLDYM** [comment]
> 那建议你使用支持异步的库进行数据库操作，比如aiomysql、asyncmy、sqlalchemy之类的，远程数据库使用同步会很容易卡住机器人

下次一定（bushi）

**Comment by yanyongyu** [comment]
另外用户数据的话请不要随意存储到用户机器人目录下，请提供配置项或者使用[localstore插件](https://nonebot.dev/docs/best-practice/data-storing)进行存储

**Comment by GLDYM** [comment]
0.3.0版本已更新，提供储存用户数据目录的配置项。

**Comment by yanyongyu** [comment]
插件测试未通过，请参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)使用 pydantic 兼容方法或者请在插件依赖中限制pydantic版本为v1，以及你的插件元数据漏了config

**Comment by GLDYM** [comment]
这次一定
![starb02](https://github.com/nonebot/nonebot2/assets/49135577/cb0ce9bc-6952-4fa2-aaea-ad959843eb3e)
