### ISSUE TITLE
Plugin: a2s查询

### ISSUE THREAD

**Issue by NanakaNeko** [nonebot/nonebot2#2602]
### PyPI 项目名

nonebot-plugin-a2s-query

### 插件 import 包名

nonebot_plugin_a2s_query

### 标签

[{"label":"游戏服务器","color":"#ea5252"},{"label":"value","color":"#99ea52"}]

**Comment by NanakaNeko** [comment]
test

**Comment by NanakaNeko** [comment]
test

**Comment by NanakaNeko** [comment]
1

**Comment by NanakaNeko** [comment]
test

**Comment by NanakaNeko** [comment]
test

**Comment by NanakaNeko** [comment]
test

**Comment by yanyongyu** [comment]
插件的数据不要存储在插件目录下，这样会导致pip卸载插件时存在残留，建议使用[localstore插件](https://nonebot.dev/docs/best-practice/data-storing)

**Comment by NanakaNeko** [comment]
> 插件的数据不要存储在插件目录下，这样会导致pip卸载插件时存在残留，建议使用[localstore插件](https://nonebot.dev/docs/best-practice/data-storing)

已经修改了

**Comment by NanakaNeko** [comment]
1
