### ISSUE TITLE
Plugin: 人类友好数据配置

### ISSUE THREAD

**Issue by QuanhuZeYu** [nonebot/nonebot2#2615]
### PyPI 项目名

nonebot-plugin-humanaticstore

### 插件 import 包名

nonebot_plugin_humanaticstore

### 标签

[{"label":"config","color":"#ea5252"},{"label":"配置工具","color":"#ea5252"}]

**Comment by QuanhuZeYu** [comment]
修改issue

**Comment by QuanhuZeYu** [comment]
test

**Comment by QuanhuZeYu** [comment]
更新

**Comment by QuanhuZeYu** [comment]
更新

**Comment by QuanhuZeYu** [comment]
0.1.2

**Comment by XieXiLin2** [comment]
包名填错了，应把 `-` 改为 `_`

**Comment by QuanhuZeYu** [comment]
> 包名填错了，应把 `-` 改为 `_`

呜呜呜太感谢了，搞了半天都不知道是怎么回事

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nb-cli-plugin-bootstrap/blob/7c0b91822f6d7acdb8802fa78d8094db556f81d0/nb_cli_plugin_bootstrap/templates/bootstrap/%7B%7Bcookiecutter.nonebot.folder_name%7D%7D/.env.prod#L9-L12

**Comment by yanyongyu** [comment]
你似乎没有在pyproject里注册插件为nb cli的命令
