### ISSUE TITLE
Plugin: diffsinger

### ISSUE THREAD

**Issue by zhzhongshi** [nonebot/nonebot2#2624]
### PyPI 项目名

nonebot-plugin-diffsinger

### 插件 import 包名

nonebot_plugin_diffsinger

### 标签

[{"label":"diffsinger","color":"#c24444"}]

### 插件配置项

_No Response_

```[tasklist]
### Tasks
- [x] add config
- [x] async
- [x] test
- [ ] readme
- [x] config
- [x] migrate to pyproject.toml
```

**Comment by zhzhongshi** [comment]
忘了改元数据了= =

**Comment by zhzhongshi** [comment]
再试试（我就不信了

**Comment by zhzhongshi** [comment]
QAQ

**Comment by modcrafts** [comment]
QAQ

**Comment by zhzhongshi** [comment]
我测了一顿，好多问题QAQ

**Comment by yanyongyu** [comment]
插件元数据里漏了config，插件依赖里需要`nonebot2>=2.2.0,<3.0.0`
