### ISSUE TITLE
Bug: 插件初始化提示：搜索路径重复

### ISSUE THREAD

**Issue by Kyomotoi** [nonebot/nonebot2#263]
**描述问题：**

在a10版本之前能正常跑的插件到了>=a10启动，初始化后报错，
但在启动uvicorn后又能成功加载
提示：Duplicate plugin search path!
错误文件：essential.py

**如何复现？**

拿下面的源码贴到项目插件目录下

**期望的结果**

正常加载目标插件

**环境信息：**

 - OS: Windows10
 - Python Version: 3.8.5
 - Nonebot Version: 2.0.0a11

**截图**

对应文件源码：https://paste.ubuntu.com/p/5nrbKz3YZs/
对应log：https://paste.ubuntu.com/p/YbxYSb4R2d/
项目目录：
![image.png](https://i.loli.net/2021/03/06/OjmdXPZsAlw9ahQ.png)

**Comment by yanyongyu** [comment]
这问题是你的代码导致的，加载了两遍插件

> File "ATRI/plugins\essential.py", line 28, in <module>
>    from main import driver

**Comment by Kyomotoi** [comment]
感谢，问题解决了，是我疏忽了（
