### ISSUE TITLE
Plugin: Chikari_economy

### ISSUE THREAD

**Issue by mrqx0195** [nonebot/nonebot2#2630]
### PyPI 项目名

nonebot-plugin-chikari-economy 

### 插件 import 包名

nonebot_plugin_chikari_economy

### 标签

[{"label":"经济","color":"#adad73"}]

**Comment by KomoriDev** [comment]
Readme 的开发者部分存在错误
应该先 `require` 再进行 `import`
```python
require("nonebot_plugin_chikari_economy")
import nonebot_plugin_chikari_economy
```

**Comment by yanyongyu** [comment]
除了readme的小问题 其他没啥问题
