### ISSUE TITLE
Adapter: RocketChat

### ISSUE THREAD

**Issue by IllTamer** [nonebot/nonebot2#2636]
### 适配器名称

RocketChat

### 适配器描述

RocketChat adapter for nonebot2

### PyPI 项目名

nonebot-adapter-rocketchat

### 适配器 import 包名

nonebot.adapters.rocketchat

### 适配器项目仓库/主页链接

https://github.com/IUnlimit/nonebot-adapter-rocketchat

### 标签

[]

**Comment by yanyongyu** [comment]
另外请在nb仓库README支持的协议部分添加一下相关信息，可以参考已有内容的格式，单独开一个新的PR

**Comment by RF-Tar-Railt** [comment]
#2435 你可以阅读参考一下这个

以及请问后续你有打算完善消息段吗，我看你目前只写了text但是注释里已经有emoji，mention等元素了

**Comment by IllTamer** [comment]
> @IllTamer 另外请在nb仓库README支持的协议部分添加一下相关信息，可以参考已有内容的格式，单独开一个新的PR

好的，感谢您的审查，我会在规范代码后更新 README 并重新 pr

**Comment by yanyongyu** [comment]
> 好的，感谢您的审查，我会在规范代码后更新 README 并重新 pr

不需要重新提交 issue，更新 README 直接新开一个 pr 即可

**Comment by IllTamer** [comment]
> #2435 你可以阅读参考一下这个
> 
> 以及请问后续你有打算完善消息段吗，我看你目前只写了text但是注释里已经有emoji，mention等元素了

感谢您的分享。

我后续会陆续完善其他监听事件的转换。事实上，Rocket.Chat 的消息发送格式较为特殊：对于支持文本内解析的消息段（如 emoji，@ 类型消息等），我会在后续更新中增加对应消息段的构建方法；对于期望发送其他类型消息的开发者，他们应该通过调用对应平台 API 的方式来实现，而非寄希望于适配器支持解析类似 onebot 协议的消息段。

以上是我的观点，如果您有任何好的想法，我也很愿意进一步交流^ω^

**Comment by RF-Tar-Railt** [comment]
> > #2435 你可以阅读参考一下这个
> > 
> > 以及请问后续你有打算完善消息段吗，我看你目前只写了text但是注释里已经有emoji，mention等元素了
> 
> 感谢您的分享。
> 
> 我后续会陆续完善其他监听事件的转换。事实上，Rocket.Chat 的消息发送格式较为特殊：对于支持文本内解析的消息段（如 emoji，@ 类型消息等），我会在后续更新中增加对应消息段的构建方法；对于期望发送其他类型消息的开发者，他们应该通过调用对应平台 API 的方式来实现，而非寄希望于适配器支持解析类似 onebot 协议的消息段。
> 
> 以上是我的观点，如果您有任何好的想法，我也很愿意进一步交流^ω^

能够发送基础的那些消息内容（文字，emoji，@，图片）就好了，并不是强制要求所有类型消息都要塞在MessageSegment

**Comment by yanyongyu** [comment]
@IllTamer 请在NB仓库README里添加一下适配器信息，开PR即可

**Comment by yanyongyu** [comment]
@IllTamer 适配器在启动的时候应该使用`self.on_ready`来处理setup的情况
