### ISSUE TITLE
Plugin: nonebot-plugin-nai3

### ISSUE THREAD

**Issue by zhulinyv** [nonebot/nonebot2#2638]
### PyPI 项目名

nonebot-plugin-nai3

### 插件 import 包名

nonebot_plugin_nai3

### 标签

[{"label":"NovelAI","color":"#35F139"}]

### 插件配置项

```dotenv
NAI3_TOKEN="xxx"
SMMS_TOKEN="xxx"
```

**Comment by yanyongyu** [comment]
你的插件元数据缺少了config，type不正确，应该为`application`。插件配置的读取采用了过时的方法，应该使用`get_plugin_config`

**Comment by zhulinyv** [comment]
已改

**Comment by yanyongyu** [comment]
看上去你的插件并不支持ob v12，你确定你的插件支持么？

**Comment by zhulinyv** [comment]
元数据中移除了不受支持的适配器.

脱离 nb 有一段时间了, 写的时候直接 copy 了别人的 metadata, 没注意到这个 💦

![3cfe559ea1dc72a11f3e5bee4139c863](https://github.com/nonebot/nonebot2/assets/66541860/79a77062-c53e-485f-bd89-abbd2717d9c5)

**Comment by yanyongyu** [comment]
插件加载报错了，看上去是因为smms在外层实例化

**Comment by zhulinyv** [comment]
修改了实例化位置 🧐

**Comment by zhulinyv** [comment]
添加了必要配置

**Comment by he0119** [comment]
NoneFlow 已更新。
