### ISSUE TITLE
Bug: 启动 nb 时无法导入模块 `nonebot.log`

### ISSUE THREAD

**Issue by WindLeaf233** [nonebot/nonebot2#264]
**描述问题：**

启动 nb 报错: ModuleNotFoundError: No module named 'nonebot.log'

**如何复现？**

1. $ pip3 install nb-cli
2. $ nb
3. 报错

**期望的结果**

显示 NoneBot logo, 并且可以正常创建项目和运行

**环境信息：**

 - OS: Linux Ubuntu 18.04 LTS aarch64
 - Python Version: 3.7.0b3 
 - Nonebot Version: 2.0.0

**截图**
![QQ截图20210306181631](https://user-images.githubusercontent.com/58383985/110203320-7bb50b00-7ea8-11eb-8595-f2d1b109aa4b.png)

**Comment by yanyongyu** [comment]
请卸载nonebot2重新安装

**Comment by WindLeaf233** [comment]
> 请卸载nonebot2重新安装

没用，不过错误变成了：

**Comment by WindLeaf233** [comment]
> 请卸载nonebot2重新安装

没用，不过错误变成了：
![image](https://user-images.githubusercontent.com/58383985/110203964-b0769180-7eab-11eb-8b6e-e9f9aadffedf.png)

**Comment by yanyongyu** [comment]
你的python版本太低了

**Comment by WindLeaf233** [comment]
已解决：python 版本 3.8，感谢回答！
