### ISSUE TITLE
Plugin: clovers插件框架

### ISSUE THREAD

**Issue by KarisAya** [nonebot/nonebot2#2642]
### PyPI 项目名

nonebot-plugin-clovers

### 插件 import 包名

nonebot_plugin_clovers

### 标签

[]

### 插件配置项

```dotenv
CLOVERS_CONFIG_FILE=clovers.toml
```

**Comment by yanyongyu** [comment]
插件类型应该是`application`，插件支持的适配器没有填写，另外插件配置项的读取方式不正确，请参考[插件配置](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)

**Comment by yanyongyu** [comment]
看你的插件内使用了pydantic v2的使用方法，插件依赖内缺少pydantic及版本限制

**Comment by KarisAya** [comment]
0.1.2.post2
