### ISSUE TITLE
Plugin: Hx_YinYing

### ISSUE THREAD

**Issue by huanxin996** [nonebot/nonebot2#2645]
### PyPI 项目名

nonebot-plugin-hx-yinying

### 插件 import 包名

nonebot_plugin_hx_yinying

### 标签

[{"label":"Chat","color":"#3b53ff"},{"label":"幻歆！","color":"#0d7ccd"},{"label":"银影！","color":"#2b4dae"}]

### 插件配置项

```dotenv
HX_API_YINYING=https://地址
HX_API_FURBAR=https://地址
YINYING_MODEL=模型
FURBAR_MODEL=模型
YINYING_TOKEN=你的token(不带bearer)
HX_REPLY_AT=False
YINYING_LIMIT=12
```

**Comment by huanxin996** [comment]
1

**Comment by huanxin996** [comment]
restart

**Comment by huanxin996** [comment]
1

**Comment by huanxin996** [comment]
1

**Comment by huanxin996** [comment]
1

**Comment by yanyongyu** [comment]
插件支持的适配器填写错误，插件里的homepage似乎不对？

**Comment by huanxin996** [comment]
已修改

> 插件支持的适配器填写错误，插件里的homepage似乎不对？

**Comment by huanxin996** [comment]
> 插件支持的适配器填写错误，插件里的homepage似乎不对？

似乎nb plugin install找不到这个插件包

**Comment by yanyongyu** [comment]
请检查你的nb-cli是否为最新版本，以及插件同步存在一定的延迟可能，但是如果你在nb商店内看到了该插件说明已经同步完成，那有可能是镜像源同步延迟，你可以使用官方源尝试

**Comment by yanyongyu** [comment]
> 提示找不到包

请提供截图

**Comment by huanxin996** [comment]
> > 提示找不到包
> 
> 请提供截图

![Screenshot_2024-04-18-18-44-09-08_2665fb67b16260a8d818298cef8dc107](https://github.com/nonebot/nonebot2/assets/121207415/ff005b11-77c5-4be5-bc67-708670ad0031)
![Screenshot_2024-04-18-18-41-00-14_2665fb67b16260a8d818298cef8dc107](https://github.com/nonebot/nonebot2/assets/121207415/d984a56d-6af5-4895-824b-d6e3607c587f)

**Comment by huanxin996** [comment]
> > > 提示找不到包
> > 
> > 
> > 请提供截图
> 
> ![Screenshot_2024-04-18-18-44-09-08_2665fb67b16260a8d818298cef8dc107](https://private-user-images.githubusercontent.com/121207415/323570450-ff005b11-77c5-4be5-bc67-708670ad0031.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzczOTQsIm5iZiI6MTcxMzQzNzA5NCwicGF0aCI6Ii8xMjEyMDc0MTUvMzIzNTcwNDUwLWZmMDA1YjExLTc3YzUtNGJlNS1iYzY3LTcwODY3MGFkMDAzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDQ0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzUzNTY5MTMxZDdmYzNiNDNjMDdlODEwNTBkYjAyYTA5OTEwZWU1MzBiOWZiMTNmZjA0OTFjOTgyOGM3NjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.URpY67eftBkUJMkQ5DwRV-3Rs81iBoAdonIEMpsduYw) ![Screenshot_2024-04-18-18-41-00-14_2665fb67b16260a8d818298cef8dc107](https://private-user-images.githubusercontent.com/121207415/323570487-d984a56d-6af5-4895-824b-d6e3607c587f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzczOTQsIm5iZiI6MTcxMzQzNzA5NCwicGF0aCI6Ii8xMjEyMDc0MTUvMzIzNTcwNDg3LWQ5ODRhNTZkLTZhZjUtNDg5NS04MjRiLWQ2ZTM2MDdjNTg3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDQ0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjUyNDE0ZTJhYzJjOTQ4ZGM0ZmI2YzQxYzQ4OThjZjQ2MzE5NDQ1OTNlNGQ3NjEyY2MwNzFhY2JiMzM4ZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mofm_ykFtr0IdRFPpGWVu3bDR3pTdQ_GFIq-zH9nZq8)

直接使用pip install nonebot-plugin-hx-yinying
![Screenshot_2024-04-18-18-47-04-53_2665fb67b16260a8d818298cef8dc107](https://github.com/nonebot/nonebot2/assets/121207415/770d636e-dca0-4c2f-93b6-a6ba1bdc2dfa)

**Comment by yanyongyu** [comment]
这个问题是由于你这边加载了商店镜像源，镜像源尚未同步，你可以明天再试

**Comment by huanxin996** [comment]
好的
