### ISSUE TITLE
Plugin: 淫语

### ISSUE THREAD

**Issue by shi-yingyingjiang** [nonebot/nonebot2#2649]
### PyPI 项目名

nonebot-plugin-yinyu

### 插件 import 包名

nonebot_plugin_yinyu

### 标签

[]

**Comment by yanyongyu** [comment]
你的插件并不依赖ob v11适配器，你应该从基类导入使得所有平台可以使用。另外你的插件模块文件名是不是写错了，应该是`__init__.py`

**Comment by shi-yingyingjiang** [comment]
已更新

**Comment by shi-yingyingjiang** [comment]
已更新

**Comment by yanyongyu** [comment]
你这里的导入还是没有更新
https://github.com/shi-yingyingjiang/nonebot-plugin-yinyu/blob/e1e7972da6128416aaeb295b26826cda93f86057/nonebot_plugin_yinyu/__init__.py#L3

应该从`nonebot.adapters`导入即可

**Comment by shi-yingyingjiang** [comment]
再更新一次

**Comment by shi-yingyingjiang** [comment]
再更新一次

**Comment by shi-yingyingjiang** [comment]
再更新一次

**Comment by yanyongyu** [comment]
既然你的插件不依赖ob适配器了，那是不是应该把ob从你的插件依赖内移除？ :joy:

**Comment by shi-yingyingjiang** [comment]
这次应该可以了（救救我）
