### ISSUE TITLE
Plugin: Yinying-Chat

### ISSUE THREAD

**Issue by YuxiCN** [nonebot/nonebot2#2653]
### PyPI 项目名

nonebot-plugin-yinying-chat

### 插件 import 包名

nonebot_plugin_yinying_chat

### 标签

[{"label":"Furry","color":"#ea5252"},{"label":"银影","color":"#ea5252"}]

### 插件配置项

```dotenv
YINYING_API_KEY=""  # 在这里输入银影APIKEY
YINYING_MODEL_NAME=""  # 在这里输入模型名称
YINYING_APP_ID=""  # 在这里输入AppID
ENABLE_PRIVATE_CHAT=true  # 是否开启私聊
YINYING_CHAT_PUBLIC=false  # 群聊是否开启公共会话
```

**Comment by yanyongyu** [comment]
请不要重复提交，直接评论即可触发检查

**Comment by YuxiCN** [comment]
> 请不要重复提交，直接评论即可触发检查

好的，抱歉刚才提交多了

**Comment by YuxiCN** [comment]
test

**Comment by YuxiCN** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-yinying-chat
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请填写插件元数据。
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

1.0.4

**Comment by YuxiCN** [comment]
> > # 📃 商店发布检查结果
> > > Plugin: nonebot-plugin-yinying-chat
> > 
> > 
> > **⚠️ 在发布检查过程中，我们发现以下问题：**
> > ```
> > * ⚠️ 无法获取到插件元数据。请填写插件元数据。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 详情
> > 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> > ♻️ 评论已更新至最新检查结果
> > 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> 
> 1.0.4

1.0.5

**Comment by YuxiCN** [comment]
> > > # 📃 商店发布检查结果
> > > > Plugin: nonebot-plugin-yinying-chat
> > > 
> > > 
> > > **⚠️ 在发布检查过程中，我们发现以下问题：**
> > > ```
> > > * ⚠️ 无法获取到插件元数据。请填写插件元数据。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 详情
> > > 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> > > ♻️ 评论已更新至最新检查结果
> > > 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> > 
> > 
> > 1.0.4
> 
> 1.0.5

1.0.6

**Comment by YuxiCN** [comment]
> > > > # 📃 商店发布检查结果
> > > > > Plugin: nonebot-plugin-yinying-chat
> > > > 
> > > > 
> > > > **⚠️ 在发布检查过程中，我们发现以下问题：**
> > > > ```
> > > > * ⚠️ 无法获取到插件元数据。请填写插件元数据。
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 详情
> > > > 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> > > > ♻️ 评论已更新至最新检查结果
> > > > 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> > > 
> > > 
> > > 1.0.4
> > 
> > 
> > 1.0.5
> 
> 1.0.6

1.0.7

**Comment by YuxiCN** [comment]
1.0.8

**Comment by YuxiCN** [comment]
1.0.9

> > > > > # 📃 商店发布检查结果
> > > > > > Plugin: nonebot-plugin-yinying-chat
> > > > > 
> > > > > 
> > > > > **⚠️ 在发布检查过程中，我们发现以下问题：**
> > > > > ```
> > > > > * ⚠️ 无法获取到插件元数据。请填写插件元数据。
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 详情
> > > > > 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> > > > > ♻️ 评论已更新至最新检查结果
> > > > > 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> > > > 
> > > > 
> > > > 1.0.4
> > > 
> > > 
> > > 1.0.5
> > 
> > 
> > 1.0.6
> 
> 1.0.7

1.0.9

**Comment by YuxiCN** [comment]
1.1.0

**Comment by YuxiCN** [comment]
1.1.2

**Comment by he0119** [comment]
你应该从 onebot.v11 导入，而不是 cqhttp。

**Comment by YuxiCN** [comment]
1.1.3

**Comment by YuxiCN** [comment]
1.1.4

**Comment by YuxiCN** [comment]
1.1.5

**Comment by YuxiCN** [comment]
1.1.6

**Comment by YuxiCN** [comment]
1.1.7

**Comment by YuxiCN** [comment]
1.1.8

**Comment by YuxiCN** [comment]
插件使用正常，但是测试一直不通过，不清除什么原因

**Comment by BigOrangeQWQ** [comment]
请填写插件元数据

**Comment by YuxiCN** [comment]
2.1

**Comment by YuxiCN** [comment]
> 请填写插件元数据

已经填写了插件元数据，依然检查未通过
![Uploading QQ截图20240418223709.png…]()

**Comment by YuxiCN** [comment]
2.2

**Comment by YuxiCN** [comment]
2.2-2

**Comment by YuxiCN** [comment]
> https://github.com/YuxiCN/nonebot_plugin_yinying_chat/blob/e5a9561bc1dfededd6ad39762af9df976522b265/nonebot_plugin_yinying_chat/__init__.py#L16
> 
> 请参考文档填写。https://nonebot.dev/docs/next/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE
> 
> 应为 `__plugin_meta__` 而不是 `plugin_metadata`。
> 
> ```python
> __plugin_meta__ = PluginMetadata(
>     name="{插件名称}",
>     description="{插件介绍}",
>     usage="{插件用法}",
> 
>     type="{插件分类}",
>     # 发布必填，当前有效类型有：`library`（为其他插件编写提供功能），`application`（向机器人用户提供功能）。
> 
>     homepage="{项目主页}",
>     # 发布必填。
> 
>     config=Config,
>     # 插件配置项类，如无需配置可不填写。
> 
>     supported_adapters={"~onebot.v11", "~telegram"},
>     # 支持的适配器集合，其中 `~` 在此处代表前缀 `nonebot.adapters.`，其余适配器亦按此格式填写。
>     # 若插件可以保证兼容所有适配器（即仅使用基本适配器功能）可不填写，否则应该列出插件支持的适配器。
> )
> ```
修改了，但还是检查不通过

**Comment by yanyongyu** [comment]
是`__plugin_meta__`不是`__plugin_metadata__`。。。

**Comment by YuxiCN** [comment]
2.3

**Comment by YuxiCN** [comment]
2.3-2

**Comment by YuxiCN** [comment]
名称设置错误，需要重新创建

**Comment by yanyongyu** [comment]
？你直接修改issue就可以了啊

**Comment by yzyyz1387** [comment]
![-1a27402dca08aee7.jpg](https://github.com/nonebot/nonebot2/assets/51691024/3c0ef27e-ee87-4493-8e16-516d07f36161)

**Comment by yanyongyu** [comment]
插件配置项那边不需要为Config加extra，这个方法在新版本中已经过时。另外看你插件依赖里有openai但实际并未使用到，应该移除。

**Comment by YuxiCN** [comment]
1.1 fix
