### ISSUE TITLE
Plugin: 职场日历

### ISSUE THREAD

**Issue by Priopus** [nonebot/nonebot2#2655]
### PyPI 项目名

nonebot-plugin-zhichang

### 插件 import 包名

nonebot_plugin_zhichang

### 标签

[]

**Comment by Priopus** [comment]
1.0.1

**Comment by Priopus** [comment]
1.0.2

**Comment by Priopus** [comment]
1.0.3

**Comment by Priopus** [comment]
1.0.4

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器，插件数据不应存放于插件目录内，请参考[数据存储](https://nonebot.dev/docs/best-practice/data-storing)存放插件数据。

**Comment by yanyongyu** [comment]
@Priopus 滴滴，是否更新？

**Comment by yanyongyu** [comment]
鉴于插件作者一个月没有回复，暂时关闭本次提交，如果需要发布请重新提交
