### ISSUE TITLE
Plugin: 战双表情

### ISSUE THREAD

**Issue by shi-yingyingjiang** [nonebot/nonebot2#2668]
### PyPI 项目名

nonebot-plugin-zsmeme

### 插件 import 包名

nonebot_plugin_zsmeme

### 标签

[{"label":"帕弥什","color":"#ea5252"}]

**Comment by RF-Tar-Railt** [comment]
？你都用httpx了怎么还装Requests

**Comment by shi-yingyingjiang** [comment]
更新了

**Comment by yanyongyu** [comment]
插件内请不要使用requests同步请求，请使用httpx或aiohttp异步请求代替。

**Comment by shi-yingyingjiang** [comment]
更新了，不知道这样写行不行
