### ISSUE TITLE
Plugin: 三爻易数

### ISSUE THREAD

**Issue by afterow** [nonebot/nonebot2#2674]
### PyPI 项目名

nonebot-plugin-sanyao

### 插件 import 包名

nonebot_plugin_sanyao

### 标签

[{"label":"占卜","color":"#415656"}]

**Comment by afterow** [comment]
1111111111111

**Comment by Well2333** [comment]
插件审核不通过的情况下，请按照noneflow的提示修改插件，然后在原issue下回复，而不是重新开启新的issue

**Comment by Well2333** [comment]
并且，插件并不是必须要发布到nonebot商店才能够使用。如果您一直无法通过审核，请自行学习python依赖管理相关内容后再进行发布。在此之前，您的插件依旧可以被他人正常使用（如果可以使用的话）。

**Comment by afterow** [comment]
222222222222

**Comment by afterow** [comment]
111111111111111111

**Comment by afterow** [comment]
222222222222222

**Comment by afterow** [comment]
3333333333333

**Comment by afterow** [comment]
222222222222

**Comment by afterow** [comment]
11111111111111111

**Comment by afterow** [comment]
444444444444444444444

**Comment by afterow** [comment]
1

**Comment by afterow** [comment]
lgc2333 here

**Comment by lgc2333** [comment]
忘记写了，加在 `__init__.py` 的第三行上面就行

**Comment by lgc2333** [comment]
忘记写了，加在 `__init__.py` 的第三行上面就行

**Comment by lgc2333** [comment]
可以了
