### ISSUE TITLE
Plugin: cyberfurry

### ISSUE THREAD

**Issue by cubstaryow** [nonebot/nonebot2#2678]
### PyPI 项目名

nonebot-plugin-cyberfurry

### 插件 import 包名

nonebot_plugin_cyberfurry

### 标签

[{"label":"幼龙云端","color":"#ccc719"},{"label":"银影","color":"#af2af3"}]

### 插件配置项

```dotenv
CF_APPID="textbot"
CF_TOKEN="yinying-texttokenx"
```

**Comment by cubstaryow** [comment]
已更新

**Comment by yanyongyu** [comment]
插件数据不要存放在bot目录下，建议使用[localstore](https://nonebot.dev/docs/best-practice/data-storing)，或者提供配置项供用户选择

**Comment by cubstaryow** [comment]
> 插件数据不要存放在bot目录下，建议使用[localstore](https://nonebot.dev/docs/best-practice/data-storing)，或者提供配置项供用户选择

好的，下个版本会尝试向此方面修改uwu

**Comment by yanyongyu** [comment]
你close干啥啊 :joy:

**Comment by cubstaryow** [comment]
> 你close干啥啊 😂

a，第一次用github不熟悉（汗
