### ISSUE TITLE
Plugin: HelpWithPic

### ISSUE THREAD

**Issue by cubstaryow** [nonebot/nonebot2#2680]
### PyPI 项目名

nonebot-plugin-HelpWithPic

### 插件 import 包名

nonebot_plugin_helpwithpic

### 标签

[{"label":"帮助","color":"#c61b1b"},{"label":"图片生成","color":"#c61b1b"}]

**Comment by cubstaryow** [comment]
已更新

**Comment by cubstaryow** [comment]
已更新，（奇怪了我本地测试没问题啊（

**Comment by yanyongyu** [comment]
插件依赖里有httpx但似乎并未使用到，可以移除

**Comment by cubstaryow** [comment]
> 插件依赖里有httpx但似乎并未使用到，可以移除

好的，下个版本将会修改

**Comment by cubstaryow** [comment]
> @cubstaryow 插件依赖缺少了anyio

修了
