### ISSUE TITLE
Adapter: Tailchat

### ISSUE THREAD

**Issue by eya46** [nonebot/nonebot2#2692]
### 适配器名称

Tailchat

### 适配器描述

Tailchat 适配器

### PyPI 项目名

nonebot-adapter-tailchat

### 适配器 import 包名

nonebot_adapter_tailchat

### 适配器项目仓库/主页链接

https://github.com/eya46/nonebot-adapter-tailchat

### 标签

[]

**Comment by yanyongyu** [comment]
请另外开一个pr补充一下nb2仓库内readme里的平台适配表格，可以参考已有的格式补充平台信息
