### ISSUE TITLE
Plugin: with_ai_agents

### ISSUE THREAD

**Issue by yejue** [nonebot/nonebot2#2696]
### PyPI 项目名

nonebot-plugin-with-ai-agents

### 插件 import 包名

nonebot_plugin_with_ai_agents

### 标签

[{"label":"AI 智能体","color":"#5dac81"},{"label":"多平台模型","color":"#5dac81"}]

### 插件配置项

```dotenv
WITH_AI_AGENTS__API_KEY=<你的大模型 api key>
WITH_AI_AGENTS__PLATFORM=<你的大模型平台>
WITH_AI_AGENTS__MODEL_NAME=<你的大模型名称>
WITH_AI_AGENTS__TAVILY_API_KEY=<Tavily 搜索 api key>
```

**Comment by yejue** [comment]
0.1.4 更新 httpx 依赖

**Comment by yejue** [comment]
0.1.5 更新插件元信息

**Comment by yanyongyu** [comment]
你的插件配置项写法完全不对啊，请参考配置文档填写。另外你的响应器也不应该用 `on_command` 而是应该用 `on_message`。

**Comment by yejue** [comment]
> 你的插件配置项写法完全不对啊，请参考配置文档填写。另外你的响应器也不应该用 `on_command` 而是应该用 `on_message`。

0.1.7 更新：改用 nonebot 配置标准、将事件响应器更改为 `on_message`

**Comment by yejue** [comment]
0.1.9 更新：整体功能优化，只保留核心功能；精简消息存储，同时对聊天历史进行策略性选取；
