### ISSUE TITLE
Plugin: 神秘学助手

### ISSUE THREAD

**Issue by Yan-Zero** [nonebot/nonebot2#2699]
### PyPI 项目名

nonebot-plugin-mysticism

### 插件 import 包名

nonebot_plugin_mysticism

### 标签

[{"label":"占卜","color":"#ea5252"},{"label":"tarot","color":"#ea5252"},{"label":"神秘学","color":"#2d4168"}]

**Comment by Yan-Zero** [comment]
update

**Comment by Yan-Zero** [comment]
> 标题的插件名称是由你插件的`__plugin_meta__` 的name决定的 这个name并不需要与你插件的pypi名称相同

原来如此

**Comment by Yan-Zero** [comment]
更新喵

**Comment by yanyongyu** [comment]
插件元数据缺少config

**Comment by Yan-Zero** [comment]
> 插件元数据缺少config

嗯，加上去了
