### ISSUE TITLE
Plugin: nonebot-plugin-RanFurryPic

### ISSUE THREAD

**Issue by Ekac00** [nonebot/nonebot2#2701]
### PyPI 项目名

nonebot-plugin-RanFurryPic

### 插件 import 包名

nonebot_plugin_RanFurryPic

### 标签

[{"label":"furry","color":"#8cb9e3"}]

**Comment by he0119** [comment]
你还需要将 nonebot2 添加至依赖中。

**Comment by Ekac00** [comment]
> 你还需要将 nonebot2 添加至依赖中。

请问是写到`插件配置项`里吗？
有什么格式要求吗？

**Comment by XieXiLin2** [comment]
建议 **认真** 看完文档并修改发版后再来发布插件。
https://nonebot.dev/docs/developer/plugin-publishing
另外建议您了解一下异步的相关知识。

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新

**Comment by StarHeartHunt** [comment]
包打得有问题，实际插件代码并没有打包进来，请重新检查打包
![image](https://github.com/nonebot/nonebot2/assets/14922941/af5501d8-1c16-4027-952a-68c1a6398c50)

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新

**Comment by StarHeartHunt** [comment]
1. 不要在 nonebot2 中使用 requests，因为会导致事件循环阻塞，可以考虑换用 httpx.AsyncClient 或者 aiohttp
2. nonebot2 从 2.3.0 开始移除了 Python 3.8 支持，请使用 3.9 及以上版本的 Python
3. 如果没有自定义打包流程的需求，pdm 应该已经自带比较完善的打包发布支持，不需要 setup.py

**Comment by Ekac00** [comment]
> 1. 不要在 nonebot2 中使用 requests，因为会导致事件循环阻塞，可以考虑换用 httpx.AsyncClient 或者 aiohttp
> 2. nonebot2 从 2.3.0 开始移除了 Python 3.8 支持，请使用 3.9 及以上版本的 Python
> 3. 如果没有自定义打包流程的需求，pdm 应该已经自带比较完善的打包发布支持，不需要 setup.py

好的，我会更换为httpx进行请求，稍后修改py版本

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新

**Comment by Ekac00** [comment]
已更新
