### ISSUE TITLE
Plugin: 库洛游戏信息

### ISSUE THREAD

**Issue by ConcyWee** [nonebot/nonebot2#2702]
### PyPI 项目名

nonebot-plugin-kurogames

### 插件 import 包名

nonebot_plugin_kurogames

### 标签

[{"label":"战双帕弥什","color":"#ea5252"},{"label":"鸣潮","color":"#ea5252"},{"label":"库洛","color":"#ea5252"}]

**Comment by Ekac00** [comment]
> ### PyPI 项目名
> nonebot-plugin-kurogames
> 
> ### 插件 import 包名
> nonebot_plugin_kurogames
> 
> ### 标签
> [{"label":"战双帕弥什","color":"#ea5252"},{"label":"鸣潮","color":"#ea5252"},{"label":"库洛","color":"#ea5252"}]
> 
> ### 插件配置项
> _No response_

不要忘记依赖哦

**Comment by ConcyWee** [comment]
已更新

**Comment by ConcyWee** [comment]
已更新0.1.6

**Comment by yanyongyu** [comment]
你的插件使用了ob11的image消息，支持的适配器事件应该限制为ob11，或者使用alc跨平台插件。数据库文件不应该随意存储于bot项目目录下，应该使用 [localstore 插件](https://nonebot.dev/docs/best-practice/data-storing)或者提供用户配置项。httpx 网络请求应该使用异步方法 `httpx.AsyncClient` 不要使用同步请求。

**Comment by ConcyWee** [comment]
已更新 0.1.7

**Comment by yanyongyu** [comment]
你的事件响应器限制的event为任意平台，但是你的回复消息是ob平台，这是不对的。另外你的数据库存储路径依然没有提供配置选项。

**Comment by ConcyWee** [comment]
更新 0.1.8

**Comment by ConcyWee** [comment]
更新 0.1.9😶‍🌫️

**Comment by yanyongyu** [comment]
请参考[插件配置文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)正确使用config，配置项应该为小写名称，插件元数据应该提供config配置类。

**Comment by ConcyWee** [comment]
更新0.1.10😑
