### ISSUE TITLE
Plugin: nonebot-tsugu

### ISSUE THREAD

**Issue by otae-1204** [nonebot/nonebot2#2709]
### PyPI 项目名

nonebot-tsugu

### 插件 import 包名

nonebot_tsugu

### 标签

[{"label":"BanG Dream","color":"#ce4def"}]

```[tasklist]
### Tasks
```

**Comment by otae-1204** [comment]
1

**Comment by otae-1204** [comment]
> # 📃 商店发布检查结果
> > 插件：nonebot-tsugu
> 
> **⚠️在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-tsugu 的信息如下：
>        name         : nonebot-tsugu                        
>        version      : 0.0.3                                
>        description  : 基于tsugu-bangdream-bot项目实现的nonebot2插件 
>       
>       dependencies
>        - httpx >=0.18.2
>        - nonebot2 >=2.0.0
>   插件 nonebot-tsugu 依赖的插件如下：
>       
>   插件 nonebot_tsugu 加载出错：
>       05-13 09:09:50 [SUCCESS] nonebot | NoneBot is initializing...
>       05-13 09:09:50 [INFO] nonebot | Current Env: prod
>       05-13 09:09:50 [ERROR] nonebot | Failed to import "nonebot_tsugu"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/runner.py", line 16, in <module>
>           plugin = load_plugin("nonebot_tsugu")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
>           module = importlib.import_module(self._third_party_plugin_ids[name])
>         File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot_tsugu/__init__.py", line 4, in <module>
>           from nonebot.adapters.onebot.v11.message import MessageSegment
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡底座加载测试失败时修改信息，请直接修改问题，机器人会自动更新检查结果。 💡当插件加载测试失败时，请发布新版本后在当前页面下评论任何内容以触发测试。
> 
> ♻️评论已更新至最新检查结果
> 
> 💪 由[NoneFlow提供支持](https://github.com/nonebot/noneflow)

1

**Comment by otae-1204** [comment]
> ### PyPI 项目名
> 尼内博继
> 
> ### 插件 import 包名
> 无机器人_tsugu
> 
> ### 标签
> [{"label":"BanG Dream","color":"#ce4def"}]
> 
> ### 插件依赖项
> [nonebot-适配器-onebot](https://pypi.org/project/nonebot-adapter-onebot)
> 
> ### 插件配置项
> _没有反应_
> 
> ### 任务
> 
> 贝塔
> [给予反馈](https://github.com/community/community/discussions/39106)
> 
> 尚未跟踪任何任务。
> 1. [ ] 
>                  
>                
>    
>                
>                  
>                    
>    
>                  
>                    
>                
>              
>              
>                
>      
>          
>        
>    
>    选项
>    
>    
>    
>      
>        
>                    
>      
>        
>            * 转换为问题
>            * 切换完成
>            * 改名
>            * 消除
> 2.

1

**Comment by otae-1204** [comment]
> # 📃 商店发布检查结果
> > 插件：nonebot-tsugu
> 
> **⚠️在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-tsugu 的信息如下：
>        name         : nonebot-tsugu                        
>        version      : 0.0.3                                
>        description  : 基于tsugu-bangdream-bot项目实现的nonebot2插件 
>       
>       dependencies
>        - httpx >=0.18.2
>        - nonebot2 >=2.0.0
>   插件 nonebot-tsugu 依赖的插件如下：
>       
>   插件 nonebot_tsugu 加载出错：
>       05-13 09:13:42 [SUCCESS] nonebot | NoneBot is initializing...
>       05-13 09:13:42 [INFO] nonebot | Current Env: prod
>       05-13 09:13:42 [ERROR] nonebot | Failed to import "nonebot_tsugu"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/runner.py", line 16, in <module>
>           plugin = load_plugin("nonebot_tsugu")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
>           module = importlib.import_module(self._third_party_plugin_ids[name])
>         File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot_tsugu/__init__.py", line 4, in <module>
>           from nonebot.adapters.onebot.v11.message import MessageSegment
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡底座加载测试失败时修改信息，请直接修改问题，机器人会自动更新检查结果。 💡当插件加载测试失败时，请发布新版本后在当前页面下评论任何内容以触发测试。
> 
> ♻️评论已更新至最新检查结果
> 
> 💪 由[NoneFlow提供支持](https://github.com/nonebot/noneflow)

2

**Comment by RF-Tar-Railt** [comment]
@kumoSleeping

**Comment by otae-1204** [comment]
> # 📃 商店发布检查结果
> > 插件：nonebot-tsugu
> 
> **⚠️在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-tsugu 的信息如下：
>        name         : nonebot-tsugu                        
>        version      : 0.0.3                                
>        description  : 基于tsugu-bangdream-bot项目实现的nonebot2插件 
>       
>       dependencies
>        - httpx >=0.18.2
>        - nonebot2 >=2.0.0
>   插件 nonebot-tsugu 依赖的插件如下：
>       
>   插件 nonebot_tsugu 加载出错：
>       05-13 09:18:06 [SUCCESS] nonebot | NoneBot is initializing...
>       05-13 09:18:06 [INFO] nonebot | Current Env: prod
>       05-13 09:18:06 [ERROR] nonebot | Failed to import "nonebot_tsugu"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/runner.py", line 16, in <module>
>           plugin = load_plugin("nonebot_tsugu")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
>           module = importlib.import_module(self._third_party_plugin_ids[name])
>         File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-tsugu-nonebot_tsugu-test/.venv/lib/python3.12/site-packages/nonebot_tsugu/__init__.py", line 4, in <module>
>           from nonebot.adapters.onebot.v11.message import MessageSegment
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡底座加载测试失败时修改信息，请直接修改问题，机器人会自动更新检查结果。 💡当插件加载测试失败时，请发布新版本后在当前页面下评论任何内容以触发测试。
> 
> ♻️评论已更新至最新检查结果
> 
> 💪 由[NoneFlow提供支持](https://github.com/nonebot/noneflow)

update

**Comment by WindowsSov8forUs** [comment]
绷不住

**Comment by otae-1204** [comment]
绷不住，关了吧，一坨屎，懒得改了
