### ISSUE TITLE
Plugin: nonebot_plugin_valve_server_query

### ISSUE THREAD

**Issue by LiLuo-B** [nonebot/nonebot2#2710]
### PyPI 项目名

nonebot-plugin-valve-server-query 

### 插件 import 包名

nonebot_plugin_valve_server_query 

### 标签

[{"label":"valve","color":"#ea5252"},{"label":"query","color":"#ea5252"},{"label":"a2s","color":"#ea5252"}]

**Comment by LiLuo-B** [comment]
已修复

**Comment by yanyongyu** [comment]
你使用了nb 2.2.0+ 的方法，请提高你的依赖版本限制到 `^2.2.0`。以及请勿在依赖中使用 `==` 限制版本。插件数据请勿随意存储于bot目录下，可以使用[localstore插件](https://nonebot.dev/docs/best-practice/data-storing)或者提供配置项。

**Comment by LiLuo-B** [comment]
已更新
