### ISSUE TITLE
Plugin: 科大讯飞星火大语言模型官方API聊天机器人插件

### ISSUE THREAD

**Issue by CCLMSY** [nonebot/nonebot2#2716]
### PyPI 项目名

nonebot-plugin-sparkapi

### 插件 import 包名

nonebot_plugin_sparkapi

### 标签

[{"label":"AI","color":"#00ff00"}]

### 插件配置项

```dotenv
SPARKAPI_APP_ID=""
SPARKAPI_API_SECRET="" 
SPARKAPI_API_KEY=""
```

**Comment by CCLMSY** [comment]
这是来自QQ邮箱的假期自动回复邮件。

**Comment by CCLMSY** [comment]
Updated

**Comment by CCLMSY** [comment]
Updated:  使用Websockets重写了API调用

@yanyongyu 查了一下wsgiref似乎属于python内置标准库的//我也没有找到额外安装的包qwq

**Comment by yanyongyu** [comment]
看错了，wsgiref是标准库，asgiref是需要安装的（

**Comment by yanyongyu** [comment]
另外你为啥不把你的request改成异步的？不需要在同步和异步之间切来切去

**Comment by CCLMSY** [comment]
好的//现在进行修改//
API和调用部分基本copy了文档给出的demo。
采用的是同步方法，测试的时候没问题就没改过来。
//感谢您抽时间指导！❤

**Comment by CCLMSY** [comment]
Bug Fixed

**Comment by CCLMSY** [comment]
Bug Fixed && Meta Updated
