### ISSUE TITLE
Plugin: nonebot-plugin-tsugu-bangdream-bot

### ISSUE THREAD

**Issue by WindowsSov8forUs** [nonebot/nonebot2#2718]
### PyPI 项目名

nonebot-plugin-tsugu-bangdream-bot

### 插件 import 包名

nonebot_plugin_tsugu_bangdream_bot

### 标签

[{"label":"tsugu","color":"#ffee88"}]

**Comment by WindowsSov8forUs** [comment]
已修改

**Comment by RF-Tar-Railt** [comment]
怎么又来一个tsugu（

**Comment by WindowsSov8forUs** [comment]
> 怎么又来一个tsugu（

那个tsugu写的实在是看不下去所以跑来写了一个（

**Comment by GreyElaina** [comment]
ycm

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器，请继承依赖的插件

**Comment by WindowsSov8forUs** [comment]
> 插件元数据缺少支持的适配器，请继承依赖的插件

已添加支持适配器元数据

**Comment by WindowsSov8forUs** [comment]
再次修改，跟随 tsugu-api-python 的结构更改
自己把自己坑了

**Comment by WindowsSov8forUs** [comment]
没触发检测吗？
