### ISSUE TITLE
Plugin: nonebot-plugin-calc24

### ISSUE THREAD

**Issue by ajdgg** [nonebot/nonebot2#2720]
### PyPI 项目名

nonebot-plugin-calc24

### 插件 import 包名

nonebot_plugin_calc24

### 标签

[]

**Comment by RF-Tar-Railt** [comment]
第一，请不要把pycache上传到仓库中
第二，文件存储请使用nonebot-plugin-localstore插件，另外文件路径拼接推荐使用pathlib而不是os.path
第三，你的插件完全可以不依赖于onebot适配器，因为你这个permisson = GROUP | PRIVATE完全没有必要
第四，你完全没有用到telegram，为什么要在supportadapters写上telegram？

**Comment by RF-Tar-Railt** [comment]
第五，你代码部分缩进混乱

第六，你文件打开部分没有指定编码格式

第七，你消息处理逻辑里面为什么不通过args = CommandArg()拿到命令后续参数，而是用event.get_plain_text() == "/xxx"? 你得清楚命令前缀是最终用户配置决定的，用户一旦把命令前缀配置为 ".", "!"等等你插件就失效了

**Comment by ajdgg** [comment]
好的

**Comment by ajdgg** [comment]
测试

**Comment by ajdgg** [comment]
更新

**Comment by yanyongyu** [comment]
如果你的插件不依赖平台，你应该从`nonebot.adapters`导入bot和event基类，而不是从适配器导入。

**Comment by ajdgg** [comment]
更新
