### ISSUE TITLE
Plugin: 自定义人格和AI绘图的混合聊天BOT

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#2723]
### PyPI 项目名

nonebot-plugin-nai3-bot

### 插件 import 包名

nonebot_plugin_nai3_bot

### 标签

[{"label":"NovelAI","color":"#52ea52"},{"label":"NAI3","color":"#52ea52"}]

### 插件配置项

```dotenv
NAI3_TOKEN="xxxxxxxxxxxxxx"
ONEAPI_KEY="sk-xxxxxxxxxxxxxxxx"
```

**Comment by Alpaca4610** [comment]
update

**Comment by Alpaca4610** [comment]
update

**Comment by yanyongyu** [comment]
插件内请勿使用requests同步网络请求，你可以使用aiohttp或者httpx代替，以及你的openai请求也应该使用异步接口。

**Comment by Alpaca4610** [comment]
更新使用AsyncOpenAI和httpx

**Comment by Alpaca4610** [comment]
> 插件内请勿使用requests同步网络请求，你可以使用aiohttp或者httpx代替，以及你的openai请求也应该使用异步接口。

已更新

**Comment by yanyongyu** [comment]
小tips，httpx的`response.content`应该在client关闭前读取。

**Comment by Alpaca4610** [comment]
> httpx的`response.content`应该在client关闭前读取。

感谢提醒，下次更新时我改一下
