### ISSUE TITLE
Plugin: 插件响应鉴权

### ISSUE THREAD

**Issue by cubstaryow** [nonebot/nonebot2#2726]
### PyPI 项目名

nonebot-plugin-authrespond

### 插件 import 包名

nonebot_plugin_authrespond

### 标签

[{"label":"黑名单","color":"#e81616"},{"label":"cubplugins","color":"#28a5d1"},{"label":"权限控制","color":"#c75d59"}]

**Comment by cubstaryow** [comment]
> 第一，你这个插件完全可以使用 [`plugin-session`](https://github.com/noneplugin/nonebot-plugin-session) 来判断会话等级，而不是强依赖于onebot11适配器的`GroupMessageEvent`，让你这个插件只能在ob11下使用。我推荐你换用 nonebot-plugin-session
> 
> 第二，你使用的 on_regex 的正则表达式里面存在泛匹配 (`.*`)，在特殊情况下这会对机器人性能造成很大影响。请换用精准一点的表达式（例如 `[\w|-]*`)

行，下个版本整x

**Comment by cubstaryow** [comment]
已更新√

**Comment by cubstaryow** [comment]
已更新√

**Comment by cubstaryow** [comment]
已更新

**Comment by RF-Tar-Railt** [comment]
你插件有一部分拿at的，可以去用[plugin-alconna](https://github.com/nonebot/plugin-alconna)的UniMessage去提取At

**Comment by cubstaryow** [comment]
> 你插件有一部分拿at的，可以去用[plugin-alconna](https://github.com/nonebot/plugin-alconna)的UniMessage去提取At

谢谢，正发愁呢x

**Comment by cubstaryow** [comment]
已更新x

**Comment by yanyongyu** [comment]
`supported_adapters` 请使用 `inherit_supported_adapters` 从依赖的插件继承。在使用第三方插件时需要先`require`，最好把 require 放在插件最初导入的部分。

**Comment by cubstaryow** [comment]
已更新

**Comment by yanyongyu** [comment]
你同时用了alconna和session插件，你应该同时继承他们两个支持的适配器列表，直接添加`inherit_supported_adapters`的参数即可。

**Comment by cubstaryow** [comment]
已更新

**Comment by yanyongyu** [comment]
等下我漏看了一个，你还要继承localstore的（（（

**Comment by cubstaryow** [comment]
> 等下我漏看了一个，你还要继承localstore的（（（

loaclstore不是本地插件数据吗，好像和适配器没关系吧(

**Comment by yanyongyu** [comment]
哪怕他和适配器没关系也需要继承，因为他也是插件

**Comment by cubstaryow** [comment]
> 哪怕他和适配器没关系也需要继承，因为他也是插件

行，更新了

**Comment by yanyongyu** [comment]
你没有require localstore。。

**Comment by cubstaryow** [comment]
> 你没有require localstore。。

在plugins_data里，启动时若配置不存在启用 localstore ，若配置存在则不会使用localstore（import和require都不会执行）

**Comment by yanyongyu** [comment]
如果你可能使用一个插件就需要声明依赖，哪怕不使用

**Comment by cubstaryow** [comment]
> 如果你可能使用一个插件就需要声明依赖，哪怕不使用

但是声明在plugins_data里（

**Comment by yanyongyu** [comment]
你需要在 inherit 前声明依赖

**Comment by cubstaryow** [comment]
> 你需要在 继承 前声明依赖

哦，懂了，马上去修）

**Comment by cubstaryow** [comment]
已修复
