### ISSUE TITLE
【功能建议】对aliases里面的关键词也设置起始命令

### ISSUE THREAD

**Issue by mengluo04** [nonebot/nonebot2#2730]
### 希望能解决的问题

目前cmd命令可以实现匹配命令前缀，但是aliases里面的不行，比如#，*开头的命令都会触发aliases里面的命令

### 描述所需要的功能

实现和cmd前缀一样的功能，比如环境变量配置文件里面的COMMAND_START参数

**Comment by RF-Tar-Railt** [comment]
你先跟我解释一下什么是命令别名

**Comment by mengluo04** [comment]
> 你先跟我解释一下什么是命令别名
on_command方法里面的这个参数：aliases

**Comment by RF-Tar-Railt** [comment]
> > 你先跟我解释一下什么是命令别名
> on_command方法里面的这个参数：aliases

我在问你它的意义和功能

**Comment by yzyyz1387** [comment]
你举个实际例子说明一下

**Comment by mengluo04** [comment]
> 你举个实际例子说明一下

群里有原神和星铁两个机器人，原神机器人那边指定是#xx角色面板，星铁这边是xx角色面板，发送#xx角色面板，两边都会触发。看了原神机器人那边不是用的nb开发，是作者用正则匹配的然后走的nobe标准，看起来是插件作者自己处理更合适？

**Comment by yzyyz1387** [comment]
哦原来你是...

**Comment by yanyongyu** [comment]
alias 就是命令的别名，同样受 command start 配置影响

**Comment by mengluo04** [comment]
> 哦原来你是...



> alias 就是命令的别名，同样受 command start 配置影响

还真是，这就尴尬了，估计是之前改env没该对，

**Comment by mengluo04** [comment]
> 哦原来你是...

OP是吧

**Comment by mengluo04** [comment]
> alias 就是命令的别名，同样受 command start 配置影响

不太对，设置了前缀，只有命令生效了，别名还是没有判断前缀，nonebot2的版本是2.2.1
![image](https://github.com/nonebot/nonebot2/assets/32565940/eb8ea776-0635-4faa-a53b-8b4acec50dd5)
![image](https://github.com/nonebot/nonebot2/assets/32565940/716df344-b2fd-4d42-89c8-c47309bf33ec)

**Comment by RF-Tar-Railt** [comment]
你把.env改成.env.prod看看
要么你把日志等级改成DEBUG

**Comment by mengluo04** [comment]
> 你把.env改成.env.prod看看 要么你把日志等级改成DEBUG

用的是.env.prod，这是debug日志的结果
![image](https://github.com/nonebot/nonebot2/assets/32565940/d4cba6e9-1cfc-4810-aeb4-8885feb6aba3)

**Comment by RF-Tar-Railt** [comment]
> > 你把.env改成.env.prod看看 要么你把日志等级改成DEBUG
> 
> 用的是.env.prod，这是debug日志的结果
> ![image](https://github.com/nonebot/nonebot2/assets/32565940/d4cba6e9-1cfc-4810-aeb4-8885feb6aba3)
> 

你自己去看插件源码。。。xxx面板用的是on_regex，与command无关

**Comment by mengluo04** [comment]
> > > 你把.env改成.env.prod看看 要么你把日志等级改成DEBUG
> > 
> > 
> > 用的是.env.prod，这是debug日志的结果
> > ![image](https://private-user-images.githubusercontent.com/32565940/332639236-d4cba6e9-1cfc-4810-aeb4-8885feb6aba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDczODgsIm5iZiI6MTcxNjM0NzA4OCwicGF0aCI6Ii8zMjU2NTk0MC8zMzI2MzkyMzYtZDRjYmE2ZTktMWNmYy00ODEwLWFlYjQtODg4NWZlYjZhYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNzZhOWJiYjQ0MzlmNmRhY2VlYTRjMmJkYjU3OGZmYTQ3MGZhNDU4NzA3MDBmYjY1OGM4MjQ5NmIxZTQxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjgKXRcjOH1ojYFK9jY4ipMHY8Rxbmb0ULRfRLJg2uo)
> 
> 你自己去看插件源码。。。xxx面板用的是on_regex，与command无关

好的，非常感谢
