### ISSUE TITLE
Plugin: 复读姬+1 PlusOne

### ISSUE THREAD

**Issue by yejue** [nonebot/nonebot2#2731]
### PyPI 项目名

nonebot-plugin-plus-one

### 插件 import 包名

nonebot_plugin_plus_one

### 标签

[{"label":"复读姬","color":"#df3cda"},{"label":"船新版本","color":"#28d98e"}]

### 插件配置项

```dotenv
# 匹配优先级
PLUS_ONE_PRIORITY = 10
```

**Comment by yejue** [comment]
add nb

**Comment by yanyongyu** [comment]
因为你使用了nb新版本的方法，你需要依赖nb 2.2.0+。你的响应器rule regex可以删除。另外你的group id获取方式不正确，你可以使用商店里的 session 插件或 alconna 插件来获取相关信息。

**Comment by yejue** [comment]
> 因为你使用了nb新版本的方法，你需要依赖nb 2.2.0+。你的响应器rule regex可以删除。另外你的group id获取方式不正确，你可以使用商店里的 session 插件或 alconna 插件来获取相关信息。

0.1.4：使用 session 插件获取 group id

**Comment by yanyongyu** [comment]
regex的问题依旧存在，另外你没有继承session支持的适配器

**Comment by yejue** [comment]
> regex的问题依旧存在，另外你没有继承session支持的适配器

0.1.7 移除 regex，增加支持的适配器

**Comment by yanyongyu** [comment]
你应该使用 nb 提供的 `inherit_supported_adapters` 方法继承支持的适配器
