### ISSUE TITLE
Plugin: nonebot-plugin-webpreview

### ISSUE THREAD

**Issue by AcoFork** [nonebot/nonebot2#2735]
### PyPI 项目名

nonebot-plugin-webpreview

### 插件 import 包名

nonebot_plugin_webpreview

### 标签

[{"label":"网页预览","color":"#ea5252"}]

**Comment by lgc2333** [comment]
1. 你代码没传上来，不论是 gh 还是 pypi
2. 商店可能已经有同类插件了
3. 建议使用 nonebot_plugin_htmlrender，并且 pyppeteer 貌似停止维护了

**Comment by AcoFork** [comment]
Update

**Comment by lgc2333** [comment]
不得不承认gpt确实是很好的辅助工具，但是我还是建议你自己先有一些基础的知识储备来判断gpt给出答案的准确性与可用性还有理解 `插件 import 包名` 这几个字的意义
