### ISSUE TITLE
Plugin: ai唱歌

### ISSUE THREAD

**Issue by CCYellowStar2** [nonebot/nonebot2#2742]
### PyPI 项目名

nonebot-plugin-aising

### 插件 import 包名

nonebot_plugin_aising

### 标签

[{"label":"唱歌","color":"#ea5252"},{"label":"NeuCoSVC","color":"#ea5252"}]

**Comment by RF-Tar-Railt** [comment]
你哪年穿越来的还依赖nonebot2 > -beta.1？

**Comment by CCYellowStar2** [comment]
Update

**Comment by RF-Tar-Railt** [comment]
你改了要往pypi发版才行

**Comment by CCYellowStar2** [comment]
> 你改了要往pypi发版才行

已经发了

**Comment by yanyongyu** [comment]
插件数据存储请使用 [localstore 插件](https://nonebot.dev/docs/best-practice/data-storing)。

**Comment by CCYellowStar2** [comment]
更新使用nonebot_plugin_localstore

**Comment by CCYellowStar2** [comment]
刷新
