### ISSUE TITLE
Plugin: QQShell

### ISSUE THREAD

**Issue by yejue** [nonebot/nonebot2#2744]
### PyPI 项目名

nonebot-plugin-qqshell

### 插件 import 包名

nonebot_plugin_qqshell

### 标签

[{"label":"SSH","color":"#cd2a8f"}]

### 插件配置项

```dotenv
QQSHELL_HOST="localhost"
QQSHELL_PORT=22
QQSHELL_HOST_USER="root"
QQSHELL_HOST_PASSWORD="xxxx"
QQSHELL_PRIORITY=10
QQSHELL_THEME="theme_black_white_rikka"
```

**Comment by RF-Tar-Railt** [comment]
?

**Comment by yejue** [comment]
> ?

?

**Comment by RF-Tar-Railt** [comment]
第一，你的插件仓库格式不对
第二，你为啥不用alc或者其他的发图，你只用了ob11的MS.image，换成跨平台图片发送是完全可以的

**Comment by Well2333** [comment]
提一些无关紧要问题，这个插件有什么必要性吗，手机端有serverbox或其他类似的软件，根本不需要这么一个输入麻烦、没有快捷键、没有补全的东西，就算你能给克服上述缺陷，但对于一些动态输出（如top）是无论如何都没法实现的。
因此个人建议建议将精力用于开发其他类型的插件

**Comment by yejue** [comment]
> 提一些无关紧要问题，这个插件有什么必要性吗，手机端有serverbox或其他类似的软件，根本不需要这么一个输入麻烦、没有快捷键、没有补全的东西，就算你能给克服上述缺陷，但对于一些动态输出（如top）是无论如何都没法实现的。 因此个人建议建议将精力用于开发其他类型的插件

首先，存在是因为有需求，无论任何软件，都需要一个打开和链接的步骤，但是对于已经存在的 bot，即使是临时起意也可以直接发送指令。对于一个简易的 shell 来说，不需要任何的补全。
第二，关于补全实际上跟我文档内所说的控制按键转发是同一个，如果有需要，转发一个 TAB 完全是可以的
第三，我希望他是一个完全的交互式 shell，即便是 top 这类动态的也是可以实现的。对于 bot 来说，发送这个动态的输出，只需要按一定的频次发送即可，完全实时不现实，一定频次甚至只需要一次的输出完全可行。毕竟应该不会人会拿这个shell来做监控工作。

如第三点所说的，这个东西需要多个版本的迭代。现版本刨去诸如 top、htop 这类命令，已经覆盖了90%以上的命令。提供一个简易、便捷，随处可用的 ssh 链接是很方便的。

**Comment by yejue** [comment]
> 第一，你的插件仓库格式不对 第二，你为啥不用alc或者其他的发图，你只用了ob11的MS.image，换成跨平台图片发送是完全可以的

跨平台图片我之前没找着，对 nb 本身还不是很熟悉。回头改一下。仓库格式的话，可不可以保持这样，提供一个 git clone 的方式安装？

**Comment by RF-Tar-Railt** [comment]
> > 第一，你的插件仓库格式不对 第二，你为啥不用alc或者其他的发图，你只用了ob11的MS.image，换成跨平台图片发送是完全可以的
> 
> 跨平台图片我之前没找着，对 nb 本身还不是很熟悉。回头改一下。仓库格式的话，可不可以保持这样，提供一个 git clone 的方式安装？

跨平台：https://nonebot.dev/docs/next/best-practice/alconna/uniseg

至于仓库问题，你现在这个格式，别人要给你插件提pr会比较困难。你要说克隆的话，把打包好的插件放在release里面让其他人不是也可以？

**Comment by yanyongyu** [comment]
如果你想跨平台的话可以使用alc，并更新你的插件元数据，继承alc支持的平台。另外你的仓库结构确实不对，没有看到你的`setup.py`或者`pyproject.toml`。其他看上去没什么问题

**Comment by XTxiaoting14332** [comment]
话说这种插件你确定不弄一下``SUPERUSER``吗 这相当于你把自己的服务器完全暴露给别人了（）

**Comment by yejue** [comment]
> 话说这种插件你确定不弄一下`SUPERUSER`吗 这相当于你把自己的服务器完全暴露给别人了（）

这个问题是考虑了的，发的时候忘记了这回事，目前打算和控制符转义、以及一些别的东西一起发下一个版本

**Comment by XTxiaoting14332** [comment]
> > 话说这种插件你确定不弄一下`SUPERUSER`吗 这相当于你把自己的服务器完全暴露给别人了（）
> 
> 这个问题是考虑了的，发的时候忘记了这回事，目前打算和控制符转义、以及一些别的东西一起发下一个版本

加油（）
