### ISSUE TITLE
Plugin: 学园偶像大师算分插件

### ISSUE THREAD

**Issue by ikarosf** [nonebot/nonebot2#2749]
### PyPI 项目名

nonebot-plugin-gakuenImasCalculator

### 插件 import 包名

nonebot_plugin_gakuenImasCalculator

### 标签

[{"label":"游戏","color":"#ea5252"},{"label":"工具","color":"#ea5f52"}]

**Comment by RF-Tar-Railt** [comment]
第一，请仔细阅读一遍nb文档中关于插件开发的部分
第二，你用的setup.py,那么你需要在`install_requires` 写明插件的依赖
第三，你的插件缺失插件元数据，这部分遵循第一点，请阅读插件开发文档
第四，你的插件完全没有依赖于 onebot适配器的内容，推荐你删除这部分的相关代码

**Comment by ikarosf** [comment]
好的我已做出对应修改，希望能行

**Comment by ikarosf** [comment]
再次修改

**Comment by ikarosf** [comment]
再再次修改

**Comment by ikarosf** [comment]
啊？我更新完怎么bot检测的版本还倒退了

**Comment by yanyongyu** [comment]
你的插件不依赖ob适配器，你应该在`setup.py`中删除该依赖，另外你的nonebot2依赖没有限制版本，应填写`>=2.2.0,<3.0.0`

**Comment by ikarosf** [comment]
> 你的插件不依赖ob适配器，你应该在`setup.py`中删除该依赖，并在calc的时候使用基类标注。另外你的nonebot2依赖没有限制版本，应填写`>=2.2.0,<3.0.0`

已更正
