### ISSUE TITLE
Feature: 让get_session_id统一起来

### ISSUE THREAD

**Issue by Reverier-Xu** [nonebot/nonebot2#275]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

使用`adapter.cqhttp MessageEvent`中的`get_session_id()`函数时, 无论在群组还是在私聊消息中都只会返回发送者的QQ号.

**描述你所需要的特性：**

通过`Event`中的`get_session_id`函数来判断当前的群组会话环境. 目前官方`adapter`中只有`mirai`重载了这个函数, 希望能统一格式.

**Comment by yanyongyu** [comment]
cqhttp的`get_session_id`在设计时就是为了允许跨群会话而只使用用户的id而不添加群组信息

**Comment by Reverier-Xu** [comment]
> cqhttp的`get_session_id`在设计时就是为了允许跨群会话而只使用用户的id而不添加群组信息
> 
> 如果你需要判断群组环境可以自行构造
> 
> 如果修改`get_session_id`将会影响cqhttp的会话机制，不过在有了自定义会话范围的api后确实可以做改进

那`get_user_id`呢? 如果需要跨群会话的话可以使用这个方法呀.

我提出这个是因为在mirai的adapter中找到了对应的方法, 但是另外两个都只是简单的返回`user_id`, 这和文档上的描述也不太一致...

**Comment by yanyongyu** [comment]
> 那get_user_id呢? 如果需要跨群会话的话可以使用这个方法呀

nonebot 默认通过 `get_session_id` 方法判断会话，不会做改变，但可以自定义

> 这和文档上的描述也不太一致

文档上说明了可以跨群响应会话，mirai并非我维护我不清楚他是怎么写的，和cqhttp有所差异
