### ISSUE TITLE
Plugin: nonebot-plugin-multigpt

### ISSUE THREAD

**Issue by syagina** [nonebot/nonebot2#2753]
### PyPI 项目名

nonebot-plugin-multigpt

### 插件 import 包名

nonebot_plugin_multigpt

### 标签

[{"label":"PPT","color":"#ea5252"},{"label":"ai","color":"#ea5252"},{"label":"GPT","color":"#ea5252"}]

**Comment by RF-Tar-Railt** [comment]
请问你是拿记事本写代码的吗？

**Comment by XTxiaoting14332** [comment]
?

**Comment by XTxiaoting14332** [comment]
诶不是哥们你那`。`是什么东西（

**Comment by forchannot** [comment]
第一，使用localstore管理你的数据和缓存文件，而不是到处扔。
第二，**不要使用**requests来完成网络请求，如果强依赖openai的话，他有有自己的openai-python的异步请求方式，如果不强依赖，则统一使用httpx的异步或者aiohttp进行网络请求
第三，文件管理很混乱，一部分用os.path，一部分又用pathlib.Path，建议统一用pathlib.Path（配合第一条）
第四，对你的依赖文件进行版本限制和约束，推荐考虑poetry或者pdm进行依赖管理，而不是自己手打依赖
