### ISSUE TITLE
Plugin: 多模态AI工具

### ISSUE THREAD

**Issue by syagina** [nonebot/nonebot2#2754]
### PyPI 项目名

nonebot-plugin-multigpt

### 插件 import 包名

nonebot_plugin_multigpt

### 标签

[{"label":"GPT","color":"#52d7ea"},{"label":"PPT","color":"#ea52c7"},{"label":"多模","color":"#eac252"}]

**Comment by XTxiaoting14332** [comment]
？

**Comment by XTxiaoting14332** [comment]
修改后直接在issue下回复即可
不要再开新的issue

**Comment by XTxiaoting14332** [comment]
你的代码中的``import nonebot``是没有必要的
还有nb插件不应该使用``requests``进行同步请求，请使用``httpx``发送异步请求，否则导致bot进程堵塞
还有请使用``localstore``来管理文件，而不是使用绝对路径，不是人人都在用Windows，也不是所有的Windows都有D盘

**Comment by syagina** [comment]
更改了

**Comment by XTxiaoting14332** [comment]
请将你插件中的``import nonebot``去掉

**Comment by RF-Tar-Railt** [comment]
> 请将你插件中的``import nonebot``去掉

错误的，是要把依赖里面的 nonebot去掉

**Comment by XTxiaoting14332** [comment]
> > 请将你插件中的`import nonebot`去掉
> 
> 错误的，是要把依赖里面的 nonebot去掉

哦还真是（

**Comment by syagina** [comment]
测试

**Comment by syagina** [comment]
测试

**Comment by syagina** [comment]
测试

**Comment by syagina** [comment]
测试

**Comment by RF-Tar-Railt** [comment]
首先，把你那个`onebot`依赖移除
其次，导入其他插件前需要先使用 require("插件包") 来导入插件

```python
from nonebot import require

require("nonebot_plugin_localstore")

from nonebot_plugin_localstore import ...
```

**Comment by XTxiaoting14332** [comment]
请声明插件依赖
在导入本地储存插件之前先``require``

```
from nonebot import require

require("nonebot_plugin_localstore")
```

**Comment by syagina** [comment]
收到！

**Comment by syagina** [comment]
有更改

**Comment by syagina** [comment]
修复bug

**Comment by syagina** [comment]
更改了README.md

**Comment by syagina** [comment]
更新

**Comment by yanyongyu** [comment]
你的插件依赖里多了一个 nonebot。获取插件配置项应该使用 `get_plugin_config`。数据存储应该使用 localstore 插件。另外你的 docx 没有写到包依赖里吧

**Comment by syagina** [comment]
> 你的插件依赖里多了一个 nonebot。获取插件配置项应该使用 `get_plugin_config`。数据存储应该使用 localstore 插件。另外你的 docx 没有写到包依赖里吧

新的pypi包已经改了

**Comment by yanyongyu** [comment]
请同步到你的gh仓库

**Comment by syagina** [comment]
> 请同步到你的gh仓库

已同步

**Comment by syagina** [comment]
测试

**Comment by syagina** [comment]
修改依赖

**Comment by RF-Tar-Railt** [comment]
你__init__里面的data dir也可以转用localstore

**Comment by syagina** [comment]
> 你__init__里面的data dir也可以转用localstore

我弄不好欸，可以帮我改一下吗

**Comment by RF-Tar-Railt** [comment]
自己读文档
https://nonebot.dev/docs/best-practice/data-storing

**Comment by syagina** [comment]
> 你__init__里面的data dir也可以转用localstore

已经完成，辛苦你们了

**Comment by syagina** [comment]
1

**Comment by syagina** [comment]
🥺求求了来个人给我审核吧🙈

**Comment by RF-Tar-Railt** [comment]
> 🥺求求了来个人给我审核吧🙈

第一，你插件里面有几个import写重复了可以删掉
第二，你的插件没有依赖任何ob11相关的特性，你可以把它们删掉了
第三，接上，你用的MessageSegment.text()的地方可以直接用字符串的

**Comment by RF-Tar-Railt** [comment]
还有一点，把你仓库里的那个pycache删了

**Comment by syagina** [comment]
> > 🥺求求了来个人给我审核吧🙈
> 
> 第一，你插件里面有几个import写重复了可以删掉 第二，你的插件没有依赖任何ob11相关的特性，你可以把它们删掉了 第三，接上，你用的MessageSegment.text()的地方可以直接用字符串的

done

**Comment by syagina** [comment]
谢谢大佬指点
