### ISSUE TITLE
Plugin: nonebot-plugin-xjie-weather

### ISSUE THREAD

**Issue by ajdgg** [nonebot/nonebot2#2755]
### PyPI 项目名

nonebot-plugin-xjie-weather

### 插件 import 包名

nonebot_plugin_xjie_weather

### 标签

[]

**Comment by ajdgg** [comment]
> 请把发图部分用nonebot-plugin-alconna或者其他相关插件重写，而非依赖onebotv11。适配器

好的

**Comment by ajdgg** [comment]
完成

**Comment by RF-Tar-Railt** [comment]
另外我看了一眼你插件里有类似等待用户输入的代码，我推荐换用 `waiter` 插件：https://github.com/RF-Tar-Railt/nonebot-plugin-waiter

**Comment by ajdgg** [comment]
更新导入nonebot_plugin_alconna

**Comment by ajdgg** [comment]
> 另外我看了一眼你插件里有类似等待用户输入的代码，我推荐换用 `waiter` 插件：https://github.com/RF-Tar-Railt/nonebot-plugin-waiter

好的，后面我会看看

**Comment by yanyongyu** [comment]
元数据里缺少支持的适配器，请继承alc，插件数据建议使用 localstore 插件存储。请勿使用 requests 进行同步网络请求，请使用 httpx 或者 aiohttp 进行异步请求。

**Comment by ajdgg** [comment]
更新元数据和使用httpx进行异步请求

**Comment by ajdgg** [comment]
更新

**Comment by ajdgg** [comment]
更新

**Comment by yanyongyu** [comment]
你的 httpx client 没有关闭
