### ISSUE TITLE
Plugin: nonebot-plugin-figure

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#2759]
### PyPI 项目名

nonebot-plugin-figure

### 插件 import 包名

figure

### 标签

[]

**Comment by RF-Tar-Railt** [comment]
你插件gh仓库就只有一个自述文件？

**Comment by KomoriDev** [comment]
> 你插件gh仓库就只有一个自述文件？

让我想起了一位故人（
