### ISSUE TITLE
Plugin: AnyMate小助手

### ISSUE THREAD

**Issue by QuickLAW** [nonebot/nonebot2#2760]
### PyPI 项目名

nonebot-plugin-anymate

### 插件 import 包名

nonebot_plugin_anymate

### 标签

[{"label":"server","color":"#ea5252"},{"label":"func","color":"#ea5252"}]

### 插件配置项

_No Response_

**Comment by RF-Tar-Railt** [comment]
你的插件有发布到github上吗

**Comment by QuickLAW** [comment]
> 你的插件有发布到github上吗

刚发

**Comment by RF-Tar-Railt** [comment]
第一，你的`config = Config.parse_obj`这段属于旧写法。请使用 

```python
from nonebot import get_plugin_config

config = get_plugin_config(Config)
```

第二，建议把文件夹命名为`nonebot_plugin_anymate`，gh仓库名字为
`nonebot-plugin-anymate`

**Comment by QuickLAW** [comment]
> 第一，你的`config = Config.parse_obj`这段属于旧写法。请使用
> 
> ```python
> from nonebot import get_plugin_config
> 
> config = get_plugin_config(Config)
> ```
> 
> 第二，建议把文件夹命名为`nonebot_plugin_anymate`，gh仓库名字为 `nonebot-plugin-anymate`

我们明白了，十分感谢

**Comment by afterow** [comment]
可以参考 https://github.com/A-kirami/nonebot-plugin-template 你的说明文件不是md格式的

**Comment by Hoshinonyaruko** [comment]
你好

**Comment by QuickLAW** [comment]
> 你们还有团队啊，膜

QWQ，没有得，怎么说呢，只是有些渊源

**Comment by QuickLAW** [comment]
> 可以参考 https://github.com/A-kirami/nonebot-plugin-template 你的说明文件不是md格式的

十分感谢，我去看看

**Comment by XTxiaoting14332** [comment]
请在依赖中加上``nonebot2``

**Comment by QuickLAW** [comment]
> 请在依赖中加上`nonebot2`

好，我懂了

**Comment by QuickLAW** [comment]
触发测试是，评论吗

**Comment by XTxiaoting14332** [comment]
pypi上发布新版本后评论就可以触发

**Comment by QuickLAW** [comment]
> 触发测试是，评论吗

测试测试

**Comment by QuickLAW** [comment]
> 触发测试是，评论吗

QAQ

**Comment by RF-Tar-Railt** [comment]
> 第一，你的`config = Config.parse_obj`这段属于旧写法。请使用 
> 
> ```python
> from nonebot import get_plugin_config
> 
> config = get_plugin_config(Config)
> ```
> 
> 第二，建议把文件夹命名为`nonebot_plugin_anymate`，gh仓库名字为
> `nonebot-plugin-anymate`
> 

你any_config也照着这里改

**Comment by QuickLAW** [comment]
> > 第一，你的`config = Config.parse_obj`这段属于旧写法。请使用
> > ```python
> > from nonebot import get_plugin_config
> > 
> > config = get_plugin_config(Config)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 第二，建议把文件夹命名为`nonebot_plugin_anymate`，gh仓库名字为
> > `nonebot-plugin-anymate`
> 
> 你any_config也照着这里改

改好了，只是发错文件了(((φ(◎ロ◎;)φ)))

**Comment by KomoriDev** [comment]
你这 `插件配置项` 怎么编辑了个表格出来？

**Comment by QuickLAW** [comment]
> 你这 `插件配置项` 怎么编辑了个表格出来？

感觉空着也是空着，我就把readme里的搬过来了。是有规范要求吗

**Comment by QuickLAW** [comment]
> > > 你这 `插件配置项` 怎么编辑了个表格出来？
> > 
> > 
> > 感觉空着也是空着，我就把readme里的搬过来了。是有规范要求吗
> 
> `插件配置项` 内的参数是 noneflow 在插件测试时使用的。你的配置若是可选项的话可以不用填（

原来如此，我悟了

**Comment by QuickLAW** [comment]
现在是，等等就行了吗

**Comment by KomoriDev** [comment]
> 现在是，等等就行了吗

是的

**Comment by QuickLAW** [comment]
> > 现在是，等等就行了吗
> 
> 是的

好的谢谢

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器。插件内请勿使用requests进行同步网络请求，请使用 httpx 或者 aiohttp 进行异步请求。数据库存储可以考虑使用 orm 插件或者使用 localstore 插件存放文件。

**Comment by QuickLAW** [comment]
> 插件元数据缺少支持的适配器。插件内请勿使用requests进行同步网络请求，请使用 httpx 或者 aiohttp 进行异步请求。数据库存储可以考虑使用 orm 插件或者使用 localstore 插件存放文件。

谢谢，稍微修改了一下

**Comment by yanyongyu** [comment]
你的插件不是依赖ob适配器的吗，支持的适配器请填写ob。

**Comment by yanyongyu** [comment]
@QuickLAW 记得更新

**Comment by RF-Tar-Railt** [comment]
第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api

第二，关于发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    msg = UniMessage.image(raw=xxx)
    await msg.send()
```

**Comment by QuickLAW** [comment]
> 第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api
> 
> 第二，关于发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97
> 
> 示例:
> ```python
> from nonebot_plugin_alconna import UniMessage
> 
> ...
> async def _():
>     msg = UniMessage.image(raw=xxx)
>     await msg.send()
> ```

明白了，过几天更新一下，加点功能

**Comment by yanyongyu** [comment]
@QuickLAW 两周了是否有更新？

**Comment by QuickLAW** [comment]
> @QuickLAW 两周了是否有更新？

出去玩了两周QAQ，更了，更了下新功能，修了bug

**Comment by QuickLAW** [comment]
测试

**Comment by QuickLAW** [comment]
> nonebot_plugin_apscheduler

再测！

**Comment by QuickLAW** [comment]
再测

**Comment by QuickLAW** [comment]
> 再测

测不动了

**Comment by XTxiaoting14332** [comment]
草

**Comment by QuickLAW** [comment]
还得测

**Comment by QuickLAW** [comment]
> > 再测
> 
> 测不动了

求求了，别测了

**Comment by yanyongyu** [comment]
你的插件缺少require，在导入别的插件前需要require

**Comment by QuickLAW** [comment]
> 你的插件缺少require，在导入别的插件前需要require

我靠对呀，两个插件我居然给忘了

**Comment by QuickLAW** [comment]
> 你的插件缺少require，在导入别的插件前需要require

谢谢大佬，十分感谢
