### ISSUE TITLE
Plugin: 鸣潮抽卡记录分析

### ISSUE THREAD

**Issue by BraveCowardp** [nonebot/nonebot2#2762]
### PyPI 项目名

nonebot-plugin-wwgachalogs

### 插件 import 包名

nonebot_plugin_wwgachalogs

### 标签

[{"label":"鸣潮","color":"#ea5252"}]

**Comment by RF-Tar-Railt** [comment]
第一，缺少 httpx依赖
第二，你时间够的话可以考虑用nb官方的`plugin-orm`来使用数据库（而不是直接用aiosqlite）
教程在https://nonebot.dev/docs/next/best-practice/database/

**Comment by BraveCowardp** [comment]
> 第一，缺少 httpx依赖 第二，你时间够的话可以考虑用nb官方的`plugin-orm`来使用数据库（而不是直接用aiosqlite） 教程在https://nonebot.dev/docs/next/best-practice/database/

好的，我修改一下

**Comment by BraveCowardp** [comment]
已添加httpx依赖，数据库暂时先不改了，数据比较简单（~主要是不太会用orm😭~）

**Comment by BraveCowardp** [comment]
第一次上传插件，才发现重新上传要手动改一下pyproject.toml的version，不然上传pypi的工作流一直失败，困扰了好长时间😭

**Comment by BraveCowardp** [comment]
机器人怎么没更新了

**Comment by BraveCowardp** [comment]
> 机器人怎么没更新了

是不是因为用了和之前一样的tag，更新了一下tag试试

**Comment by BraveCowardp** [comment]
奇怪，本地虚拟环境测试加载没问题，这上面测试怎么会超时呢，明天研究一下
![image](https://github.com/nonebot/nonebot2/assets/61410850/8b43b707-86ed-4a1d-93c8-7ee7842fc416)

**Comment by BraveCowardp** [comment]
改成orm插件使用数据库了

**Comment by yanyongyu** [comment]
你插件里的 aiosqlite 依赖可以移除了吧

**Comment by BraveCowardp** [comment]
> 你插件里的 aiosqlite 依赖可以移除了吧，如果你要在开发时使用，他应该是你的dev依赖

确实是多余的依赖，已经移除了
