### ISSUE TITLE
Plugin: nonebot-plugin-easymarkdown

### ISSUE THREAD

**Issue by phquathi** [nonebot/nonebot2#2766]
### PyPI 项目名

nonebot-plugin-easymarkdown

### 插件 import 包名

nonebot_plugin_easymarkdown

### 标签

[{"label":"code","color":"#5284ea"}]

**Comment by RF-Tar-Railt** [comment]
我觉得你完全可以把这个插件做成library类型的啊，为什么非得限制在ob里呢

**Comment by RF-Tar-Railt** [comment]
另外，请使用`nonebot_plugin_localstore`来存放你的pdf文件，或者你去使用`tempfile`库，在系统temp目录内存放你的pdf文件

**Comment by phquathi** [comment]
pdf发完就删了

**Comment by RF-Tar-Railt** [comment]
> pdf发完就删了
> 

即使如此我说的也是推荐行为。
