### ISSUE TITLE
Plugin: Daily Task

### ISSUE THREAD

**Issue by WMGray** [nonebot/nonebot2#2768]
### PyPI 项目名

 nonebot-plugin-daily-task

### 插件 import 包名

nonebot_plugin_daily_task

### 标签

[{"label":"每日任务","color":"#ea5252"}]

### 插件配置项

_No Response_

**Comment by RF-Tar-Railt** [comment]
第一，先 require 再 import
第二，请修改你的pyproject.toml里的description
第三，你的插件可以去用`plugin-orm`，教程：https://nonebot.dev/docs/next/best-practice/database/
第四，如果能够不依赖ob适配器最好（不改也没关系）

**Comment by WMGray** [comment]
> 第一，先 require 再 import 第二，请修改你的pyproject.toml里的description 第三，你的插件可以去用`plugin-orm`，教程：https://nonebot.dev/docs/next/best-practice/database/ 第四，如果能够不依赖ob适配器最好（不改也没关系）

okk

**Comment by WMGray** [comment]
update

**Comment by RF-Tar-Railt** [comment]
如果你仍然想用tinydb作为你的插件数据库，请通过`nonebot_plugin_localstore` 给出的路径来存放你的数据库文件（而非 `Path(__file__).parent` ）

**Comment by WMGray** [comment]
> 如果你仍然想用tinydb作为你的插件数据库，请通过`nonebot_plugin_localstore` 给出的路径来存放你的数据库文件（而非 `Path(__file__).parent` ）

好的，最近会改一下数据库

**Comment by WMGray** [comment]
update

**Comment by WMGray** [comment]
update

**Comment by WMGray** [comment]
> 你的插件依赖里怎么有nb-cli，另外你nb2需要fastapi驱动么？

emm 这个我当时直接用pdm安装的

**Comment by RF-Tar-Railt** [comment]
nb-cli与pdm是一样的应当装在全局环境下的

**Comment by RF-Tar-Railt** [comment]
另外如fastapi之类的你应该使用 pdm add -d fastapi 来将其分配在 dev 依赖中，与安装依赖区分

**Comment by WMGray** [comment]
> 另外如fastapi之类的你应该使用 pdm add -d fastapi 来将其分配在 dev 依赖中，与安装依赖区分
嗯嗯 好的

**Comment by WMGray** [comment]
update

**Comment by WMGray** [comment]
update

**Comment by WMGray** [comment]
update
