### ISSUE TITLE
Plugin: MCSM小助手

### ISSUE THREAD

**Issue by LiLuo-B** [nonebot/nonebot2#2770]
### PyPI 项目名

nonebot-plugin-mcsm

### 插件 import 包名

nonebot_plugin_mcsm

### 标签

[{"label":"MCSM","color":"#ea5252"},{"label":"应用托管","color":"#5272ea"},{"label":"服务器管理","color":"#4cc275"}]

### 插件配置项

```
mcsm_api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
mcsm_url=http://127.0.0.1:13983
mcsm_img_path=/root
```

**Comment by LiLuo-B** [comment]
已更改

**Comment by LiLuo-B** [comment]
已修复

**Comment by LiLuo-B** [comment]
已修复

**Comment by LiLuo-B** [comment]
test

**Comment by RF-Tar-Railt** [comment]
标题的插件名称是由你插件的__plugin_meta__ 的name决定的
这个name并不需要与你插件的pypi名称相同

**Comment by RF-Tar-Railt** [comment]
另外你的插件没有在github发布或公开。

**Comment by LiLuo-B** [comment]
> 标题的插件名称是由你插件的__plugin_meta__ 的name决定的 这个name并不需要与你插件的pypi名称相同

好的好的 已修改

**Comment by LiLuo-B** [comment]
test

**Comment by RF-Tar-Railt** [comment]
第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api
第二，你插件里面先event: MessageEvent再str(event.message)的写法可以写成message = EventMessage() 然后 str(message)
第三，关于发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

**Comment by RF-Tar-Railt** [comment]
示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    image = await instance_info_image(xxx)
    msg = UniMessage.image(raw=image)
    await msg.finish()
```

**Comment by RF-Tar-Railt** [comment]
因为用了alc的缘故，你的插件元数据内支持的适配器那一项应当继承 alc：使用 nb 提供的 inherit_supported_adapters 方法继承支持的适配器

示例：

```python
from nonebot.plugin import inherit_supported_adapters

support_adapters=inherit_supported_adapters("nonebot_plugin_alconna")
```

**Comment by LiLuo-B** [comment]
好的 已修改
