### ISSUE TITLE
Plugin: 绝地潜兵信息查询小助手

### ISSUE THREAD

**Issue by SherkeyXD** [nonebot/nonebot2#2771]
### PyPI 项目名

nonebot-plugin-helldivers

### 插件 import 包名

nonebot_plugin_helldivers

### 标签

[{"label":"helldivers","color":"#ffd700"}]

### 插件配置项

```dotenv
None
```

**Comment by SherkeyXD** [comment]
updated

**Comment by RF-Tar-Railt** [comment]
第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api

第三，关于回复以及发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    msg = UniMessage.image(path=xxx)
    await msg.send(reply_to=True)
```

**Comment by SherkeyXD** [comment]
Updated.

以及为什么只有一和三，二呢（

**Comment by RF-Tar-Railt** [comment]
因为用了saa的缘故，你的插件元数据内支持的适配器那一项应当继承 saa：使用 nb 提供的 inherit_supported_adapters 方法继承支持的适配器

示例：

```python
from nonebot.plugin import inherit_supported_adapters

supported_adapters=inherit_supported_adapters("nonebot_plugin_saa")
```

**Comment by SherkeyXD** [comment]
Updated
