### ISSUE TITLE
Plugin: asmr

### ISSUE THREAD

**Issue by CCYellowStar2** [nonebot/nonebot2#2774]
### PyPI 项目名

nonebot-plugin-asmr

### 插件 import 包名

nonebot_plugin_asmr

### 标签

[{"label":"asmr","color":"#ea5252"},{"label":"音声","color":"#ea5252"}]

**Comment by CCYellowStar2** [comment]
1

**Comment by CCYellowStar2** [comment]
1

**Comment by RF-Tar-Railt** [comment]
请把代码里面的print删掉，或者用logger

**Comment by CCYellowStar2** [comment]
更新

**Comment by RF-Tar-Railt** [comment]
你确定你代码最下面那个用音乐卡片发链接的部分可用吗

**Comment by CCYellowStar2** [comment]
> 你确定你代码最下面那个用音乐卡片发链接的部分可用吗

我这gocq可以用

**Comment by RF-Tar-Railt** [comment]
> > 你确定你代码最下面那个用音乐卡片发链接的部分可用吗
> 
> 那你们现在都是怎么发音乐卡片的

我意思是卡片不是只能网易云或者qq音乐或者啥吗（

**Comment by CCYellowStar2** [comment]
> > > 你确定你代码最下面那个用音乐卡片发链接的部分可用吗
> > 
> > 
> > 那你们现在都是怎么发音乐卡片的
> 
> 我意思是卡片不是只能网易云或者qq音乐或者啥吗（

你试过我的弄不了吗

**Comment by CCYellowStar2** [comment]
> > > 你确定你代码最下面那个用音乐卡片发链接的部分可用吗
> > 
> > 
> > 那你们现在都是怎么发音乐卡片的
> 
> 我意思是卡片不是只能网易云或者qq音乐或者啥吗（

所以我这个现在是要怎么样
