### ISSUE TITLE
Plugin: nonebot_plugin_obastatus

### ISSUE THREAD

**Issue by Dongyanmio** [nonebot/nonebot2#2779]
### PyPI 项目名

nonebot-plugin-obastatus

### 插件 import 包名

nonebot_plugin_obastatus

### 标签

[{"label":"BMCLAPI","color":"#5f82ba"}]

### 插件配置项

```dotenv
OBA_COOKIE="openbmclapi-jwt="
```

**Comment by RF-Tar-Railt** [comment]
你的插件没有发布到github上吗

**Comment by Dongyanmio** [comment]
> 你的插件没有发布到github上吗

确定发了

**Comment by Dongyanmio** [comment]
> > 你的插件没有发布到github上吗
> 
> 确定发了

另外就是，我不小心将私钥填写了（）

**Comment by RF-Tar-Railt** [comment]
> > 你的插件没有发布到github上吗
> 
> 确定发了

哪呢

**Comment by Dongyanmio** [comment]
https://github.com/Zero-Octagon/nonebot-plugin-obastatus

**Comment by Dongyanmio** [comment]
能帮忙删下issue吗

________________________________
发件人: Tarrailt ***@***.***>
发送时间: 2024年6月20日 18:34
收件人: nonebot/nonebot2 ***@***.***>
抄送: 冬烟mio ***@***.***>; Author ***@***.***>
主题: Re: [nonebot/nonebot2] Plugin: nonebot-plugin-obastatus (Issue #2779)


你的插件没有发布到github上吗

确定发了

哪呢

―

**Comment by Dongyanmio** [comment]
已更新

**Comment by Dongyanmio** [comment]
更新了

**Comment by RF-Tar-Railt** [comment]
第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api

第二，关于回复以及发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    msg = UniMessage.image(path=xxx)
    await msg.send(reply_to=True)
```

**Comment by Dongyanmio** [comment]
感谢大佬建议，已做出相关更改。

**Comment by RF-Tar-Railt** [comment]
你发图那里应该用UniMessage.image(url="xxxxx")

**Comment by yanyongyu** [comment]
你的scheduler执行的reload cache应该使用异步函数，httpx也应该使用异步client。你的依赖nonebot2版本应该是`2.2.0`以上。

**Comment by Dongyanmio** [comment]
updata

**Comment by yanyongyu** [comment]
你的httpx依然没有使用异步方法

**Comment by Dongyanmio** [comment]
很抱歉打扰这么多次，遇到了点问题，在执行无参数指令时会默认将下一次发送的信息作为上一个指令的参数进行解析，我想不出如何解决，所以httpx可能要暂时搁置。

**Comment by Dongyanmio** [comment]
已更新

**Comment by yanyongyu** [comment]
¿ 你的httpx用法完全不对啊，请参考httpx文档使用异步client `AsyncClient`

**Comment by he0119** [comment]
你应该参考这个 <https://www.python-httpx.org/async/>，然后改成这种感觉：

```python
async def reload_cache():
    async with httpx.AsyncClient() as client:
        version = (await client.get('https://bd.bangbang93.com/openbmclapi/metric/version', headers=headers)).json()
```

**Comment by Dongyanmio** [comment]
或许真成异步了？但好像写得还是假异步？

**Comment by yanyongyu** [comment]
你的代码里仍然有一处未修改 https://github.com/Zero-Octagon/nonebot-plugin-obastatus/blob/4bc9ea9e7475d316cdb1cc77c6ab37030b71804a/nonebot_plugin_obastatus/__init__.py#L355 。使用异步方式编写不会影响其他插件的并行执行。

**Comment by Dongyanmio** [comment]
> 你的代码里仍然有一处未修改 https://github.com/Zero-Octagon/nonebot-plugin-obastatus/blob/4bc9ea9e7475d316cdb1cc77c6ab37030b71804a/nonebot_plugin_obastatus/__init__.py#L355 。使用异步方式编写不会影响其他插件的并行执行。

很抱歉打扰了这么久，这次改完应该是将提出的要求解决了
