### ISSUE TITLE
Plugin: EVE ONLINE 多功能机器人
版本 - v0.2.3


### ISSUE THREAD

**Issue by zifox666** [nonebot/nonebot2#2781]
### PyPI 项目名

nonebot-plugin-eve-tool

### 插件 import 包名

nonebot_plugin_eve_tool

### 标签

[{"label":"game","color":"#ea5252"},{"label":"eve","color":"#ea5252"}]

### 插件配置项

```dotenv
EVE_MYSQL_PASSWORD={your_password}
```

**Comment by RF-Tar-Railt** [comment]
第一，检查你的 `aioredis`，去GitHub上搜一下相关issue，或者看有没有新版本的 “aioredis”

第二，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api

第三，关于发图，你都用 alc插件了，直接上UniMessage 发图。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    image = await instance_info_image(xxx)
    msg = UniMessage.image(raw=image)
    await msg.finish()
```

第四，因为用了alc的缘故，你的插件元数据内支持的适配器那一项应当继承 alc：使用 nb 提供的 inherit_supported_adapters 方法继承支持的适配器

示例：

```python
from nonebot.plugin import inherit_supported_adapters

supported_adapters=inherit_supported_adapters("nonebot_plugin_alconna")
```

**Comment by zifox666** [comment]
谢谢大佬，已更新
aioredis采用try except大法
其他建议已经修改

**Comment by zifox666** [comment]
又更新了点小问题-。-

**Comment by RF-Tar-Railt** [comment]
另外数据库方面你先看看nb教程：https://nonebot.dev/docs/best-practice/database/

**Comment by zifox666** [comment]
已更新，谢谢大佬辅导

**Comment by zifox666** [comment]
把aioredis全面换成redis了，希望能正常加载>.<

**Comment by zifox666** [comment]
...

**Comment by zifox666** [comment]
对不起疯狂打扰各位大佬，这下应该是正确的版本号了

**Comment by RF-Tar-Railt** [comment]
@yanyongyu 你看看有没有啥问题

**Comment by yanyongyu** [comment]
你的插件依赖里怎么还有requests，还有你的numpy、jinja等依赖并未使用。

**Comment by zifox666** [comment]
谢谢大佬，已更新，把requests替换成了aiohttp。request,numpy已经移除，jinjia将会用到所以没有删去。httpx没法删，那个接口处理逻辑aiohttp莫名其妙获取不到数据。

**Comment by yanyongyu** [comment]
你的插件加载出错了，缺少文件

**Comment by zifox666** [comment]
已更新

**Comment by yanyongyu** [comment]
还是有问题？

**Comment by zifox666** [comment]
已更新
由于需要判断加群事件所以添加了ob依赖，删去了多余的依赖
