### ISSUE TITLE
Plugin: b站消息转发

### ISSUE THREAD

**Issue by BraveCowardp** [nonebot/nonebot2#2784]
### PyPI 项目名

nonebot-plugin-biliforward

### 插件 import 包名

nonebot_plugin_biliforward

### 标签

[{"label":"bilibili","color":"#ea5252"},{"label":"哔哩哔哩","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
你插件依赖里有明显的错误 https://github.com/BraveCowardp/nonebot-plugin-biliforward/blob/dd7d16bd1d1f5d79821b05842a9f647ff27d8687/pyproject.toml#L19 。

**Comment by BraveCowardp** [comment]
> 你插件依赖里有明显的错误 https://github.com/BraveCowardp/nonebot-plugin-biliforward/blob/dd7d16bd1d1f5d79821b05842a9f647ff27d8687/pyproject.toml#L19 。

这个有什么错误

**Comment by BraveCowardp** [comment]
我好像明白了，开发者不应该在依赖里指定数据库驱动？已经修改了

**Comment by RF-Tar-Railt** [comment]
你可以写在dev依赖里
