### ISSUE TITLE
Plugin: QQ群-Discord 互通

### ISSUE THREAD

**Issue by Autuamn** [nonebot/nonebot2#2787]
### PyPI 项目名

nonebot-plugin-dcqq-relay

### 插件 import 包名

nonebot_plugin_dcqq_relay

### 标签

[{"label":"消息互通","color":"#428fdb"}]

### 插件配置项

```dotenv
DCQQ_RELAY_CHANNEL_LINKS=[]
DCQQ_RELAY_UNMATCH_BEGINNING=["/"]
```

**Comment by RF-Tar-Railt** [comment]
你qq频道互通你用ob11适配器干什么

**Comment by Autuamn** [comment]
艹，忘记改了

已改
