### ISSUE TITLE
Plugin: nonebot-plugin-discord-message-bridge

### ISSUE THREAD

**Issue by xxtg666** [nonebot/nonebot2#2789]
### PyPI 项目名

nonebot-plugin-discord-message-bridge

### 插件 import 包名

nonebot_plugin_discord_message_bridge

### 标签

[{"label":"消息转发","color":"#ea5252"}]

### 插件配置项

```dotenv
dmb_bot_token="xxx"
dmb_webhook_url="xxx"
dmb_webhook_id=0
dmb_guild_id=0
dmb_channel_id=0
dmb_qq_id=0
dmb_qq_forward_failed="cry"
dmb_max_reply_preview_length=100
dmb_http_proxy="http://127.0.0.1:7890"
dmb_prefix="[Discord] "
dmb_bot_name="Discord Message Bridge"
dmb_qq_sudo_format="/sudo {Q} {C}"
dmb_qq_command="dmb"
dmb_discord_command_prefix="~"
dmb_qq_command_prefix="."
```

**Comment by xxtg666** [comment]
是的，自己做的，目前正在改发布的bug……

**Comment by RF-Tar-Railt** [comment]
我先就说两句，第一，nonebot有discord适配器，第二，你最好先去参考一下社区里别的相同类型的插件怎么实现的

**Comment by xxtg666** [comment]
那确实，我这样实现bug比较多，实在不行就不发了吧……

**Comment by KomoriDev** [comment]
或许你可以借鉴社区里的 [QQ频道-Discord 插件](https://github.com/Autuamn/nonebot-plugin-dcqg-relay)以优化你的代码 
~~你的代码还有不少问题，目前不能通过~~
