### ISSUE TITLE
Plugin: 指令更新NapCat

### ISSUE THREAD

**Issue by tianyisama** [nonebot/nonebot2#2790]
### PyPI 项目名

nonebot-plugin-ncupdate

### 插件 import 包名

nonebot_plugin_ncupdate

### 标签

[{"label":"NapCat","color":"#ea5252"}]

**Comment by tianyisama** [comment]
再试一次

**Comment by yanyongyu** [comment]
你插件的依赖nb版本过于古老。你的插件配置项读取方式不正确，请参考文档 配置 章节，并在插件元数据内添加配置。

**Comment by tianyisama** [comment]
> 你插件的依赖nb版本过于古老。你的插件配置项读取方式不正确，请参考文档 配置 章节，并在插件元数据内添加配置。

好的，过一会修改

**Comment by tianyisama** [comment]
> 你插件的依赖nb版本过于古老。你的插件配置项读取方式不正确，请参考文档 配置 章节，并在插件元数据内添加配置。

ok
