### ISSUE TITLE
Plugin: nonebot-plugin-mai-online-lineup

### ISSUE THREAD

**Issue by shengwang52005** [nonebot/nonebot2#2792]
### PyPI 项目名

nonebot-plugin-mai-online-lineup

### 插件 import 包名

nonebo_plugin_mai_online_lineup

### 标签

[{"label":"舞萌","color":"#ea5252"},{"label":"Maimai","color":"#ea5252"},{"label":"在线排队","color":"#229cd5"}]

修改issue*2

**Comment by RF-Tar-Railt** [comment]
你依赖写错了，应该是nonebot2而不是nonebot

**Comment by shengwang52005** [comment]
import包名填错了，应该改为下划线==
重开一下（）
