### ISSUE TITLE
Plugin: 鸣潮wiki

### ISSUE THREAD

**Issue by shi-yingyingjiang** [nonebot/nonebot2#2801]
### PyPI 项目名

nonebot-plugin-WWwiki

### 插件 import 包名

nonebot_plugin_WWwiki

### 标签

[{"label":"鸣潮","color":"#ea5252"},{"label":"wiki","color":"#30af29"}]

**Comment by he0119** [comment]
也许那个库叫 [Pillow](https://pypi.org/project/pillow/)。

**Comment by shi-yingyingjiang** [comment]
> 也许那个库叫 [Pillow](https://pypi.org/project/pillow/)。

已经发现了，太难绷了

**Comment by shi-yingyingjiang** [comment]
已更新

**Comment by shi-yingyingjiang** [comment]
漏个bs4,上不来气了

**Comment by RF-Tar-Railt** [comment]
第一，你的插件可以移除onebotv11的依赖，因为你并没有依赖ob特有的api

第二，关于发图，你可以使用 alc插件或者saa插件。教程：https://nonebot.dev/docs/next/best-practice/alconna/uniseg#%E9%80%9A%E7%94%A8%E6%B6%88%E6%81%AF%E5%BA%8F%E5%88%97

示例:
```python
from nonebot_plugin_alconna import UniMessage

...
async def _():
    img: BytesIO = ...
    await UniMessage.image(raw=img).send()
```

第三，有关文件路径的部分推荐使用 `pathlib` 而不是 os.path，教程：https://graiax.cn/appendix/tips/pathlib 和 https://docs.python.org/zh-cn/3/library/pathlib.html

**Comment by RF-Tar-Railt** [comment]
第四，你可以去使用 `nonebot-plugin-htmlrender` 来替换你插件中关于 playwright的调用部分（要么你自己找个地方负责持久化 playwright的启动，不然插件每执行一次都要启动一次playwright

**Comment by RF-Tar-Railt** [comment]
https://github.com/shi-yingyingjiang/nonebot-plugin-WWwiki/pull/1

**Comment by shi-yingyingjiang** [comment]
已更新

**Comment by RF-Tar-Railt** [comment]
你真的在用poetry吗（

**Comment by shi-yingyingjiang** [comment]
> 你真的在用poetry吗（

没，用的setuptools

**Comment by RF-Tar-Railt** [comment]
> > 你真的在用poetry吗（
> 
> 没，用的setuptools

。。。既然如此你还是学一下pdm吧

**Comment by shi-yingyingjiang** [comment]
> > > 你真的在用诗歌吗（
> > 
> > 
> > 没，用的setuptools
> 
> 。。。既然如此，你还是学一下pdm吧

我把lxml拼成xlml了
