### ISSUE TITLE
Plugin: 学习强国挂机

### ISSUE THREAD

**Issue by TeenStudyFlow** [nonebot/nonebot2#2808]
### PyPI 项目名

XXQG

### 插件 import 包名

XXQG

### 标签

[{"label":"学习强国","color":"#e0d31c"}]

### 插件配置项

```dotenv
local_browser_path=""
```

**Comment by RF-Tar-Railt** [comment]
？你repo在哪

**Comment by RF-Tar-Railt** [comment]
？你确定要让插件pypi名叫这名字？

**Comment by TeenStudyFlow** [comment]
> ？你确定要让插件pypi名叫这名字？
> 
> 别的不说，你这插件里面功能是足够单拿出去作为一个sdk的

这只是我采集数据的时候顺手写的，你可以拉取代码进行魔改。

**Comment by RF-Tar-Railt** [comment]
不是哥们，你知道pypi名是什么意思吗

**Comment by TeenStudyFlow** [comment]
> 不是哥们，你知道pypi名是什么意思吗
pypi有问题吗
![Clip_2024-07-11_18-03-05](https://github.com/nonebot/nonebot2/assets/143619319/b644fac0-c66e-414e-ba6f-c68ceed3229a)

**Comment by RF-Tar-Railt** [comment]
> > 不是哥们，你知道pypi名是什么意思吗
> pypi有问题吗
> ![Clip_2024-07-11_18-03-05](https://github.com/nonebot/nonebot2/assets/143619319/b644fac0-c66e-414e-ba6f-c68ceed3229a)
> 

我就是给你个建议，pypi名毕竟不是你在插件商店里的名字，你现在拿所谓nb插件而不是sdk占用了这个名字，那后面别人要上传一个学习强国相关的sdk你怎么办呢

本来你这也可以把核心功能拎出来作为一个sdk，再开一个插件来引用它的

**Comment by TeenStudyFlow** [comment]
> > > 不是哥们，你知道pypi名是什么意思吗
> > > pypi有问题吗
> > > ![Clip_2024-07-11_18-03-05](https://private-user-images.githubusercontent.com/143619319/347774470-b644fac0-c66e-414e-ba6f-c68ceed3229a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTMyMjEsIm5iZiI6MTcyMDY5MjkyMSwicGF0aCI6Ii8xNDM2MTkzMTkvMzQ3Nzc0NDcwLWI2NDRmYWMwLWM2NmUtNDE0ZS1iYTZmLWM2OGNlZWQzMjI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWI3YjU0NjQ4ZGZjNTJmZmEyYjU3MTMzYWJlMDMyNWM3YjZkMTUwZDYwYmFhYWY5YjBjYTI2YmVjNGZjMDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AnaxPGC_TZBYwcm3n32_6wjTjcxrTjFv7B6t7rSboCQ)
> 
> 我就是给你个建议，pypi名毕竟不是你在插件商店里的名字，你现在拿所谓nb插件而不是sdk占用了这个名字，那后面别人要上传一个学习强国相关的sdk你怎么办呢
> 
> 本来你这也可以把核心功能拎出来作为一个sdk，再开一个插件来引用它的
后续真的有人需要这个名字来传SDK的话，可以发邮件，本身这只是我采集数据时顺手写的插件。

**Comment by j1g5awi** [comment]
已經占了，現在讓他改好像也没什麽用了……

**Comment by yanyongyu** [comment]
你是用了 nonebot 2.2.0+ 的方法，请修改依赖版本。数据库存储路径应该提供配置项或者使用 localstore 插件，而非直接存储在项目目录。

**Comment by yanyongyu** [comment]
是否有更新？
