### ISSUE TITLE
Plugin: wordle

### ISSUE THREAD

**Issue by shiyihang2007** [nonebot/nonebot2#2817]
### PyPI 项目名

nonebot-plugin-wordle-simple

### 插件 import 包名

nonebot_plugin_wordle_simple

### 标签

[]

### 插件配置项

```dotenv
WORDLE__GROUPS_ENABLED=["白名单群聊, 格式为字符串列表"]
```

**Comment by shiyihang2007** [comment]
修改了依赖项

**Comment by KomoriDev** [comment]
https://github.com/shiyihang2007/nonebot-plugin-wordle-simple/blob/ec26afa50d6e726356a7b5ac2da730a77ac41097/nonebot_plugin_wordle_simple/config.py#L5-L6

所用的 `set[]` 是 3.10+ 的写法，而你的 pyproject.toml 写的是 3.8+

**Comment by shiyihang2007** [comment]
> https://github.com/shiyihang2007/nonebot-plugin-wordle-simple/blob/ec26afa50d6e726356a7b5ac2da730a77ac41097/nonebot_plugin_wordle_simple/config.py#L5-L6
> 
> 所用的 `set[]` 是 3.10+ 的写法，而你的 pyproject.toml 写的是 3.8+

坏了，我本地用的是 3.12，所以没注意

**Comment by shiyihang2007** [comment]
fixed

**Comment by yanyongyu** [comment]
你的插件内使用了 nonebot 2.2.0+ 的方法，请修改依赖版本。

**Comment by shiyihang2007** [comment]
已修改为 >=2.2.0
