### ISSUE TITLE
Plugin: vv_helper

### ISSUE THREAD

**Issue by SwedishDoveCooker** [nonebot/nonebot2#2820]
### PyPI 项目名

nonebot-plugin-weiweibot

### 插件 import 包名

nonebot_plugin_weiweibot

### 标签

[]

### 插件配置项

_No Response_

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by KomoriDev** [comment]
1. __init__.py 44 行
```py
- username: str = None
+ username: Optional[str] = None
```
2. `SESSION_EXPIRE_TIMEOUT` 配置并未在 `config.py` 中写出
3. 不建议使用 `from moudle import *` ，详见 [PEP8](https://peps.python.org/pep-0008/#imports)

**Comment by SwedishDoveCooker** [comment]
已修改🥹🥹🥹

**Comment by KomoriDev** [comment]
？

**Comment by XTxiaoting14332** [comment]
?

**Comment by SwedishDoveCooker** [comment]
🤔你说的我应该都改了啊, 你们这里看不到吗

**Comment by SwedishDoveCooker** [comment]
🤔你说的我应该都改了啊, 你们这里看不到吗

**Comment by lengmianzz** [comment]
> 🤔你说的我应该都改了啊, 你们这里看不到吗

请确保修改后的文件上传到github

 注意查看发布检查结果， 
1.你的插件并没有元数据
 请参考NB文档（https://nonebot.dev/docs/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE）
2.插件存在报错

**Comment by SwedishDoveCooker** [comment]
已经修改了, 感谢指正🥹🥹🥹

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by SwedishDoveCooker** [comment]
已修改

**Comment by yanyongyu** [comment]
你的机器人响应了基类事件，但用了 onebot 协议进行了回复，这会产生问题，你可以限制响应的事件类型为 onebot 事件，或者使用 alconna uniseg 跨平台插件。另外你的插件 config 内容是 nb 内置的配置，你可以直接从 driver 获取而不需要自己读取。另外你的日志为什么要写入 logfile 而不是用 nb 提供的 logger。

**Comment by SwedishDoveCooker** [comment]
已修改, 之前理解有点小杯🥹🥹🥹

**Comment by yanyongyu** [comment]
你 Bot Message 类导入的依然是基类。不用的 config 记得删除。

**Comment by SwedishDoveCooker** [comment]
已修改🥹🥹🥹
