### ISSUE TITLE
Plugin: 每日油价

### ISSUE THREAD

**Issue by wyeeeee** [nonebot/nonebot2#2821]
### PyPI 项目名

nonebot-plugin-daily-oil-price

### 插件 import 包名

nonebot_plugin_daily_oil_price

### 标签

[]

**Comment by he0119** [comment]
<https://github.com/wyeeeee/nonebot-plugin-daily-oil-price/blob/d3477f38506f11af9f8c7bb7c5db6db101c90d04/nonebot_plugin_daily_oil_price/__init__.py#L23>

插件元数据中的主页不应该为空。

**Comment by wyeeeee** [comment]
fixed
后续会改为图片，考虑使用其他多平台方案

**Comment by wyeeeee** [comment]
Updated

**Comment by yanyongyu** [comment]
你的插件配置项读取部分采用了旧版方式，请参考 nb 文档 配置 部分改写为新版本使用方法。数据文件建议使用 localstore 插件存储，不要存储在插件目录安装下。

**Comment by wyeeeee** [comment]
fixed
