### ISSUE TITLE
Plugin: nonebot_plugin_game_torrent

### ISSUE THREAD

**Issue by Cvandia** [nonebot/nonebot2#2826]
### PyPI 项目名

nonebot-plugin-game-torrent

### 插件 import 包名

nonebot_plugin_game_torrent

### 标签

[]

**Comment by Cvandia** [comment]
Update

**Comment by yanyongyu** [comment]
你使用了 nb 2.2.0+ 的方法，请修改你的插件依赖版本。

**Comment by Cvandia** [comment]
fixed
