### ISSUE TITLE
能否拓展一下get_group_info()接口返回的数据（字段）

### ISSUE THREAD

**Issue by Lebron-Bryant** [nonebot/nonebot2#283]
**是否在使用中遇到某些问题而需要新的特性？请描述：**
我在调用get_group_info（）接口时，发现返回的数据字段只有四个，分别是：
group_id(群号)、group_name（群名称）max_member_count（群规模）member_count（群成员个数）

**描述你所需要的特性：**

能否增加一下群简介、群创建时间和群头像这些字段呢。

**Comment by yanyongyu** [comment]
上报字段由 `go-cqhttp` 以及 `onebot` 标准决定，与nonebot无关

**Comment by Lebron-Bryant** [comment]
> 上报字段由 `go-cqhttp` 以及 `onebot` 标准决定，与nonebot无关。
> 
> 如果有需求，前往go-cqhttp提出



> 上报基线由`go-cqhttp`以及`onebot`标准决定，与nonebot无关。
> 
> 如果有需求，前往go-cqhttp提出

好的
