### ISSUE TITLE
Plugin: exe_code

### ISSUE THREAD

**Issue by wyf7685** [nonebot/nonebot2#2834]
### PyPI 项目名

nonebot-plugin-exe-code

### 插件 import 包名

nonebot_plugin_exe_code

### 标签

[]

### 插件配置项

```dotenv
EXE_CODE__USER=["{user_id}"]
EXE_CODE__GROUP=["{group_id}"]
```

**Comment by RF-Tar-Railt** [comment]
弱问一句，你这个插件有经过充分的防注入测试吗

**Comment by wyf7685** [comment]
插件编写的初衷是为了在QQ上对nb进行运行时侵入式修改，基本上是面向开发者的，所以没有对应防御措施。

代码处理参考 [这里](https://github.com/wyf7685/nonebot-plugin-exe-code/blob/master/nonebot_plugin_exe_code/code_context.py#L91)

由于对Bot的操作权限较高，插件要求用户在配置项里填入指定 用户ID/群组ID 后才能使用
