### ISSUE TITLE
Plugin: 命令行

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#2839]
### PyPI 项目名

nonebot-plugin-system-command

### 插件 import 包名

nonebot_plugin_system_command

### 标签

[]

### 插件配置项

```env
SYS_CMD_SH="/sh"
SYS_CMD_CMD="/cmd"
```

**Comment by KomoriDev** [comment]
`on_command` 是带 COMMAND_START 的，不要在里面额外加上 `/`

**Comment by tkgs0** [comment]
> `on_command` 是带 COMMAND_START 的，不要在里面额外加上 `/`

防止用户设置 COMMAND_START=[""] 时Bot无差别响应用户发送的sh开头的消息, 所以加了额外的 `/`

**Comment by KomoriDev** [comment]
> > `on_command` 是带 COMMAND_START 的，不要在里面额外加上 `/`
> 
> 防止用户设置 COMMAND_START=[""] 时Bot无差别响应用户发送的sh开头的消息, 所以加了额外的 `/`

不是限 SUPERUSER 使用吗，这么为难超级用户真的好吗（

**Comment by tkgs0** [comment]
> > > `on_command` 是带 COMMAND_START 的，不要在里面额外加上 `/`
> > 
> > 
> > 防止用户设置 COMMAND_START=[""] 时Bot无差别响应用户发送的sh开头的消息, 所以加了额外的 `/`
> 
> 不是限 SUPERUSER 使用吗，这么为难超级用户真的好吗（

你说的非常有道理, 但是我感觉直接去掉额外的 `/` 还是有很大的风险; 因此我将插件修改为可在 `.env*` 中自定义触发指令, 可以让用户自己决定用什么样的指令来触发本插件

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器，支持所有适配器请显式指定为`None`。另外你的代码里为什么需要escape和unescape消息。

**Comment by tkgs0** [comment]
> 插件元数据缺少支持的适配器，支持所有适配器请显式指定为`None`。另外你的代码里为什么需要unescape消息，plain text是不需要unescape的。

已指定supported_adapters=None, 已删除unescape
