### ISSUE TITLE
Plugin: 基于清影的AI视频生成

### ISSUE THREAD

**Issue by Alpaca4610** [nonebot/nonebot2#2842]
### PyPI 项目名

nonebot-plugin-cogvideox

### 插件 import 包名

nonebot_plugin_cogvideox

### 标签

[{"label":"AI","color":"#ea5252"},{"label":"视频生成","color":"#1a30b7"}]

### 插件配置项

```dotenv
ZHIPU_KEY="xxxxxxxxxxxxxx"
```

**Comment by Alpaca4610** [comment]
插件已经做了异步请求的处理，测试生成AI视频时不会影响其他插件的正常触发运行。

**Comment by yanyongyu** [comment]
插件使用了旧版本的配置读取方式，请更新到新版本并升级依赖的 nb 版本到 2.2.0+ 。

**Comment by Alpaca4610** [comment]
update
