### ISSUE TITLE
Plugin: 谁是卷王

### ISSUE THREAD

**Issue by KomoriDev** [nonebot/nonebot2#2848]
### PyPI 项目名

nonebot-plugin-wakatime

### 插件 import 包名

nonebot_plugin_wakatime

### 标签

[{"label":"WakaTime","color":"#000000"}]

**Comment by KomoriDev** [comment]
fixed

**Comment by KomoriDev** [comment]
fixed

**Comment by yanyongyu** [comment]
插件依赖中不应该指定驱动器和数据库类型。插件元数据缺少支持的适配器。
