### ISSUE TITLE
Plugin: 奇怪的小功能

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#2850]
### PyPI 项目名

nonebot-plugin-function

### 插件 import 包名

nonebot_plugin_function

### 标签

[]

**Comment by zhongwen-4** [comment]
0.1.2

**Comment by zhongwen-4** [comment]
0.1.3

**Comment by zhongwen-4** [comment]
0.1.4

**Comment by zhongwen-4** [comment]
0.1.5

**Comment by zhongwen-4** [comment]
0.1.5

**Comment by zhongwen-4** [comment]
0.1.6

**Comment by zhongwen-4** [comment]
0.1.7

**Comment by zhongwen-4** [comment]
增加usage

**Comment by zhongwen-4** [comment]
增加主页链接

**Comment by zhongwen-4** [comment]
0.1.8

**Comment by zhongwen-4** [comment]
更新主页使用方法

**Comment by yanyongyu** [comment]
你都用 alconna 了为什么不写成跨平台的。。？另外你的httpx用法不太正确，不需要自己quote和拼接参数，你可以用params传。

**Comment by zhongwen-4** [comment]
> 你都用 alconna 了为什么不写成跨平台的。。？另外你的httpx用法不太正确，不需要自己quote和拼接参数，你可以用params传。

跨平台的话就算了,这种破插件没必要跨平台()

**Comment by zhongwen-4** [comment]
更新httpx用法

**Comment by yanyongyu** [comment]
你的GitHub仓库是不是没有更新

**Comment by zhongwen-4** [comment]
> 你的GitHub仓库是不是没有更新

啊,抱一丝,刚刚看到, 刚刚更新了
