### ISSUE TITLE
Plugin: SunoAI音乐生成

### ISSUE THREAD

**Issue by CCYellowStar2** [nonebot/nonebot2#2852]
### PyPI 项目名

nonebot-plugin-sunoai

### 插件 import 包名

nonebot_plugin_sunoai

### 标签

[{"label":"SunoAi","color":"#ea5252"},{"label":"AI歌曲","color":"#ea5252"}]

### 插件配置项

```dotenv
SUNO_KEY="sk-xxxxxxxxxxxx"
```

**Comment by KomoriDev** [comment]
关于 Alconna 的 Option
```py
Option(
    "--prompt",
	Args["prompt", StrMulti],
    alias=("-p",),
    default=None,
    help_text="使用简单模式 Prompt(使用后无需其他参数)",
),
```
可以直接写成
```py
Option(
    "-p|--prompt",
	Args["prompt", StrMulti],
    default=None,
    help_text="使用简单模式 Prompt(使用后无需其他参数)",
),
```

**Comment by CCYellowStar2** [comment]
> 关于 Alconna 的 Option，可以：
> 
> ```diff
> Option(
> +	"-p|--prompt",
> 	Args["prompt", StrMulti],
> -	alias=("-p",),
> 	default=None,
> 	help_text="使用简单模式 Prompt(使用后无需其他参数)",
> ),
> ```

这个改不改好像不影响使用（）
