### ISSUE TITLE
Plugin: 🦌管签到

### ISSUE THREAD

**Issue by SamuNatsu** [nonebot/nonebot2#2858]
### PyPI 项目名

nonebot-plugin-deer-pipe

### 插件 import 包名

nonebot_plugin_deer_pipe

### 标签

[]

**Comment by zty012** [comment]
给bot都冲晕了

**Comment by SamuNatsu** [comment]
v0.0.3

**Comment by SamuNatsu** [comment]
v0.0.4

**Comment by AzideCupric** [comment]
可以使用 [loacalstore](https://nonebot.dev/docs/best-practice/data-storing) 来存储数据（

**Comment by SamuNatsu** [comment]
> 可以使用 [loacalstore](https://nonebot.dev/docs/best-practice/data-storing) 来存储数据（

我看他这个 localstore 把路径写死到用户目录下，我 docker 还要额外 volume 一下用户目录来持久化数据，懒，不如直接塞插件目录

**Comment by AzideCupric** [comment]
> 这个 localstore 把路径写死到用户目录下

```python
class Config(BaseModel):
    localstore_cache_dir: Optional[Path] = None
    localstore_config_dir: Optional[Path] = None
    localstore_data_dir: Optional[Path] = None
```

可以通过环境变量指定位置，文档没写（

**Comment by SamuNatsu** [comment]
> > 这个 localstore 把路径写死到用户目录下
> 
> ```python
> class Config(BaseModel):
>     localstore_cache_dir: Optional[Path] = None
>     localstore_config_dir: Optional[Path] = None
>     localstore_data_dir: Optional[Path] = None
> ```
> 
> 可以通过环境变量指定位置，文档没写（

……

文档都不写全，甲级战犯

**Comment by yanyongyu** [comment]
插件数据请勿存放在插件目录下，请使用 localstore 或提供配置项。插件元数据缺少支持的适配器，请显示指定支持所有适配器。

**Comment by SamuNatsu** [comment]
> 插件数据请勿存放在插件目录下，请使用 localstore 或提供配置项。插件元数据缺少支持的适配器，请显示指定支持所有适配器。

在改了.jpg

**Comment by SamuNatsu** [comment]
v0.0.5

**Comment by SamuNatsu** [comment]
v0.0.6

**Comment by yanyongyu** [comment]
> 另外问一嘴，在 `setuptools` 的 `pyproject.toml` 依赖中是一定得有一个适配器依赖才能使得检查 bot 正常运行吗

你插件依赖了什么适配器就写什么，没有就不用

**Comment by SamuNatsu** [comment]
v0.1.0

**Comment by SamuNatsu** [comment]
v0.1.3

**Comment by SamuNatsu** [comment]
v0.1.4

**Comment by SamuNatsu** [comment]
retest v0.1.4

**Comment by yanyongyu** [comment]
> v0.2.0

新版本不用在这再更新了，registry 会自动更新。
