### ISSUE TITLE
Plugin: 漂流瓶

### ISSUE THREAD

**Issue by luosheng520qaq** [nonebot/nonebot2#2860]
### PyPI 项目名

nonebot-plugin-web-bottle

### 插件 import 包名

nonebot_plugin_web_bottle

### 标签

[{"label":"漂流瓶","color":"#689dd0"},{"label":"审核","color":"#e3567b"}]

### 插件配置项

```dotenv
DRIVER=~fastapi
```

**Comment by bingqiu456** [comment]
> 已修改

🥰

**Comment by luosheng520qaq** [comment]
![3cbc1db1a578a77484ec3654f193f85b](https://github.com/user-attachments/assets/7317145a-71f9-46f1-9227-6b5a3c32b746)

**Comment by luosheng520qaq** [comment]
> # 📃 商店发布检查结果
> > 插件：nonebot-plugin-web-bottle
> 
> **⚠️在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-web-bottle 的信息如下：
>        name         : nonebot-plugin-web-bottle 
>        version      : 0.0.9                     
>        description  : 有web的漂流瓶                  
>       
>       dependencies
>        - aiofiles >=23.2.1
>        - fastapi >=0.110.0
>        - httpx >=0.23.0
>        - nonebot_plugin_localstore >=0.7.0
>        - pydantic >=1.10.11
>   插件 nonebot-plugin-web-bottle 依赖的插件如下：
>       nonebot_plugin_localstore
>   插件 nonebot_plugin_web_bottle 加载出错：
>       08-07 19:09:01 [SUCCESS] nonebot | NoneBot is initializing...
>       08-07 19:09:01 [INFO] nonebot | Current Env: prod
>       08-07 19:09:01 [ERROR] nonebot | Failed to import "nonebot_plugin_web_bottle"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-web-bottle-nonebot_plugin_web_bottle-test/runner.py", line 16, in <module>
>           plugin = load_plugin("nonebot_plugin_web_bottle")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-web-bottle-nonebot_plugin_web_bottle-test/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-web-bottle-nonebot_plugin_web_bottle-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
>           module = importlib.import_module(self._third_party_plugin_ids[name])
>         File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-web-bottle-nonebot_plugin_web_bottle-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-web-bottle-nonebot_plugin_web_bottle-test/.venv/lib/python3.12/site-packages/nonebot_plugin_web_bottle/__init__.py", line 3, in <module>
>           from nonebot.adapters.onebot.v11 import Message, GroupMessageEvent, Bot, MessageSegment
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 由 [NoneFlow](
![ba0a26283c78584a29c6f16e0d3d7409](https://github.com/user-attachments/assets/59fff5e9-0501-41df-af40-65052c49f5cb)
https://github.com/nonebot/noneflow) 提供支持

**Comment by bingqiu456** [comment]
修改了

**Comment by yanyongyu** [comment]
插件配置项写法不正确，请参考文档 配置 部分，并在元数据内添加。

**Comment by luosheng520qaq** [comment]
> 插件配置项写法不正确，请参考文档 配置 部分，并在元数据内添加。

已修改元数据配置项，优化设置读取

**Comment by luosheng520qaq** [comment]
再次修改，修复类型注解忘了加上去这个问题（）

**Comment by luosheng520qaq** [comment]
再次修改，感谢大佬帮忙QwQ

**Comment by luosheng520qaq** [comment]
缺失依赖已添加

**Comment by luosheng520qaq** [comment]
已发版 最新的0.2.5 可能有延迟？
