### ISSUE TITLE
Plugin: ba-tools

### ISSUE THREAD

**Issue by hanasa2023** [nonebot/nonebot2#2863]
### PyPI 项目名

nonebot-plugin-ba-tools 

### 插件 import 包名

nonebot_plugin_ba_tools

### 标签

[{"label":"蔚蓝档案","color":"#00fcf8"}]

### 插件配置项

_No Response_

**Comment by hanasa2023** [comment]
recheck

**Comment by hanasa2023** [comment]
recheck

**Comment by hanasa2023** [comment]
recheck

**Comment by hanasa2023** [comment]
recheck

**Comment by hanasa2023** [comment]
recheck

**Comment by yanyongyu** [comment]
插件数据请勿存储在插件目录下，请使用 localstore 插件。另外插件依赖里限制了 pydantic 版本，插件内如无要求的话可以放开限制兼容 v1 v2.

**Comment by hanasa2023** [comment]
使用localstore插件管理资源文件，移除pydantic版本限制

**Comment by hanasa2023** [comment]
使用localstore插件管理资源文件，移除pydantic版本限制

**Comment by hanasa2023** [comment]
问个问题，如果插件已发布。那么插件更新后应如何进行加载测试，是商店检测到插件更新后自动测试吗？

**Comment by NCBM** [comment]
是的，商店检测到在 PyPI 发了新版会自动重新测试

**Comment by hanasa2023** [comment]
> 是的，商店检测到在 PyPI 发了新版会自动重新测试

好的，感谢解答

**Comment by yanyongyu** [comment]
你这个pydantic也太草率了一点（，至少加个小于 3.0.0。

**Comment by hanasa2023** [comment]
已修改
