### ISSUE TITLE
Plugin: B站收藏夹监视器

### ISSUE THREAD

**Issue by kawaiior** [nonebot/nonebot2#2868]
### PyPI 项目名

nonebot-plugin-bili-fav-watcher

### 插件 import 包名

nonebot_plugin_bili_fav_watcher

### 标签

[{"label":"bilibili","color":"#ea5252"}]

**Comment by kawaiior** [comment]
recheck

**Comment by kawaiior** [comment]
recheck

**Comment by kawaiior** [comment]
recheck

**Comment by kawaiior** [comment]
recheck

**Comment by yanyongyu** [comment]
插件配置方式不正确，请参考文档 配置 部分，并在插件元数据内添加配置信息。数据文件请勿存储在机器人目录下，请使用 localstore 插件或者提供配置项。

**Comment by kawaiior** [comment]
recheck

**Comment by kawaiior** [comment]
recheck
