### ISSUE TITLE
Plugin: 精华消息管理

### ISSUE THREAD

**Issue by BEISNWKZNAN** [nonebot/nonebot2#2872]
### PyPI 项目名

nonebot-plugin-essence-message

### 插件 import 包名

nonebot_plugin_essence_message

### 标签

[]

**Comment by BEISNWKZNAN** [comment]
已改用 nonebot_plugin_localstore

**Comment by BEISNWKZNAN** [comment]
recheck

**Comment by BEISNWKZNAN** [comment]
recheck

**Comment by BEISNWKZNAN** [comment]
recheck

**Comment by yanyongyu** [comment]
插件依赖里限制了 pydantic 版本，如果无要求请放开限制。另外依赖里还有 requests，不用的请删除。你的 db 操作都使用了同步 io，推荐使用异步操作。

**Comment by BEISNWKZNAN** [comment]
十分感谢您的建议,已修改
