### ISSUE TITLE
Plugin: 聊天截图伪造

### ISSUE THREAD

**Issue by lm175** [nonebot/nonebot2#2876]
### PyPI 项目名

nonebot_plugin_fakepic

### 插件 import 包名

nonebot_plugin_fakepic

### 标签

[{"label":"图片生成","color":"#59c3fb"}]

**Comment by yanyongyu** [comment]
插件配置读取使用了过时的方法，请参考文档使用新版方法并删除 Extra 。插件内使用了CQ码处理消息，这是非常不推荐的，你可以使用 message 直接处理。

**Comment by lm175** [comment]
好的，我改一下
