### ISSUE TITLE
Plugin: pokepoke_miss

### ISSUE THREAD

**Issue by shengwang52005** [nonebot/nonebot2#2878]
### PyPI 项目名

pokepoke-miss

### 插件 import 包名

pokepoke_miss

### 标签

[{"label":"舞萌","color":"#f7fe0e"},{"label":"戳一戳","color":"#e80606"}]

**Comment by shengwang52005** [comment]
有路过的佬能看一下吗，感谢

**Comment by Decrabbityyy** [comment]
> 有路过的佬能看一下吗，感谢

https://nonebot.dev/docs/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE

**Comment by shengwang52005** [comment]
retry

**Comment by shengwang52005** [comment]
retry

**Comment by shengwang52005** [comment]
retry

**Comment by yanyongyu** [comment]
你的事件响应器匹配了所有的notice事件并block，会导致别人无法使用，请通过 rule 来判断或者使用 on_type 来接收指定事件类型并删除block。

**Comment by shengwang52005** [comment]
> 你的事件响应器匹配了所有的notice事件并block，会导致别人无法使用，请通过 rule 来判断或者使用 on_type 来接收指定事件类型并删除block。另外你的插件名称和tag或许可以换下，看上去有点意义不明。

根据建议，[使用了 on_type 来接收指定事件类型并删除block](https://github.com/shengwang52005/pokepoke_miss/compare/0.1.16...main)，移除了wmc标签、
