### ISSUE TITLE
Feature: on_shell_command parser 判断是否解析到"--help"

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#288]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

在使用 on_shell_command 的过程中发现 "help" 参数并不在 "args" 列表中
我希望能判断是否有 "-h / --help"，用来发送插件的帮助信息

**描述你所需要的特性：**

希望能将 "help" (Ture or False) 添加到 "args" 中；
或者别的能判断 "help" 机制

**Comment by Jigsaw111** [comment]
因为 `-h/--help` 参数在 argparse 模块里会调用 help_action，识别到就会自己打印 helpmsg 然后 exit（不会返回args），然而 nb2 的 on_shell_command 里的 ArgumentParser 类重写了一部分方法使得本该 exit 的操作都被忽略了，所以 -h 是会默认忽略的。

一个暂时的解决方法是把在初始化  ArgumentParser 示例时使用参数 add_help=False 把自带的 help 取消掉，然后自己 `add_argument("-h", "--help", action = "store_true")`

**Comment by yanyongyu** [comment]
fixed in https://github.com/nonebot/nonebot2/commit/1f585d8bcb7241d15cd7b0a80a73c976e2196b80

帮助信息将会输出在 `ParserExit.message` ，请注意判断 `ParserExit.status` 是否为 0
