### ISSUE TITLE
Plugin: Minecraft查服

### ISSUE THREAD

**Issue by molanp** [nonebot/nonebot2#2881]
### PyPI 项目名

nonebot-plugin-mccheck

### 插件 import 包名

nonebot_plugin_mccheck

### 标签

[{"label":"Minecraft","color":"#ea5252"},{"label":"i18n","color":"#39c5bb"}]

### 插件配置项

_No Response_

**Comment by molanp** [comment]
add: `nonebot-adapter-onebot`

**Comment by molanp** [comment]
add:`ujson`

**Comment by molanp** [comment]
add:`language.json`

**Comment by molanp** [comment]
1

**Comment by molanp** [comment]
1

**Comment by molanp** [comment]
2

**Comment by molanp** [comment]
3

**Comment by yanyongyu** [comment]
插件的 scoped config 编写有误，如果你用了 scoped config，那你的 prefix 应该换个名字。另外通信那块用了同步 io，会阻塞机器人，请使用异步进行通信。

**Comment by molanp** [comment]
已修改

**Comment by molanp** [comment]
已完成修复工作

**Comment by molanp** [comment]
完成

**Comment by yanyongyu** [comment]
你的通信部分依然是同步 io，对于 dns 解析，请使用 asyncquery 和 asyncresolver。对于 socket 通信，请使用 asyncio

**Comment by molanp** [comment]
> 你的通信部分依然是同步 io，对于 dns 解析，请使用 asyncquery 和 asyncresolver。对于 socket 通信，请使用 asyncio

请检查更改是否符合要求
[https://github.com/molanp/nonebot_plugin_mccheck/commit/25bbebfa5a320027e115727076c21534b2ff6eda](https://github.com/molanp/nonebot_plugin_mccheck/commit/25bbebfa5a320027e115727076c21534b2ff6eda)

**Comment by yanyongyu** [comment]
请删除你多余的一些代码，另外你的 socket 为什么不直接用 asyncio.open_connection 而是用 thread

**Comment by molanp** [comment]
> 请删除你多余的一些代码，另外你的 socket 为什么不直接用 asyncio.open_connection 而是用 thread

[MineStat](https://github.com/FragLand/minestat)是一个第三方库，我只是附加到本地

**Comment by molanp** [comment]
现已移除不必要的代码[molanp/nonebot_plugin_mccheck/commit/b97d3ed0cd891d7a8d5e3ac9c88ea5fad75e52de](https://github.com/molanp/nonebot_plugin_mccheck/commit/b97d3ed0cd891d7a8d5e3ac9c88ea5fad75e52de)

**Comment by molanp** [comment]
字体文件似乎未正确包含，我会在近期进行修复

**Comment by yanyongyu** [comment]
minestat 里大量使用了同步方法，建议还是改写成异步

**Comment by molanp** [comment]
> minestat 里大量使用了同步方法，建议还是改写成异步

很难实现

**Comment by molanp** [comment]
> minestat 里大量使用了同步方法，建议还是改写成异步

此项工作无法完成，已向minestat维护者提出请求

**Comment by molanp** [comment]
已使用其他方法实现异步socket

**Comment by molanp** [comment]
1
