### ISSUE TITLE
Plugin: nonebot-plugin-ehentai-search

### ISSUE THREAD

**Issue by N791** [nonebot/nonebot2#2884]
### PyPI 项目名

nonebot-plugin-ehentai-search

### 插件 import 包名

nonebot_plugin_ehentai_search

### 标签

[{"label":"ehentai","color":"#ffe700"}]

**Comment by N791** [comment]
test

**Comment by N791** [comment]
2

**Comment by yanyongyu** [comment]
怎么close了

**Comment by N791** [comment]
我以为通过测试就可以关掉了

**Comment by KomoriDev** [comment]
noneflow 会自动改插件名的

**Comment by yanyongyu** [comment]
插件里的 log 可以直接使用 nonebot.logger 不需要从 loguru 导入

**Comment by N791** [comment]
> 插件里的 log 可以直接使用 nonebot.logger 不需要从 loguru 导入

好的，已修改
