### ISSUE TITLE
Plugin: dify插件

### ISSUE THREAD

**Issue by gsskk** [nonebot/nonebot2#2888]
### PyPI 项目名

nonebot-plugin-dify

### 插件 import 包名

nonebot_plugin_dify

### 标签

[{"label":"LLM","color":"#ea5252"},{"label":"Dify","color":"#ea5252"}]

### 插件配置项

```dotenv
DIFY_API_BASE=http://127.0.0.1:8080/v1
DIFY_API_KEY=app-1111111111111111
```

**Comment by gsskk** [comment]
v0.1.3

**Comment by yanyongyu** [comment]
插件依赖里缺少 nonebot2 。插件元数据里的 config 填写错误。插件数据请勿存储于插件目录，请参考[文档](https://nonebot.dev/docs/best-practice/data-storing)使用 localstore 插件。

**Comment by gsskk** [comment]
v0.1.4 已修复 https://github.com/gsskk/nonebot-plugin-dify/commit/fd874d0f4b7df5d71dc1918856e105fea2671985
