### ISSUE TITLE
Plugin: mai2_pcount

### ISSUE THREAD

**Issue by shengwang52005** [nonebot/nonebot2#2890]
### PyPI 项目名

mai2_pcount

### 插件 import 包名

mai2_pcount

### 标签

[{"label":"舞萌","color":"#eabf0b"},{"label":"机厅","color":"#a60a25"}]

**Comment by shoucandanghehe** [comment]
https://github.com/shengwang52005/mai2_pcount/blob/38f015d0f997eefbc2db86959c3970bc20ea25d0/mai2_pcount/__main__.py#L10-L15

建议使用 [localstore](https://github.com/nonebot/plugin-localstore) 存储插件数据
[文档](https://nonebot.dev/docs/best-practice/data-storing)

**Comment by shengwang52005** [comment]
> https://github.com/shengwang52005/mai2_pcount/blob/38f015d0f997eefbc2db86959c3970bc20ea25d0/mai2_pcount/__main__.py#L10-L15
> 
> 建议使用 [localstore](https://github.com/nonebot/plugin-localstore) 存储插件数据 [文档](https://nonebot.dev/docs/best-practice/data-storing)

收到，正在修改了

**Comment by shengwang52005** [comment]
> https://github.com/shengwang52005/mai2_pcount/blob/38f015d0f997eefbc2db86959c3970bc20ea25d0/mai2_pcount/__main__.py#L10-L15
> 
> 建议使用 [localstore](https://github.com/nonebot/plugin-localstore) 存储插件数据 [文档](https://nonebot.dev/docs/best-practice/data-storing)

修改好了，根据建议，[使用了localstore来存储数据](https://github.com/shengwang52005/mai2_pcount/compare/0.1.0...0.2.1)

**Comment by he0119** [comment]
请问你依赖里的 pil_utils 为什么要锁死版本号？最新版的没法用吗？

**Comment by shengwang52005** [comment]
> 请问你依赖里的 pil_utils 为什么要锁死版本号？最新版的没法用吗？

感谢提醒，[已修改](https://github.com/shengwang52005/mai2_pcount/compare/0.2.1...0.2.2)

**Comment by yanyongyu** [comment]
你插件里有用到 httpx 和 pil_utils 吗？不用的依赖请删除。

**Comment by shengwang52005** [comment]
> 你插件里有用到 httpx 和 pil_utils 吗？不用的依赖请删除。

感谢提醒

根据建议，[删除了无用依赖项](https://github.com/shengwang52005/mai2_pcount/compare/0.2.2...0.2.3)
