### ISSUE TITLE
Plugin: nonebot_plugin_mute

### ISSUE THREAD

**Issue by shengwang52005** [nonebot/nonebot2#2892]
### PyPI 项目名

nonebot_plugin_mute

### 插件 import 包名

nonebot_plugin_mute

### 标签

[{"label":"禁言","color":"#ff0303"},{"label":"娱乐","color":"#03fff2"}]

### 插件配置项

mute_times=[1,5,10,30,50,520]

**Comment by yanyongyu** [comment]
插件元数据缺少 config 。插件依赖不用的请删除。

**Comment by shengwang52005** [comment]
> 插件元数据缺少 config 。插件依赖不用的请删除。

感谢提醒，已修改，[根据文档重构了config，删除了无用依赖项](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.1.1...0.2.1)

**Comment by yanyongyu** [comment]
config的配置项名称请小写，否则是无效的

**Comment by shengwang52005** [comment]
> config的配置项名称请小写，否则是无效的

[已更改](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.2.1...0.2.2)

**Comment by yanyongyu** [comment]
不是我说的是你的配置项名字 MUTE_TIMES 啊不是config类名。。。

**Comment by shengwang52005** [comment]
> 不是我说的是你的配置项名字 MUTE_TIMES 啊不是config类名。。。

抱歉抱歉，[已经更改了喵](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.2.2...0.2.3)

**Comment by KomoriDev** [comment]
> > 不是我说的是你的配置项名字 MUTE_TIMES 啊不是config类名。。。
> 
> 抱歉抱歉，[已经更改了喵](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.2.2...0.2.3)

```diff
from pydantic import BaseModel, Field

class Config(BaseModel):
-   MUTE_TIMES: list[int] = Field(default=[1, 5, 10, 30])
+   mute_times: list[int] = Field(default=[1, 5, 10, 30])
```

**Comment by shengwang52005** [comment]
> > > 不是我说的是你的配置项名字 MUTE_TIMES 啊不是config类名。。。
> > 
> > 
> > 抱歉抱歉，[已经更改了喵](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.2.2...0.2.3)
> 
> ```diff
> from pydantic import BaseModel, Field
> 
> class Config(BaseModel):
> -   MUTE_TIMES: list[int] = Field(default=[1, 5, 10, 30])
> +   mute_times: list[int] = Field(default=[1, 5, 10, 30])
> ```

[已更改](https://github.com/shengwang52005/nonebot_plugin_mute/compare/0.2.3...0.2.4)，抱歉抱歉（）
