### ISSUE TITLE
Plugin: 你看我像

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#2894]
### PyPI 项目名

nonebot-plugin-looklike

### 插件 import 包名

nonebot_plugin_looklike

### 标签

[]

**Comment by yanyongyu** [comment]
你插件的 tag 没有意义啊，tag 是用来做分类的，插件的描述本来就是会显示在商店的，你可以删除。

**Comment by tkgs0** [comment]
> 你插件的 tag 没有意义啊，tag 是用来做分类的，插件的描述本来就是会显示在商店的，你可以删除。

已删除
