### ISSUE TITLE
Plugin: lagrange

### ISSUE THREAD

**Issue by Lonely-Sails** [nonebot/nonebot2#2897]
### PyPI 项目名

nonebot_plugin_lagrange

### 插件 import 包名

nonebot_plugin_lagrange

### 标签

[{"label":"Lagrange","color":"#ea5252"}]

### 插件配置项

```dotenv
LAGRANGE_PATH='Lagrange'
LAGRANGE_AUTO_START=true
LAGRANGE_AUTO_INSTALL=true
LAGRANGE_MAX_CACHE_LOG=500
```

**Comment by Lonely-Sails** [comment]
已更新

**Comment by shoucandanghehe** [comment]
推荐使用 asyncio.subprocess
而不是 subprocess + threading

**Comment by AzideCupric** [comment]
或许可以试试基于 [nonebot-plugin-gocqhttp](https://github.com/mnixry/nonebot-plugin-gocqhttp) 进行修改

**Comment by Lonely-Sails** [comment]
> 或许可以试试基于 [nonebot-plugin-gocqhttp](https://github.com/mnixry/nonebot-plugin-gocqhttp) 进行修改

我试试看

**Comment by yanyongyu** [comment]
你插件完全不需要用 threading 来写啊，可以全部改成 asyncio。

**Comment by Lonely-Sails** [comment]
已更新

**Comment by Lonely-Sails** [comment]
> 你插件完全不需要用 threading 来写啊，可以全部改成 asyncio。

我想要在启动的时候自动开启，只用asyncio貌似做不到（

**Comment by shoucandanghehe** [comment]
> 我想要在启动的时候自动开启，只用asyncio貌似做不到（

[on_startup](https://nonebot.dev/docs/advanced/runtime-hook#%E5%90%AF%E5%8A%A8%E5%87%86%E5%A4%87)可以直接塞async func啊

**Comment by Lonely-Sails** [comment]
> > 我想要在启动的时候自动开启，只用asyncio貌似做不到（
> 
> [on_startup](https://nonebot.dev/docs/advanced/runtime-hook#%E5%90%AF%E5%8A%A8%E5%87%86%E5%A4%87)可以直接塞async func啊

已修改

**Comment by j1g5awi** [comment]
所以，本插件的[开关]拉格兰功能有何用处？
我的常识告诉我，nonebot 不能在关闭所有拉格兰之后再发一条消息提示「已关闭」，当然也不能在拉格兰没打开的时候接收消息打开拉格兰（

**Comment by Lonely-Sails** [comment]
> 所以，本插件的[开关]拉格兰功能有何用处？ 我的常识告诉我，nonebot 不能在关闭所有拉格兰之后再发一条消息提示「已关闭」，当然也不能在拉格兰没打开的时候接收消息打开拉格兰（

WebUi 还在设计，目前会在启动时自动开启。

**Comment by Lonely-Sails** [comment]
WebUi 基础功能开发完毕

**Comment by Lonely-Sails** [comment]
已更新

**Comment by j1g5awi** [comment]
何不将 webui 文件存在 pypi 包内？

**Comment by Lonely-Sails** [comment]
> 何不将 webui 文件存在 pypi 包内？

已修改

**Comment by Lonely-Sails** [comment]
我已尝试修复（因为无法复现
