### ISSUE TITLE
Plugin: 复读6

### ISSUE THREAD

**Issue by tkgs0** [nonebot/nonebot2#2899]
### PyPI 项目名

nonebot-plugin-repesix

### 插件 import 包名

nonebot_plugin_repesix

### 标签

[]

**Comment by tkgs0** [comment]
r

**Comment by tkgs0** [comment]
rr

**Comment by NCBM** [comment]
建议使用 `on_keyword` 而非 `on_regex`

**Comment by yanyongyu** [comment]
你的第二种匹配确实可以直接用 fullmatch，相对来说更高效一点

**Comment by reine-ishyanami** [comment]
那两个事件处理函数可以删掉一个吧，直接把两个事件匹配贴一个函数上就行

**Comment by tkgs0** [comment]
已改成更高效的on_fullmatch
