### ISSUE TITLE
Plugin: LiteyukiBot(plugin)

### ISSUE THREAD

**Issue by snowykami** [nonebot/nonebot2#2904]
### PyPI 项目名

nonebot-plugin-liteyukibot

### 插件 import 包名

nonebot_plugin_liteyukibot

### 标签

[{"label":"liteyuki","color":"#d0e9ff"},{"label":"轻雪","color":"#a2d8f4"}]

**Comment by snowykami** [comment]
已添加插件元数据`nonebot-plugin-liteyukibot 0.1.1`

**Comment by yanyongyu** [comment]
虽然但是，你的插件依赖nb的驱动器和nb-cli？以及你的 bot 启动要新开 thread？

**Comment by snowykami** [comment]
> 虽然但是，你的插件依赖nb的驱动器和nb-cli？以及你的 bot 启动要新开 thread？

是这样的，因为要创建一个事件循环(不过目前看来应该没啥问题，后续兼容性我会继续测试

**Comment by snowykami** [comment]
已移除NoneBot驱动器依赖

**Comment by snowykami** [comment]
已移除残留的requests，更换为aiohttp
