### ISSUE TITLE
Adapter: OPQBot

### ISSUE THREAD

**Issue by yuban10703** [nonebot/nonebot2#2906]
### 适配器名称

OPQBot

### 适配器描述

OPQBot 适配器

### PyPI 项目名

nonebot-adapter-opqbot

### 适配器 import 包名

nonebot.adapters.opqbot

### 适配器项目仓库/主页链接

https://github.com/opq-osc/nonebot-adapter-opqbot

### 标签

[{"label":"QQNT","color":"#35a7c9"}]

**Comment by yanyongyu** [comment]
adapter 启动时操作请使用 `self.on_ready`，另外你的 bot api 请求没有经过 nb 的 api hook，你可以参考 qq 适配器修改。

**Comment by yanyongyu** [comment]
由于某些原因，决定暂不接受发布该适配器
