### ISSUE TITLE
Feature: 使 websockets 支持 proxy

### ISSUE THREAD

**Issue by shoucandanghehe** [nonebot/nonebot2#2908]
### 希望能解决的问题

目前 `websockets` 官方不支持 `proxy` https://github.com/python-websockets/websockets/issues/364
这导致 `adapter-discord` 在需要 `proxy` 的时候不能正常工作 (还有其他适配器可能需要通过代理连接ws吗？)

### 描述所需要的功能

但是有一些社区实现可以让 `websockets` 支持 `proxy`
比如：[racinette/websockets_proxy](https://github.com/racinette/websockets_proxy)
我们是否可以在 `NoneBot` 内部使用/重新实现 这些补丁让 `websockets` 支持 `proxy`

P.S. 如果认为使用补丁不好的话，是否至少应该抛出警告，告知用户设置了无用的 `proxy`？

**Comment by yanyongyu** [comment]
nb 本来就没有地方设置 proxy 吧

**Comment by shoucandanghehe** [comment]
https://github.com/nonebot/nonebot2/blob/f540245aec3e3ea3d945e2c73ea80dcbafbde7b8/nonebot/drivers/aiohttp.py#L161-L179
https://github.com/nonebot/nonebot2/blob/f540245aec3e3ea3d945e2c73ea80dcbafbde7b8/nonebot/drivers/websockets.py#L69-L78

如果通过nb的Adapter去建立websocket连接的话
在aiohttp的177行，proxy是传递过去可以正常使用的
而websockets里，proxy的设置并不会生效

**Comment by yanyongyu** [comment]
看上去 websockets 短时间内不会支持 proxy，暂时先添加个 warning 提示吧。
