### ISSUE TITLE
Plugin: 阿瓦隆

### ISSUE THREAD

**Issue by SamuNatsu** [nonebot/nonebot2#2914]
### PyPI 项目名

nonebot-plugin-avalon

### 插件 import 包名

nonebot_plugin_avalon

### 标签

[{"label":"game","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
插件依赖里缺少 nonebot2。

**Comment by SamuNatsu** [comment]
v0.2.1

显式添加 `nonebot2` 作为插件依赖
