### ISSUE TITLE
Plugin: nonebot-plugin-lolinfo

### ISSUE THREAD

**Issue by Shadow403** [nonebot/nonebot2#2917]
### PyPI 项目名

nonebot-plugin-lolinfo

### 插件 import 包名

nonebot_plugin_lolinfo

### 标签

[{"label":"LOL","color":"#ea5252"},{"label":"英雄联盟","color":"#00aaff"}]

**Comment by Shadow403** [comment]
update

**Comment by yanyongyu** [comment]
插件测试仍然未通过，请注意补充遗漏的依赖

**Comment by Shadow403** [comment]
update 0.2.0
