### ISSUE TITLE
Plugin: 消音器

### ISSUE THREAD

**Issue by youlanan** [nonebot/nonebot2#2918]
### PyPI 项目名

nonebot-plugin-tea-silencer

### 插件 import 包名

nonebot_plugin_tea_silencer

### 标签

[{"label":"拦截","color":"#fe7931"},{"label":"屏蔽","color":"#31c8fe"}]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
插件使用了 nb 2.2.1+ 的方法，请在依赖中提升版本限制。你插件元数据的 config 看上去写的不对。插件的数据请勿存储在插件目录下，请使用 localstore 插件获取存储路径，或提供配置项。

**Comment by youlanan** [comment]
已修复 QuQ
- [x] 在依赖中提升版本限制
- [x] 修复错误、重复代码
- [x] 默认储存插件数据至your_bot\data\silencer\
- [x] 添加一个配置项，用于指定数据的储存路径

**Comment by yanyongyu** [comment]
你这个数据存储写的还是不对啊。。。你要不还是直接用 localstore 吧，直接能够获取存储目录路径。

**Comment by youlanan** [comment]
- [x] 非常好的 localstore
