### ISSUE TITLE
Plugin: 无情的发图姬

### ISSUE THREAD

**Issue by Funny1Potato** [nonebot/nonebot2#2922]
### PyPI 项目名

nonebot-plugin-sendpic

### 插件 import 包名

nonebot_plugin_sendpic

### 标签

[]

### 插件配置项

_No Response_

**Comment by Funny1Potato** [comment]
已更新

**Comment by Funny1Potato** [comment]
已更新

**Comment by Funny1Potato** [comment]
+1

**Comment by Funny1Potato** [comment]
唐完了

**Comment by shoucandanghehe** [comment]
网络通信请不要使用`requests`会阻塞机器人
请使用`aiohttp`或者`httpx`

**Comment by Funny1Potato** [comment]
收到，已修改

**Comment by shoucandanghehe** [comment]
> 收到，已修改

意思是让你用异步👇 不是换个库用同步（
```python
from httpx import AsyncClient
async with AsyncClient() as session:
    response = await session.get(url)
```

**Comment by Funny1Potato** [comment]
原来如此，受教了

**Comment by shoucandanghehe** [comment]
截至你发的0.0.10版
插件配置还没有声明在Config类里
建议阅读 https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by shoucandanghehe** [comment]
顺便你用require的方法好诡异（
建议阅读 https://nonebot.dev/docs/advanced/requiring#%E6%8F%92%E4%BB%B6%E4%BE%9D%E8%B5%96%E5%A3%B0%E6%98%8E

**Comment by XieXiLin2** [comment]
https://github.com/nonebot/plugin-apscheduler?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

**Comment by Funny1Potato** [comment]
非！常！抱！歉！之前自己用的时候没有考虑那么多，改完发上来之前也没好好检查过，给您添麻烦了

**Comment by yanyongyu** [comment]
你的插件名建议换一个方便理解的。插件配置的读取方式不对，参考文档使用 get_plugin_config 。

**Comment by Funny1Potato** [comment]
好的，已修改

**Comment by yanyongyu** [comment]
让你换插件名是指你插件元数据里的插件名称，不是 pypi 包名。。。pypi 包名搞这么长干啥。。。

**Comment by Funny1Potato** [comment]
原来是这样嘛，不好意思是我理解错误了，已经改回来了

**Comment by yanyongyu** [comment]
如果改了名字记得发版并在这里重新触发测试。
