### ISSUE TITLE
Plugin: 悠悠

### ISSUE THREAD

**Issue by ChenXu233** [nonebot/nonebot2#2927]
### PyPI 项目名

nonebot-plugin-yoyogame

### 插件 import 包名

nonebot_plugin_yoyogame

### 标签

[{"label":"game","color":"#ea5252"},{"label":"多人游戏","color":"#73fe1f"}]

### 插件配置项

_No Response_

**Comment by ChenXu233** [comment]
:ambulance: :rocket:

**Comment by ChenXu233** [comment]
:ambulance: again

**Comment by ChenXu233** [comment]
:rocket: please

**Comment by yanyongyu** [comment]
插件使用了过时的配置读取方式，请更新

**Comment by ChenXu233** [comment]
> 插件使用了过时的配置读取方式，请更新

已更新
