### ISSUE TITLE
Plugin: 【QQ官机】恶魔轮盘

### ISSUE THREAD

**Issue by STESmly** [nonebot/nonebot2#2929]
### PyPI 项目名

【QQ官机】恶魔轮盘

### 插件 import 包名

QQrobot__BuckshotRoulette

### 标签

[{"label":"恶魔轮盘","color":"#ea5252"},{"label":"小白向","color":"#0d8a74"}]

### 插件配置项

```dotenv
需要额外创建的文件夹
# 1：恶魔轮盘/匹配 
# 2：恶魔轮盘/个人信息/基础信息
```

**Comment by shoucandanghehe** [comment]
首先你的插件目录结构不太对 而且似乎没有在`pypi`发布 可以参考这里 https://nonebot.dev/docs/developer/plugin-publishing
然后数据存储请使用`localstore` 可以参考这里 https://nonebot.dev/docs/best-practice/data-storing
清除未使用的导入 比如 `requests`


最后建议将
```python
timing = require("nonebot_plugin_apscheduler").scheduler
```
改为
```python
require("nonebot_plugin_apscheduler")

from nonebot_plugin_apscheduler import scheduler
```
可以参考这里 https://nonebot.dev/docs/advanced/requiring
