### ISSUE TITLE
Plugin: 次元星辰

### ISSUE THREAD

**Issue by zouXH-god** [nonebot/nonebot2#2934]
### PyPI 项目名

nonebot-plugin-ACGalaxy

### 插件 import 包名

nonebot-plugin-ACGalaxy

### 标签

[{"label":"bilibili","color":"#52eaea"},{"label":"漫展","color":"#52ea65"}]

**Comment by zouXH-god** [comment]
1

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器，请继承 alconna 插件

**Comment by zouXH-god** [comment]
已修改，请查阅
