### ISSUE TITLE
Plugin: 二维码生成器

### ISSUE THREAD

**Issue by Funny1Potato** [nonebot/nonebot2#2941]
### PyPI 项目名

nonebot-plugin-QRrender

### 插件 import 包名

nonebot_plugin_QRrender

### 标签

[{"label":"二维码","color":"#ea5252"}]

**Comment by Funny1Potato** [comment]
1

**Comment by Funny1Potato** [comment]
1

**Comment by shoucandanghehe** [comment]
插件数据存储请使用 localstore
参考文档：https://nonebot.dev/docs/next/best-practice/data-storing

**Comment by Funny1Potato** [comment]
已更改为使用localstore存储

**Comment by yanyongyu** [comment]
你的插件依赖使用了 *，请正确限制版本。你的qrcode使用了同一个缓存文件，存在数据竞争问题，请使用随机文件名防止冲突。你的配置项应该采用小写名称。

**Comment by Funny1Potato** [comment]
收到，已修改
