### ISSUE TITLE
Plugin: githubmodels

### ISSUE THREAD

**Issue by lyqgzbl** [nonebot/nonebot2#2944]
### PyPI 项目名

nonebot-plugin-githubmodels

### 插件 import 包名

nonebot_plugin_githubmodels

### 标签

[]

### 插件配置项

```dotenv
GITHUB_TOKEN="hxjxnfkdmzjs"
```

**Comment by yanyongyu** [comment]
你插件依赖里nonebot2多了fastapi extra，请删除。另外你的openai client使用了同步方法，请使用 AsyncOpenAI。你的插件不依赖ob适配器，请删除依赖，更新元数据。

**Comment by lyqgzbl** [comment]
update

**Comment by yanyongyu** [comment]
你插件读取配置项的方法不正确，另外你依赖的nb版本应该是 2.2.1+ 。

**Comment by yanyongyu** [comment]
@lyqgzbl 是否有更新？

**Comment by lyqgzbl** [comment]
已更新

**Comment by yanyongyu** [comment]
你配置读取的方式依然不正确啊，参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)使用 `get_plugin_config`。

**Comment by lyqgzbl** [comment]
更新了

**Comment by yanyongyu** [comment]
插件配置项应该全部小写，另外你依赖了pydantic v2的写法，你可以直接替换成通用的 `Field(gt=0)`

**Comment by lyqgzbl** [comment]
更新了
