### ISSUE TITLE
Plugin: nonebot-plugin-brecreport

### ISSUE THREAD

**Issue by A-nemon-e** [nonebot/nonebot2#2952]
### PyPI 项目名

nonebot-plugin-brecreport

### 插件 import 包名

nonebot_plugin_brecreport

### 标签

[{"label":"bilibili","color":"#f77979"}]

**Comment by A-nemon-e** [comment]
0

**Comment by A-nemon-e** [comment]
1

**Comment by A-nemon-e** [comment]
我去，metadata写错了

**Comment by A-nemon-e** [comment]
现在应该对了

**Comment by A-nemon-e** [comment]
触发

**Comment by A-nemon-e** [comment]
> 我去，metadata写错了

改完又丢 逗号，天天没谁了真是😰

**Comment by yanyongyu** [comment]
插件依赖里限制了 pydantic 版本 v1，请升级你的版本至 v2 或者采用兼容的写法。另外你的挂载路由的方式不正确，建议参考[文档](https://nonebot.dev/docs/advanced/routing)使用nb提供的挂载功能。插件元数据也缺少支持的适配器，并且你使用了 ob11 的 bot 消息发送 api。

**Comment by yanyongyu** [comment]
@A-nemon-e 是否有更新？

**Comment by yanyongyu** [comment]
长时间无响应，如需发布请修改后重新提交插件
