### ISSUE TITLE
Plugin: NailongRemove

### ISSUE THREAD

**Issue by Refound-445** [nonebot/nonebot2#2953]
### PyPI 项目名

nonebot-plugin-nailongremove

### 插件 import 包名

nonebot_plugin_nailongremove

### 标签

[{"label":"图像分类模型","color":"#5269ea"}]

**Comment by shoucandanghehe** [comment]
别开新issue了，直接编辑就行

**Comment by Refound-445** [comment]
1

**Comment by Refound-445** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot-plugin-nailongremove
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出项目 nonebot-plugin-nailongremove 创建失败：
>       Creating virtualenv nonebot-plugin-nailongremove-nonebot-plugin-nailongremove-test in /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
>       Installing /home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nailongremove-nonebot_plugin_nailongremove-test/.venv/lib/python3.12/site-packages/nvidia/__init__.py over existing file
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

1

**Comment by Decrabbityyy** [comment]
需要补充插件元数据
https://nonebot.dev/docs/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE

**Comment by yanyongyu** [comment]
看上去插件的安装有点问题，测试跑不起来

**Comment by yanyongyu** [comment]
你插件依赖里填了tensorflow似乎并未使用

**Comment by Refound-445** [comment]
1

**Comment by Refound-445** [comment]
2

**Comment by Refound-445** [comment]
3

**Comment by Refound-445** [comment]
5

**Comment by Refound-445** [comment]
不容易

**Comment by Decrabbityyy** [comment]
不容易

**Comment by Refound-445** [comment]
6

**Comment by Refound-445** [comment]
嗯

**Comment by yanyongyu** [comment]
插件依赖的 nb2 版本应该是 2.2.0+，pillow、torch 和 torchvision 不应该写死版本，aiohttp 似乎没看到使用。你的模型权重放错了位置吧，应该放在插件目录下。模型推理应该加上 `with torch.inference_mode()`。

**Comment by Refound-445** [comment]
1

**Comment by Refound-445** [comment]
> 插件依赖的 nb2 版本应该是 2.2.0+，pillow、torch 和 torchvision 不应该写死版本，aiohttp 似乎没看到使用。你的模型权重放错了位置吧，应该放在插件目录下。模型推理应该加上 `with torch.inference_mode()`。

1

**Comment by yanyongyu** [comment]
你GitHub仓库里的代码是不是没更新

**Comment by Refound-445** [comment]
> 你GitHub仓库里的代码是不是没更新

已更

**Comment by yanyongyu** [comment]
你的模型权重没有打包到包里？这样用户怎么使用

**Comment by Refound-445** [comment]
> 你的模型权重没有打包到包里？这样用户怎么使用

。

**Comment by yanyongyu** [comment]
你获取模型路径的方式不正确 https://github.com/Refound-445/nonebot-plugin-nailongremove/blob/a945f951f16a7216f60212349477956233d03966/nonebot_plugin_nailongremove/model.py#L49

应该是 `Path(__file__).parent / "xxx.pth"`

**Comment by Refound-445** [comment]
> 你获取模型路径的方式不正确 https://github.com/Refound-445/nonebot-plugin-nailongremove/blob/a945f951f16a7216f60212349477956233d03966/nonebot_plugin_nailongremove/model.py#L49
> 
> 应该是 `Path(__file__).parent / "xxx.pth"`

。

**Comment by yanyongyu** [comment]
你的仓库没有更新

**Comment by Refound-445** [comment]
> 你的仓库没有更新

。

**Comment by yanyongyu** [comment]
https://github.com/Refound-445/nonebot-plugin-nailongremove/blob/e001804c5dae8fd56a2a3912154503e7605fa43b/nonebot_plugin_nailongremove/model.py#L57

你这个路径是干啥用的。。。我给你的路径写法就是替代这个的。是相同的效果。

**Comment by Refound-445** [comment]
> @Refound-445 是否有更新？

已更新
