### ISSUE TITLE
Plugin: SSE日志输出流

### ISSUE THREAD

**Issue by KiKi-XC** [nonebot/nonebot2#2959]
### PyPI 项目名

nonebot-plugin-logstream

### 插件 import 包名

nonebot_plugin_logstream

### 标签

[{"label":"log","color":"#41fae7"},{"label":"SSE","color":"#1eefff"}]

### 插件配置项

```dotenv
DRIVER=~fastapi
```

**Comment by KiKi-XC** [comment]
1

**Comment by yanyongyu** [comment]
插件内请注意检查 asgi app 是否为 fastapi，而不是假定是 fastapi。如果是的情况下才进行加载，不是的情况请给出 warning。元数据缺少支持的适配器。

**Comment by KiKi-XC** [comment]
> 插件内请注意检查 asgi app 是否为 fastapi，而不是假定是 fastapi。如果是的情况下才进行加载，不是的情况请给出 warning。元数据缺少支持的适配器。

插件并没有要求指定的适配器，请问是否可以不填元数据的支持适配器

**Comment by yanyongyu** [comment]
如果支持所有适配器也需要显式填写 none

**Comment by KiKi-XC** [comment]
> 如果支持所有适配器也需要显式填写 none

已添加`supported_adapters='none'`至`__plugin_meta__`,pypi版本1.0.4

**Comment by StarHeartHunt** [comment]
> > 如果支持所有适配器也需要显式填写 none
> 
> 已添加`supported_adapters='none'`至`__plugin_meta__`,pypi版本1.0.4

https://github.com/KiKi-XC/nonebot_plugin_logstream/blob/f68ed3263d2228b100bd846bc9bf7e3f092a6efe/nonebot_plugin_logstream/__init__.py#L19

supported_adapters='none' 不符合 metadata 格式，可参考下面代码

https://github.com/nonebot/nonebot2/blob/c0c8e1aa021a952ce9d9aff3e0ede3889a599fc3/nonebot/plugins/echo.py#L14

**Comment by KiKi-XC** [comment]
> > > 如果支持所有支架也需要显式填写无
> > 
> > 
> > 已添加`supported_adapters='none'`至`__plugin_meta__`pypi版本1.0.4
> 
> https://github.com/KiKi-XC/nonebot_plugin_logstream/blob/f68ed3263d2228b100bd846bc9bf7e3f092a6efe/nonebot_plugin_logstream/__init__.py#L19
> 
> supported_adapters='none' 不符合元数据格式，可参考下面代码
> 
> https://github.com/nonebot/nonebot2/blob/c0c8e1aa021a952ce9d9aff3e0ede3889a599fc3/nonebot/plugins/echo.py#L14

已提交，感谢指正
