### ISSUE TITLE
Bug: Mirai模块处理仅含@Bot的消息时报错

### ISSUE THREAD

**Issue by SinonJZH** [nonebot/nonebot2#296]
**描述问题：**

对于单独的@bot消息处理时报错。

**如何复现？**

使用mirai模块处理消息，当在群聊中单独@机器人（不跟随其他信息）时消息处理报错

**期望的结果**

能够正常处理

**环境信息：**

 - OS: CentOS & Winodws
 - Python Version: 3.9.2
 - Nonebot Version: nonebot cli version 0.4.0

**截图**
![image](https://user-images.githubusercontent.com/44700327/112746873-7a2cbd80-8fe4-11eb-9b6a-46620c3ee67f.png)

**Comment by yanyongyu** [comment]
@mnixry
