### ISSUE TITLE
Plugin: nonebot-plugin-yareminder

### ISSUE THREAD

**Issue by yao-yun** [nonebot/nonebot2#2961]
### PyPI 项目名

nonebot-plugin-yareminder

### 插件 import 包名

nonebot_plugin_yareminder

### 标签

[]

**Comment by yao-yun** [comment]
已添加项目主页链接

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器，请继承你使用的上游插件。

**Comment by yao-yun** [comment]
已更新支持的适配器

**Comment by yanyongyu** [comment]
你应该使用 `inherit_supported_adapters` 继承 alc 和 saa

**Comment by yao-yun** [comment]
已更正

**Comment by yanyongyu** [comment]
你的GitHub仓库并没有更新

**Comment by yao-yun** [comment]
不好意思，请参考 https://github.com/yao-yun/nonebot-plugin-yareminder/tree/v0.1.7，这也是发布到pypi的版本；更改因为某些原因还没同步到 master 分支，我随后检查

**Comment by yao-yun** [comment]
更改已同步至 [master](https://github.com/yao-yun/nonebot-plugin-yareminder/tree/master)
