### ISSUE TITLE
Bot: 树才怪BOT

### ISSUE THREAD

**Issue by Treeeeee1101** [nonebot/nonebot2#2962]
### 机器人名称

树才怪BOT

### 机器人描述

玩宝可梦游戏，qq官方机器人

### 机器人项目仓库/主页链接

https://bot.q.qq.com/s/1z7fay0yn?id=102150514

### 标签

[{"label":"宝可梦","color":"#ea5252"},{"label":"游戏","color":"#5748dd"}]

**Comment by yanyongyu** [comment]
机器人主页请填写你的开源地址。
