### ISSUE TITLE
Plugin: 批量撤回

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#2965]
### PyPI 项目名

nonebot-plugin-batch-withdrawal

### 插件 import 包名

nonebot_plugin_batch_withdrawal

### 标签

[]

**Comment by yanyongyu** [comment]
插件依赖缺少nb2。数据库使用了同步方法，建议更换异步。

**Comment by yanyongyu** [comment]
sqlite3 可以更换为 aiosqlite

**Comment by zhongwen-4** [comment]
> sqlite3 可以更换为 aiosqlite

那个啥, 下次重构一定带上aiosqlite, 现在好像有点不会用()

**Comment by shoucandanghehe** [comment]
~~建议一步到位orm~~

**Comment by yanyongyu** [comment]
用法是基本一致的啊，改成异步的就行

**Comment by zhongwen-4** [comment]
修改sqlite -> aiosqlite

**Comment by zhongwen-4** [comment]
元数据被误删了, 已修复

**Comment by zhongwen-4** [comment]
1
