### ISSUE TITLE
Plugin: Beat Saber查分器

### ISSUE THREAD

**Issue by qwq12738qwq** [nonebot/nonebot2#2973]
### PyPI 项目名

nonebot-plugin-beatsaberscore

### 插件 import 包名

nonebot_plugin_beatsaberscore

### 标签

[{"label":"Beat Saber","color":"#456df1"}]

**Comment by qwq12738qwq** [comment]
已更新

**Comment by yanyongyu** [comment]
你仓库里怎么有两个不同的 `__init__.py` 。插件配置项读取方式不正确，配置项名称应该是小写，同时插件依赖的 nb2 版本应该提升到 2.2.0+。插件数据应该使用 [localstore 插件](https://nonebot.dev/docs/best-practice/data-storing)获取数据文件路径。

**Comment by yanyongyu** [comment]
@qwq12738qwq 是否有更新？

**Comment by qwq12738qwq** [comment]
> @qwq12738qwq 是否有更新？

更新力

**Comment by qwq12738qwq** [comment]
1

**Comment by yanyongyu** [comment]
你的插件配置项读取方式不正确，配置项名称应该是小写，元数据里也缺少配置类。

**Comment by qwq12738qwq** [comment]
4

**Comment by qwq12738qwq** [comment]
忘记上传pypi了....
