### ISSUE TITLE
Plugin: 计算器：游戏

### ISSUE THREAD

**Issue by Yurchiu** [nonebot/nonebot2#2975]
### PyPI 项目名

nonebot-plugin-calc-game

### 插件 import 包名

nonebot_plugin_calc_game

### 标签

[{"label":"game","color":"#ea5252"}]

**Comment by Yurchiu** [comment]
👀

**Comment by Yurchiu** [comment]
👀

**Comment by Yurchiu** [comment]
2

**Comment by Yurchiu** [comment]
3

**Comment by Yurchiu** [comment]
4

**Comment by yanyongyu** [comment]
你插件的正则表达式字符串前面没有加 `r""`。你插件似乎不支持 ob12 适配器吧。插件配置项使用了旧版本的写法，如果不用请删了，元数据内也一并改为 None。

**Comment by Yurchiu** [comment]
第一次写插件，如有不当请多多包涵。谢谢。

**Comment by Yurchiu** [comment]
done
