### ISSUE TITLE
Plugin: pjsk-helper

### ISSUE THREAD

**Issue by Atr1ck** [nonebot/nonebot2#2979]
### PyPI 项目名

nonebot-plugin-pjsk-helper

### 插件 import 包名

nonebot_plugin_pjsk_helper

### 标签

[]

**Comment by Atr1ck** [comment]
update

**Comment by Atr1ck** [comment]
update

**Comment by Atr1ck** [comment]
update

**Comment by zhongwen-4** [comment]
请添加元数据和依赖，元数据参考https://nonebot.dev/docs/developer/plugin-publishing#%E5%A1%AB%E5%86%99%E6%8F%92%E4%BB%B6%E5%85%83%E6%95%B0%E6%8D%AE

**Comment by Atr1ck** [comment]
update

**Comment by Atr1ck** [comment]
update

**Comment by zhongwen-4** [comment]
少依赖了，加一下
nonebot_adapter_onebot
nonebot2

**Comment by Atr1ck** [comment]
更新，刚才似乎没检查)

**Comment by zhongwen-4** [comment]
![image](https://github.com/user-attachments/assets/4c48c036-2d41-452e-b70c-51da9b1b814e)

**Comment by zhongwen-4** [comment]
![image](https://github.com/user-attachments/assets/fbd6b21c-b0eb-4340-a693-36a687d7e277)

**Comment by Atr1ck** [comment]
readme内容仍未编写，功能仍待完善和优化，我会尽快编写

**Comment by Atr1ck** [comment]
非常抱歉未仔细阅读文档，感谢帮助

**Comment by zhongwen-4** [comment]
你怎么关了, 检查通过了放那就行了

**Comment by Decrabbityyy** [comment]
可以先上架再慢慢改（

**Comment by zhongwen-4** [comment]
你的github似乎没更新 ()

**Comment by Atr1ck** [comment]
啊抱歉，最后一版忘记push了))

**Comment by Atr1ck** [comment]
程序有问题，暂时关闭

**Comment by Atr1ck** [comment]
已修复

**Comment by yanyongyu** [comment]
插件内存在读取项目路径数据 https://github.com/Atr1ck/nonebot-plugin-pjsk-helper/blob/7d9a6838a5e3f9ef4dabdad8e093f303437c5948/nonebot_plugin_pjsk_helper/__main__.py#L86，请使用 [localstore 插件](https://nonebot.dev/docs/best-practice/data-storing)。插件使用了同步浏览器自动化，会导致机器人阻塞，建议更换 playwright。
