### ISSUE TITLE
docker 部署报错 ModuleNotFoundError: No module named 'bot'

### ISSUE THREAD

**Issue by fake2ky** [nonebot/nonebot2#298]
**问题描述**
docker 部署报错,  ModuleNotFoundError: No module named 'bot'
使用nb-cli生成的项目, 尝试过换python版本还是没办法解决,  这是哪里有问题吗

**复现方法**
docker-compose up

**期望的行为**

**日志信息**
![bug](http://111.231.168.154:9000/tea/20210329140257.png)

**相关代码**
```python
# 请在这里贴上你认为相关的代码
```

**运行环境**
 - 操作系统：
 - OneBot（CQHTTP）实现及版本：cqhttp
 - NoneBot 版本：nonebot2
 - aiocqhttp 版本：
 - Python 版本：3.7, 3.8

**Comment by yanyongyu** [comment]
你的bot启动文件名字是`bot.py`吗

**Comment by fake2ky** [comment]
> 你的bot启动文件名字是`bot.py`吗

是的,  我发现是windows环境问题 ,去掉这些代码就正常了
`   volumes: `
`- "/etc/localtime:/etc/localtime"- "./:/app/"`
