### ISSUE TITLE
Plugin: osu! Match Monitor

### ISSUE THREAD

**Issue by Sevenyine** [nonebot/nonebot2#2982]
### PyPI 项目名

nonebot-plugin-osu-match-monitor

### 插件 import 包名

nonebot_plugin_osu_match_monitor

### 标签

[{"label":"OSU","color":"#da6699"}]

### 插件配置项

_No Response_

**Comment by Sevenyine** [comment]
已更新

**Comment by Sevenyine** [comment]
已更新

**Comment by yanyongyu** [comment]
插件元数据缺少配置项和支持的适配器。插件读取配置项的方法不正确，请使用新版本方法。

**Comment by Sevenyine** [comment]
已修改(=´∀｀)人(´∀｀=)

**Comment by yanyongyu** [comment]
你配置类可以删掉extra了，没必要写这个，这种写法是pyd v1的写法。

**Comment by Sevenyine** [comment]
改好了 ！（）
