### ISSUE TITLE
Plugin: 给我点颜色瞧瞧

### ISSUE THREAD

**Issue by FrostN0v0** [nonebot/nonebot2#2983]
### PyPI 项目名

nonebot-plugin-color-see-see

### 插件 import 包名

nonebot_plugin_color_see_see

### 标签

[{"label":"game","color":"#97e7e1"}]

**Comment by yanyongyu** [comment]
插件不应该依赖 nb2 的驱动器，请删除fastapi extra。

**Comment by FrostN0v0** [comment]
已删除
