### ISSUE TITLE
Plugin: nonechat

### ISSUE THREAD

**Issue by hanasa2023** [nonebot/nonebot2#2989]
### PyPI 项目名

nonebot-plugin-nonechat

### 插件 import 包名

nonebot_plugin_nonechat

### 标签

[{"label":"LLM","color":"#52eacf"}]

**Comment by yanyongyu** [comment]
插件依赖里不应该有 nb2 extra 的驱动器。你的 proxy 也不应该写入到 environ 里吧，会影响其他插件。另外，localstore 请使用新版本方法。

**Comment by hanasa2023** [comment]
> 插件依赖里不应该有 nb2 extra 的驱动器。你的 proxy 也不应该写入到 environ 里吧，会影响其他插件。另外，localstore 请使用新版本方法。

确实在设计上有许多问题，现已修改
