### ISSUE TITLE
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'

### ISSUE THREAD

**Issue by CodeZWT** [nonebot/nonebot2#299]
**描述问题：**

ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'

在nonebot\plugins\echo.py"下第六行
from nonebot.adapters.cqhttp import Bot, unescape, MessageEvent, Message, MessageSegment
仍然引用了已不存在的文件
以及文档中 开始——开始使用——最小实例 中的 bot.py 模板需要修改

**Comment by yanyongyu** [comment]
文档是以gocq为例默认已装cqhttp

**Comment by CodeZWT** [comment]
from nonebot.adapters.cqhttp 导入这个包
在最新的nonebot2中，adapters文件夹下没有 cqhttp文件夹，所以导入不成功，目前该文件夹下只有一个_base.py文件
所以在bot.py的模板中是否存在误导
且在自带插件echo.py中同样引用了，且unescape 在_base中已经迁移或移除，MessageEvent应该是已经修改Event类？

**Comment by yanyongyu** [comment]
> from nonebot.adapters.cqhttp 导入这个包
> 在最新的nonebot2中，adapters文件夹下没有 cqhttp文件夹，所以导入不成功，目前该文件夹下只有一个_base.py文件
> 所以在bot.py的模板中是否存在误导
> 且在自带插件echo.py中同样引用了，且unescape 在_base中已经迁移或移除，MessageEvent应该是已经修改Event类？

![image](https://user-images.githubusercontent.com/42488585/112852571-a462a600-90de-11eb-9e17-f1adac065589.png)

解读部分已说明配置CQHTTP协议端

**Comment by CodeZWT** [comment]
谢谢，我配置协议端试试看

**Comment by yanyongyu** [comment]
![image](https://user-images.githubusercontent.com/42488585/112853453-729e0f00-90df-11eb-9305-14429aeaae65.png)
在 master 文档里有安装提示

**Comment by CodeZWT** [comment]
非常感谢大佬解答，正是缺少了这步导致的

**Comment by doraemon-hub-art** [comment]
感谢老哥解答
