### ISSUE TITLE
Plugin: nonebot-weather

### ISSUE THREAD

**Issue by hriyel** [nonebot/nonebot2#2991]
### PyPI 项目名

nonebot-weather

### 插件 import 包名

nonebot_weather

### 标签

[{"label":"weather","color":"#34aad4"},{"label":"server","color":"#0e799e"}]

**Comment by hriyel** [comment]
更新数据

**Comment by hriyel** [comment]
updata

**Comment by hriyel** [comment]
updata

**Comment by hanasa2023** [comment]
打包时未包含所需插件所需依赖，建议通过poetry、pdm、uv等包管理器对依赖及项目配置进行管理。另外，请参考nonebot文档中的[插件命名规范](https://nonebot.dev/docs/developer/plugin-publishing)，规范化插件名称。

**Comment by hriyel** [comment]
updata

**Comment by hriyel** [comment]
1

**Comment by XTxiaoting14332** [comment]
是update不是updata(

**Comment by yanyongyu** [comment]
插件测试未通过，请注意添加插件依赖。看上去你的插件并未使用到适配器特殊功能，可以删除 ob11 依赖，使用基类，另外元数据内支持的适配器也对应修改。

**Comment by yanyongyu** [comment]
@hriyel 是否有更新？
