### ISSUE TITLE
Plugin: Marsho AI插件

### ISSUE THREAD

**Issue by Asankilp** [nonebot/nonebot2#2992]
### PyPI 项目名

nonebot-plugin-marshoai

### 插件 import 包名

nonebot_plugin_marshoai

### 标签

[{"label":"猫娘","color":"#e6a432"},{"label":"AI","color":"#32c3e6"}]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
插件依赖里不应该存在 nb2 extra 的驱动器。插件元数据缺少配置项。

**Comment by Asankilp** [comment]
update

**Comment by Asankilp** [comment]
update

**Comment by Asankilp** [comment]
updata!!!!!!!!!
