### ISSUE TITLE
Plugin: nonebot_plugin_SimpleToWrite

### ISSUE THREAD

**Issue by STESmly** [nonebot/nonebot2#2994]
### PyPI 项目名

nonebot-plugin-SimpleToWrite

### 插件 import 包名

nonebot_plugin_SimpleToWrite

### 标签

[{"label":"编写简化","color":"#104772"},{"label":"小白向推荐","color":"#149581"}]

**Comment by STESmly** [comment]
更新

**Comment by STESmly** [comment]
> # 📃 商店发布检查结果
> > Plugin: nonebot_plugin_SimpleToWrite
> 
> **✅ 所有测试通过，一切准备就绪！**
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

更新

**Comment by KomoriDev** [comment]
已发布的插件不需要回复

**Comment by STESmly** [comment]
> 已发布的插件不需要回复

但是我想改一下在插件商店里面的名字

**Comment by KomoriDev** [comment]
> > 已发布的插件不需要回复
> 
> 但是我想改一下在插件商店里面的名字

改 `PluginMetaData` 的 `name` 参数即可，nonebot 商店每隔 4 小时测试一次。如果测试通过就会应用更改
