### ISSUE TITLE
Plugin: lolinfo

### ISSUE THREAD

**Issue by Shadow403** [nonebot/nonebot2#2996]
### PyPI 项目名

nonebot-plugin-lolinfo

### 插件 import 包名

nonebot_plugin_lolinfo

### 标签

[{"label":"LOL","color":"#02ceff"},{"label":"英雄联盟","color":"#ff02fb"}]

**Comment by Shadow403** [comment]
update

**Comment by Shadow403** [comment]
update

**Comment by Shadow403** [comment]
UPDATE

**Comment by yanyongyu** [comment]
插件元数据缺少配置类。httpx应该使用 async client，否则会阻塞机器人。

**Comment by Shadow403** [comment]
> 插件元数据缺少配置类。httpx应该使用 async client，否则会阻塞机器人。

UpDaTe
