### ISSUE TITLE
Plugin: BiliRequestAll

### ISSUE THREAD

**Issue by Shadow403** [nonebot/nonebot2#2998]
### PyPI 项目名

nonebot-plugin-bilirequestall

### 插件 import 包名

nonebot_plugin_bilirequestall

### 标签

[{"label":"BiliBili","color":"#ec06e7"},{"label":"审批","color":"#ff6c00"}]

**Comment by Shadow403** [comment]
于此插件相同 重写了https://github.com/nonebot/nonebot2/issues/1238

**Comment by yanyongyu** [comment]
你的插件已经发布过了，不需要重复提交，如需修改请提交pr。另外你的插件读取配置项使用了 nb 2.2.0+ 的方法，需要将依赖版本提升。另外，你的依赖里限制了pydantic的版本号，看你的代码似乎并没有需要pyd v2的地方，请放宽限制或删除。
