### ISSUE TITLE
Plugin: ZXPM插件管理

### ISSUE THREAD

**Issue by HibiKier** [nonebot/nonebot2#3002]
### PyPI 项目名

nonebot-plugin-zxpm

### 插件 import 包名

nonebot_plugin_zxpm

### 标签

[{"label":"小真寻","color":"#fbe4e4"},{"label":"多平台适配","color":"#ea5252"},{"label":"插件管理","color":"#456df1"}]

### 插件配置项

```dotenv
zxpm_db_url="sqlite:data/zxpm/db/zxpm.db"
zxpm_notice_info_cd=300
zxpm_ban_reply="才不会给你发消息."
zxpm_ban_level=5
zxpm_switch_level=1
zxpm_admin_default_auth=5
zxpm_font="msyh.ttc"
```

**Comment by yanyongyu** [comment]
你的插件怎么写死了pydantic版本。。。依赖的nb2不应该包含驱动器。数据目录请使用localstore或者提供配置项。

**Comment by HibiKier** [comment]
已移除驱动器，pydantic依赖，并添加数据路径配置

**Comment by HibiKier** [comment]
修改ob11限制插件

**Comment by HibiKier** [comment]
添加pil依赖
