### ISSUE TITLE
Plugin: lingyi_chat

### ISSUE THREAD

**Issue by yeying-xingchen** [nonebot/nonebot2#3005]
### PyPI 项目名

nonebot-plugin-lingyi-chat

### 插件 import 包名

nonebot_plugin_lingyi_chat

### 标签

[{"label":"ChatGPT","color":"#ea5252"},{"label":"AI","color":"#ea5252"}]

### 插件配置项

```dotenv
API_URL=你的API地址
```

**Comment by yeying-xingchen** [comment]
Update-修复依赖缺失。

**Comment by yeying-xingchen** [comment]
Update-修复BUG

**Comment by yeying-xingchen** [comment]
Update-修复 返回内容不正确。

**Comment by yanyongyu** [comment]
插件依赖的nb版本应该是 2.2.0+。插件支持的适配器应该是全平台吧，请在元数据内修改为 `None`。

**Comment by yeying-xingchen** [comment]
> 插件依赖的nb版本应该是 2.2.0+。插件支持的适配器应该是全平台吧，请在元数据内修改为 `None`。

已经修改完成
