### ISSUE TITLE
Plugin: nonebot_plugin_BFVsearch

### ISSUE THREAD

**Issue by swallow513** [nonebot/nonebot2#3007]
### PyPI 项目名

nonebot_plugin_bfvsearch

### 插件 import 包名

nonebot_plugin_bfvsearch

### 标签

[{"label":"战地五","color":"#529aea"}]

**Comment by yanyongyu** [comment]
插件依赖版本没有填写限制，并且缺少ob11适配器的依赖。

**Comment by swallow513** [comment]
已添加

**Comment by swallow513** [comment]
1

**Comment by swallow513** [comment]
1

**Comment by yanyongyu** [comment]
你仓库的代码没有更新

**Comment by swallow513** [comment]
抱歉，现在更新了
