### ISSUE TITLE
Plugin: MinecraftWatcher

### ISSUE THREAD

**Issue by Lonely-Sails** [nonebot/nonebot2#3009]
### PyPI 项目名

nonebot_plugin_mc_watcher

### 插件 import 包名

nonebot_plugin_mc_watcher

### 标签

[{"label":"Minecraft","color":"#d79f10"}]

### 插件配置项

```dotenv
MINECRAFT_SERVERS={"测试": "lemonfate.cn"}
```

**Comment by Lonely-Sails** [comment]
upgrade

**Comment by Lonely-Sails** [comment]
qwq

**Comment by Lonely-Sails** [comment]
awa

**Comment by yanyongyu** [comment]
插件使用了pydantic v2版本的方法，请在依赖内添加pydantic并限制版本。定时任务建议使用 [apscheduler 插件](https://nonebot.dev/docs/best-practice/scheduler)。

**Comment by Lonely-Sails** [comment]
已限制 pedantic 版本。一般情况下间隔的时间不会很长，感觉好像用不到 APScheduler（
