### ISSUE TITLE
Plugin: 西工大翱翔门户成绩监控

### ISSUE THREAD

**Issue by qllokirin** [nonebot/nonebot2#3011]
### PyPI 项目名

nonebot-plugin-npu

### 插件 import 包名

nonebot_plugin_npu

### 标签

[{"label":"西工大","color":"#66ccff"}]

**Comment by qllokirin** [comment]
添加依赖nonebot-adapter-onebot

**Comment by yanyongyu** [comment]
插件依赖了bs4，应该使用全名。imgkit、paho-mqtt写死了版本，请修改。

**Comment by qllokirin** [comment]
> 插件依赖了bs4，应该使用全名。imgkit、paho-mqtt写死了版本，请修改。

感谢ddl，看了几遍文档但提交的时候还是忘了😭，已修正
