### ISSUE TITLE
Plugin: nb插件更新器

### ISSUE THREAD

**Issue by hanasa2023** [nonebot/nonebot2#3014]
### PyPI 项目名

nonebot-plugin-updater

### 插件 import 包名

nonebot_plugin_updater

### 标签

[{"label":"插件更新","color":"#dd2200"}]

**Comment by yanyongyu** [comment]
元数据缺少支持的适配器。你的config为啥要get两遍。。。

**Comment by hanasa2023** [comment]
> 元数据缺少支持的适配器。你的config为啥要get两遍。。。

还真是😢
