### ISSUE TITLE
Plugin: boom

### ISSUE THREAD

**Issue by yeying-xingchen** [nonebot/nonebot2#3016]
### PyPI 项目名

nonebot-plugin-boom

### 插件 import 包名

nonebot_plugin_boom

### 标签

[{"label":"unsafe","color":"#ea5252"}]

**Comment by yeying-xingchen** [comment]
修复 依赖缺失。

**Comment by yanyongyu** [comment]
你的插件为什么限制python版本这么高

**Comment by yeying-xingchen** [comment]
还没合并草
