### ISSUE TITLE
docker部署 TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by fake2ky** [nonebot/nonebot2#302]
**描述问题：**

在腾讯云上执行docker-compose出现TypeError: 'NoneType' object is not callable

**如何复现？**

nb-cli创建的项目, 执行docker-compose

**期望的结果**

能够正常部署

**环境信息：**

 - OS: linux centos7
 - Python Version: 3.8
 - Nonebot Version: 2.0.0

**截图**
![20210330132501](https://user-images.githubusercontent.com/31437813/112938125-969f3600-915b-11eb-9abe-c45a6be698c6.png)

**Comment by yanyongyu** [comment]
降级pydantic到1.7.3或者使用最新版nonebot2
