### ISSUE TITLE
Plugin: 真寻日报

### ISSUE THREAD

**Issue by HibiKier** [nonebot/nonebot2#3020]
### PyPI 项目名

nonebot-plugin-zxreport

### 插件 import 包名

nonebot_plugin_zxreport

### 标签

[{"label":"小真寻","color":"#fbe4e4"},{"label":"多平台适配","color":"#ea5252"},{"label":"日报","color":"#dd628b"}]

**Comment by HibiKier** [comment]
1

**Comment by HibiKier** [comment]
1

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器和配置项。localstore 插件使用前没有require。

**Comment by HibiKier** [comment]
已修改
