### ISSUE TITLE
Plugin: 团购

### ISSUE THREAD

**Issue by Onimaimai** [nonebot/nonebot2#3025]
### PyPI 项目名

nonebot-plugin-buy

### 插件 import 包名

nonebot_plugin_buy

### 标签

[]

**Comment by zhongwen-4** [comment]
![Screenshot_2024-10-17-00-52-10-782_mark via](https://github.com/user-attachments/assets/cea9c7c4-ad16-414a-b202-2754bb94697d)

**Comment by Onimaimai** [comment]
啊好的好的

**Comment by afterow** [comment]
大哥你干嘛

**Comment by zhongwen-4** [comment]
审核通过了不用关的

**Comment by yanyongyu** [comment]
插件依赖请限制版本，pydantic没有用到就不用写。插件元数据缺少支持的适配器。插件数据请使用 localstore 插件存储。

**Comment by Onimaimai** [comment]
已完善
