### ISSUE TITLE
Plugin: DDNet 成绩查询

### ISSUE THREAD

**Issue by gongfuture** [nonebot/nonebot2#3030]
### PyPI 项目名

nonebot-plugin-ddrace

### 插件 import 包名

nonebot_plugin_ddrace

### 标签

[{"label":"game","color":"#ea5252"},{"label":"DDNet","color":"#f39c12"}]

### 插件配置项

_No Response_

**Comment by gongfuture** [comment]
已更新

**Comment by gongfuture** [comment]
已更新 0.0.2

**Comment by yanyongyu** [comment]
插件使用了旧版本的插件读取方式 https://github.com/gongfuture/nonebot-plugin-ddrace/blob/60901816dbc1fe33ef3e7c2f195377f5c81a81ba/nonebot_plugin_ddrace/config.py#L25 ，请使用新版本方法。插件配置项请删除Extra，依赖内删除 pydantic 版本限制。配置项那的数据存储目录请使用 localstore 插件。

**Comment by gongfuture** [comment]
已更新 0.0.3

**Comment by yanyongyu** [comment]
你的priority可以使用 `Field(ge=1)` 来做限制，不用使用 validator

**Comment by gongfuture** [comment]
> 你的priority可以使用 `Field(ge=1)` 来做限制，不用使用 validator

好的，我明天改一下

**Comment by gongfuture** [comment]
已更新 0.0.4

**Comment by gongfuture** [comment]
已更新 0.0.5

**Comment by gongfuture** [comment]
已更新 0.0.6

**Comment by gongfuture** [comment]
已更新 0.0.6

**Comment by yanyongyu** [comment]
> @yanyongyu  请问后续的插件更新，是直接更新这个issue吗？还是需要新开issue？

后续更新插件发布新版本即可，如需更新tag请pr更新
