### ISSUE TITLE
Plugin: 恶魔轮盘赌

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/nonebot2#3032]
### PyPI 项目名

nonebot_plugin_BR

### 插件 import 包名

nonebot_plugin_BR

### 标签

[{"label":"游戏","color":"#fa0404"}]

**Comment by yanyongyu** [comment]
插件依赖 nb2 2.2.0+ 。插件支持的适配器没有继承 uninfo session。

**Comment by Agnes4m** [comment]
已更新适配器和依赖
