### ISSUE TITLE
Plugin: nonebot-plugin-picksong

### ISSUE THREAD

**Issue by Onimaimai** [nonebot/nonebot2#3034]
### PyPI 项目名

nonebot-plugin-picksong

### 插件 import 包名

nonebot_plugin_picksong

### 标签

[]

### 插件配置项

```dotenv
UIN = 000
SKEY = 000
```

**Comment by Onimaimai** [comment]
修正依赖项

**Comment by Onimaimai** [comment]
修复语法

**Comment by Onimaimai** [comment]
补充依赖项

**Comment by Onimaimai** [comment]
1

**Comment by Onimaimai** [comment]
1

**Comment by Onimaimai** [comment]
1

**Comment by Onimaimai** [comment]
2

**Comment by kanbereina** [comment]
①请确保你的插件依赖性是可被正常安装，并且插件正常加载，而不是一遍又一遍地修改你的`pyproject.toml`的`version`版本，这并没有任何意义。

②在你的插件中，同时使用了`httpx`库和`requests`库，但是你使用的`requests.get`方法是同步的，会导致阻塞`eventloop`，这会导致下载音频时机器人无法处理其他事件，建议只使用`httpx`库中的异步方法进行网络请求。

**Comment by zhongwen-4** [comment]
还有你的项目主页尚未填写

**Comment by Onimaimai** [comment]
移除requests库，补填项目主页

**Comment by Onimaimai** [comment]
1

**Comment by Onimaimai** [comment]
移除重复导入

**Comment by Onimaimai** [comment]
增加 imageio-ffmpeg 依赖

**Comment by Onimaimai** [comment]
好像 pyproject 缩进有误

**Comment by zhongwen-4** [comment]
graiax似乎没用到？可以删了

**Comment by zhongwen-4** [comment]
请把**logging**换成**logger**

**Comment by shoucandanghehe** [comment]
```python
from nonebot.log import logger
```
然后直接用就行了，不用自己设置

**Comment by Onimaimai** [comment]
ok
