### ISSUE TITLE
Plugin: 省流

### ISSUE THREAD

**Issue by ChenXu233** [nonebot/nonebot2#3041]
### PyPI 项目名

nonebot-plugin-summary

### 插件 import 包名

nonebot_plugin_summary

### 标签

[{"label":"省流","color":"#57f99a"},{"label":"AI","color":"#c0d048"}]

### 插件配置项

```dotenv
SUMMARY__TOKEN = TOKEN
```

**Comment by ChenXu233** [comment]
:rocket: update

**Comment by zhongwen-4** [comment]
你的utils.py中尚未导入nonebot_plugin_userinfo和nonebot_plugin_orm，请在(这里)[https://github.com/ChenXu233/nonebot-plugin-summary/blob/main/nonebot_plugin_summary/utils.py]添加以下内容
```Python
from nonebot import require
require("nonebot_plugin_userinfo")
require("nonebot_plugin_userinfo")
```

**Comment by ChenXu233** [comment]
> 你的utils.py中尚未导入nonebot_plugin_userinfo和nonebot_plugin_orm，请在[这里](https://github.com/ChenXu233/nonebot-plugin-summary/blob/main/nonebot_plugin_summary/utils.py)添加以下内容
> 
> ```python
> from nonebot import require
> require("nonebot_plugin_userinfo")
> require("nonebot_plugin_orm")
> ```

直接在生产环境写了，没注意到这个问题，抱歉。
不过似乎nonebot_plugin_orm已经被依赖链的nonebot_plugin_chatrecorder reqiure过了，似乎加不加都无所谓？

:rocket: update again

**Comment by ChenXu233** [comment]
:rocket: update again

I'm a cat girl, so I always make mistakes meow. Please forgive me.....

**Comment by ChenXu233** [comment]
:rocket: update again and again

I'm a cat girl, so I always make mistakes meow. Please forgive me again.....

**Comment by yanyongyu** [comment]
你的插件内使用了session插件但是你的插件依赖内并未添加和require

**Comment by ChenXu233** [comment]
> 你的插件内使用了session插件但是你的插件依赖内并未添加和require

我reqiure过nonebot_plugin_chatrecorder，而nonebot_plugin_chatrecorder又require了orm，session_orm, session,应该不会有问题吧？
或者说规范化的话其实我应该把这几个全部都reqiure一遍喵？

**Comment by shoucandanghehe** [comment]
个人认为只要你插件直接依赖了都要声明一下

**Comment by ChenXu233** [comment]
:rocket: 已声明

**Comment by yanyongyu** [comment]
你的插件依赖内没有添加

**Comment by ChenXu233** [comment]
:rocket: 已声明
