### ISSUE TITLE
Plugin: BiliMusic Downloader

### ISSUE THREAD

**Issue by Lonely-Sails** [nonebot/nonebot2#3045]
### PyPI 项目名

nonebot_plugin_bilimusic

### 插件 import 包名

nonebot_plugin_bilimusic

### 标签

[{"label":"bilibili","color":"#52d5ea"},{"label":"music","color":"#ea52ca"}]

**Comment by yanyongyu** [comment]
插件测试出错了，请修正插件

**Comment by Lonely-Sails** [comment]
update
