### ISSUE TITLE
Plugin: nonebot_plugin_partner_join

### ISSUE THREAD

**Issue by YuuzukiRin** [nonebot/nonebot2#3048]
### PyPI 项目名

nonebot-plugin-partner-join

### 插件 import 包名

nonebot_plugin_partner_join

### 标签

[{"label":"maimai","color":"#a1b5e8"},{"label":"picture","color":"#a1b5e8"}]

### 插件配置项

_No Response_

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by YuuzukiRin** [comment]
已更新

**Comment by yanyongyu** [comment]
插件依赖请限制版本，imageio似乎没有使用到可以删除，dotenv也应该删除。你插件的init文件名写错了，少了两下划线。。。插件读取配置项的方式错误，请参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)编写，同时请勿修改全局配置或者使用eval。另外请勿自行使用dotenv加载配置，这会影响nb运行。插件数据请使用 [localstore 插件](https://nonebot.dev/docs/best-practice/data-storing)。

**Comment by yanyongyu** [comment]
你`__init__.py`文件名到现在都没改。。。插件元数据还是缺少配置项。配置部分 https://github.com/YuuzukiRin/nonebot_plugin_partner_join/blob/44ebfc4ab4497d81406d8ace44d3114ce8097af3/nonebot_plugin_partner_join/_init_.py#L105-L115 不需要，直接从插件配置读取即可。

请使用 Message 而不是用cq码！！！https://github.com/YuuzukiRin/nonebot_plugin_partner_join/blob/44ebfc4ab4497d81406d8ace44d3114ce8097af3/nonebot_plugin_partner_join/_init_.py#L157-L164

**Comment by yanyongyu** [comment]
插件发送本地文件请使用 `pathlib.Path` https://github.com/YuuzukiRin/nonebot_plugin_partner_join/blob/351b00e339876ceaa013f5ab3451a5b12b14d372/nonebot_plugin_partner_join/__init__.py#L207

配置读取方式依然不正确，请参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)正确读取插件配置，并在插件元数据中添加配置类。https://github.com/YuuzukiRin/nonebot_plugin_partner_join/blob/351b00e339876ceaa013f5ab3451a5b12b14d372/nonebot_plugin_partner_join/__init__.py#L75-L85

**Comment by yanyongyu** [comment]
插件配置项默认值填写不正确，请直接填写数值，不需要从全局获取。插件发送本地文件路径依然不正确，请使用 pathlib

**Comment by yanyongyu** [comment]
插件元数据里缺少配置项。pathlib使用方式不正确，你可以直接传path不要自己format file uri。https://github.com/YuuzukiRin/nonebot_plugin_partner_join/blob/0c61f1aeb8e47a2a6e4dc32554713fdaa3b4902c/nonebot_plugin_partner_join/__init__.py#L206
