### ISSUE TITLE
Plugin: FishSpeechTTS

### ISSUE THREAD

**Issue by Cvandia** [nonebot/nonebot2#3049]
### PyPI 项目名

nonebot-plugin-fishspeech-tts

### 插件 import 包名

nonebot_plugin_fishspeech_tts

### 标签

[{"label":"TTS","color":"#23e907"},{"label":"语音合成","color":"#e9297f"}]

**Comment by yanyongyu** [comment]
你的插件主页是不是写错了。。。

**Comment by Cvandia** [comment]
fix
