### ISSUE TITLE
Bug: nonebot.adapters.cqhttp.exception.ActionFailed:消息不存在

### ISSUE THREAD

**Issue by retroxz** [nonebot/nonebot2#305]
**描述问题：**

使用go-cqhttp反向ws和nonebot的CQ协议连接时, 群聊的回复类消息100%会报异常
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=MSG_NOT_FOUND, retcode=100, status=failed, wording=消息不存在>
go-cqhttp中日志正常
**如何复现？**

1. go-cqhttp使用反向ws和nonebot连接
2. 选择任意一个群聊消息, 右键回复该消息, 该bug就会触发

**期望的结果**

解决此异常

**环境信息：**

 - OS: win10
 - Python 3.8 x64
 - Nonebot Version: v2.0.0a11

**截图**

[https://z3.ax1x.com/2021/03/30/cFWopn.png](url)

**Comment by yanyongyu** [comment]
这是gocq的问题与nonebot无关

顺便提一下问题发生的可能性：

- 你回复的消息gocq并没有收到，例如当时未启动gocq

**Comment by retroxz** [comment]
已确定问题是go-cqhttp数据库相关启动失败
