### ISSUE TITLE
Plugin: 防撤回

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#3054]
### PyPI 项目名

nonebot-prevent-withdrawal

### 插件 import 包名

nonebot_prevent_withdrawal

### 标签

[]

**Comment by yanyongyu** [comment]
你的插件内使用了data目录下的同一个文件名进行读写和发送，会在并发中产生问题，建议使用tempfile生成的随机临时文件路径或cache目录下自行生成不同文件名发送。

**Comment by zhongwen-4** [comment]
> 你的插件内使用了data目录下的同一个文件名进行读写和发送，会在并发中产生问题，建议使用tempfile生成的随机临时文件路径或cache目录下自行生成不同文件名发送。

有吗，我插件的data.json文件里面写的全是配置项来着

**Comment by yanyongyu** [comment]
https://github.com/zhongwen-4/nonebot-prevent-withdrawal/blob/a5e430c7a449d0aaf6a1d572c30fb357c2111247/src/nonebot_prevent_withdrawal/__init__.py#L289

**Comment by zhongwen-4** [comment]
已更新

**Comment by yanyongyu** [comment]
你需要用随机文件名来避免覆写。。。

**Comment by zhongwen-4** [comment]
已更新
