### ISSUE TITLE
Feature: 插件元数据新增字段以描述展示在NB商店的tag

### ISSUE THREAD

**Issue by ChenXu233** [nonebot/nonebot2#3056]
### 希望能解决的问题

NB商店中有一个tag，用来描述插件相关信息，能否将tag加入插件元数据中？这样在发布插件数据的时候，就无需填写相关内容，而在编写代码元数据的时候就可以写了。

顺便还能规范化一下tag？

### 描述所需要的功能

在插件元数据中添加新字段，用以描述插件展示在商店中的tag

**Comment by yanyongyu** [comment]
tag放在商店里发布的时候还可以选择已有的tag
