### ISSUE TITLE
Plugin: Bot的消息也是消息

### ISSUE THREAD

**Issue by eya46** [nonebot/nonebot2#3063]
### PyPI 项目名

nonebot-plugin-mmm

### 插件 import 包名

nonebot_plugin_mmm

### 标签

[{"label":"人机合一","color":"#ea5252"}]

**Comment by eya46** [comment]
`updata`

**Comment by yanyongyu** [comment]
你的bot handle event最后使用create task来异步进行，否则会阻塞sent事件传递。记得把task ref存储并在shutdown的时候cancel。

**Comment by eya46** [comment]
`updata`

**Comment by MeetWq** [comment]
updata
