### ISSUE TITLE
Plugin: pong

### ISSUE THREAD

**Issue by eya46** [nonebot/nonebot2#3065]
### PyPI 项目名

nonebot-plugin-pong

### 插件 import 包名

nonebot_plugin_pong

### 标签

[{"label":"ping","color":"#ff0000"},{"label":"pong","color":"#0000ff"}]

**Comment by tkgs0** [comment]
ping

**Comment by eya46** [comment]
> ping

pong

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器

**Comment by eya46** [comment]
`updata`
