### ISSUE TITLE
Plugin: 群聊广播插件

### ISSUE THREAD

**Issue by F1Justin** [nonebot/nonebot2#3071]
### PyPI 项目名

nonebot-plugin-specify-broadcast

### 插件 import 包名

nonebot_plugin_specify_broadcast

### 标签

[{"label":"广播","color":"#5dbe8a"}]

### 插件配置项

_No Response_

### 插件测试

- [x] 🔥插件测试中，请稍后

**Comment by yanyongyu** [comment]
插件配置项编写错误，请参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)使用，并移除pydantic和pydantic-settings依赖限制，提升nb版本限制到 2.2.0+ 。插件logger请参考[文档](https://nonebot.dev/docs/appendices/log)使用nb提供的logger。插件指令不正确，你加\*\*干什么。

**Comment by yanyongyu** [comment]
@F1Justin 是否有更新？

**Comment by F1Justin** [comment]
> [@F1Justin](https://github.com/F1Justin) 是否有更新？

已尝试修复了所述问题

**Comment by yanyongyu** [comment]
插件读取配置项的方式不正确，请参考文档，不要自行修改config读取方式。

**Comment by F1Justin** [comment]
> [@F1Justin](https://github.com/F1Justin) 是否有更新？

暂时没有时间更新（

**Comment by yanyongyu** [comment]
@F1Justin issue开了太久了，如果没有更新请更新后重新发布
