### ISSUE TITLE
Plugin: nonebot-plugin-api-scheduler

### ISSUE THREAD

**Issue by mmdexb** [nonebot/nonebot2#3073]
### PyPI 项目名

nonebot-plugin-api-scheduler

### 插件 import 包名

nonebot_plugin_api_scheduler

### 标签

[{"label":"scheduler","color":"#ea5252"},{"label":"api","color":"#ea5252"}]

### 插件配置项

_No Response_

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
@mmdexb 测试还未通过，是否有更新？

**Comment by yanyongyu** [comment]
请在插件中判断当前驱动器是否支持使用，如果不支持给出warning日志，而不是直接假定用户使用fastapi，这样会产生报错。

**Comment by yanyongyu** [comment]
@mmdexb 是否有更新？

**Comment by mmdexb** [comment]
已进行修复

**Comment by yanyongyu** [comment]
你的判断方法不对啊，fastapi 是 driver 不是 adapter。你应该使用

```python
from fastapi import FastAPI
from nonebot.drivers import ASGIMixin

driver = nonebot.get_driver()
isinstance(driver, ASGIMixin) and isinstance(nonebot.get_app(), FastAPI)
```

**Comment by mmdexb** [comment]
> 你的判断方法不对啊，fastapi 是 driver 不是 adapter。你应该使用
> 
> from fastapi import FastAPI
> from nonebot.drivers import ASGIMixin
> 
> driver = nonebot.get_driver()
> isinstance(driver, ASGIMixin) and isinstance(nonebot.get_app(), FastAPI)

已完成修改，感谢修正
