### ISSUE TITLE
Plugin: nonebot-plugin-leetcodeapi-khasa

### ISSUE THREAD

**Issue by KhasAlushird** [nonebot/nonebot2#3074]
### PyPI 项目名

nonebot-plugin-leetcodeAPI-KHASA

### 插件 import 包名

nonebot_plugin_leetcodeAPI_KHASA

### 标签

[{"label":"leetcode","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
插件依赖没有填写版本限制，请正确添加，nb的版本应为 2.2.0+ 。插件元数据缺少配置项，配置项应为小写。httpx 请使用 async client 进行异步请求。

**Comment by KhasAlushird** [comment]
> 插件依赖没有填写版本限制，请正确添加，nb的版本应为 2.2.0+ 。插件元数据缺少配置项，配置项应为小写。httpx 请使用 async client 进行异步请求。

现已解决并通过了bot测试。

**Comment by KhasAlushird** [comment]
> 你的代码没有更新到仓库

抱歉，现已同步到仓库
