### ISSUE TITLE
Plugin: Comfyui绘图插件

### ISSUE THREAD

**Issue by DiaoDaiaChan** [nonebot/nonebot2#3080]
### PyPI 项目名

nonebot-plugin-comfyui

### 插件 import 包名

nonebot_plugin_comfyui

### 标签

[{"label":"comfyui","color":"#ea5252"},{"label":"AI绘图","color":"#ea5252"}]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
插件依赖没有限制版本，请正确添加依赖，nb版本需要 2.2.0+ 。

**Comment by DiaoDaiaChan** [comment]
更新依赖nonebot2>=2.2.0

**Comment by yanyongyu** [comment]
你其他依赖还是没有加版本限制啊

**Comment by DiaoDaiaChan** [comment]
豪~都听叮咚佬的加上了
