### ISSUE TITLE
Bot: CanrotBot

### ISSUE THREAD

**Issue by wangyw15** [nonebot/nonebot2#3085]
### 机器人名称

CanrotBot

### 机器人描述

有很多实用功能的bot，也有很多没什么用的娱乐功能；接入了大模型，并且有一部分功能可以被大模型调用。主打一个全都有（

### 机器人项目仓库/主页链接

https://github.com/wangyw15/CanrotBot

### 标签

[]

**Comment by zhongwen-4** [comment]
你的插件名称不符合规范，项目尚未发布到pypi，插件元数据尚未填写，请参考[这里](https://nonebot.dev/docs/developer/plugin-publishing)修改后重新从[插件商店](https://nonebot.dev/store/plugins)发布插件

**Comment by zhongwen-4** [comment]
看错了()
