### ISSUE TITLE
Plugin: b站弹幕监控

### ISSUE THREAD

**Issue by STESmly** [nonebot/nonebot2#3090]
### PyPI 项目名

nonebot-plugin-bililivedm

### 插件 import 包名

nonebot_plugin_bililivedm

### 标签

[{"label": "bilibili", "color": "#ea5252"}, {"label": "全平台可用", "color": "#232a7a"}]

**Comment by yanyongyu** [comment]
插件读取配置项的方式不正确。依赖的httpx没有使用吧。还有你这个ws连接自己是什么鬼，你这么写换个地方就跑不了了。还有为什么要在插件里做tkinter界面。

**Comment by STESmly** [comment]
> 插件读取配置项的方式不正确。依赖的httpx没有使用吧。还有你这个ws连接自己是什么鬼，你这么写换个地方就跑不了了。还有为什么要在插件里做tkinter界面。

修改配置项读取方式，移除多余依赖，移除tk界面，修改默认的ws链接地址

**Comment by STESmly** [comment]
重新上传

**Comment by STESmly** [comment]
> 你不应该使用ws来连接ob地址，你发送的事件都是无效的。ob有完整的bot握手和事件格式协议。

这个我在上传的时候忘改了（可能造成了误导），重新上传的那一版已经把默认和演示的ws地址改为了8000/bilidm了

**Comment by yanyongyu** [comment]
@STESmly 插件加载未通过请修改后重新测试

**Comment by STESmly** [comment]
> [@STESmly](https://github.com/STESmly) 插件加载未通过请修改后重新测试

哈哈哈，抱歉，才发现之前那版的pypi上传失败了，已经修改重新上传了

**Comment by yanyongyu** [comment]
你 `get_plugin_config` 为什么要写这么多次。

**Comment by STESmly** [comment]
> 你 `get_plugin_config` 为什么要写这么多次。

已修改
