### ISSUE TITLE
Feature: 配置管理改进

### ISSUE THREAD

**Issue by tomorinao-www** [nonebot/nonebot2#3099]
### 希望能解决的问题

默认使用的env文件配置很多用户不适应，不够现代化，导致许多插件设计了自己的yml和JSON配置管理

### 描述所需要的功能

yml和JSON配置管理好处有：
1，现代化配置文件，读写方便，语法提示，一键格式化
2，有预设配置文件，用户不需要复制粘贴配置项名，防止出错
推荐参照这些插件，推广到全插件的配置管理

**Comment by yanyongyu** [comment]
之所以不采用yaml与json，是综合考虑的结果。yaml和json文件都会在容器化部署时增加用户上手难度，不够灵活，dotenv 是目前 docker / k8s 均有良好支持的通用方案。

**Comment by tomorinao-www** [comment]
但是很多插件都有自己的JSON，yaml配置，而不使用你们的env，那是否应该给开发者建议一下，或者统一一下各个插件的配置系统标准规范，比如自定义配置应该放在什么文件夹

友利奈绪-勿忘我
***@***.***








---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月1日(周五) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nonebot/nonebot2] Feature: 配置管理改进 (Issue #3099)




 
之所以不采用yaml与json，是综合考虑的结果。yaml和json文件都会在容器化部署时增加用户上手难度，不够灵活，dotenv 是目前 docker / k8s 均有良好支持的通用方案。
 
&mdash;

**Comment by yanyongyu** [comment]
目前商店发布的插件都要求使用nb的配置项，或者使用localstore插件统一目录，localstore目录也可以由用户通过dotenv配置。
