### ISSUE TITLE
考慮移除 shebang lines

### ISSUE THREAD

**Issue by cleoold** [nonebot/nonebot2#31]
諸如

https://github.com/nonebot/nonebot2/blob/2c13303d89217eee0690435f55ebb9ac7f3b33a7/nonebot/message.py#L1
https://github.com/nonebot/nonebot2/blob/2c13303d89217eee0690435f55ebb9ac7f3b33a7/nonebot/exception.py#L2

這些注釋除了製造誤解外沒有任何作用。

**Comment by richardchien** [comment]
确实，似乎是 Python 2 时代的东西了
