### ISSUE TITLE
Plugin: nonebot-reply

### ISSUE THREAD

**Issue by hriyel** [nonebot/nonebot2#3104]
### PyPI 项目名

nonebot-reply

### 插件 import 包名

nonebot_reply

### 标签

[{"label":"复读","color":"#45D7E0"}]

### 插件配置项

None

**Comment by hriyel** [comment]
更新

**Comment by hriyel** [comment]
update

**Comment by afterow** [comment]
尊敬的插件开发者您好，很感谢您对NoneBot社区插件的贡献，我们查看了您的代码，发现了如下问题：


1. 你的项目名不对，你这个是插件，不是nonebot生态的一部分
2. nonebot是一个牛而逼之的框架，你关于插件开发的问题都可以在[nb官方文档](https://nonebot.dev/docs/next/developer/plugin-publishing)找到，
3. 另外你目前的问题大部分也可以你之前的[issues](https://github.com/nonebot/nonebot2/issues/2991)找到
4. 我注意到，在您提出的问题中，存在不少重复与错误之处，这会对您的学习python有很大的影响。因此，我诚挚地建议您借助笔记来优化学习体验。强烈推荐您采用支持Markdown格式的笔记软件以减少重复错误

或许你访问不了nonebot文档下面是文档内容，我这边贴心的为你复制了
`NoneBot 插件使用下述命名规范：
对于项目名，建议统一以 nonebot-plugin- 开头，之后为拟定的插件名字，词间用横杠 - 分隔；
项目名用于代码仓库名称、PyPI 包的发布名称等；
`
你也可以使用下面的命令安装将文档离线
```
nb plugin install nonebot_plugin_docs
```
安装完成后使用
```
nb run
```
等插件启动后可以在你的浏览器随时打开

**Comment by yanyongyu** [comment]
插件包名请以 nonebot-plugin-xxx 的格式命名。另外请正确填写插件的依赖以通过测试。
