### ISSUE TITLE
Plugin: PyPi下载统计

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#3108]
### PyPI 项目名

nonebot-plugin-pypistats

### 插件 import 包名

nonebot_plugin_pypistats

### 标签

[]

**Comment by zhongwen-4** [comment]
修复bug（）

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器。pypistats 的请求看上去是同步的，他提供了api接口，可以直接使用httpx进行异步的请求。

**Comment by zhongwen-4** [comment]
> 插件元数据缺少支持的适配器。pypistats 的请求看上去是同步的，他提供了api接口，可以直接使用httpx进行异步的请求。

全平台适配可以不写适配器吗（
***
已更新

**Comment by yanyongyu** [comment]
你用的alconna那你得继承alconna支持的适配器，另外你的代码是不是没有更新到仓库。

**Comment by zhongwen-4** [comment]
已更新

**Comment by yanyongyu** [comment]
`inherit_supported_adapters` 直接从 nonebot.plugin 导入即可

**Comment by zhongwen-4** [comment]
已更新
