### ISSUE TITLE
Plugin: 权限控制

### ISSUE THREAD

**Issue by Yan-Zero** [nonebot/nonebot2#3111]
### PyPI 项目名

nonebot-plugin-pam

### 插件 import 包名

nonebot_plugin_pam

### 标签

[{"label":"rule","color":"#ea5252"}]

### 插件配置项

_No Response_

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件不能假定用户使用的是fastapi驱动器，应该要做检查。插件数据请使用 localstore 插件存储。

**Comment by yanyongyu** [comment]
@Yan-Zero 是否有更新？

**Comment by Yan-Zero** [comment]
> 插件不能假定用户使用的是fastapi驱动器，应该要做检查。插件数据请使用 localstore 插件存储。

感谢提醒。已经添加了 FastAPI 驱动器的检测。
关于插件数据，经过测试，localstore 并不能很好的满足需要，因为插件主要是基于 nonebot2 的实例进行管理——即，多个机器人相互独立。
如果使用 localstore 的 config_dir，那么存在某些程度的障碍，并且也不如之间放在机器人目录下方便，并且以 "plugin_name"/"command".yaml 或者 "plugin_name".yaml 的组织形式插件规则也更加清晰

**Comment by yanyongyu** [comment]
用户是可以指定localstore存储目录的，可以通过调整存储目录到项目目录下来分开存储。或者你也可以提供配置文件路径的选项，而不是写死路径。

**Comment by Yan-Zero** [comment]
> 用户是可以指定localstore存储目录的，可以通过调整存储目录到项目目录下来分开存储。或者你也可以提供配置文件路径的选项，而不是写死路径。

好的，添加了配置项了
