### ISSUE TITLE
Plugin: nonebot_plugin_better_broadcast

### ISSUE THREAD

**Issue by captain-wangrun-cn** [nonebot/nonebot2#3113]
### PyPI 项目名

nonebot-plugin-better-broadcast

### 插件 import 包名

nonebot_plugin_better_broadcast

### 标签

[{"label":"广播","color":"#1fd5ec"},{"label":"broadcast","color":"#231fec"}]

### 插件配置项

_No Response_

**Comment by yanyongyu** [comment]
插件依赖的nb版本应该是2.2.0+。插件依赖请勿限制 pydantic 版本。

**Comment by captain-wangrun-cn** [comment]
> 插件依赖的nb版本应该是2.2.0+。插件依赖请勿限制 pydantic 版本。

已提升nonebot2依赖版本为2.2.0+，并移除pydantic版本限制
