### ISSUE TITLE
Plugin: 恩情课文

### ISSUE THREAD

**Issue by zhaomaoniu** [nonebot/nonebot2#3122]
### PyPI 项目名

nonebot-plugin-kindness-lesson

### 插件 import 包名

nonebot_plugin_kindness_lesson

### 标签

[]

### 插件配置项

```dotenv
KINDNESS_LESSON_API_KEY=sd-0d000721
```

**Comment by zhaomaoniu** [comment]
1

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器。插件配置项读取不需要自己判断pydantic版本，直接使用nb提供的方法。

**Comment by zhaomaoniu** [comment]
已修改
