### ISSUE TITLE
Plugin: nb商店插件安装器web版

### ISSUE THREAD

**Issue by CM-Edelweiss** [nonebot/nonebot2#3125]
### PyPI 项目名

nonebot-plugin-manageweb

### 插件 import 包名

nonebot_plugin_manageweb

### 标签

[{"label":"webui","color":"#ea5252"},{"label":"插件更新","color":"#505d4d"}]

### 插件配置项

_No Response_

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件元数据缺少支持的适配器。

**Comment by CM-Edelweiss** [comment]
> 插件元数据缺少支持的适配器。

纯webui服务，适配所有适配器

**Comment by yanyongyu** [comment]
> 纯webui服务，适配所有适配器

也需要填写None

**Comment by CM-Edelweiss** [comment]
已更新
