### ISSUE TITLE
Adapter: Mail

### ISSUE THREAD

**Issue by mobyw** [nonebot/nonebot2#3128]
### 适配器名称

Mail

### 适配器描述

邮件收发协议

### PyPI 项目名

nonebot-adapter-mail

### 适配器 import 包名

nonebot.adapters.mail

### 适配器项目仓库/主页链接

https://github.com/mobyw/nonebot-adapter-mail

### 标签

[]

**Comment by yanyongyu** [comment]
适配器依赖版本限制不对，~=限制了 patch 版本

**Comment by mobyw** [comment]
> 适配器依赖版本限制不对，~=限制了 patch 版本

Fixed in version [1.0.0-alpha.3](https://github.com/mobyw/nonebot-adapter-mail/commit/2cb00f68bdc331c5e32b555c22896b1d48d2f86b)
