### ISSUE TITLE
建议：在 alpha 期间不使用带 post 的版本号

### ISSUE THREAD

**Issue by 7sDream** [nonebot/nonebot2#313]
由于 python-poetry/poetry#3657 这个 bug 的存在，poetry 现在无法安装带 post 版本的 alpha release。

而 poetry 是文档里的推荐项目管理方式，所以用带 post 版本来问题修复会让较多下游项目无法接收到版本更新……

比如 0eadf5f4e989ef0206c0fc43c9a97eb5d97aa783 和 85f002335059b328ed7f36f299368f29bb18c35b 最近的这两个修复 load error 的 commit 在 2.0.0a13.post1 里，但是使用 poetry 只能安装到 2.0.0.a13，会导致项目出错。

**Comment by mnixry** [comment]
现阶段我们需要一种表达方式来表达"功能性更新"和"修复性更新"的区别
而.post就提供了这种标识, 不过poetry不能识别这种标记也确实是一种硬伤

如果您有更好的想法, 可以随时提出

**Comment by 7sDream** [comment]
poetry 是处理 alpha release(prerelease) 的 post version 有问题，正常版本的 post version 是没问题的。

也确实没啥别的好方案，只能说期待尽快结束 alpha 期了😄️~

**Comment by yanyongyu** [comment]
由于poetry采用semver管理版本号，与pep440规定的python package版本管理存在冲突，poetry无法识别post release
