### ISSUE TITLE
Plugin: nonebot-plugin-zepplife

### ISSUE THREAD

**Issue by 1296lol** [nonebot/nonebot2#3131]
### PyPI 项目名

nonebot-plugin-zepplife

### 插件 import 包名

nonebot_plugin_zepplife

### 标签

[{"label":"运动","color":"#34cb0e"}]

### 插件配置项

```dotenv
ZEPPLIFE_USER=""
ZEPPLIFE_PASSWORD=""
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by 1296lol** [comment]
更新了pyproject.toml

**Comment by yanyongyu** [comment]
插件依赖了requests，请使用 httpx 的 AsyncClient 代替。插件配置项编写错误，请正确填写配置项的名称并移除默认值中的 `config.xxx`。

**Comment by 1296lol** [comment]
已使用AsyncCilent代替requests，移除了对requests的依赖；插件配置项已更新
