### ISSUE TITLE
Plugin: nonebot-plugin-hyp

### ISSUE THREAD

**Issue by Reversedeer** [nonebot/nonebot2#3139]
### PyPI 项目名

nonebot-plugin-hyp

### 插件 import 包名

nonebot_plugin_hyp

### 标签

[{"label":"Hypixel","color":"#d5a446"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件读取配置项的方法不正确，https://github.com/Reversedeer/nonebot_plugin_hyp/blob/4af5152f21c08557440a05cf2fa51b5d78e7fbc1/nonebot_plugin_hyp/utils.py#L35-L45 。请参考[文档](https://nonebot.dev/docs/appendices/config#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)使用，并在插件元数据内添加配置类

**Comment by Reversedeer** [comment]
已使用pydantic==2.10.2管理插件配置

**Comment by yanyongyu** [comment]
。。。usage请不要写在配置项里，另外插件元数据需要填写config

**Comment by Reversedeer** [comment]
...改完电脑没电了，还没测，只能晚上再改了(

**Comment by Reversedeer** [comment]
更新

**Comment by yanyongyu** [comment]
你的依赖里限制了pydantic版本，nb这边需要兼容1和2，如果你没有特殊版本要求请删除。

**Comment by Reversedeer** [comment]
> 你的依赖里限制了pydantic版本，nb这边需要兼容1和2，如果你没有特殊版本要求请删除。

插件不需要限制版本吗，还是nb这边限制了就行

**Comment by yanyongyu** [comment]
> 插件不需要限制版本吗，还是nb这边限制了就行

你也可以复制nb的版本限制，兼容1和2，但是别写死2

**Comment by Reversedeer** [comment]
已改qwq(
