### ISSUE TITLE
Plugin: 喜报/悲报 生成器

### ISSUE THREAD

**Issue by CNFrestone** [nonebot/nonebot2#3141]
#没整明白咋上传（草）
### PyPI 项目名

喜报/悲报 生成器

### 插件 import 包名

xibao_and_beibao_mod

### 标签

[{"label":"func","color":"#e75050"},{"label":"喜报","color":"#f3c20a"},{"label":"悲报","color":"#696867"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by CNFrestone** [comment]
> 使用指令 "喜报+内容"/“悲报+内容“来生成图片

**Comment by CNFrestone** [comment]
> ### PyPI 项目名
> 喜报/悲报 生成器
> 
> ### 插件 import 包名
> xibao_and_beibao_mod
> 
> ### 标签
> [{"label":"func","color":"#e75050"},{"label":"喜报","color":"#f3c20a"},{"label":"悲报","color":"#696867"}]
> 
> ### 插件配置项

**Comment by he0119** [comment]
可以参考这里。<https://nonebot.dev/docs/developer/plugin-publishing#%E5%8F%91%E5%B8%83%E8%87%B3-pypi>

**Comment by yanyongyu** [comment]
请先参考[nb文档](https://nonebot.dev/docs/developer/plugin-publishing)或者https://packaging.python.org/en/latest/ 发布你的插件到 pypi 后再来发布插件到 nb 商店
