### ISSUE TITLE
Plugin: ZXWB词库问答

### ISSUE THREAD

**Issue by HibiKier** [nonebot/nonebot2#3142]
### PyPI 项目名

nonebot-plugin-zxwb

### 插件 import 包名

nonebot_plugin_zxwb

### 标签

[{"label":"小真寻","color":"#fbe4e4"},{"label":"多平台适配","color":"#ea5252"},{"label":"词条问答","color":"#527dea"}]

### 插件配置项

```dotenv
zxwb_db_url=None
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by HibiKier** [comment]
1

**Comment by yanyongyu** [comment]
插件依赖写死了tortoise orm的版本，插件支持的适配器需要再继承下uninfo？你的logger为啥不从nb导入。

**Comment by HibiKier** [comment]
已更新插件homepage地址

**Comment by yanyongyu** [comment]
你没发版。。

**Comment by HibiKier** [comment]
已发版
