### ISSUE TITLE
Plugin: CSGO_MARKET

### ISSUE THREAD

**Issue by Florenz0707** [nonebot/nonebot2#3144]
### PyPI 项目名

nonebot-plugin-csgomarket

### 插件 import 包名

nonebot_plugin_csgomarket

### 标签

[{"label":"CSGO","color":"#fb9f29"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by Florenz0707** [comment]
除了page.set_content外，已修改完毕。

**Comment by yanyongyu** [comment]
你插件支持的适配器为什么不是继承 alconna 和 uninfo 的。。。

**Comment by Florenz0707** [comment]
已修改。

**Comment by yanyongyu** [comment]
你的uninfo插件没有require

**Comment by Florenz0707** [comment]
没有使用uninfo插件，已从poetry.dependencies和inherit_supported_adapters中移除uninfo
