### ISSUE TITLE
windows下，创建插件和注册事件之后测试一直没反应 Checking for matchers in priority 1...

### ISSUE THREAD

**Issue by youlingforever0328** [nonebot/nonebot2#315]
**windows下，创建插件和注册事件之后测试一直没反应 Checking for matchers in priority 1...

**Comment by yanyongyu** [comment]
请给出你的日志截图和代码，不按格式来的我怎么回答你啊（

**Comment by youlingforever0328** [comment]
自定义插件代码:
esp32cam.py：


from nonebot import on_command
from nonebot.rule import to_me
from nonebot.typing import T_State
from nonebot.adapters import Bot, Event


weather = on_command("天气", rule=to_me(), priority=1)




@weather.handle()
async def handle_first_receive(bot: Bot, event: Event, state: T_State):
&nbsp; &nbsp; args = str(event.get_message()).strip()&nbsp; # 首次发送命令时跟随的参数，例：/天气 上海，则args为上海
&nbsp; &nbsp; print(f"==={args}===")
&nbsp; &nbsp; if args:
&nbsp; &nbsp; &nbsp; &nbsp; state["city"] = args&nbsp; # 如果用户发送了参数则直接赋值




@weather.got("city", prompt="你想查询哪个城市的天气呢？")
async def handle_city(bot: Bot, state: T_State):
&nbsp; &nbsp; city = state["city"]
&nbsp; &nbsp; if city not in ["上海", "北京"]:
&nbsp; &nbsp; &nbsp; &nbsp; await weather.reject("你想查询的城市暂不支持，请重新输入！")
&nbsp; &nbsp; # weather = await get_weather_from_xxx(city)
&nbsp; &nbsp; city_weather = "晴天"
&nbsp; &nbsp; # await bot.send(city_weather)
&nbsp; &nbsp; await weather.finish(city_weather)





bot.py:


#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import nonebot
from nonebot.adapters.cqhttp import Bot as CQHTTPBot


# Custom your logger
#&nbsp;
# from nonebot.log import logger, default_format
# logger.add("error.log",
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; rotation="00:00",
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; diagnose=False,
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; level="ERROR",
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; format=default_format)


# You can pass some keyword args config to init function
nonebot.init()


driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)


nonebot.load_builtin_plugins()
nonebot.load_from_toml("pyproject.toml")
&nbsp;
nonebot.load_plugins("src/plugins") # 自定义的插件esp32cam在src/plugins下




app = nonebot.get_asgi()


# Modify some config / config depends on loaded configs
#&nbsp;
# config = driver.config
# do something...




if __name__ == "__main__":
&nbsp; &nbsp; nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
&nbsp; &nbsp; nonebot.run(app="__mp_main__:app")



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nonebot/nonebot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nonebot/nonebot2] windows下，创建插件和注册事件之后测试一直没反应 Checking for matchers in priority 1... (#315)





 
请给出你的日志截图和代码，不按格式来的我怎么回答你啊（

**Comment by yanyongyu** [comment]
能否截图或者使用markdown代码块格式发送，我这看到的全是乱码

**Comment by youlingforever0328** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nonebot/nonebot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nonebot/nonebot2] windows下，创建插件和注册事件之后测试一直没反应 Checking for matchers in priority 1... (#315)





 
能否截图或者使用markdown代码块格式发送，我这看到的全是乱码

**Comment by yanyongyu** [comment]
请你使用github网页版或官方客户端进行回复，你这邮件回复全是乱码

**Comment by youlingforever0328** [comment]
### 自定义插件代码 esp32cam.py 
![image](https://user-images.githubusercontent.com/57934209/113704971-6df4de80-970f-11eb-9d54-cb06ef7386f1.png)

### bot.py
![image](https://user-images.githubusercontent.com/57934209/113704984-75b48300-970f-11eb-9682-6b1fa1ec80a4.png)

### 运行结果 发送“天气”，一直在Checking for matchers in priority 1...
![image](https://user-images.githubusercontent.com/57934209/113704871-4bfb5c00-970f-11eb-886b-0a99b6a92352.png)

**Comment by yanyongyu** [comment]
你的配置使用的是 `command_start=["/"]` 请你使用 `/天气` 触发命令

**Comment by youlingforever0328** [comment]
好的，感谢
