### ISSUE TITLE
Docs: 建议在插件商店页数导航条中添加输入页数跳转的功能

### ISSUE THREAD

**Issue by liuzhaoze** [nonebot/nonebot2#3150]
### 描述问题或主题

在插件商店中浏览插件时，如果看到30页关闭页面，想从31页继续浏览，需要多次点击下一页按钮

### 需做出的修改

在页数导航条右侧添加一个输入框和一个跳转按钮，实现在输入框中输入页数后点击跳转按钮，直接跳转至指定页码处

例如：

`跳转至 [  ] 页    [跳转]`

**Comment by yanyongyu** [comment]
跳转到页数感觉并不是什么必要的功能，正常也不会去一页一页浏览，搜索不是更好的方式？

**Comment by liuzhaoze** [comment]
好的，因为我自己确实在一页一页翻想要的插件（

**Comment by KomoriDev** [comment]
可以使用油猴脚本 [`nonebot-website-tweaker`](https://github.com/KomoriDev/nonebot-website-tweaker)，它允许你通过方向键（←→）切换页数
~虽然也可以输入，但多多少少有点问题~
