### ISSUE TITLE
Plugin: 链接分享解析器重制版

### ISSUE THREAD

**Issue by fllesser** [nonebot/nonebot2#3153]
### PyPI 项目名

nonebot-plugin-resolver2

### 插件 import 包名

nonebot_plugin_resolver2

### 标签

[{"label":"音频","color":"#cb324f"},{"label":"视频","color":"#cb324f"},{"label":"bilibili","color":"#ec3658"}]

### 插件配置项

_No Response_

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by fllesser** [comment]
新版已发布

**Comment by yanyongyu** [comment]
插件数据请使用 localstore 插件存储。插件存在滥用 regex 的情况，会导致机器人卡死的情况，请使用 keyword 或其他 rule 替代。

**Comment by fllesser** [comment]
> 插件数据请使用 localstore 插件存储。插件存在滥用 regex 的情况，会导致机器人卡死的情况，请使用 keyword 或其他 rule 替代。

已做调整

**Comment by yanyongyu** [comment]
httpx应该使用AsyncClient异步请求。

**Comment by fllesser** [comment]
> httpx应该使用AsyncClient异步请求。

哭，还有什么问题，ddl都一并说了吧

**Comment by fllesser** [comment]
> httpx应该使用AsyncClient异步请求。

改好了

**Comment by fllesser** [comment]
改错了，明天再改

**Comment by fllesser** [comment]
> 。

改好了

**Comment by fllesser** [comment]
> httpx应该使用AsyncClient异步请求。

改好了，ddl
