### ISSUE TITLE
Plugin: Arcaea表情包生成器

### ISSUE THREAD

**Issue by JQ-28** [nonebot/nonebot2#3159]
### PyPI 项目名

nonebot-plugin-arcaea-sticker

### 插件 import 包名

nonebot_plugin_arcaea_sticker

### 标签

[{"label":"Arcaea","color":"#1f1e33"},{"label":"表情包","color":"#d560e2"}]

### 插件配置项

```dotenv
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件数据请使用 localstore 存储

**Comment by yanyongyu** [comment]
@JQ-28 是否有更新？

**Comment by yanyongyu** [comment]
请使用 localstore >= 0.7 提供的 get_plugin_cache_dir 。

**Comment by JQ-28** [comment]
> 请使用 localstore >= 0.7 提供的 get_plugin_cache_dir 。

更新了插件并移除了缓存
