### ISSUE TITLE
Plugin: 名片赞，表情回应插件

### ISSUE THREAD

**Issue by fllesser** [nonebot/nonebot2#3169]
### PyPI 项目名

nonebot-plugin-emojilike

### 插件 import 包名

nonebot_plugin_emojilike

### 标签

[{"label":"赞","color":"#e8ec2a"},{"label":"emoji","color":"#e5e861"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
localstore的版本不对，应该是大于等于 0.7.0 。

**Comment by fllesser** [comment]
> localstore的版本不对，应该是大于等于 0.7.0 。

改好了
