### ISSUE TITLE
Plugin: 奶龙魔法

### ISSUE THREAD

**Issue by Refound-445** [nonebot/nonebot2#3173]
### PyPI 项目名

nonebot-plugin-nailongmagic

### 插件 import 包名

nonebot_plugin_nailongmagic

### 标签

[{"label":"SD","color":"#3645e3"},{"label":"nailong","color":"#edd81b"},{"label":"func","color":"#43ed1b"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by he0119** [comment]
```log
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

感觉你这个插件可能在测试环境里跑不起来。

**Comment by yanyongyu** [comment]
插件缓存目录请使用 localstore 。插件使用了 pydantic v2 的 validator 写法，建议删除。

**Comment by Refound-445** [comment]
> 插件缓存目录请使用 localstore 。插件使用了 pydantic v2 的 validator 写法，建议删除。

1

**Comment by yanyongyu** [comment]
你还是没有使用 localstore 啊，请使用 localstore 插件获取插件缓存目录，并删除配置项

**Comment by Refound-445** [comment]
> 你还是没有使用 localstore 啊，请使用 localstore 插件获取插件缓存目录，并删除配置项

2

**Comment by yanyongyu** [comment]
配置项请删除，localstore 提供了统一的配置项。

**Comment by Refound-445** [comment]
> 配置项请删除，localstore 提供了统一的配置项。

3
