### ISSUE TITLE
Plugin: 南无阿弥陀佛

### ISSUE THREAD

**Issue by Kaguya233qwq** [nonebot/nonebot2#3177]
### PyPI 项目名

nonebot-plugin-amitabha

### 插件 import 包名

nonebot_plugin_amitabha

### 标签

[{"label":"念佛","color":"#fae1a9"},{"label":"阿弥陀佛","color":"#fab6a9"}]

### 插件配置项

```dotenv
send_interval=5
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件数据请使用 localstore 存储

**Comment by Kaguya233qwq** [comment]
> 插件数据请使用 localstore 存储

插件已使用localstore

**Comment by yanyongyu** [comment]
使用localstore后就不需要单独给配置项了，localstore有配置选项

**Comment by Kaguya233qwq** [comment]
> 使用localstore后就不需要单独给配置项了，localstore有配置选项

好的~蟹蟹ddl

**Comment by Kaguya233qwq** [comment]
updated

**Comment by yanyongyu** [comment]
插件导入 localstore 前需要 require

**Comment by Kaguya233qwq** [comment]
已使用require
