### ISSUE TITLE
Plugin: nonebot_plugin_pjsekaihelper

### ISSUE THREAD

**Issue by Ant1816** [nonebot/nonebot2#3179]
### PyPI 项目名

nonebot-plugin-pjsekaihelper

### 插件 import 包名

nonebot_plugin_pjsekaihelper

### 标签

[{"label":"pjsk","color":"#ea5252"},{"label":"世界计划","color":"#52ea5a"},{"label":"音游","color":"#52c5ea"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件依赖里多了 datetime 和 pathlib，ob 适配器版本缺少限制。param 请不要从 nb 的 internal 模块导入，请从 `nonebot.params` 导入。

**Comment by Ant1816** [comment]
依赖已删除datetime和pathlib, ob适配器版本限制为>=2.1.0, param从nonebot.params导入, 全局变量已经正确初始化

**Comment by yanyongyu** [comment]
插件还使用了 requests，请用 httpx.AsyncClient 或者 aiohttp 替代。插件内使用了运行目录读写文件，请使用 localstore 插件获取路径。插件配置使用了过时的 validator，要么别用，要么兼容 pydantic v1 和 v2。插件元数据缺少配置项。

**Comment by Ant1816** [comment]
插件已使用httpx.AsyncClient处理请求 全部读写操作已改用localstore获取目录 已经删除过时的validator 元数据补全配置项

**Comment by yanyongyu** [comment]
插件依赖里的 requests 没有删除。你 validator 的写法限定 pydantic v2了，你可以选择移除 validator 或者在插件依赖里限定 pydantic >=2.0.0。

**Comment by Ant1816** [comment]
插件依赖已删除requests pydantic版本限制为>=2.0
