### ISSUE TITLE
Plugin: nonebot-plugin-ollama

### ISSUE THREAD

**Issue by MaStAr1128** [nonebot/nonebot2#3181]
### PyPI 项目名

nonebot-plugin-ollama

### 插件 import 包名

nonebot_plugin_ollama

### 标签

[{"label":"LLM","color":"#da56f6"},{"label":"AI","color":"#56f65f"}]

### 插件配置项

```dotenv
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件依赖多了nb-cli，请删除。插件使用了 requests，请使用 `httpx.AsyncClient` 或 aiohttp 代替。插件元数据缺少支持的适配器。插件使用了 pydantic v2 的 validator，建议删除或者在插件内自行判断。

**Comment by MaStAr1128** [comment]
已按要求修改。
