### ISSUE TITLE
Plugin: nonebot-plugin-flo-luck

### ISSUE THREAD

**Issue by Florenz0707** [nonebot/nonebot2#3187]
### PyPI 项目名

nonebot-plugin-flo-luck

### 插件 import 包名

nonebot_plugin_flo_luck

### 标签

[{"label":"jrrp","color":"#52eae7"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件数据请使用 localstore 存储。

**Comment by Florenz0707** [comment]
修改完毕。
