### ISSUE TITLE
Plugin: 好友与群邀请管理

### ISSUE THREAD

**Issue by hakunomiko** [nonebot/nonebot2#3189]
### PyPI 项目名

nonebot-plugin-add-friends

### 插件 import 包名

nonebot_plugin_add_friends

### 标签

[{"label":"同意好友","color":"#04ff48"},{"label":"加群邀请","color":"#0ecdf7"}]

### 插件配置项

```dotenv
SUPERUSERS=["123123123"]
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件数据路径使用 localstore 不需要写配置项，localstore 有提供配置能力。

**Comment by hakunomiko** [comment]
> 插件数据路径使用 localstore 不需要写配置项，localstore 有提供配置能力。

已删除不必要的配置项
