### ISSUE TITLE
Plugin: 求生之路addons文件管理

### ISSUE THREAD

**Issue by ScorMax** [nonebot/nonebot2#3193]
### PyPI 项目名

nonebot-plugin-addons-manager

### 插件 import 包名

nonebot_plugin_addons_manager

### 标签

[{"label":"求生之路","color":"#FFFF6E"}]

### 插件配置项

destination_path = "/root/Steam/steamapps/common/Left 4 Dead 2 Dedicated Server/left4dead2/addons"
SUPERUSERS=["123456789"]

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件读取配置项的方式不正确，请参考文档使用 `get_plugin_config` 。插件使用了 CQ 码，请使用 MessageSegment 替代。

**Comment by ScorMax** [comment]
你好，目前已经修改插件读取配置项的方式，同时使用MessageSegment获取消息序列内容，但是不知道插件名的修改在哪修改

**Comment by ScorMax** [comment]
你好，这是我第一次写插件所以有些地方并不是很清楚，非常感谢解答，目前插件名已经修改，最新版本也已上传更新

**Comment by yanyongyu** [comment]
你插件的 admin qq 配置项不需要，可以直接用 nb 的 superusers。

**Comment by ScorMax** [comment]
已经删去admin_qq配置，使用SUPERUSERS进行权限管理
