### ISSUE TITLE
Plugin: 加群自动审批

### ISSUE THREAD

**Issue by padoru233** [nonebot/nonebot2#3200]
### PyPI 项目名

nonebot-plugin-auto-enter-group

### 插件 import 包名

nonebot_plugin_auto_enter_group

### 标签

[{"label":"群管","color":"#ea5252"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件元数据缺少主页。插件依赖的 nb 版本过低，请使用 2.2.0+。插件数据请使用 localstore 插件存储。
