### ISSUE TITLE
Plugin: 夸克搜

### ISSUE THREAD

**Issue by fllesser** [nonebot/nonebot2#3202]
### PyPI 项目名

nonebot-plugin-quark

### 插件 import 包名

nonebot_plugin_quark

### 标签

[{"label":"search","color":"#e1cfcf"},{"label":"quark","color":"#cfbfbf"}]

### 插件配置项

```dotenv

```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件依赖中 httpx 的版本限制填写错误，ob适配器请添加版本限制。

**Comment by fllesser** [comment]
> 插件依赖中 httpx 的版本限制填写错误，ob适配器请添加版本限制。

好惹

**Comment by yanyongyu** [comment]
你这httpx的版本还是不对啊，你得写上大于 xxx 小于 1.0.0

**Comment by fllesser** [comment]
> 你这httpx的版本还是不对啊，你得写上大于 xxx 小于 1.0.0

别骂了别骂了😭，不太懂这个规范
