### ISSUE TITLE
Plugin: 小真寻的WebUi

### ISSUE THREAD

**Issue by HibiKier** [nonebot/nonebot2#3205]
### PyPI 项目名

nonebot-plugin-zxui

### 插件 import 包名

nonebot_plugin_zxui

### 标签

[{"label":"小真寻","color":"#fbe4e4"},{"label":"WebUi","color":"#2bcaca"}]

### 插件配置项

```dotenv
zxui_username="admin"
zxui_password="admin"
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by he0119** [comment]
你这个插件配置项的格式不太对诶，应该是 dotenv 的写法（key=value）才行吧。

**Comment by yanyongyu** [comment]
插件数据可以使用 localstore 存储了，现在 localstore 支持按插件配置存储目录。

**Comment by HibiKier** [comment]
> 插件数据可以使用 localstore 存储了，现在 localstore 支持按插件配置存储目录。

已修改
