### ISSUE TITLE
Plugin: 群成员检测 dev版

### ISSUE THREAD

**Issue by zhongwen-4** [nonebot/nonebot2#3213]
### PyPI 项目名

nonebot-plugin-number-detection

### 插件 import 包名

nonebot_plugin_number_detection

### 标签

[{"label":"群管","color":"#ea5252"}]

### 插件配置项

```dotenv
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件配置项的名字建议都价格前缀，或者用scoped config

**Comment by zhongwen-4** [comment]
> 插件配置项的名字建议都价格前缀，或者用scoped config

已添加

**Comment by yanyongyu** [comment]
代码里有 print，如果你希望打日志请使用 nb 的 logger。你配置项的前缀为啥不用插件名相关的 detect。。。

**Comment by zhongwen-4** [comment]
> 代码里有 print，如果你希望打日志请使用 nb 的 logger。你配置项的前缀为啥不用插件名相关的 detect。。。

已删除，配置项已修改
