### ISSUE TITLE
Plugin: nonebot-plugin-suggarchat

### ISSUE THREAD

**Issue by JohnRichard4096** [nonebot/nonebot2#3215]
### PyPI 项目名

nonebot-plugin-suggarchat

### 插件 import 包名

nonebot_plugin_suggarchat

### 标签

[{"label":"ChatBot","color":"#ea5252"},{"label":"聊天","color":"#ea5252"},{"label":"OpenAI","color":"#ea5252"}]

### 插件配置项

```dotenv
```

### 插件测试

- [ ] 如需重新运行插件测试，请勾选左侧勾选框

**Comment by yanyongyu** [comment]
插件加载测试未通过，缺少ob适配器依赖
