### ISSUE TITLE
Plugin: 轻量化的本地数据存储

### ISSUE THREAD

**Issue by kanbereina** [nonebot/nonebot2#3225]
### PyPI 项目名

nonebot-plugin-litestore

### 插件 import 包名

nonebot_plugin_litestore

### 标签

[{"label":"store","color":"#51deda"},{"label":"lite","color":"#e6ebeb"},{"label":"lib","color":"#cc5741"}]

### 插件配置项

```dotenv

```

### 插件测试

- [x] 🔥插件测试中，请稍后

**Comment by yanyongyu** [comment]
目前商店发布插件均统一要求使用 localstore 插件，并可以通过配置项一键修改存储位置，暂时不考虑提供别的存储渠道。
