### ISSUE TITLE
Feature: 对日志一些提议

### ISSUE THREAD

**Issue by Kyomotoi** [nonebot/nonebot2#324]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

log 等级为 info 输出时，on_message 所触发的 Matcher 提示过于刷屏，影响查看日志查看。
详细如下：
![image.png](https://i.loli.net/2021/04/10/PLqhC3luU97DNWA.png)
可见，短短三句话，就已经占据了控制台的大部分位置
**描述你所需要的特性：**

在 config 中添加相关设置（开关），或者只有当 log 等级为 debug 时，才显示相关内容。

**Comment by yanyongyu** [comment]
日志等级改动是一件麻烦事（
暂时延后，做整体改动

**Comment by yanyongyu** [comment]
修改了部分日志等级，支持 `LOG_LEVEL` 自定义输出等级
