### ISSUE TITLE
Bug: Logger 发起对象名一律为 nonebot

### ISSUE THREAD

**Issue by Lancercmd** [nonebot/nonebot2#332]
**描述问题：**
![image](https://user-images.githubusercontent.com/59906398/115154552-ff6c3500-a0ad-11eb-8cca-7bbb0b1cc9d6.png)
在 [v2.0.0a11](https://github.com/nonebot/nonebot2/tree/v2.0.0a11) 及更早版本中，通过在事件处理的文件或者包中调用 `loguru.logger` 其输出的日志之发起对象名为该文件或包之名称
![image](https://user-images.githubusercontent.com/59906398/115154578-2cb8e300-a0ae-11eb-94f0-93857c642110.png)
在 [v2.0.0a13.post1](https://github.com/nonebot/nonebot2/tree/v2.0.0a13.post1) 中，使用相同方式输出的日志，其发起对象名一律为 nonebot

**期望的结果**

日志之发起对象名为该文件或包之名称

**环境信息：**

 - OS: windows-latest
 - Python Version: 3.9.4
 - Nonebot Version: v2.0.0a13.post1

**Comment by yanyongyu** [comment]
fixed
