### ISSUE TITLE
question: 部署成功，但外部插件无法使用

### ISSUE THREAD

**Issue by CNflysky** [nonebot/nonebot2#339]
**描述问题：**

在树莓派(arm64)上部署了go-cqhttp，然后按照文档里一步步部署了bot，最后发现，内置功能可以使用(/echo命令)，安装(nb plugin install)外部插件无法使用,发送插件定义的命令没有响应。
**如何复现？**

怀疑是python版本问题，升级至3.9故障依旧，遂在一台全新的x86 vps上安装，问题依旧（使用poetry安装会提示依赖版本冲突）

**期望的结果**

**环境信息：**

 - OS: Debian 10
 - Python Version: 3.9.2
 - Nonebot Version: 2.00a13-post1

**截图**
![IMG_20210427_010326](https://user-images.githubusercontent.com/48781081/116122461-64e6a400-a6f4-11eb-98d1-75b810f49be7.jpg)

ps:加了群没同意，只能先在这开个issue了

**Comment by yanyongyu** [comment]
请先检查你的nonebot2安装版本是否正确，以及环境是否为python3.7.3或更高

**Comment by CNflysky** [comment]
> 请先检查你的nonebot2安装版本是否正确，以及环境是否为python3.7.3或更高
> 
> 提供一下无法使用外部插件的日志

![IMG_20210427_014157](https://user-images.githubusercontent.com/48781081/116127437-6adf8380-a6fa-11eb-9196-083386a3b622.jpg)

04-27 01:44:53 [INFO] nonebot | NoneBot is initializing...
04-27 01:44:53 [INFO] nonebot | Current Env: dev
04-27 01:44:53 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
04-27 01:44:53 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
04-27 01:44:53 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
04-27 01:44:53 [INFO] nonebot | Succeeded to import "nonebot_plugin_status"
04-27 01:44:53 [INFO] nonebot | Running NoneBot...
04-27 01:44:53 [DEBUG] nonebot | Loaded adapters: cqhttp
04-27 01:44:53 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
04-27 01:44:53 [INFO] uvicorn | Started reloader process [20841] using watchgod
04-27 01:44:54 [INFO] nonebot | NoneBot is initializing...
04-27 01:44:54 [INFO] nonebot | Current Env: dev
04-27 01:44:54 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
04-27 01:44:54 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
04-27 01:44:54 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
04-27 01:44:54 [INFO] nonebot | Succeeded to import "nonebot_plugin_status"
04-27 01:44:54 [INFO] uvicorn | Started server process [20843]
04-27 01:44:54 [INFO] uvicorn | Waiting for application startup.
04-27 01:44:54 [INFO] uvicorn | Application startup complete.
04-27 01:44:57 [INFO] uvicorn | ('127.0.0.1', 40576) - "WebSocket /cqhttp/ws" [accepted]
04-27 01:44:57 [INFO] nonebot | WebSocket Connection from CQHTTP Bot ********** Accepted!
04-27 01:45:21 [INFO] nonebot | CQHTTP ********** | [message.private.friend]: Message 2108133533 from ********** "状态"
04-27 01:45:21 [DEBUG] nonebot | Checking for matchers in priority 1...
04-27 01:45:21 [INFO] nonebot | CQHTTP ********** | [message.private.friend]: Message 683721076 from ********** "/状态"
04-27 01:45:21 [DEBUG] nonebot | Checking for matchers in priority 1...
04-27 01:45:21 [DEBUG] nonebot | Checking for matchers in priority 10...
04-27 01:45:21 [DEBUG] nonebot | Checking for matchers in priority 10...
04-27 01:45:27 [INFO] nonebot | CQHTTP ********** | [message.private.friend]: Message 917910572 from ********** "/echo test"
04-27 01:45:27 [DEBUG] nonebot | Checking for matchers in priority 1...
04-27 01:45:27 [INFO] nonebot | Event will be handled by <Matcher from nonebot.plugins.echo, type=message, priority=1, temp=False>
04-27 01:45:27 [DEBUG] nonebot | Running matcher <Matcher from nonebot.plugins.echo, type=message, priority=1, temp=False>
04-27 01:45:27 [DEBUG] nonebot | CQHTTP | Calling API send_msg
04-27 01:45:27 [INFO] nonebot | Matcher <Matcher from nonebot.plugins.echo, type=message, priority=1, temp=False> running complete
04-27 01:45:27 [DEBUG] nonebot | Stop event propagation
04-27 01:46:35 [INFO] nonebot | CQHTTP ********** | [message.private.friend]: Message -1346411114 from ********** "状态"
04-27 01:46:35 [DEBUG] nonebot | Checking for matchers in priority 1...
04-27 01:46:35 [DEBUG] nonebot | Checking for matchers in priority 10...

**Comment by yanyongyu** [comment]
你没有配置superuser，status插件只会对superuser响应

**Comment by CNflysky** [comment]
> 你没有配置superuser，status插件只会对superuser响应

啊这...那我先试试看，好了就关了这个issue

**Comment by CNflysky** [comment]
解决了，的确是这个superuser的问题。
