### ISSUE TITLE
希望打通企业微信机器人、飞书机器人的开发，将nonebot2打造成最全面的智能机器人

### ISSUE THREAD

**Issue by mrchenxxx** [nonebot/nonebot2#341]
希望打通企业微信机器人、飞书机器人的开发，将nonebot2打造成最全面的智能机器人

**Comment by yanyongyu** [comment]
我个人并没有那么多时间去维护这么多协议的开发，希望能有大佬来提供支持

欢迎在 https://v2.nonebot.dev/store.html 发布协议适配

**Comment by yanyongyu** [comment]
目前飞书适配器已经立项，以后就能用飞书了

**Comment by StarHeartHunt** [comment]
已于 #425 中添加飞书适配器支持

**Comment by d-w-x** [comment]
飞书插件适配体验：

今天尝试将商店的插件 nonebot_plugin_status 和 nonebot_plugin_picsearcher 适配飞书机器人，目前发现以下情况：

## 开发者经验：

原始插件导入的是 
```python
from nonebot.adapters.cqhttp import PokeNotifyEvent, PrivateMessageEvent
```

```python
from nonebot.adapters.cqhttp import Bot, MessageEvent, GroupMessageEvent, Message
```

前者是为了特殊使用到戳一戳，导入 cqhttp  的 PokeNotifyEvent 属于正常，对于 PrivateMessageEvent，和后一种插件的导入，两个插件都采用了 cqhttp 的类。

这个一方面是插件作者的习惯，但是是否：
1. 同时反应了当前文档上对于插件开发者的引导不足？文档上可能需要注明 “如果非开发特殊平台插件，请从 nonebot.adapters 而不是更详细的实现中导入相关类。
2. 具体到作者导入的包，私聊和群聊是大部分聊天软件中的常用两种场景。对于飞书中，群聊和私聊的区分，是在 EventMessage 的 chat_type 中，而cqhttp这边是 MessageEvent 下的 message_type: Literal["group"]，这里框架并没有抽象出一个统一的区分私聊和群聊的方法，是否是抽象度过高或者插件的文档（API）的引导不足？

## 飞书适配器本身还需要进一步完善

今天测试适配器的私聊一个小问题，不知道是笔误还是我配置错误。
在使用飞书时，发现有些关键想法还是没法实现：
1. 图片等富媒体资源返回的是飞书提供的key，而非进一步访问飞书的API取得资源的二进制文件；
2. 提供的 call_api 强制将 response 的返回值进行 json 序列化，无法[手动获取资源](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-resource/get)，*额外的关于框架，是否需要考虑提供一个额外的 call_api_with_media 或者更底层的直接返回 respose 处理一些富媒体或者其他情况？*；

## 平台本身适配度比较低

在将 cqhttp 插件 飞书化的时候，发现有太多的修改要做，插件作者依赖了太多基于 cqhttp 适配器本身的函数、数据结构，这是否反应出了平台的抽象程度不够，没有对关键的数据结构进行进一步适配导致了不同适配器的差异性？
现在框架本身只方便了适配器作者，而适配器本身没有做到可以互相无痕/小改动替代，没有完全屏蔽底层的查差异性，甚至可以说基本没有屏蔽差异性，这和“适配器”本身是相悖的。

现在开发新插件的时候还是需要同时看官方文档和插件作者的文档，将文档中
>nonebot.adapters.cqhttp 模块
>nonebot.adapters.ding 模块
>nonebot.adapters.mirai 模块
>nonebot.adapters.feishu 模块
这几个模块能完全抽象到 nonebot.adapters 文档中，插件开发者不需要看更细节的实现文档可能才更像是 适配器。

关于需要抽象的功能可能更需要插件作者的反馈，表达他们想要XXX功能，在 adapters  没有，而必须调用详细的方法时，适配器可能就需要考虑是否将改功能抽象化。例：

>当前飞书无法获取图像内容，而 cqhttp 中可以提供图片的 url，那么适配器是否需要一个方法，获取消息中富文本消息，甚至抽象出一些更详细的“文本Segment”，“图片Segment”等其他机器人中都可能有的方法，而不是到 Segment 剩下的交由 `具体方法参考协议消息段类型或源码。` 点到位置？
>当前飞书无法获取到消息id，不知道 cqhttp 的情况，适配器是否需要一个方法获取id，以实现一些基于上下文的功能？

框架本身是方便插件开发者的，现在的nonebot2我用起来，至少飞书和 cqhttp 更像是两个完全不相同项目的杂合，可能是飞书适配器暂时不够完整，但我认为平台可能需要对插件实现的“最小功能”做出一些约束。

**Comment by yanyongyu** [comment]
> 插件作者依赖了太多基于 cqhttp 适配器本身的函数、数据结构，这是否反应出了平台的抽象程度不够

很遗憾，一个能够适配所有平台的插件接口是很难实现的，每个平台都拥有不同类型的消息，甚至有的平台只能纯文本，`onebot v12` 已经尽力在做平台统一了，不过类似飞书这类webhook的平台难以做到接口统一化

**Comment by yanyongyu** [comment]
> cqhttp这边是 MessageEvent 下的 message_type: Literal["group"]，这里框架并没有抽象出一个统一的区分私聊和群聊的方法

你是不会用isinstance吗？

```python
isinstance(event, GroupMessageEvent)
isinstance(event, PrivateMessageEvent)
```

**Comment by yanyongyu** [comment]
> 当前飞书无法获取到消息id，不知道 cqhttp 的情况，适配器是否需要一个方法获取id，以实现一些基于上下文的功能

能不能获取到id是飞书说了算啊，隔壁钉钉连用户信息都不给你呢，上下文功能cqhttp就有啊，飞书不是我写的我不清楚情况，你可以自行查看飞书是否支持`get_session_id()`进行上下文对话

还有啊，上下文对话是完全可以自定义的，你去看看update permission方法自行定义上下文，插件市场里就有人实现了，跨群、多用户的上下文插件

**Comment by d-w-x** [comment]
抱歉
