### ISSUE TITLE
Bug: 在旧版onebot协议中，access_token使用Token而非Bearer

### ISSUE THREAD

**Issue by Lancercmd** [nonebot/nonebot2#35]
**描述问题：**

nonebot2 和 go-cqhttp v0.9.29 设置一致的 access_token 时， nonebot2 返回 401

**如何复现？**

1. 在 nonebot2 的 .env.* 内设置 access_token = "xxxx" （总之是非空的 token ）
2. 在 go-cqhttp v0.9.29 的 config.json 设置和上面相同的 access_token
3. 启动 nonebot2，等待来自 go-cqhttp 的连接
4. 启动 go-cqhttp，尝试连接 nonebot2

**期望的结果**

连接成功

**环境信息：**

 - OS: Windows 10 May 2004
 - Python Version: 3.8.6
 - Nonebot Version: nonebot2-dev-4f6f991

**Comment by yanyongyu** [comment]
修改cqhttp的协议适配以兼容旧版协议鉴权
