### ISSUE TITLE
Feature: 为Adapter提供更高级的封装

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#351]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

对于CQHTTP Adapter的初学者来说，最常见的问题莫过于发送图片等文件
另外onebot协议提供的不同发送方式也不是一个方式能通吃所有情景
例如在传输小图片场景下，base64很合适
大文件情况，file很合适，但是如果是容器化部署等方案时无法使用
所以我希望能对这类API提供更高层的封装

**描述你所需要的特性：**

我用代码描述如下

```python
...

from nonebot.adatper.cqhttp.helpers import ImageHelper

foo = on_command(...)

@foo.handle()
async def _(bot:Bot.event:Event):
    with open(...) as f:
        image = ImageHelper(f) #也可以传path对象，BytesIO等
    print(image) # [CQ:image,url=...] 小文件自动采用base64，大文件用http

```
语音等同理

**Comment by yanyongyu** [comment]
暂时先为cqhttp的`MessageSegment`添加一些通过类型进行重载的方法

**Comment by yanyongyu** [comment]
improved support in https://github.com/nonebot/nonebot2/commit/4b38afdcd7f98e350f3958690b0b06a51b8b3f57
