### ISSUE TITLE
Feature: 重构adapter/driver的API逻辑

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#352]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

相关issue: #240 
我个人认为，想要试图为NoneBot优雅地提供正向ws或者轮询支持
总而言之就是由nonebot作为客户端的情形，那么我们很可能需要对adapter或者driver的api做出重大更改
比如说彻底解耦driver和adapter的关系，让driver事件和adapter事件不再绑定
但是这样势必会带来阻力，毕竟nonebot2已经是趋于稳定的项目
或者可以考虑给Adapter类加Mixin这样的？

**Comment by Jigsaw111** [comment]
更大的问题是有些协议压根不需要用 websocket 来进行连接（如钉钉， telegram），或者说 websocket 只是该协议的一个选择（如 onebot），这个时候与 websocket 耦合过深的 driver 和 adapter 就很容易给新 adapter 的编写产生阻碍。开发者不得不打破框架原定的逻辑来编程，这对于 nonebot 的兼容性是十分不利的。

**Comment by synodriver** [comment]
什么时候做呢（：

**Comment by yanyongyu** [comment]
> 什么时候做呢（：

dev分支已经实装，正向driver还需要完善，正向目前以aiohttp作为实验性driver

**Comment by synodriver** [comment]
> > 什么时候做呢（：
> 
> dev分支已经实装，正向driver还需要完善，正向目前以aiohttp作为实验性driver

aiohttp好耶

**Comment by yanyongyu** [comment]
released in `2.0.0a14`
