### ISSUE TITLE
Chore: [RFC] cqhttp适配器更名为onebot适配器

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/nonebot2#353]
* 新增 gocq 适配器之后，经常有新用户把 cqhttp 适配器与 gocq 适配器混淆。
* gocq 与 cqhttp 在名称上过于接近，易造成误解。
* 酷q http标准已更名为 onebot 标准，文档也使用 onebot 标准来称呼 cqhttp 适配器的实现。

基于以上三点理由，请求将cqhttp适配器更名为onebot适配器。

**Comment by yanyongyu** [comment]
pypi不允许更名，只能新建项目。暂时还是不考虑了
