### ISSUE TITLE
go-cqhttp连接不上

### ISSUE THREAD

**Issue by Alkitor** [nonebot/nonebot2#354]
**描述问题：**

使用nonebot2搭建起来，然后使用go-cqhttp去连接一直报错403。
但是使用aiocqhttp搭建就不会出现问题。
不知道是我哪里配置出现了问题，自己没有头绪。

**如何复现？**

按照文档里的步骤搭建的最小实例，但没有加载插件。

**期望的结果**

**环境信息：**

 - OS: Windows 10 20h2
 - Python Version: 3.9.5
 - Nonebot Version: 最近安装

**截图**

![image](https://user-images.githubusercontent.com/30173062/117566632-4ddb8500-b0ea-11eb-9bee-e849f1233466.png)

**Comment by mnixry** [comment]
这个问题应该是你的反向ws地址没有配置对, 看起来应该是 `/gocq/ws`

**Comment by Alkitor** [comment]
> 这个问题应该是你的反向ws地址没有配置对, 看起来应该是 `/gocq/ws`

成功了，感谢！

**Comment by Jigsaw111** [comment]
看来又是我的锅（
