### ISSUE TITLE
Let's make a English Documentation of the project

### ISSUE THREAD

**Issue by vybhav72954** [nonebot/nonebot2#365]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

Without concise English documentation, I believe most global collaborators would be discouraged.

**描述你所需要的特性：**

Translate the whole documentation, make sure that it follows proper grammar, free of Jargons, and aligns properly with the project.

**Comment by vybhav72954** [comment]
@StarHeartHunt So can I start working on this, or shall i wait for you to assign this to me?

Moreover, I am proposing a `README.en.md` file. It can preferably reside in a Translate directory in the root, or i can place the markdown in the root itself. What do you propose?

**Comment by richardchien** [comment]
Are you using NoneBot v2 or just giving suggestion? This project is mainly targeting Chinese users, we now only support  instant messaging softwares that're used in China. Meanwhile it's not stable now, which means the APIs change frequently, so maintaining an English version of documentation may incur huge costs. May be we will consider add English documentation after the first stable version released.

**Comment by vybhav72954** [comment]
> Are you using NoneBot v2 or just giving suggestion? This project is mainly targeting Chinese users, we now only support instant messaging softwares that're used in China. Meanwhile it's not stable now, which means the APIs change frequently, so maintaining an English version of documentation may incur huge costs. May be we will consider add English documentation after the first stable version released.

Oh, that makes so much sense. I was not aware of it a single bit. Please take this as a suggestion only. Considering the project is still in the alpha stage. I agree that maintaining documentation in a second language would be a hassle. Considering i am not Chinese I assume I cant build the project as well in my machine.

Thanks for the info. Please feel free to close the issue for now in that case.

**Comment by richardchien** [comment]
OK, I'm closing this. Thank you for the advice though.
