### ISSUE TITLE
Bug: Something went wrong这文档写的诗歌什么东西

### ISSUE THREAD

**Issue by Cosmos-Break** [nonebot/nonebot2#372]
**描述问题：**

**如何复现？**

**期望的结果**

**环境信息：**

 - OS: [e.g. Linux]
 - Python Version: [e.g. 3.8]
 - Nonebot Version: [e.g. 2.0.0]

**截图**

**Comment by yanyongyu** [comment]
由于你提交的issue未能描述任何问题，先close了

**Comment by j1g5awi** [comment]
如果您觉得我们的文档不足，就请指出不足在什么地方，而不是发个毫无意义的垃圾 issue
