### ISSUE TITLE
Mirai无法正常连接

### ISSUE THREAD

**Issue by Cosmos-Break** [nonebot/nonebot2#373]
**描述问题：**
运行 https://v2.nonebot.dev/next/guide/mirai-guide.html 的正向ws
```

auth_key=None host=IPv4Address('127.0.0.1') port=8080
Traceback (most recent call last):
  File "/root/wool_bot/qq/mirai_bot.py", line 5, in <module>
    nonebot.get_driver().register_adapter('mirai', Bot)
  File "/root/anaconda3/lib/python3.8/site-packages/nonebot/drivers/__init__.py", line 81, in register_adapter
    adapter.register(self, self.config, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/nonebot/adapters/mirai/bot.py", line 205, in register
    raise ApiNotAvailable('mirai')
nonebot.exception.ApiNotAvailable: mirai
```

**截图**
http模块已启用
![image](https://user-images.githubusercontent.com/26603288/119233767-1397cc00-bb5d-11eb-9c67-25bd1fb8a024.png)

**Comment by yanyongyu** [comment]
目测你没有正确配置nonebot2的mah adapter的api host和port

**Comment by Cosmos-Break** [comment]
是在.env里面配置？

**Comment by j1g5awi** [comment]
建议加群，issue 里问答效率太低。

**Comment by mnixry** [comment]
> 是在.env里面配置？

是的

```shell
MIRAI_AUTH_KEY=1234567890
MIRAI_HOST=127.0.0.1 # 当MAH运行在本机时
MIRAI_PORT=8080 # MAH的监听端口
```

经过测试, 按照文档中这样配置应该是没有问题的
不过值得注意的是如果你修改过MAH的监听端口, 应该在`.env`文件中作出相应更改

**Comment by j1g5awi** [comment]
> > 是在.env里面配置？
> 
> 是的
> 
> ```shell
> MIRAI_AUTH_KEY=1234567890
> MIRAI_HOST=127.0.0.1 # 当MAH运行在本机时
> MIRAI_PORT=8080 # MAH的监听端口
> ```
> 
> 经过测试, 按照文档中这样配置应该是没有问题的
> 不过值得注意的是如果你修改过MAH的监听端口, 应该在`.env`文件中作出相应更改
> 
> 另外, 请确认加载的是使用正向WS的Adapter而不是使用POST上报的Adapter
> 
> ```python
> ...
> from nonebot.adapters.mirai import WebsocketBot
> 
> ...
> nonebot.get_driver().register_adapter('mirai-ws', WebsocketBot, qq=12345678)
> ...
> ```
Q&A 又增加了

**Comment by yanyongyu** [comment]
closed due to solved in qq group
