### ISSUE TITLE
Bug: apascheduler plugin timezone settging don't work.

### ISSUE THREAD

**Issue by Cosmos-Break** [nonebot/nonebot2#379]
**描述问题：**

在env中设置
APSCHEDULER_AUTOSTART=true
APSCHEDULER_CONFIG={"apscheduler.timezone": "Asia/Shanghai"}

**如何复现？**

**期望的结果**

**环境信息：**

 - OS: [e.g. Linux]
 - Python Version: [e.g. 3.8]
 - Nonebot Version: [e.g. 2.0.0]

**截图**

![image](https://user-images.githubusercontent.com/26603288/119299390-683c6380-bc91-11eb-8e72-e5da3da709f6.png)
本机时间
![image](https://user-images.githubusercontent.com/26603288/119299445-7e4a2400-bc91-11eb-9f03-8c179062de8d.png)

**Comment by yanyongyu** [comment]
请尝试查看 `/etc/localtime` 文件，或使用如下代码查看本机时区

```python
>>> from tzlocal import get_localzone
>>> tz = get_localzone()
>>> tz
```

**Comment by Cosmos-Break** [comment]
多谢 用下面这个命令解决啦
sudo timedatectl set-timezone Asia/Shanghai
