### ISSUE TITLE
Feature: 支持 adapter 自定义 Response

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/nonebot2#383]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

目前在开发例如开黑啦/飞书等平台的 adapter 过程中，平台存在自动重发机制，要求返回200状态码以标识 Webhook 推送接收成功，而目前 Driver 中 Response 被硬性规定为收到请求后返回204与空 body，导致多平台兼容性出现问题。

**描述你所需要的特性：**

支持 adapter 自定义 Response 的 body 与返回的 status code。

**Comment by yanyongyu** [comment]
resolved in pr #406
