### ISSUE TITLE
Plugin: 戳一戳rua头像 & rua一张图片

### ISSUE THREAD

**Issue by Zeta-qixi** [nonebot/nonebot2#384]
**插件名称：**

戳一戳rua头像 & rua一张图片

**插件功能：**

发送 rua 头像/图片 的 gif

**PyPI 项目名：**

nonebot-plugin-rua

**插件 import 包名：**

null

**插件项目仓库/主页链接：**

https://github.com/Zeta-qixi/nonebot2-plugins/tree/master/rua

**Comment by yanyongyu** [comment]
请修改你的import包名

**Comment by yanyongyu** [comment]
查看pypi并未能找到你的项目，请打包上传pypi后再发布插件
