### ISSUE TITLE
使用nbcli创建的插件无法载入 nonebot.load_builtin_plugins()

### ISSUE THREAD

**Issue by djkcyl** [nonebot/nonebot2#389]
在poetry里创建的插件不能载入nonebot.load_builtin_plugins()
![image](https://user-images.githubusercontent.com/59153990/119936235-6b01c600-bfbb-11eb-939e-b6a38296ea7b.png)

在系统里直接用python3.8 -m pip安装的nbcli用不了
![image](https://user-images.githubusercontent.com/59153990/119936303-87056780-bfbb-11eb-8101-ccca286e2158.png)

**Comment by yanyongyu** [comment]
图一：未安装`nonebot-adapter-cqhttp`，目前这个内置插件只支持cqhttp
图二：请先升级pip版本后使用

**Comment by djkcyl** [comment]
明白了，也就是mirai-ws不能用这个内置插件

更新pip后在系统环境内可以使用nbcli了

**Comment by yanyongyu** [comment]
先close了，有问题可以再开
