### ISSUE TITLE
现在的cqhttp配置文件跟文档里的不一样

### ISSUE THREAD

**Issue by djkcyl** [nonebot/nonebot2#393]
现在版本的cq配置文件跟以前不一样了，看文档没看明白要怎么连接起来

Labels里为什么没有question（

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/120067788-1ee47d80-c0b0-11eb-9182-a91db0b8502c.png)

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/120067988-fdd05c80-c0b0-11eb-97e2-11f1881962c9.png)

**Comment by yanyongyu** [comment]
文档已在dev分支修改过了，等gocq 1.0 stable之后再作改动

**Comment by yanyongyu** [comment]
至于你的配置文件，应该配置ws reverse `/cqhttp/ws` 或者http post `/cqhttp/`

**Comment by djkcyl** [comment]
好了，用反向ws弄好了，
（建议加一个question的模板，要不然只能选bug

**Comment by yanyongyu** [comment]
> 好了，用反向ws弄好了，
> （建议加一个question的模板，要不然只能选bug

question 模板也加了但在dev分支还没生效（（
