### ISSUE TITLE
Bug: 通知事件响应器总是会执行两次

### ISSUE THREAD

**Issue by RtekiX** [nonebot/nonebot2#399]
**描述问题：**

我写了两个插件，其中一个插件注册了一个on_keywords事件响应器，优先级为2，另一个插件注册了一个on_notice事件响应器，优先级为1
每当触发on_notice事件响应器时，处理器总会执行两次

**如何复现？**
![image](https://user-images.githubusercontent.com/40229223/120808137-55703b80-c57b-11eb-8ab3-3445369743e0.png)
![image](https://user-images.githubusercontent.com/40229223/120808274-7df83580-c57b-11eb-8c9a-dcf7f35e3d7f.png)

**期望的结果**

nonebot的日志本应该是
/*收到消息*/
06-04 21:00:34 [DEBUG] nonebot | Checking for matchers in priority 1...
06-04 21:00:34 [INFO] nonebot | Event will be handled by <Matcher from notify, type=notice, priority=1, temp=False>
06-04 21:00:34 [DEBUG] nonebot | CQHTTP | Calling API send_msg
06-04 21:00:35 [INFO] nonebot | Matcher <Matcher from notify, type=notice, priority=1, temp=False> running complete

本应是处理一次就结束，但实际日志是
/*收到通知信息*/
06-04 21:00:34 [DEBUG] nonebot | Checking for matchers in priority 1...
06-04 21:00:34 [INFO] nonebot | Event will be handled by <Matcher from notify, type=notice, priority=1, temp=False>
06-04 21:00:34 [DEBUG] nonebot | Running matcher <Matcher from notify, type=notice, priority=1, temp=False>
06-04 21:00:34 [DEBUG] nonebot | CQHTTP | Calling API send_msg
06-04 21:00:34 [INFO] nonebot | Event will be handled by <Matcher from notify, type=notice, priority=1, temp=False>
06-04 21:00:34 [DEBUG] nonebot | Running matcher <Matcher from notify, type=notice, priority=1, temp=False>
06-04 21:00:34 [DEBUG] nonebot | CQHTTP | Calling API send_msg
06-04 21:00:35 [INFO] nonebot | Matcher <Matcher from notify, type=notice, priority=1, temp=False> running complete
06-04 21:00:35 [INFO] nonebot | Matcher <Matcher from notify, type=notice, priority=1, temp=False> running complete

**环境信息：**

 - OS: Windows10
 - Python Version: 3.7.6
 - Nonebot Version: 2.0.0a13

**Comment by yanyongyu** [comment]
请检查你是否有插件间互相import

**Comment by RtekiX** [comment]
> 请检查你是否有插件间互相import

![image](https://user-images.githubusercontent.com/40229223/120811086-32935680-c57e-11eb-9dd4-711ee712e1e7.png)
![image](https://user-images.githubusercontent.com/40229223/120811141-3f17af00-c57e-11eb-9b22-2674a5bee3d5.png)

两个插件都用到了自己本目录下的data_source.py，但import是区分了路径的
应该没有相互import的情况

**Comment by yanyongyu** [comment]
![image](https://user-images.githubusercontent.com/42488585/120811472-94ec5700-c57e-11eb-9673-388e87e70643.png)
这个会导致插件加载两遍，请使用相对路径

**Comment by RtekiX** [comment]
> ![image](https://user-images.githubusercontent.com/42488585/120811472-94ec5700-c57e-11eb-9673-388e87e70643.png)
> 这个会导致插件加载两遍，请使用相对路径

谢谢，那应该不是bug，是我对python还不太熟悉
已解决

**Comment by yanyongyu** [comment]
不是python的问题，是nonebot这边的插件加载机制并不允许使用绝对路径直接去import插件，文档内有说明，参看https://v2.nonebot.dev/advanced/export-and-require.html
