### ISSUE TITLE
Bug:Mirai 邀请入群和入群操作报错

### ISSUE THREAD

**Issue by nainiu233** [nonebot/nonebot2#400]
**描述问题：**

Mirai 邀请机器人入群报错

**如何复现？**

1. 邀请机器人入群
2. approve(bot)

**期望的结果**

**环境信息：**

 - OS: [windows]
 - Python Version: [3.8.8]
 - Nonebot Version: [2.0.0a13.post1]

**截图**

![image](https://user-images.githubusercontent.com/36364025/120922223-714e1b80-c6fa-11eb-9aa9-f4948fa73d1d.png)

**Comment by mnixry** [comment]
related: #271 #273 似乎和这个类似

~~忘修了~~

**Comment by nainiu233** [comment]
更改前与 #271 #273 代码无差别 尝试回滚更改报错一样

**Comment by mnixry** [comment]
> 更改前与 #271 #273 代码无差别 尝试回滚更改报错一样

试试类似于 #407 的修改

**Comment by nainiu233** [comment]
求改后解决
