### ISSUE TITLE
Bug: 插件目录下存在文件与插件同名时加载失败

### ISSUE THREAD

**Issue by Jerry-FaGe** [nonebot/nonebot2#401]
**描述问题：**

从a12更新到a13p1后插件加载出现`RecursionError: maximum recursion depth exceeded while calling a Python object`，并且回退至a12问题依然存在

**如何复现？**

1. `pip3.8 install nonebot2 --upgrade`
2. 重启bot
3. 加载到最后一个插件目录时控制台开始刷屏（见截图）

我在bot.py文件中加载了两个插件目录，这在之前的版本中是可用的，更新a13p1后前面加载的插件都可以正常使用。但最后一个加载的插件目录下的所有插件都会刷屏这个错误

```python
nonebot.init(_env_file=".env.prod")

driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)
app = nonebot.get_asgi()

config = driver.config

nonebot.load_builtin_plugins()
nonebot.load_plugin('nonebot_plugin_apscheduler')
nonebot.load_plugin('haruka_bot')
nonebot.load_plugins("src/plugins")
nonebot.load_plugins("src/Genshin_Impact_bot")
```

**期望的结果**

正常运行

**环境信息：**

 - OS: Ubuntu 18.04
 - Python Version: 3.8.6
 - Nonebot Version: 2.0.0a13.post1

**截图**

![image](https://user-images.githubusercontent.com/40235071/121317297-c0838e80-c93c-11eb-86ed-da4d8ec5af1b.png)

**Comment by yanyongyu** [comment]
修改你那个almanac插件目录下的almanac.py文件名，换一个文件名就好了

**Comment by Jerry-FaGe** [comment]
> 修改你那个almanac插件目录下的almanac.py文件名，换一个文件名就好了
> 
> 这个问题等我有空了修

原来是这样！刚开始没往那方面想，亲测改名可以解决，谢谢啦！
（我还有一点疑问，就是为什么这个问题在a12上没有，升到a13p1出现，而降回a12不会消失呢）

**Comment by yanyongyu** [comment]
@Jerry-FaGe 降版本也没消失不应该，可能是你降级的不彻底？

**Comment by Jerry-FaGe** [comment]
> @Jerry-FaGe 降版本也没消失不应该，可能是你降级的不彻底？

可能吧，总之谢谢啦！等待修复后close

**Comment by mnixry** [comment]
> > 修改你那个almanac插件目录下的almanac.py文件名，换一个文件名就好了
> 
> > 
> 
> > 这个问题等我有空了修
> 
> 
> 
> 原来是这样！刚开始没往那方面想，亲测改名可以解决，谢谢啦！
> 
> （我还有一点疑问，就是为什么这个问题在a12上没有，升到a13p1出现，而降回a12不会消失呢）

a12被yank了，根本不存在，只有a11和a13

**Comment by mnixry** [comment]
> > 修改你那个almanac插件目录下的almanac.py文件名，换一个文件名就好了
> 
> > 
> 
> > 这个问题等我有空了修
> 
> 
> 
> 原来是这样！刚开始没往那方面想，亲测改名可以解决，谢谢啦！
> 
> （我还有一点疑问，就是为什么这个问题在a12上没有，升到a13p1出现，而降回a12不会消失呢）

a12被yank了，根本不存在，只有a11和a13

**Comment by Jerry-FaGe** [comment]
@mnixry 听说了，不过确实可以下到，也怪我没先去看看Releases XD
![image](https://user-images.githubusercontent.com/40235071/121331885-e2cfd900-c949-11eb-945f-0c5a3431e4a8.png)

**Comment by yanyongyu** [comment]
fixed in latest dev branch
