### ISSUE TITLE
Feature: 动态添加消息处理函数

### ISSUE THREAD

**Issue by felinae98** [nonebot/nonebot2#413]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

在某些复杂逻辑和场景的，例如got到一个参数之后需要根据这个参数增加或删除一些后续的交互流程，例如got一些新的参数，执行不同类型的交互。

**描述你所需要的特性：**

在matcher实例运行的过程当中提供在matcher中动态增加handler的方法

**Comment by felinae98** [comment]
btw，文档中的“进阶-深入”部分写得很好

**Comment by yanyongyu** [comment]
你这个需求有三种解决方法：

1. 在state内存储当前交互状态，后续handler根据state判断是否执行（got可以通过预先向`state[key]`赋任意值跳过）
2. 为每个场景另写一个Matcher，复制源Matcher的信息（args_parser, permission）等，使用`matcher = Matcher(); asyncio.create_task(matcher.run(bot, event, state))` 直接执行该场景handler
3. 动态向实例添加handler：
   ```python
   @matcher.handle()
   async def handler(bot: Bot, matcher: Matcher):  # 此处添加matcher参数，其余不变
       matcher.handlers.append(xxx_handler)
       matcher.handlers.extend([xxx, yyy])
   ```

**Comment by yanyongyu** [comment]
如果没有什么问题的话先close了

**Comment by felinae98** [comment]
所以b2了这三个方法都还管用吗

**Comment by yanyongyu** [comment]
> 所以b2了这三个方法都还管用吗

大体上还是不变，但可以参考 https://v2.nonebot.dev/docs/next/tutorial/plugin/matcher-operation#skip 提供了跳过当前函数的办法

**Comment by felinae98** [comment]
请教一下`asyncio.create_task(matcher.run(bot, event, state))`和`await matcher.run(bot, event, state)`的区别

**Comment by yanyongyu** [comment]
> 请教一下`asyncio.create_task(matcher.run(bot, event, state))`和`await matcher.run(bot, event, state)`的区别

create_task是将coroutine安排进入loop但并不会等待他执行，await是会等待执行完毕

**Comment by felinae98** [comment]
所以在这个地方的具体区别是啥呢，这里注意到如果使用create_task的方式，使用nonebug抛出的assertion error不会出现在pytest中，无论后续matcher产生了什么样的错误都不会被pytest发现

**Comment by yanyongyu** [comment]
create_task就相当于触发了另一个事件响应，与当前事件无关，这个确实超出了nonebug对当前matcher测试的范围

**Comment by yanyongyu** [comment]
> 使用await的话可以成功捕捉到assertion error，请问使用await的话会产生其他的问题吗

nonebug 可能依然无法捕获到后续matcher的got receive等请求

**Comment by felinae98** [comment]
（所以未来nonebug会支持相关测试吗

**Comment by yanyongyu** [comment]
设置matcher的temp或者expire参数

https://v2.nonebot.dev/docs/tutorial/plugin/create-matcher#%E6%9C%89%E6%95%88%E6%9C%9F-tempexpire_time

**Comment by felinae98** [comment]
解决了，但是设置temp并不行，nonebot在此处移除临时handler
https://github.com/nonebot/nonebot2/blob/56c6f6a4717a76e55dc3808a834d783d2f4cb191/nonebot/message.py#L147
但是matcher.run的时候并不会运行这部分代码，所以不会移除临时handler。
将expire设为现在可以解决这个问题
