### ISSUE TITLE
Bug: 重启电脑后无法连接mirai

### ISSUE THREAD

**Issue by nainiu233** [nonebot/nonebot2#417]
**描述问题：**

已经是第二次发生了 重启电脑后无法无法连接

**如何复现？**

玄学问题

**期望的结果**

**环境信息：**

 - OS: [windows 10 ]
 - Python Version: [3.8.8]
 - Nonebot Version: [ 2.0.0a13.post1]

**截图**

![QQ截图20210621131538](https://user-images.githubusercontent.com/36364025/122710426-cbbab080-d292-11eb-888e-c57091d0d8de.png)

**Comment by yanyongyu** [comment]
你mah启动了吗？

**Comment by nainiu233** [comment]
> 你mah启动了吗？

启动了

**Comment by nainiu233** [comment]
mah 没有正常启动 https://github.com/project-mirai/mirai-api-http/issues/373
