### ISSUE TITLE
Bug: 文档和源码找不到API的相关描述

### ISSUE THREAD

**Issue by RiotGamesU** [nonebot/nonebot2#418]
**描述问题：**
Rule: to_me的触发条件是什么呢,我在文档的API页面没有找到,翻源码也没找到

**如何复现？**
一.文档截图:
1.to_me()
![image](https://user-images.githubusercontent.com/67886642/122743695-cc1a7200-d2b9-11eb-9da9-5914b9b37626.png)
2.is_tome()
![image](https://user-images.githubusercontent.com/67886642/122743769-e2c0c900-d2b9-11eb-945d-b7f49eb94a98.png)
二.源码截图
1.to_me()
![image](https://user-images.githubusercontent.com/67886642/122743820-f2d8a880-d2b9-11eb-8be4-a1c70a4e7aee.png)
2.is_tome()
![image](https://user-images.githubusercontent.com/67886642/122743856-ff5d0100-d2b9-11eb-8e5d-c85b060303c6.png)

**期望的结果**
请教如何使用这个API文档或源码,抑或是文档或源码注释亦需完善

**环境信息：**

 - OS: win10 latest
 - Python Version: Python 3.9.5
 - Nonebot Version: latest

**截图**
上面"如何复现?"处

**Comment by mnixry** [comment]
这个是根据不同Adapter实现而不同的
可以参照adapter相关源码

不过这个的确是需要补充的地方

**Comment by RiotGamesU** [comment]
> 这个是根据不同Adapter实现而不同的
> 可以参照adapter相关源码
> 
> 不过这个的确是需要补充的地方

我用的nonebot2的adapter是cqhttp,和它连接的另一端(不太懂怎么称呼)用的go-cqhttp,看了好久API文档感觉看不太懂...请问是我有哪些地方没学所以不懂吗,还是文档没写全

**Comment by RiotGamesU** [comment]
> 这个是根据不同Adapter实现而不同的
> 可以参照adapter相关源码
> 
> 不过这个的确是需要补充的地方

只学过一些Python基础和异步方面的基础知识

**Comment by mnixry** [comment]
> 我用的nonebot2的adapter是cqhttp,和它连接的另一端(不太懂怎么称呼)用的go-cqhttp,看了好久API文档感觉看不太懂...请问是我有哪些地方没学所以不懂吗,还是文档没写全

cqhttp的话在[这个文件](https://github.com/nonebot/nonebot2/blob/master/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py)里面

大概就是以下几种情况
- 被@
- 被回复
- 私聊消息
- 被称呼NICKNANE中配置的昵称

**Comment by RiotGamesU** [comment]
> > 我用的nonebot2的adapter是cqhttp,和它连接的另一端(不太懂怎么称呼)用的go-cqhttp,看了好久API文档感觉看不太懂...请问是我有哪些地方没学所以不懂吗,还是文档没写全
> 
> cqhttp的话在[这个文件](https://github.com/nonebot/nonebot2/blob/master/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py)里面
> 
> 大概就是以下几种情况
> 
> * 被@
> * 被回复
> * 私聊消息
> * 被称呼NICKNANE中配置的昵称

好的,谢谢,请问OneBot协议里的API,nonebot2的cqhttp是否都实现了呢,https://github.com/botuniverse/onebot/blob/master/v11/specs/api/public.md#get_group_list-%E8%8E%B7%E5%8F%96%E7%BE%A4%E5%88%97%E8%A1%A8
这个API我在前面所说的环境下该如何调用呢,希望您不吝赐教

**Comment by mnixry** [comment]
> 这个API我在前面所说的环境下该如何调用呢,希望您不吝赐教

在事件处理函数中传入的bot对象直接调用即可
比如`bot.delete_msg(message_id=123456)`这样~~我随便写的，意思对了就好~~

P.S 还有什么问题的话加[QQ群](https://jq.qq.com/?_wv=1027&k=zGzEJSVE)应该回复会快一点

**Comment by RiotGamesU** [comment]
> > 这个API我在前面所说的环境下该如何调用呢,希望您不吝赐教
> 
> 在事件处理函数中传入的bot对象直接调用即可
> 比如`bot.delete_msg(message_id=123456)`这样~我随便写的，意思对了就好~
> 
> P.S 还有什么问题的话加[QQ群](https://jq.qq.com/?_wv=1027&k=zGzEJSVE)应该回复会快一点

好的,谢谢

**Comment by yanyongyu** [comment]
如果还有问题的话欢迎reopen
