### ISSUE TITLE
Bug: OneBot协议v11版本的图片消息提供了通过代理访问图片的功能,但是在nonebot2未找到相关的代理设置

### ISSUE THREAD

**Issue by RiotGamesU** [nonebot/nonebot2#420]
**描述问题：**
OneBot协议v11版本的图片消息提供了通过代理访问图片的功能,但是在nonebot2未找到相关的代理设置

**如何复现？**
![}IC13_B0WSV4_2(@90MK3UL](https://user-images.githubusercontent.com/67886642/123535317-9f50d980-d755-11eb-9569-9da396cb8362.png)

![JX1G}3)HN`H_E(@1P OMY7T](https://user-images.githubusercontent.com/67886642/123535326-ad065f00-d755-11eb-85c8-53df40b2cf30.png)

![BV6 V{Y%)MSC5WM}%} R64C](https://user-images.githubusercontent.com/67886642/123535329-b099e600-d755-11eb-9bfb-2183a18849f4.png)

**期望的结果**
![}IC13_B0WSV4_2(@90MK3UL](https://user-images.githubusercontent.com/67886642/123535332-b5f73080-d755-11eb-90f2-a06776549639.png)

**环境信息：**

 - OS: win10 latest
 - Python Version: Python 3.9.5
 - Nonebot Version: latest

**Comment by RiotGamesU** [comment]
经过群友提醒,是go-cqhttp的代理设置,so sry

**Comment by yanyongyu** [comment]
https://github.com/nonebot/nonebot2/blob/1db462e4ad245b57669ea03781a030c0d7873053/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/message.py#L81-L94

**Comment by RiotGamesU** [comment]
> https://github.com/nonebot/nonebot2/blob/1db462e4ad245b57669ea03781a030c0d7873053/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/message.py#L81-L94

请问如何设置图片请求的headers?我请求pixiv的图片需要设置Referer

**Comment by RiotGamesU** [comment]
> https://github.com/nonebot/nonebot2/blob/1db462e4ad245b57669ea03781a030c0d7873053/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/message.py#L81-L94

请问这个咋用啊...小白表示不懂啊

**Comment by yanyongyu** [comment]
> 请问如何设置图片请求的headers?我请求pixiv的图片需要设置Referer

这个问题你得去问gocq支不支持

> 请问这个咋用啊...小白表示不懂啊

```python
from nonebot.adapters.cqhttp import MessageSegment

await matcher.send(MessageSegment.image("file:///xxxxxx", cache=True, proxy=True))
```

**Comment by RiotGamesU** [comment]
> > 请问如何设置图片请求的headers?我请求pixiv的图片需要设置Referer
> 
> 这个问题你得去问gocq支不支持
> 
> > 请问这个咋用啊...小白表示不懂啊
> 
> ```python
> from nonebot.adapters.cqhttp import MessageSegment
> 
> await matcher.send(MessageSegment.image("file:///xxxxxx", cache=True, proxy=True))
> ```

好的谢谢
