### ISSUE TITLE
Question: 在插件中使用内置的FastAPI定义接口，外部调用该接口时返回connect ECONNREFUSED

### ISSUE THREAD

**Issue by retroxz** [nonebot/nonebot2#422]
**描述问题：**

在nonebot2的一个插件中，使用内置的FastApi驱动定义一个接口，然后外部调用该接口时connect ECONNREFUSED
未能返回任何结果

**如何复现？**

1. 自定义一个新的插件apis
2. 在插件中使用如下代码定义一个api
```python
@app.post('/api/message/send')
async def _(item: Item):
    if not item.key == global_config.api_key:
        return {'code': 1, 'message': 'key无效'}
    #获取bot实例
    try:
        bot = list(nonebot.get_bots().values())[0]
    except:
        return {'code': 1, 'message': 'Bot不在线'}
    params = {
        'message': Message(inspect.cleandoc(item.message)),
        'user_id' if item.message_type == 'private' else 'group_id': item.qid
    }
    await bot.call_api(F"send_{item.message_type}_msg", **params)
    return {'code': 0, 'message': '发送成功'}
```
4. 加载该插件 并进行外部请求

**期望的结果**

正常返回json

**环境信息：**

 - OS: Centos7
 - Python Version: 3.8
 - Nonebot Version: 2.0.0a13.post1

该插件在windows10环境加载后可以正常运行并返回json，且请求一个未定义的路由时会返回404错误，但该插件加载到linux环境时，请求任何路由地址均返回connect ECONNREFUSED
插件启动后在linux本地也无法请求接口

**Comment by mnixry** [comment]
即使路由没有绑定也不应该是Connection Refused， 而应该是404
所以请检查监听端口和监听地址是否正确
比如想要通过公网或者局域网进行访问，请修改监听地址为`0.0.0.0`

**Comment by yanyongyu** [comment]
该问题是你自身的问题，例如防火墙未放行端口，部署时误绑定host为127.0.0.1等

**Comment by retroxz** [comment]
解决了 host绑定错误
