### ISSUE TITLE
用cqhttp撤回Q群消息不成功

### ISSUE THREAD

**Issue by lunzima** [nonebot/nonebot2#423]
**描述问题：**
似乎已经正确执行了delete_msg，但是匹配关键字的群聊消息并没有撤回

**如何复现？**

> def chat_rule() -> Rule:
  async def _chat_rule(bot: "Bot", event: "Event", state: T_State) -> bool:
    return event.message_type != "private" and str(event.user_id) != str(bot.self_id)

  return Rule(_chat_rule)

withdraw_bot = on_message(rule=chat_rule(), permission=None, priority=1, block=False)

@withdraw_bot.handle()
async def handle_first_receive(bot: Bot, event: Event, state: T_State):
  session = str(event.user_id)
  args = str(event.get_message()).strip()
  if dfafilter.has_profanities(args):
      logger.info('Profanities censored!')
      bot.delete_msg(message_id=event.message_id)

尝试过推迟消息撤回的时间，也尝试过重试多次撤回消息，但是没有效果
在go-cqhttp那里提过issue https://github.com/Mrs4s/go-cqhttp/issues/945
但是maintainer建议在这里重新发

**环境信息：**

nonebot2版本: 2.0.0a13
go-cqhttp版本: 1.0.0-beta4
运行环境: Ubuntu 20.04
使用协议: via nonebot2-adapter-cqhttp
go-cqhttp适配器连接方式: ws-reverse

**Comment by lunzima** [comment]
异步函数没加await，锅了

**Comment by yanyongyu** [comment]
`await bot.delete_msg(xxx)`
