### ISSUE TITLE
Bug:  使用HTTP方式通信时出现TypeError: Object of type MessageSegment is not JSON serializable

### ISSUE THREAD

**Issue by zhanbao2000** [nonebot/nonebot2#426]
**描述问题：**

使用HTTP方式通信时可以正常接收由go-cqhttp发来的请求，但是nonebot2将请求发送至go-cqhttp时便会发生标题所述错误。经查发现是nonebot2将http请求传递到httpx模块时，该请求中仍然保留了MessageSegment类，导致json_dumps函数无法理解

备注：
1、使用反向ws方法不会触发此bug，一切正常
2、我使用了nonebot1作为对比，以下是httpx调用json_dumps之前的dict的内容

nonebot：
> {'message_type': 'private', 'user_id': 12345678, 'message': [{'type': 'text', 'data': {'text': '你好，世界'}}]}

nonebot2：
> {'user_id': 12345678, 'message_type': 'private', 'message': [MessageSegment(type='text', data={'text': '你好，世界'})]}

**如何复现？**

1、使用2.0.0a13.post1版本的nonebot2和v1.0.0-beta3版本的go-cqhttp
2、以http方式进行通信
3、加载内置插件
4、对机器人使用/echo指令（/echo 你好，世界）
5、nonebot2控制台出现报错（见日志），消息也无法发送，go-cqhttp控制台也看不到nonebot的请求

**环境信息：**

 - OS: Windows10
 - Python Version: 3.9
 - Nonebot Version: 2.0.0a13.post1
 - go-cqhttp Version: v1.0.0-beta3

**日志：**

[bug.log](https://github.com/nonebot/nonebot2/files/6759526/bug.log)

**Comment by yanyongyu** [comment]
你在调用api时请自行处理类型转换，cqhttp只对send做类型转换

**Comment by yanyongyu** [comment]
看了下cqhttp对post连接方式确实没有提供特制的jsonencoder

**Comment by yanyongyu** [comment]
fixed in latest dev
