### ISSUE TITLE
Bug: mirai adapter调用upload_image上传图片报错

### ISSUE THREAD

**Issue by yabaia** [nonebot/nonebot2#429]
**描述问题：**

mirai adapter调用upload_image上传图片报错：

```powershell
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: http://127.0.0.1:8000/uploadImage
For more information check: https://httpstatuses.com/400
```

**如何复现？**

```python
with open('file.png', 'rb') as f:
    img = BytesIO(f.read())
img_id = await bot.upload_image('group', img)
```

**期望的结果**

```
{'imageId': '{******-****-FD90-491D-141D77303EE5}.png', 'url': 'http://gchat.qpic.cn/gchatpic_new/*********', 'path': ''}
```

**环境信息：**

 - OS: Windows10
 - Python Version: 3.8.2
 - Nonebot Version: 2.0.0a13.post1
 - Mirai Version: 2.7-M1
 - mirai-api-http Version: 1.12.0

**截图**

![image-20210707135254327](https://user-images.githubusercontent.com/49870766/124708711-39223e80-df2d-11eb-9601-6626106317e9.png)

**原因**

mah v-1.8.4 的uploadImage api需要提供sessionKey。
经过测试，mah 版本1.12.0，在增加sessionKey后能返回预期结果，
是个新手，代码写的不好，就不提pr了。
> ### [图片文件上传](https://github.com/zxsean/mirai-api-http/blob/master/docs/API.md#%E5%9B%BE%E7%89%87%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)
>
> ```
> [POST] /uploadImage
> ```
>
> 使用此方法上传图片文件至服务器并返回ImageId
>
> #### 请求
>
> Content-Type：multipart/form-data
>
> | 名字       | 类型   | 可选  | 举例        | 说明                          |
> | ---------- | ------ | ----- | ----------- | ----------------------------- |
> | sessionKey | String | false | YourSession | 已经激活的Session             |
> | type       | String | false | "friend "   | "friend" 或 "group" 或 "temp" |
> | img        | File   | false | -           | 图片文件                      |

在mah v-2.0的http adapter中就不需要了

> ### [图片文件上传](https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md#%E5%9B%BE%E7%89%87%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)
>
> 使用此方法上传图片文件至服务器并返回ImageId
>
> ```
> [POST] /uploadImage
> ```
>
> **本接口为[POST]请求, 参数格式为`multipart/form-data`**
>
> #### 请求:
>
> | 名字       | 类型   | 可选  | 举例        | 说明                          |
> | ---------- | ------ | ----- | ----------- | ----------------------------- |
> | sessionKey | String | true  | YourSession | 已经激活的Session             |
> | type       | String | false | "friend"    | "friend" 或 "group" 或 "temp" |
> | img        | File   | false | -           | 图片文件                      |

**Comment by yanyongyu** [comment]
@mnixry

**Comment by yanyongyu** [comment]
fixed in pr #430
