### ISSUE TITLE
Feature: 会话超时钩子函数

### ISSUE THREAD

**Issue by Nattsu0514** [nonebot/nonebot2#433]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

related: https://github.com/nonebot/discussions/discussions/18

需要用户没有在session-expire-timeout设定的时间内进一步操作则运行函数并提醒。

**描述你所需要的特性：**

会话超时钩子函数。

**Comment by Nattsu0514** [comment]
之前论坛发了个差不多的，想了想这个功能应该还是挺常用的吧..

**Comment by yanyongyu** [comment]
> 之前论坛发了个差不多的，想了想这个功能应该还是挺常用的吧..

功能确实有用，但目前nonebot并没有主动超时事件，只有被动的循环检测，目前做不到提供钩子

**Comment by yanyongyu** [comment]
如果有更好的解决方案话欢迎提出，暂时close这个issue

**Comment by clacknya** [comment]
any update?
