### ISSUE TITLE
如何关闭文件检测watchdog

### ISSUE THREAD

**Issue by zhishixiang** [nonebot/nonebot2#436]
我写的插件全部数据都会保存在本地文件里面，但是每次保存文件时都会因为检测到文件改变而重启机器人，我没有看到指南里面有提到类似问题的解决方案，有什么办法能解决吗

**Comment by j1g5awi** [comment]
![image](https://user-images.githubusercontent.com/50312681/125718659-162b7c48-7d7f-42ea-9726-3c1722c573a3.png)
文档里写了，你可以自定义 watchdog 的监控文件夹。

**Comment by StarHeartHunt** [comment]
在生产环境使用`ENVIRONMENT=prod`

**Comment by yanyongyu** [comment]
可以通过配置来解决
