### ISSUE TITLE
Plugin: nonebot_plugin_setu

### ISSUE THREAD

**Issue by ayanamiblhx** [nonebot/nonebot2#437]
**插件名称：**

nonebot_plugin_setu

**插件功能：**

基于loliconImage Api的涩图插件，内置涩图CD

**PyPI 项目名：**

nonebot_plugin_setu

**插件 import 包名：**

nonebot_plugin_setu

**插件项目仓库/主页链接：**

https://github.com/ayanamiblhx/nonebot_plugin_setu

**Comment by StarHeartHunt** [comment]
在 pypi 上搜索之后没有找到对应的包，请确认一下是否 publish 到 pypi 上了。
pypi 上没有的话会导致无法通过 nb-cli 正常安装。
