### ISSUE TITLE
Plugin: nonebot_plugin_fr24

### ISSUE THREAD

**Issue by IronWolf-K** [nonebot/nonebot2#441]
**插件名称：**

FlightRadar24查询模块

**插件功能：**

通过FlightRadar24查询航班信息

**PyPI 项目名：**

nonebot-plugin-fr24

**插件 import 包名：**

nonebot_plugin_fr24

**插件项目仓库/主页链接：**

https://github.com/IronWolf-K/nonebot_plugin_fr24

**Comment by yanyongyu** [comment]
修改一下插件名称吧，这样怪怪的

**Comment by IronWolf-K** [comment]
是重新提交issue？
