### ISSUE TITLE
Question: 如何在钩子函数“运行预处理”中修改message内容

### ISSUE THREAD

**Issue by chanchancl** [nonebot/nonebot2#443]
主要是想使用一个函数对消息进行预处理，将繁体字转为简体字，方便matcher的匹配

例如

```python
@run_preprocessor
async def _(matcher: Matcher, bot: Bot, event: Event, state: T_State):
    event.message = convert(event.message, "zh-cn")
```

**Comment by mnixry** [comment]
你这种写法思路看起来是正确的, 只要实现好`convert`函数就应该没有问题

**Comment by j1g5awi** [comment]
`run_preprocessor`  装饰器是在事件分发之后执行，你想要在 Matcher 匹配前执行需要用 `event_preprocessor` 装饰器。

**Comment by yanyongyu** [comment]
直接赋值即可，注意类型应为`Message`

**Comment by chanchancl** [comment]
通过一些测试，如下的方法是可以完成需求的，但总感觉特别别扭，大佬有没有更好的实现方法。。
比如将 父类转换为子类。

```
@event_preprocessor
async def _(bot: Bot, event: Event, state: T_State):
    if not isinstance(event, MessageEvent):
        return
    event.__class__ = MessageEvent
    event.message = Message(convert(str(event.message), "zh-cn"))
```

**Comment by mnixry** [comment]
> 通过一些测试，如下的方法是可以完成需求的，但总感觉特别别扭，大佬有没有更好的实现方法。。
> 比如将 父类转换为子类。
> 

如果你的代码编辑器足够智能, 你应该是不需要这一行的

```diff
@event_preprocessor
async def _(bot: Bot, event: Event, state: T_State):
    if not isinstance(event, MessageEvent):
       return
-   event.__class__ = MessageEvent
    event.message = Message(convert(str(event.message), "zh-cn"))
```

另外, 直接将Message转换成字符串再转回, 可能会导致[CQ码注入漏洞](https://github.com/nonebot/nonebot2/issues/212#issuecomment-778007483)

我推荐您可以直接遍历`Message`对象(它继承于`list`), 并对所有`type=text`的文本进行翻译

```python
@event_preprocessor
async def _(bot: Bot, event: Event, state: T_State):
    if not isinstance(event, MessageEvent):
        return
    for segment in event.message:
        if not segment.is_text():
            continue
        segment.data['text'] = convert(segment.data['text'], 'zh-cn')
```

大概是这样

**Comment by chanchancl** [comment]
@mnixry 多谢大佬，
这个类型转换确实是不需要的，event本身就有 message 字段

另外我对convert稍微包装了一下，让其成为一个异步函数，应该可以避免阻塞事件循环。

再问几个问题

1. event.message 为何是一个数组，一个消息message 中可以有多个消息段，这些消息段是怎样划分的。

比如一个消息中，同时包含文本，图片等，是以这些消息的类型来划分的吗？

2. 通过打印类型，我知道event实际上是 nonebot.adapters.cqhttp.GroupMessageEvent， 如果将来我需要使用GroupMessageEvent中的字段，比如group_id，在这种情况下，该如何对event进行转换

最后再贴上最终的代码
```
async def AsyncTranslate(text, dst):
    return convert(text, dst)


@event_preprocessor
async def _(bot: Bot, event: Event, state: T_State):
    if not isinstance(event, MessageEvent):
        return

    for segment in event.message:
        if not segment.is_text():
            continue
        segment.data['text'] = await AsyncTranslate(str(event.message), "zh-cn")
```

**Comment by mnixry** [comment]
> event.message 为何是一个数组

这是NoneBot的设计,可以同时包括多种形式的消息,能够对富文本等进行良好的支持, 同时能够规避由字符串转义带来的注入问题

这种数组消息格式[同时也是OneBot标准所规范的](https://github.com/botuniverse/onebot/blob/master/v11/specs/message/array.md#%E6%B6%88%E6%81%AF%E6%AE%B5%E6%95%B0%E7%BB%84)

> 一个消息message 中可以有多个消息段，这些消息段是怎样划分的。
> 比如一个消息中，同时包含文本，图片等，是以这些消息的类型来划分的吗？

这个和OneBot协议的实现有关, 在大多数实现中, 它的确是按照消息类型和元素在消息中的位置决定的

> 通过打印类型，我知道event实际上是 nonebot.adapters.cqhttp.GroupMessageEvent， 如果将来我需要使用GroupMessageEvent中的字段，比如group_id，在这种情况下，该如何对event进行转换

一样的, 你只需要加上`isinstance(event,GroupMessageEvent)`判断就可以在代码段内使用`GroupMessageEvent`特有的字段了

顺带一提, 事件类型的转换是在`adapter`接收事件的时候就完成的:

<details>

<summary>相关代码</summary>

https://github.com/nonebot/nonebot2/blob/96d05cb5217fa2c542c46de85b5527d2201e9860/packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py#L295-L329

</details>

另外,在事件处理函数中, 我们还[支持通过类型标记事件处理函数进行重载来简化代码](https://dev--nonebot2.netlify.app/next/advanced/overloaded-handlers.html)

> 最后再贴上最终的代码
> 
> ```python
> async def AsyncTranslate(text, dst):
>     return convert(text, dst)
> ```

你这样并不能完成从同步到异步的转换, 如果想要实现这种转换, [请考虑使用`nonebot.utils.run_sync`](https://v2.nonebot.dev/api/utils.html#run-sync-func)

**Comment by chanchancl** [comment]
@mnixry 再次感谢

以前还真没发现 isinstance 有这种功能，试了一下，发现确实如果通过 not isinstance 判断之后，后面就可以使用相关的字段了。

剩下的我应该再去读读onebot的文档，我之前一直是用 websocket 裸连go-cqhttp，这和使用框架之间还是有一些区别

```
@event_preprocessor
async def _(bot: Bot, event: Event, state: T_State):
    if not isinstance(event, MessageEvent):
        return

    for segment in event.message:
        if not segment.is_text():
            continue
        segment.data['text'] = await run_sync(convert(str(event.message), "zh-cn"))
    
    if not isinstance(event, GroupMessageEvent):
        return
    log.logger.debug(f"test group {event.group_id}")
```

**Comment by mnixry** [comment]
> 以前还真没发现 isinstance 有这种功能，试了一下，发现确实如果通过 not isinstance 判断之后，后面就可以使用相关的字段了。

这个代码提示应该是编辑器提供的能力, ~~可能是以前你用的编辑器太菜了~~

---

感谢回复, 鉴于问题看起来已经解决, 我将关闭这个Issue, 如果您有任何相关的问题可以重新打开

如果有任何其他的问题, 您可以在[讨论版创建提问](https://github.com/nonebot/discussions/discussions/new)或者[加入我们的QQ群](https://jq.qq.com/?_wv=1027&k=5OFifDh), 我们将不吝解答

如果对NoneBot2有任何反馈或者建议, 可以[创建Issue](https://github.com/nonebot/nonebot2/issues/new/choose)以便于我们进行进一步的跟踪
