### ISSUE TITLE
Plugin: QQ闪照重现

### ISSUE THREAD

**Issue by LycanW** [nonebot/nonebot2#455]
**插件名称：**

QQ闪照重现

**插件功能：**

重新把闪照用图片方式发出

**PyPI 项目名：**

nonebot_plugin_flashre

**插件 import 包名：**

nonebot_plugin_flashre-1.0.tar.gz

**插件项目仓库/主页链接：**

https://github.com/LycanW/nonebot_plugin_flashre

**Comment by yanyongyu** [comment]
请在pypi发布后再来发布插件
