### ISSUE TITLE
Bug: Mirai-API-HTTP Bot被邀请入群 群成员申请入群处理异常

### ISSUE THREAD

**Issue by nainiu233** [nonebot/nonebot2#460]
**描述问题：**
在收到入群后使用await event.approve(bot) 报错
在收到群成员申请入群后使用await event.approve(bot) 报错
**如何复现？**
相关代码

Bot被邀请
```python
from nonebot import on_request
from nonebot.adapters import Bot, Event

invite_group = on_request(priority=5)


@invite_group.handle()
async def first_receive(bot: Bot, event: Event):
    if event.get_event_name() != 'BotInvitedJoinGroupRequestEvent':
        return
    request_session = eval(event.get_event_description())
    if request_session['from_id'] != <qqid>:
        await event.reject(bot, message='你没有权限邀请我入群!')
        return
    else:
        await event.approve(bot)
        return
```

**期望的结果**

同意邀请入群申请

**环境信息：**

 - OS: [windows10]
 - Python Version: [3.8]
 - Nonebot Version: [ 2.0.0a13.post1]

**截图**

![QQ截图20210803231338](https://user-images.githubusercontent.com/36364025/128040537-bac5cfad-c9a8-4b61-8774-bb0e21126a7d.png)
![QQ截图20210803232641](https://user-images.githubusercontent.com/36364025/128042596-be14f18a-3741-4c10-85ae-6c41918c8c55.png)
![QQ截图20210803232651](https://user-images.githubusercontent.com/36364025/128042639-9163c1d8-5107-44f1-8562-b3c3951e89c5.png)

备注 await event.reject是没问题的

**Comment by yanyongyu** [comment]
@mnixry

**Comment by mnixry** [comment]
Duplicate of #400 
已在dev分支修复

@yanyongyu 第二张截图似乎和 #459 有关系

**Comment by QuBenhao** [comment]
@mnixry 您好，请问bot在处理加群请求的时候报这个错是为什么呀
`    
       return await bot.api.post('/resp/memberJoinRequestEvent',
AttributeError: 'functools.partial' object has no attribute 'post'
`

**Comment by mnixry** [comment]
> 您好，请问bot在处理加群请求的时候报这个错是为什么呀

非常抱歉, 现在Mirai Adapter已经不再由NoneBot官方维护

如果您正在使用`2.0.0a16`以及之前的版本, 我恐怕将不会提供任何可行的支持 (因为我很久没用过mah了)

如果您正在使用为mah2和`beta`版本设计的mirai adapter, 请前往 <https://github.com/ieew/nonebot_adapter_mirai2> 仓库进行反馈

/cc @ieew

**Comment by QuBenhao** [comment]
> > 您好，请问bot在处理加群请求的时候报这个错是为什么呀
> 
> 非常抱歉, 现在Mirai Adapter已经不再由NoneBot官方维护
> 
> 如果您正在使用`2.0.0a16`以及之前的版本, 我恐怕将不会提供任何可行的支持 (因为我很久没用过mah了)
> 
> 如果您正在使用为mah2和`beta`版本设计的mirai adapter, 请前往 https://github.com/ieew/nonebot_adapter_mirai2 仓库进行反馈
> 
> /cc @ieew

@mnixry 感谢。我忘了说清楚，我是python 3.10 + nonebot 2.0.0a16 + mirai2。我去咨询一下
