### ISSUE TITLE
Bug: Mirai-API-HTTP 无法正常链接

### ISSUE THREAD

**Issue by nainiu233** [nonebot/nonebot2#463]
**描述问题：**

Mirai-API-HTTP 无法正常链接

**环境信息：**

 - OS: [windows10]
 - Python Version: [3.8]
 - Nonebot Version: [a.14]

**协议端信息：**

 - 协议端: [nonebot-adapter-mirai]
 - 协议端版本: [a14]

**截图或日志**

![QQ截图20210804144119](https://user-images.githubusercontent.com/36364025/128134026-0ea4c396-7433-447f-9a3d-bf0aedfe4413.png)

**Comment by yanyongyu** [comment]
请在注册adapter时使用 `mirai`
