### ISSUE TITLE
Bug: httpcore.ReadTimeout

### ISSUE THREAD

**Issue by lajxw** [nonebot/nonebot2#469]
**描述问题：**

使用新版后
发送消息报错
httpcore.ReadTimeout

**如何复现？**

await XXX.finish()

**环境信息：**

 - OS: [windows10]
 - Python Version: [3.8 3.9均测试过]
 - Nonebot Version: [a14]

**协议端信息：**

 - 协议端: [mirai]
 - 协议端版本: [a14]

**截图或日志**

![QQ截图20210805173402](https://user-images.githubusercontent.com/46254113/128328043-2a04396a-6bad-4c41-ac06-193ecc607250.png)

**Comment by yanyongyu** [comment]
@mnixry

**Comment by mnixry** [comment]
请将异常堆栈截全面一些，以便进行进一步分析和追踪问题

**Comment by lajxw** [comment]
![QQ截图20210805174542](https://user-images.githubusercontent.com/46254113/128329841-1bf42b15-0b05-4895-9daa-ad9eb2c6a140.png)
![QQ截图20210805174603](https://user-images.githubusercontent.com/46254113/128329874-9d16e080-69bc-4ed0-8093-cd5190a71ed0.png)
![QQ截图20210805174613](https://user-images.githubusercontent.com/46254113/128329894-303d9192-aa26-4b95-94cb-2074b6ecfb6f.png)


> 请将异常堆栈截全面一些，以便进行进一步分析和追踪问题

**Comment by mnixry** [comment]
> 已经使用了多个版本的mirai-api-http进行测试 均发生问题

通信方式是http上报还是websocket?

**Comment by lajxw** [comment]
> 通信方式是http上报还是websocket?

都测试过了 都有问题

**Comment by mnixry** [comment]
非常抱歉, 该问题在我这里无法进行复现
请检查您的网络连接已经防火墙等情况

**Comment by lajxw** [comment]
测试记录 windows server 2016
python 3.8.7
nonebot and mirai  a14 
mirai-console 2.7-M2
mirai-core 2.7-RC-dev-1
mirai-api-http v1.12.0
防火墙 关闭
问题存在

测试记录 windows 10
python 3.9.6
nonebot and mirai  a14 
mirai-console 2.6.7
mirai-core 2.6.7
mirai-api-http v1.11.0
防火墙 关闭
问题存在

测试记录 windows 10
python 3.9.6
nonebot and mirai  a14 
mirai-console 2.7-M2
mirai-core 2.7-RC-dev-1
mirai-api-http v1.12.0
防火墙 关闭
问题存在

**Comment by yanyongyu** [comment]
未能复现问题，如果有其他细节信息欢迎reopen并补充
