### ISSUE TITLE
Bug: 在Centos上启动失败

### ISSUE THREAD

**Issue by skadiD** [nonebot/nonebot2#477]
**描述问题：**
在centos上使用nb-cli创建项目并运行，bot在加载插件前中断出错
**如何复现？**
1.创建虚拟环境（python3.9）
2.安装`nb-cli` 并使用 `nb create`创建目录
3.启动bot（`nb start`)

**期望的结果**
bot初始化和加载默认插件成功

**环境信息：**

 - OS: [CentOS 7.9]
 - Python Version: [3.9.0b5]
 - Nonebot Version: [2.0.0a.14]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [1.0.0 b5]

**截图或日志**
![bug](https://user-images.githubusercontent.com/50161715/128624687-f1124bd6-65f0-4186-9eed-1243ee5f7328.png)

**Comment by mnixry** [comment]
possible related: https://github.com/samuelcolvin/pydantic/issues/1832

我感觉有可能是Python版本3.9.0b5的问题, 试着更换Python版本到支持的稳定版本 (如[`3.8.11`](https://www.python.org/downloads/release/python-3811/)或者[`3.9.6`](https://www.python.org/downloads/release/python-396/))

~~我知道CentOS7编译安装一个Python很辛苦, 但是你可能需要再来一次了~~

**Comment by skadiD** [comment]
yep，确实如此（一口气降到3.7）
