### ISSUE TITLE
使用bot.call_api()无法成功发送消息

### ISSUE THREAD

**Issue by Shi-Iho** [nonebot/nonebot2#49]
bot.call_api()无法成功发送消息。2种情况。1.没有错误，但并没有成功发送消息。2.出现错误ActionFailed，retcode=100。
使用go-cqhttp。
刚开始用，可能是因为我不懂怎么用。非常感谢。
代码
```python
import nonebot
from nonebot.rule import to_me
from nonebot.adapters.cqhttp import Bot, Event

keyword = {"test1", "test2"}

block = nonebot.plugin.on_keyword(keyword, rule=to_me(), priority=5)


@block.handle()
async def handle_first_receive(bot: Bot, event: Event, state: dict):
    user_id = event.user_id
    event_id = event.id
    print(event.user_id, "  ", event_id)
    await bot.call_api("send_msg", data={"user_id": user_id, "message": "123"})
```
日志  
11-12 09:58:18 [INFO] nonebot | CQHTTP | 1XXXXXXXX2 [message.private.friend]: Message 7313 from 3XXXXXXXX6 "test1"
11-12 09:58:18 [DEBUG] nonebot | Checking for matchers in priority 5...
11-12 09:58:18 [INFO] nonebot | Event will be handled by <Matcher from block, type=message, priority=5, temp=False>
11-12 09:58:18 [DEBUG] nonebot | Running matcher <Matcher from block, type=message, priority=5, temp=False>
3XXXXXXXX6    7313
11-12 09:58:18 [DEBUG] nonebot | CQHTTP | Calling API send_msg
11-12 09:58:18 [INFO] nonebot | Matcher <Matcher from block, type=message, priority=5, temp=False> running complete
11-12 09:58:18 [DEBUG] nonebot | Stop event propagation

**Comment by yanyongyu** [comment]
action failed是协议端的错误，具体看那边的日志，没有发出去的话确认nonebot这边是否有call api的debug日志，如果有那就是协议端问题参看那边的日志

**Comment by Shi-Iho** [comment]
找到问题了。文档中的示例是错误的。
![image](https://user-images.githubusercontent.com/51045202/98915506-f676a680-2504-11eb-91fd-d625c1a1fc44.png)  
用这种写法，参数将会被封装到data中。
![image](https://user-images.githubusercontent.com/51045202/98915865-70a72b00-2505-11eb-8683-759862e83832.png)
应该这样写才是正确的。
```python
await bot.call_api("send_msg", user_id=user_id, message="123")
```

**Comment by yanyongyu** [comment]
确实是文档写错了，可能是在nb1迁移过来的时候忘记修改了
