### ISSUE TITLE
Feature: 对戳一戳事件的响应

### ISSUE THREAD

**Issue by XCwosjw** [nonebot/nonebot2#494]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

虽然可以通过event.type来判断是否是戳一戳，但加一个对于戳一戳事件的完整支持我觉得还是更好一点

**描述你所需要的特性：**

支持对戳一戳事件的响应

**Comment by yanyongyu** [comment]
poke为cqhttp的特殊事件

你可以通过 `isinstance(event, PokeNotifyEvent)` 进行判断

nonebot不会为cqhttp添加一个内置响应，你可以自行编写一个rule

**Comment by XCwosjw** [comment]
不，我说的是对于Mirai的NudgeEvent（戳一戳事件）的响应，而不是cqhttp，我之前忘了说，抱歉。

**Comment by yanyongyu** [comment]
无论是cqhttp还是mirai都可以自行编写rule，nonebot不会对这个进行处理

**Comment by mnixry** [comment]
> 无论是cqhttp还是mirai都可以自行编写rule，nonebot不会对这个进行处理

现在MAH Adapter就没有戳一戳这个事件，会fallback回Event基类 :rofl:

**Comment by yanyongyu** [comment]
（
