### ISSUE TITLE
Bug: 在插件内赋值 __plugin_name__ 后，get_loaded_plugins() 获取插件的 matcher 属性为空

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/nonebot2#502]
**描述问题：**

在插件内手动赋值 `__plugin_name__` 后，get_loaded_plugins() 获取插件的 matcher 属性为空

**如何复现？**

编写插件并在插件内赋值 `__plugin_name__` ：

```python
from nonebot import on_message, on_notice, on_request, get_driver, get_loaded_plugins

__plugin_name__ = 'test'

message_matcher = on_message()
notice_matcher_t1 = on_notice()
request_matcher_t1 = on_request()


@get_driver().on_startup
async def matcher_test():
    print([(p.name, p.matcher) for p in get_loaded_plugins()])
```

在以下三种插件加载方式中，该现象都会发生：

目录结构：

![image](https://user-images.githubusercontent.com/41713304/129921370-27111660-2179-4f2e-9c3b-351dd5c66655.png)

导入语句：

![image](https://user-images.githubusercontent.com/41713304/129921468-72a095dc-9355-4e81-87d5-e87fdd0543c4.png)

上面导入的插件内容一致

控制台输出：

![image](https://user-images.githubusercontent.com/41713304/129921611-9a64f1dd-3934-4410-9c20-a346400fc2d8.png)

**特别的**，如果**当前路径**存在**同名目录**且**目录不为空**，则无论是否在插件内赋值 `__plugin_name__`，get_loaded_plugins() 都能够正常获取插件的 matcher

目录结构：

![image](https://user-images.githubusercontent.com/41713304/129922684-7f3be5e5-f29e-41c4-85cf-78c916eac8b0.png)

导入语句：

![image](https://user-images.githubusercontent.com/41713304/129922709-a1f0e7a0-fef4-4b6b-86e6-3a5f72df86a8.png)

控制台输出：

![image](https://user-images.githubusercontent.com/41713304/129922791-b6a7ea7c-1d28-4b58-91c1-d30c567eb6ba.png)

**期望的结果**

在插件内赋值 __plugin_name__ 后，get_loaded_plugins() 依然能正确获取插件的 matcher 属性

**环境信息：**

 - OS: Windows 10 21H1
 - Python Version: 3.9.6
 - Nonebot Version: 2.0.0a15

**协议端信息：**

 - 协议端: 无
 - 协议端版本: 无

**截图或日志**

如上

**Comment by yanyongyu** [comment]
nonebot 通过 `__plugin_name__` 属性进行 `Matcher` 判断，请勿自行修改该变量。

**Comment by Ailitonia** [comment]
好

使用 `__plugin_name__` 是 nb1 遗留的习惯

a13并未有该现象，a15中才有（a14大概也有？
