### ISSUE TITLE
账号被风控问题

### ISSUE THREAD

**Issue by Inetgeek** [nonebot/nonebot2#515]
**描述问题：**
经常发生我的机器人在群里和它交互无响应，没有任何反应，但是私聊主动交互机器人机器人正常工作。比如我在群里@机器人让它干啥一开始挺正常的，后面就不工作了，然后我私聊机器人让它做相同的事又有响应。后台报错是群消息发送失败，账号可能被风控。一旦疑似被风控那么这个时候主动群发和指定发给某个朋友的函数也不能正常调用api，函数包括send_friend_msg()和send_group_msg()不能正常使用
**如何复现？**
新注册的账号或老账号刚搭建机器人登录初期都会遇到

**Comment by mnixry** [comment]
首先，这个问题不是nonebot造成的，而是onebot协议实现端的问题

其次，提示“被风控”这就已经表明这是腾讯所做的限制，这个问题的解决办法已经不在我们任何第三方的能力范围之内

请参考：https://github.com/Mrs4s/go-cqhttp/issues/211#issuecomment-812059109

**Comment by Inetgeek** [comment]
感谢，大佬早点休息，辛苦啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月1日(周三) 凌晨2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nonebot/nonebot2] 账号被风控问题 (#515)




 
首先，这个问题不是nonebot造成的，而是onebot协议实现端的问题
 
其次，提示“被风控”这就已经表明这是腾讯所做的限制，这个问题的解决办法已经不在我们任何第三方的能力范围之内
 
请参考：Mrs4s/go-cqhttp#211 (comment)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanyongyu** [comment]
风控可以尝试挂久一点，设备锁等等
