### ISSUE TITLE
Plugin: hoshino插件修改

### ISSUE THREAD

**Issue by G41mywaifu** [nonebot/nonebot2#527]
**插件名称：**

hoshino插件修改

**插件功能：**

将适用于hoshino的插件修改为适用于nonebot2的插件

**PyPI 项目名：**

nonebot_plugin_re

**插件 import 包名：**

null

**插件项目仓库/主页链接：**

https://github.com/G41mywaifu/nonebot_plugin_re

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: hoshino插件修改

**⚠️ We have found following problem(s) in pre-publish progress:**
<pre><code><li>⚠️ Package <a href="https://pypi.org/project/nonebot_plugin_re/">nonebot_plugin_re</a> is not available on PyPI.<dt>  Please publish your package to PyPI.</dt></li></code></pre>
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/G41mywaifu/nonebot_plugin_re">homepage</a> returns 200.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by StarHeartHunt** [comment]
请正确填写插件import包名
