### ISSUE TITLE
Plugin: HanayoriBot

### ISSUE THREAD

**Issue by kanomahoro** [nonebot/nonebot2#528]
**插件名称：**

HanayoriBot

**插件功能：**

B站动态推送与开播提醒插件

**PyPI 项目名：**

nonebot-plugin-hanayori

**插件 import 包名：**

nonebot_plugin_hanayori

**插件项目仓库/主页链接：**

https://github.com/kanomahoro/nonebot-hanayori

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: HanayoriBot

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kanomahoro/nonebot-hanayori">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-hanayori/">nonebot-plugin-hanayori</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
