### ISSUE TITLE
Plugin: HTTP静态文件托管

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#531]
**插件名称：**

HTTP静态文件托管

**插件功能：**

一款 HTTP 静态文件托管插件, 为跨机文件传输提供了优雅的解决方案

**PyPI 项目名：**

nonebot-plugin-filehost

**插件 import 包名：**

nonebot_plugin_filehost

**插件项目仓库/主页链接：**

https://github.com/mnixry/nonebot-plugin-filehost

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: HTTP静态文件托管

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/mnixry/nonebot-plugin-filehost">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-filehost/">nonebot-plugin-filehost</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
