### ISSUE TITLE
Plugin: SimpleMusic

### ISSUE THREAD

**Issue by kanomahoro** [nonebot/nonebot2#533]
**插件名称：**

SimpleMusic

**插件功能：**

最简Q群点歌插件，支持网易云、QQ音乐

**PyPI 项目名：**

nonebot-plugin-simplemusic

**插件 import 包名：**

nonebot_plugin_simplemusic

**插件项目仓库/主页链接：**

https://github.com/kanomahoro/nonebot-simplemusic

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: SimpleMusic

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kanomahoro/nonebot-simplemusic">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-simplemusic/">nonebot-plugin-simplemusic</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by mnixry** [comment]
需要注意一下, 你GitHub仓库并不包含`pyproject.toml`等与PyPI包构建相关的文件
作为更好的工程实践, 建议在整理后进行上传, 以便其他用户自行构建
