### ISSUE TITLE
Bug: event_postprocessor 不能在 matcher 运行后正常执行

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/nonebot2#537]
**描述问题：**

event_postprocessor 不能在 matcher 运行后正常执行

**如何复现？**

编写以下插件
```python
from nonebot import on_command, logger
from nonebot.message import event_postprocessor
from nonebot.typing import T_State
from nonebot.adapters.cqhttp.event import Event, MessageEvent
from nonebot.adapters.cqhttp.bot import Bot


test = on_command('test')


@test.handle()
async def handle_test(bot: Bot, event: MessageEvent, state: T_State):
    logger.opt(colors=True).info('<ly>matcher is running!</ly>')


@event_postprocessor
async def handle_event_postprocessor(bot: Bot, event: Event, state: T_State):
    logger.opt(colors=True).success('<ly>event_postprocessor is running!</ly>')
```

**期望的结果**

event_postprocessor 能在任意情况下正常执行

实际上当 matcher 运行后 event_postprocessor 会被跳过

![image](https://user-images.githubusercontent.com/41713304/134709135-4d0d52ec-2df1-48a8-94ee-196c9c4d3da6.png)

**其他信息**

第 250 行 `return result` 将直接导致 matcher 运行后 event_postprocessor 被跳过

https://github.com/nonebot/nonebot2/blob/0b35d5e724a2fc7fc1e7d90499aea8a9c27e821d/nonebot/message.py#L238-L262

**环境信息：**

 - OS: Windows 10 21H1
 - Python Version: 3.9.6
 - Nonebot Version: 2.0.0a15

**协议端信息：**

 - 协议端: 无
 - 协议端版本: 无

**截图或日志**

如上

**Comment by AkiraXie** [comment]
这个确实会这样，如果某一个matcher是block的话，会触发StopPropagation这个异常，之后应该continue的但是却直接return了，所以return只应该面对非StopPropagation的Exception才行。

**Comment by yanyongyu** [comment]
这个问题是由pr #322 导致

**Comment by mnixry** [comment]
已在 #539 中修复, 该修复将会包含在下次版本发布中
