### ISSUE TITLE
Plugin: pornhub风格图标生成

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#542]
**插件名称：**

pornhub风格图标生成

**插件功能：**

生成pornhub风格logo

**PyPI 项目名：**

nonebot-plugin-phlogo

**插件 import 包名：**

nonebot_plugin_phlogo

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-phlogo

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: pornhub风格图标生成

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kexue-z/nonebot-plugin-phlogo">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-phlogo/">nonebot-plugin-phlogo</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
