### ISSUE TITLE
Plugin: rs-software-zhixue

### ISSUE THREAD

**Issue by MasterYuan418** [nonebot/nonebot2#548]
**插件名称：**

rs-software-zhixue

**插件功能：**

在NoneBot上查看你的智学网成绩

**PyPI 项目名：**

rs-software-zhixue

**插件 import 包名：**

rs-software-zhixue

**插件项目仓库/主页链接：**

https://pypi.org/project/rs-software-zhixue

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: rs-software-zhixue

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://pypi.org/project/rs-software-zhixue">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/rs-software-zhixue/">rs-software-zhixue</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
你发布的pypi包存在错误，请检查打包是否正确，另外`id`填写错误，link最好给仓库链接
