### ISSUE TITLE
Plugin: HarukaBot

### ISSUE THREAD

**Issue by SK-415** [nonebot/nonebot2#55]
**你的插件名称：**

HarukaBot

**简短描述插件功能：**

将B站UP主的动态和直播信息推送至QQ

**插件 import 使用的名称**

haruka_bot

**插件 install 使用的名称**

haruka-bot

通过 pypi 安装

> 请事先发布插件到[pypi](https://pypi.org/)

**插件项目仓库/主页链接**

SK-415/HarukaBot

**Comment by yanyongyu** [comment]
@SK-415 插件打包有点问题

文档还没有编写，暂时可以参考 [nonebot-plugin-status](https://github.com/cscs181/QQ-GitHub-Bot/tree/master/src/plugins/nonebot_plugin_status)

注意插件文件夹下的pyproject.toml

**Comment by SK-415** [comment]
> @SK-415 插件打包有点问题
> 
> 文档还没有编写，暂时可以参考 [nonebot-plugin-status](https://github.com/cscs181/QQ-GitHub-Bot/tree/master/src/plugins/nonebot_plugin_status)
> 
> 注意插件文件夹下的pyproject.toml

我确实是参考低调佬的 ` nonebot-plugin-status` 打包的. 只是我直接使用根目录的 `pypeoject.toml` 定位到 plugins 目录下打包的. 因为我觉得 bot 本身没有打包的需求, 但是 bot 跟插件的依赖是一样, 应该可以共用一份 `pyproject.toml`. 

我这边实际测试下来, 打出的包目录结构与低调佬的 ` nonebot-plugin-status` 目录结构一致, 通过 pip 安装到本地也能通过 `nonebot.load_plugin("haruka_bot")` 正常加载运行. 我看低调佬源码中 `nb install` 也是使用 pip 安装的, 便猜测应该没有影响. 

如果我理解的不对还请大佬指正 OTZ .
