### ISSUE TITLE
Plugin: ZhixueScore

### ISSUE THREAD

**Issue by MasterYuan418** [nonebot/nonebot2#552]
**插件名称：**

ZhixueScore

**插件功能：**

在NoneBot上查询你的智学网成绩

**PyPI 项目名：**

rs-software-zhixue

**插件 import 包名：**

rs_software_zhixue

**插件项目仓库/主页链接：**

https://github.com/RisConn/software-zhixue

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: ZhixueScore

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/RisConn/software-zhixue">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/rs-software-zhixue/">rs-software-zhixue</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
你打包的包里根本没有代码啊，你要么删除 `setup.py` 用poetry打包

**Comment by MasterYuan418** [comment]
啊这...对不起我真没咋用过py...一直都用的是nuget....
非常抱歉，会去修正的。
感谢。
