### ISSUE TITLE
Plugin: Twitter推送

### ISSUE THREAD

**Issue by kanomahoro** [nonebot/nonebot2#563]
**插件名称：**

Twitter推送

**插件功能：**

Twitter推送插件，自带推文翻译功能

**PyPI 项目名：**

nonebot-plugin-twitter

**插件 import 包名：**

nonebot_plugin_twitter

**插件项目仓库/主页链接：**

https://github.com/kanomahoro/nonebot-twitter

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: Twitter推送

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kanomahoro/nonebot-twitter">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-twitter/">nonebot-plugin-twitter</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
