### ISSUE TITLE
Plugin: nb2chan

### ISSUE THREAD

**Issue by yucongo** [nonebot/nonebot2#565]
**插件名称：**

nb2chan

**插件功能：**

Nonebot2酱推送

**PyPI 项目名：**

nb2chan

**插件 import 包名：**

nb2chan

**插件项目仓库/主页链接：**

https://github.com/ffreemt/nb2chan

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: nb2chan

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/ffreemt/nb2chan">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nb2chan/">nb2chan</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
