### ISSUE TITLE
Feature: 为OneBot适配器添加`helpers`工具函数/工具类

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#567]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

NoneBot1中提供了丰富的预定义函数, 包括:
- [判断取消关键词以取消事件处理](https://github.com/nonebot/nonebot/blob/3a90c3fdc1017e4c1af04dcb3e786bea915619d1/nonebot/command/argfilter/controllers.py#L7-L34)
- [判断`是/否`类关键词](https://github.com/nonebot/nonebot/blob/3a90c3fdc1017e4c1af04dcb3e786bea915619d1/nonebot/command/argfilter/converters.py#L4-L28)
- [提取消息中的图片](https://github.com/nonebot/nonebot/blob/3a90c3fdc1017e4c1af04dcb3e786bea915619d1/nonebot/command/argfilter/extractors.py#L15-L22)
- [提取消息中的数字](https://github.com/nonebot/nonebot/blob/3a90c3fdc1017e4c1af04dcb3e786bea915619d1/nonebot/command/argfilter/extractors.py#L25-L28)

**描述你所需要的特性：**

在NoneBot2的OneBot Adapter中封装一些预定义的函数到`nonebot.adapters.cqhttp.helpers`, 例如:
- [带有隔离等级的命令防抖和冷却](https://github.com/mixmoe/IzumiBot/blob/b13416d34acd0695091f131252f0aaad5c3840cb/IzumiBot/plugins/bot_utils/controllers.py#L44-L95)
- [允许用户通过取消类关键词结束matcher执行](https://github.com/mixmoe/IzumiBot/blob/b13416d34acd0695091f131252f0aaad5c3840cb/IzumiBot/plugins/bot_utils/controllers.py#L16-L41)
- [将`是/否`类关键词转换为`boolean`](https://github.com/mixmoe/IzumiBot/blob/b13416d34acd0695091f131252f0aaad5c3840cb/IzumiBot/plugins/bot_utils/converter.py#L50-L62)
- [提取消息中的图片URL](https://github.com/mixmoe/IzumiBot/blob/b13416d34acd0695091f131252f0aaad5c3840cb/IzumiBot/plugins/bot_utils/extractors.py#L9-L14)

~~私货好多~~

**Comment by mnixry** [comment]
> 为什么叫helpers不叫utils呢？

因为utils已经有了，定位是实现平台特定协议所需的工具函数
helpers是帮助用户完成特定需求的工具函数，所以区分开

> 另外可否考虑单独做成插件？（可以适配各种adapter的）

~~要是做成插件就没人用了，直接内置用的人还多一点~~

**Comment by StarHeartHunt** [comment]
提取消息中的图片感觉可以放到utils，变成从message提取指定类型的segment

**Comment by yanyongyu** [comment]
merged in nonebot/adapter-onebot#2
