### ISSUE TITLE
Feature: 命令处理类函数重载支持任意参数名、注解、依赖注入

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#568]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

NoneBot2支持通过[函数类型注解](https://www.python.org/dev/peps/pep-0484/)来对事件处理函数能够接受的函数类型进行筛选
但是它目前只支持直接使用类进行注解, 不支持`Union`等类型标识符

**描述你所需要的特性：**

使事件处理函数重载支持`Union`之类的类型标识符, 最好包括对`ForwardRef`等的支持

~~虽然assign了我自己但是我没时间写诶~~

**Comment by yanyongyu** [comment]
done in latest dev branch
