### ISSUE TITLE
oicq作为客户端向nonebot推送消息时无法解析

### ISSUE THREAD

**Issue by retroxz** [nonebot/nonebot2#583]
**描述问题：**

oicq作为客户端向nonebot推送消息时无法解析，所有消息均提示“ValueError: Event has no message!”

**如何复现？**

1. 使用oicq作为客户端登录，方法参考https://github.com/takayama-lily/oicq/tree/master/http-api
2. 配置oicq上报方式为反向ws，消息格式为array
3. 发送消息，提示“ValueError: Event has no message!”

**环境信息：**

 - OS: windows10
 - Python Version: 3.8
 - Nonebot Version: 2.0.0a16

**协议端信息：**

 - 协议端: oicq
 - 协议端版本: 1.21.2

**截图或日志**

`module.exports = {

    //通用配置
    general: {
        platform:           1,       //1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad
        log_level:          "info",  //trace,debug,info,warn,error,mark
        use_cqhttp_notice:  true,   //是否使用cqhttp标准的notice事件格式

        host:               "0.0.0.0",  //监听主机名
        port:               5700,       //端口
        use_http:           false,      //启用http
        use_ws:             false,      //启用正向ws，和http使用相同地址和端口
        access_token:       "",         //访问api的token
        secret:             "",         //上报数据的sha1签名密钥
        post_timeout:       30,         //post超时时间(秒)
        post_message_format:"array",    //"string"或"array"
        enable_cors:        false,      //是否允许跨域请求
        enable_heartbeat:   false,      //是否启用ws心跳
        heartbeat_interval: 15000,      //ws心跳间隔(毫秒)
        rate_limit_interval:500,        //使用_rate_limited后缀限速调用api的排队间隔时间(毫秒)
        event_filter:       "",         //json格式的事件过滤器文件路径
        post_url: [ //上报地址，可以添加多个url
            // "http://your.address.com:80",
        ],
        ws_reverse_url: [ //反向ws地址，可以添加多个url
            "ws://127.0.0.1:1885/cqhttp/ws"
        ],
        ws_reverse_reconnect_interval: 3000, //反向ws断线重连间隔(毫秒)，设为负数直接不重连
        ws_reverse_reconnect_on_code_1000: true, //反向ws是否在关闭状态码为1000的时候重连
    },`

**Comment by yanyongyu** [comment]
oicq因为不符合onebot协议规范所以无法正确解析

**Comment by retroxz** [comment]
谢谢大佬 我是看到CQHTTP协议文档上写可以吧node-onebot作为客户端所以试了一下
