### ISSUE TITLE
Plugin: IT咨讯

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#584]
**插件名称：**

IT咨讯

**插件功能：**

获取IT咨讯并生成图片发送

**PyPI 项目名：**

nonebot-plugin-itnew

**插件 import 包名：**

nonebot-plugin-itnews

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/nonebot_plugin_itnews

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: IT咨讯

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/yzyyz1387/nonebot_plugin_itnews">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-itnew/">nonebot-plugin-itnew</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
