### ISSUE TITLE
Plugin: lolheroes

### ISSUE THREAD

**Issue by cjladmin** [nonebot/nonebot2#590]
**插件名称：**

lolheroes

**插件功能：**

获取lol英雄背景的故事

**PyPI 项目名：**

lolHeroes

**插件 import 包名：**

lolheroes

**插件项目仓库/主页链接：**

https://github.com/cjladmin/lolheroes

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: lolheroes

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/cjladmin/lolheroes">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/lolHeroes/">lolHeroes</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
