### ISSUE TITLE
Plugin: nonebot_plugin_youthstudy

### ISSUE THREAD

**Issue by ayanamiblhx** [nonebot/nonebot2#593]
**插件名称：**

nonebot_plugin_youthstudy

**插件功能：**

基于nonebot的青年大学习插件，用来获取最新一期的青年大学习答案

**PyPI 项目名：**

nonebot-plugin-youthstudy

**插件 import 包名：**

nonebot_plugin_youthstudy

**插件项目仓库/主页链接：**

https://github.com/ayanamiblhx/nonebot_plugin_youthstudy

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: nonebot_plugin_youthstudy

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/ayanamiblhx/nonebot_plugin_youthstudy">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-youthstudy/">nonebot-plugin-youthstudy</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
