### ISSUE TITLE
Plugin: gocqapi

### ISSUE THREAD

**Issue by FYWinds** [nonebot/nonebot2#596]
**插件名称：**

gocqapi

**插件功能：**

对 go-cqhttp 的 API 调用添加了类型注解与滥用OOP的返回值Model支持，远离魔法方法的Dict[Any, Any]

**PyPI 项目名：**

gocqapi

**插件 import 包名：**

gocqapi

**插件项目仓库/主页链接：**

https://github.com/FYWinds/gocqapi

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: gocqapi

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/FYWinds/gocqapi">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/gocqapi/">gocqapi</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
