### ISSUE TITLE
Plugin: 工作性价比计算器

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#598]
**插件名称：**

工作性价比计算器

**插件功能：**

一个计算工作性价比的插件

**PyPI 项目名：**

nonebot-plugin-workscore

**插件 import 包名：**

nonebot_plugin_workscore

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/nonebot_plugin_workscore

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 工作性价比计算器

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/yzyyz1387/nonebot_plugin_workscore">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-workscore/">nonebot-plugin-workscore</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
