### ISSUE TITLE
Plugin: 诺基亚手机图生成

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#600]
**插件名称：**

诺基亚手机图生成

**插件功能：**

生成一张诺基亚（无内鬼）图片

**PyPI 项目名：**

nonebot-plugin-nokia

**插件 import 包名：**

nonebot_plugin_nokia

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-nokia

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 诺基亚手机图生成

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kexue-z/nonebot-plugin-nokia">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-nokia/">nonebot-plugin-nokia</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
