### ISSUE TITLE
Plugin: nonebot-plugin-asoulcnki

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#602]
**插件名称：**

nonebot-plugin-asoulcnki

**插件功能：**

枝网查重插件，查询发病小作文复制比

**PyPI 项目名：**

nonebot-plugin-asoulcnki

**插件 import 包名：**

nonebot_plugin_asoulcnki

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-asoulcnki

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: nonebot-plugin-asoulcnki

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/MeetWq/nonebot-plugin-asoulcnki">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-asoulcnki/">nonebot-plugin-asoulcnki</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
