### ISSUE TITLE
在Bot.on_calling_api函数中提供取消调用api的方法，取消后返回内容自定义

### ISSUE THREAD

**Issue by HibiKier** [nonebot/nonebot2#605]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

例如某功能定时发送任务对某个群聊发送消息，但是在该群中此功能被关闭了，如果要使该消息不被定时任务发送，需要写if 开关状态....来判断是否发送消息，希望在call_api的钩子函数中统一进行管理

**描述你所需要的特性：**

提供在on_calling_api提供取消调用api的方法

**Comment by synodriver** [comment]
这个可以有(

**Comment by yanyongyu** [comment]
done in dev
