### ISSUE TITLE
Plugin: nonebot-plugin-petpet

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#606]
**插件名称：**

nonebot-plugin-petpet

**插件功能：**

制作头像相关的沙雕表情包

**PyPI 项目名：**

nonebot-plugin-petpet

**插件 import 包名：**

nonebot_plugin_petpet

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-petpet

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: nonebot-plugin-petpet

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/MeetWq/nonebot-plugin-petpet">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-petpet/">nonebot-plugin-petpet</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
