### ISSUE TITLE
Plugin: ShindanMaker

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#608]
**插件名称：**

ShindanMaker

**插件功能：**

使用 ShindanMaker 网站的趣味占卜

**PyPI 项目名：**

nonebot-plugin-shindan

**插件 import 包名：**

nonebot_plugin_shindan

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-shindan

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: ShindanMaker

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/MeetWq/nonebot-plugin-shindan">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-shindan/">nonebot-plugin-shindan</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
