### ISSUE TITLE
Plugin: 虚拟朋友

### ISSUE THREAD

**Issue by snowyfirefly** [nonebot/nonebot2#610]
**插件名称：**

虚拟朋友

**插件功能：**

基于小冰框架的人工智能聊天机器人

**PyPI 项目名：**

nonebot-plugin-vf

**插件 import 包名：**

nonebot_plugin_vf

**插件项目仓库/主页链接：**

https://github.com/snowyfirefly/VirtualFriends

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 虚拟朋友

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/snowyfirefly/VirtualFriends">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-vf/">nonebot-plugin-vf</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by snowyfirefly** [comment]
虚拟朋友插件0.0.5

**Comment by mnixry** [comment]
请确定您项目的`setup.cfg`编写正确, 目前上传到PyPI的目录结构并不支持以包名`nonebot_plugin_vf`引入

**Comment by yanyongyu** [comment]
他的配置是正确的，但是没有写依赖项
