### ISSUE TITLE
Plugin: 在线运行代码

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#612]
**插件名称：**

在线运行代码

**插件功能：**

在线运行代码插件，支持输入

**PyPI 项目名：**

nonebot-plugin-code

**插件 import 包名：**

nonebot-plugin-code

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/nonebot_plugin_code

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 在线运行代码

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/yzyyz1387/nonebot_plugin_code">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-code/">nonebot-plugin-code</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
