### ISSUE TITLE
Plugin: 随机黑丝

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#616]
**插件名称：**

随机黑丝

**插件功能：**

发送一张黑丝涩图，内置CD

**PyPI 项目名：**

nonebot-plugin-heisi

**插件 import 包名：**

nonebot_plugin_heisi

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/nonebot_plugin_heisi

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 随机黑丝

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/yzyyz1387/nonebot_plugin_heisi">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-heisi/">nonebot-plugin-heisi</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
