### ISSUE TITLE
Bug: Little Bug in the Guide Doc 文档中的小bug

### ISSUE THREAD

**Issue by HowQi** [nonebot/nonebot2#62]
**描述问题：**

在指南->编写插件->事件处理->常用事件处理结构里附加的一小段示例代码似乎有问题

在27行(附上下文)

```
    # 发送一些信息
    await bot.send("message")
    await matcher.send("message")
    await matcher.finish("message")
```
bot.send似乎是需要两个参数的,即,正确写法为

```
await bot.send(event,"message")
```
不知是不是作者疏忽忘记了,特此汇报

**如何复现？**

[点★击★这★里](https://v2.nonebot.dev/guide/creating-a-handler.html#常用事件处理结构)

**期望的结果**

见描述问题一栏,略

**环境信息：**

浏览器: Cent Broswer

**截图**

略

**Comment by yanyongyu** [comment]
感谢！已修改
