### ISSUE TITLE
Plugin: picsbank

### ISSUE THREAD

**Issue by Diaosi1111** [nonebot/nonebot2#623]
**插件名称：**

picsbank

**插件功能：**

匹配图片进行回答

**PyPI 项目名：**

nonebot-plugin-picsbank

**插件 import 包名：**

nonebot_plugin_picsbank

**插件项目仓库/主页链接：**

https://github.com/Diaosi1111/nonebot_plugin_picsbank

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: picsbank

**⚠️ We have found following problem(s) in pre-publish progress:**
<pre><code><li>⚠️ Package <a href="https://pypi.org/project/https://pypi.org/project/nonebot-plugin-picsbank/">https://pypi.org/project/nonebot-plugin-picsbank</a> is not available on PyPI.<dt>  Please publish your package to PyPI.</dt></li></code></pre>
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/Diaosi1111/nonebot_plugin_picsbank">homepage</a> returns 200.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
我看到您的项目源码里有

```python
 __plugin_name__ = "pics_bank" 
```

这可能会影响到 NoneBot 的插件加载机制
