### ISSUE TITLE
Plugin: 剧集更新列表

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#625]
**插件名称：**

剧集更新列表

**插件功能：**

获取聚集更新

**PyPI 项目名：**

nonebot-plugin-tvseries

**插件 import 包名：**

nonebot_plugin_tvseries

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-tvseries

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 剧集更新列表

**⚠️ We have found following problem(s) in pre-publish progress:**
<pre><code><li>⚠️ Package <a href="https://pypi.org/project/https://pypi.org/project/nonebot-plugin-tvseries//">https://pypi.org/project/nonebot-plugin-tvseries/</a> is not available on PyPI.<dt>  Please publish your package to PyPI.</dt></li></code></pre>
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kexue-z/nonebot-plugin-tvseries">homepage</a> returns 200.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
