### ISSUE TITLE
Plugin: lol比赛信息

### ISSUE THREAD

**Issue by Diaosi1111** [nonebot/nonebot2#627]
**插件名称：**

lol比赛信息

**插件功能：**

简单的lol比赛信息插件，订阅后会定时推送当日比赛结果

**PyPI 项目名：**

nonebot-plugin-lolmatch

**插件 import 包名：**

nonebot_plugin_lolmatch

**插件项目仓库/主页链接：**

https://github.com/Diaosi1111/nonebot_plugin_lolmatch

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: lol比赛信息

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/Diaosi1111/nonebot_plugin_lolmatch">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-lolmatch/">nonebot-plugin-lolmatch</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
