### ISSUE TITLE
Plugin: OlivOS.nb2

### ISSUE THREAD

**Issue by j1g5awi** [nonebot/nonebot2#632]
**插件名称：**

OlivOS.nb2

**插件功能：**

在 NoneBot2 中加载 OlivOS 插件

**PyPI 项目名：**

olivos.nb2

**插件 import 包名：**

OlivOS

**插件项目仓库/主页链接：**

https://github.com/nonepkg/OlivOS.nb2

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: OlivOS.nb2

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/nonepkg/OlivOS.nb2">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/olivos.nb2/">olivos.nb2</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
