### ISSUE TITLE
Plugin: 通过浏览器来生成图片

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#634]
**插件名称：**

通过浏览器来生成图片

**插件功能：**

通过playwright加一点点前端知识来简单的生成图片

**PyPI 项目名：**

nonebot-plugin-htmlrender

**插件 import 包名：**

nonebot_plugin_htmlrender

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-htmlrender

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 通过浏览器来生成图片

**⚠️ We have found following problem(s) in pre-publish progress:**
<pre><code><li>⚠️ Package <a href="https://pypi.org/project/https://pypi.org/project/nonebot-plugin-htmlrender//">https://pypi.org/project/nonebot-plugin-htmlrender/</a> is not available on PyPI.<dt>  Please publish your package to PyPI.</dt></li></code></pre>
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/kexue-z/nonebot-plugin-htmlrender">homepage</a> returns 200.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
