### ISSUE TITLE
Plugin: 简易群管

### ISSUE THREAD

**Issue by yzyyz1387** [nonebot/nonebot2#636]
**插件名称：**

简易群管

**插件功能：**

简易群管 踢 禁 改

**PyPI 项目名：**

nonebot-plugin-admin

**插件 import 包名：**

nonebot_plugin_admin

**插件项目仓库/主页链接：**

https://github.com/yzyyz1387/nonebot_plugin_admin

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: 简易群管

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/yzyyz1387/nonebot_plugin_admin">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-admin/">nonebot-plugin-admin</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
