### ISSUE TITLE
Plugin: nonebot-plugin-logo

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#638]
**插件名称：**

nonebot-plugin-logo

**插件功能：**

PornHub、Youtube 等风格logo生成

**PyPI 项目名：**

nonebot-plugin-logo

**插件 import 包名：**

nonebot_plugin_logo

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-logo

**Comment by yanyongyu** [comment]
# 📃 Publish Check Result
> Plugin: nonebot-plugin-logo

**✅ All tests passed, you are ready to go!**
<details>
    <summary>Report Detail</summary>
    <pre><code><li>✅ Project <a href="https://github.com/MeetWq/nonebot-plugin-logo">homepage</a> returns 200.</li>
<li>✅ Package <a href="https://pypi.org/project/nonebot-plugin-logo/">nonebot-plugin-logo</a> is available on PyPI.</li></code></pre>
    </details>

---
💪 Powered by NoneBot2 Publish Bot
