### ISSUE TITLE
Bug: 回复问题

### ISSUE THREAD

**Issue by sam01101** [nonebot/nonebot2#66]
#65

**Comment by yanyongyu** [comment]
https://github.com/nonebot/nonebot2/pull/65#issuecomment-730344401

**Comment by sam01101** [comment]
> [#65 (comment)](https://github.com/nonebot/nonebot2/pull/65#issuecomment-730344401)
> 
> See also #64

並不是重複, 請仔細檢查

**Comment by sam01101** [comment]
我所在的版本本已是dev, 此bug依然存在

**Comment by yanyongyu** [comment]
能否提供一下日志，我这里所有的发送和回复都正常

![image](https://user-images.githubusercontent.com/42488585/99667450-64901000-2aa7-11eb-92c7-3708f6691a68.png)

**Comment by yanyongyu** [comment]
nonebot会删除第一个reply以及后面的两个@

**Comment by sam01101** [comment]
> nonebot会删除第一个reply以及后面的两个@

尝试使用TIM

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/99667722-c5b7e380-2aa7-11eb-8321-63128e5aa173.png)
在TIM中, @已自动添加, 但不知为何并未移除

**Comment by yanyongyu** [comment]
我是用的是tim，依然未能复现消息内容与你提供的复现消息基本一致，解析正常

![image](https://user-images.githubusercontent.com/42488585/99668222-69a18f00-2aa8-11eb-9556-95c6f4d6bf8f.png)

**Comment by sam01101** [comment]
> 能否提供一下日志，我这里所有的发送和回复都正常，还有环境信息
> 
> ![image](https://user-images.githubusercontent.com/42488585/99667450-64901000-2aa7-11eb-92c7-3708f6691a68.png)

环境: dev版本, 0c39b06355ef710132a96bebc7f42df76f941bb5

![image](https://user-images.githubusercontent.com/25792361/99668275-7920d800-2aa8-11eb-81c5-b4736a802d9f.png)

![image](https://user-images.githubusercontent.com/25792361/99668346-8f2e9880-2aa8-11eb-933c-1f703d8f4aaa.png)

**Comment by yanyongyu** [comment]
在 `_check_reply` 中添加两行，确认一下日志解析前后的消息内容

![image](https://user-images.githubusercontent.com/42488585/99668559-e2a0e680-2aa8-11eb-9228-af98664d2dbe.png)

**Comment by sam01101** [comment]
> 在 `_check_reply` 中添加两行，确认一下日志解析前后的消息内容
> 
> ![image](https://user-images.githubusercontent.com/42488585/99668559-e2a0e680-2aa8-11eb-9228-af98664d2dbe.png)

![Uploading image.png…]()

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/99669206-b3d74000-2aa9-11eb-8b17-79ab86539dd4.png)

**Comment by yanyongyu** [comment]
你回复的消息是否是机器人的消息

**Comment by yanyongyu** [comment]
已定位bug
