### ISSUE TITLE
使用matcher.send发送的字符串cq码不会被转换

### ISSUE THREAD

**Issue by sfghgy249** [nonebot/nonebot2#662]
**描述问题：**
协议端为go-cqhttp
使用matcher.send发送带cq码的字符串实际将会以cq码原文发送信息。如matcher.send(message = [CQ:face,id=11])。qq实际发送消息为 [CQ:face,id=11]而不是表情。
发现/Nonebot/adapters/cqhttp/bot.py中第446行与447行对整个消息进行了cq码转义。似乎因为连cq码外面的[ ]也转义而导致。

**如何复现？**

使用matcher.send发送任意带cq码的字符串。

**期望的结果**

matcher.send正常对cq码进行转换

**环境信息：**

 - OS: [Windows]
 - Python Version: [e.g. 3.8]
 - Nonebot Version: [e.g. 2.0.0]

**协议端信息：**

 - 协议端: [e.g. go-cqhttp]
 - 协议端版本: [e.g. 1.0.0]

**截图或日志**

**Comment by sfghgy249** [comment]
> 

啊matcher.send(message = “[CQ:face,id=11]”) 忘记加引号，不好意思，但是问题确实存在

**Comment by yanyongyu** [comment]
这不是bug，是安全考虑，请使用MessageSegment

**Comment by sfghgy249** [comment]
好的

**Comment by mnixry** [comment]
Duplicate of #212
