### ISSUE TITLE
Plugin: 群文件直链提取器

### ISSUE THREAD

**Issue by ninthseason** [nonebot/nonebot2#663]
**插件名称：**

群文件直链提取器

**插件功能：**

提取群文件的下载直链。

**PyPI 项目名：**

nonebot-plugin-directlinker

**插件 import 包名：**

nonebot_plugin_directlinker

**插件项目仓库/主页链接：**

https://github.com/ninthseason/nonebot-plugin-directlinker

**标签：**

[{"label":"a:cqhttp","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 群文件直链提取器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#ea5252</li><li>✅ 项目 <a href="https://github.com/ninthseason/nonebot-plugin-directlinker">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-directlinker/">nonebot-plugin-directlinker</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
