### ISSUE TITLE
Plugin: 转发姬

### ISSUE THREAD

**Issue by ninthseason** [nonebot/nonebot2#665]
**插件名称：**

转发姬

**插件功能：**

群聊消息实时转发

**PyPI 项目名：**

nonebot-plugin-forwarder

**插件 import 包名：**

nonebot_plugin_forwarder

**插件项目仓库/主页链接：**

https://github.com/ninthseason/nonebot_plugin_forwarder

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 转发姬

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ninthseason/nonebot_plugin_forwarder">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-forwarder/">nonebot-plugin-forwarder</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
