### ISSUE TITLE
Adapter: 开黑啦

### ISSUE THREAD

**Issue by Tian-que** [nonebot/nonebot2#670]
**协议名称：**

开黑啦

**协议功能：**

开黑啦协议适配

**PyPI 项目名：**

nonebot-adapter-kaiheila

**协议 import 包名：**

nonebot.adapters.kaiheila

**协议项目仓库/主页链接：**

https://github.com/Tian-que/nonebot-adapter-kaiheila

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: 开黑啦

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Tian-que/nonebot-adapter-kaiheila">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-adapter-kaiheila/">nonebot-adapter-kaiheila</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
