### ISSUE TITLE
Bug: 部分情况下，加载失败的插件依然会出现在当前已导入的所有插件中

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#675]
**描述问题：**

通过 nonebot.get_loaded_plugins() 获取当前已导入的所有插件，加载失败的插件也出现在其中

**如何复现？**

1. 复制 2.0.0 a16 版本文档的[注册事件响应器](https://61d3d9dbcadf413fd3238e89--nonebot2.netlify.app/guide/creating-a-matcher.html)一节的 weather.py 的代码作为插件，并在 2.0.0 beta1 版本导入它（很显然，这会发生错误）
2. 通过 nonebot.get_loaded_plugins() 获取已导入的插件，可以发现这个加载失败的插件出现在了已导入的插件中

**期望的结果**

加载失败的插件不出现在已导入的所有插件中

**环境信息：**

 - OS: [Windows]
 - Python Version: [3.10]
 - Nonebot Version: [2.0.0 b1]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [1.0.0]

**截图或日志**

```
[ERROR] nonebot | Failed to import "kirami.plugins.weather"
ValueError: Unknown parameter state for function <function handle_first_receive at 0x000001924056AB90> with type typing.Dict[typing.Any, typing.Any]

{Plugin(name='weather', module=<module 'kirami.plugins.weather' from 'D:\\Users\\Documents\\gitee\\KiramiBot\\kirami\\plugins\\weather\\__init__.py'>, module_name='kirami.plugins.weather', manager=<nonebot.plugin.manager.PluginManager object at 0x000002140ECEF130>, export={}, matcher=set(), parent_plugin=None, sub_plugins=set())}
```

**Comment by yanyongyu** [comment]
已在dev中修复
