### ISSUE TITLE
Plugin: KFC疯狂星期四

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#688]
**插件名称：**

KFC疯狂星期四

**插件功能：**

天天疯狂！随机输出KFC疯狂星期四文案。

**PyPI 项目名：**

https://pypi.org/project/nonebot-plugin-crazy-thursday/

**插件 import 包名：**

nonebot_plugin_crazy_thursday

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_crazy_thursday

**Comment by yanyongyu** [comment]
请刷新你的文档后发布插件，pypi项目名不要使用链接，只需要名称
