### ISSUE TITLE
Plugin: KFC疯狂星期四

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#689]
**插件名称：**

KFC疯狂星期四

**插件功能：**

天天疯狂！随机输出KFC疯狂星期四文案。

**PyPI 项目名：**

nonebot-plugin-crazy-thursday

**插件 import 包名：**

nonebot_plugin_crazy_thursday

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_crazy_thursday

**Comment by KafCoppelia** [comment]
怎么又寄了 QAQ

**Comment by yanyongyu** [comment]
请使用最新版beta1文档发布插件 ctrl f5强制刷新
