### ISSUE TITLE
Plugin: 扔骰子

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#690]
**插件名称：**

扔骰子

**插件功能：**

掷骰！扔出指定个数的多面骰子。

**PyPI 项目名：**

nonebot-plugin-roll

**插件 import 包名：**

nonebot_plugin_roll

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_roll

**Comment by yanyongyu** [comment]
请使用新版本文档发布插件，ctrl f5强制刷新

**Comment by KafCoppelia** [comment]
在哪里呢？🤔master文档里没看到

**Comment by yanyongyu** [comment]
v2.nonebot.dev

**Comment by he0119** [comment]
![image](https://user-images.githubusercontent.com/5219550/149486610-12826617-4c20-4b73-a241-aba53a3ed025.png)
新版的发布界面应该是这样的。

**Comment by KafCoppelia** [comment]
刷不进去😫

**Comment by KafCoppelia** [comment]
机缘巧合找到了个文档内/docs的链接进了新版文档，然后OK了
