### ISSUE TITLE
Plugin: 扔骰子

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#694]
**插件名称：**

扔骰子

**插件功能：**

掷骰！扔出指定个数的多面骰子。

**PyPI 项目名：**

nonebot-plugin-roll

**插件 import 包名：**

nonebot_plugin_roll

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_roll

**标签：**

[{"label":"t:roll","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 扔骰子

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:roll-#ea5252</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_roll">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-roll/">nonebot-plugin-roll</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
