### ISSUE TITLE
Plugin: 疯狂星期四

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#696]
**插件名称：**

疯狂星期四

**插件功能：**

天天疯狂！随机输出KFC疯狂星期四文案

**PyPI 项目名：**

nonebot-plugin-crazy-thursday

**插件 import 包名：**

nonebot_plugin_crazy_thursday

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_crazy_thursday

**标签：**

[{"label":"t:Thursday","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 疯狂星期四

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:Thursday-#ea5252</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_crazy_thursday">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-crazy-thursday/">nonebot-plugin-crazy-thursday</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
