### ISSUE TITLE
Plugin: 疫情查询

### ISSUE THREAD

**Issue by Zeta-qixi** [nonebot/nonebot2#698]
**插件名称：**

新冠疫情查询😷

**插件功能：**

查询国内城市新冠疫情信息与政策

**PyPI 项目名：**

nonebot-plugin-covid19-news

**插件 import 包名：**

nonebot_plugin_covid19_news

**插件项目仓库/主页链接：**

https://github.com/Zeta-qixi/nonebot-plugin-covid19-news

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 新冠疫情查询😷

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Zeta-qixi/nonebot-plugin-covid19-news">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-covid19-news/">nonebot-plugin-covid19-news</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by mnixry** [comment]
请记得将`setup.py`等包构建上传相关文件提交至仓库
