### ISSUE TITLE
Log: 美化logger输出

### ISSUE THREAD

**Issue by yanyongyu** [nonebot/nonebot2#7]
## IDEAS

- [x] 输出重要信息
- [x] 明确Log分级
- [x] 输出添加颜色以区分信息

**Comment by XZhouQD** [comment]
一键添加基于插件的plugin_name_abbr属性（如果有？）的前缀？比如
[INFO][MW_RC_No] .......................
[ERROR][MW_RC_No] .......................

提供一个简单的config.yaml（yaml？json？其他格式？）来快速指定是否输出log到文件以及log的输出等级？

**Comment by Kyomotoi** [comment]
黑名单，可涉及至某群/某人，使某群/某人没法使用/触发本插件
插件开关也给整一个，最好可单独控制每个群

**Comment by Kyomotoi** [comment]
输出群/私聊类型，以及对应群号/Q号，demo:
[GROUP][123456789] text: xxxxxxx
[PRIVATE][123456789] text: xxxxxxx

其中，如果信息类型是小程序一类：
[GROUP][123456789] rich: xxxxxxx
[PRIVATE][123456789] rich: xxxxxxx

信息类型用蓝色，群号/Q号以及其中的文本则用正常的白色，如 text 中包含类似CQ码一类的东西，则用黄色对其进行标注
