### ISSUE TITLE
Plugin: 人生重开模拟器

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#700]
**插件名称：**

人生重开模拟器

**插件功能：**

这垃圾人生一秒也不想待了？立即重开！

**PyPI 项目名：**

nonebot-plugin-remake

**插件 import 包名：**

nonebot_plugin_remake

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-remake

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"a:cqhttp","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 人生重开模拟器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, a:cqhttp-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-remake">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-remake/">nonebot-plugin-remake</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
