### ISSUE TITLE
single session插件无法正常运作

### ISSUE THREAD

**Issue by CherryGS** [nonebot/nonebot2#709]
**描述问题：**

如果在另一个 `run_preprocessor` 中 `raise IgnoredException` , 会导致 `single session` 插件无法正确执行删除操作 , 导致之后的 `matcher` 被无情 `IgnoredException(Another matcher running)` 掉

**如何复现？**

用 `run_preprocessor` 装饰一个函数并抛出 `IgnoredException` , 然后尝试触发另一个 `matcher` , 得到 log "matcher running is cancelled"

**期望的结果**

matcher 正常运行

**环境信息：**

 - OS: linux
 - Python Version: 3.10
 - Nonebot Version: 2b1

**协议端信息：**

 - 协议端: gocq
 - 协议端版本: b8f2

**截图或日志**

**Comment by yanyongyu** [comment]
fixed in #711
