### ISSUE TITLE
Plugin: 天气查询

### ISSUE THREAD

**Issue by zjkwdy** [nonebot/nonebot2#714]
**插件名称：**

天气查询

**插件功能：**

使用wttr.in的在线天气查询。

**PyPI 项目名：**

nonebot-plugin-weather-lite

**插件 import 包名：**

nonebot_plugin_weather_lite

**插件项目仓库/主页链接：**

https://github.com/zjkwdy/nonebot_plugin_weather_lite

**标签：**

[{"label":"t:天气","color":"#6ec3d9"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 天气查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: 天气-#ea5252</li><li>✅ 项目 <a href="https://github.com/zjkwdy/nonebot_plugin_weather_lite">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-weather-lite/">nonebot-plugin-weather-lite</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
不是你咋开了个新的

**Comment by yanyongyu** [comment]
直接修改就可以啊 重开一个干啥

**Comment by zjkwdy** [comment]
是我头脑发热一时草率了
