### ISSUE TITLE
Adapter: mirai2

### ISSUE THREAD

**Issue by ieew** [nonebot/nonebot2#717]
**协议名称：**

mirai2

**协议功能：**

为 nonebot2 添加 mirai_api_http2.x的兼容适配器

**PyPI 项目名：**

nonebot_adapter_mirai2

**协议 import 包名：**

nonebot.adapters.mirai2

**协议项目仓库/主页链接：**

https://github.com/ieew/nonebot_adapter_mirai2

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Adapter: mirai2

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/**协议 import 包名：**/">**协议 import 包名：**</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: mirai-#ea5252, mah2.x-#ea5252</li><li>✅ 项目 <a href="https://github.com/ieew/nonebot_adapter_mirai2">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
