### ISSUE TITLE
Plugin: nonebot_plugin_fortune

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#719]
**插件名称：**

nonebot_plugin_fortune

**插件功能：**

抽签！占卜一下你的今日运势

**PyPI 项目名：**

nonebot-plugin-fortune

**插件 import 包名：**

nonebot_plugin_fortune

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_fortune

**标签：**

[{"label":"a:cqhttp","color":"#6952ea"},{"label":"t:fortune","color":"#ea6f52"},{"label":"alpha only","color":"#181717"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_fortune

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#6952ea, t:fortune-#ea6f52, alpha only-#181717</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_fortune">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-fortune/">nonebot-plugin-fortune</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
