### ISSUE TITLE
Plugin: 塔罗牌

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#722]
**插件名称：**

塔罗牌

**插件功能：**

塔罗牌！占卜今日运势

**PyPI 项目名：**

nonebot-plugin-tarot

**插件 import 包名：**

nonebot_plugin_tarot

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_tarot

**标签：**

[{"label":"a:cqhttp","color":"#eaa452"},{"label":"t:tarot","color":"#461264"},{"label":"alpha only","color":"#b41f14"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 塔罗牌

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#eaa452, t:tarot-#461264, alpha only-#b41f14</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_tarot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tarot/">nonebot-plugin-tarot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
