### ISSUE TITLE
Plugin: emoji 合成器

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#725]
**插件名称：**

emoji 合成器

**插件功能：**

😎+😁=？

**PyPI 项目名：**

nonebot-plugin-emojimix

**插件 import 包名：**

nonebot_plugin_emojimix

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-emojimix

**标签：**

[{"label":"t:emoji","color":"#ea5252"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: emoji 合成器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:emoji-#ea5252</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-emojimix">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-emojimix/">nonebot-plugin-emojimix</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
