### ISSUE TITLE
Plugin: 今天吃什么

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#728]
**插件名称：**

今天吃什么

**插件功能：**

选择恐惧症？让Bot给你今天吃什么建议！

**PyPI 项目名：**

nonebot-plugin-what2eat

**插件 import 包名：**

nonebot_plugin_what2eat

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_what2eat

**标签：**

[{"label":"a:cqhttp","color":"#cd3d3d"},{"label":"t:what2eat","color":"#f09526"},{"label":"alpha only","color":"#181717"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 今天吃什么

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:cqhttp-#cd3d3d, t:what2eat-#f09526, alpha only-#181717</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_what2eat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-what2eat/">nonebot-plugin-what2eat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
