### ISSUE TITLE
Plugin: NoneBot 数据存储

### ISSUE THREAD

**Issue by he0119** [nonebot/nonebot2#733]
**插件名称：**

NoneBot 数据存储

**插件功能：**

提供简单的插件数据封装与数据库访问

**PyPI 项目名：**

nonebot-plugin-datastore

**插件 import 包名：**

nonebot_plugin_datastore

**插件项目仓库/主页链接：**

https://github.com/he0119/nonebot-plugin-datastore

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: NoneBot 数据存储

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/he0119/nonebot-plugin-datastore">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-datastore/">nonebot-plugin-datastore</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
