### ISSUE TITLE
Plugin: NoneBot的go-cqhttp启动器

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#735]
**插件名称：**

NoneBot的go-cqhttp启动器

**插件功能：**

一款在NoneBot2中直接运行go-cqhttp的插件, 无需额外下载安装

**PyPI 项目名：**

nonebot-plugin-gocqhttp

**插件 import 包名：**

nonebot_plugin_gocqhttp

**插件项目仓库/主页链接：**

https://github.com/mnixry/nonebot-plugin-gocqhttp

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:gocqhttp","color":"#eabd52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: NoneBot的go-cqhttp启动器

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:gocqhttp-#eabd52</li><li>✅ 项目 <a href="https://github.com/mnixry/nonebot-plugin-gocqhttp">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-gocqhttp/">nonebot-plugin-gocqhttp</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
