### ISSUE TITLE
Plugin: nonebot-general-rss

### ISSUE THREAD

**Issue by mobyw** [nonebot/nonebot2#738]
**插件名称：**

nonebot-general-rss

**插件功能：**

支持频道的通用RSS订阅插件

**PyPI 项目名：**

nonebot-general-rss

**插件 import 包名：**

nonebot-general-rss

**插件项目仓库/主页链接：**

https://github.com/mobyw/nonebot-general-rss

**标签：**

[{"label":"t:RSS","color":"#80070b"},{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-general-rss

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:RSS-#80070b, a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/mobyw/nonebot-general-rss">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-general-rss/">nonebot-general-rss</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
@mobyw onebot adapter 提供了Adapter.custom_model和Bot.cuatom_send大可不必patch

**Comment by j1g5awi** [comment]
以及，为啥你不给 ELF_RSS PR 而是自己上架插件

**Comment by mobyw** [comment]
> @mobyw onebot adapter 提供了Adapter.custom_model和Bot.custom_send大可不必patch

好的我去看一下，这个直接从a16适配过来的，就用了相同的方法

**Comment by mobyw** [comment]
> 以及，为啥你不给 ELF_RSS PR 而是自己上架插件。
> 
> 只是个疑问，fork 插件上架也是合理的。

需要保存来源以及主动推送，现在写的只能打补丁才能用，不用补丁的会整理下给原作者PR下（
