### ISSUE TITLE
Plugin: go-cqhttp 频道支持适配补丁

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#746]
**插件名称：**

go-cqhttp 频道支持适配补丁

**插件功能：**

NoneBot2的QQ频道(go-cqhttp协议)支持适配补丁插件

**PyPI 项目名：**

nonebot-plugin-guild-patch

**插件 import 包名：**

nonebot_plugin_guild_patch

**插件项目仓库/主页链接：**

https://github.com/mnixry/nonebot-plugin-guild-patch

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"t:gocqhttp","color":"#a2ea52"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: go-cqhttp 频道支持适配补丁

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, t:gocqhttp-#a2ea52</li><li>✅ 项目 <a href="https://github.com/mnixry/nonebot-plugin-guild-patch">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-guild-patch/">nonebot-plugin-guild-patch</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
