### ISSUE TITLE
Plugin: 棋类游戏

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#750]
**插件名称：**

棋类游戏

**插件功能：**

棋类游戏插件，目前支持 五子棋、黑白棋、围棋

**PyPI 项目名：**

nonebot-plugin-chess

**插件 import 包名：**

nonebot_plugin_chess

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-chess

**标签：**

[{"label":"t:chess","color":"#ea5252"},{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 棋类游戏

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:chess-#ea5252, a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-chess">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chess/">nonebot-plugin-chess</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
