### ISSUE TITLE
Plugin: 词云

### ISSUE THREAD

**Issue by he0119** [nonebot/nonebot2#753]
**插件名称：**

词云

**插件功能：**

根据群内聊天记录生成词云

**PyPI 项目名：**

nonebot-plugin-wordcloud

**插件 import 包名：**

nonebot_plugin_wordcloud

**插件项目仓库/主页链接：**

https://github.com/he0119/nonebot-plugin-wordcloud

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 词云

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/he0119/nonebot-plugin-wordcloud">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-wordcloud/">nonebot-plugin-wordcloud</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
