### ISSUE TITLE
Plugin: 聊天记录插件

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#757]
**插件名称：**

聊天记录插件

**插件功能：**

记录机器人收到和发出的消息

**PyPI 项目名：**

nonebot-plugin-chatrecorder

**插件 import 包名：**

nonebot_plugin_chatrecorder

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-chatrecorder

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 聊天记录插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-chatrecorder">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chatrecorder/">nonebot-plugin-chatrecorder</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
