### ISSUE TITLE
Plugin: random-cat

### ISSUE THREAD

**Issue by alphaAE** [nonebot/nonebot2#761]
**插件名称：**

random-cat

**插件功能：**

使用外网API随机发送猫猫狗狗图片，不在本地缓存，可选群启用

**PyPI 项目名：**

nonebot-plugin-random-cat

**插件 import 包名：**

nonebot_plugin_random_cat

**插件项目仓库/主页链接：**

https://github.com/NoneBot2-Ae/nonebot-plugin-random-cat

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: random-cat

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/NoneBot2-Ae/nonebot-plugin-random-cat">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-random-cat/">nonebot-plugin-random-cat</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
