### ISSUE TITLE
Plugin: 群聊反闪照

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#766]
**插件名称：**

群聊反闪照

**插件功能：**

顾名思义🎇

**PyPI 项目名：**

nonebot-plugin-antiflash

**插件 import 包名：**

nonebot_plugin_antiflash

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_antiflash

**标签：**

[{"label":"a:onebot","color":"#6f64d4"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 群聊反闪照

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#6f64d4</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_antiflash">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-antiflash/">nonebot-plugin-antiflash</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
