### ISSUE TITLE
Plugin: random_cat_gif

### ISSUE THREAD

**Issue by applenana** [nonebot/nonebot2#774]
**插件名称：**

random_cat_gif

**插件功能：**

无需魔法上网，无需图库的随机猫猫gif插件

**PyPI 项目名：**

random_cat_gif

**插件 import 包名：**

random_cat_gif

**插件项目仓库/主页链接：**

https://github.com/applenana/random_cat_gif

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: random_cat_gif

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/applenana/random_cat_gif">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/random_cat_gif/">random_cat_gif</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
