### ISSUE TITLE
Plugin: 无数据库的问答插件

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#776]
**插件名称：**

无数据库的问答插件

**插件功能：**

wordbank,但是重写了

**PyPI 项目名：**

nonebot-plugin-word-bank2

**插件 import 包名：**

nonebot_plugin_word_bank2

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-word-bank2

**标签：**

[{"label":"a:onebot","color":"#ff0000"},{"label":"wordbank","color":"#0b00ff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 无数据库的问答插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ff0000, wordbank-#0b00ff</li><li>✅ 项目 <a href="https://github.com/kexue-z/nonebot-plugin-word-bank2">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-word-bank2/">nonebot-plugin-word-bank2</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
