### ISSUE TITLE
Plugin: Fgo从者推理

### ISSUE THREAD

**Issue by suhexia** [nonebot/nonebot2#778]
**插件名称：**

Fgo从者推理

**插件功能：**

通过bot描述的从者特征，玩家对从者进行猜测的游戏

**PyPI 项目名：**

ServantReasoning

**插件 import 包名：**

nonebot_plugin_ServantReasoning

**插件项目仓库/主页链接：**

https://github.com/suhexia/ServantReasoningGame

**标签：**

[{"label":"t:game","color":"#ed9a41"},{"label":"a:gocqhttp","color":"#ed9a41"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Fgo从者推理

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:game-#ed9a41, a:gocqhttp-#ed9a41</li><li>✅ 项目 <a href="https://github.com/suhexia/ServantReasoningGame">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/ServantReasoning/">ServantReasoning</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
