### ISSUE TITLE
Bug: MessageTemplate 存在CQ码注入问题

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#781]
**描述问题：**

使用 Message.template 的 format 时可能存在CQ码注入问题

**如何复现？**

```python
>>> from nonebot.adapters.onebot.v11 import Message
>>> Message.template(Message("{nickname}是我老婆!")).format(nickname="[CQ:at,qq=all]")
[MessageSegment(type='at', data={'qq': 'all'}), MessageSegment(type='text', data={'text': '是我老婆!'})]
```

**期望的结果**

上面的例子中，`"[CQ:at,qq=all]"` 应被解析为文本，而不是 `at` 类型

**环境信息：**

 - OS: Linux Ubuntu 20.04
 - Python Version: 3.8.10
 - Nonebot Version: 2.0.0b1

**截图或日志**

![Snipaste_2022-02-09_16-03-35.png](https://s2.loli.net/2022/02/09/IO76rTnLsAfuHjZ.png)

**Comment by yanyongyu** [comment]
fixed in #782
