### ISSUE TITLE
Plugin: 轻量文字转图片插件

### ISSUE THREAD

**Issue by mobyw** [nonebot/nonebot2#783]
**插件名称：**

轻量文字转图片插件

**插件功能：**

基于PIL的轻量文字转图片插件

**PyPI 项目名：**

nonebot-plugin-txt2img

**插件 import 包名：**

nonebot_plugin_txt2img

**插件项目仓库/主页链接：**

https://github.com/mobyw/nonebot-plugin-txt2img

**标签：**

[{"label":"a:onebot","color":"#0083ff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 轻量文字转图片插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#0083ff</li><li>✅ 项目 <a href="https://github.com/mobyw/nonebot-plugin-txt2img">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-txt2img/">nonebot-plugin-txt2img</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
