### ISSUE TITLE
Plugin: おはよう！

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#787]
**插件名称：**

おはよう！

**插件功能：**

早晚安记录作息，培养优质睡眠😴

**PyPI 项目名：**

nonebot-plugin-morning

**插件 import 包名：**

nonebot_plugin_morning

**插件项目仓库/主页链接：**

https://github.com/KafCoppelia/nonebot_plugin_morning

**标签：**

[{"label":"a:onebot","color":"#da421c"},{"label":"t:morning","color":"#ebc025"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: おはよう！

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#da421c, t:morning-#ebc025</li><li>✅ 项目 <a href="https://github.com/KafCoppelia/nonebot_plugin_morning">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-morning/">nonebot-plugin-morning</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
