### ISSUE TITLE
Docs: NoneBot2文档改进计划

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#793]
# NoneBot2文档改进计划

Related: #3 ~~#372~~

## 描述问题或主题

NoneBot2文档由于一些原因~~主要是我们语文太菜~~，它的撰写方法存在各种问题，对新手的理解和使用造成了困难。
我们在这里希望对NoneBot现有的文档结构作出一点改进。

但是这不是我们几位开发者能够完成的。
我们都是普通人，在完成学习和工作之余维护项目代码和文档，实在感觉有些分身乏术。

**我们衷心希望，看到这个issue的每一个人，都为这个文档，作出一份自己的贡献。**
**而一份好的文档，需要你们每个人的帮助。**

<details>
<summary>不太正经的话</summary>

- 我写这么多，要是没人来做我好尴尬啊……
- ![image](https://user-images.githubusercontent.com/32300164/153769358-6a4a8130-6469-4317-9e76-5e2bd9098a29.png)
- ~~来贡献文档，领NoneBot周边~~这个我得问问RC……也没决定要做啥

</details>

## 需作出的修改

> 我在这里提供一个列表，包含了我个人在阅读文档过程中发现的一些问题
大家可以在Issue下方补充自己的见解，我会加到下面的这个列表中
如果各位看到这里面的一些问题自己有能力解决，可以向我们提交PR进行修改。

* [ ] 更新文档中的所有asciinema示例
* [x]  在文档开篇介绍NoneBot的组成部分（Adapter，Driver，Plugin...）
	- 这部分不用特别详细，因为进阶会详细讲事件处理流程这里
* [x] 在安装方式一节给出最推荐的一种
	* [x] 添加一个使用Conda作为虚拟环境管理工具使用nb-cli的教程
		- 因为它在各种平台上算是比较好装的，也比较适合nb-cli的操作需要
	- 是不是应该把给只使用插件的用户的教程放在这里？
* [x] 把使用脚手架移到教程一节，将教程以脚手架创建的项目结构为核心展开
	* [x] 引导式教程，分步骤，第一步创建项目，第二部选择驱动器/注册适配器 这样的
	* [x] 创建插件一步从脚手架命令开始，讲解创建插件的文件结构，引入Python包的概念
	* [x] 简化加载插件一节，将各种加载插件方式移动到API参考部分
		- 加一条警告，不要随便动`bot.py`，除非你知道你在干啥
	* [x] 详细化定义插件配置一节，加几个常见字段类型的示例，并且告诉开发者，插件配置应该从哪载入，什么时候实例化
		- 结合脚手架创建的文件结构(`config.py`)进行讲解
	* [x] 定义事件响应器部分，应该先解释会话的概念
		* [x] 权限控制这里可以直接说，为了可复用的控制一个事件能否被响应，我们提供了两种解决方案，然后打个表格做对比 
		* [x] 创建事件响应器，这个地方给例子比较好（比如教用户自己写个echo？），然后具体有哪些扔API文档
	* [x] 定义事件处理流程，把`got`和`receive`位置换一下，最好给一个例子做对比
		* [x] 获取上下文信息这一步可以开始提及简单的依赖注入了，给个例子，说明一些依赖是怎样声明的
			- 具体有哪些依赖就不用报菜名了，直接扔API文档链接
	* [x] 删除事件响应器操作一节，补全API相关部分，直接扔链接
	* [x] 优化插件示例一节，按照上面的步骤，构建一个插件应该被打散成了很多步，这里需要给所有文件做个总结，然后可以提一些高阶的东西
	* [x] 移动自定义日志一节到进阶，因为开发入门似乎用不到
* [x] 将钩子函数一节和进阶首页工作原理篇合并，在讲解工作原理的时候标示出各个钩子的运行时机，给个API文档链接即可
* [x] 跨插件访问，加上直接`import`这一种方法，讲明什么时候该`require`，什么时候直接`import`就行
* [x] 权限控制，这个地方想要表达的本质就是`PERMISSION`是一个`(bot,event)->Awaitable[bool]`，可以改一下表述方式
* [x] 移动发布插件到进阶最后，让用户在发布插件前就对NoneBot有一个完整的了解
* [x] 删除定时任务的从NoneBot v1迁移一节
	* [x] 尝试修改`scheduler`插件为可以直接import的版本
* [ ] 添加可执行示例

如果对以上部分有任何疑问，也可以在官方交流群里面直接联系我们

---

**最后，在这里感谢你们对NoneBot社区作出的贡献！**

**Comment by dlkong194** [comment]
事件响应器操作

**Comment by yanyongyu** [comment]
dotenv以及环境变量配置的地方需要明确配置项的存在条件，需要dotenv文件中存在的配置项才会从环境变量读取 (#1575 )

**Comment by shikukuya** [comment]
![image](https://user-images.githubusercontent.com/89395757/214236026-05b53940-89bd-4675-99d6-fd2b853178e1.png)

这里代码块我觉得用plain更好
