### ISSUE TITLE
Docs: 移除商店中的过期插件

### ISSUE THREAD

**Issue by j1g5awi** [nonebot/nonebot2#795]
# 移除商店中的过期插件

不知不觉 NoneBot2 已经进入 beta 一个多月，值此 beta2 版本发布之际，我们计划将插件商店中仍未适配 beta 更新的插件移除，在此处列出名单以告知作者，如有错误请回复。

### Git 已适配但未在 PyPI 发版（Warning）

[nonebot-plugin-setu](https://github.com/ayanamiblhx/nonebot_plugin_setu) @ayanamiblhx
[nonebot-plugin-filehost](https://github.com/mnixry/nonebot-plugin-filehost) @mnixry
[nonebot-plugin-leetcode](https://github.com/zxz0415/leetcode) @zxz0415
[nonebot-plugin-picsbank](https://github.com/Diaosi1111/nonebot_plugin_picsbank) @Diaosi1111

### 依赖问题

- [ ] [nonebot-plugin-wordbank](https://github.com/Joenothing-lst/word-bank) @Joenothing-lst GitHub 仓库里没有 setup.py 或 pyproject.toml 
- [ ] [nonebot-plugin-fr24](https://github.com/IronWolf-K/nonebot_plugin_fr24) @IronWolf-K
- [x] [nonebot-plugin-imgsearch](https://github.com/bakashigure/nonebot_plugin_imgsearch) @bakashigure
- [x] [nonebot-plugin-itnew](https://github.com/yzyyz1387/nonebot_plugin_itnews) @yzyyz1387
- [x] [lolHeroes](https://github.com/cjladmin/lolheroes) @cjladmin
- [x] [nonebot-plugin-random-cat](https://github.com/NoneBot2-Ae/nonebot-plugin-random-cat) @alphaAE
- [ ] [random_cat_gif](https://github.com/applenana/random_cat_gif) @applenana GitHub 仓库里没有 setup.py 或 pyproject.toml 
- [x] [ServantReasoning](https://github.com/suhexia/ServantReasoningGame) @suhexia
- [ ] [nonebot-plugin-anime-news](https://github.com/5656565566/anime_news) @5656565566 仓库里没有 setup.py 或 pyproject.toml
- [x] [nonebot-pulgin-autoagree](https://github.com/ZakiuC/NoneBot_Pulgin_AutoAgree) @ZakiuC
- [x] [nonebot-plugin-fg](https://github.com/mgsky1/FG-plugin) @mgsky1
- [ ] [nonebot-mockingbird-plugin](https://github.com/Diaosi1111/nonebot_mockingbird_plugin) @Diaosi1111

#### beta2 `Config` 问题

[nonebot-plugin-pixivrank-search](https://github.com/HibiKier/nonebot_plugin_pixivrank_search) @HibiKier 
[nonebot-plugin-heisi](https://github.com/yzyyz1387/nonebot_plugin_heisi) @yzyyz1387
[nonebot-plugin-admin](https://github.com/yzyyz1387/nonebot_plugin_admin) @yzyyz1387

#### 其他

[nonebot-plugin-vf](https://github.com/snowyfirefly/VirtualFriends) @snowyfirefly 代码未托管在 GitHub，懒得管

### 待删除

[nonebot-plugin-test](https://github.com/nonebot/plugin-test) @yanyongyu
[nonebot-plugin-web](https://github.com/abrahum/nonebot_plugin_web) @abrahum
[nonebot-plugin-ipypreter](https://github.com/iyume/nonebot-plugin-ipypreter) @iyume
[nonebot-plugin-arcaea](https://github.com/iyume/nonebot-plugin-arcaea) @iyume
[nonebot-plugin-statistical](https://github.com/HibiKier/nonebot_plugin_statistical) @HibiKier
[nonebot-plugin-workscore](https://github.com/yzyyz1387/nonebot_plugin_workscore) @yzyyz1387
[nonebot-plugin-nokia](https://github.com/kexue-z/nonebot-plugin-nokia) @kexue-z
[nonebot-plugin-pctrl](https://github.com/CherryGS/nonebot_plugin_PCtrl) @CherryGS

### 已删除

[nonebot-plugin-hanayori](https://github.com/kanomahoro/nonebot-hanayori) @kanomahoro 
[nonebot-plugin-simplemusic](https://github.com/kanomahoro/nonebot-simplemusic) @kanomahoro
[nonebot-plugin-twitter](https://github.com/kanomahoro/nonebot-twitter) @kanomahoro

## 数据来源

[Lancercmd/nonebot2-store-test](https://github.com/Lancercmd/nonebot2-store-test)

**Comment by kexue-z** [comment]
- [nonebot-plugin-word-bank2](https://github.com/kexue-z/nonebot-plugin-word-bank2) `v0.1.1`已经适配 beta1, 并在pypi发版
- [nonebot-plugin-tvseries](https://github.com/kexue-z/nonebot-plugin-tvseries) `v0.0.2.3` 已经适配 beta1, 并在pypi发版
- [nonebot-plugin-phlogo](https://github.com/kexue-z/nonebot-plugin-phlogo) `v0.0.2` 已经适配 beta1, 并在pypi发版
----
- [nonebot-plugin-nokia](https://github.com/kexue-z/nonebot-plugin-nokia) 可以作为新手教材吗?

**Comment by kitUIN** [comment]
- [nonebot-plugin-ncm](https://github.com/kitUIN/nonebot_tools/tree/master/nonebot_tools/nonebot-plugin-ncm) `v1.2.3` 已经适配 beta1, 并在pypi发版

**Comment by j1g5awi** [comment]
>     * [nonebot-plugin-nokia](https://github.com/kexue-z/nonebot-plugin-nokia) 可以作为新手教材吗?

不在此 Issue 讨论范围。

**Comment by mgsky1** [comment]
- [x] [nonebot-plugin-fg](https://github.com/mgsky1/FG-plugin)v2.0.2已适配beta版本，在github的README已说明

**Comment by mgsky1** [comment]
> > [nonebot-plugin-fg](https://github.com/mgsky1/FG-plugin)v2.0.2已适配beta版本，在github的README已说明
> 
> 请依赖 nonebot-plugin-apscheduler

已更新README

**Comment by synodriver** [comment]
[nonebot-plugin-picsearcher](https://github.com/synodriver/nonebot_plugin_picsearcher) 已经更新

**Comment by Zeta-qixi** [comment]
[nonebot-plugin-covid19-news](https://github.com/Zeta-qixi/nonebot-plugin-covid19-news)v0.2.2.4 已支持beta版本

**Comment by ninthseason** [comment]
- [x] [nonebot-plugin-repeater](https://github.com/ninthseason/nonebot-plugin-repeater)
- [x] [nonebot-plugin-directlinker](https://github.com/ninthseason/nonebot-plugin-directlinker) 
- [x] [nonebot-plugin-forwarder](https://github.com/ninthseason/nonebot_plugin_forwarder)

均已支持beta版本并已经发布

**Comment by abrahum** [comment]
- [ ] [nonebot-plugin-web](https://github.com/abrahum/nonebot_plugin_web) 不会支持 beta1 请移除 ~~黑历史~~
- [x] [nonebot-plugin-cocdicer](https://github.com/abrahum/nonebot_plugin_cocdicer) 0.3.1 已支持 beta1 并发版
- [x] [nonebot-plugin-r6s](https://github.com/abrahum/nonebot_plugin_r6s) 0.4.1 已支持 beta1 并发版

**Comment by knva** [comment]
[nonebot_plugin_biliav](https://github.com/knva/nonebot_plugin_biliav) @knva 已适配并已发布pipy

**Comment by anlen123** [comment]
- [ ] [nonebot_plugin_abbrreply](https://github.com/anlen123/nonebot_plugin_abbrreply) 已适配并已发布pipy

**Comment by j1g5awi** [comment]
> [nonebot-plugin-picsearcher](https://github.com/synodriver/nonebot_plugin_picsearcher)0.1.6rc2 已经支持beta版本并已经发布

你是不是没有依赖 NoneBot2 和 Adapter

**Comment by j1g5awi** [comment]
> [nonebot-plugin-repeater](https://github.com/ninthseason/nonebot-plugin-repeater)
> [nonebot-plugin-directlinker](https://github.com/ninthseason/nonebot-plugin-directlinker)
> [nonebot-plugin-forwarder](https://github.com/ninthseason/nonebot_plugin_forwarder)

请依赖 NoneBot2 和 Adapter

**Comment by j1g5awi** [comment]
> [nonebot_plugin_biliav](https://github.com/knva/nonebot_plugin_biliav) @knva 已适配并已发布pipy

请依赖 NoneBot2 和 Adapter

**Comment by j1g5awi** [comment]
> > > [nonebot-plugin-fg](https://github.com/mgsky1/FG-plugin)v2.0.2已适配beta版本，在github的README已说明
> > 
> > 
> > 请依赖 nonebot-plugin-apscheduler
> 
> 已更新README

我指的是你的项目依赖，你改 README 干啥

**Comment by rmuchan** [comment]
- [ ] [nonebot-plugin-flexperm](https://github.com/rmuchan/nonebot-plugin-flexperm) 已适配beta并发版

**Comment by HibiKier** [comment]
[nonebot-plugin-pixivrank-search](https://github.com/HibiKier/nonebot_plugin_pixivrank_search) @HibiKier
[nonebot-plugin-russian](https://github.com/HibiKier/nonebot_plugin_russian) @HibiKier
[nonebot-plugin-statistical](https://github.com/HibiKier/nonebot_plugin_statistical) @HibiKier
全部适配且发版

**Comment by knva** [comment]
> 

[nonebot_plugin_biliav](https://github.com/knva/nonebot_plugin_biliav) @knva 已经添加依赖并测试.

**Comment by j1g5awi** [comment]
> [nonebot-plugin-pixivrank-search](https://github.com/HibiKier/nonebot_plugin_pixivrank_search) @HibiKier
> [nonebot-plugin-statistical](https://github.com/HibiKier/nonebot_plugin_statistical) @HibiKier

检查下这两个插件的 config 属性调用

**Comment by KafCoppelia** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            https://github.com/KafCoppelia/nonebot_plugin_fortune 插件已发布最新版，适配b1且pypi已发行
    
    
     
    
        
                    ***@***.***
        
    
 

    On 2/14/2022 ***@***.***> wrote： 




移除商店中的过期插件

不知不觉 NoneBot2 已经进入 beta 一个多月，值此 beta2 版本发布之际，我们计划将插件商店中仍未适配 beta 更新的插件移除，在此列出名单以告知作者，如有错误请在此 Issue 回复。

列表

Git 已适配但未在 PyPI 发版（Warning）

nonebot-plugin-filehost @mnixry

nonebot-plugin-tvseries @kexue-z

nonebot-plugin-fortune @KafCoppelia

nonebot-plugin-word-bank2 @kexue-z

未适配

nonebot-plugin-test @yanyongyu

nonebot-plugin-picsearcher @synodrivernonebot-plugin-web @abrahum

nonebot-plugin-wordbank @Joenothing-lst

nonebot-plugin-ipypreter @iyume

nonebot-plugin-arcaea @iyume

nonebot-plugin-ncm @kitUIN

nonebot-plugin-cocdicer @abrahum

nonebot-plugin-r6s @abrahum

nonebot-plugin-guess @ffreemt

nonebot_plugin_abbrreply @anlen123

nonebot_plugin_biliav @knva

nonebot-plugin-pixivrank-search @HibiKier

nonebot-plugin-russian @HibiKier

nonebot-plugin-statistical @HibiKier

nonebot_plugin_setu @ayanamiblhx

nonebot-plugin-fr24 @IronWolf-K

nonebot-plugin-autohelp @ffreemt

nonebot-plugin-flexperm @rmuchan

nonebot_plugin_epicfree @monsterxcn

nonebot-plugin-hanayori @kanomahoro

nonebot-plugin-simplemusic @kanomahoro

nonebot-plugin-phlogo @kexue-z

nonebot-plugin-twitter @kanomahoro

nonebot-plugin-leetcode @zxz0415

nonebot-plugin-imgsearch @bakashigure

nonebot-plugin-itnew @yzyyz1387

lolHeroes @cjladmin

nonebot-plugin-youthstudy @ayanamiblhx

gocqapi @FYWinds

nonebot-plugin-workscore @yzyyz1387

nonebot-plugin-nokia @kexue-z

nonebot-plugin-vf @snowyfirefly

nonebot-plugin-picsbank @Diaosi1111

nonebot-plugin-lolmatch @Diaosi1111

nonebot-plugin-repeater @ninthseason

nonebot-plugin-pctrl @CherryGS

nonebot-plugin-directlinker @ninthseason

nonebot-plugin-forwarder @ninthseason

nonebot-plugin-covid19-news @Zeta-qixi

nonebot-plugin-fg @mgsky1

nonebot-plugin-random-cat @alphaAE

random_cat_gif @applenana

ServantReasoning @suhexia

**Comment by j1g5awi** [comment]
@KafCoppelia 检查下该插件的 config 属性调用

PS：你的邮件客户端似乎会导致网页端看到一团乱码

**Comment by j1g5awi** [comment]
## 对于 Config 的建议

如果您的插件有必须手动填写的配置项，请在获取该配置项失败时抛出一个具有提醒性质的 Exception

如果您的插件提供默认配置，请使用 `hasattr()` 函数检测用户是否填写或自定义 Config 类

**Comment by KafCoppelia** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    已更正在0.4.1，pypi已发行 https://github.com/KafCoppelia/nonebot_plugin_fortune刚收到最新的关于修改意见，后续版本会改进
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 2/15/2022 ***@***.***> wrote： 




@KafCoppelia 检查下该插件的 config 属性调用

PS：你的邮件客户端似乎会导致网页端看到一团乱码

**Comment by synodriver** [comment]
> > [nonebot-plugin-picsearcher](https://github.com/synodriver/nonebot_plugin_picsearcher)0.1.6rc2 已经支持beta版本并已经发布
> 
> 你是不是没有依赖 NoneBot2 和 Adapter

已经修改，0.1.6正式版已经发布

**Comment by monsterxcn** [comment]
[nonebot-plugin-epicfree](https://github.com/monsterxcn/nonebot_plugin_epicfree) [0.1.7](https://pypi.org/project/nonebot-plugin-epicfree/#history) 已适配 beta2

**Comment by bingganhe123** [comment]
已补全



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月17日(周四) 中午1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [nonebot/nonebot2] Docs: 移除商店中的过期插件 (Issue #795)




 
移除商店中的过期插件
 
不知不觉 NoneBot2 已经进入 beta 一个多月，值此 beta2 版本发布之际，我们计划将插件商店中仍未适配 beta 更新的插件移除，在此处列出名单以告知作者，如有错误请回复。
 
列表
 
Git 已适配但未在 PyPI 发版（Warning）
 
nonebot-plugin-filehost @mnixry
 nonebot-plugin-fortune @KafCoppelia
 
未适配
 
nonebot-plugin-test @yanyongyu
 nonebot-plugin-web @abrahum
 nonebot-plugin-wordbank @Joenothing-lst
 nonebot-plugin-ipypreter @iyume
 nonebot-plugin-arcaea @iyume
 nonebot-plugin-guess @ffreemt
 nonebot-plugin-pixivrank-search @HibiKier
 nonebot-plugin-statistical @HibiKier
 nonebot_plugin_setu @ayanamiblhx
 nonebot-plugin-fr24 @IronWolf-K
 nonebot-plugin-autohelp @ffreemt
 nonebot-plugin-hanayori @kanomahoro
 nonebot-plugin-simplemusic @kanomahoro
 nonebot-plugin-twitter @kanomahoro
 nonebot-plugin-leetcode @zxz0415
 nonebot-plugin-imgsearch @bakashigure
 nonebot-plugin-itnew @yzyyz1387
 lolHeroes @cjladmin
 nonebot-plugin-youthstudy @ayanamiblhx
 nonebot-plugin-workscore @yzyyz1387
 nonebot-plugin-nokia @kexue-z
 nonebot-plugin-vf @snowyfirefly
 nonebot-plugin-picsbank @Diaosi1111
 nonebot-plugin-lolmatch @Diaosi1111
 nonebot-plugin-repeater @ninthseason
 nonebot-plugin-pctrl @CherryGS
 nonebot-plugin-directlinker @ninthseason
 nonebot-plugin-forwarder @ninthseason
 nonebot-plugin-fg @mgsky1
 nonebot-plugin-random-cat @alphaAE
 random_cat_gif @applenana
 ServantReasoning @suhexia
 nonebot-plugin-read-60s @bingganhe123
 
数据来源
 
Lancercmd/nonebot2-store-test

**Comment by j1g5awi** [comment]
> 已补全

是依赖不是开发依赖

**Comment by j1g5awi** [comment]
> > > 已补全
> > 
> > 
> > 是依赖不是开发依赖
> 
> 抱歉，已进行修改并上传

还是有问题，你可以去看看那些未在此名单的插件。

**Comment by KafCoppelia** [comment]
- [x] nonebot-plugin-crazy-thursday
- [x] nonebot-plugin-tarot
- [ ] nonebot-plugin-fortune
- [x] nonebot-plugin-what2eat
- [ ] nonebot-plugin-morning
- [ ] nonebot-plugin-antiflash

已适配且发版

**Comment by j1g5awi** [comment]
@KafCoppelia nonebot-plugin-morning、nonebot-plugin-what2eat 缺少 requests 的依赖

**Comment by ayanamiblhx** [comment]
[nonebot_plugin_setu](https://github.com/ayanamiblhx/nonebot_plugin_setu)
[nonebot-plugin-youthstudy](https://github.com/ayanamiblhx/nonebot_plugin_youthstudy)
已适配beta2并发版

**Comment by iyume** [comment]
nonebot-plugin-ipypreter 请移除
nonebot-plugin-arcaea 请移除

**Comment by TDK1969** [comment]
- [x] [nonebot-plugin-bilibilibot 1.1](https://github.com/TDK1969/nonebot_plugin_bilibilibot)已适配v2.0.0-beta.2并发布到pypi

**Comment by TDK1969** [comment]
> @TDK1969 没有适配器的依赖

已在README.md中添加

**Comment by Nranphy** [comment]
- [x] [nonebot_plugin_leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2)已适配v2.0.0-beta.2并已发布

**Comment by ayanamiblhx** [comment]
> @ayanamiblhx 你的插件压根就没写依赖啊

已添加并在pypi发版

**Comment by mwbimh** [comment]
[nonebot-plugin-broker](https://github.com/mwbimh/nonebot_plugin_broker) @mwbimh 已添加依赖并发布

**Comment by SEAFHMC** [comment]
[nonebot-plugin-arcaeabot](https://github.com/SEAFHMC/nonebot-plugin-arcaeabot)已适配v2.0.0-beta.2并发布到pypi

**Comment by CherryCherries** [comment]
[[nonebot-plugin-abstract](https://github.com/CherryCherries/nonebot-plugin-abstract) @CherryCherries 已适配v2.0.0-beta.2并发布到PyPI

**Comment by CherryCherries** [comment]
[nonebot-plugin-abstract](https://github.com/CherryCherries/nonebot-plugin-abstract) @CherryCherries 已适配v2.0.0-beta.2并发布到PyPI

**Comment by j1g5awi** [comment]
@TDK1969 让你往包里写，你写 README 干啥
@Nranphy @SEAFHMC 算你们过了，`Config` 问题请看 https://github.com/nonebot/nonebot2/issues/795#issuecomment-1040024378
@ayanamiblhx 你咋把 NoneBot 1 和 2 都给依赖了
@mwbimh ✅
@CherryCherries PyPI 包里依旧没有依赖

**Comment by ayanamiblhx** [comment]
> @TDK1969 让你往包里写，你写 README 干啥 @Nranphy @SEAFHMC 算你们过了，`Config` 问题请看 [#795 (comment)](https://github.com/nonebot/nonebot2/issues/795#issuecomment-1040024378) @ayanamiblhx 你咋把 NoneBot 1 和 2 都给依赖了 @mwbimh ✅ @CherryCherries PyPI 包里依旧没有依赖

已删除nb1

**Comment by TDK1969** [comment]
> > @TDK1969 让你往包里写，你写 README 干啥 @Nranphy @SEAFHMC 算你们过了，`Config` 问题请看 [#795 (comment)](https://github.com/nonebot/nonebot2/issues/795#issuecomment-1040024378) @ayanamiblhx 你咋把 NoneBot 1 和 2 都给依赖了 @mwbimh ✅ @CherryCherries PyPI 包里依旧没有依赖
> 
> 已删除nb1

抱歉，已在包里修改并发布至pypi

**Comment by CherryCherries** [comment]
> @TDK1969 让你往包里写，你写 README 干啥 @Nranphy @SEAFHMC 算你们过了，`Config` 问题请看 [#795 (comment)](https://github.com/nonebot/nonebot2/issues/795#issuecomment-1040024378) @ayanamiblhx 你咋把 NoneBot 1 和 2 都给依赖了 @mwbimh ✅ @CherryCherries PyPI 包里依旧没有依赖

[nonebot-plugin-abstract](https://github.com/CherryCherries/nonebot-plugin-abstract) 已发布到PyPI

**Comment by 25252www** [comment]
@j1g5awi [nonebot_plugin_fire](https://github.com/25252www/nonebot_plugin_fire)已适配beta2并发版

**Comment by j1g5awi** [comment]
依赖没写全的插件这几天我会去挨个 PR，请注意查收。

`Config` 有问题的插件本次暂且放过，自己看 https://github.com/nonebot/nonebot2/issues/795#issuecomment-1040024378 要怎么改。

其余的未适配插件以及对上面的 PR 不做回应的插件，清明节（4 月 5 日）当天删除。

**Comment by Nranphy** [comment]
[nonebot_plugin_leetcode2](https://github.com/Nranphy/nonebot_plugin_leetcode2) 1.0.5 已修改Config相关问题并已发布。

**Comment by 25252www** [comment]
@j1g5awi [nonebot_plugin_fire](https://github.com/25252www/nonebot_plugin_fire) 已接受PR，完善Config并发版

**Comment by SEAFHMC** [comment]
[nonebot-plugin-arcaeabot](https://github.com/SEAFHMC/nonebot-plugin-arcaeabot) Config已更改（不知道是不是这样改

**Comment by monsterxcn** [comment]
- [x] [nonebot-plugin-color](https://github.com/monsterxcn/nonebot-plugin-color/tree/a8feb3b5adefdf60f8db56acdd865ff16b5163ba) [0.1.1](https://pypi.org/project/nonebot-plugin-color/0.1.1/) 已适配

（@j1g5awi 佬辛苦了😘

**Comment by j1g5awi** [comment]
@ninthseason `hasattr` 不是这样用的。
