### ISSUE TITLE
Plugin: pixiv.net p站查询图片

### ISSUE THREAD

**Issue by anlen123** [nonebot/nonebot2#801]
**插件名称：**

pixiv.net p站查询图片

**插件功能：**

pixiv.net p站查询图片(支持动图和多图)

**PyPI 项目名：**

nonebot-plugin-pixiv

**插件 import 包名：**

nonebot_plugin_pixiv

**插件项目仓库/主页链接：**

https://github.com/anlen123/nonebot_plugin_pixiv

**标签：**
[{"label": "t: pixiv","color": "#0096fa"},{"label": "R18","color": "#ffff00"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: pixiv.net p站查询图片

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 标签解码失败。<dt>请确保标签格式正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/anlen123/nonebot_plugin_pixiv">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-pixiv/">nonebot-plugin-pixiv</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
