### ISSUE TITLE
Plugin: 60s读世界小插件

### ISSUE THREAD

**Issue by bingganhe123** [nonebot/nonebot2#808]
**插件名称：**

60s读世界小插件

**插件功能：**

定时向指定群或列表好友发送每日60s读世界

**PyPI 项目名：**

nonebot-plugin-read-60s 0.1.5

**插件 import 包名：**

nonebot_plugin_read_60s

**插件项目仓库/主页链接：**

https://github.com/bingganhe123/60s-

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 60s读世界小插件

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot-plugin-read-60s 0.1.5/">nonebot-plugin-read-60s 0.1.5</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/bingganhe123/60s-">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
