### ISSUE TITLE
Plugin: YetAnotherPicSearch

### ISSUE THREAD

**Issue by NekoAria** [nonebot/nonebot2#824]
**插件名称：**

YetAnotherPicSearch

**插件功能：**

基于 kitUIN/PicImageSearch 的另一个 Nonebot 搜图插件。

**PyPI 项目名：**

yetanotherpicsearch

**插件 import 包名：**

YetAnotherPicSearch

**插件项目仓库/主页链接：**

https://github.com/NekoAria/YetAnotherPicSearch

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: YetAnotherPicSearch

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/NekoAria/YetAnotherPicSearch">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/yetanotherpicsearch/">yetanotherpicsearch</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
