### ISSUE TITLE
Feature: 接收用户私聊发来的文件

### ISSUE THREAD

**Issue by fslongjin** [nonebot/nonebot2#833]
**是否在使用中遇到某些问题而需要新的特性？请描述：
我希望开发一个班级文件收集机器人，希望能够支持私聊文件接收。

**描述你所需要的特性：**
支持接收私聊文件

**Comment by yanyongyu** [comment]
请阅读说明 https://github.com/nonebot/nonebot2#%E4%BB%80%E4%B9%88%E4%B8%8D%E6%98%AF-nonebot2

是否具有平台的某个功能与nonebot无关，请前往对应平台提出需求
