### ISSUE TITLE
Plugin: mockingbird

### ISSUE THREAD

**Issue by Diaosi1111** [nonebot/nonebot2#840]
**插件名称：**

mockingbird

**插件功能：**

简单使用mockingbird让机器人讲话

**PyPI 项目名：**

nonebot-mockingbird-plugin

**插件 import 包名：**

nonebot_mockingbird_plugin

**插件项目仓库/主页链接：**

https://github.com/Diaosi1111/nonebot_mockingbird_plugin

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: mockingbird

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Diaosi1111/nonebot_mockingbird_plugin">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_mockingbird-plugin/">nonebot_mockingbird-plugin</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
