### ISSUE TITLE
Plugin: 二维码识别与发送

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#842]
**插件名称：**

二维码识别与发送

**插件功能：**

qq聊天二维码插件

**PyPI 项目名：**

nonebot-plugin-qrcode

**插件 import 包名：**

nonebot_plugin_qrcode

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-qrcode

**标签：**

[{"label":"a:onebot","color":"#ea5252"},{"label":"QRcode","color":"#0020ff"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 二维码识别与发送

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot-plugin-qrcode/">nonebot-plugin-qrcode</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#ea5252, QRcode-#0020ff</li><li>✅ 项目 <a href="https://github.com/kexue-z/nonebot-plugin-qrcode">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by kexue-z** [comment]
发布了ruuaaaaa
