### ISSUE TITLE
Plugin: 番剧新闻

### ISSUE THREAD

**Issue by 5656565566** [nonebot/nonebot2#849]
**插件名称：**

番剧新闻

**插件功能：**

从bangumi.moe定时获取番剧信息

**PyPI 项目名：**

nonebot-plugin-anime-news

**插件 import 包名：**

nonebot_plugin_anime_news

**插件项目仓库/主页链接：**

https://github.com/5656565566/anime_news

**标签：**

[{"label":"bangumi","color":"#761aab"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 番剧新闻

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/https://pypi.org/project/nonebot-plugin-anime-news/1.0.0//">https://pypi.org/project/nonebot-plugin-anime-news/1.0.0/</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 标签: bangumi-#761aab</li><li>✅ 项目 <a href="https://github.com/5656565566/anime_news">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by 5656565566** [comment]
> **插件名称：**
> 
> 番剧新闻
> 
> **插件功能：**
> 
> 从bangumi.moe定时获取番剧信息
> 
> **PyPI 项目名：**
> 
> nonebot-plugin-anime-news
> 
> **插件 import 包名：**
> 
> nonebot_plugin_anime_news
> 
> **插件项目仓库/主页链接：**
> 
> https://github.com/5656565566/anime_news
> 
> **标签：**
> 
> [{"label":"bangumi","color":"#761aab"}]
