### ISSUE TITLE
Plugin: 动漫新闻

### ISSUE THREAD

**Issue by 5656565566** [nonebot/nonebot2#851]
**插件名称：**

动漫新闻

**插件功能：**

一个简易的获取来自 bangumi.moe 番剧时间表的插件

**PyPI 项目名：**

nonebot-plugin-anime-news

**插件 import 包名：**

nonebot_plugin_anime_news

**插件项目仓库/主页链接：**

https://github.com/5656565566/anime_news

**标签：**

[{"label":"bangumi","color":"#aa52ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 动漫新闻

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: bangumi-#aa52ea</li><li>✅ 项目 <a href="https://github.com/5656565566/anime_news">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_anime_news/">nonebot_plugin_anime_news</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
