### ISSUE TITLE
Plugin: 订阅推送管理

### ISSUE THREAD

**Issue by mwbimh** [nonebot/nonebot2#854]
**插件名称：**

订阅推送管理

**插件功能：**

一个简化编写订阅和推送功能的插件，也支持插件间信息交互

**PyPI 项目名：**

nonebot-plugin-broker

**插件 import 包名：**

nonebot_plugin_broker

**插件项目仓库/主页链接：**

https://github.com/mwbimh/nonebot_plugin_broker

**标签：**

[{"label":"a:onebot","color":"#a11313"},{"label":"t:发布/订阅","color":"#1373a1"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 订阅推送管理

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#a11313, t:发布/订阅-#1373a1</li><li>✅ 项目 <a href="https://github.com/mwbimh/nonebot_plugin_broker">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-broker/">nonebot-plugin-broker</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
