### ISSUE TITLE
Plugin: bilibili通知插件

### ISSUE THREAD

**Issue by TDK1969** [nonebot/nonebot2#858]
**插件名称：**

bilibili通知插件

**插件功能：**

将up主更新、番剧更新、主播开播等信息推送到QQ

**PyPI 项目名：**

nonebot-plugin-bilibilibot

**插件 import 包名：**

nonebot_plugin_bilibilibot

**插件项目仓库/主页链接：**

https://github.com/TDK1969/nonebot_plugin_bilibilibot

**标签：**

[{"label":"bilibili","color":"#f605dd"},{"label":"a:onebot11","color":"#05f6e4"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: bilibili通知插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: bilibili-#f605dd, a:onebot11-#05f6e4</li><li>✅ 项目 <a href="https://github.com/TDK1969/nonebot_plugin_bilibilibot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bilibilibot/">nonebot-plugin-bilibilibot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
