### ISSUE TITLE
Plugin: 色图生成

### ISSUE THREAD

**Issue by monsterxcn** [nonebot/nonebot2#862]
**插件名称：**

色图生成

**插件功能：**

Nonebot2 色图生成插件！哎哟这个色啊，好色！

**PyPI 项目名：**

nonebot-plugin-color

**插件 import 包名：**

nonebot_plugin_color

**插件项目仓库/主页链接：**

https://github.com/monsterxcn/nonebot-plugin-color

**标签：**

[{"label": "a:onebot", "color": "#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 色图生成

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/monsterxcn/nonebot-plugin-color">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-color/">nonebot-plugin-color</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
