### ISSUE TITLE
Plugin: 21点游戏插件

### ISSUE THREAD

**Issue by yaowan233** [nonebot/nonebot2#864]
**插件名称：**

21点游戏插件

**插件功能：**

一个基于签到积分的21点游戏与积分对战插件

**PyPI 项目名：**

nonebot-plugin-blackjack

**插件 import 包名：**

nonebot_plugin_blackjack

**插件项目仓库/主页链接：**

https://github.com/yaowan233/nonebot-plugin-blackjack

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 21点游戏插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/yaowan233/nonebot-plugin-blackjack">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-blackjack/">nonebot-plugin-blackjack</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
