### ISSUE TITLE
Bug: Something went wrong

### ISSUE THREAD

**Issue by xia0ji233** [nonebot/nonebot2#867]
当我尝试更新自己的nonebot版本时，运行nonebot出现了如下错误
![image](https://user-images.githubusercontent.com/73569212/158042107-c19796df-ed08-4e43-9a3f-74c284b74ca4.png)
原来的nb-cli版本为0.5.1，更新后的版本为0.6.6，更新的时候并没有报出依赖有问题。
求解决办法

**Comment by yanyongyu** [comment]
请查看 https://github.com/nonebot/discussions/discussions/74 迁移指南
