### ISSUE TITLE
Plugin: QQ自动同意好友申请

### ISSUE THREAD

**Issue by ZakiuC** [nonebot/nonebot2#870]
**插件名称：**

QQ自动同意好友申请

**插件功能：**

QQ自动同意好友申请

**PyPI 项目名：**

nonebot-pulgin-autoagree

**插件 import 包名：**

nonebot_pulgin_autoagree

**插件项目仓库/主页链接：**

https://github.com/ZakiuC/NoneBot_Pulgin_AutoAgree

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: QQ自动同意好友申请

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ZakiuC/NoneBot_Pulgin_AutoAgree">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_pulgin_autoagree/">nonebot_pulgin_autoagree</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
