### ISSUE TITLE
Bug: 发送视频报错，但是视频又发出来了

### ISSUE THREAD

**Issue by Huangtingdt** [nonebot/nonebot2#873]
**描述问题：**

发送视频出现nonebot.adapters.onebot.v11.exception.NetworkError异常，然后视频过一会儿又发送成功了。

**期望的结果**

不要出现异常

**环境信息：**

 - OS: [Ubuntu]
 - Python Version: [3.8.10]
 - Nonebot Version: [e.g. 2.0.0b2]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [v1.0.0-rc1]

**截图或日志**
![image](https://user-images.githubusercontent.com/45315146/158804131-86110676-64d8-4316-bd58-ba987ff78b6b.png)

**Comment by yanyongyu** [comment]
这个报错是由于gocq未能及时返回api调用结果，可以尝试调高timeout时间

https://v2.nonebot.dev/docs/next/tutorial/configuration#api-timeout
