### ISSUE TITLE
Plugin: Arcaea查分插件

### ISSUE THREAD

**Issue by SEAFHMC** [nonebot/nonebot2#874]
**插件名称：**

Arcaea查分插件

**插件功能：**

Arcaea查分插件(recent, best30)

**PyPI 项目名：**

nonebot-plugin-arcaeabot

**插件 import 包名：**

nonebot_plugin_arcaeabot

**插件项目仓库/主页链接：**

https://github.com/SEAFHMC/nonebot-plugin-arcaeabot

**标签：**

[{"label":"Arcaea","color":"#db52ea"},{"label":"a:onebot","color":"#ff2e00"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: Arcaea查分插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Arcaea-#db52ea, a:onebot-#ff2e00</li><li>✅ 项目 <a href="https://github.com/SEAFHMC/nonebot-plugin-arcaeabot">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-arcaeabot/">nonebot-plugin-arcaeabot</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
