### ISSUE TITLE
Plugin: 成分姬

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#877]
**插件名称：**

成分姬

**插件功能：**

查询B站关注列表的VTuber成分

**PyPI 项目名：**

nonebot-plugin-ddcheck

**插件 import 包名：**

nonebot_plugin_ddcheck

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-ddcheck

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 成分姬

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-ddcheck">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-ddcheck/">nonebot-plugin-ddcheck</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
