### ISSUE TITLE
Feature: 热重载插件

### ISSUE THREAD

**Issue by BlueDeer233** [nonebot/nonebot2#880]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

每次修改插件内容后都需要整体重启bot，同时想做一个在线热重载插件（不用在服务器上重启bot）

**描述你所需要的特性：**

是否可以在[nonebot.plugin.load](https://github.com/nonebot/nonebot2/blob/master/nonebot/plugin/load.py)中新增例如reload_plugins(*plugin_dir)这样的功能  
可以使用[importlib.reload](https://docs.python.org/3/library/imp.html?highlight=reload#imp.reload)功能重载已经加载过的插件

**Comment by yanyongyu** [comment]
由于python引用和缓存的问题，`importlib.reload`也仅仅是虚假的热重载，并不能做到完全替换原有的引用，所以在python中一般使用冷重载的方式重新启动（

**Comment by BlueDeer233** [comment]
那还有比较好的在线更新插件办法吗，把原来的插件del然后load_plugin？

**Comment by yanyongyu** [comment]
del 再 load 和reload效果一致，

**Comment by BlueDeer233** [comment]
sys.modules.pop也不行吗 T.T

**Comment by yanyongyu** [comment]
> sys.modules.pop也不行吗 T.T

并不行，python只要引用计数不清零，就不会被回收。

**Comment by BlueDeer233** [comment]
了解了，我看MCDReforged用的sys.modules.pop重载插件，我先写个插件试试，不行就没折了

**Comment by BlueDeer233** [comment]
理解，之前做flask和quart后端的时候就是这样的，这个用sys.modules方法的时候似乎还要维护plugins Dict，在hoshinobot上甚至还要维护_loaded_services Dict、_service_bundle Dict，总之热重载还挺麻烦的
