### ISSUE TITLE
Plugin: 第二个leetcode查询插件

### ISSUE THREAD

**Issue by Nranphy** [nonebot/nonebot2#881]
**插件名称：**

第二个leetcode查询插件

**插件功能：**

可查询用户信息、获取每日一题与随机一题和搜索题目。

**PyPI 项目名：**

nonebot-plugin-leetcode2

**插件 import 包名：**

nonebot_plugin_leetcode2

**插件项目仓库/主页链接：**

https://github.com/Nranphy/nonebot_plugin_leetcode2

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 第二个leetcode查询插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/Nranphy/nonebot_plugin_leetcode2">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-leetcode2/">nonebot-plugin-leetcode2</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
