### ISSUE TITLE
Plugin: HikariSearch

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#883]
**插件名称：**

HikariSearch

**插件功能：**

使用 HikariSearch 的又一个搜图插件

**PyPI 项目名：**

nonebot-plugin-hikarisearch

**插件 import 包名：**

nonebot_plugin_hikarisearch

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-hikarisearch

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: HikariSearch

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-hikarisearch">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-hikarisearch/">nonebot-plugin-hikarisearch</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by mnixry** [comment]
star了吗star了吗star了吗

**Comment by MeetWq** [comment]
233，点啦
