### ISSUE TITLE
Plugin: MediaWiki查询

### ISSUE THREAD

**Issue by KoishiStudio** [nonebot/nonebot2#885]
**插件名称：**

MediaWiki查询

**插件功能：**

为群聊提供简单的wiki查询功能（仅支持onebot）

**PyPI 项目名：**

nonebot-plugin-mediawiki

**插件 import 包名：**

nonebot_plugin_mediawiki

**插件项目仓库/主页链接：**

https://github.com/KoishiStudio/nonebot-plugin-mediawiki

**标签：**

[{"label":"a:onebot","color":"#000000"},{"label":"t:wiki","color":"#679ff9"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: MediaWiki查询

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000, t:wiki-#679ff9</li><li>✅ 项目 <a href="https://github.com/KoishiStudio/nonebot-plugin-mediawiki">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-mediawiki/">nonebot-plugin-mediawiki</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
