### ISSUE TITLE
Plugin: 快速搜索

### ISSUE THREAD

**Issue by KoishiStudio** [nonebot/nonebot2#888]
**插件名称：**

快速搜索

**插件功能：**

指引群友快速 访 ~~(tui)~~ 问 ~~(dao)~~ 谷歌娘（在中国大陆大概就是度娘了～）

**PyPI 项目名：**

nonebot-plugin-giyf

**插件 import 包名：**

nonebot_plugin_giyf

**插件项目仓库/主页链接：**

https://github.com/KoishiStudio/nonebot-plugin-giyf

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 快速搜索

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/KoishiStudio/nonebot-plugin-giyf">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-giyf/">nonebot-plugin-giyf</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
