### ISSUE TITLE
Plugin: wordle猜单词

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#890]
**插件名称：**

wordle猜单词

**插件功能：**

wordle猜单词游戏

**PyPI 项目名：**

nonebot-plugin-wordle

**插件 import 包名：**

nonebot_plugin_wordle

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-wordle

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: wordle猜单词

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-wordle">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-wordle/">nonebot-plugin-wordle</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
