### ISSUE TITLE
Plugin: 语句抽象化

### ISSUE THREAD

**Issue by CherryCherries** [nonebot/nonebot2#893]
**插件名称：**

语句抽象化

**插件功能：**

能够将你的语句变得抽象起来~

**PyPI 项目名：**

nonebot-plugin-abstract

**插件 import 包名：**

nonebot_plugin_abstract

**插件项目仓库/主页链接：**

https://github.com/CherryCherries/nonebot-plugin-abstract

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 语句抽象化

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/CherryCherries/nonebot-plugin-abstract">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-abstract/">nonebot-plugin-abstract</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
