### ISSUE TITLE
Plugin: 汉兜 Handle

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#898]
**插件名称：**

汉兜 Handle

**插件功能：**

汉字版Wordle 猜成语插件

**PyPI 项目名：**

nonebot-plugin-handle

**插件 import 包名：**

nonebot_plugin_handle

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-handle

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 汉兜 Handle

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-handle">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-handle/">nonebot-plugin-handle</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
