### ISSUE TITLE
Feature: 将内置on_*系列函数作为MatcherGroup的方法

### ISSUE THREAD

**Issue by mnixry** [nonebot/nonebot2#90]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

在实际使用中，我需要对nonebot进行一层包装，而MatcherGroup类可以起到对Matcher类似于“工厂函数”的作用
我希望能够将on_*系列函数作为MatcherGroup类的一个方法

**描述你所需要的特性：**

```python
group = MatcherGroup(rule=Rule(some_rule))

matcher = group.on_command("xxx")

@matcher.handle
async def foo():
    ...
```

在库内的on系列函数可以作为一个已经预先实例化的MatcherGroup的方法

```python
_InnerGroup = MatcherGroup()

on_command = _InnerGroup.on_command
```

~希望我描述清楚了~

**Comment by yanyongyu** [comment]
将 `MatcherGroup` 作为类似于 `CommandGroup` 的实现

**Comment by mnixry** [comment]
> 你的意思是将 `MatcherGroup` 作为类似于 `CommandGroup` 的实现

差不多
