### ISSUE TITLE
Plugin: 监测群事件

### ISSUE THREAD

**Issue by cjladmin** [nonebot/nonebot2#900]
**插件名称：**

监测群事件

**插件功能：**

监测群成员变动、文件上传、红包运气王、管理员变动等等...

**PyPI 项目名：**

nonebot-plugin-monitor

**插件 import 包名：**

nonebot_plugin_monitor

**插件项目仓库/主页链接：**

https://github.com/cjladmin/nonebot_plugin_monitor

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 监测群事件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/cjladmin/nonebot_plugin_monitor">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_monitor/">nonebot_plugin_monitor</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by j1g5awi** [comment]
请在项目依赖里填写 nonebot2、nonebot-adapter-onebot

**Comment by yanyongyu** [comment]
@cjladmin 请正确在插件setup.py中填写依赖

**Comment by cjladmin** [comment]
OK添加了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 晚上8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/nonebot2] Plugin: 监测群事件 (Issue #900)






请在项目依赖里填写 nonebot2、nonebot-adapter-onebot

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;
