### ISSUE TITLE
Plugin: 今日兽兽

### ISSUE THREAD

**Issue by ye-tutu** [nonebot/nonebot2#903]
**插件名称：**

今日兽兽

**插件功能：**

每天推送furry图-福瑞bot插件

**PyPI 项目名：**

**插件 import 包名：**

**插件项目仓库/主页链接：**

https://github.com/ye-tutu/nonebot_plugin_everyfur

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 今日兽兽

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/**插件 import 包名：**/">**插件 import 包名：**</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ye-tutu/nonebot_plugin_everyfur">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
