### ISSUE TITLE
Plugin: 扫雷游戏

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#906]
**插件名称：**

扫雷游戏

**插件功能：**

在qq中玩扫雷

**PyPI 项目名：**

nonebot-plugin-minesweeper

**插件 import 包名：**

nonebot_plugin_minesweeper

**插件项目仓库/主页链接：**

https://github.com/MeetWq/nonebot-plugin-minesweeper

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 扫雷游戏

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/MeetWq/nonebot-plugin-minesweeper">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-minesweeper/">nonebot-plugin-minesweeper</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
