### ISSUE TITLE
Plugin: nonebot_plugin_draw

### ISSUE THREAD

**Issue by bingganhe123** [nonebot/nonebot2#909]
**插件名称：**

nonebot_plugin_draw

**插件功能：**

模拟抽签的一个本地化插件

**PyPI 项目名：**

nonebot_plugin_draw

**插件 import 包名：**

nonebot_plugin_draw

**插件项目仓库/主页链接：**

https://github.com/bingganhe123/nonebot_plugin_draw

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_draw

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/bingganhe123/nonebot_plugin_draw">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_draw/">nonebot_plugin_draw</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
