### ISSUE TITLE
Plugin: 好友请求和群请求处理

### ISSUE THREAD

**Issue by ziru-w** [nonebot/nonebot2#912]
**插件名称：**

好友请求和群请求处理

**插件功能：**

处理被请求加QQ好友和QQ群的请求

**PyPI 项目名：**

nonebot_plugin_addFriend

**插件 import 包名：**

nonebot_plugin_addFriend

**插件项目仓库/主页链接：**

https://github.com/ziru-w/nonebot_plugin_addFriend

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 好友请求和群请求处理

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/ziru-w/nonebot_plugin_addFriend">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_addFriend/">nonebot_plugin_addFriend</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
请在setup.py文件内加上安装所需要的依赖项

**Comment by ziru-w** [comment]
关掉这个issue吧，诶嘿



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 晚上11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/nonebot2] Plugin: 好友请求和群请求处理 (Issue #912)





 
请在setup.py文件内加上安装所需要的依赖项
