### ISSUE TITLE
Plugin: 监测QQ群事件

### ISSUE THREAD

**Issue by cjladmin** [nonebot/nonebot2#925]
**插件名称：**

监测QQ群事件

**插件功能：**

监测QQ群状态，例如：群成员人数变动、文件上传、红包运气王、管理员变动等

**PyPI 项目名：**

nonebot-plugin-monitor

**插件 import 包名：**
nonebot_plugin_monitor

**插件项目仓库/主页链接：**

https://github.com/cjladmin/nonebot_plugin_monitor

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 监测QQ群事件

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ module_name: 无法匹配到数据。<dt>请确保填写该项目。</dt></li><li>⚠️ 包 <a href="https://pypi.org/project/https://pypi.org/project/nonebot-plugin-monitor/0.0.2//">https://pypi.org/project/nonebot-plugin-monitor/0.0.2/</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/cjladmin/nonebot_plugin_monitor">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by StarHeartHunt** [comment]
表单参数存在填写错误

请注意：
PyPI 项目名：您的插件所在的 PyPI Project 名，如 nonebot-plugin-xxxx
import 包名：您的插件通过 Python 导入时使用的包名，如 nonebot_plugin_xxxx

参阅：[发布插件](https://v2.nonebot.dev/docs/next/advanced/publish-plugin#%E7%94%B3%E8%AF%B7%E5%8F%91%E5%B8%83%E5%88%B0-nonebot2-%E6%8F%92%E4%BB%B6%E5%95%86%E5%BA%97)

**Comment by yanyongyu** [comment]
请检查一下你的插件可用性，pypi打包文件中并未包含任何插件代码

**Comment by yanyongyu** [comment]
由于长时间未能正确发布插件，先close了，欢迎修改后重新发布
