### ISSUE TITLE
Plugin: 随机唐可可

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#930]
**插件名称：**

随机唐可可

**插件功能：**

找到唐可可，和她一起做学园偶像！🎶

**PyPI 项目名：**

nonebot-plugin-randomtkk

**插件 import 包名：**

nonebot_plugin_randomtkk

**插件项目仓库/主页链接：**

https://github.com/MinatoAquaCrews/nonebot_plugin_randomtkk

**标签：**

[{"label":"a:onebot","color":"#d62222"},{"label":"t:Tan Kuku","color":"#fdaf75"},{"label":"t:Liyuu","color":"#465dfd"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 随机唐可可

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#d62222, t:Tan Kuku-#fdaf75, t:Liyuu-#465dfd</li><li>✅ 项目 <a href="https://github.com/MinatoAquaCrews/nonebot_plugin_randomtkk">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-randomtkk/">nonebot-plugin-randomtkk</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
