### ISSUE TITLE
Bug: 一直卡在Checking for matchers in priority 1

### ISSUE THREAD

**Issue by Aaisui** [nonebot/nonebot2#932]
**描述问题：**

一直卡在Checking for matchers in priority 1，

**如何复现？**

我编写了如下代码作为测试：
![image](https://user-images.githubusercontent.com/57386745/164018973-2abd6916-418a-430b-8663-7fd73224010e.png)
这是我的配置文件：
![image](https://user-images.githubusercontent.com/57386745/164019136-dcdfdd6a-83ef-4009-a5ff-e905400025ad.png)

向机器人发送/weather或者/test甚至是/echo 123
![image](https://user-images.githubusercontent.com/57386745/164020612-b38842e7-1257-47d3-8988-5ebc8ad51d8d.png)

![image](https://user-images.githubusercontent.com/57386745/164020385-566d0d13-4cb0-4094-9083-8f3a4f1e90ca.png)

**期望的结果**

应该@我一次并发送一些消息，但是实际上是：
![image](https://user-images.githubusercontent.com/57386745/164019462-d3cd0120-38b4-4265-b005-636ecbeaa876.png)

**环境信息：**

 - OS: windows
 - Python Version: Python3.8
 - Nonebot Version:  2.0.0-beta.2
 - 
**协议端信息：**
使用了nonebot_plugin_gocqhttp 插件

**截图或日志**

04-19 21:53:01 [INFO] nonebot_plugin_gocqhttp | [2069564018] Bot进入了群 自学(936754919).
04-19 21:53:01 [SUCCESS] nonebot | ONEBOT V11 2069564018 | [notice.group_increase.approve]: {'time': 1650376381, 'self_id': 2069564018, 'post_type': 'notice', 'notice_type': 'group_increase', 'sub_type': 'approve', 'user_id': 2069564018, 'group_id': 936754919, 'operator_id': 0}
04-19 21:53:01 [DEBUG] nonebot | Checking for matchers in priority 1...
04-19 21:53:02 [INFO] nonebot_plugin_gocqhttp | [2069564018] 收到来自群 自学(936754919) 内用户 月石(3514520240) 的加群邀请.
04-19 21:53:02 [SUCCESS] nonebot | ONEBOT V11 2069564018 | [request.group.invite]: {'time': 1650376382, 'self_id': 2069564018, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'invite', 'group_id': 936754919, 'user_id': 3514520240, 'comment': '', 'flag': '1650376380922620'}
04-19 21:53:02 [DEBUG] nonebot | Checking for matchers in priority 1...
04-19 21:53:02 [INFO] uvicorn | 127.0.0.1:52876 - "GET /api/status HTTP/1.1" 200
04-19 21:53:03 [INFO] nonebot_plugin_gocqhttp | [2069564018] 收到群 自学(936754919) 内 月石(3514520240) 的消息: weather (-942845021)
04-19 21:53:03 [SUCCESS] nonebot | ONEBOT V11 2069564018 | [message.group.normal]: Message -942845021 from 3514520240@[群:936754919] "weather"
04-19 21:53:03 [DEBUG] nonebot | Checking for matchers in priority 1...
04-19 21:53:05 [INFO] uvicorn | 127.0.0.1:52889 - "GET /api/accounts HTTP/1.1" 200
04-19 21:53:05 [INFO] uvicorn | 127.0.0.1:52876 - "GET /api/status HTTP/1.1" 200
04-19 21:53:05 [INFO] nonebot_plugin_gocqhttp | [2069564018] 收到群 自学(936754919) 内 月石(3514520240) 的消息: /weather (1589903897)
04-19 21:53:05 [SUCCESS] nonebot | ONEBOT V11 2069564018 | [message.group.normal]: Message 1589903897 from 3514520240@[群:936754919] "/weather"

**Comment by Aaisui** [comment]
草导包导错了，没事了自己犯蠢了

**Comment by deepDarkFantasyy** [comment]
我也遇到了同样的问题,能详细说说哪边出了问题吗?
