### ISSUE TITLE
Plugin: nonebot-plugin-dida

### ISSUE THREAD

**Issue by TDK1969** [nonebot/nonebot2#933]
**插件名称：**

nonebot-plugin-dida

**插件功能：**

基于Nonebot的滴答清单插件,可创建普通任务/子任务,按照条件查询任务

**PyPI 项目名：**

nonebot-plugin-dida

**插件 import 包名：**

nonebot_plugin_dida

**插件项目仓库/主页链接：**

https://github.com/TDK1969/nonebot_plugin_dida

**标签：**

[{"label":"t:滴答清单","color":"#007ffd"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot-plugin-dida

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: t:滴答清单-#007ffd</li><li>✅ 项目 <a href="https://github.com/TDK1969/nonebot_plugin_dida">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_dida/">nonebot_plugin_dida</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
如果你的插件依赖onebot的话请在pypi发布时安装依赖里正确填写

**Comment by TDK1969** [comment]
插件不依赖onebot
