### ISSUE TITLE
Bug: MessageTemplate.format 将消息段错误拼接为文本

### ISSUE THREAD

**Issue by MingxuanGame** [nonebot/nonebot2#938]
**描述问题：**

`MessageTemplate.format` 将非文本类型消息段错误拼接为文本类型

**如何复现？**

```python
>>> from nonebot.adapters.onebot.v11 import Message, MessageSegment
>>> Message.template("{}{}").format(MessageSegment.image("file:///"), "hello")
[MessageSegment(type='text', data={'text': '[CQ:image,file=file:///,cache=true,proxy=true]'}), MessageSegment(type='text', data={'text': 'hello'})]
```

**期望的结果**

```python
>>> from nonebot.adapters.onebot.v11 import Message, MessageSegment
>>> Message.template("{}{}").format(MessageSegment.image("file:///"), "hello")
[MessageSegment(type='image', data={'file': 'file:///', 'type': None, 'cache': 'true', 'proxy': 'true', 'timeout': None}), MessageSegment(type='text', data={'text': 'hello'})]
```

**环境信息：**

 - OS: Windows 10
 - Python Version: 3.9.6
 - Nonebot Version: 2.0.0-beta2

**截图或日志**

![before](https://user-images.githubusercontent.com/68982190/165677394-d5679b8c-6ab8-4eb9-a796-c5e597273031.png)

**备注**

我自己写了一段修复代码（不保证稳定性）

[`template.py`](https://github.com/nonebot/nonebot2/blob/master/nonebot/internal/adapter/template.py)将原来的

```python
formatted_text = self.format_field(obj, str(format_control))
results.append(formatted_text)
```
替换为
```python
from .message import MessageSegment
if isinstance(obj, MessageSegment):
    results.append(obj)
else:
    formatted_text = self.format_field(obj, str(format_control))
    results.append(formatted_text)
```

修复后效果如下

![fix](https://user-images.githubusercontent.com/68982190/165677717-e7cff460-d2d4-47ff-907d-a8a9fc0a6a84.png)

**Comment by StarHeartHunt** [comment]
https://github.com/nonebot/nonebot2/blob/3870f0084d4c7a856211d07d99d535a19c071e0c/nonebot/internal/adapter/template.py#L174-L178

应该是这里，onebot adapter 那边没指定 formatter，直接转 str 进来了。

**Comment by yanyongyu** [comment]
@mnixry 🤗
