### ISSUE TITLE
Plugin: 支付宝到账语音

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#939]
**插件名称：**

支付宝到账语音

**插件功能：**

发送支付宝到账语音, 支持金额范围为0.01~999999999999.99

**PyPI 项目名：**

nonebot-plugin-alipayvoice

**插件 import 包名：**

nonebot_plugin_alipayvoice

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-alipayvoice

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 支付宝到账语音

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-alipayvoice">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-alipayvoice/">nonebot-plugin-alipayvoice</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
提醒 pyproject里的homepage和repo写错了（
