### ISSUE TITLE
Plugin: 一言

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#943]
**插件名称：**

一言

**插件功能：**

总有一句话能打动你的心

**PyPI 项目名：**

nonebot-plugin-hitokoto

**插件 import 包名：**

nonebot_plugin_hitokoto

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-hitokoto

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 一言

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-hitokoto">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-hitokoto/">nonebot-plugin-hitokoto</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
