### ISSUE TITLE
Plugin: B站视频封面提取

### ISSUE THREAD

**Issue by A-kirami** [nonebot/nonebot2#945]
**插件名称：**

B站视频封面提取

**插件功能：**

提取B站视频的封面，支持链接、av号、bv号

**PyPI 项目名：**

nonebot-plugin-bilicover

**插件 import 包名：**

nonebot_plugin_bilicover

**插件项目仓库/主页链接：**

https://github.com/A-kirami/nonebot-plugin-bilicover

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: B站视频封面提取

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/A-kirami/nonebot-plugin-bilicover">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-bilicover/">nonebot-plugin-bilicover</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
