### ISSUE TITLE
Plugin: 中国象棋

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#948]
**插件名称：**

中国象棋

**插件功能：**

象棋，支持人机和对战

**PyPI 项目名：**

nonebot-plugin-cchess

**插件 import 包名：**

nonebot_plugin_cchess

**插件项目仓库/主页链接：**

https://github.com/noneplugin/nonebot-plugin-cchess

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 中国象棋

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#000000</li><li>✅ 项目 <a href="https://github.com/noneplugin/nonebot-plugin-cchess">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-cchess/">nonebot-plugin-cchess</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
