### ISSUE TITLE
Feature: Add tests case 

### ISSUE THREAD

**Issue by bytemain** [nonebot/nonebot2#95]
各 adapter 需要写一些 test case 来测试 Message 和 Event 的表现。

**Comment by lengthmin** [comment]
不仅要各 adapter 自己写， nonebot 也要写一点测试 adapter 通用性的 test case

**Comment by felinae98** [comment]
确实很需要了，或者先弄一个简单的单元测试框架，可以测试一些内部函数的功能

**Comment by yanyongyu** [comment]
这个问题等 `NoneBug` 项目结束可以得到解决

**Comment by felinae98** [comment]
这个项目大概什么时候完成，有repo吗，想围观开发进度

**Comment by yanyongyu** [comment]
> 这个项目大概什么时候完成，有repo吗，想围观开发进度

暂时并没有，你可以参考OSPP日程表

**Comment by yanyongyu** [comment]
nonebug正式在dev分支启用，单元测试编写中
