### ISSUE TITLE
Plugin: NoneBot2 文档搜索

### ISSUE THREAD

**Issue by MingxuanGame** [nonebot/nonebot2#951]
**插件名称：**

NoneBot2 文档搜索

**插件功能：**

在 QQ 群内搜索 NoneBot2 文档

**PyPI 项目名：**

nonebot-plugin-rtfm

**插件 import 包名：**

nonebot_plugin_rtfm

**插件项目仓库/主页链接：**

https://github.com/MingxuanGame/nonebot-plugin-rtfm

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: NoneBot2 文档搜索

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 标签解码失败。<dt>请确保标签格式正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/MingxuanGame/nonebot-plugin-rtfm">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-rtfm/">nonebot-plugin-rtfm</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
