### ISSUE TITLE
Bot: Inkar Suki

### ISSUE THREAD

**Issue by HornCopper** [nonebot/nonebot2#954]
**机器人名称：**

Inkar Suki

**机器人功能：**

一个十分方便的Bot，支持包括Webhook、群管、互动等一系列功能

**机器人项目仓库/主页链接：**

https://github.com/HornCopper/Inkar-Suki

**标签：**

[{"label":"Minecraft","color":"#d03790"},{"label":"GitHub","color":"#374fd0"},{"label":"群管","color":"#4ede39"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: Inkar Suki

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: Minecraft-#d03790, GitHub-#374fd0, 群管-#4ede39</li><li>✅ 项目 <a href="https://github.com/HornCopper/Inkar-Suki">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
