### ISSUE TITLE
Plugin: 国际象棋

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nonebot2#956]
**插件名称：**

国际象棋

**插件功能：**

国际象棋，支持人机和对战

**PyPI 项目名：**

nonebot-plugin-chess

**插件 import 包名：**

nonebot_plugin_chess

**插件项目仓库/主页链接：**

https://github.com/noneplugin/nonebot-plugin-chess

**标签：**

[{"label":"a:onebot","color":"#020202"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 国际象棋

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: a:onebot-#020202</li><li>✅ 项目 <a href="https://github.com/noneplugin/nonebot-plugin-chess">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-chess/">nonebot-plugin-chess</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
