### ISSUE TITLE
Bot: ShigureBot

### ISSUE THREAD

**Issue by lgc2333** [nonebot/nonebot2#958]
**机器人名称：**

ShigureBot

**机器人功能：**

给自己的综合性娱乐Bot写的插件集

**机器人项目仓库/主页链接：**

https://github.com/lgc2333/ShigureBot

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Bot: ShigureBot

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/lgc2333/ShigureBot">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
