### ISSUE TITLE
[寻求帮助] AttributeError: module 'nonebot' has no attribute 'load_bulitin_plugins'

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot2#96]
nonebot版本: 2.0.0a6(使用`python3.8 -m pip install nonebot2`安装,镜像也是刚重装的,确保没有使用过nonebot1)
OS: CentOS 8
python版本: 3.8.0
遇到的问题:在按照[官方教程](https://v2.nonebot.dev/guide/loading-a-plugin.html#%E5%8A%A0%E8%BD%BD%E5%86%85%E7%BD%AE%E6%8F%92%E4%BB%B6) 加载插件时，无法加载内置插件。 
![image](https://user-images.githubusercontent.com/36919867/100964517-cd758e80-3563-11eb-82cb-63c010299df9.png)

bot.py内容如下
![image](https://user-images.githubusercontent.com/36919867/100964638-0dd50c80-3564-11eb-9f82-91c6ac280a41.png)

**Comment by yanyongyu** [comment]
当前文件目录下是否还有个叫nonebot的文件夹

**Comment by railannad** [comment]
> 当前文件目录下是否还有个叫nonebot的文件夹，有没有卸载重装试过
没有叫nonebot的文件夹
![image](https://user-images.githubusercontent.com/36919867/100965359-838da800-3565-11eb-8672-6a359cf46434.png)

uninstall 之后再install算是重装吗？试过了，不行

**Comment by yanyongyu** [comment]
运行一下如下代码看一眼

```bash
python -c "import nonebot, inspect; print(inspect.getsource(nonebot))"
```

**Comment by lengthmin** [comment]
打错字了 是 builtin

![image](https://user-images.githubusercontent.com/13938334/100966069-05ca9c00-3567-11eb-9dff-09a90291ee67.png)

**Comment by railannad** [comment]
> 打错字了 是 builtin
> 
> ![image](https://user-images.githubusercontent.com/13938334/100966069-05ca9c00-3567-11eb-9dff-09a90291ee67.png)

啊这，我是直接复制文档里的。。。

**Comment by lengthmin** [comment]
让写文档的出来挨打吧

**Comment by railannad** [comment]
感谢楼上二位大佬
