### ISSUE TITLE
Docs: 文档关于插件的描述

### ISSUE THREAD

**Issue by jingyuexing** [nonebot/nonebot2#960]
文档描述不够细致
比如描述关于插件的配置项的
plugin_config.json
```json
{
  "plugins": ["path.to.your.plugin"],
  "plugin_dirs": ["path/to/your/plugins"]
}
```

在一个新手刚刚入门的情况下,请问这个`plugin_config.json` 相对于bot.py 是什么位置 这个配置文件是写在项目根目录下还是写在`plugin/{plugin_name}/plugin_config.json`
作为一个实列  他的目录结构是什么样的 
以及 是不是有一个手把手 用每一个commit标注清楚  每一个行为在干什么的模板样例的仓库

所有的文档是及其零散,将每一个配置项单独拿出来说 但是并没有清楚的讲配置所在整个项目当中的位置是怎样的

**Comment by jingyuexing** [comment]
最重要的是文档教程并非连续 而是零散的 各讲各的 这是最重要的 也是最让新手难以理解的地方 
由于是零散的 导致不知道项目为什么要这么做

**Comment by j1g5awi** [comment]
reference to #793

**Comment by yanyongyu** [comment]
> 以及 是不是有一个手把手 用每一个commit标注清楚 每一个行为在干什么的模板样例的仓库

> * [ ]  以一个初始化的项目入手 开始讲解各个部分
> * [ ]  当完成了项目的初始化 我们需要为机器人增加命令
> * [ ]  比如 `Wether` 命令  (思考方向  我们要匹配城市 所以要如何做  我们要防止恶意注入 所以要如何做)
> * [ ]  添加了`XX` 配置  为了让bot起到什么作用
> * [ ]  ………………

手把手那就不像文档了，更像教程，教程的目的在于写出一个什么bot，文档的目的在于说明框架的某一个功能，教程并不能很好的囊括框架的每一个功能

**Comment by jingyuexing** [comment]
> 手把手那就不像文档了，更像教程，教程的目的在于写出一个什么bot，文档的目的在于说明框架的某一个功能，教程并不能很好的囊括框架的每一个功能

教程当然是不可缺少的，至少能够让人跟着步骤做一个初步的bot出来 让人有动力去做下一步，或者分出一个教程板块 API板块就专门介绍API，新手教程太缺少了

**Comment by Zhao-sai-sai** [comment]
模块的编写，我一个感觉我自己python错的人，看你的文档都看不懂，不用说小白了，看文档还不如直接看人家写好的项目类

**Comment by Zhao-sai-sai** [comment]
> > 以及不是有一个手把手用每一个承诺标明每一个行为在做什么的样板样的仓库
> 
> > * [ ]   以一个手把手开始创业项目的部分
> > * [ ]   当完成了增加项目的初始化 我们需要为机器人命令
> > * [ ]   （想`Wether`我们的方向要匹配所以要如何做我们要阻止的目的所以要如何做）
> > * [ ]   添加了`XX`配置 为了让机器人什么作用
> > * [ ]   ………………
> 
> 手把手可以将某个文档的功能、描述、目的是编写出什么机器人、文档的目的是说明文档的功能，并提供文档的括框的每个文档的功能。

问题是我们在能懂他写的什么，看的我感觉比我密码学看的还迷茫类，怎么搞
