### ISSUE TITLE
Plugin: 合成字符画(GIF)

### ISSUE THREAD

**Issue by RafuiiChan** [nonebot/nonebot2#963]
**插件名称：**

合成字符画(GIF)

**插件功能：**

顾名思义

**PyPI 项目名：**

nonebot-plugin-charpic

**插件 import 包名：**

nonebot_plugin_charpic

**插件项目仓库/主页链接：**

https://github.com/RafuiiChan/nonebot_plugin_charpic

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 合成字符画(GIF)

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/RafuiiChan/nonebot_plugin_charpic">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_charpic/">nonebot_plugin_charpic</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by 1umine** [comment]
1
