### ISSUE TITLE
Plugin: 幻影坦克图片合成

### ISSUE THREAD

**Issue by RafuiiChan** [nonebot/nonebot2#967]
**插件名称：**

幻影坦克图片合成

**插件功能：**

合成幻影坦克图片，黑白背景下显示不同图片

**PyPI 项目名：**

nonebot-plugin-miragetank

**插件 import 包名：**

nonebot_plugin_miragetank

**插件项目仓库/主页链接：**

https://github.com/RafuiiChan/nonebot_plugin_miragetank

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 幻影坦克图片合成

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/RafuiiChan/nonebot_plugin_miragetank">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_miragetank/">nonebot_plugin_miragetank</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by 1umine** [comment]
1
