### ISSUE TITLE
Plugin:  nonebot_plugin_even

### ISSUE THREAD

**Issue by PadorFelice** [nonebot/nonebot2#969]
**插件名称：**

 nonebot_plugin_eventdone

**插件功能：**

远程好友申请事件的处理~

**PyPI 项目名：**

 nonebot_plugin_eventdone 

**插件 import 包名：**

 nonebot_plugin_eventdone 

**插件项目仓库/主页链接：**

https://github.com/PadorFelice/nonebot_plugin_eventdone

**标签：**

[{"label":"nonebot","color":"#ea5252"},{"label":"事件处理","color":"#be52ea"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: nonebot_plugin_eventdone

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 标签: nonebot-#ea5252, 事件处理-#be52ea</li><li>✅ 项目 <a href="https://github.com/PadorFelice/nonebot_plugin_eventdone">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot_plugin_eventdone/">nonebot_plugin_eventdone</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by PadorFelice** [comment]
呜呜呜，这个名字写错啦，少了done

**Comment by PadorFelice** [comment]
> **插件名称：**
> 
> nonebot_plugin_eventdone
> 
> **插件功能：**
> 
> 远程好友申请事件的处理~
> 
> **PyPI 项目名：**
> 
> nonebot_plugin_eventdone
> 
> **插件 import 包名：**
> 
> nonebot_plugin_eventdone
> 
> **插件项目仓库/主页链接：**
> 
> https://github.com/PadorFelice/nonebot_plugin_eventdone
> 
> **标签：**
> 
> [{"label":"nonebot","color":"#ea5252"},{"label":"事件处理","color":"#be52ea"}]
