### ISSUE TITLE
Plugin: 语录娱乐

### ISSUE THREAD

**Issue by bingqiu456** [nonebot/nonebot2#972]
**插件名称：**

语录娱乐

**插件功能：**

语录娱乐小插件

**PyPI 项目名：**

nonebot-plugin-yulu

**插件 import 包名：**

nonebot_plugin_yulu

**插件项目仓库/主页链接：**

https://github.com/bingqiu456/nonebot-plugin-yulu

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 语录娱乐

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/bingqiu456/nonebot-plugin-yulu">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-yulu/">nonebot-plugin-yulu</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot

**Comment by yanyongyu** [comment]
插件缺少依赖项

**Comment by bingqiu456** [comment]
你好，现在加了
