### ISSUE TITLE
Plugin: 新冠疫情数据查询

### ISSUE THREAD

**Issue by nicklly** [nonebot/nonebot2#974]
**插件名称：**

国内新冠疫情数据查询

**插件功能：**

查询国内各省份及下属地级市的疫情数据

**PyPI 项目名：**

nonebot-plugin-covid

**插件 import 包名：**

nonebot_plugin_covid

**插件项目仓库/主页链接：**

https://github.com/nicklly/nonebot2_covid_plugin

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 新冠疫情数据查询

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 包 <a href="https://pypi.org/project/nonebot-plugin-covid/">nonebot-plugin-covid</a> 未发布至 PyPI。<dt>请将您的包发布至 PyPI。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/nicklly/nonebot2_covid_plugin">主页</a> 返回状态码 200.</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
