### ISSUE TITLE
Plugin: MockingBird语音

### ISSUE THREAD

**Issue by AkashiCoin** [nonebot/nonebot2#988]
**插件名称：**

MockingBird语音

**插件功能：**

利用MockingBird来生成语音，并支持多种语音切换

**PyPI 项目名：**

nonebot-plugin-mockingbird

**插件 import 包名：**

nonebot_plugin_mockingbird

**插件项目仓库/主页链接：**

https://github.com/AkashiCoin/nonebot_plugin_mockingbird

**标签：**

[{"label":"a:onebot","color":"#000000"}]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: MockingBird语音

**⚠️ 在发布检查过程中，我们发现以下问题:**
<pre><code><li>⚠️ 标签解码失败。<dt>请确保标签格式正确。</dt></li></code></pre>
<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/AkashiCoin/nonebot_plugin_mockingbird">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-mockingbird/">nonebot-plugin-mockingbird</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
