### ISSUE TITLE
Plugin: 百度翻译

### ISSUE THREAD

**Issue by NumberSir** [nonebot/nonebot2#991]
**插件名称：**

百度翻译

**插件功能：**

可以调用百度翻译 API 实现常用语种之间的互译

**PyPI 项目名：**

nonebot-plugin-baidutranslate

**插件 import 包名：**

nonebot_plugin_baidutranslate

**插件项目仓库/主页链接：**

https://github.com/NumberSir/nonebot_plugin_baidutranslate

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 百度翻译

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/NumberSir/nonebot_plugin_baidutranslate">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-baidutranslate/">nonebot-plugin-baidutranslate</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
