### ISSUE TITLE
Plugin: 数据库连接插件

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#994]
**插件名称：**

数据库连接插件

**插件功能：**

使用 tortoise-orm 连接数据库 小白也能轻松优雅的上手！

**PyPI 项目名：**

nonebot-plugin-tortoise-orm

**插件 import 包名：**

nonebot_plugin_tortoise_orm

**插件项目仓库/主页链接：**

https://github.com/kexue-z/nonebot-plugin-tortoise-orm

**标签：**

[]

**Comment by yanyongyu** [comment]
# 📃 商店发布检查结果

> Plugin: 数据库连接插件

**✅ 所有测试通过，一切准备就绪!**

<details><summary>详情</summary><pre><code><li>✅ 项目 <a href="https://github.com/kexue-z/nonebot-plugin-tortoise-orm">主页</a> 返回状态码 200.</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-tortoise-orm/">nonebot-plugin-tortoise-orm</a> 已发布至 PyPI</li></code></pre></details>

---

💪 Powered by NoneBot2 Publish Bot
